### ISSUE TITLE
Unable to start mirth-server-launcher

### ISSUE THREAD

**Issue by abdallahkadour** [nextgenhealthcare/connect#10]
I have downloaded the last version `NextGen Connect 3.8.0` for Windows x64, which is a zip. I unzipped it and tried to start the jar `mirth-server-launcher.jar` as adminstrator. But, I got the following error: 

```cmd
ERROR 2019-08-04 19:52:04,022 [Main Server Thread] com.mirth.connect.server.MirthWebServer: Could not load web app
MultiException[java.io.IOException: Unable to establish loopback connection, java.io.IOException: Unable to establish loopback connection]
        at org.eclipse.jetty.server.Server.doStart(Server.java:383)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com.mirth.connect.server.MirthWebServer.startup(MirthWebServer.java:350)
        at com.mirth.connect.server.Mirth.startWebServer(Mirth.java:386)
        at com.mirth.connect.server.Mirth.startup(Mirth.java:265)
        at com.mirth.connect.server.Mirth.run(Mirth.java:154)
        Suppressed: java.io.IOException: Unable to establish loopback connection
                at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
                at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at sun.nio.ch.PipeImpl.<init>(Unknown Source)
                at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
                at java.nio.channels.Pipe.open(Unknown Source)
                at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
                at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
                at java.nio.channels.Selector.open(Unknown Source)
                at org.eclipse.jetty.io.SelectorManager.newSelector(SelectorManager.java:380)
                at org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:94)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
                at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:258)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
                at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
                at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:279)
                at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
                at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
                at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
                at org.eclipse.jetty.server.Server.doStart(Server.java:398)
                ... 5 more
        Caused by: java.net.SocketException: Permission denied: connect
                at sun.nio.ch.Net.connect0(Native Method)
                at sun.nio.ch.Net.connect(Unknown Source)
                at sun.nio.ch.Net.connect(Unknown Source)
                at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
                at java.nio.channels.SocketChannel.open(Unknown Source)
                at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
                ... 28 more
Caused by: java.io.IOException: Unable to establish loopback connection
        at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
        at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.nio.ch.PipeImpl.<init>(Unknown Source)
        at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
        at java.nio.channels.Pipe.open(Unknown Source)
        at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
        at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
        at java.nio.channels.Selector.open(Unknown Source)
        at org.eclipse.jetty.io.SelectorManager.newSelector(SelectorManager.java:380)
        at org.eclipse.jetty.io.ManagedSelector.doStart(ManagedSelector.java:94)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.io.SelectorManager.doStart(SelectorManager.java:258)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:138)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:108)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:279)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:244)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at org.eclipse.jetty.server.Server.doStart(Server.java:398)
        ... 5 more
Caused by: java.net.SocketException: Permission denied: connect
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.Net.connect(Unknown Source)
        at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
        at java.nio.channels.SocketChannel.open(Unknown Source)
        at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
        ... 28 more
WARN  2019-08-04 19:52:12,559 [Main Server Thread] com.mirth.connect.server.Mirth: Could not start web server
```

Did I miss something? 

Thanks in advance.

**Comment by davutg** [comment]
> ```batchfile
> Caused by: java.net.SocketException: Permission denied: connect
> ```

How did you try to run Mirth as an admin ?  If you opened a cmd window as Administrator, and run > java jar -mirth-server-launcher.jar 

it should work. Even you are an admin in your PC, by default your operations are constrained. You need elevated rights. As MAC users need sudo.
