### ISSUE TITLE
Custom Java libraries no longer work after upgrade.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1033]
After upgrading to most current stable version, all custom libraries no longer work.

Example:  

importPackage(Packages.com.SonicHealth);

During my troubleshooting, I've commented out any other reference to the above package.  Just this single line importing the package exists at this moment.

The following error is displayed in the console.

[2009-01-21 10:43:52,739]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: c339cc4a-709e-4aea-8129-823de3ed72b8: org.mule.umo.routing.RoutingException: Failed to route event via endpoint: null. Message payload is of type: com.webreach.mirth.model.MessageObject
org.mule.umo.routing.RoutingException: Failed to route event via endpoint: null. Message payload is of type: com.webreach.mirth.model.MessageObject
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:84)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:235)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)Caused by: org.mule.umo.routing.CouldNotRouteOutboundMessageException: Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.file.FileConnector@7aa187, endpointUri=file://e:/Interfaces/InboundPDF/RyanWhite/OutBound, transformer=Transformer{name='c339cc4a-709e-4aea-8129-823de3ed72b8_destination_1_transformer', returnClass=false, returnClass=false, sourceTypes=[]}, name='_fileEndpoint#1696205683', type='sender', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@10b841, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: com.webreach.mirth.model.MessageObject
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:63)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	... 16 moreCaused by: org.mule.umo.provider.DispatchException: Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.js.JavaScriptConnector@10f8ee4, endpointUri=js://sink, transformer=Transformer{name='c339cc4a-709e-4aea-8129-823de3ed72b8_destination_2_transformer', returnClass=false, returnClass=false, sourceTypes=[]}, name='_jsEndpoint#308200350', type='sender', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@67e92a, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: com.webreach.mirth.model.MessageObject
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:180)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:52)
	... 19 moreCaused by: org.mule.umo.transformer.TransformerException: 
CHANNEL:
	Binary File Copy
CONNECTOR:
	Encrypt PDF
SCRIPT SOURCE:
	
LINE NUMBER:
	1
DETAILS:
	TypeError: error: '/' should be followed by '>' (com.webreach.mirth.server.MirthJavascriptTransformerException)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:457)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:350)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.getMessageObjectFromEvent(DefaultMessageObjectController.java:624)
	at com.webreach.mirth.connectors.js.JavaScriptMessageDispatcher.doDispatch(JavaScriptMessageDispatcher.java:61)
	at com.webreach.mirth.connectors.js.JavaScriptMessageDispatcher.doSend(JavaScriptMessageDispatcher.java:99)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	... 23 moreCaused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	Binary File Copy
CONNECTOR:
	Encrypt PDF
SCRIPT SOURCE:
	
LINE NUMBER:
	1
DETAILS:
	TypeError: error: '/' should be followed by '>'
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:448)
	... 31 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1029
Reporter: bytemann
Created: 2009-01-21T07:44:39.000-0800

**Comment by rbeckman-nextgen** [comment]
Tried to reproduce this issue with the following steps:

1) Did a clean install of Mirth using the installer
2) Added a custom JAR file to the lib/custom directory
3) Ran the installer again with the same settings

The JAR file was still in the lib/custom directory after the upgrade.



Imported Comment. Original Details:
Author: geraldb
Created: 2009-06-09T11:43:30.000-0700
