### ISSUE TITLE
ReferenceError: "useStrictParser" is not defined

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1037]
I'm trying to create a simple channel HL7v2.x to XML.  I installed Mirth and it was working yesterday. Today, I get the error below.  It turns out that if I replace "useStrictParser" with true, then I get error on the next parameter in the method, and so on.  I deleted the channel and recreated it with on luck.  I uninstalled Mirth and reinstalled with no luck.  I could go back to my original VMWare image (clean install) and try again.  However, it seems like there's an startup/initialization problem.  Questions/Comments?  Thank you.

[2009-01-30 15:42:54,210]  ERROR (com.webreach.mirth.server.util.JavaScriptUtil:116): Error executing Deploy script.
com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	newChannel
SCRIPT SOURCE:
	Deploy
LINE NUMBER:
	3
DETAILS:
	ReferenceError: "useStrictParser" is not defined.
	at com.webreach.mirth.server.util.JavaScriptUtil.executeScript(JavaScriptUtil.java:146)
	at com.webreach.mirth.server.util.JavaScriptUtil.executeScript(JavaScriptUtil.java:109)
	at com.webreach.mirth.server.controllers.DefaultConfigurationController.executeChannelDeployScripts(DefaultConfigurationController.java:400)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:248)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:208)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:138)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1033
Reporter: pomeroy8
Created: 2009-01-30T12:54:27.000-0800

**Comment by rbeckman-nextgen** [comment]
If you are using code like...

SerializerFactory.getHL7Serializer(useStrictParser, useStrictValidation, handleRepetitions).toXML(message);
default xml namespace = new Namespace('urn:hl7-org:v2xml');

...then you need to replace useStrictParser, useStrictValidation, and handleRepetitions with appropriate boolean values.  These are the changeable properties for the HL7v2.x serializer.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-05-15T14:05:18.000-0700
