### ISSUE TITLE
Database Reader generates errors selecting multiple columns from a single table in a SQL 2005 database when one of those columns is of type TEXT.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1075]
Using a Database Reader to select multiple columns from a SQL 2005 database, one of which is of type TEXT, causes an error when database polling begins.  

I have a database reader which reads from a SQL 2005 database using the following query.

I have a database reader which reads from a SQL 2005 database using the following query.

Code:
SELECT OutgoingMessageID,RawData FROM OutgoingMessage

OutgoingMessageID's type is unique identifier, and RawData's is TEXT (this field contains an entire HL7 v2 message).

When this channel starts polling, I get the following error:

Code:
INFO   | jvm 1    | 2009/04/08 08:54:54 | ERROR 2009-04-08 08:54:54,690 [cd837093-5930-4e9e-984f-925d96ce5870_source_connector._jdbcEndpoint#-1243393496.receiver.2] org.mule.impl.DefaultComponentExceptionStrategy: Caught exception in Exception Strategy for: cd837093-5930-4e9e-984f-925d96ce5870: org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.jdbc.JdbcConnector@1db9433, endpointUri=jdbc://query, transformer=Transformer{name='ResultMapToXML', returnClass=false, returnClass=false, sourceTypes=[interface java.util.Map, class java.lang.String]}, name='_jdbcEndpoint#-1243393496', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1e0eeb9, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: org.apache.commons.dbutils.BasicRowProcessor$CaseInsensitiveHashMap
INFO   ]( jvm 1    | 2009/04/08 08:54:54 | org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.jdbc.JdbcConnector@1db9433, endpointUri=jdbc://query, transformer=Transformer{name='ResultMapToXML', returnClass=false, returnClass=false, sourceTypes=[interface java.util.Map, class java.lang.String)}, name='_jdbcEndpoint#-1243393496', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1e0eeb9, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: org.apache.commons.dbutils.BasicRowProcessor$CaseInsensitiveHashMap
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:235)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at com.webreach.mirth.connectors.jdbc.JdbcMessageReceiver.processMessage(JdbcMessageReceiver.java:171)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.providers.TransactedPollingMessageReceiver$MessageProcessorWorker.doInTransaction(TransactedPollingMessageReceiver.java:159)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:72)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.providers.TransactedPollingMessageReceiver$MessageProcessorWorker.run(TransactedPollingMessageReceiver.java:149)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2009/04/08 08:54:54 | Caused by: org.mule.umo.transformer.TransformerException: Failed to parse result map
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at com.webreach.mirth.server.mule.transformers.ResultMapToXML.doTransform(ResultMapToXML.java:110)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
INFO   | jvm 1    | 2009/04/08 08:54:54 | 	... 12 more

The unusual thing is that if I select only the RawData column the channel does not produce errors. The error only occurs when selecting multiple columns (of any type) in that query.

The only workaround I've found, at this point, is to use SQL SERVER's CAST function to cast the RawData TEXT column to type VARCHAR(MAX).

Code:
SELECT OutgoingMessageID AS OutgoingMessage_OutgoingMessageID, CAST(OutgoingMessage.RawData as varchar(MAX)) AS OutgoingMessage_RawData FROM OutgoingMessage

When I use this, everything works again. The message is processed, and sent out successfully via an LLP Sender. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1071
Reporter: jordan_s
Created: 2009-04-14T13:59:31.000-0700

**Comment by rbeckman-nextgen** [comment]
You can also cast to CLOB, which is more appropriate when coming from TEXT.  This likely relates to the jtds driver we are using for jdbc.  If this is replaced with a proprietary sql server jdbc driver, the issue might be fixed.  Since we cannot package a different driver, you should use the cast workaround.  Upgrading the jtds jar to 1.2.2 did not seem to fix the issue.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-05-18T15:31:19.000-0700

**Comment by rbeckman-nextgen** [comment]
this is a bug that can be fixed - it is (probably) not due to the jdbc driver

create table #x (MessageID INT, MessageXML XML)
insert into #x (1, '<root />')

mirth database reader connector does select MessageID, MessageXML from #x  ..

com.webreach.mirth.server.mule.transformers.ResultMapToXML  gets the data and starts looping through the result set..

First, it gets the xml column back as a clob, reads it and adds it to the dom, so far so good - I thought this is where it would fail, but the xml type is supported. =)

Then it goes and gets the next key from the result set, and tries to create an element in the target doc using the key name.  Well, this is the point of failure

				String key = (String) iter.next();
				Element child = document.createElement(key);

boom
INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 

And a separate bug exists such that the root cause (this message) is lost in the wrapper exception and never logged.  (You never see the invalid character err.. - this is far too common, wrap and through, root cause never gets logged.... grr)

Anyway, the keyset for the resultset has,

dataSet.keySet() = [outboundmessagequeue.messagexml, .messageid]

the second key for some reason is missing the outboundmessagequeue prefix, and the "." there is your invalid character error.  

If I change the value of key in the debugger to outboundmessagequeue.messageid, it works fine.  But trying to create an xml element that starts with . does not go over well.  So, what is happening, why is that part missing, and what do we have to do to get this to work?

Imported Comment. Original Details:
Author: john.newman
Created: 2010-07-15T08:07:02.000-0700

**Comment by rbeckman-nextgen** [comment]
tracing further upstream, it looks like the source message from the jdbc driver  has

outboundmessage.messagexml, .messageid

so it's not like some mirth transformer is doing that or anything like that..

now if i apply the suggested workaround and cast it to nvarchar(max), the jdbc driver sends back

{messageid=1, messagexml=javax.sql.rowset.serial.SerialClob@796ec83e}

which of course works fine.  So I guess it probably is an issue with JTDS,  hmm

Imported Comment. Original Details:
Author: john.newman
Created: 2010-07-15T08:17:38.000-0700

**Comment by rbeckman-nextgen** [comment]
OK with a simple test case I can see that JTDS has the "tableName" value set on the result set for the xml column, but not the int column.

Adding the cast to nvarchar(max), the table name is left out in both cases.  So this IS an issue with the jdbc driver and not any code within mirth.  This should remain closed, sorry for the noise.  I will see if I can get something filed with the jtds project, but I think that code is dead or frozen..

Imported Comment. Original Details:
Author: john.newman
Created: 2010-07-15T08:32:43.000-0700

**Comment by rbeckman-nextgen** [comment]
http://sourceforge.net/tracker/index.php?func=detail&aid=1339303&group_id=33291&atid=407762



This is not a jTDS issue, but rather a SQL Server
limitation. You'll see that even with the MS driver, if you
specify selectMethod=direct rather than cursor, you'll get
the exact same behavior. When using direct result sets (aka
firehose cursors) SQL Server does not return complete
metadata information, for performance reasons (keeping the
size of metadata at a minimum).  < ding ding ding

You can achieve similar behavior (including lower
performance) as the MS driver if you specify
"useCursors=true" in your connection URL. This will create
cursors for all SELECT queries and extra network requests
will have to be done to fetch data. It's your choice.

Or you can append "FOR BROWSE" to all your SELECT statements
to force SQL Server to always return complete metadata, even
for firehose cursors. But that will make your application
non-portable accross databases. Again, your choice.

...

Alin.




Imported Comment. Original Details:
Author: john.newman
Created: 2010-07-15T08:51:59.000-0700

**Comment by rbeckman-nextgen** [comment]
The reason this issue occurs is because BasicRowProcessor.toMap scans the columns in the result set to determine if multiple tables are being selected from. Due to the SQL Server limitation described above, it may not be able to read the table names for some columns. If so, it then assumes that multiple tables are represented and attempts to prefix the resultMap column names with the table names. Since the table name is blank for some column(s), it attempts to put ".columnName" in the result map which produces the "invalid or illegal XML character" error.

Version 3.0.0 erroneously did not include the table name prefix behavior when multiple tables were being selected from, which ended up masking this issue in that version.

We can fix this issue by modifying BasicRowProcessor to not treat the blank table names as a distinct table. However, this error could still occur when selecting from multiple tables.

Imported Comment. Original Details:
Author: brentm
Created: 2014-01-17T10:39:42.000-0800

**Comment by rbeckman-nextgen** [comment]
Related forum threads:

http://www.mirthcorp.com/community/forums/showthread.php?t=9811
http://www.mirthcorp.com/community/forums/showthread.php?p=36839
http://www.mirthcorp.com/community/forums/showthread.php?t=9881

Imported Comment. Original Details:
Author: brentm
Created: 2014-01-17T10:41:55.000-0800

**Comment by rbeckman-nextgen** [comment]
May want to address MIRTH-2340 at the same time.

Imported Comment. Original Details:
Author: brentm
Created: 2014-01-17T13:06:17.000-0800

**Comment by rbeckman-nextgen** [comment]
We will no longer be checking tablename at all when creating the result set XML. This has a few implications.

1. We never use the tablename in XML element anymore regardless of how many tables are included in the query. We always use just the column name or the alias if it exists. To make sure there are no conflicts, aliases should always be used when possible.
2. If there is a conflict in the name/alias of two columns (regardless of how many tables there are), the channel will throw an exception when reading and a unique alias must be added. This will change in the future (MIRTH-3138)
3. It should no longer be necessary to set useCursors because an error will no longer be thrown if the table name is missing.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-03-31T11:00:43.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that the table name is never used in the generated XML anymore. Also when duplicate column labels are detected, the poll fails and an exception is thrown to the server log.

It's good that an exception is thrown and no messages are actually processed, rather than the previous behavior of just overwriting values with the same keys. MIRTH-3138 will address actually allowing multiple values per key/alias.

Imported Comment. Original Details:
Author: narupley
Created: 2014-04-02T12:04:32.000-0700

**Comment by rbeckman-nextgen** [comment]
I am getting this error in 3.4.2.  What is the Mirth suggested workaround for this issue?

Imported Comment. Original Details:
Author: kirbykn2
Created: 2017-03-02T05:36:14.000-0800
