### ISSUE TITLE
Implement a better error handling for Code Template - Function.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1085]
When using Code Template - Function type, and the content of the function is not wrapped with its function {} stub, none of the channels can be deployed with a series of very ambiguous and misleading errors pointing to the channel's source Filter/Transformer code.

ERROR (com.webreach.mirth.server.mule.transformers.JavaScriptTransformer:249): ERROR-300: Transformer error
com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	Test 
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	Filter/Transformer
LINE NUMBER:
	4
LINE SOURCE:
	
	return true;
DETAILS:
	invalid return
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.initialise(JavaScriptTransformer.java:246)
	at org.mule.MuleManager.registerTransformer(MuleManager.java:564)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:216)
	at org.apache.commons.digester.SetRootRule.end(SetRootRule.java:209)
	at org.apache.commons.digester.Rule.end(Rule.java:230)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1130)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1685)
	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:250)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:208)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:138)

ERROR (org.apache.commons.digester.Digester:1132): End event threw exception
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:216)
	at org.apache.commons.digester.SetRootRule.end(SetRootRule.java:209)
	at org.apache.commons.digester.Rule.end(Rule.java:230)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1130)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1685)
	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:250)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:208)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:138)Caused by: org.mule.umo.lifecycle.InitialisationException: Initialisation Failure: 
CHANNEL:
	Test
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	Filter/Transformer
LINE NUMBER:
	4
LINE SOURCE:
	
	return true;
DETAILS:
	invalid return
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.initialise(JavaScriptTransformer.java:250)
	at org.mule.MuleManager.registerTransformer(MuleManager.java:564)
	... 24 moreCaused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	Test
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	Filter/Transformer
LINE NUMBER:
	4
LINE SOURCE:
	
	return true;
DETAILS:
	invalid return
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.initialise(JavaScriptTransformer.java:246)
	... 25 more
	
		
	
WARN  (com.webreach.mirth.server.Mirth:253): Error deploying channels.
org.mule.config.ConfigurationException: Failed to parse configuration resource "C:\Program Files\Mirth\conf\mule-config.xml" (org.mule.config.ConfigurationException)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:196)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:250)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:208)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:138)Caused by: org.mule.config.ConfigurationException: Failed to parse configuration resource "C:\Program Files\Mirth\conf\mule-config.xml"
	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:121)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
	... 3 moreCaused by: org.mule.umo.lifecycle.InitialisationException: Initialisation Failure: 
CHANNEL:
	Test 
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	Filter/Transformer
LINE NUMBER:
	4
LINE SOURCE:
	
	return true;
DETAILS:
	invalid return
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2919)
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2945)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1133)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1685)
	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
	... 5 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1081
Reporter: chrisr
Created: 2009-05-06T10:02:57.000-0700

**Comment by rbeckman-nextgen** [comment]
Changing the priority to 'Major' due to the severity of the effects this issue causes.

Imported Comment. Original Details:
Author: chrisr
Created: 2009-05-06T10:07:06.000-0700

**Comment by rbeckman-nextgen** [comment]
To eliminate the possible confusion, provided a default code snippet for Function type.

Imported Comment. Original Details:
Author: chrisr
Created: 2009-05-06T16:51:23.000-0700

**Comment by rbeckman-nextgen** [comment]
This is a great request. I've put try-catch blocks in a large number of functions just so I can generate sensible error messages before re-throwing.

Imported Comment. Original Details:
Author: colinsj
Created: 2009-07-09T10:09:42.000-0700
