### ISSUE TITLE
ArrayIndexOutOfBoundsException:1 while converting CSV (Delimitted Text) file to HL7 Message

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1086]
We have created a channel for converting values from CSV (delimited text) file to HL7 message. Firsttime when we have deployed and tested, it has worked very well. However then we have selected the 'Handle Repetition' check-box in the outbound template Properties window and deployed and tested, it has given below error:

ERROR-300: Transformer error
ERROR MESSAGE:	Error evaluating transformer
com.webreach.mirth.model.converters.SerializerException: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:195)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:50)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:438)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:350)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.getMessageObjectFromEvent(DefaultMessageObjectController.java:624)
	at com.webreach.mirth.connectors.file.FileMessageDispatcher.doDispatch(FileMessageDispatcher.java:65)
	at com.webreach.mirth.connectors.file.FileMessageDispatcher.doSend(FileMessageDispatcher.java:144)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:235)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at com.webreach.mirth.model.converters.ER7XMLHandler.startElement(ER7XMLHandler.java:111)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:190)
	... 33 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1082
Reporter: yogesh_puranik
Created: 2009-05-07T02:56:40.000-0700

**Comment by rbeckman-nextgen** [comment]
We have also tried by deleting the existing channel as well as source file. Then restarted the MIRTH service also, but everytime it has given the same error. 

Please help, its very urgent.

Imported Comment. Original Details:
Author: yogesh_puranik
Created: 2009-05-07T02:58:52.000-0700

**Comment by rbeckman-nextgen** [comment]
Will need more information, including the channel and sample messages without any patient data in them.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-05-15T13:11:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Sounds like a channel configuration issue.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-06-01T11:47:48.000-0700
