### ISSUE TITLE
SOAP Listener fails for data with more than 32768 bytes

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1094]
The SOAP Listener can't accept inptus with more than 32768 bytes. The next exception is launched;

_soapConnector#12941627.soap:Mirth.receiver.5] org.mule.impl.DefaultExceptionStrategy: Caught exception in Exception Strategy: null
java.lang.IndexOutOfBoundsException
        at java.io.PushbackInputStream.read(PushbackInputStream.java:143)
        at org.apache.commons.httpclient.ChunkedInputStream.read(ChunkedInputStream.java:181)
        at org.mule.providers.http.HttpMessageReceiver.parseRequest(HttpMessageReceiver.java:276)
        at org.mule.providers.http.HttpMessageReceiver$HttpWorker.run(HttpMessageReceiver.java:113)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Thread.java:613)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1091
Reporter: albertosaez
Created: 2009-05-15T17:43:00.000-0700

**Comment by rbeckman-nextgen** [comment]
HttpMessageReceiver which overrites Mule original 

This class change the chunked part of the parseRequest method

Imported Comment. Original Details:
Author: albertosaez
Created: 2009-05-15T17:47:35.000-0700

**Comment by rbeckman-nextgen** [comment]
wsSender sends large data using a WS. Simply send generic xml to init the transfer.
wsReceiver is a simple ws receiver which converts the input string into a XML document.

The transformer in the WSSender creates a large message. If you change the for limit to 8, the message is processed fine, but for a 9 limit it fails.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-06-10T16:38:27.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed mule bug that only allowed chunked data of 32kb because of a buffer offset error.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-06-10T17:30:34.000-0700
