### ISSUE TITLE
Bug on upgrade on MS SQL 2005 DB in 1.8.1.4193

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1123]
Misspelling on table in script.

[2009-06-12 10:29:26,613]  ERROR (com.webreach.mirth.server.util.DatabaseUtil:135): Error was encountered and ignored while executing statement: ALTER TABLE PREFERNECES ALTER COLUMN VALUE TEXT
java.sql.SQLException: Cannot find the object "PREFERNECES" because it does not exist or you do not have permissions.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:365)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2781)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2224)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:628)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:525)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:487)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeImpl(JtdsStatement.java:664)
	at net.sourceforge.jtds.jdbc.JtdsStatement.execute(JtdsStatement.java:1114)
	at com.webreach.mirth.server.util.DatabaseUtil.executeScript(DatabaseUtil.java:129)
	at com.webreach.mirth.server.controllers.DefaultMigrationController.migrate(DefaultMigrationController.java:323)
	at com.webreach.mirth.server.controllers.DefaultMigrationController.migrate(DefaultMigrationController.java:150)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:169)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:130)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1120
Reporter: wcombs
Created: 2009-06-12T07:39:06.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed typos in sql server upgrade scripts.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-06-12T10:42:13.000-0700
