### ISSUE TITLE
Calling web service with integrated windows authentication security does not work when obtaining wsdl information with  ntlm security is OK

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1125]
Calling web service report error 401.2 when invoking the wsdl works fine
sniffing the web service call appears with basic security instead of NTLM
the URI of both wsdl URI and web service endpoint URI includes something in the form  <http://domain%5Cuser:password@ip/webservice> (%5C is '\')

The web service is published with integrated windows authentication

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1122
Reporter: nachoiec
Created: 2009-06-14T22:19:41.000-0700

**Comment by rbeckman-nextgen** [comment]
The error that reports IIS is 
ERROR-410: SOAP Connector error
ERROR MESSAGE:	Error invoking WebService
AxisFault
 faultCode: {http://xml.apache.org/axis/}HTTP
 faultSubcode: 
 faultString: (401)Unauthorized
 faultActor: 
 faultNode: 
 faultDetail: 
	{}:return code:  401
&lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01//EN&quot; &quot;http://www.w3.org/TR/html4/strict.dtd&quot;&gt;
&lt;HTML&gt;&lt;HEAD&gt;&lt;TITLE&gt;You are not authorized to view this page&lt;/TITLE&gt;
&lt;META HTTP-EQUIV=&quot;Content-Type&quot; Content=&quot;text/html; charset=Windows-1252&quot;&gt;
&lt;STYLE type=&quot;text/css&quot;&gt;
  BODY { font: 8pt/12pt verdana }
  H1 { font: 13pt/15pt verdana }
  H2 { font: 8pt/12pt verdana }
  A:link { color: red }
  A:visited { color: maroon }
&lt;/STYLE&gt;
&lt;/HEAD&gt;&lt;BODY&gt;&lt;TABLE width=500 border=0 cellspacing=10&gt;&lt;TR&gt;&lt;TD&gt;

&lt;h1&gt;You are not authorized to view this page&lt;/h1&gt;
You do not have permission to view this directory or page using the credentials that you supplied because your Web browser is sending a WWW-Authenticate header field that the Web server is not configured to accept.
&lt;hr&gt;
&lt;p&gt;Please try the following:&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;Contact the Web site administrator if you believe you should be able to view this directory or page.&lt;/li&gt;
&lt;li&gt;Click the &lt;a href=&quot;javascript:location.reload()&quot;&gt;Refresh&lt;/a&gt; button to try again with different credentials.&lt;/li&gt;
&lt;/ul&gt;
&lt;h2&gt;HTTP Error 401.2 - Unauthorized: Access is denied due to server configuration.&lt;br&gt;Internet Information Services (IIS)&lt;/h2&gt;
&lt;hr&gt;
&lt;p&gt;Technical Information (for support personnel)&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;Go to &lt;a href=&quot;http://go.microsoft.com/fwlink/?linkid=8180&quot;&gt;Microsoft Product Support Services&lt;/a&gt; and perform a title search for the words &lt;b&gt;HTTP&lt;/b&gt; and &lt;b&gt;401&lt;/b&gt;.&lt;/li&gt;
&lt;li&gt;Open &lt;b&gt;IIS Help&lt;/b&gt;, which is accessible in IIS Manager (inetmgr),
 and search for topics titled &lt;b&gt;About Security&lt;/b&gt;, &lt;b&gt;Authentication&lt;/b&gt;, and &lt;b&gt;About Custom Error Messages&lt;/b&gt;.&lt;/li&gt;
&lt;/ul&gt;

&lt;/TD&gt;&lt;/TR&gt;&lt;/TABLE&gt;&lt;/BODY&gt;&lt;/HTML&gt;

	{http://xml.apache.org/axis/}HttpErrorCode:401

(401)Unauthorized
	at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:744)
	at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:1870)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.invokeWebService(AxisMessageDispatcher.java:278)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.doSend(AxisMessageDispatcher.java:315)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:178)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)



Imported Comment. Original Details:
Author: nachoiec
Created: 2009-06-15T05:54:12.000-0700

**Comment by rbeckman-nextgen** [comment]
Adding this file to the ./conf directory in the mirth installation path results in a problem solution.

With this file the proccess of calling a Web service uses the apache http client instead sun client.

Thanks to Alberto Saez for this solution!!!

My be this file included in Mirth distributions???


Imported Comment. Original Details:
Author: nachoiec
Created: 2009-06-30T03:22:36.000-0700

**Comment by rbeckman-nextgen** [comment]
I have the same issue in 3.4.2

HTTP Sender error
ERROR MESSAGE: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>401 - Unauthorized: Access is denied due to invalid credentials.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>401 - Unauthorized: Access is denied due to invalid credentials.</h2>
  <h3>You do not have permission to view this directory or page using the credentials that you supplied.</h3>
 </fieldset></div>
</div>
</body>
</html>


Imported Comment. Original Details:
Author: nawaf
Created: 2017-04-26T10:35:38.000-0700

**Comment by carm-afea** [comment]
> Adding this file to the ./conf directory in the mirth installation path results in a problem solution.

Pardon me if the answer is obvious, but what file needs to be added to the conf directory?
