### ISSUE TITLE
SOAP Response doesn't have correct namespace

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1152]
SOAP Listener response doesn't have correct namespace, it should be "http://components.mule.server.mirth.webreach.com"

Here's the response I received:
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><ns1:acceptMessageResponse soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:ns1="http://DefaultNamespace"><acceptMessageReturn xsi:type="xsd:string">Message: c623c22f-a90c-463e-85c7-9b123532859a has been successfully received</acceptMessageReturn></ns1:acceptMessageResponse></soapenv:Body></soapenv:Envelope>

Error message from Metro:
javax.xml.ws.WebServiceException: Unexpected response element {http://DefaultNamespace}acceptMessageResponse expected: {http://components.mule.server.mirth.webreach.com}acceptMessageResponse
	at com.sun.xml.ws.client.sei.ResponseBuilder$RpcLit.readResponse(ResponseBuilder.java:614)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:121)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:118)
	at $Proxy34.acceptMessage(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1150
Reporter: teru
Created: 2009-07-21T13:50:15.000-0700

**Comment by rbeckman-nextgen** [comment]
This should have been resolved as a part of MIRTH-1246

Imported Comment. Original Details:
Author: jacobb
Created: 2010-05-27T14:29:59.000-0700
