### ISSUE TITLE
DICOM Sender does not work in Java 1.6

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1162]
The DICOM Sender does not work properly on Java 1.6 (only Java 1.5).  Trying to send a DICOM message results in a MessageObject exception:

ERROR 2009-08-13 10:41:19,019 [25f03039-4a53-405b-a4fd-c726ebc82ef9_destination_1_connector.88d501b0-5149-42d8-a3e7-3b6a083abb24.receiver.1] org.mule.impl.DefaultComponentExceptionStrategy: Caught exception in Exception Strategy for: 88d501b0-5149-42d8-a3e7-3b6a083abb24: org.mule.umo.routing.RoutingException: Failed to route event via endpoint: null. Message payload is of type: com.webreach.mirth.model.MessageObject
org.mule.umo.routing.RoutingException: Failed to route event via endpoint: null. Message payload is of type: com.webreach.mirth.model.MessageObject
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:84)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:178)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.mule.umo.routing.CouldNotRouteOutboundMessageException: Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.dimse.DICOMConnector@135a16a, endpointUri=dicom://127.0.0.1:104, transformer=Transformer{name='88d501b0-5149-42d8-a3e7-3b6a083abb24_destination_1_transformer', returnClass=false, returnClass=false, sourceTypes=[]}, name='_dicomEndpoint#326168120', type='sender', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@b4c33, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: com.webreach.mirth.model.MessageObject
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:63)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	... 16 more
Caused by: org.mule.umo.provider.DispatchException: Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.dimse.DICOMConnector@135a16a, endpointUri=dicom://127.0.0.1:104, transformer=Transformer{name='88d501b0-5149-42d8-a3e7-3b6a083abb24_destination_1_transformer', returnClass=false, returnClass=false, sourceTypes=[]}, name='_dicomEndpoint#326168120', type='sender', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@b4c33, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: com.webreach.mirth.model.MessageObject
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:180)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	... 19 more
Caused by: java.io.IOException: The system cannot find the path specified
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.checkAndCreate(Unknown Source)
	at java.io.File.createTempFile(Unknown Source)
	at java.io.File.createTempFile(Unknown Source)
	at com.webreach.mirth.connectors.dimse.DICOMMessageDispatcher.doSend(DICOMMessageDispatcher.java:51)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	... 23 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1161
Reporter: jacobb
Created: 2009-08-13T10:54:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Set the tempdir property on the JVM.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-09-10T13:29:01.000-0700

**Comment by rbeckman-nextgen** [comment]
Test to make sure this still works in Windows Vista when running Mirth as a service.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-09-24T17:13:25.000-0700

**Comment by rbeckman-nextgen** [comment]
Creating a temp directory in the Mirth home directory and setting it to be the system temp dir fixed DICOM issues when running Mirth as a service.  The temp directory can be changed in mirth.properties

Imported Comment. Original Details:
Author: jacobb
Created: 2009-09-25T16:07:51.000-0700
