### ISSUE TITLE
Error Logging Message

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1178]
HL7 Message are returning an error to the sender - This is happening about 4 times a day.  Here's the most recent error:

[2009-09-08 10:09:05,554]  ERROR (com.webreach.mirth.server.controllers.DefaultMessageObjectController:205): could not log message: id=66316f84-ede9-4aac-b886-f91beac49b67
com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in derby/derby-message.xml.  
--- The error occurred while executing update.  
--- Check the  
	
	INSERT INTO 
	
	MESSAGE (ID, SERVER_ID, CHANNEL_ID, SOURCE, TYPE, DATE_CREATED, VERSION, IS_ENCRYPTED, STATUS, RAW_DATA, RAW_DATA_PROTOCOL, TRANSFORMED_DATA, TRANSFORMED_DATA_PROTOCOL, ENCODED_DATA, ENCODED_DATA_PROTOCOL, CONNECTOR_NAME, ERRORS, CORRELATION_ID, CONNECTOR_MAP, CHANNEL_MAP, RESPONSE_MAP, ATTACHMENT) 
	
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
	.  
--- Check the SQL Statement (preparation failed).  
--- Cause: java.sql.SQLTransactionRollbackException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SYSCONGLOMERATES, (5,15)
  Waiting XID : {13736911, S} , APP,  
	
	INSERT INTO 
	
	MESSAGE (ID, SERVER_ID, CHANNEL_ID, SOURCE, TYPE, DATE_CREATED, VERSION, IS_ENCRYPTED, STATUS, RAW_DATA, RAW_DATA_PROTOCOL, TRANSFORMED_DATA, TRANSFORMED_DATA_PROTOCOL, ENCODED_DATA, ENCODED_DATA_PROTOCOL, CONNECTOR_NAME, ERRORS, CORRELATION_ID, CONNECTOR_MAP, CHANNEL_MAP, RESPONSE_MAP, ATTACHMENT) 
	
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
	
  Granted XID : {13715252, S} 
Lock : ROW, SYSCONGLOMERATES, (5,14)
  Waiting XID : {13715252, X} , APP, alter table "APP"."MESSAGE" compress
  Granted XID : {13715252, S} , {13736911, S} 
. The selected victim is XID : 13736911.
Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SYSCONGLOMERATES, (5,15)
  Waiting XID : {13736911, S} , APP,  
	
	INSERT INTO 
	
	MESSAGE (ID, SERVER_ID, CHANNEL_ID, SOURCE, TYPE, DATE_CREATED, VERSION, IS_ENCRYPTED, STATUS, RAW_DATA, RAW_DATA_PROTOCOL, TRANSFORMED_DATA, TRANSFORMED_DATA_PROTOCOL, ENCODED_DATA, ENCODED_DATA_PROTOCOL, CONNECTOR_NAME, ERRORS, CORRELATION_ID, CONNECTOR_MAP, CHANNEL_MAP, RESPONSE_MAP, ATTACHMENT) 
	
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
	
  Granted XID : {13715252, S} 
Lock : ROW, SYSCONGLOMERATES, (5,14)
  Waiting XID : {13715252, X} , APP, alter table "APP"."MESSAGE" compress
  Granted XID : {13715252, S} , {13736911, S} 
. The selected victim is XID : 13736911.
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:91)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.writeMessageToDatabase(DefaultMessageObjectController.java:202)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.updateMessage(DefaultMessageObjectController.java:177)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setStatus(DefaultMessageObjectController.java:725)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setSuccess(DefaultMessageObjectController.java:657)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.manageResponseAck(MllpMessageDispatcher.java:372)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.doDispatch(MllpMessageDispatcher.java:211)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.doSend(MllpMessageDispatcher.java:246)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.soap.ServiceProxy$AxisServiceHandler.invoke(ServiceProxy.java:161)
	at com.webreach.mirth.connectors.soap.axis.extensions.MuleProvider.invokeMethod(MuleProvider.java:72)
	at org.apache.axis.providers.java.RPCProvider.processMessage(RPCProvider.java:186)
	at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:323)
	at com.webreach.mirth.connectors.soap.axis.extensions.MuleProvider.invoke(MuleProvider.java:93)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	at org.apache.axis.handlers.soap.SOAPService.invoke(SOAPService.java:454)
	at org.apache.axis.server.AxisServer.invoke(AxisServer.java:281)
	at com.webreach.mirth.connectors.soap.axis.AxisServiceComponent.doPost(AxisServiceComponent.java:523)
	at com.webreach.mirth.connectors.soap.axis.AxisServiceComponent.onCall(AxisServiceComponent.java:135)
	at sun.reflect.GeneratedMethodAccessor674.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mule.model.DynamicEntryPoint.invokeCurrent(DynamicEntryPoint.java:168)
	at org.mule.model.DynamicEntryPoint.invoke(DynamicEntryPoint.java:90)
	at org.mule.impl.DefaultLifecycleAdapter.onCall(DefaultLifecycleAdapter.java:177)
	at org.mule.impl.DefaultLifecycleAdapter.intercept(DefaultLifecycleAdapter.java:232)
	at org.mule.impl.InterceptorsInvoker.execute(InterceptorsInvoker.java:53)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:230)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at org.mule.providers.http.HttpMessageReceiver$HttpWorker.run(HttpMessageReceiver.java:145)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SYSCONGLOMERATES, (5,15)
  Waiting XID : {13736911, S} , APP,  
	
	INSERT INTO 
	
	MESSAGE (ID, SERVER_ID, CHANNEL_ID, SOURCE, TYPE, DATE_CREATED, VERSION, IS_ENCRYPTED, STATUS, RAW_DATA, RAW_DATA_PROTOCOL, TRANSFORMED_DATA, TRANSFORMED_DATA_PROTOCOL, ENCODED_DATA, ENCODED_DATA_PROTOCOL, CONNECTOR_NAME, ERRORS, CORRELATION_ID, CONNECTOR_MAP, CHANNEL_MAP, RESPONSE_MAP, ATTACHMENT) 
	
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
	
  Granted XID : {13715252, S} 
Lock : ROW, SYSCONGLOMERATES, (5,14)
  Waiting XID : {13715252, X} , APP, alter table "APP"."MESSAGE" compress
  Granted XID : {13715252, S} , {13736911, S} 
. The selected victim is XID : 13736911.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.ibatis.common.jdbc.SimpleDataSource$SimplePooledConnection.invoke(SimpleDataSource.java:958)
	at $Proxy6.prepareStatement(Unknown Source)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.prepareStatement(SqlExecutor.java:494)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:76)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
	... 61 moreCaused by: java.sql.SQLException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SYSCONGLOMERATES, (5,15)
  Waiting XID : {13736911, S} , APP,  
	
	INSERT INTO 
	
	MESSAGE (ID, SERVER_ID, CHANNEL_ID, SOURCE, TYPE, DATE_CREATED, VERSION, IS_ENCRYPTED, STATUS, RAW_DATA, RAW_DATA_PROTOCOL, TRANSFORMED_DATA, TRANSFORMED_DATA_PROTOCOL, ENCODED_DATA, ENCODED_DATA_PROTOCOL, CONNECTOR_NAME, ERRORS, CORRELATION_ID, CONNECTOR_MAP, CHANNEL_MAP, RESPONSE_MAP, ATTACHMENT) 
	
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
	
  Granted XID : {13715252, S} 
Lock : ROW, SYSCONGLOMERATES, (5,14)
  Waiting XID : {13715252, X} , APP, alter table "APP"."MESSAGE" compress
  Granted XID : {13715252, S} , {13736911, S} 
. The selected victim is XID : 13736911.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 83 more
Caused by: java.sql.SQLTransactionRollbackException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SYSCONGLOMERATES, (5,15)
  Waiting XID : {13736911, S} , APP,  
	
	INSERT INTO 
	
	MESSAGE (ID, SERVER_ID, CHANNEL_ID, SOURCE, TYPE, DATE_CREATED, VERSION, IS_ENCRYPTED, STATUS, RAW_DATA, RAW_DATA_PROTOCOL, TRANSFORMED_DATA, TRANSFORMED_DATA_PROTOCOL, ENCODED_DATA, ENCODED_DATA_PROTOCOL, CONNECTOR_NAME, ERRORS, CORRELATION_ID, CONNECTOR_MAP, CHANNEL_MAP, RESPONSE_MAP, ATTACHMENT) 
	
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
	
  Granted XID : {13715252, S} 
Lock : ROW, SYSCONGLOMERATES, (5,14)
  Waiting XID : {13715252, X} , APP, alter table "APP"."MESSAGE" compress
  Granted XID : {13715252, S} , {13736911, S} 
. The selected victim is XID : 13736911.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.ibatis.common.jdbc.SimpleDataSource$SimplePooledConnection.invoke(SimpleDataSource.java:958)
	at $Proxy6.prepareStatement(Unknown Source)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.prepareStatement(SqlExecutor.java:494)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:76)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.writeMessageToDatabase(DefaultMessageObjectController.java:202)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.updateMessage(DefaultMessageObjectController.java:177)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setStatus(DefaultMessageObjectController.java:725)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setSuccess(DefaultMessageObjectController.java:657)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.manageResponseAck(MllpMessageDispatcher.java:372)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.doDispatch(MllpMessageDispatcher.java:211)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.doSend(MllpMessageDispatcher.java:246)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.soap.ServiceProxy$AxisServiceHandler.invoke(ServiceProxy.java:161)
	at com.webreach.mirth.connectors.soap.axis.extensions.MuleProvider.invokeMethod(MuleProvider.java:72)
	at org.apache.axis.providers.java.RPCProvider.processMessage(RPCProvider.java:186)
	at org.apache.axis.providers.java.JavaProvider.invoke(JavaProvider.java:323)
	at com.webreach.mirth.connectors.soap.axis.extensions.MuleProvider.invoke(MuleProvider.java:93)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	at org.apache.axis.handlers.soap.SOAPService.invoke(SOAPService.java:454)
	at org.apache.axis.server.AxisServer.invoke(AxisServer.java:281)
	at com.webreach.mirth.connectors.soap.axis.AxisServiceComponent.doPost(AxisServiceComponent.java:523)
	at com.webreach.mirth.connectors.soap.axis.AxisServiceComponent.onCall(AxisServiceComponent.java:135)
	at sun.reflect.GeneratedMethodAccessor674.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mule.model.DynamicEntryPoint.invokeCurrent(DynamicEntryPoint.java:168)
	at org.mule.model.DynamicEntryPoint.invoke(DynamicEntryPoint.java:90)
	at org.mule.impl.DefaultLifecycleAdapter.onCall(DefaultLifecycleAdapter.java:177)
	at org.mule.impl.DefaultLifecycleAdapter.intercept(DefaultLifecycleAdapter.java:232)
	at org.mule.impl.InterceptorsInvoker.execute(InterceptorsInvoker.java:53)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:230)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at org.mule.providers.http.HttpMessageReceiver$HttpWorker.run(HttpMessageReceiver.java:145)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)Caused by: java.sql.SQLException: A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, SYSCONGLOMERATES, (5,15)
  Waiting XID : {13736911, S} , APP,  
	
	INSERT INTO 
	
	MESSAGE (ID, SERVER_ID, CHANNEL_ID, SOURCE, TYPE, DATE_CREATED, VERSION, IS_ENCRYPTED, STATUS, RAW_DATA, RAW_DATA_PROTOCOL, TRANSFORMED_DATA, TRANSFORMED_DATA_PROTOCOL, ENCODED_DATA, ENCODED_DATA_PROTOCOL, CONNECTOR_NAME, ERRORS, CORRELATION_ID, CONNECTOR_MAP, CHANNEL_MAP, RESPONSE_MAP, ATTACHMENT) 
	
	VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
	
  Granted XID : {13715252, S} 
Lock : ROW, SYSCONGLOMERATES, (5,14)
  Waiting XID : {13715252, X} , APP, alter table "APP"."MESSAGE" compress
  Granted XID : {13715252, S} , {13736911, S} 
. The selected victim is XID : 13736911.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 83 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1177
Reporter: jscottking
Created: 2009-09-08T08:33:51.000-0700

**Comment by rbeckman-nextgen** [comment]
This is either a configuration issue or an issue with your database.  Derby should not be used as your production database for Mirth.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-09-10T11:01:16.000-0700
