### ISSUE TITLE
Cannot open database "mirthdb" requested by the login. The login failed.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1198]
Default Cannot open database "mirthdb" requested by the login. The login failed.
Hi,
I am facing some problem from past few weeks.
Here is the description.

There are multiple errors in the Mirth logs over the last few days. they indicate inability for Mirth to reach an endpoint port that should be listening. Also unable to access it's MIRTHDB at times. Checked for dependency on SQL service - it is there.

Below is the log.

WARN 2009-09-19 23:31:28,918 [f38a32fe-7cdd-4f66-9e38-d1f40d7240b4_source_connector._mllpEndpoint#-994855892.receiver.7] com.webreach.mirth.connectors.mllp.MllpMessageDisp atcher: Can't connect to the endopint,waiting10.0seconds for reconnecting
(java.net.SocketTimeoutException: connect timed out)
WARN 2009-09-19 23:31:48,919 [f38a32fe-7cdd-4f66-9e38-d1f40d7240b4_source_connector._mllpEndpoint#-994855892.receiver.7] com.webreach.mirth.connectors.mllp.MllpMessageDisp atcher: Can't connect to the endopint,waiting10.0seconds for reconnecting
(java.net.SocketTimeoutException: connect timed out)
ERROR 2009-09-19 23:32:08,920 [f38a32fe-7cdd-4f66-9e38-d1f40d7240b4_source_connector._mllpEndpoint#-994855892.receiver.7] com.webreach.mirth.connectors.mllp.MllpMessageDisp atcher: Can't connect to the endopint: payload not sent
ERROR 2009-09-20 05:51:45,500 [Thread-0] com.webreach.mirth.server.controllers.MessageObjec tController: java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
ERROR 2009-09-20 05:51:45,515 [Thread-0] com.webreach.mirth.server.controllers.SystemLogger : java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
ERROR 2009-09-20 05:51:45,531 [Thread-0] com.webreach.mirth.server.controllers.ChannelStati sticsController: Could not initialize channel statistics.
ERROR 2009-09-20 05:51:45,531 [Thread-0] com.webreach.mirth.server.controllers.Configuratio nController: could not initialize configuration settings
com.webreach.mirth.server.controllers.ControllerEx ception: error loading encryption key
at com.webreach.mirth.server.controllers.Configuratio nController.loadEncryptionKey(ConfigurationControl ler.java:542)
at com.webreach.mirth.server.controllers.Configuratio nController.initialize(ConfigurationController.jav a:160)
at com.webreach.mirth.server.Mirth.startup(Mirth.java :154)
at com.webreach.mirth.server.Mirth.run(Mirth.java:113 )
Caused by: java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnos tic(SQLDiagnostic.java:365)
at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(Td sCore.java:2781)
at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCor e.java:2224)
at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.ja va:599)
at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(C onnectionJDBC2.java:331)
at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(C onnectionJDBC3.java:50)
at net.sourceforge.jtds.jdbc.Driver.connect(Driver.ja va:178)
at java.sql.DriverManager.getConnection(Unknown Source)
at java.sql.DriverManager.getConnection(Unknown Source)
at com.ibatis.common.jdbc.SimpleDataSource.popConnect ion(SimpleDataSource.java:580)
at com.ibatis.common.jdbc.SimpleDataSource.getConnect ion(SimpleDataSource.java:222)
at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTran saction.init(JdbcTransaction.java:48)
at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTran saction.getConnection(JdbcTransaction.java:89)
at com.ibatis.sqlmap.engine.mapping.statement.General Statement.executeQueryForObject(GeneralStatement.j ava:104)
at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelega te.queryForObject(SqlMapExecutorDelegate.java:566)
at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelega te.queryForObject(SqlMapExecutorDelegate.java:541)
at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.qu eryForObject(SqlMapSessionImpl.java:106)
at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.qu eryForObject(SqlMapSessionImpl.java:110)
at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.que ryForObject(SqlMapClientImpl.java:87)
at com.webreach.mirth.server.controllers.Configuratio nController.loadEncryptionKey(ConfigurationControl ler.java:527)
... 3 more
ERROR 2009-09-20 05:51:45,546 [Thread-0] com.webreach.mirth.server.controllers.MigrationCon troller: Could not initialize migration controller.
java.lang.Exception: java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
at com.webreach.mirth.server.util.DatabaseUtil.execut eScript(DatabaseUtil.java:131)
at com.webreach.mirth.server.controllers.MigrationCon troller.migrate(MigrationController.java:143)
at com.webreach.mirth.server.controllers.MigrationCon troller.initialize(MigrationController.java:101)
at com.webreach.mirth.server.Mirth.startup(Mirth.java :155)
at com.webreach.mirth.server.Mirth.run(Mirth.java:113 )
Caused by: java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnos tic(SQLDiagnostic.java:365)
at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(Td sCore.java:2781)
at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCor e.java:2224)
at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.ja va:599)
at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(C onnectionJDBC2.java:331)
at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(C onnectionJDBC3.java:50)
at net.sourceforge.jtds.jdbc.Driver.connect(Driver.ja va:178)
at java.sql.DriverManager.getConnection(Unknown Source)
at java.sql.DriverManager.getConnection(Unknown Source)
at com.ibatis.common.jdbc.SimpleDataSource.popConnect ion(SimpleDataSource.java:580)
at com.ibatis.common.jdbc.SimpleDataSource.getConnect ion(SimpleDataSource.java:222)
at com.webreach.mirth.server.util.DatabaseUtil.execut eScript(DatabaseUtil.java:104)
... 4 more
WARN 2009-09-20 05:51:45,875 [Thread-0] com.webreach.mirth.server.controllers.ChannelContr oller: com.webreach.mirth.server.controllers.ControllerEx ception: java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
ERROR 2009-09-20 05:51:45,875 [Thread-0] com.webreach.mirth.server.controllers.UserControll er: Could not reset user status.
ERROR 2009-09-20 05:51:45,875 [Thread-0] com.webreach.mirth.server.controllers.Configuratio nController: Could not retrieve latest configuration.
java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnos tic(SQLDiagnostic.java:365)
at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(Td sCore.java:2781)
at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCor e.java:2224)
at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.ja va:599)
at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(C onnectionJDBC2.java:331)
at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(C onnectionJDBC3.java:50)
at net.sourceforge.jtds.jdbc.Driver.connect(Driver.ja va:178)
at java.sql.DriverManager.getConnection(Unknown Source)
at java.sql.DriverManager.getConnection(Unknown Source)
at com.ibatis.common.jdbc.SimpleDataSource.popConnect ion(SimpleDataSource.java:580)
at com.ibatis.common.jdbc.SimpleDataSource.getConnect ion(SimpleDataSource.java:222)
at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTran saction.init(JdbcTransaction.java:48)
at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTran saction.getConnection(JdbcTransaction.java:89)
at com.ibatis.sqlmap.engine.mapping.statement.General Statement.executeQueryForObject(GeneralStatement.j ava:104)
at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelega te.queryForObject(SqlMapExecutorDelegate.java:566)
at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelega te.queryForObject(SqlMapExecutorDelegate.java:541)
at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.qu eryForObject(SqlMapSessionImpl.java:106)
at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.qu eryForObject(SqlMapSessionImpl.java:110)
at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.que ryForObject(SqlMapClientImpl.java:87)
at com.webreach.mirth.server.controllers.Configuratio nController.getLatestConfiguration(ConfigurationCo ntroller.java:454)
at com.webreach.mirth.server.Mirth.startMule(Mirth.ja va:205)
at com.webreach.mirth.server.Mirth.startup(Mirth.java :163)
at com.webreach.mirth.server.Mirth.run(Mirth.java:113 )
ERROR 2009-09-20 05:51:45,875 [Thread-0] com.webreach.mirth.server.Mirth: Could not retrieve latest configuration.
java.lang.NullPointerException
at com.webreach.mirth.server.Mirth.startMule(Mirth.ja va:205)
at com.webreach.mirth.server.Mirth.startup(Mirth.java :163)
at com.webreach.mirth.server.Mirth.run(Mirth.java:113 )
WARN 2009-09-20 05:51:45,890 [DefaultQuartzScheduler_Worker-1] com.webreach.mirth.plugins.messagepruner.MessagePr unerService: could not prune message database
com.webreach.mirth.server.controllers.ControllerEx ception: java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
at com.webreach.mirth.server.controllers.ChannelContr oller.getChannel(ChannelController.java:132)
at com.webreach.mirth.plugins.messagepruner.MessagePr unerService.execute(MessagePrunerService.java:188)
at org.quartz.core.JobRunShell.run(JobRunShell.java:2 02)
at org.quartz.simpl.SimpleThreadPool$WorkerThread.run (SimpleThreadPool.java:529)
Caused by: java.sql.SQLException: Cannot open database "mirthdb" requested by the login. The login failed.
at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnos tic(SQLDiagnostic.java:365)

Please let me know hw can i handle this issue.

Thanks in advance.
Edit/Delete Message Reply With Quote Multi-Quote This Message Quick reply to this message

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1198
Reporter: sriiyengar
Created: 2009-09-24T04:11:02.000-0700

**Comment by rbeckman-nextgen** [comment]
This is not an issue with Mirth, but an issue with your database setup and/or configuration.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-09-24T14:21:54.000-0700
