### ISSUE TITLE
SFTP connector - cannot use channel variables

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1204]
Per forum Posting http://www.mirthcorp.com/community/forums/showthread.php?t=3025.

SFTP Connector does not work with destination mappings (channel variables or otherwise) as Site, Directory, User or Password.  See stack trace below:

ERROR-403: File connector error
ERROR MESSAGE:	Error writing file
com.jcraft.jsch.JSchException: host must not be null.
at com.jcraft.jsch.JSch.getSession(JSch.java:143)
at com.jcraft.jsch.JSch.getSession(JSch.java:137)
at com.webreach.mirth.connectors.file.filesystems.Sft pConnection.<init>(SftpConnection.java:89)
at com.webreach.mirth.connectors.file.filesystems.Fil eSystemConnectionFactory.makeObject(FileSystemConn ectionFactory.java:90)
at org.apache.commons.pool.impl.GenericObjectPool.bor rowObject(GenericObjectPool.java:816)
at com.webreach.mirth.connectors.file.FileConnector.g etConnection(FileConnector.java:298)
at com.webreach.mirth.connectors.file.FileMessageDisp atcher.doDispatch(FileMessageDispatcher.java:105)
at com.webreach.mirth.connectors.file.FileMessageDisp atcher.doSend(FileMessageDispatcher.java:144)
at org.mule.providers.AbstractMessageDispatcher.send( AbstractMessageDispatcher.java:167)
at org.mule.impl.MuleSession.sendEvent(MuleSession.ja va:191)
at org.mule.impl.MuleSession.sendEvent(MuleSession.ja va:130)
at org.mule.routing.outbound.AbstractOutboundRouter.s end(AbstractOutboundRouter.java:85)
at org.mule.routing.outbound.FilteringMulticastingRou ter.route(FilteringMulticastingRouter.java:45)
at org.mule.routing.outbound.OutboundMessageRouter$1. doInTransaction(OutboundMessageRouter.java:78)
at org.mule.transaction.TransactionTemplate.execute(T ransactionTemplate.java:48)
at org.mule.routing.outbound.OutboundMessageRouter.ro ute(OutboundMessageRouter.java:82)
at org.mule.impl.model.DefaultMuleProxy.onCall(Defaul tMuleProxy.java:247)
at org.mule.impl.model.seda.SedaComponent.doSend(Seda Component.java:209)
at org.mule.impl.model.AbstractComponent.sendEvent(Ab stractComponent.java:277)
at org.mule.impl.MuleSession.sendEvent(MuleSession.ja va:201)
at org.mule.routing.inbound.InboundMessageRouter.send (InboundMessageRouter.java:180)
at org.mule.routing.inbound.InboundMessageRouter.rout e(InboundMessageRouter.java:147)
at org.mule.providers.AbstractMessageReceiver$Default InternalMessageListener.onMessage(AbstractMessageR eceiver.java:493)
at org.mule.providers.AbstractMessageReceiver.routeMe ssage(AbstractMessageReceiver.java:272)
at org.mule.providers.AbstractMessageReceiver.routeMe ssage(AbstractMessageReceiver.java:231)
at com.webreach.mirth.connectors.vm.VMMessageReceiver .getMessages(VMMessageReceiver.java:178)
at org.mule.providers.TransactedPollingMessageReceive r.poll(TransactedPollingMessageReceiver.java:108)
at org.mule.providers.PollingMessageReceiver.run(Poll ingMessageReceiver.java:90)
at org.mule.impl.work.WorkerContext.run(WorkerContext .java:290)
at edu.emory.mathcs.backport.java.util.concurrent.Thr eadPoolExecutor$Worker.runTask(ThreadPoolExecutor. java:650)
at edu.emory.mathcs.backport.java.util.concurrent.Thr eadPoolExecutor$Worker.run(ThreadPoolExecutor.java :675)
at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1204
Reporter: glickpw
Created: 2009-09-28T11:37:57.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-1125

Imported Comment. Original Details:
Author: jacobb
Created: 2009-09-28T18:14:11.000-0700
