### ISSUE TITLE
Upgrade apache commons net to 2.0 to fix parser error

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1219]
Updating the library from 1.4 to 2.0 addresses the following exception when connecting to certain FTP servers:

FATAL (org.mule.impl.DefaultComponentExceptionStrategy:84): The error is: Unknown parser type: UNKNOWN Type: L8
org.apache.commons.net.ftp.parser.ParserInitializationException: Unknown parser type: UNKNOWN Type: L8
       at org.apache.commons.net.ftp.parser.DefaultFTPFileEntryParserFactory.createFileEntryParser(DefaultFTPFileEntryParserFactory.java:118)
       at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:2358)
       at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2141)
       at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2188)
       at com.webreach.mirth.connectors.file.filesystems.FtpConnection.listFiles(FtpConnection.java:117)
       at com.webreach.mirth.connectors.file.FileMessageReceiver.listFiles(FileMessageReceiver.java:430)
       at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:110)
       at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
       at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
       at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
       at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
       at java.lang.Thread.run(Thread.java:595)

The upgrade can be done once these lifecycle methods in FtpConnection are changed to reflect the changes in the commons-net FTPClient:

public void activate() {
// client.setReaderThread(true);
}

public void passivate() {
// client.setReaderThread(false);
} 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1219
Reporter: geraldb
Created: 2009-10-09T10:51:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Upgraded JAR and removed reference to methods.

Imported Comment. Original Details:
Author: geraldb
Created: 2009-10-09T11:12:09.000-0700
