### ISSUE TITLE
SFTP Connector does not handle server timeouts correctly

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1236]
SftpConnection does not properly handle disconnects from the server.
 * The SFTP destination always works right after Redeployment
 * Attempts to send several files immediately after Redeployment are always successful
 * If the channel is dormant for some time, an attempt to send a file through will always result in the "Broken pipe" exception and the file is not transmitted.
 * Next immediate attempt after the failure always succeeds.

Possible Explanation
 * Peer SFTP server does not properly time-out / close connections.
 * SftpConnection does not close a connection after sending a single message .
 * SFTP server times-out the connection, but SftpConnection still thinks it has one open.
 * An attempt to send the next message fails. SftpConnection now realizes the the connection is broken (Exception is thrown), but it's too late for the current message, it's handled as an error with no attempt to re-establish connection or retransmit.
 * Next message after the failure will succeed because SftpConnection now opens a new connection and properly transfers the file again leaving the open connection hanging (cycle repeats)

Exception Stack Trace:
        at com.jcraft.jsch.ChannelSftp.cd(ChannelSftp.java:285)
	at com.webreach.mirth.connectors.file.filesystems.SftpConnection.cdmake(SftpConnection.java:200)
	at com.webreach.mirth.connectors.file.filesystems.SftpConnection.writeFile(SftpConnection.java:168)
	at com.webreach.mirth.connectors.file.FileMessageDispatcher.doDispatch(FileMessageDispatcher.java:106)
	at com.webreach.mirth.connectors.file.FileMessageDispatcher.doSend(FileMessageDispatcher.java:144)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
        ....
Caused by: java.io.IOException: Pipe closed
	at java.io.PipedInputStream.read(Unknown Source)
	at java.io.PipedInputStream.read(Unknown Source)
	at com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2325)
	at com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2351)
	at com.jcraft.jsch.ChannelSftp._realpath(ChannelSftp.java:1810)
	at com.jcraft.jsch.ChannelSftp.cd(ChannelSftp.java:268)
	... 28 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1236
Reporter: aoganesi
Created: 2009-10-26T18:15:59.000-0700

**Comment by rbeckman-nextgen** [comment]
Basically, I am proposing to make the SftpConnection a little smarter when it comes to validating an existing connection. Currently the isValid method is relying on the client.isConnected() API call to determine if the connection is still alive. This method seems to be unreliable for many FTP servers which timeout the connection without properly notifying the client.

I suggest the following:
* Introduce a local valriable lastDir
* Set this varible in listFiles(String fromDir, String filenamePattern) method
* Set this varible in writeFile(String file, String toDir, boolean append, byte[] message) method
* Set this varible in readFile(String file, String toDir) method
* Modify the isValid method as follows:

Code:
public boolean isValid()
{
    if (lastDir == null)
        return client.isConnected();
    else
        return client.isConnected() && canRead(lastDir);
}

This code may be little slower in high-volumen scenarios but should be a lot more reliable.

Imported Comment. Original Details:
Author: aoganesi
Created: 2009-10-26T18:27:43.000-0700

**Comment by rbeckman-nextgen** [comment]
Added lastDir to store the last read or written directory in SFTP. This directory is checked if it can be read when checking if the connection is still valid.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-11-02T10:34:04.000-0800
