### ISSUE TITLE
A message in error won't go away: java.sql.SQLException: Error: executeQueryForObject returned too many results.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1244]
Hi,

We had a connection drop yesterday.  So today there were some messages sitting in the error state.  Once the connection was restored, we were able to run 'reporcess' and they all got sent straight through ok.  

Except for one message...  I don't know what's so special about this one, it is really just like the rest.  But when we try to do reprocess, this stack trace is thrown and it is permanently stuck in the error state:

[2009-11-04 15:35:08,796]  ERROR (com.webreach.mirth.server.controllers.DefaultMessageObjectController:589): Could not locate existing message
java.sql.SQLException: Error: executeQueryForObject returned too many results.
                at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForObject(GeneralStatement.java:108)
                at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:566)
                at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:541)
                at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
                at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForObject(SqlMapClientImpl.java:83)
                at com.webreach.mirth.server.controllers.DefaultMessageObjectController.lookupMessageId(DefaultMessageObjectController.java:615)
                at com.webreach.mirth.server.controllers.DefaultMessageObjectController.cloneMessageObjectForBroadcast(DefaultMessageObjectController.java:587)
                at com.webreach.mirth.server.mule.adaptors.Adaptor.convertMessage(Adaptor.java:66)
                at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:335)
                at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
                at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
                at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
                at com.webreach.mirth.server.controllers.DefaultMessageObjectController.getMessageObjectFromEvent(DefaultMessageObjectController.java:624)
                at com.webreach.mirth.connectors.jms.JmsMessageDispatcher.dispatchMessage(JmsMessageDispatcher.java:89)
                at com.webreach.mirth.connectors.jms.JmsMessageDispatcher.doSend(JmsMessageDispatcher.java:261)
                at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
                at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
                at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
                at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
                at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
                at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
                at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
                at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
                at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
                at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
                at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
                at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
                at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
                at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
                at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
                at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
                at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
                at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:178)
                at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
                at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
                at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
                at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
                at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
                at java.lang.Thread.run(Unknown Source)

It looks like a bug to me, but maybe not.  A brief google indicated that message means mirth is expecting 1 result back but is getting more than one.  If this is my fault or it has already been fixed, I apologize (I hate that)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1244
Reporter: john.newman
Created: 2009-11-04T13:05:35.000-0800

**Comment by rbeckman-nextgen** [comment]
Please test it on the latest release/release candidate to verify if the issue still exists.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-11-04T16:53:20.000-0800

**Comment by rbeckman-nextgen** [comment]
It looks like the message was not stored in the database properly when the database connection went down.  It should be removed from the database and reprocessed as a new message manually.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-11-17T12:49:17.000-0800

**Comment by rbeckman-nextgen** [comment]
thanks Jacob. Unfortunately I cannot reproduce it either.  Worse, we can't exactly upgrade to the latest version right now for a whole list of reasons.

If this resurfaces on it's own I will do some more investigating and possibly reopen if I have something more useful than a stacktrace.

Imported Comment. Original Details:
Author: john.newman
Created: 2009-11-17T12:53:38.000-0800
