### ISSUE TITLE
Database reader On Update statement validation too restrictive.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1250]
When trying to EXECUTE a stored procedure, the channel fails to activate due to a validation error in the channel, even though the Server Administrator successfully validated the channel. 

The server fails with:
[2009-11-11 09:26:48,848]  DEBUG (java.sql.PreparedStatement:26): {pstm-100270} Parameters: [Error starting the channel cannot be activated due to a problem at one of the endpoint abbf108a-8939-4426-800e-203aff93f9ff, HIGH, org.mule.umo.model.ModelException: Failed to register listener abbf108a-8939-4426-800e-203aff93f9ff on endpoint jdbc://query
	at org.mule.impl.model.AbstractModel.registerListeners(AbstractModel.java:228)
	at org.mule.impl.model.AbstractModel.startComponent(AbstractModel.java:465)
	at org.mule.management.mbeans.ModelService.startComponent(ModelService.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.StandardMetaDataImpl.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.MetaDataImpl.invoke(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.access$100(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Ack statement should be an INSERT, UPDATE, or DELETE SQL statement
	at com.webreach.mirth.connectors.jdbc.JdbcConnector.getReadAndAckStatements(JdbcConnector.java:262)
	at com.webreach.mirth.connectors.jdbc.JdbcConnector.createReceiver(JdbcConnector.java:184)
	at org.mule.providers.AbstractConnector.registerListener(AbstractConnector.java:506)
	at org.mule.impl.model.AbstractModel.registerListeners(AbstractModel.java:224)
	... 27 more
, <properties/>]

Why does Mirth assume that the ACK statement must be a DELETE, INSERT or UPDATE statement? I need to execute a procedure, so it should also allow EXECUTE or at the very least a SELECT?

I'd prefer it if this validation did not exist at all. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1250
Reporter: willo
Created: 2009-11-10T23:54:18.000-0800

**Comment by rbeckman-nextgen** [comment]
Or at least allow us to use Javascript to execute arbitrary code

Imported Comment. Original Details:
Author: willo
Created: 2009-11-11T00:01:12.000-0800

**Comment by rbeckman-nextgen** [comment]
You do have the option to use JavaScript, and I think this will work if you use that.  Check the "Use JavaScript" yes radio button and I don't think the validation still exists.  Does that work for you?

Imported Comment. Original Details:
Author: jacobb
Created: 2009-11-18T15:42:04.000-0800

**Comment by rbeckman-nextgen** [comment]
Oh, I see that. I expected that I could have Javascript on, on either one of the two. For the moment I've come up with a work around, but when I have some time I'll experiment with the JS way of doing things.

Imported Comment. Original Details:
Author: willo
Created: 2009-11-18T22:25:01.000-0800

**Comment by rbeckman-nextgen** [comment]
Use JavaScript for queries other than SELECT and on-update statements other than INSERT, UPDATE, or DELETE.  We use QueryRunner to execute the non-JavaScript queries.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-12-02T17:34:43.000-0800
