### ISSUE TITLE
Channel - changing the incoming data type from HL7 to XML causes array excepti

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1254]
Steps to reproduce:

1. Create a new channel - making sure the incoming data is HL7 2.x
2. Deploy and run a message through it
3. Change the incoming data to XML
4. Deploy and run a message through it

Expected result: the message should process as normal

Actual Result: Message is marked as having ERROR'd out with this stacktrace:

 Caused by: org.mule.umo.transformer.TransformerException: java.lang.ArrayIndexOutOfBoundsException: 1 (com.webreach.mirth.model.converters.SerializerException)

       at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:470)

       at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:356)

       at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)

       at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)

       at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)

       at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)

       at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)

       ... 11 more

 Caused by: com.webreach.mirth.model.converters.SerializerException: java.lang.ArrayIndexOutOfBoundsException: 1

       at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:200)

       at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:50)

       at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:444)

       ... 17 more

 Caused by: java.lang.ArrayIndexOutOfBoundsException: 1

       at com.webreach.mirth.model.converters.ER7XMLHandler.startElement(ER7XMLHandler.java:111)

       at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)

       at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)

       at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)

       at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)

       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)

       at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)

       at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)

       at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)

       at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:195)

       ... 19 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1254
Reporter: malcomm
Created: 2009-11-17T19:55:48.000-0800

**Comment by rbeckman-nextgen** [comment]
meant to make the summary have: ArrayIndexOutOfBoundsException

Imported Comment. Original Details:
Author: malcomm
Created: 2009-11-17T19:56:23.000-0800

**Comment by rbeckman-nextgen** [comment]
I kept on getting this ArrayIndexOutOfBoundsException until I created a new channel that only had XML as the incoming source, but the transformer and everything else was exactly the same (took me a long time to figure out that there was something wrong w/ Mirth).

This sounds a lot like MIRTH-1082 (never resolved).

I finally realized what was going on after reading this post:

http://www.mirthcorp.com/community/forums/showthread.php?p=10906

"Perhaps you'd started configuring your channel using HL7 as incoming data format, and once you saved the configuration, you changed it to XML?

I've experienced a problem very similar to this. In my case, the workarround was start configuring a new channel from scratch using XML as incoming data format."

Imported Comment. Original Details:
Author: malcomm
Created: 2009-11-17T20:04:43.000-0800

**Comment by rbeckman-nextgen** [comment]
The steps you gave should produce the error described.  This is because you only changed your incoming data to XML, while leaving the source outbound data type and destination outbound data type as HL7 2.x.  Without any transformers, this implicit conversion will not work.  See my forum response below for more information, and I will look into a way to make this feature more clear:

You simply need to go through each transformer (on both the source and every destination) and make sure both the Incoming and Outgoing data are set to the data type you want.

This quirk actually happens because of how flexible Mirth Connect is. Before you first save your channel or edit your transformers, whatever you change the incoming data to changes the incoming/outgoing data type on every filter/transformer in the channel. After that, you will have to change each setting individually.

Imagine you wanted to receive HL7 at the source, but send out XML to the destination (assuming you do the proper transforms). If the incoming data setting always changed all transformer data types, this sort of common conversion inside of a channel would not be possible. If you have changed your entire channel to XML, and then later after this "initial state" has been created you only change the incoming data back, then you will get these errors.

It's really simple to fix once you understand what it's doing. I agree the current way it sets these properties is not very clean, but changing system wide settings the first time you set incoming data actually ends up solving this issue for most cases. The other option would be to force you to change the setting on every transformer in the source and each destination manually when you want to create a channel with something other than the default. That would be very time consuming. Perhaps a prompt with multiple options would be helpful in the future.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-11-18T15:36:24.000-0800
