### ISSUE TITLE
parameter Map / getMessageByPageLimit Error Message 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1258]
The following error was logged five times in a six minute time frame. I have not seen it before or since. I cannot reproduce it. Everything else about the system appears to be functioning.

[2009-11-26 10:10:43,034]  WARN  (org.mortbay.jetty.context./:589): /messages: 
com.webreach.mirth.server.controllers.ControllerException: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred while applying a parameter map.  
--- Check the Message.getMessageByPageLimit-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: java.sql.SQLException: An expression of non-boolean type specified in a context where a condition is expected, near 'ILIKE'.
Caused by: java.sql.SQLException: An expression of non-boolean type specified in a context where a condition is expected, near 'ILIKE'.
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.getMessagesByPageLimit(DefaultMessageObjectController.java:299)
	at com.webreach.mirth.server.servlets.MessageObjectServlet.doPost(MessageObjectServlet.java:82)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:616)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.mortbay.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:666)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
	at org.mortbay.http.HttpServer.service(HttpServer.java:909)
	at org.mortbay.http.HttpConnection.service(HttpConnection.java:816)
	at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:982)
	at org.mortbay.http.HttpConnection.handle(HttpConnection.java:833)
	at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:244)
	at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred while applying a parameter map.  
--- Check the Message.getMessageByPageLimit-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: java.sql.SQLException: An expression of non-boolean type specified in a context where a condition is expected, near 'ILIKE'.
Caused by: java.sql.SQLException: An expression of non-boolean type specified in a context where a condition is expected, near 'ILIKE'.
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryWithCallback(GeneralStatement.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForList(GeneralStatement.java:123)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:615)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:589)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:95)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.getMessagesByPageLimit(DefaultMessageObjectController.java:290)
	... 15 moreCaused by: java.sql.SQLException: An expression of non-boolean type specified in a context where a condition is expected, near 'ILIKE'.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:365)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2781)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2224)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:628)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:525)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:487)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:475)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:186)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteQuery(GeneralStatement.java:205)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryWithCallback(GeneralStatement.java:173)
	... 21 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1258
Reporter: colinsj
Created: 2009-11-26T15:59:17.000-0800

**Comment by rbeckman-nextgen** [comment]
Rather similar to MIRTH-507

Imported Comment. Original Details:
Author: colinsj
Created: 2009-11-26T15:59:57.000-0800

**Comment by rbeckman-nextgen** [comment]
This should have been fixed in MIRTH-939.  Please re-open an issue if this problem is still occurring in the latest Mirth Connect release.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-12-01T15:51:48.000-0800

**Comment by rbeckman-nextgen** [comment]
Note this also might been fixed as a part of MIRTH-1074, which should be included in 1.8.1.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-12-01T15:53:52.000-0800
