### ISSUE TITLE
Database Writer in SQL mode does not allow comments

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1271]
When using the Database Writer in SQL mode, comments will cause the following exception:

[2009-12-16 14:10:43,731]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: 14c4cf95-4531-4fa4-a172-85774fd9a70a: java.lang.IllegalArgumentException: Write statement should be an INSERT, UPDATE, or DELETE SQL statement.
java.lang.IllegalArgumentException: Write statement should be an INSERT, UPDATE, or DELETE SQL statement.
	at com.webreach.mirth.connectors.jdbc.JdbcMessageDispatcher.doDispatch(JdbcMessageDispatcher.java:110)
	at com.webreach.mirth.connectors.jdbc.JdbcMessageDispatcher.doSend(JdbcMessageDispatcher.java:139)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:52)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:476)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:436)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:353)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:619)

This is in spite of the fact that the syntax highlighter highlights the comments as if they are valid.  It would be a nice feature if you were able to use comments in your SQL code.  I'm assuming the SQL contexts in the Database Reader behave the same, although I have not tested it.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1271
Reporter: ericb
Created: 2009-12-16T14:17:33.000-0800

**Comment by rbeckman-nextgen** [comment]
Connector now strips comments before validating statement. Tested with following statement:

-- FIRST COMMENT
INSERT INTO -- SECOND COMMENT
PATIENT (FIRST_NAME)
VALUES ("TEST");
-- THIRD COMMENT

This results in the following statement:

INSERT INTO
PATIENT (FIRST_NAME)
VALUES ("TEST");


Imported Comment. Original Details:
Author: geraldb
Created: 2010-03-04T10:55:14.000-0800

**Comment by rbeckman-nextgen** [comment]
I have tried all three forms of comments and they are failing for me.  Here is one of my examples that is failing...

-- Insert into the demographics table. 
INSERT INTO Demographics (PatientID, BirthDate, DeathDate, Gender, FirstName, MiddleName, LastName, DateAdded, DateUpdated, DateDeleted, FirstNameSoundex, LastNameSoundex)
VALUES (111,'2000-01-01', NULL,'Male' ,'John' , 'J.' , 'Doe' , '2011-05-19 10:10:10' ,  NULL, NULL, '', '' ) ON DUPLICATE KEY UPDATE
PatientID=VALUES(PatientID),
BirthDate=VALUES(BirthDate),
DeathDate=VALUES(DeathDate),
Gender=VALUES(Gender),
FirstName=VALUES(FirstName),
MiddleName=VALUES(MiddleName),
LastName=VALUES(LastName),
DateAdded=VALUES(DateAdded),
DateUpdated=VALUES(DateUpdated),
DateDeleted=VALUES(DateDeleted),
FirstNameSoundex=VALUES(FirstNameSoundex),
LastNameSoundex=VALUES(LastNameSoundex);



Imported Comment. Original Details:
Author: leswestberg
Created: 2011-05-19T09:20:53.000-0700

**Comment by rbeckman-nextgen** [comment]
Retested since this error still occurs. If the first line is a comment, the current logic will strip the comment and replace it with a newline. When it then checks the statement, it checks using "startsWith" which could not find an INSERT/UPDATE/DELETE on the first line and throw an error.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-05-31T11:58:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Updated to not append a newline at the beginning if the first line is a comment (caused the statement check to fail).

Imported Comment. Original Details:
Author: geraldb
Created: 2011-05-31T11:59:41.000-0700

**Comment by rbeckman-nextgen** [comment]
Now also works with comments as the first line.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-06-07T14:59:32.000-0700
