### ISSUE TITLE
ACK isn't sent with Send ACK set to "Respond from" and wrong HL7 message

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1275]
When incomming message violates LLP protocol ACK message isn't sent to client.
For correct HL7 messages ACK is correctly sents to client.

Channel type: LLP Listener
"Send ACK": "Response from"
The responseMap for ACK is built in a dedicated destination.

Wrong incomming message (CR in OBR.13):
MSH|^~\&|X|Y|Z|K|20091204092013||ORM^O01|1259914813326|P|2.5
PID|||1234||DOE^JOHN||19470322|M|||
PV1||O|||||||||||||||||||||||||||||||||||||||||||||||||V
ORC|NW|719868||329410|||^^^^^R||20091204092213||||||20091204092213
OBR|1|719868||ABC^ABC DESC|||||||L||screening
|||||||||||||||||WALK||||||20091204092200|

============
Mirth 1.7.1 error:

[2009-12-21 16:11:08,471]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: da31308a-ec7e-4b74-a59b-eb6fa16908bb: org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.mllp.MllpConnector@1990d96, endpointUri=mllp://127.0.0.1:22400, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_mllpEndpoint#-319374599', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1c9982e, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String
org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.mllp.MllpConnector@1990d96, endpointUri=mllp://127.0.0.1:22400, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_mllpEndpoint#-319374599', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1c9982e, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:440)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:415)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:339)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:595)Caused by: org.mule.umo.transformer.TransformerException: 
CHANNEL:
	DSS_RAD2
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
LINE NUMBER:
	1
DETAILS:
	TypeError: error: Unexpected character encountered (lex state 9): '](' (com.webreach.mirth.server.MirthJavascriptTransformerException)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:448)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:346)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	... 11 moreCaused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	DSS_RAD2
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
LINE NUMBER:
	1
DETAILS:
	TypeError: error: Unexpected character encountered (lex state 9): '|'
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:439)
	... 18 more

============
Mirth 1.8.1 error:

[2009-12-21 16:17:50,712)  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: da31308a-ec7e-4b74-a59b-eb6fa16908bb: org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.mllp.MllpConnector@165ab39, endpointUri=mllp://127.0.0.1:22400, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_mllpEndpoint#146961267', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@768dc8, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String
org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.mllp.MllpConnector@165ab39, endpointUri=mllp://127.0.0.1:22400, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_mllpEndpoint#146961267', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@768dc8, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:83)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:476)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:436)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:353)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:595)Caused by: org.mule.umo.transformer.TransformerException: 
CHANNEL:
	DSS_RAD2
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
LINE NUMBER:
	0
DETAILS:
	TypeError: The content of elements must consist of well-formed character data or markup. (com.webreach.mirth.server.MirthJavascriptTransformerException)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:470)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:356)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	... 11 moreCaused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	DSS_RAD2
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
LINE NUMBER:
	0
DETAILS:
	TypeError: The content of elements must consist of well-formed character data or markup.
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:460)
	... 18 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1275
Reporter: flytaylor
Created: 2009-12-21T07:19:18.000-0800

**Comment by rbeckman-nextgen** [comment]
Currently Mirth Connect needs to parse the message in order to send an ACK back.  For generating an ACK, it is obvious why the message needs to be parsed.  For sending a custom ACK, the message also needs to be parsed in order for it to even get to the source, destinations, or postprocessor that might generate the ACK.

The sending client should safely assume the message was not parsed correctly and Mirth Connect never processed it if no ACK at all was received.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-12-22T15:44:49.000-0800
