### ISSUE TITLE
Failed to route event via endpoint: null. Message payload is of type: com.webreach.mirth.model.MessageObject.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1279]
This has been happening off and on. I have stopped and started the Mirth engine and it is still leaving the error message below.

[2009-12-08 11:57:41,467] ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: 7d05e066-7780-4627-8e48-92ffa9cceb43: org.mule.umo.routing.RoutingException: Failed to route event via endpoint: null. Message payload is of type: com.webreach.mirth.model.MessageObject 
org.mule.umo.routing.RoutingException: Failed to route event via endpoint: null. Message payload is of type: com.webreach.mirth.model.MessageObject 
at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:84) 
at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247) 
at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209) 
at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277) 
at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201) 
at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161) 
at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128) 
at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493) 
at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272) 
at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244) 
at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:440) 
at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:418) 
at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:339) 
at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290) 
at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650) 
at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675) 
at java.lang.Thread.run(Unknown Source)Caused by: org.mule.umo.routing.CouldNotRouteOutboundMessageException: Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.vm.VMConnector@69ed4a, endpointUri=vm://7d05e066-7780-4627-8e48-92ffa9cceb43, transformer=Transformer{name='b0074076-a55d-4bb1-8020-aaa7db4fe9c4_destination_1_transformer', returnClass=false, returnClass=false, sourceTypes=[]}, name='_vmEndpoint#-420937123', type='sender', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@3d511e, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: com.webreach.mirth.model.MessageObject 
at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:111) 
at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78) 
at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48) 
at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82) 
... 16 moreCaused by: org.mule.umo.provider.DispatchException: Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.vm.VMConnector@69ed4a, endpointUri=vm://7d05e066-7780-4627-8e48-92ffa9cceb43, transformer=Transformer{name='b0074076-a55d-4bb1-8020-aaa7db4fe9c4_destination_1_transformer', returnClass=false, returnClass=false, sourceTypes=[]}, name='_vmEndpoint#-420937123', type='sender', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@3d511e, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: com.webreach.mirth.model.MessageObject 
at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:179) 
at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191) 
at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130) 
at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85) 
at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89) 
... 19 moreCaused by: org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.vm.VMConnector@42a6eb, endpointUri=vm://7d05e066-7780-4627-8e48-92ffa9cceb43, transformer=Transformer{name='7d05e066-7780-4627-8e48-92ffa9cceb43_source_preprocessor', returnClass=false, returnClass=false, sourceTypes=[]}, name='7d05e066-7780-4627-8e48-92ffa9cceb43', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@f757b9, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=null, initialState=started, createConnector=0}. Message payload is of type: java.lang.String 
at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64) 
at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79) 
at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493) 
at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272) 
at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231) 
at com.webreach.mirth.connectors.vm.VMMessageReceiver.dispatchMessage(VMMessageReceiver.java:118) 
at com.webreach.mirth.connectors.vm.VMMessageDispatcher.routeTemplatedMessage(VMMessageDispatcher.java:216) 
at com.webreach.mirth.connectors.vm.VMMessageDispatcher.doSend(VMMessageDispatcher.java:273) 
at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166) 
... 23 moreCaused by: org.mule.umo.transformer.TransformerException: 
CHANNEL: 
TOA - Mirth To MyWay - MFN 
CONNECTOR: 
sourceConnector 
SCRIPT SOURCE: 

LINE NUMBER: 
36 
DETAILS: 
Wrapped java.sql.SQLException: Network error IOException: Connection timed out: connect (com.webreach.mirth.server.MirthJavascriptTransformerException) 
at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:448) 
at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:346) 
at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48) 
at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197) 
at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200) 
at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251) 
at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61) 
... 31 moreCaused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL: 
TOA - Mirth To MyWay - MFN 
CONNECTOR: 
sourceConnector 
SCRIPT SOURCE: 

LINE NUMBER: 
36 
DETAILS: 
Wrapped java.sql.SQLException: Network error IOException: Connection timed out: connect 
at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:439) 
... 37 moreCaused by: java.sql.SQLException: Network error IOException: Connection timed out: connect 
at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(ConnectionJDBC2.java:372) 
at net.sourceforge.jtds.jdbc.ConnectionJDBC3.<init>(ConnectionJDBC3.java:50) 
at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:178) 
at java.sql.DriverManager.getConnection(Unknown Source) 
at java.sql.DriverManager.getConnection(Unknown Source) 
at com.webreach.mirth.server.util.DatabaseConnection.<init>(DatabaseConnection.java:64) 
at com.webreach.mirth.server.util.DatabaseConnectionFactory.createDatabaseConnection(DatabaseConnectionFactory.java:65) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
at java.lang.reflect.Method.invoke(Unknown Source) 
at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:142) 
at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:201) 
at org.mozilla.javascript.optimizer.OptRuntime.callN(OptRuntime.java:84) 
at org.mozilla.javascript.gen.c38._c14(bf622824-431e-4f37-8677-4e8f95ab5cca:41) 
at org.mozilla.javascript.gen.c38.call(bf622824-431e-4f37-8677-4e8f95ab5cca) 
at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:106) 
at org.mozilla.javascript.gen.c38._c0(bf622824-431e-4f37-8677-4e8f95ab5cca:204) 
at org.mozilla.javascript.gen.c38.call(bf622824-431e-4f37-8677-4e8f95ab5cca) 
at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:337) 
at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:2755) 
at org.mozilla.javascript.gen.c38.call(bf622824-431e-4f37-8677-4e8f95ab5cca) 
at org.mozilla.javascript.gen.c38.exec(bf622824-431e-4f37-8677-4e8f95ab5cca) 
at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:393) 
... 37 moreCaused by: java.net.ConnectException: Connection timed out: connect 
at java.net.PlainSocketImpl.socketConnect(Native Method) 
at java.net.PlainSocketImpl.doConnect(Unknown Source) 
at java.net.PlainSocketImpl.connectToAddress(Unknown Source) 
at java.net.PlainSocketImpl.connect(Unknown Source) 
at java.net.SocksSocketImpl.connect(Unknown Source) 
at java.net.Socket.connect(Unknown Source) 
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) 
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) 
at java.lang.reflect.Method.invoke(Unknown Source) 
at net.sourceforge.jtds.jdbc.SharedSocket.createSocketForJDBC3(SharedSocket.java:289) 
at net.sourceforge.jtds.jdbc.SharedSocket.<init>(SharedSocket.java:250) 
at net.sourceforge.jtds.jdbc.ConnectionJDBC2.<init>(ConnectionJDBC2.java:297) 
... 60 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1279
Reporter: sriiyengar
Created: 2009-12-23T01:18:19.000-0800

**Comment by rbeckman-nextgen** [comment]
This is a blocking issue. Kindly let me know the solution asap.
Thanks in advance.

Imported Comment. Original Details:
Author: sriiyengar
Created: 2009-12-23T01:23:38.000-0800

**Comment by rbeckman-nextgen** [comment]
This is a very generic error that would need more information to fix.  The issue tracker is not the place to be asking for support.  If you need your issue resolved quickly and cannot figure it out you should try posting on the forums for free support or contacting the Mirth help desk for professional support.

Imported Comment. Original Details:
Author: jacobb
Created: 2009-12-23T10:52:13.000-0800
