### ISSUE TITLE
Javascript does not use normal repsonse mechanism

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1286]
When using a javascript connector it is not possible to enter a response other than through a string.  When looking through documentation and help there seem to be a mechanism in place to accept Response object from which it is possible to send structured and modulated responses to a channel.

However when using a JAva script connector and trying to instantiate a response object through the factory like so :

 if (!cgsiResponse.isOk())
   responseMap.put(connector, ResponseFactory
				.getFailureResponse(cgsiResponse.getErrorNumber() + ' :: '
						+ cgsiResponse.getMessageErreur()));
 else
   responseMap.put(connector, ResponseFactory
				.getSuccessResponse("Message successfuly processed"));

the channel invariable ends up with a cast exception stating Response cannot be cast to string.  Investigation in isolating the script parts and through the source code of mirth itself seem to point to this code here in JavaScriptMessageDispatcher.java

if (messageObject.getResponseMap().containsKey(messageObject.getConnectorName())) {
					response = (String) messageObject.getResponseMap().get(messageObject.getConnectorName());

Using the Response object however would be preferable since it allows better modulation of the script`s outcome and how it's going to be handled in the rest of the framework.

Changing the script to the following solved the situation but it is not ideal since I can no longer report erroneous outcome other than by throwing exception which has it`s drawback, negative response would be much more preferable.

if (!cgsiResponse.isOk())
		responseMap.put(connector, '' + cgsiResponse.getErrorNumber() + ' :: '
				+ cgsiResponse.getMessageErreur());
	else
		responseMap.put(connector, 'Message successfuly processed');

Here is the exception that was thrown

ERROR-414: JavaScript Connector error
ERROR MESSAGE:	Error executing script: 
java.lang.ClassCastException: com.webreach.mirth.model.Response cannot be cast to java.lang.String
	at com.webreach.mirth.connectors.js.JavaScriptMessageDispatcher.doDispatch(JavaScriptMessageDispatcher.java:80)
	at com.webreach.mirth.connectors.js.JavaScriptMessageDispatcher.doSend(JavaScriptMessageDispatcher.java:99)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:178)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1286
Reporter: santaroga
Created: 2010-01-04T10:58:13.000-0800

**Comment by rbeckman-nextgen** [comment]
Added if the response is a String or Response object and handle it accordingly.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-03-29T11:08:05.000-0700
