### ISSUE TITLE
MSH Parsing error

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#129]
As a first step in connecting to a production ADT system I'm tryiing to simply store a message to a file.  I basically am using the example LLP 2 file example and storing the HL7 message.  It works fine when I use some sample messages.  When I use a message from the production system I get MSH parsing errors indication that '|' is incorrect. 

The exception is below.  If you need the HL7 file I can send that.

Thanks in advance.

INFO  com.webreach.mirth.server.Mirth: starting mirth server...
Mirth 1.1.0 (August 28, 2006) server successfully started: Wed Oct 18 16:24:56 E
DT 2006
Running Java 1.5.0_08 on Windows XP (5.1, x86)
INFO  com.webreach.mirth.server.mule.util.ER7Util: Unable to convert message to
XML (Possibly already in XML or Invalid HL7)
ERROR com.webreach.mirth.server.mule.filters.JavaScriptFilter: org.mozilla.javas
cript.EcmaError: TypeError: error: Unexpected character encountered (lex state 3
): '|' (<cmd>#2)
ca.uhn.hl7v2.HL7Exception: Couldn't create MSH for version 2.1  (does your class
path include this version?) ...
        at ca.uhn.hl7v2.parser.Parser.makeControlMSH(Parser.java:299)
        at ca.uhn.hl7v2.parser.PipeParser.getCriticalResponseData(PipeParser.jav
a:635)
        at com.webreach.mirth.util.ACKGenerator.generateAckResponse(ACKGenerator
.java:37)
        at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.generateACK(TcpMe
ssageReceiver.java:285)
        at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.processData(TcpMe
ssageReceiver.java:275)
        at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.run(TcpMessageRec
eiver.java:250)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Wor
ker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Wor
ker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: The version 2.1  is not recognize
d
        at ca.uhn.hl7v2.model.GenericMessage.getGenericMessageClass(GenericMessa
ge.java:38)
        at ca.uhn.hl7v2.parser.Parser.makeControlMSH(Parser.java:289)
        ... 9 more
ERROR org.mule.impl.DefaultExceptionStrategy: Caught exception in Exception Stra
tegy: Can't parse critical fields from MSH segment (ca.uhn.hl7v2.HL7Exception: C
ouldn't create MSH for version 2.1  (does your classpath include this version?)
... ): MSH|^~\&|ADL|LHH|EAD|BEN|200609260920||ADT^A01|20060926092025|T|2.1
ca.uhn.hl7v2.HL7Exception: Can't parse critical fields from MSH segment (ca.uhn.
hl7v2.HL7Exception: Couldn't create MSH for version 2.1  (does your classpath in
clude this version?) ... ): MSH|^~\&|ADL|LHH|EAD|BEN|200609260920||ADT^A01|20060
926092025|T|2.1
        at ca.uhn.hl7v2.parser.PipeParser.getCriticalResponseData(PipeParser.jav
a:643)
        at com.webreach.mirth.util.ACKGenerator.generateAckResponse(ACKGenerator
.java:37)
        at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.generateACK(TcpMe
ssageReceiver.java:285)
        at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.processData(TcpMe
ssageReceiver.java:275)
        at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.run(TcpMessageRec
eiver.java:250)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Wor
ker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Wor
ker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Unknown Source)
WARN  org.mule.config.ExceptionHelper: Failed to load error mappings from: META-
INF/services/org/mule/config/tcp-exception-mappings.properties. This may be beca
use there are no error code mappings for protocol: tcp

Imported Issue. Original Details:
Jira Issue Key: MIRTH-107
Reporter: toledoj
Created: 2006-10-19T04:30:14.000-0700

**Comment by rbeckman-nextgen** [comment]
1.2 will allow you to use a preprocessor to fix-up any invalid HL7.

Imported Comment. Original Details:
Author: chrisl
Created: 2006-10-31T01:30:58.000-0800
