### ISSUE TITLE
Error in Server

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1305]
Below is error message from 
X:\Program Files\Mirth\logs\Mirth.log.1

This error had been going on for some time - since 00:21 (12:21am) this morning.  I did a deploy-all and none of the channels would restart.  I had to stop the Mirth service and restart it.  Then everything worked.  Here's the error message:

ERROR 2010-01-13 16:00:20,793 [052cfbef-ca2c-4ed8-af5a-54b6caad052d_destination_1_connector_queue_thread] com.webreach.mirth.server.controllers.DefaultMessageObjectController: could not log message: id=60577c11-ac26-4abf-a636-9bd2c2317667
com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in derby/derby-message.xml.  
--- The error occurred while applying a parameter map.  
--- Check the Message.getMessageCount-InlineParameterMap.  
--- Check the statement (query failed).  
--- Cause: java.sql.SQLException: The conglomerate (31,425) requested does not exist.
Caused by: java.sql.SQLException: The conglomerate (31,425) requested does not exist.
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryWithCallback(GeneralStatement.java:185)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForObject(GeneralStatement.java:104)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:566)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForObject(SqlMapClientImpl.java:83)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.writeMessageToDatabase(DefaultMessageObjectController.java:254)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.updateMessage(DefaultMessageObjectController.java:204)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setStatus(DefaultMessageObjectController.java:845)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setSuccess(DefaultMessageObjectController.java:771)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.manageResponseAck(MllpMessageDispatcher.java:375)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.sendPayload(MllpMessageDispatcher.java:310)
	at org.mule.providers.QueueEnabledConnector$QueueWorker.run(QueueEnabledConnector.java:199)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: The conglomerate (31,425) requested does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.execute(Unknown Source)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:186)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteQuery(GeneralStatement.java:205)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryWithCallback(GeneralStatement.java:173)
	... 13 more
Caused by: java.sql.SQLException: The conglomerate (31,425) requested does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 25 more

Caused by: 
java.sql.SQLException: The conglomerate (31,425) requested does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.execute(Unknown Source)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:186)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteQuery(GeneralStatement.java:205)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryWithCallback(GeneralStatement.java:173)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForObject(GeneralStatement.java:104)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:566)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForObject(SqlMapClientImpl.java:83)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.writeMessageToDatabase(DefaultMessageObjectController.java:254)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.updateMessage(DefaultMessageObjectController.java:204)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setStatus(DefaultMessageObjectController.java:845)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setSuccess(DefaultMessageObjectController.java:771)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.manageResponseAck(MllpMessageDispatcher.java:375)
	at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.sendPayload(MllpMessageDispatcher.java:310)
	at org.mule.providers.QueueEnabledConnector$QueueWorker.run(QueueEnabledConnector.java:199)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: The conglomerate (31,425) requested does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 25 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1305
Reporter: jim
Created: 2010-01-13T14:59:52.000-0800

**Comment by rbeckman-nextgen** [comment]
Looks like an issue with derby.  We do not recommend using derby as the Mirth database in production.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-02-02T13:34:23.000-0800
