### ISSUE TITLE
 Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.tcp.TcpConnector@2f54, endpointUri=tcp://192.168.1.207:7001,

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1308]
I am sending data on TCPListener of Mirth  , using java program .but following exception comes.
[2010-01-15 11:46:42,307]  
ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: 734b1001-b5da-4fe6-91a7-af2a5ad25ff5: org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.tcp.TcpConnector@2f54,endpointUri=tcp://192.168.1.207:7001, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_tcpEndpoint#-1056770793', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@70cdd2, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. 
Message payload is of type: java.lang.String
org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.tcp.TcpConnector@2f54,endpointUri=tcp://192.168.1.207:7001, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_tcpEndpoint#-1056770793', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@70cdd2, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:83)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at com.webreach.mirth.connectors.tcp.TcpMessageReceiver$TcpWorker.processData(TcpMessageReceiver.java:308)
	at com.webreach.mirth.connectors.tcp.TcpMessageReceiver$TcpWorker.run(TcpMessageReceiver.java:266)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:595)Caused by: org.mule.umo.transformer.TransformerException: 
CHANNEL:
	TCP Listener
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
LINE NUMBER:
	0

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1308
Reporter: rpatil
Created: 2010-01-14T22:18:21.000-0800

**Comment by rbeckman-nextgen** [comment]
You will need to post on the forums or contact Mirth for professional support.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-01-15T13:47:43.000-0800
