### ISSUE TITLE
SOAP SENDER error:The entity name must immediately follow the '&amp;' 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1317]
The error Below is generated when the channel attempts to take a HL7 message and send it to the Quest Server via the SOAP Sender.  All is set up according to the information gleaned from the documentation.  At the bottom of this report is the XML Channel File.

An independently generated client via SOAPUI, WSDL2JAVA, etc works fine utilizing the same HL7 file.  If I am missing something, what am I missing??

Error Output:

ERROR-410: SOAP Connector error
ERROR MESSAGE:	Error invoking WebService
AxisFault
 faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server.userException
 faultSubcode: 
 faultString: org.xml.sax.SAXParseException: The entity name must immediately follow the '&amp;' in the entity reference.
 faultActor: 
 faultNode: 
 faultDetail: 
	{http://xml.apache.org/axis/}stackTrace:org.xml.sax.SAXParseException: The entity name must immediately follow the '&amp;' in the entity reference.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.client.Call.invoke(Call.java:2698)
	at org.apache.axis.client.Call.invoke(Call.java:1870)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.invokeWebService(AxisMessageDispatcher.java:295)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.doSend(AxisMessageDispatcher.java:330)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:233)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:123)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)

	{http://xml.apache.org/axis/}hostname:PaulC-PC

org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.
	at org.apache.axis.AxisFault.makeFault(AxisFault.java:101)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:701)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.client.Call.invoke(Call.java:2698)
	at org.apache.axis.client.Call.invoke(Call.java:1870)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.invokeWebService(AxisMessageDispatcher.java:295)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.doSend(AxisMessageDispatcher.java:330)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:233)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:123)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	... 29 more

Channel Export:

<com.webreach.mirth.model.Channel>
  <id>59d5c872-4ed6-4f39-ad5f-7bb9a9f8a7ab</id>
  <name>validate Orders</name>
  <description></description>
  <enabled>true</enabled>
  <version>1.8.2.4472</version>
  <lastModified>
    <time>1264530562842</time>
    <timezone>America/New_York</timezone>
  </lastModified>
  <revision>12</revision>
  <sourceConnector>
    <name>sourceConnector</name>
    <properties>
      <property name="validateConnections">1</property>
      <property name="DataType">File Reader</property>
      <property name="pollingFrequency">1000</property>
      <property name="scheme">file</property>
      <property name="moveToDirectory">G:/Development Area/Mirthtest Directories/Sample_orders_out</property>
      <property name="passive">1</property>
      <property name="secure">1</property>
      <property name="moveToErrorDirectory"></property>
      <property name="fileFilter">*.hl7</property>
      <property name="username">anonymous</property>
      <property name="password">anonymous</property>
      <property name="binary">0</property>
      <property name="FTPAnonymous">1</property>
      <property name="regex">0</property>
      <property name="processBatchFiles">0</property>
      <property name="autoDelete">0</property>
      <property name="charsetEncoding">DEFAULT_ENCODING</property>
      <property name="moveToPattern">${ORIGINALNAME}</property>
      <property name="sortAttribute">date</property>
      <property name="fileAge">0</property>
      <property name="host">G:/Development Area/Mirthtest Directories/Sample_orders_in</property>
      <property name="checkFileAge">0</property>
      <property name="pollingType">interval</property>
    </properties>
    <transformer>
      <steps/>
      <inboundProtocol>HL7V2</inboundProtocol>
      <outboundProtocol>HL7V2</outboundProtocol>
    </transformer>
    <filter>
      <rules/>
    </filter>
    <transportName>File Reader</transportName>
    <mode>SOURCE</mode>
    <enabled>true</enabled>
  </sourceConnector>
  <destinationConnectors>
    <com.webreach.mirth.model.Connector>
      <name>Destination 1</name>
      <properties>
        <property name="soapGenerateEnvelope">1</property>
        <property name="soapEnvelope">&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:soapenc=&quot;http://schemas.xmlsoap.org/soap/encoding/&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
&lt;soap:Body&gt;&#x0D;
  &lt;submitOrder xmlns=&quot;http://medplus.com/orders&quot;&gt;&#x0D;
    &lt;order xmlns=&quot;java:com.medplus.serviceHub.orders.webservice&quot;&gt;&#x0D;
      &lt;hl7Order&gt;${message.rawData}&lt;/hl7Order&gt;&#x0D;
    &lt;/order&gt;&#x0D;
  &lt;/submitOrder&gt;&#x0D;
&lt;/soap:Body&gt;&#x0D;
&lt;/soap:Envelope&gt;</property>
        <property name="host">axis:https://mzealtest:customer1@cert.hub.care360.com/orders/service?method=submitOrder</property>
        <property name="DataType">SOAP Sender</property>
        <property name="definition">H4sIAAAAAAAAAO1YTWwbRRQeO3biOCn5qSi0VaU0bSgtdDclVZES0ZImQTU4PySFolBEx/Yk3rLe3e6O600RVJXoiXOFOHCs4MCRCiRO0AO0F34uVEhcENciVZyKOPDe7P967SYVSotUSx6vZ9+bee97PzPvfX6bZC2TPF3Wa1KDlUxGy1WpppgcRr3CVKlhSaeWptmKoilc0bVvv/9y+0fHPvg9TTqKpBe4DJXZJ9cMZnHSVzxLz1O5zhVVnqXGRJHkdYOZFPmsc+R9kiqSQYuZ55Uym9Eqhq5o/LXFAieDDqNKtVV5iZuKtjphGyDVAE5LuJ50glpVWDPb9es317ed+amDpF8ieVWnlZdometmgXTzqsmsqq5WbOPYiwQ/vY0cjP3w7eLkiUnTpGvzK4vMMkActmCibHwNthnWzVWJGqA5A3WVFcmCpxqVpgLtiPNJpUlXgeQoLjWt1JZJt2JNamLlIukW00jNyU6hkS3bNVXWaA32pGUmvzoHjwDLYy5uU7rGmcY52VcEEWRHBBlFkB0R5KkIIbBmcDXEMl0k/RY7V2cagKmyGrwGEzweMoEjlmIhW46DWHMua842ye4WOi+JH1Qid2bg6J0fPh1KE2IbqHsKoNou1JJALclXSxJqXap9dvCfid9U4Rjdql6m6gI1uStqr08NBnfnOg0T3MoW/2yDk/64aTg5hNuNo2/WWMVQ65bkus+JeklaMWHNhm6+g47rzgMEBMQcaW9RF87AqCBNN7NxDlyVk+FW5phBGgtoANIecDfw1bLDsrcVy2JABU5ttHG3EGUgGYCZpxzmS3XORBDlwQlK1HIsmeAEgkaEz9YgfHxfsC/9vOvj7+gnHSRVIBlLucAc4zYyMOaBaaiFdJOeEIFsqYhsUefDeOW0pLKJuCj+m61f943sfvmPr9YVyzkRy1n4dggNt3DSAe6DjwNi8GbDUbi/yrkxLrumsNBtLZ0aEpoKH2TATa9AupFDS+AwzMlQG96GVVHlyK6Dcd998y180x8hyiAfJ7vclRuNhtQYEws+Nzo6irlCs6LL7myzPycj9xIR3zsL2ra3ZFa4Av7ZE2z1JELsuICIx86m2QCbzkAxTrbMmxVmesoLoi5hL0M8D7ZxKD+WAoeCRGMg21ib7cc4OdguK+gokBVKCb6L9IXFM4IZ3Cft+/9TrRJjNMxaRQEuuNNuHeQue/RMyS6TnKaoKkYFrFauKmrFPVP7QzHl5vIeFqzhJoHwqRBL9Tj2pFoAysHS4rwN/D3qlYfkN2aLzpngWrzXcD0ctwjMMhNz911NcZv1tvRVbQ7eDDfrYnokOu2pF6b2d43SdtcUbb5crptW8/KpQ0n01E6mx2ExQRju4h6nncJh2gk3MftCK9hj1BBGHqivU7UeQvX0elHFoZAk1CtxBXCYTaI8nUS5sC5QcDi5bspT9wIvhFJfJNkszU8uzNhlZvg3ynA0n/XR9k6zjRmhC/zZoqsh+OFSIg6u8eDWgwl2c+xhPIz2OIuD6QK27ThcQyDnLjmJNukUEEpc9C2QuS/D9JruylNQkQQ0lzcxOC4/NMbYIHY9Hnaz1mpAcmUTobvyP4IucrcZNKN3OgXSg095dRMRvPpAEQxhslHng8sF5fUQatc2EbVrD43fheC5GHawrLg8N6XL6xs7xyA/Yjl45PBxRaPmWhj/XFV9PthDCHATh/HNscDNB2qBG8kWuB4AADcKtynkNJ18S6RSiYYUk4NOZbMt0Ug7WmDaEaw3lCTrMA57kiajd8+cc1t3isvpGP1+HA7EJp/F4WATCnJsw3gBeKtNiN+CulTcirBfV4cL09uluqJyRbMknHH2EuSZpkZcGk4kq16qKdzxS5Psa995nPcaiD8+8+EvJ/M7/k6TziLprDIK7FDhF4Fd9thlwS4LdqiA5VNLCxSbRJyZUDf1OUxzXicKJUxHa6duLfYyb3gLCIWOFckWvAFOii6N18qCqlUE7m1OtrtVlFeYonRORdrkL/dU3Zf9i7ED8uKFo3fTpHeZZObqqrpMsqLNsUy63FZiIVTIFEJFUKSy7BOV5UJcpU6VQQVYTcAjb/ntQE72tGpxBT1DbFB65RGwZ89jOeNiBJoT75MYPH85BCkRgA6iN8V4A87ive+6t3PJpI1pyul72DLM6v9FBo1lC7Hxo4yZlDH9vwO2l0HBxEqFchacM38KI6R68flOC0vfvy84u4vnu48M/6AMb3MiuosW5LoyJGKpWi9JZWqysSOjmPTGDx8ecxOf7Pbh/gUHifa5ahoAAA==</property>
        <property name="replyChannelId">sink</property>
        <property name="rotateQueue">0</property>
        <property name="serviceEndpoint">https://mzealtest:customer1@cert.hub.care360.com/orders/service</property>
        <property name="attachmentContents">&lt;list/&gt;</property>
        <property name="attachmentTypes">&lt;list/&gt;</property>
        <property name="reconnectMillisecs">10000</property>
        <property name="wsdlUrl">https://mzealtest:customer1@cert.hub.care360.com/orders/service?wsdl</property>
        <property name="method">submitOrder</property>
        <property name="attachmentNames">&lt;list/&gt;</property>
        <property name="soapActionURI"></property>
        <property name="usePersistentQueues">0</property>
      </properties>
      <transformer>
        <steps/>
        <inboundTemplate></inboundTemplate>
        <outboundTemplate></outboundTemplate>
        <inboundProtocol>HL7V2</inboundProtocol>
        <outboundProtocol>HL7V2</outboundProtocol>
        <inboundProperties/>
        <outboundProperties/>
      </transformer>
      <filter>
        <rules/>
      </filter>
      <transportName>SOAP Sender</transportName>
      <mode>DESTINATION</mode>
      <enabled>true</enabled>
    </com.webreach.mirth.model.Connector>
  </destinationConnectors>
  <properties>
    <property name="synchronous">true</property>
    <property name="encryptData">false</property>
    <property name="dont_store_filtered">false</property>
    <property name="store_messages">true</property>
    <property name="initialState">started</property>
    <property name="max_message_age">-1</property>
    <property name="transactional">false</property>
    <property name="error_messages_only">false</property>
  </properties>
  <preprocessingScript>// Modify the message variable below to pre process data
return message;</preprocessingScript>
  <postprocessingScript>// This script executes once after a message has been processed
return;</postprocessingScript>
  <deployScript>// This script executes once when the mule engine is started
// You only have access to the globalMap here to persist data
return;</deployScript>
  <shutdownScript>// This script executes once when the mule engine is stopped
// You only have access to the globalMap here to persist data
return;</shutdownScript>
</com.webreach.mirth.model.Channel>

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1317
Reporter: paulnc2008
Created: 2010-01-26T10:44:23.000-0800

**Comment by rbeckman-nextgen** [comment]
You might need to wrap your message in CDATA.  The SOAP Connector has also been completely rewritten for 2.0, so if this is a different error it will not exist in the next release.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-02-02T13:33:17.000-0800
