### ISSUE TITLE
FileMessageReceiver Null Pointer

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1346]
I was testing something else and ran into a null pointer w/ the most recent changes from Trunk. To recreate this:

* Attempt to deploy a FileMessageReceiver channel

Error:

ERROR 2010-02-20 18:02:20,041 [main] com.webreach.mirth.server.Mirth: Error deploying channels.
org.mule.umo.lifecycle.InitialisationException: Failed to create "Message Receiver" with "com.webreach.mirth.connectors.file.FileMessageReceiver"
	at com.webreach.mirth.connectors.file.FileConnector.createReceiver(FileConnector.java:242)
	at org.mule.providers.AbstractConnector.registerListener(AbstractConnector.java:503)
	at org.mule.impl.model.AbstractModel.registerListeners(AbstractModel.java:220)
	at org.mule.impl.model.AbstractModel.registerComponent(AbstractModel.java:180)
	at com.webreach.mirth.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:197)
	at com.webreach.mirth.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:175)
	at com.webreach.mirth.server.Mirth.deployChannels(Mirth.java:214)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:122)
	at com.webreach.mirth.server.Mirth.main(Mirth.java:82)
Caused by: org.mule.providers.service.ConnectorServiceException: Failed to create "Message Receiver" with "file"
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageReceiver(ConnectorServiceDescriptor.java:321)
	at com.webreach.mirth.connectors.file.FileConnector.createReceiver(FileConnector.java:239)
	... 8 more
Caused by: java.lang.NullPointerException
	at com.webreach.mirth.connectors.file.FileMessageReceiver.<init>(FileMessageReceiver.java:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:271)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:278)
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageReceiver(ConnectorServiceDescriptor.java:319)
	... 9 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1346
Reporter: malcomm
Created: 2010-02-20T18:04:47.000-0800

**Comment by rbeckman-nextgen** [comment]
Simple change; from this:

        this.readDir = replacer.replaceValues(readDir, fileConnector.getChannelId());
        this.moveDir = replacer.replaceValues(moveDir, fileConnector.getChannelId());
        this.moveToPattern = replacer.replaceValues(moveToPattern, fileConnector.getChannelId());
        this.errorDir = replacer.replaceValues(errorDir, fileConnector.getChannelId());

        this.fileConnector = (FileConnector) connector;

To this:

        this.fileConnector = (FileConnector) connector;

        this.readDir = replacer.replaceValues(readDir, fileConnector.getChannelId());
        this.moveDir = replacer.replaceValues(moveDir, fileConnector.getChannelId());
        this.moveToPattern = replacer.replaceValues(moveToPattern, fileConnector.getChannelId());
        this.errorDir = replacer.replaceValues(errorDir, fileConnector.getChannelId());

Imported Comment. Original Details:
Author: malcomm
Created: 2010-02-20T18:05:57.000-0800

**Comment by rbeckman-nextgen** [comment]
Applied patch.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-03-12T10:42:54.000-0800
