### ISSUE TITLE
Big DICOM files fail with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1352]
While processing a large DICOM file, I get the following error and the DICOM file sent by the Destination to DCM4chee gets corrupted. This is a Mammogram file of about 8MB. This is a bit urgent so if you can suggest a workaround, that will be great! My channel source is set to listening to a port for DICOM files and the channel destination writes the DICOM file to another port on the same machine (on which DCM4chee is listening)

[2010-02-24 13:20:55,374]  ERROR (com.webreach.mirth.server.util.AttachmentUtil:54): Error merging DICOM data
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.RangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at com.webreach.mirth.server.util.DICOMUtil.getDICOMRawData(DICOMUtil.java:48)
    at org.mule.providers.TemplateValueReplacer.loadContextFromMessageObject(TemplateValueReplacer.java:125)
    at org.mule.providers.TemplateValueReplacer.replaceValues(TemplateValueReplacer.java:61)
    at org.mule.providers.TemplateValueReplacer.replaceValues(TemplateValueReplacer.java:55)
    at com.webreach.mirth.connectors.dimse.DICOMMessageDispatcher.doSend(DICOMMessageDispatcher.java:52)
    at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
    at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
    at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
    at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
    at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:52)
    at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
    at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
    at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
    at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
    at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
    at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
    at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
    at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
    at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
    at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
    at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
    at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
    at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:202)
    at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
    at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
    at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
    at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1352
Reporter: cuberoy
Created: 2010-02-24T19:32:55.000-0800

**Comment by rbeckman-nextgen** [comment]
Hey Chetan, would it be possible to send me the DICOM image that failed? Email me at bradd@mirthcorp.com

-Brad

Imported Comment. Original Details:
Author: bradd
Created: 2010-03-31T15:25:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Cannot reproduce without the DICOM image that is failing.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-04-08T13:39:12.000-0700
