### ISSUE TITLE
Error thrown when using Saxon XSLT jars

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1361]
Mirth 1.8.2.x throws an error when the Saxon XSLT jars (saxon9.jar, saxon9-dom.jar) are put in the classpath (.../lib/custom). The Saxon jars allow the use of XSLT 2.0 functionalty.

When the .jars are present, the error below is thrown. In version 1.8.0, this error did not occur.

It appears that the reference to the "indent-number" attribute in com.webreach.mirth.model.converters.DocumentSerializer.java causes this error. It would be helpful if this attribute reference can be made optionl via a property or have the code updated accommodate the presence of the Saxon jars.

`
INFO 2010-03-05 17:09:44,830 [Thread-1] com.webreach.mirth.server.Mirth: starti
ng mirth server...
ERROR 2010-03-05 17:09:45,387 [Thread-1] com.webreach.mirth.model.converters.Doc
umentSerializer: Unknown attribute indent-number
Exception in thread "Thread-1" java.lang.RuntimeException: java.lang.RuntimeExce
ption: Error occurred. Cause: com.ibatis.common.xml.NodeletException: Error par
sing XML. Cause: org.xml.sax.SAXParseException: Premature end of file.
at com.webreach.mirth.server.util.SqlConfig.getSqlMap Client(SqlConfig.ja
va:77)
at com.webreach.mirth.server.controllers.DefaultMessa geObjectController.
removeAllFilterTables(DefaultMessageObjectControll er.java:90)
at com.webreach.mirth.server.Mirth.startup(Mirth.java :166)
at com.webreach.mirth.server.Mirth.run(Mirth.java:130 )
Caused by: java.lang.RuntimeException: Error occurred. Cause: com.ibatis.common
.xml.NodeletException: Error parsing XML. Cause: org.xml.sax.SAXParseException:
Premature end of file.
at com.ibatis.sqlmap.engine.builder.xml.SqlMapConfigP arser.parse(SqlMapC
onfigParser.java:84)
at com.ibatis.sqlmap.client.SqlMapClientBuilder.build SqlMapClient(SqlMap
ClientBuilder.java:62)
at com.webreach.mirth.server.util.SqlConfig.getSqlMap Client(SqlConfig.ja
va:74)
... 3 more
Caused by: com.ibatis.common.xml.NodeletException: Error parsing XML. Cause: or
g.xml.sax.SAXParseException: Premature end of file.
at com.ibatis.common.xml.NodeletParser.parse(NodeletP arser.java:52)
at com.ibatis.sqlmap.engine.builder.xml.SqlMapConfigP arser.parse(SqlMapC
onfigParser.java:81)
... 5 more
Caused by: org.xml.sax.SAXParseException: Premature end of file.
at org.apache.xerces.util.ErrorHandlerWrapper.createS AXParseException(Un
known Source)
at org.apache.xerces.util.ErrorHandlerWrapper.fatalEr ror(Unknown Source)

at org.apache.xerces.impl.XMLErrorReporter.reportErro r(Unknown Source)
at org.apache.xerces.impl.XMLErrorReporter.reportErro r(Unknown Source)
at org.apache.xerces.impl.XMLVersionDetector.determin eDocVersion(Unknown
Source)
at org.apache.xerces.parsers.XML11Configuration.parse (Unknown Source)
at org.apache.xerces.parsers.XML11Configuration.parse (Unknown Source)
at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(U nknown Source)
at com.ibatis.common.xml.NodeletParser.createDocument (NodeletParser.java
:147)
at com.ibatis.common.xml.NodeletParser.parse(NodeletP arser.java:49)
... 6 more
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1362
Reporter: rhilado
Created: 2010-03-10T16:37:22.000-0800

**Comment by rbeckman-nextgen** [comment]
Based on the error, it looks like Saxon is overwriting javax.xml.transform.TransformerFactory.  Can you look at the jar and verify this class or namespaces exists in Saxon?  If so, can you try a newer version that does not use this namespace?  Please provide a link to the jar you are using.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-03-22T14:31:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Yes, it appears that Saxon implements the abstract methods on both the javax.xml.transform.TransformerFactory and javax.xml.transform.sax.SAXTransformerFactory. This can be seen in the sourcecode  net/sf/saxon/TransformerFactoryImpl.java.

Unfortunately, both the old version 9.1 (Saxon-B) and the new version 9.2 (SaxonHE - home edition) implement this method and cause this error.

The .jar files and source code can be downloaded from:
http://saxon.sourceforge.net/#F9.2HE

I'm currently using 9.1 (Saxon-B), but will be moving to the new version at some point.

Imported Comment. Original Details:
Author: rhilado
Created: 2010-03-22T15:17:20.000-0700

**Comment by rbeckman-nextgen** [comment]
FYI: Regarding moving to SaxonHE, after further review, I probably won't move to SaxonHE. Many of the most valuable features (extensions) have been taken out of Saxon-B, and now only available in SaxonPE and SaxonEE. Unfortunate. So I'll be sticking with Saxon-B for a while.

Imported Comment. Original Details:
Author: rhilado
Created: 2010-03-22T15:26:38.000-0700

**Comment by rbeckman-nextgen** [comment]
Added a try-catch around setting the indent-number attribute to handle the error when Saxon-B is on the classpath.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-03-26T14:05:20.000-0700
