### ISSUE TITLE
Operations on files that do not match the input filename pattern

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1373]
We have a channel with an Input filename pattern: PKOUT*.TXT

We frequentely find messages in the error log like this one:

INFO   | jvm 1    | 2010/03/25 09:48:46 | ERROR 2010-03-25 09:48:46,228 [7553a877-5738-4fae-8d31-617cc0647a5d_source_connector._fileEndpoint#1545075378.receiver.1] org.mule.impl.DefaultComponentExceptionStrategy: Caught exception in Exception Strategy for: 7553a877-5738-4fae-8d31-617cc0647a5d: org.mule.MuleException: Failed to move file "//fpffe01/rotomat$/export/mirth_in/PKOUT03252010094846.NEW" to "//fpffe01/rotomat$/export/mirth_bak/PKOUT03252010094846.NEW".  The file already exists.
INFO   | jvm 1    | 2010/03/25 09:48:46 | org.mule.MuleException: Failed to move file "//fpffe01/rotomat$/export/mirth_in/PKOUT03252010094846.NEW" to "//fpffe01/rotomat$/export/mirth_bak/PKOUT03252010094846.NEW".  The file already exists.
INFO   | jvm 1    | 2010/03/25 09:48:46 | 	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:261)
INFO   | jvm 1    | 2010/03/25 09:48:46 | 	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:123)
INFO   | jvm 1    | 2010/03/25 09:48:46 | 	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
INFO   | jvm 1    | 2010/03/25 09:48:46 | 	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
INFO   | jvm 1    | 2010/03/25 09:48:46 | 	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
INFO   | jvm 1    | 2010/03/25 09:48:46 | 	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
INFO   | jvm 1    | 2010/03/25 09:48:46 | 	at java.lang.Thread.run(Unknown Source)

So the channel tries to process files named *.NEW,  althoug this should not be the case !

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1374
Reporter: mourisj
Created: 2010-03-26T07:36:05.000-0700

**Comment by rbeckman-nextgen** [comment]
There is no process that should process *.NEW file, except the process that creates them. 
Some application writes in the temporary file PKOUT**.NEW; when done, it rename the file to PKOUT**.TXT
This file should the be processed by Mirth.

There ARE *.NEW files in the mirth_bak folder, but none with the name specified !!

So the error is a double error: 

- *.NEW files should not be processed
- * the error is displayed for files that actually are not there !

The application generates files with unique names, so it is not possible to have duplicates on filenames.

Imported Comment. Original Details:
Author: mourisj
Created: 2010-03-26T07:46:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Updated to use WildcardFileFilter from commons-io which handles patterns correctly.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-03-29T11:31:03.000-0700
