### ISSUE TITLE
Message Trees not functioning properly

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1412]
After adding message template the message tree is not populated

Stack trace:

Could not launch from cache. Will try online mode. [Some of required resources are not cached.]
Exception in thread "Timer-3" java.lang.NoClassDefFoundError: org/apache/xerces/parsers/SAXParser
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.mirth.connect.model.converters.ER7Serializer.toXML(ER7Serializer.java:123)
	at com.mirth.connect.model.converters.ER7Serializer.toXML(ER7Serializer.java:34)
	at com.mirth.connect.client.ui.TreePanel.setMessage(TreePanel.java:352)
	at com.mirth.connect.client.ui.TemplatePanel$1UpdateTimer.run(TemplatePanel.java:196)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.xerces.parsers.SAXParser
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1413
Reporter: bradd
Created: 2010-05-04T11:07:26.000-0700

**Comment by rbeckman-nextgen** [comment]
This occurs when the client is webstarted, because xercesImpl is not included in the jnlp.  ER7Seralizer calls ER7Reader, which needs xercesImpl.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-05-04T11:33:10.000-0700

**Comment by rbeckman-nextgen** [comment]
Added xercesImpl-2.9.1.jar back to the client and the jnlp.  ER7Serializer is called by the message tree, which calls ER7Reader, which uses xercesImpl.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-05-04T12:24:49.000-0700
