### ISSUE TITLE
InstanceAlreadyExistsException at channel deployment

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1417]
I created a simple test channel, that picks local files and sends an email with the file content.
When I tried deploying, it did not deploy, for an authentic reason. When I rectified that, and tried to redeploy, I have been getting this error and the channel doesnt deploy.

[2010-05-10 14:03:15,468]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:174): Error registering channel.
javax.management.InstanceAlreadyExistsException: MirthConfiguration:type=control,name=c97e329b-c47c-4db1-9be0-2ccdbeac37e6_source_connectorService
	at com.sun.jmx.mbeanserver.Repository.addMBean(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.internal_addObject(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source)
	at org.mule.management.agents.JmxAgent.registerConnectorService(JmxAgent.java:436)
	at com.mirth.connect.server.controllers.MuleEngineController.registerConnector(MuleEngineController.java:485)
	at com.mirth.connect.server.controllers.MuleEngineController.configureInboundRouter(MuleEngineController.java:245)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:201)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:172)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:222)
	at com.mirth.connect.server.Mirth.run(Mirth.java:130)

[2010-05-10 14:03:15,468]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:564): Error unregistering channel component.
org.mule.umo.model.ModelException: The required object/property "UMO Descriptor" is null
	at org.mule.impl.model.AbstractModel.unregisterComponent(AbstractModel.java:188)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterChannel(MuleEngineController.java:562)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:177)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:222)
	at com.mirth.connect.server.Mirth.run(Mirth.java:130)

How do we get rid of this?

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1418
Reporter: deepa
Created: 2010-05-10T14:10:22.000-0700

**Comment by rbeckman-nextgen** [comment]
You can restart the server to fix this issue.  That being said, can you give the channel(s) and/or steps to reproduce this error so it can be fixed permanently?

Imported Comment. Original Details:
Author: jacobb
Created: 2010-05-10T15:18:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Yes the restart worked. Thanks.

And these are the steps to reproduce the error, check out the pics attached :
1. Create a simple channel, File reader src connector and Email sender destination. 
2. Set the 'Use server settings' option ON (refer to settings2 jpg). But on the general settings, do not have the email server settings updated yet (refer to settings1.jpg).
Try to deploy the channel and you should get this error.


Imported Comment. Original Details:
Author: deepa
Created: 2010-05-10T16:29:01.000-0700

**Comment by rbeckman-nextgen** [comment]
Settings1 - General settings on Mirth Admin 
Settings2 - Settings on the destination connector

Imported Comment. Original Details:
Author: deepa
Created: 2010-05-10T16:29:47.000-0700

**Comment by rbeckman-nextgen** [comment]
Added try/catch around the endpoint/connector registration so that descriptor registration continues. This allows the unregister reference to the descriptor not cause an NPE.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-05-14T11:45:17.000-0700

**Comment by rbeckman-nextgen** [comment]
Still occurs after this exception:

[2010-07-08 18:12:42,769]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:237): Failed to configure outbound router.
java.net.URISyntaxException: Illegal character in path at index 37: file:///MirthTraining/outbox/Hospital A
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.mirth.connect.server.controllers.MuleEngineController.configureOutboundRouter(MuleEngineController.java:350)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:235)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:176)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:226)
	at com.mirth.connect.server.Mirth.run(Mirth.java:134)

Imported Comment. Original Details:
Author: mitchd
Created: 2010-07-08T18:15:04.000-0700

**Comment by rbeckman-nextgen** [comment]
Moved connector registration to the end of configureInboundRouter so that if endpoint parsing fails it won't register the service.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-07-09T15:25:59.000-0700

**Comment by rbeckman-nextgen** [comment]
I am using Mac OS X and 2.0.0.4999 (RC1) and I'm getting the same error. Requires a restart to work but on any modification it won't redeploy. Perhaps the issue should be reopened?

Imported Comment. Original Details:
Author: simonmd
Created: 2010-09-03T14:48:38.000-0700

**Comment by rbeckman-nextgen** [comment]
Simon, what error did you put in your channel to reproduce it?

Imported Comment. Original Details:
Author: jacobb
Created: 2010-09-07T10:46:27.000-0700

**Comment by rbeckman-nextgen** [comment]
Any updates on what still causes this issue in the RC?

Imported Comment. Original Details:
Author: jacobb
Created: 2010-09-09T13:58:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Report from a user of RC1:

"I have setup a JMS writer.  When I started Mirth Connect, my ActiveMQ server was not running... this caused Mirth Connect not to deploy my channel ... I don't know if this is the expected behaviour ?

Afterwards I start my ActiveMQ server, and I do a Redeploy all channels ... but the channel with my JMS writer still doesn't get deployed ...

"Failed to configure outbound router.
javax.management.InstanceAlreadyExistsException: MirthConfiguration:type=control,name=430bebca-bb4d-4d4a-a6e9-1066a5155d14_destination_1_connectorService"

Only restarting Mirth Connect completely solved the issue."


Imported Comment. Original Details:
Author: jacobb
Created: 2010-09-20T11:25:14.000-0700

**Comment by rbeckman-nextgen** [comment]
Added exception handling in configureInboundRouter and configureOutboundRouter so that the routers are added to the descriptor before throwing an exception.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-09-21T11:59:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Found it once again when changing the endpoint scheme.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-10-04T16:17:32.000-0700

**Comment by rbeckman-nextgen** [comment]
Saw the InstanceAlreadyExistsException again today on the Mirth Connect Version  - 2.0.1.5164 .
Occurred when I included an output JMSWriter connector with a new queue name on a remote MQ server. I have the brokerURL property set and we access a bunch of other queues from the same channel, in the same way, but from other destinations.

Mirth Connect restart didn't help. Manually creating the queue on the remote MQ server did not work either. 


Imported Comment. Original Details:
Author: deepa
Created: 2010-11-22T13:06:52.000-0800

**Comment by rbeckman-nextgen** [comment]
Well, the channel got deployed when I restarted Mirth Connect again after I created the queue manually. 


Imported Comment. Original Details:
Author: deepa
Created: 2010-11-22T13:22:04.000-0800

**Comment by rbeckman-nextgen** [comment]
MIRTH-1695 - Separated the creation and the registering of transformers so the destination's FilteringMulticastingRouter is created and can be unregistered properly when deployment fails.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-01-10T16:57:48.000-0800

**Comment by rbeckman-nextgen** [comment]
Deepa,

Do you have a way to reproduce the InstanceAlreadyExistsException after a failed deploy with a JMS Writer or Reader?  If you could attach a channel that causes it that would be very helpful.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-01-13T14:42:56.000-0800

**Comment by rbeckman-nextgen** [comment]
Moving this issue back to 2.0.0 and closing it because we were unable to reproduce the new error.  If a test case to reproduce the InstanceAlreadyExistsException is submitted again it should be done under a new issue.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-02-02T12:02:54.000-0800
