### ISSUE TITLE
File Reader - add support for traversing subdirectories

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1440]
Imported Issue. Original Details:
Jira Issue Key: MIRTH-1441
Reporter: chrisr
Created: 2010-06-03T14:27:51.000-0700

**Comment by rbeckman-nextgen** [comment]
The method to load files in the API for the file methods will need to be updated to accept a boolean for recursively traversing directories. Can the existing wildcard or RegEx pattern support be extended to support this?

Imported Comment. Original Details:
Author: geraldb
Created: 2010-06-08T14:38:40.000-0700

**Comment by rbeckman-nextgen** [comment]
Using Java, there's no wildcard or RegEx pattern support for searching through subdirectories recursively.  We'll have to add a new component for the boolean parameter.

Imported Comment. Original Details:
Author: chrisr
Created: 2010-06-08T15:37:46.000-0700

**Comment by rbeckman-nextgen** [comment]
This would require some substantial changes to our API, so we are considering switching to Apache VFS

Imported Comment. Original Details:
Author: mitchd
Created: 2010-06-24T13:52:47.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 6476: Added support to the File Reader for recursive subdirectory traversal. If recursion is on, FileReceiver keeps track of a set of visited directories so that the same directory would never be read twice (due to symlinks, etc.). The traversal is done in a pre-order, depth-first manner. A dialog has been added to the UI when recursion is enabled to warn users of the implications. In order to facilitate the set of visited directories, a getCanonicalPath method has been added to FileInfo, so that FileSystemConnection implementations have a way to retrieve an absolute and unique path string for the file.

Imported Comment. Original Details:
Author: narupley
Created: 2013-06-12T18:23:59.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified new "Include All Subdirectories" option in File Reader processes all files in the specified read directory along with its subdirectories.

Imported Comment. Original Details:
Author: matts
Created: 2013-06-28T12:53:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Are there currently issues with this functionality in Version 3.5.1?  I'm trying to use the "Include All Subdirectories" setting on my sftp File Reader channel, but as soon as I turn it on and Redeploy the channel, the Connection stays in a Polling Status and never generates an error or gives any notification something wrong, and I usually have to Halt the job when I try to revert the setting and redeploy.
When I Halt the job I'll get a email notification stating "Returned object not currently part of this pool".  The main directory I am pointed to only has 7 Subfolders directly below.  And there is currently a total of 80 files within all the directories combined.
I looked in the Mirth.log file, and each time I Halt the channel it generates the error below, but does not log anything before or after.
Is there currently a known bug, or am I probably just not setting something up correctly?
Thanks.

ERROR 2018-03-08 19:08:05,500 [File Reader Polling Thread on Passport 277 In - IH (33110d3b-abb0-4ff0-93f6-2ef0f7763d05) < 33110d3b-abb0-4ff0-93f6-2ef0f7763d05_Worker-1] com.mirth.connect.connectors.file.FileReceiver: Error polling in channel: 33110d3b-abb0-4ff0-93f6-2ef0f7763d05
java.lang.IllegalStateException: Returned object not currently part of this pool
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:541)
	at com.mirth.connect.connectors.file.FileConnector.releaseConnection(FileConnector.java:205)
	at com.mirth.connect.connectors.file.FileReceiver.listDirectories(FileReceiver.java:574)
	at com.mirth.connect.connectors.file.FileReceiver.listFilesRecursively(FileReceiver.java:222)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:199)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

Imported Comment. Original Details:
Author: ntaylor
Created: 2018-03-08T17:15:28.000-0800

**Comment by rbeckman-nextgen** [comment]
Can you take a threaddump (with jstack) while it's stuck in Polling, and post it here?

Imported Comment. Original Details:
Author: narupley
Created: 2018-03-08T17:50:49.000-0800

**Comment by rbeckman-nextgen** [comment]
Requested files.

Imported Comment. Original Details:
Author: ntaylor
Created: 2018-03-08T23:44:28.000-0800

**Comment by rbeckman-nextgen** [comment]
I've attached the dump files.  It's the first time I've use jstack, so if it looks like I didn't do it correctly or any information is missing, please let me know.  Thanks.

Imported Comment. Original Details:
Author: ntaylor
Created: 2018-03-08T23:46:19.000-0800
