### ISSUE TITLE
Parsing files before they are written to disk, enable file age by default

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1443]
I get these errors on File reader channels (about 0.04% of the time)

[2010-06-08 12:21:59,696]  ERROR (com.webreach.mirth.connectors.file.FileMessageReceiver:239): Unable to route.org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.file.FileConnector@1455974, endpointUri=file:////10.1.32.203/customer/HL7_Messages/ORM, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_fileEndpoint#-1981046210', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1c93b3c, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: [B

	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)

	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:83)

	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)

	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)

	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)

	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:233)

	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:123)

	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)

	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)

	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)

	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)

	at java.lang.Thread.run(Unknown Source)
Caused by: org.mule.umo.transformer.TransformerException: com.webreach.mirth.model.converters.SerializerException: Unable to parse, message is null or too short:  (com.webreach.mirth.server.mule.adaptors.AdaptorException)

	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:346)

	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)

	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)

	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)

	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)

	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)

	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)

	... 11 more
Caused by: com.webreach.mirth.server.mule.adaptors.AdaptorException: com.webreach.mirth.model.converters.SerializerException: Unable to parse, message is null or too short: 

	at com.webreach.mirth.server.mule.adaptors.Adaptor.handleException(Adaptor.java:80)

	at com.webreach.mirth.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:32)

	at com.webreach.mirth.server.mule.adaptors.Adaptor.getMessage(Adaptor.java:52)

	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:316)

	... 17 more
Caused by: com.webreach.mirth.model.converters.SerializerException: Unable to parse, message is null or too short: 

	at com.webreach.mirth.model.converters.ER7Serializer.getMetadataFromEncoded(ER7Serializer.java:266)

	at com.webreach.mirth.server.mule.adaptors.Adaptor.populateMetadataFromEncoded(Adaptor.java:91)

	at com.webreach.mirth.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:24)

	... 19 more

Then this one
[2010-06-08 12:21:59,696]  WARN  (com.webreach.mirth.server.mule.adaptors.HL7v2Adaptor:77): error adapting message
com.webreach.mirth.model.converters.SerializerException: Unable to parse, message is null or too short: 
	at com.webreach.mirth.model.converters.ER7Serializer.getMetadataFromEncoded(ER7Serializer.java:266)
	at com.webreach.mirth.server.mule.adaptors.Adaptor.populateMetadataFromEncoded(Adaptor.java:91)
	at com.webreach.mirth.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:24)
	at com.webreach.mirth.server.mule.adaptors.Adaptor.getMessage(Adaptor.java:52)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:316)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:83)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:233)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:123)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)

And then this one
[2010-06-08 12:21:59,696]  ERROR (com.webreach.mirth.model.converters.ER7Serializer:265): Unable to parse, message is null or too short: 
about 0.04% of the time on file reader channels.

I'm thinking it has something to do with writing and reading from disk at the same time? How do I adjusted the polling interval and to check file age to reduce the instances of these errors, but I can't seem to make them go away.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1444
Reporter: stefangagnon
Created: 2010-06-08T09:42:44.000-0700

**Comment by rbeckman-nextgen** [comment]
We can potentially address this by enabled the Check File Age option by default.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-06-30T14:49:08.000-0700

**Comment by rbeckman-nextgen** [comment]
Could not reproduce this when file age was on.  

Imported Comment. Original Details:
Author: jacobb
Created: 2010-07-08T12:09:45.000-0700

**Comment by rbeckman-nextgen** [comment]
Enabled file age by default at 1000ms.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-07-08T12:10:41.000-0700
