### ISSUE TITLE
"export *" in Mirth Shell crashes with java.lang.ClassCastException

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1450]
Issuing an export command in the Mirth Shell with "*" as an argument causes the following crash:

Connected to Mirth Connect server @ https://127.0.0.1:8443 (1.8.2.4472)
$export * /tmp/channels.mirth
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.webreach.mirth.server.launcher.ShellLauncher.main(ShellLauncher.java:51)
Caused by: java.lang.ClassCastException: com.webreach.mirth.server.tools.Token cannot be cast to com.webreach.mirth.server.tools.StringToken
	at com.webreach.mirth.server.tools.Shell.commandExport(Shell.java:767)
	at com.webreach.mirth.server.tools.Shell.executeStatement(Shell.java:266)
	at com.webreach.mirth.server.tools.Shell.runConsole(Shell.java:187)
	at com.webreach.mirth.server.tools.Shell.runShell(Shell.java:152)
	at com.webreach.mirth.server.tools.Shell.run(Shell.java:123)
	at com.webreach.mirth.server.tools.Shell.<init>(Shell.java:85)
	... 5 more

--

Exporting a channel with a named ID works fine:

Connected to Mirth Connect server @ https://127.0.0.1:8443 (1.8.2.4472)
$status
ID					Status		Name
e184ab24-cca5-461c-8104-f21cfca05696	STARTED		HL7 Channel
$export e184ab24-cca5-461c-8104-f21cfca05696 /tmp/channels.mirth
Exporting HL7 Channel
Export Complete.
$

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1451
Reporter: mscjontai
Created: 2010-06-15T08:55:18.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed to create a StringToken from the original Token.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-06-23T14:54:28.000-0700
