### ISSUE TITLE
TypeError: error: Unexpected character encountered (lex state 9): '?' on ORU

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1461]
ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: a3a7e4e8-3029-4e46-ad60-e05b7a59cb8b: org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.mllp.MllpConnector@11d5915, endpointUri=mllp://127.0.0.1:8443, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_mllpEndpoint#-1650312611', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1cd000a, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String
org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.mllp.MllpConnector@11d5915, endpointUri=mllp://127.0.0.1:8443, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_mllpEndpoint#-1650312611', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1cd000a, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:83)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:476)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:436)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:353)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)Caused by: org.mule.umo.transformer.TransformerException: 
CHANNEL:
	RAPSHODY_PACS_LLP
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
LINE NUMBER:
	0
DETAILS:
	TypeError: error: Unexpected character encountered (lex state 9): '?' (com.webreach.mirth.server.MirthJavascriptTransformerException)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:470)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:356)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	... 11 moreCaused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	RAPSHODY_PACS_LLP
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
LINE NUMBER:
	0
DETAILS:
	TypeError: error: Unexpected character encountered (lex state 9): '?'
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:460)
	... 18 more

Please Help!! I see other similar problems (http://www.mirthcorp.com/community/issues/browse/MIRTH-745), but i don't find where is the  "Encode Entities" for do some tests.

Thanks

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1462
Reporter: ireesa
Created: 2010-06-25T04:00:12.000-0700

**Comment by rbeckman-nextgen** [comment]
For support issues please contact the help desk or the Mirth Support Forum.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-06-28T15:58:55.000-0700
