### ISSUE TITLE
Channel with File Writer won't deploy with spaces in path

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1476]
Steps to recreate:

1) Created a channel with an LLP Listener, File Reader.
2) For the File Reader, set the output directory to /Mirth Training/outbox (a valid, existing folder on my system).
3) For the File Reader, set the file name to ${UUID}.txt, and the output template to the message encoded data.
4) Redeploy All
5) Get the following two exceptions:

[2010-07-08 10:00:35,928]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:237): Failed to configure outbound router.
java.net.URISyntaxException: Illegal character in path at index 13: file:///Mirth Training/outbox
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.mirth.connect.server.controllers.MuleEngineController.configureOutboundRouter(MuleEngineController.java:350)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:235)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:176)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:226)
	at com.mirth.connect.server.Mirth.run(Mirth.java:134)

[2010-07-08 10:00:36,013]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:604): Error unregistering channel component.
java.lang.ClassCastException: org.mule.routing.outbound.OutboundPassThroughRouter cannot be cast to org.mule.routing.outbound.FilteringMulticastingRouter
	at org.mule.impl.model.AbstractModel.stopDispatchers(AbstractModel.java:441)
	at org.mule.impl.model.AbstractModel.unregisterComponent(AbstractModel.java:209)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterChannel(MuleEngineController.java:602)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:195)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:226)
	at com.mirth.connect.server.Mirth.run(Mirth.java:134)

6) Go back and change the path for the File Writer to a different valid directory.  Now I get a different exception:

[2010-07-08 10:01:04,819]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:180): Error registering channel.
org.mule.umo.model.ModelException: Descriptor "ce5725f3-7dc6-48b0-8186-577cad3d5684" already exists in the model
	at org.mule.impl.model.AbstractModel.registerComponent(AbstractModel.java:165)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:241)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:176)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:226)
	at com.mirth.connect.server.Mirth.run(Mirth.java:134)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1477
Reporter: ericb
Created: 2010-07-08T10:08:02.000-0700

**Comment by rbeckman-nextgen** [comment]
I've discovered since submitting this issue that this only seems to happen when creating a channel with a File Writer where the Directory path contains a space in it.  If you specify a directory with no space in its path, it works fine.

Imported Comment. Original Details:
Author: ericb
Created: 2010-07-08T11:46:06.000-0700

**Comment by rbeckman-nextgen** [comment]
This issue also affects the File Reader.  Basically the same thing... if the path in the Directory setting of the File Reader contains a space, the channel won't deploy.

Imported Comment. Original Details:
Author: ericb
Created: 2010-07-08T14:18:18.000-0700

**Comment by rbeckman-nextgen** [comment]
No longer use URI to parse the endpoints since the MuleEndpointURI does that and also escapes the special characters.

Imported Comment. Original Details:
Author: geraldb
Created: 2010-07-09T15:27:27.000-0700
