### ISSUE TITLE
Connector Type: File Reader,  Method: file, ends in error if there are spaces in the Directory path name 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1500]
It dosn't like path name with spaces. If you change the channel to point to a path without spaces you get a second error. 
You have to delete the channel and start over.

First Error

2010-07-19 13:48:27,187]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:230): Failed to configure inbound router.
java.net.URISyntaxException: Illegal character in path at index 15: file://I:/Mirth Test
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at com.mirth.connect.server.controllers.MuleEngineController.configureInboundRouter(MuleEngineController.java:334)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:228)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:176)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:226)
	at com.mirth.connect.server.Mirth.run(Mirth.java:134)

Second Error

[2010-07-19 13:39:14,109]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:230): Failed to configure inbound router.
javax.management.InstanceAlreadyExistsException: MirthConfiguration:type=control,name=98d1aabf-c932-4d15-a697-ebcdc9bb268b_source_connectorService
	at com.sun.jmx.mbeanserver.Repository.addMBean(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.internal_addObject(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source)
	at org.mule.management.agents.JmxAgent.registerConnectorService(JmxAgent.java:436)
	at com.mirth.connect.server.controllers.MuleEngineController.registerConnector(MuleEngineController.java:525)
	at com.mirth.connect.server.controllers.MuleEngineController.configureInboundRouter(MuleEngineController.java:285)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:228)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:176)
	at com.mirth.connect.server.Mirth.deployChannels(Mirth.java:226)
	at com.mirth.connect.server.Mirth.run(Mirth.java:134)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1501
Reporter: kt7277
Created: 2010-07-19T12:20:39.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-1477, which has been resolved.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-07-22T13:22:15.000-0700
