### ISSUE TITLE
Error deploying channels.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1509]
[2010-08-02 17:51:11,621]  WARN  (com.webreach.mirth.server.Mirth:253): Error deploying channels.
org.mule.config.ConfigurationException: Failed to parse configuration resource "C:\Program Files\Mirth\conf\mule-config.xml" (org.mule.config.ConfigurationException)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:196)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:250)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:208)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:138)Caused by: org.mule.config.ConfigurationException: Failed to parse configuration resource "C:\Program Files\Mirth\conf\mule-config.xml"
	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:121)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
	... 3 moreCaused by: org.mule.management.agents.JmxManagementException: Failed to start Jmx Connector
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2919)
	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2945)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1133)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1685)
	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
	... 5 moreCaused by: org.mule.management.agents.JmxManagementException: Failed to start Jmx Connector
	at org.mule.management.agents.JmxAgent.start(JmxAgent.java:194)
	at org.mule.MuleManager.registerAgent(MuleManager.java:1037)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:216)
	at org.apache.commons.digester.SetRootRule.end(SetRootRule.java:209)
	at org.apache.commons.digester.Rule.end(Rule.java:230)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1130)
	... 16 moreCaused by: java.io.IOException: Cannot bind to URL [rmi://localhost:1099/server]: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 

	java.net.SocketTimeoutException: Read timed out]
	at javax.management.remote.rmi.RMIConnectorServer.newIOException(Unknown Source)
	at javax.management.remote.rmi.RMIConnectorServer.start(Unknown Source)
	at org.mule.management.agents.JmxAgent.start(JmxAgent.java:192)
	... 25 moreCaused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 

	java.net.SocketTimeoutException: Read timed out]
	at com.sun.jndi.rmi.registry.RegistryContext.rebind(Unknown Source)
	at com.sun.jndi.toolkit.url.GenericURLContext.rebind(Unknown Source)
	at javax.naming.InitialContext.rebind(Unknown Source)
	at javax.management.remote.rmi.RMIConnectorServer.bind(Unknown Source)
	... 27 moreCaused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 

	java.net.SocketTimeoutException: Read timed out
	at sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
	at sun.rmi.server.UnicastRef.newCall(Unknown Source)
	at sun.rmi.registry.RegistryImpl_Stub.rebind(Unknown Source)
	... 31 moreCaused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readByte(Unknown Source)
	... 35 more

[2010-08-02 17:51:11,621]  ERROR (org.apache.commons.digester.Digester:1132): End event threw exception
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.beanutils.MethodUtils.invokeMethod(MethodUtils.java:216)
	at org.apache.commons.digester.SetRootRule.end(SetRootRule.java:209)
	at org.apache.commons.digester.Rule.end(Rule.java:230)
	at org.apache.commons.digester.Digester.endElement(Digester.java:1130)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.commons.digester.Digester.parse(Digester.java:1685)
	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:250)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:208)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:138)Caused by: org.mule.management.agents.JmxManagementException: Failed to start Jmx Connector
	at org.mule.management.agents.JmxAgent.start(JmxAgent.java:194)
	at org.mule.MuleManager.registerAgent(MuleManager.java:1037)
	... 24 moreCaused by: java.io.IOException: Cannot bind to URL [rmi://localhost:1099/server]: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 

	java.net.SocketTimeoutException: Read timed out]
	at javax.management.remote.rmi.RMIConnectorServer.newIOException(Unknown Source)
	at javax.management.remote.rmi.RMIConnectorServer.start(Unknown Source)
	at org.mule.management.agents.JmxAgent.start(JmxAgent.java:192)
	... 25 moreCaused by: javax.naming.CommunicationException [Root exception is java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 

	java.net.SocketTimeoutException: Read timed out]
	at com.sun.jndi.rmi.registry.RegistryContext.rebind(Unknown Source)
	at com.sun.jndi.toolkit.url.GenericURLContext.rebind(Unknown Source)
	at javax.naming.InitialContext.rebind(Unknown Source)
	at javax.management.remote.rmi.RMIConnectorServer.bind(Unknown Source)
	... 27 moreCaused by: java.rmi.ConnectIOException: error during JRMP connection establishment; nested exception is: 

	java.net.SocketTimeoutException: Read timed out
	at sun.rmi.transport.tcp.TCPChannel.createConnection(Unknown Source)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(Unknown Source)
	at sun.rmi.server.UnicastRef.newCall(Unknown Source)
	at sun.rmi.registry.RegistryImpl_Stub.rebind(Unknown Source)
	... 31 moreCaused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readByte(Unknown Source)
	... 35 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1511
Reporter: vidya-k
Created: 2010-08-02T05:33:38.000-0700

**Comment by rbeckman-nextgen** [comment]
This is a configuration error.  Please look to the forums for support.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-08-02T10:33:47.000-0700
