### ISSUE TITLE
xml to hl7 channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1546]
regarding the script:
        SerializerFactory.getHL7Serializer(true, true, true).fromXML(msg['patient_data_id']);

[2010-08-26 19:42:50,025]  ERROR (com.webreach.mirth.server.util.JavaScriptUtil:120): Error executing Deploy script.
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.webreach.mirth.server.util.JavaScriptUtil.getSourceCode(JavaScriptUtil.java:271)
	at com.webreach.mirth.server.util.JavaScriptUtil.executeScript(JavaScriptUtil.java:152)
	at com.webreach.mirth.server.util.JavaScriptUtil.executeScript(JavaScriptUtil.java:113)
	at com.webreach.mirth.server.controllers.DefaultConfigurationController.executeGlobalScript(DefaultConfigurationController.java:451)
	at com.webreach.mirth.server.controllers.DefaultConfigurationController.executeGlobalDeployScript(DefaultConfigurationController.java:443)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:247)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:208)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:138)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1548
Reporter: vidya-k
Created: 2010-08-26T07:18:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Please use the forums for support.  The issue tracker is for bugs, not questions on how to use Mirth Connect.  If you are not sure if you found a bug, please post it on the forum first.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-08-27T13:50:24.000-0700
