### ISSUE TITLE
xml to hl7

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1548]
[2010-08-27 15:57:50,963]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: 9642b8ec-0ea4-49c2-a221-f59ca60ac3e1: org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.jdbc.JdbcConnector@1660e34, endpointUri=jdbc://query, transformer=Transformer{name='ResultMapToXML', returnClass=false, returnClass=false, sourceTypes=[interface java.util.Map, class java.lang.String]}, name='_jdbcEndpoint#1688337306', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1722d01, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: org.apache.commons.dbutils.BasicRowProcessor$CaseInsensitiveHashMap
org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.webreach.mirth.connectors.jdbc.JdbcConnector@1660e34, endpointUri=jdbc://query, transformer=Transformer{name='ResultMapToXML', returnClass=false, returnClass=false, sourceTypes=[interface java.util.Map, class java.lang.String]}, name='_jdbcEndpoint#1688337306', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@1722d01, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: org.apache.commons.dbutils.BasicRowProcessor$CaseInsensitiveHashMap
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:83)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:235)
	at com.webreach.mirth.connectors.jdbc.JdbcMessageReceiver.processMessage(JdbcMessageReceiver.java:168)
	at org.mule.providers.TransactedPollingMessageReceiver$1.doInTransaction(TransactedPollingMessageReceiver.java:98)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:104)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)Caused by: org.mule.umo.transformer.TransformerException: 
CHANNEL:
	try
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
SOURCE CODE:
	
5: msg = new XML(newMessage);
6: if (msg.namespace("") != undefined) { default xml namespace = msg.namespace(""); } else { default xml namespace = ''; }
7: function doFilter() { phase = 'filter'; return true; }function doTransform() { phase = 'transformer'; logger = Packages.org.apache.log4j.Logger.getLogger(phase);
8: 
9: 
10: SerializerFactory.getHL7Serializer(true, true, true).fromXML(msg);
11: 
12: }
LINE NUMBER:
	10
DETAILS:
	Wrapped java.lang.NullPointerException (com.webreach.mirth.server.MirthJavascriptTransformerException)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:470)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:356)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	... 13 moreCaused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:
	try
CONNECTOR:
	sourceConnector
SCRIPT SOURCE:
	
SOURCE CODE:
	
5: msg = new XML(newMessage);
6: if (msg.namespace("") != undefined) { default xml namespace = msg.namespace(""); } else { default xml namespace = ''; }
7: function doFilter() { phase = 'filter'; return true; }function doTransform() { phase = 'transformer'; logger = Packages.org.apache.log4j.Logger.getLogger(phase);
8: 
9: 
10: SerializerFactory.getHL7Serializer(true, true, true).fromXML(msg);
11: 
12: }
LINE NUMBER:
	10
DETAILS:
	Wrapped java.lang.NullPointerException
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:458)
	... 20 moreCaused by: java.lang.NullPointerException
	at ca.uhn.hl7v2.parser.XMLParser.supportsEncoding(XMLParser.java:148)
	at ca.uhn.hl7v2.parser.Parser.parse(Parser.java:150)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
	at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
	at org.mozilla.javascript.gen._3fb23bb8_ea82_489e_b682_5b6513d2efa3_106._c_doTransform_13(3fb23bb8-ea82-489e-b682-5b6513d2efa3:10)
	at org.mozilla.javascript.gen._3fb23bb8_ea82_489e_b682_5b6513d2efa3_106.call(3fb23bb8-ea82-489e-b682-5b6513d2efa3)
	at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:108)
	at org.mozilla.javascript.gen._3fb23bb8_ea82_489e_b682_5b6513d2efa3_106._c_script_0(3fb23bb8-ea82-489e-b682-5b6513d2efa3:13)
	at org.mozilla.javascript.gen._3fb23bb8_ea82_489e_b682_5b6513d2efa3_106.call(3fb23bb8-ea82-489e-b682-5b6513d2efa3)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:426)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3157)
	at org.mozilla.javascript.gen._3fb23bb8_ea82_489e_b682_5b6513d2efa3_106.call(3fb23bb8-ea82-489e-b682-5b6513d2efa3)
	at org.mozilla.javascript.gen._3fb23bb8_ea82_489e_b682_5b6513d2efa3_106.exec(3fb23bb8-ea82-489e-b682-5b6513d2efa3)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:403)
	... 20 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1550
Reporter: vidya-k
Created: 2010-08-27T03:30:12.000-0700

**Comment by rbeckman-nextgen** [comment]
Please use the forums for support.  The issue tracker is for bugs, not questions on how to use Mirth Connect.  If you are not sure if you found a bug, please post it on the forum first.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-08-27T13:50:39.000-0700
