### ISSUE TITLE
Mule shutdown hook running concurrently with Mirth shutdown hook.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1561]
seeing this when I stop mirth connect:

INFO  2010-09-13 16:50:37,088 [Thread-4] com.mirth.connect.server.Mirth: shutting down mirth due to normal request
ERROR 2010-09-13 16:50:37,096 [Thread-4] com.mirth.connect.server.controllers.MuleEngineController: Error unregistering channel component.
java.lang.NullPointerException
	at org.mule.impl.model.AbstractModel.unregisterComponent(AbstractModel.java:210)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterChannel(MuleEngineController.java:718)
	at com.mirth.connect.server.controllers.MuleEngineController.undeployChannels(MuleEngineController.java:268)
	at com.mirth.connect.server.controllers.MuleEngineController.stopEngine(MuleEngineController.java:152)
	at com.mirth.connect.server.Mirth.stopEngine(Mirth.java:205)
	at com.mirth.connect.server.Mirth.shutdown(Mirth.java:171)
	at com.mirth.connect.server.Mirth$ShutdownHook.run(Mirth.java:369)
ERROR 2010-09-13 16:50:37,096 [Thread-4] com.mirth.connect.server.controllers.MuleEngineController: Error undeploying channels.
java.lang.NullPointerException
	at org.mule.MuleManager.unregisterEndpoint(MuleManager.java:553)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterConnectors(MuleEngineController.java:748)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterChannel(MuleEngineController.java:723)
	at com.mirth.connect.server.controllers.MuleEngineController.undeployChannels(MuleEngineController.java:268)
	at com.mirth.connect.server.controllers.MuleEngineController.stopEngine(MuleEngineController.java:152)
	at com.mirth.connect.server.Mirth.stopEngine(Mirth.java:205)
	at com.mirth.connect.server.Mirth.shutdown(Mirth.java:171)
	at com.mirth.connect.server.Mirth$ShutdownHook.run(Mirth.java:369)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1566
Reporter: steven_kehlet
Created: 2010-09-14T12:12:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Okay, I've reproduced it with only this 1 channel.  It's a channel I've had since 1.8.2.  If I disable it then stop mirth, the error becomes:

INFO  2010-09-13 17:01:40,751 [Thread-4] com.mirth.connect.server.Mirth: shutting down mirth due to normal request
ERROR 2010-09-13 17:01:40,751 [Thread-4] com.mirth.connect.server.Mirth: java.lang.NullPointerException

when I enable it and then stop mirth the big NPEs come back.


Imported Comment. Original Details:
Author: steven_kehlet
Created: 2010-09-14T12:13:41.000-0700

**Comment by rbeckman-nextgen** [comment]
Added shutdown hook list to Mirth to enable MuleManager to add a shutdown hook after Mirth's

Imported Comment. Original Details:
Author: mitchd
Created: 2010-09-16T17:26:05.000-0700
