### ISSUE TITLE
can't do "channel list" in CLI

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1562]
[11:20 AM] appliance:/opt/mirthconnect # ./Mirth\ Connect\ CLI mirth-cli-launcher.xml -a https://127.0.0.1:8443 -u admin -p admin -v 2.0.0.4999
Connected to Mirth Connect server @ https://127.0.0.1:8443 (2.0.0.4999)
$channel list
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Caused by: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : java.util.ArrayList
required-type       : java.util.Properties
line number         : 16
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:88)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:234)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:206)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:234)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:206)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:150)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:59)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:77)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:68)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:142)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:931)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:917)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:861)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:853)
	at com.mirth.connect.model.converters.ObjectXMLSerializer.fromXML(ObjectXMLSerializer.java:61)
	at com.mirth.connect.client.core.Client.getChannel(Client.java:192)
	at com.mirth.connect.cli.CommandLineInterface.commandChannelList(CommandLineInterface.java:800)
	at com.mirth.connect.cli.CommandLineInterface.executeStatement(CommandLineInterface.java:277)
	at com.mirth.connect.cli.CommandLineInterface.runConsole(CommandLineInterface.java:190)
	at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:155)
	at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:128)
	at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:71)
	... 11 more
Caused by: java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:394)
	at java.util.Properties.setProperty(Properties.java:143)
	at com.thoughtworks.xstream.converters.collections.PropertiesConverter.unmarshal(PropertiesConverter.java:84)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
	... 43 more
[11:21 AM] appliance:/opt/mirthconnect # 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1567
Reporter: steven_kehlet
Created: 2010-09-14T12:15:10.000-0700

**Comment by rbeckman-nextgen** [comment]
Moved mirth-client-core to top of classpath for CLI.

Imported Comment. Original Details:
Author: mitchd
Created: 2010-09-16T14:10:28.000-0700
