### ISSUE TITLE
hitting enter in CLI causes NPE

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1563]
also hitting enter causes an NPE

[11:23 AM] appliance:/opt/mirthconnect # ./Mirth\ Connect\ CLI mirth-cli-launcher.xml -a https://127.0.0.1:8443 -u admin -p admin -v 2.0.0.4999
Connected to Mirth Connect server @ https://127.0.0.1:8443 (2.0.0.4999)
$
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.mirth.connect.cli.CommandLineInterface.addToken(CommandLineInterface.java:394)
	at com.mirth.connect.cli.CommandLineInterface.tokenizeCommand(CommandLineInterface.java:385)
	at com.mirth.connect.cli.CommandLineInterface.executeStatement(CommandLineInterface.java:216)
	at com.mirth.connect.cli.CommandLineInterface.runConsole(CommandLineInterface.java:190)
	at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:155)
	at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:128)
	at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:71)
	... 11 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1568
Reporter: steven_kehlet
Created: 2010-09-14T12:15:53.000-0700

**Comment by rbeckman-nextgen** [comment]
Wrapped the addToken method in a null check to ensure the current token is not null.

Imported Comment. Original Details:
Author: mitchd
Created: 2010-09-15T17:06:44.000-0700
