### ISSUE TITLE
exception on first startup of 2.0.0

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1565]
got this the first time I started MC2 on a new box. Only enabled channel was "good ack server", attached.

ERROR 2010-09-14 01:15:41,020 [Thread-2] com.mirth.connect.server.controllers.DefaultMigrationController: Could not migr
ate channels.
java.lang.NullPointerException
        at com.mirth.connect.server.controllers.DefaultChannelController.updateChannel(DefaultChannelController.java:148
)
        at com.mirth.connect.server.controllers.DefaultMigrationController.migrateChannels(DefaultMigrationController.ja
va:162)
        at com.mirth.connect.server.Mirth.startup(Mirth.java:152)
        at com.mirth.connect.server.Mirth.run(Mirth.java:112)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1570
Reporter: steven_kehlet
Created: 2010-09-14T12:31:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Might have been a problem with importing via shell errors.

Imported Comment. Original Details:
Author: mitchd
Created: 2010-09-16T17:18:21.000-0700
