### ISSUE TITLE
errors on 2.0.0.5056 startup

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1576]
see these exceptions in the Server Log on the Dashboard:

ERROR 2010-09-29 00:19:25,046 [Thread-2] com.mirth.connect.server.controllers.DefaultChannelController: com.mirth.connect.server.controllers.ControllerException: com.ibatis.
common.jdbc.exception.NestedSQLException:   
--- The error occurred in postgres/postgres-channel.xml.  
--- The error occurred while applying a result map.  
--- Check the Channel.get-channel-result.  
--- Check the result mapping for the 'destinationConnectors' property.  
--- Cause: com.thoughtworks.xstream.converters.ConversionException: 124 : 124
---- Debugging information ----
message             : 124
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : 124
class               : java.util.ArrayList
required-type       : java.lang.String
line number         : 263
-------------------------------
ERROR 2010-09-29 00:19:25,063 [Thread-2] com.mirth.connect.server.controllers.DefaultMigrationController: Could not migrate channels.
com.mirth.connect.server.controllers.ControllerException: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in postgres/postgres-channel.xml.  
--- The error occurred while applying a result map.  
--- Check the Channel.get-channel-result.  
--- Check the result mapping for the 'destinationConnectors' property.  
--- Cause: com.thoughtworks.xstream.converters.ConversionException: 124 : 124
---- Debugging information ----
message             : 124
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : 124
class               : java.util.ArrayList
required-type       : java.lang.String
line number         : 263
-------------------------------
        at com.mirth.connect.server.controllers.DefaultChannelController.getChannel(DefaultChannelController.java:64)
        at com.mirth.connect.server.controllers.DefaultMigrationController.migrateChannels(DefaultMigrationController.java:151)
        at com.mirth.connect.server.Mirth.startup(Mirth.java:167)
        at com.mirth.connect.server.Mirth.run(Mirth.java:126)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in postgres/postgres-channel.xml.  
--- The error occurred while applying a result map.  
--- Check the Channel.get-channel-result.  
--- Check the result mapping for the 'destinationConnectors' property.  
--- Cause: com.thoughtworks.xstream.converters.ConversionException: 124 : 124
---- Debugging information ----
message             : 124
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : 124
class               : java.util.ArrayList
required-type       : java.lang.String
line number         : 263
-------------------------------
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:204)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForList(MappedStatement.java:139)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:567)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:94)
        at com.mirth.connect.server.controllers.DefaultChannelController.getChannel(DefaultChannelController.java:62)
        ... 3 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: 124 : 124
---- Debugging information ----
message             : 124
cause-exception     : java.lang.ArrayIndexOutOfBoundsException

cause-message       : 124
class               : java.util.ArrayList
required-type       : java.lang.String
line number         : 263
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:88)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:234)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:206)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:234)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:206)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:59)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:77)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:68)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:59)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:142)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:931)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:917)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:861)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:853)
        at com.mirth.connect.model.converters.ObjectXMLSerializer.fromXML(ObjectXMLSerializer.java:65)
        at com.mirth.connect.server.sqlmap.extensions.ListTypeHandler.getResult(ListTypeHandler.java:29)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.getResult(CustomTypeHandler.java:52)
        at com.ibatis.sqlmap.engine.mapping.result.ResultMap.getPrimitiveResultMappingValue(ResultMap.java:619)
        at com.ibatis.sqlmap.engine.mapping.result.ResultMap.getResults(ResultMap.java:345)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleResults(SqlExecutor.java:384)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleMultipleResults(SqlExecutor.java:300)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:189)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
        ... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 124
        at com.thoughtworks.xstream.core.util.Base64Encoder.mapCharToInt(Base64Encoder.java:88)
        at com.thoughtworks.xstream.core.util.Base64Encoder.decode(Base64Encoder.java:75)
        at com.thoughtworks.xstream.converters.basic.Base64StringConverter.unmarshal(Base64StringConverter.java:47)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        ... 43 more
ERROR 2010-09-29 00:19:26,095 [Thread-2] com.mirth.connect.server.controllers.MuleEngineController: Error redeploying channels.
com.mirth.connect.server.controllers.ControllerException: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in postgres/postgres-channel.xml.  
--- The error occurred while applying a result map.  
--- Check the Channel.get-channel-result.  
--- Check the result mapping for the 'destinationConnectors' property.  
--- Cause: com.thoughtworks.xstream.converters.ConversionException: 124 : 124
---- Debugging information ----
message             : 124
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : 124
class               : java.util.ArrayList
required-type       : java.lang.String
line number         : 263
-------------------------------
        at com.mirth.connect.server.controllers.DefaultChannelController.getChannel(DefaultChannelController.java:64)
        at com.mirth.connect.server.controllers.MuleEngineController.redeployAllChannels(MuleEngineController.java:282)
        at com.mirth.connect.server.controllers.MuleEngineController.startEngine(MuleEngineController.java:145)
        at com.mirth.connect.server.Mirth.startEngine(Mirth.java:205)
        at com.mirth.connect.server.Mirth.startup(Mirth.java:176)
        at com.mirth.connect.server.Mirth.run(Mirth.java:126)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in postgres/postgres-channel.xml.  
--- The error occurred while applying a result map.  
--- Check the Channel.get-channel-result.  
--- Check the result mapping for the 'destinationConnectors' property.  

--- Cause: com.thoughtworks.xstream.converters.ConversionException: 124 : 124
---- Debugging information ----
message             : 124
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : 124
class               : java.util.ArrayList
required-type       : java.lang.String
line number         : 263
-------------------------------
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:204)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryForList(MappedStatement.java:139)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:567)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:541)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:94)
        at com.mirth.connect.server.controllers.DefaultChannelController.getChannel(DefaultChannelController.java:62)
        ... 5 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: 124 : 124
---- Debugging information ----
message             : 124
cause-exception     : java.lang.ArrayIndexOutOfBoundsException
cause-message       : 124
class               : java.util.ArrayList
required-type       : java.lang.String
line number         : 263
-------------------------------
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:88)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:234)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:206)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:234)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:206)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:150)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:59)
        at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:77)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:68)
        at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:75)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:59)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:142)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:33)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:931)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:917)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:861)
        at com.thoughtworks.xstream.XStream.fromXML(XStream.java:853)
        at com.mirth.connect.model.converters.ObjectXMLSerializer.fromXML(ObjectXMLSerializer.java:65)
        at com.mirth.connect.server.sqlmap.extensions.ListTypeHandler.getResult(ListTypeHandler.java:29)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.getResult(CustomTypeHandler.java:52)
        at com.ibatis.sqlmap.engine.mapping.result.ResultMap.getPrimitiveResultMappingValue(ResultMap.java:619)
        at com.ibatis.sqlmap.engine.mapping.result.ResultMap.getResults(ResultMap.java:345)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleResults(SqlExecutor.java:384)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.handleMultipleResults(SqlExecutor.java:300)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeQuery(SqlExecutor.java:189)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteQuery(MappedStatement.java:221)
        at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeQueryWithCallback(MappedStatement.java:189)
        ... 11 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 124
        at com.thoughtworks.xstream.core.util.Base64Encoder.mapCharToInt(Base64Encoder.java:88)
        at com.thoughtworks.xstream.core.util.Base64Encoder.decode(Base64Encoder.java:75)
        at com.thoughtworks.xstream.converters.basic.Base64StringConverter.unmarshal(Base64StringConverter.java:47)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:81)
        ... 45 more
INFO  2010-09-29 00:19:26,104 [Thread-2] com.mirth.connect.server.Mirth: Mirth Connect 2.0.0.5056 (September 24, 2010) server successfully started: Wed Sep 29 00:19:26 UTC 2
010
INFO  2010-09-29 00:19:26,105 [Thread-2] com.mirth.connect.server.Mirth: This product was developed by Mirth Corporation (http://www.mirthcorp.com) and its contributors (c)2
005-2010.
INFO  2010-09-29 00:19:26,105 [Thread-2] com.mirth.connect.server.Mirth: Running Java HotSpot(TM) Server VM 1.6.0_21 on Linux (2.6.18-164.9.1.el5, i386) with charset UTF-8.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1581
Reporter: steven_kehlet
Created: 2010-09-28T17:24:25.000-0700

**Comment by rbeckman-nextgen** [comment]
Did this occur when migrating from 1.8.2 to 2.0 RC2, or was it migrating from an early 2.0 build?  Is there a channel that will reproduce this error on startup of 2.0?  If this only happens during the initial database migration, the 1.8.2 channel that causes it will be needed, so that we can load it into a 1.8.2 database and then start 2.0 against it.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-09-28T18:02:26.000-0700

**Comment by rbeckman-nextgen** [comment]
I came across this error while QA'ing Mirth Appliance 3.3.0 V1000-04-F3B8897C-0011.  This occurred after an upgrade from Mirth Connect 2.0.2923 to 2.0.2956 as part of an upgrade on said appliance.  You can see this instance by hitting my QA appliance at 10.10.3.46.

Imported Comment. Original Details:
Author: rudyq
Created: 2010-09-29T13:25:23.000-0700

**Comment by rbeckman-nextgen** [comment]
> Did this occur when migrating from 1.8.2 to 2.0 RC2, or was it migrating from an early 2.0 build? 

From an early 2.0.0 build.

> Is there a channel that will reproduce this error on startup of 2.0? 

It seems to happen on every Mirth Connect startup.  I can't get the Channels page to load to export the channel, I get a popup with a stack trace:

org.apache.commons.httpclient.ProtocolException: Unable to parse header: --- The error occurred in postgres/postgres-channel.xml.  
..........


Imported Comment. Original Details:
Author: steven_kehlet
Created: 2010-09-29T13:28:16.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in MIRTH-1563 with revision 5059.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-10-04T10:48:00.000-0700
