### ISSUE TITLE
Writing message to mirthdb can be deadlocked and is not handled, mirthdb is left inconsistent (sqlserver2005)

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1580]
Hello,

We are using sql server 2005 in production and running into this problem. The service is trying to update the status of a message and failing on a deadlock.   (There were a few reports of this issue using derby, closed as "won't fix dont use derby".)  Really I think it does not have much to do with the actual RDBMS used, there is a deadlock possibility with this update query and another one I am trying to identify.  Once I determine exactly how to reproduce it on sql server 2005, I bet I could reproduce it using the same steps on most other RDBMS.  If the deadlock(s) with the queries cannot be resolved, the exception condition needs caught, and the query retried.

ERROR 2010-10-05 10:38:50,097 [0e5e19bf-2fcc-497d-a2fa-f8f6a5f0507e_destination_1_connector_queue_thread] com.webreach.mirth.server.controllers.DefaultMessageObjectController: could not log message: id=da3206e5-08d9-4370-b01b-dab37515c08d
com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in sqlserver2005/sqlserver2005-message.xml.  
--- The error occurred while applying a parameter map.  
--- Check the Message.update-message-param.  
--- Check the statement (update failed).  
--- Cause: java.sql.SQLException: Transaction (Process ID 84) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
Caused by: java.sql.SQLException: Transaction (Process ID 84) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:91)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.update(SqlMapExecutorDelegate.java:505)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.update(SqlMapSessionImpl.java:90)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.update(SqlMapClientImpl.java:67)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.writeMessageToDatabase(DefaultMessageObjectController.java:261)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.updateMessage(DefaultMessageObjectController.java:204)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setStatus(DefaultMessageObjectController.java:845)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.setSuccess(DefaultMessageObjectController.java:771)
	at com.webreach.mirth.connectors.http.HttpClientMessageDispatcher.send(HttpClientMessageDispatcher.java:409)
	at com.webreach.mirth.connectors.http.HttpClientMessageDispatcher.sendPayload(HttpClientMessageDispatcher.java:425)
	at org.mule.providers.QueueEnabledConnector$QueueWorker.run(QueueEnabledConnector.java:202)
	at java.lang.Thread.run(Thread.java:595)
Caused by: java.sql.SQLException: Transaction (Process ID 84) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

writeMessageToDatabase(DefaultMessageObjectController.java:261)   just catches the sql exception and puts it in the log.  Catch blocks with log only are always a little scary, it probably should be doing something else...

The query that is always chosen as the victim is

    <update id="updateMessage" parameterMap="update-message-param">
		UPDATE MESSAGE
		SET STATUS = ?,
			RAW_DATA = ?,
			TRANSFORMED_DATA = ?,
			ENCODED_DATA = ?,
			ERRORS = ?,
			CORRELATION_ID = ?,
			CONNECTOR_MAP = ?,
			CHANNEL_MAP = ?,
			RESPONSE_MAP = ?,
            ATTACHMENT = ?
		WHERE ID = ?
	</update>

I can't see how that would cause a problem, the execution plan is pretty straightforward, indexes and keys look ok.  There's some other query running at the same time that is locking.. I don't know what that is yet, working on getting the deadlock graph in the error log.  I should mentino that I do have the administrator UI left open.  We suspect it may be a query from that thing instead of another one inside the server.  Possible?  I'm keeping the UI closed today and we'll see if it shows up again.

Either way, with this issue present our mirthdb is inconsistent.  I have 40 messages that are still saying status = queued, but no actually queued messages, they all got sent (which is good) but mirthdb is defunct..

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1585
Reporter: john.newman
Created: 2010-10-05T09:08:38.000-0700

**Comment by rbeckman-nextgen** [comment]
Does this seem to happen around a certain time?  What is your message pruning schedule like?  I'm wondering if the other query running is either pruning the messages or the message attachments.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-11-29T16:31:29.000-0800

**Comment by rbeckman-nextgen** [comment]
We had the same issue a while ago ... It was caused by a defect network card of the Mirth server pc (or vmware host).

Imported Comment. Original Details:
Author: nicovn
Created: 2010-11-30T05:45:39.000-0800

**Comment by rbeckman-nextgen** [comment]
we actually do not have message pruning enabled on any channel, it happens for about 5% of messages throughout the day.  The http sender channels with the persistent queues seem to do it.  It probably would be easy enough to reproduce with 3 or 4 http sender channels using persistent queues under high volume.

You can probably change the priority to major, all this really means is there's records in mirthdb that have status = 'queued' when it should say sent.  It does not actually cause problems with message processing (I thought it might have been..).

Imported Comment. Original Details:
Author: john.newman
Created: 2010-11-30T06:19:57.000-0800

**Comment by rbeckman-nextgen** [comment]
The changes noted in the following forum thread might help: http://www.mirthcorp.com/community/forums/showthread.php?p=17211 

Imported Comment. Original Details:
Author: jacobb
Created: 2011-01-13T14:46:30.000-0800

**Comment by rbeckman-nextgen** [comment]
Assigning this to Jacob since he has more background with the issue.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-02-14T09:31:10.000-0800

**Comment by rbeckman-nextgen** [comment]
Updated sqlserver and sqlserver2000 message.xml files to use selects with nolock and updates, inserts, and deletes with rowlock.  This should also dramatically improve performance on SQL Server.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-02-14T16:34:48.000-0800

**Comment by rbeckman-nextgen** [comment]
Look into using nvarchar in MIRTH-1759.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-02-28T16:57:08.000-0800
