### ISSUE TITLE
Exception when getting source for exceptions when running short deploy/shutdown/pre/post scripts

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1618]
Created a channel with the following postprocessor script:

logger.error(tmp);

This results in the following exception:

[2010-11-05 12:28:11,814]  ERROR (com.mirth.connect.server.util.JavaScriptUtil:226): Error executing Postprocessor script from channel: 47bd66fc-da1d-4e96-9174-654cd730cc12
java.lang.ArrayIndexOutOfBoundsException: -1
	at com.mirth.connect.server.util.JavaScriptUtil.getSourceCode(JavaScriptUtil.java:406)
	at com.mirth.connect.server.util.JavaScriptUtil.executeScript(JavaScriptUtil.java:250)
	at com.mirth.connect.server.util.JavaScriptUtil.executePostprocessorScripts(JavaScriptUtil.java:155)
	at com.mirth.connect.server.mule.transformers.JavaScriptPostprocessor.doPostProcess(JavaScriptPostprocessor.java:23)
	at com.mirth.connect.server.mule.transformers.JavaScriptPostprocessor.doPostProcess(JavaScriptPostprocessor.java:40)
	at com.mirth.connect.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:224)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1625
Reporter: geraldb
Created: 2010-11-05T12:29:17.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed ArrayIndexOutOfBounds when trying to get the source code lines for a generated script of 5 lines or less.  Fixed the error line number offsets for deploy/shutdown/pre/post scripts.  Added a source code report for errors compiling deploy/shutdown/pre/post scripts, even though these errors should be caught on the client before allowing a deploy.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-11-11T16:50:41.000-0800
