### ISSUE TITLE
Mirth errors while trying to load channel preprocessor

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1621]
After importing Mirth 1.8.2 channels into a new instance of Mirth 2.0.0 we keep getting the same error when starting Mirth. 
The error seems to happen in the channel preprocessor. 

{noformat}
NFO  2010-11-04 15:22:05,231 [Thread-2] com.mirth.connect.server.Mirth: Mirth Connect 2.0.0.5127 (October 28, 2010) server s
arted: Thu Nov 04 15:22:05 CST 2010
INFO  2010-11-04 15:22:05,231 [Thread-2] com.mirth.connect.server.Mirth: This product was developed by Mirth Corporation (htt
orp.com) and its contributors (c)2005-2010.
INFO  2010-11-04 15:22:05,231 [Thread-2] com.mirth.connect.server.Mirth: Running Java HotSpot(TM) 64-Bit Server VM 1.6.0_20 o
        at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
ERROR 2010-11-04 15:22:04,250 [Thread-2] com.mirth.connect.server.util.JavaScriptUtil: Error executing f2439943-2775-416b-8df
c-1fd7d920f9eb_Deploy script from channel: f2439943-2775-416b-8dfc-1fd7d920f9eb
com.mirth.connect.server.MirthJavascriptTransformerException:
SOURCE CODE:
4816:   }
4817: };var release_tag = 50;function doScript() {
4818: // This script executes once when the mule engine is started
4819: // You only have access to the globalMap here to persist data
4820:
4821: message = message.replace(/:/g, "](")
4822: message = message.replace (/;/g, "^");
4823: return message;
4824: }
LINE NUMBER:    4820
DETAILS:        ReferenceError: "message" is not defined.
        at com.mirth.connect.server.util.JavaScriptUtil.executeScript(JavaScriptUtil.java:251)
        at com.mirth.connect.server.util.JavaScriptUtil.executeChannelDeployOrShutdownScript(JavaScriptUtil.java:180)
        at com.mirth.connect.server.controllers.DefaultScriptController.executeChannelDeployScript(DefaultScriptController.ja
va:197)
       	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:199)
        at com.mirth.connect.server.controllers.MuleEngineController.redeployAllChannels(MuleEngineController.java:281)
        at com.mirth.connect.server.controllers.MuleEngineController.startEngine(MuleEngineController.java:144)
        at com.mirth.connect.server.Mirth.startEngine(Mirth.java:205)
        at com.mirth.connect.server.Mirth.startup(Mirth.java:176)
        at com.mirth.connect.server.Mirth.run(Mirth.java:126)
INFO  2010-11-04 15:22:05,231 [Thread-2) com.mirth.connect.server.Mirth: Mirth Connect 2.0.0.5127 (October 28, 2010) server s
uccessfully started: Thu Nov 04 15:22:05 CST 2010
INFO  2010-11-04 15:22:05,231 [Thread-2] com.mirth.connect.server.Mirth: This product was developed by Mirth Corporation (htt
p://www.mirthcorp.com) and its contributors (c)2005-2010.
INFO  2010-11-04 15:22:05,231 [Thread-2] com.mirth.connect.server.Mirth: Running Java HotSpot(TM) 64-Bit Server VM 1.6.0_20 o
n Linux (2.6.18-xen, amd64) with charset UTF-8.
{noformat}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1628
Reporter: iges
Created: 2010-11-08T13:39:50.000-0800

**Comment by rbeckman-nextgen** [comment]
Could you attach a channel that causes the problem?  A 1.8.2 channel export would be best.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-11-09T16:50:08.000-0800

**Comment by rbeckman-nextgen** [comment]
See attached file.

Imported Comment. Original Details:
Author: iges
Created: 2010-11-10T10:22:05.000-0800

**Comment by rbeckman-nextgen** [comment]
Could you please remove the attached channel. 

Imported Comment. Original Details:
Author: iges
Created: 2010-11-15T13:38:34.000-0800

**Comment by rbeckman-nextgen** [comment]
Channel removed.  You had message = message.replace lines in your deploy script.  The deploy script does not have the message.  I'm not sure what that would have done in 1.8.2, but it probably should have errored.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-11-15T13:48:57.000-0800

**Comment by rbeckman-nextgen** [comment]
You had message = message.replace lines in your deploy script. The deploy script does not have the message. I'm not sure what that would have done in 1.8.2, but it probably should have errored.

Imported Comment. Original Details:
Author: jacobb
Created: 2010-11-16T11:30:36.000-0800
