### ISSUE TITLE
Shutting down the Mirth service while processing causes a fatal error.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#164]
Start Mirth v1.2 service. Let it process files in the INBOUND folder. When the files are being processed, stop Mirth. It throws the following exception. 

Starting the Mirth service back causes  the same exception (continuous) for all the files in the INBOUND folder. The files simply get moved  very fast to the "Move-to" directory. 

NOTE: This problem does not happen in Mirth v1.1. When the command window is closed or Mirth stopped in the Administrator, it exits gracefully.

FATAL 2006-11-14 15:53:31,265 [93a81ab2-b2a3-49db-8d11-672105c8b123_source_connector._fileEndpoint#1558759253.receiver.1] org.mule.impl.DefaultComponentExceptionStrategy: The Default Component Exception Strategy has been invoked but there is no current event on the context
FATAL 2006-11-14 15:53:31,265 [93a81ab2-b2a3-49db-8d11-672105c8b123_source_connector._fileEndpoint#1558759253.receiver.1] org.mule.impl.DefaultComponentExceptionStrategy: The error is: Exception while processing "1FBA96DD-D405-4b97-9A2A-AA38EF43A47A.HL7" Result of rollback of move was unsuccessful
org.mule.MuleException: Exception while processing "1FBA96DD-D405-4b97-9A2A-AA38EF43A47A.HL7" Result of rollback of move was unsuccessful
    at org.mule.providers.file.FileMessageReceiver.processFile(FileMessageReceiver.java:242)
    at org.mule.providers.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
    at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:73)
    at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.mule.MuleException: File "1FBA96DD-D405-4b97-9A2A-AA38EF43A47A.HL7" does not exist or cannot be read
    at org.mule.providers.file.FileMessageReceiver.processFile(FileMessageReceiver.java:185)
    ... 6 more
FATAL 2006-11-14 15:53:31,295 [93a81ab2-b2a3-49db-8d11-672105c8b123_source_connector._fileEndpoint#1558759253.receiver.1] org.mule.impl.DefaultComponentExceptionStrategy: The Default Component Exception Strategy has been invoked but there is no current event on the context
FATAL 2006-11-14 15:53:31,295 [93a81ab2-b2a3-49db-8d11-672105c8b123_source_connector._fileEndpoint#1558759253.receiver.1] org.mule.impl.DefaultComponentExceptionStrategy: The error is: Exception while processing "208786BA-3614-4d2d-8B07-5C767E7EB4CD.HL7" Result of rollback of move was unsuccessful
org.mule.MuleException: Exception while processing "208786BA-3614-4d2d-8B07-5C767E7EB4CD.HL7" Result of rollback of move was unsuccessful
    at org.mule.providers.file.FileMessageReceiver.processFile(FileMessageReceiver.java:242)
    at org.mule.providers.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
    at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:73)
    at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.mule.MuleException: File "208786BA-3614-4d2d-8B07-5C767E7EB4CD.HL7" does not exist or cannot be read
    at org.mule.providers.file.FileMessageReceiver.processFile(FileMessageReceiver.java:185)
    ... 6 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-143
Reporter: brendanh
Created: 2006-11-22T11:38:27.000-0800

**Comment by rbeckman-nextgen** [comment]
See addition of channel processing status

Imported Comment. Original Details:
Author: admin
Created: 2007-07-26T15:55:31.000-0700

**Comment by rbeckman-nextgen** [comment]
Some of this issue has already been addressed.  Other parts will be addressed by MIRTH-475.

Imported Comment. Original Details:
Author: jacobb
Created: 2007-10-16T12:13:06.000-0700
