### ISSUE TITLE
Dashboard Status Panel UI Issue

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1699]
Please see included screenshots. The dashboard status panel has some UI issues rendering items, and it changes what is shown based on how you hover your mouse over the items. Sometimes the scroll bar on the right is not rendered properly as well.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1712
Reporter: dschramm
Created: 2011-01-07T10:22:52.000-0800

**Comment by rbeckman-nextgen** [comment]
(these two should work)

Imported Comment. Original Details:
Author: dschramm
Created: 2011-01-07T10:25:06.000-0800

**Comment by rbeckman-nextgen** [comment]
Also, I can produce strange behavior if I select "dashboard status panel", then click on "Channels", then click on "Dashboard" as shown in screenshot "dashboardstatuspanel.tiff'

Imported Comment. Original Details:
Author: dschramm
Created: 2011-01-07T11:08:51.000-0800

**Comment by rbeckman-nextgen** [comment]
Can you reproduce this regularly on both Windows and Mac?  I haven't seen it occur yet.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-01-10T17:46:32.000-0800

**Comment by rbeckman-nextgen** [comment]
Here are the stacktraces it generates:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mirth.connect.client.ui.ImageCellRenderer.getTableCellRendererComponent(ImageCellRenderer.java:30)
	at javax.swing.JTable.prepareRenderer(JTable.java:5720)
	at org.jdesktop.swingx.JXTable.prepareRenderer(JXTable.java:3491)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2072)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:1974)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1770)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:153)
	at javax.swing.JComponent.paintComponent(JComponent.java:752)
	at javax.swing.JComponent.paint(JComponent.java:1029)
	at javax.swing.JComponent.paintChildren(JComponent.java:862)
	at javax.swing.JComponent.paint(JComponent.java:1038)
	at javax.swing.JViewport.paint(JViewport.java:747)
	at javax.swing.JComponent.paintChildren(JComponent.java:862)
	at javax.swing.JComponent.paint(JComponent.java:1038)
	at javax.swing.JComponent.paintChildren(JComponent.java:862)
	at javax.swing.JComponent.paint(JComponent.java:1038)
	at javax.swing.JComponent.paintChildren(JComponent.java:862)
	at javax.swing.JComponent.paint(JComponent.java:1038)
	at javax.swing.JComponent.paintChildren(JComponent.java:862)
	at javax.swing.JSplitPane.paintChildren(JSplitPane.java:1030)
	at javax.swing.JComponent.paint(JComponent.java:1038)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5098)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4882)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:811)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:713)
	at javax.swing.RepaintManager.seqPaintDirtyRegions(RepaintManager.java:693)
	at javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(SystemEventQueueUtilities.java:125)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mirth.connect.client.ui.ImageCellRenderer.getTableCellRendererComponent(ImageCellRenderer.java:30)
	at javax.swing.JTable.prepareRenderer(JTable.java:5720)
	at org.jdesktop.swingx.JXTable.prepareRenderer(JXTable.java:3491)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2072)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:1974)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1770)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:153)
	at javax.swing.JComponent.paintComponent(JComponent.java:752)
	at javax.swing.JComponent.paint(JComponent.java:1029)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5098)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4882)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:811)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:713)
	at javax.swing.RepaintManager.seqPaintDirtyRegions(RepaintManager.java:693)
	at javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(SystemEventQueueUtilities.java:125)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:633)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

Imported Comment. Original Details:
Author: dschramm
Created: 2011-01-11T12:54:49.000-0800

**Comment by rbeckman-nextgen** [comment]
This can be reproduced with the TCP Sender.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-01-11T15:07:11.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed reference to the MonitoringController's Event.ATTEMPTING enumeration, which was causing the NullPointerException.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-01-11T15:09:59.000-0800
