### ISSUE TITLE
Erroneously gives "Encountered invalid queued message."

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1792]
I checked through the source code on FishEye using the stack trace below. It seems that the error handling code for failed connections is throwing an exception, which is obscuring the true cause of failure.

This line seems responsible - in WebServiceMessageDispatcher.java :192

if (e.getCause().getClass() == ConnectException.class) {

---
Behavior observed: Throwing message similar to "Encountered invalid queued message.  Message removed from queue: queueId=c1ea521b-4d82-4be8-9412-f5f2ababef08_destination_1_connector" which obscures the true cause of the failure.

Desired behavior: Give the true error message

---
ERROR-400: Connector error
ERROR MESSAGE:	Encountered invalid queued message.  Message removed from queue: queueId=c1ea521b-4d82-4be8-9412-f5f2ababef08_destination_1_connector
java.lang.NullPointerException
	at com.mirth.connect.connectors.ws.WebServiceMessageDispatcher.sendPayload(WebServiceMessageDispatcher.java:192)
	at org.mule.providers.QueueEnabledConnector$QueueWorker.run(QueueEnabledConnector.java:218)
	at java.lang.Thread.run(Thread.java:662)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1808
Reporter: tlittle
Created: 2011-04-04T11:37:49.000-0700

**Comment by rbeckman-nextgen** [comment]
This was fixed in MIRTH-1743 and is included in release version 2.1.0.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-04-04T11:46:28.000-0700
