### ISSUE TITLE
JMS Reader doesn't see ActiveMQ connectionFactory class

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1796]
I am trying to read from ActiveMQ queue.

JMS Reader settings

Use JNDI: No
Connection Factory Class: org.apache.activemq.ActiveMQConnectionFactory
Destination: testQueue

Produces the following error:

ERROR (com.mirth.connect.server.controllers.MuleEngineController:316): Failed to configure inbound router.
org.mule.providers.FatalConnectException: ReconnectStrategy "org.mule.providers.SingleAttemptConnectionStrategy" failed to reconnect receiver on endpoint "com.mirth.connect.connectors.jms.JmsConnector@109851a"
	at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java:34)
	at org.mule.providers.AbstractConnectionStrategy.connect(AbstractConnectionStrategy.java:67)
	at org.mule.providers.AbstractConnector.startConnector(AbstractConnector.java:252)
	at org.mule.MuleManager.registerConnector(MuleManager.java:497)
	at com.mirth.connect.server.controllers.MuleEngineController.registerConnector(MuleEngineController.java:668)
	at com.mirth.connect.server.controllers.MuleEngineController.configureInboundRouter(MuleEngineController.java:440)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:314)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:201)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:46)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:615)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.mortbay.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:677)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
	at org.mortbay.http.HttpServer.service(HttpServer.java:909)
	at org.mortbay.http.HttpConnection.service(HttpConnection.java:820)
	at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.mortbay.http.HttpConnection.handle(HttpConnection.java:837)
	at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:245)
	at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)Caused by: org.mule.providers.FatalConnectException: ReconnectStrategy "org.mule.providers.SingleAttemptConnectionStrategy" failed to reconnect receiver on endpoint "com.mirth.connect.connectors.jms.JmsConnector@109851a"
	at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java:34)
	at org.mule.providers.AbstractConnectionStrategy.connect(AbstractConnectionStrategy.java:67)
	at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:774)
	at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java:32)
	... 22 moreCaused by: org.mule.providers.ConnectException: Initialisation Failure: Initialisation Failure: org.apache.activemq.ActiveMQConnectionFactory
	at com.mirth.connect.connectors.jms.JmsConnector.doConnect(JmsConnector.java:256)
	at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:780)
	at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java:32)
	... 25 moreCaused by: org.mule.umo.lifecycle.InitialisationException: Initialisation Failure: org.apache.activemq.ActiveMQConnectionFactory
	at com.mirth.connect.connectors.jms.JmsConnector.createConnectionFactory(JmsConnector.java:185)
	at com.mirth.connect.connectors.jms.JmsConnector.createConnection(JmsConnector.java:202)
	at com.mirth.connect.connectors.jms.JmsConnector.doConnect(JmsConnector.java:251)
	... 27 moreCaused by: java.lang.ClassNotFoundException: org.apache.activemq.ActiveMQConnectionFactory
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.mirth.connect.connectors.jms.JmsConnector.createConnectionFactory(JmsConnector.java:172)

Where does it look for connectionFactory classes? Is it possible to specify a path to the class within connection factory class settings?

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1812
Reporter: miheir
Created: 2011-04-12T09:49:42.000-0700

**Comment by rbeckman-nextgen** [comment]
Did you add the activemq jar to the custom lib directory?

Imported Comment. Original Details:
Author: jacobb
Created: 2011-04-12T10:52:11.000-0700

**Comment by rbeckman-nextgen** [comment]
I did try to add it to custom-lib and lib directories.

Imported Comment. Original Details:
Author: miheir
Created: 2011-04-12T10:56:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Please try posting on the forums for support until it is determined that this is a bug.  We have not had issues reading from ActiveMQ

Imported Comment. Original Details:
Author: jacobb
Created: 2011-04-12T11:27:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Hello - i was wondering if you found the fix to this - as i am having the same issue

Imported Comment. Original Details:
Author: maherkj
Created: 2011-11-14T12:38:59.000-0800

**Comment by rbeckman-nextgen** [comment]
I don't have any issue reading a queue from activeMQ  with the 2.1.1 version

Imported Comment. Original Details:
Author: wello007
Created: 2012-07-18T05:09:15.000-0700
