### ISSUE TITLE
Deleting user that is not logged in causes exception

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1797]
If you attempt to delete a user that is not logged in, you will see this exception:

ERROR 2011-04-12 17:35:56,068 [SslListener0-2] org.mortbay.jetty.context./: /users: 
java.lang.IllegalStateException
	at org.mortbay.jetty.servlet.AbstractSessionManager$Session.removeAttribute(AbstractSessionManager.java:866)
	at com.mirth.connect.server.util.UserSessionCache.invalidateAllSessionsForUser(UserSessionCache.java:53)
	at com.mirth.connect.server.servlets.UserServlet.doPost(UserServlet.java:95)

This is because deleting a user also invalidates their HTTP session, which does not exist if they are not logged in. A check should be added before invalidating.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1813
Reporter: geraldb
Created: 2011-04-12T14:52:44.000-0700

**Comment by rbeckman-nextgen** [comment]
Added check for invalid sessions.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-04-12T15:07:46.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that exception is no longer shown.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-04-14T11:53:01.000-0700
