### ISSUE TITLE
Better handling of empty messages

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1798]
If you currently try to process an empty message using any of the connectors, you will see a long exception ending with:

... 37 moreCaused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 4
at java.lang.String.charAt(Unknown Source)
at com.mirth.connect.model.converters.ER7Serializer.getMetadataFromEncoded(ER7Serializer.java:273)
at com.mirth.connect.server.mule.adaptors.Adaptor.populateMetadataFromEncoded(Adaptor.java:100)
at com.mirth.connect.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:40)
... 39 more

This is basically the serializer failing to find the start of the message. There should be some logic to detect a blank message and show a friendlier warning, something like "Empty message received" or along those lines.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1814
Reporter: geraldb
Created: 2011-04-15T11:30:18.000-0700

**Comment by rbeckman-nextgen** [comment]
After changes to the HL7 encoder, this error no longer exists.

If you process a blank message and you have a transformer step you will instead see:

org.xml.sax.SAXParseException: Premature end of file.

And if you process a blank message without a transformer step you will see:

com.mirth.connect.model.converters.SerializerException: Unable to parse, message is null or too short

Both of which are easier to understand.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-10-25T09:11:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Resolved as a part of MIRTH-1880

Imported Comment. Original Details:
Author: jacobb
Created: 2011-10-25T11:19:34.000-0700
