### ISSUE TITLE
Unable to deploy Email Sender using server SMTP settings

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1801]
If you have a channel using the Email Sender and set the "User Server Settings" option to Yes and deploy, you will get this error:

ERROR 2011-04-20 09:49:49,980 [main] com.mirth.connect.server.controllers.MuleEngineController: Failed to configure outbound router.
org.mule.umo.endpoint.MalformedEndpointException: The endpoint "smtp://" is malformed and cannot be parsed
	at org.mule.impl.endpoint.MuleEndpointURI.<init>(MuleEndpointURI.java:150)
	at com.mirth.connect.server.controllers.MuleEngineController.configureOutboundRouter(MuleEngineController.java:496)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:338)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:205)
	at com.mirth.connect.server.controllers.MuleEngineController.redeployAllChannels(MuleEngineController.java:298)
	at com.mirth.connect.server.controllers.MuleEngineController.startEngine(MuleEngineController.java:147)
	at com.mirth.connect.server.Mirth.startEngine(Mirth.java:251)
	at com.mirth.connect.server.Mirth.startup(Mirth.java:216)
	at com.mirth.connect.server.Mirth.run(Mirth.java:145)
	at com.mirth.connect.server.Mirth.main(Mirth.java:97)
Caused by: java.net.URISyntaxException: Expected authority at index 7: smtp://
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.failExpecting(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.mule.impl.endpoint.MuleEndpointURI.<init>(MuleEndpointURI.java:147)
	... 9 more

This is because the engine requires a host setting (in this case, the SMTP server) which is not provided when that option is selected. The current workaround is to use connector settings instead.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1817
Reporter: geraldb
Created: 2011-04-20T12:23:31.000-0700

**Comment by rbeckman-nextgen** [comment]
Updated to set endpoint host to "sink" if server settings are used.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-04-21T10:24:38.000-0700
