### ISSUE TITLE
Web service sender error: unsupported endpoint address

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1811]
Invoking the following web service causes an exception: http://www.nanonull.com/TimeService/TimeService.asmx?wsdl

Caused by: javax.xml.ws.WebServiceException: Unsupported endpoint address: 
	at com.sun.xml.internal.ws.api.pipe.TransportTubeFactory.create(Unknown Source)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(Unknown Source)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Unknown Source)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Unknown Source)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Unknown Source)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Unknown Source)
	at com.sun.xml.internal.ws.client.Stub.process(Unknown Source)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.doInvoke(Unknown Source)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.invoke(Unknown Source)
	at com.mirth.connect.connectors.ws.WebServiceMessageDispatcher.processMessage(WebServiceMessageDispatcher.java:147)
	at com.mirth.connect.connectors.ws.WebServiceMessageDispatcher.doDispatch(WebServiceMessageDispatcher.java:83)
	... 25 more

After some debugging, it looks like the Dispatch.RequestContext that is created in the WebServiceConnector.java:237 has a NULL value for the endpoint property, while invoking other services has the correct URL for this value.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1827
Reporter: geraldb
Created: 2011-04-29T09:16:52.000-0700

**Comment by rbeckman-nextgen** [comment]
This can be fixed by changing the port from "{http://www.Nanonull.com/TimeService/}TimeServiceHttpGet" to "{http://www.Nanonull.com/TimeService/}TimeServiceSoap".  The wrong port is selected because there are multiple.  This should be addressed by MIRTH-1790.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-04-29T11:30:03.000-0700

**Comment by rbeckman-nextgen** [comment]
This will be fixed as a part of MIRTH-1790.  There is a workaround for now.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-04-29T11:31:47.000-0700
