### ISSUE TITLE
CLONE - Load test: inconsistent data error when you manually start & stop a Mirth jdbc channel. 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1827]
Mirth channel performs replication messages between two tables in a local DBMS on the same server as Mirth, polling each 500 ms 100 new messages.
Mirth 2.1 RC1 , 256 MB Java Heap size, on Windows XP pro 32 / 2 GB RAM using Oracle 10gR2 SGBD. 
(same error with the same test using Postgres 8.4 SGBD for Mirth 2.1 RC1 + inbound and outbound Postgres tables)
The error occurred after a start and stop of the channel , Having previously received a significant number of messages - in full archive mode - (here after 100,000 msg , 0.7 KB/msg sized, for this test).

For each message received (archived as received but not distributed):  (not marked as Sent, nor errored or queued)  the following error in Mirth log:

[2011-04-21 17:11:21,542]  ERROR (com.mirth.connect.connectors.jdbc.JdbcMessageReceiver:194): Error in channel: ZBR1_Y1_ADT_DEPUIS_CPAGE
org.mule.umo.ComponentException: Cannot route event as component "f28d7ea9-8e4d-46db-9c38-6fca9e4838af" is stopped. Connector that caused exception is: f28d7ea9-8e4d-46db-9c38-6fca9e4838af. Message payload is of type: org.apache.commons.dbutils.BasicRowProcessor$CaseInsensitiveHashMap
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:258)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:176)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:143)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:229)
	at com.mirth.connect.connectors.jdbc.JdbcMessageReceiver.processMessage(JdbcMessageReceiver.java:179)
	at org.mule.providers.TransactedPollingMessageReceiver$1.doInTransaction(TransactedPollingMessageReceiver.java:98)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:104)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1846
Reporter: bruno.martin@chu-dijon.fr
Created: 2011-05-16T09:57:29.000-0700

**Comment by rbeckman-nextgen** [comment]
MIRTH-1846 affects Version 2.1.0.5389 
- OS Windows & Postgres 8.4 or Oracle 10.2
- idem OS Suse Linux 64 SLES 11 SP1 64 + Oracle 10.2

Typical error:
16 18:39:44,713]  ERROR (com.mirth.connect.connectors.jdbc.JdbcMessageReceiver:194): Error in channel: ZBR1_Y1_ADT_DEPUIS_CPAGE
org.mule.umo.ComponentException: Cannot route event as component "f28d7ea9-8e4d-46db-9c38-6fca9e4838af" is stopped. Connector that caused exception is: f28d7ea9-8e4d-46db-9c38-6fca9e4838af. Message payload is of type: org.apache.commons.dbutils.BasicRowProcessor$CaseInsensitiveHashMap
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:258)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:176)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:143)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:229)
	at com.mirth.connect.connectors.jdbc.JdbcMessageReceiver.processMessage(JdbcMessageReceiver.java:179)
	at org.mule.providers.TransactedPollingMessageReceiver$1.doInTransaction(TransactedPollingMessageReceiver.java:98)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:104)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Thread.java:662)


Imported Comment. Original Details:
Author: bruno.martin@chu-dijon.fr
Created: 2011-05-16T10:06:30.000-0700

**Comment by rbeckman-nextgen** [comment]
Sample channel

Imported Comment. Original Details:
Author: bruno.martin@chu-dijon.fr
Created: 2011-05-16T10:08:48.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-1818

Imported Comment. Original Details:
Author: jacobb
Created: 2011-05-16T11:52:16.000-0700
