### ISSUE TITLE
Error Message after trying to transfer a file from a file reader to a file writer - unable to transform message - but no transformation required - going from ASCII to ASCII - so file does not get transferred.  

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1829]
I am trying to send a file via Mirth Connect Administrator on a Windows 7 O/S 64 bit machine from a file reader ASCII file type to a file writer ASCII type and get an error message that says unable to transform message - but I did not set up a transformation, nor do I require the file to be transformed.  Because of this, this file is not getting transferred.  I have tried multiple times to take the files that are not getting transferred and redeploying the channel and these files are still not getting transferred.  

I have included the error message file in it's entirety below.  Please help.  

[2011-05-18 15:21:31,926]  ERROR (com.mirth.connect.connectors.file.FileMessageReceiver:234): Unable to route.org.mule.umo.routing.RoutingException: Failed to transform message before applying the filter. Failed to route event via endpoint: ImmutableMuleEndpoint{connector=com.mirth.connect.connectors.file.FileConnector@79a5d7e0, endpointUri=file://c:/data/lpnt/bbk, transformer=Transformer{name='ByteArrayToString', returnClass=false, returnClass=false, sourceTypes=[class [B, class java.lang.String]}, name='_fileEndpoint#-2125213528', type='receiver', properties={}, transactionConfig=org.mule.impl.MuleTransactionConfig@2090f5c5, filter=null, deleteUnacceptedMessages=false, initialised=true, securityFilter=null, synchronous=true, initialState=started, createConnector=0}. Message payload is of type: java.lang.String

	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:64)

	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)

	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)

	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)

	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:225)

	at com.mirth.connect.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:228)

	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:118)

	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)

	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)

	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)

	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)

	at java.lang.Thread.run(Unknown Source)
Caused by: org.mule.umo.transformer.TransformerException: java.lang.ArrayIndexOutOfBoundsException: 0 (com.mirth.connect.server.mule.adaptors.AdaptorException)

	at com.mirth.connect.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:284)

	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)

	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)

	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)

	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)

	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)

	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)

	... 11 more
Caused by: com.mirth.connect.server.mule.adaptors.AdaptorException: java.lang.ArrayIndexOutOfBoundsException: 0

	at com.mirth.connect.server.mule.adaptors.Adaptor.handleException(Adaptor.java:89)

	at com.mirth.connect.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:48)

	at com.mirth.connect.server.mule.adaptors.Adaptor.getMessage(Adaptor.java:61)

	at com.mirth.connect.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:255)

	... 17 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0

	at com.mirth.connect.model.converters.ER7Serializer.getMetadataFromEncoded(ER7Serializer.java:281)

	at com.mirth.connect.server.mule.adaptors.Adaptor.populateMetadataFromEncoded(Adaptor.java:100)

	at com.mirth.connect.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:40)

	... 19 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1848
Reporter: chrismcnatt
Created: 2011-05-18T13:41:09.000-0700

**Comment by rbeckman-nextgen** [comment]
The specific version I am using is 2.1.0.5389

Imported Comment. Original Details:
Author: chrismcnatt
Created: 2011-05-18T13:53:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Hello Chris

Just tried to do the same and it worked fine.
I use a delimited text as format for inbound and outbound connectors.


Imported Comment. Original Details:
Author: wello007
Created: 2011-05-20T07:14:57.000-0700
