### ISSUE TITLE
Error removing individual or filtered messages in a channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1835]
When trying to remove individual or filtered messages in a channel through the message browser, an exception is thrown.  This only occurs with the distribution.  Removing all messages works fine.  The exception is below:

com.mirth.connect.server.servlets.MessageObjectServlet: com.mirth.connect.server.controllers.ControllerException: org.apache.commons.lang.SerializationException: java.lang.ClassNotFoundException: com.mirth.connect.model.filters.MessageObjectFilter
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.removeMessages(DefaultMessageObjectController.java:409)
	at com.mirth.connect.server.servlets.MessageObjectServlet.doPost(MessageObjectServlet.java:105)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.commons.lang.SerializationException: java.lang.ClassNotFoundException: com.mirth.connect.model.filters.MessageObjectFilter
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:165)
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:192)
	at org.apache.commons.lang.SerializationUtils.clone(SerializationUtils.java:80)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.removeMessagesFromQueue(DefaultMessageObjectController.java:516)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.removeMessages(DefaultMessageObjectController.java:404)
	... 24 more
Caused by: java.lang.ClassNotFoundException: com.mirth.connect.model.filters.MessageObjectFilter
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at java.io.ObjectInputStream.resolveClass(Unknown Source)
	at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
	at java.io.ObjectInputStream.readClassDesc(Unknown Source)
	at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
	at java.io.ObjectInputStream.readObject0(Unknown Source)
	at java.io.ObjectInputStream.readObject(Unknown Source)
	at org.apache.commons.lang.SerializationUtils.deserialize(SerializationUtils.java:162)
	... 28 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1854
Reporter: jacobb
Created: 2011-05-26T11:03:45.000-0700

**Comment by rbeckman-nextgen** [comment]
Updated launcher to not use StringUtils for checking excludes in the ManifestDirectory.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-05-31T16:21:51.000-0700

**Comment by rbeckman-nextgen** [comment]
Removed commons-lang from the mirth-launcher.jar classpath so that SerializationUtils is on the right classloader.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-06-07T11:11:40.000-0700
