### ISSUE TITLE
Mirth 2.1.0 inbound ftp connector unable to pool a folder directory containing 72800 message files (1 KB each file)

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1856]
Mirth 2.1 inbound ftp connector, (tested here on localhost ftp server) is able to pool messages on a directory containing up to 10 000  1KB message files (present in the directory at a given time)  without problem, however beyond this limit, (in our case 72800 message files) the polling no bring any message.
In Mirth log, the folowing error:
--
[2011-06-20 19:11:07,558]  FATAL (org.mule.impl.DefaultComponentExceptionStrategy:84): The error is: java.net.SocketTimeoutException: Read timed out
java.lang.Exception: java.net.SocketTimeoutException: Read timed out
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Unknown Source)Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:294)
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:490)
	at org.apache.commons.net.ftp.FTP.sendCommand(FTP.java:534)
	at org.apache.commons.net.ftp.FTPClient._openDataConnection_(FTPClient.java:509)
	at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:2296)
	at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:2269)
	at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2046)
	at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2093)
	at com.mirth.connect.connectors.file.filesystems.FtpConnection.listFiles(FtpConnection.java:137)
	at com.mirth.connect.connectors.file.FileMessageReceiver.listFiles(FileMessageReceiver.java:416)
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:104)
--
(of course, ftp server state was checked in parallel during this test)

Best regards,

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1879
Reporter: bruno.martin@chu-dijon.fr
Created: 2011-06-20T10:32:15.000-0700

**Comment by rbeckman-nextgen** [comment]
This could potentially be resolved by making the socket timeout on the FTP client configurable through the connector settings.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-06-20T10:35:15.000-0700

**Comment by rbeckman-nextgen** [comment]
A higher value for the FTP timeout actually soles the problem (240 sec instead  of 10 sec) for the Timeout parameter of the inbound connector.
(just checked)

Sorry for this false alarm.

Best regards,


Imported Comment. Original Details:
Author: bruno.martin@chu-dijon.fr
Created: 2011-06-20T10:46:30.000-0700

**Comment by rbeckman-nextgen** [comment]
This issue can be addressed by changing the timeout value.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-06-20T13:50:24.000-0700
