### ISSUE TITLE
Unable to deploy channel with DICOM Listener in 2.1.1

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1861]
Channels with a DICOM Listener as the source connector will not deploy.  To recreate, simply create a new channel, select DICOM as the source connector and use all default settings.  Set all data types to DICOM.  Use any destination connector.  Save and deploy.

Channel does not deploy, and you get the following exception:

[2011-07-05 17:12:23,436]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:230): Error registering channel.
org.mule.providers.service.ConnectorServiceException: Failed to create "Message Receiver" with "dicom"
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageReceiver(ConnectorServiceDescriptor.java:321)
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageReceiver(ConnectorServiceDescriptor.java:287)
	at org.mule.providers.AbstractServiceEnabledConnector.createReceiver(AbstractServiceEnabledConnector.java:132)
	at com.mirth.connect.connectors.dimse.DICOMConnector.createReceiver(DICOMConnector.java:228)
	at org.mule.providers.AbstractConnector.registerListener(AbstractConnector.java:503)
	at com.mirth.connect.connectors.dimse.DICOMConnector.registerListener(DICOMConnector.java:195)
	at org.mule.impl.model.AbstractModel.registerListeners(AbstractModel.java:232)
	at org.mule.impl.model.AbstractModel.registerComponent(AbstractModel.java:188)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:364)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:212)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
	at java.lang.Thread.run(Unknown Source)Caused by: java.lang.SecurityException: class "org.dcm4che2.tool.dcmrcv.MirthDcmRcv"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClassCond(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructors(Unknown Source)
	at org.mule.util.ClassHelper.getConstructor(ClassHelper.java:315)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:262)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:278)
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageReceiver(ConnectorServiceDescriptor.java:319)
	... 33 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1884
Reporter: ericb
Created: 2011-07-05T17:21:00.000-0700

**Comment by rbeckman-nextgen** [comment]
This is fixed in 2.1.1.5490.b781

Imported Comment. Original Details:
Author: jacobb
Created: 2011-07-06T16:05:18.000-0700
