### ISSUE TITLE
CLI: resetstats command execution raises exception

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1862]
Open instance of CLI.  Execute resetstats command.  Exception:

C:\Program Files\Mirth Connect>mccommand.exe
Connected to Mirth Connect server @ https://127.0.0.1:8443 (2.1.1.5481)
$resetstats
com.mirth.connect.client.core.ClientException: com.mirth.connect.client.core.ClientException: method failed: HTTP/1.1 500 Server Error
        at com.mirth.connect.client.core.ServerConnection.executePostMethod(ServerConnection.java:104)
        at com.mirth.connect.client.core.Client.clearStatistics(Client.java:624)

        at com.mirth.connect.cli.CommandLineInterface.commandResetstats(CommandLineInterface.java:1105)
        at com.mirth.connect.cli.CommandLineInterface.executeStatement(CommandLineInterface.java:312)
        at com.mirth.connect.cli.CommandLineInterface.runConsole(CommandLineInterface.java:192)
        at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:157)
        at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:130)
        at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:73)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)

        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
        at com.exe4j.runtime.WinLauncher.main(Unknown Source)
        at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)
Caused by: com.mirth.connect.client.core.ClientException: method failed: HTTP/1.1 500 Server Error
        at com.mirth.connect.client.core.ServerConnection.executePostMethod(ServerConnection.java:99)
        ... 19 more
$

I first saw this happen in 2.1.0.  Still happening in 2.1.1.  Happens in both interactive and scripted mode.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1885
Reporter: ericb
Created: 2011-07-06T15:08:02.000-0700

**Comment by rbeckman-nextgen** [comment]
This issue relates to MIRTH-1849.  Deploying the channel once would fix the issue.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-07-06T15:39:12.000-0700

**Comment by rbeckman-nextgen** [comment]
This is fixed in 2.1.1.5490.b781

Imported Comment. Original Details:
Author: jacobb
Created: 2011-07-06T16:05:05.000-0700
