### ISSUE TITLE
Channel status exception

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1881]
With one channel on the dashboard, the following error appeared in the server log:

ERROR 2011-07-20 10:33:13,350 [qtp25805098-34] com.mirth.connect.server.servlets.ChannelStatusServlet: org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.UncheckedPrintWriter.setError(UncheckedPrintWriter.java:107)
	at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:280)
	at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:295)
	at org.eclipse.jetty.io.UncheckedPrintWriter.print(UncheckedPrintWriter.java:460)
	at com.mirth.connect.server.servlets.ChannelStatusServlet.doPost(ChannelStatusServlet.java:85)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:149)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:96)
	at java.io.ByteArrayOutputStream.writeTo(Unknown Source)
	at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:258)
	at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:107)
	at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:271)
	... 26 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1906
Reporter: geraldb
Created: 2011-07-20T11:19:48.000-0700

**Comment by rbeckman-nextgen** [comment]
Changed print to println for writing serialized status object.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-07-20T11:21:40.000-0700
