### ISSUE TITLE
HTTP Sender errors when URL uses a variable ${server} and Use Persistent Queues is enabled.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1890]
HTTP Sender Channel:
Source Transformer: channelMap.put("server", "localhost:5566");
Destination Sending to: http://${server}
Use Persistent Queues is set to Yes.

If the end destination is down, causing queuing, two Errors are immediately thrown:

[2011-08-04 11:38:01,848]  FATAL (org.mule.impl.DefaultComponentExceptionStrategy:84): The error is: java.net.UnknownHostException: ${server}
java.lang.Exception: java.net.UnknownHostException: ${server}
	at com.mirth.connect.connectors.http.HttpMessageDispatcher.sendPayload(HttpMessageDispatcher.java:197)
	at org.mule.providers.QueueEnabledConnector$QueueWorker.run(QueueEnabledConnector.java:218)
	at java.lang.Thread.run(Thread.java:680)Caused by: java.net.UnknownHostException: ${server}
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:195)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:432)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at java.net.Socket.<init>(Socket.java:375)
	at java.net.Socket.<init>(Socket.java:249)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:79)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:121)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:706)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:386)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)
	at com.mirth.connect.connectors.http.HttpMessageDispatcher.submitHttpRequest(HttpMessageDispatcher.java:128)
	at com.mirth.connect.connectors.http.HttpMessageDispatcher.sendPayload(HttpMessageDispatcher.java:187)
	... 2 more

[2011-08-04 11:38:01,848]  FATAL (org.mule.impl.DefaultComponentExceptionStrategy:83): The Default Component Exception Strategy has been invoked but there is no current event on the context

Channel works as expected if end system is up.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1917
Reporter: dschramm
Created: 2011-08-04T11:43:04.000-0700

**Comment by rbeckman-nextgen** [comment]
In server\src\com\mirth\connect\connectors\http\HttpMessageDispatcher.java 
I suspect you need to use URLDecoder.decode either on line 76 where you add a request to the queue, or on line 187 where you take a request off the queue. Not sure which is better.

Imported Comment. Original Details:
Author: noahpcc
Created: 2011-09-13T13:07:43.000-0700

**Comment by rbeckman-nextgen** [comment]
Can't reproduce this in the latest builds.  David, can you try again with 2.1.1 and if the issue still occurs then try it with the trunk build?

Imported Comment. Original Details:
Author: jacobb
Created: 2011-10-17T14:25:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Attaching sample channel to test error. Not erroring as expected in MC 2.1.1.5490.

Sample Message: <a><b>bbb</b></a>

Imported Comment. Original Details:
Author: dschramm
Created: 2011-10-17T15:00:11.000-0700

**Comment by rbeckman-nextgen** [comment]
On the http sender, the URL still needs to still include the protocol (e.g. "http://${server}").  If the protocol is not included in the url field, then it should also not be in the variable.

It looks like this works fine from the globalMap, but the issue is with the channel and connector map values not being persisted and reused from the queue.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-10-17T17:09:34.000-0700

**Comment by rbeckman-nextgen** [comment]
URL decode the http endpoint uri so that variables can be used in queued message addresses.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-10-17T17:54:30.000-0700
