### ISSUE TITLE
NullPointerException - Failed to disconnect on (re)deploy of a channel with a database reader source

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1900]
When you use a global variable in the URL field of the Database Reader source (e.g. $(DBConnctionString) ) a Nullpointer exception is thrown when you redeploy the channel. (Failed to disconnect)

[2011-08-29 11:27:44,958]  ERROR (com.mirth.connect.connectors.jdbc.JdbcConnector:308): Failed to disconnect: null
java.lang.NullPointerException
	at com.mirth.connect.connectors.jdbc.JdbcConnector.shutdownDataSource(JdbcConnector.java:450)
	at com.mirth.connect.connectors.jdbc.JdbcConnector.doDisconnect(JdbcConnector.java:466)
	at org.mule.providers.AbstractConnector.disconnect(AbstractConnector.java:801)
	at org.mule.providers.AbstractConnector.stopConnector(AbstractConnector.java:306)
	at org.mule.providers.AbstractConnector.doDispose(AbstractConnector.java:613)
	at org.mule.providers.AbstractConnector.dispose(AbstractConnector.java:331)
	at org.mule.MuleManager.unregisterConnector(MuleManager.java:508)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterConnectors(MuleEngineController.java:778)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterChannel(MuleEngineController.java:752)
	at com.mirth.connect.server.controllers.MuleEngineController.undeployChannels(MuleEngineController.java:267)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:184)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:46)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:615)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.mortbay.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:677)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
	at org.mortbay.http.HttpServer.service(HttpServer.java:909)
	at org.mortbay.http.HttpConnection.service(HttpConnection.java:820)
	at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:986)
	at org.mortbay.http.HttpConnection.handle(HttpConnection.java:837)
	at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:245)
	at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1929
Reporter: nicovn
Created: 2011-08-29T02:43:11.000-0700

**Comment by rbeckman-nextgen** [comment]
Got the same error when using a Database Writer destination

Imported Comment. Original Details:
Author: jlmorin
Created: 2012-07-25T13:42:17.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed with MIRTH-2320. Tested and verified that the exception no longer occurs in either the receiver or dispatcher.

Imported Comment. Original Details:
Author: brentm
Created: 2013-01-17T15:34:37.000-0800

**Comment by rbeckman-nextgen** [comment]
This was happening only when you use template variables in conjunction with JavaScript mode. That's because when in JavaScript mode **and** there is at least one replaceable variable in the URL, username, or password, the data source does not get instantiated. So in shutdownDataSource, the reference to bds.close() throws the NPE.

This is no longer a problem in 3.0 with the rewrite (MIRTH-2320), as the actual query/update execution is handled by a delegate which decides whether or not to use a persistent data source.

Imported Comment. Original Details:
Author: narupley
Created: 2013-04-01T14:39:14.000-0700
