### ISSUE TITLE
SMTP Connector attachments

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1909]
Trying to send a simple e-mail with the new SMTP Sender channel on the trunk version. I try the "Test Mail" button and it works good, so I don't have connection problems.

When I deploy the channel, it throws me this error:

Code:
ERROR 2011-09-07 13:56:33,395 [qtp2793484-35] com.mirth.connect.server.controllers.MuleEngineController: Failed to configure outbound router.
java.lang.IllegalArgumentException: Cannot invoke com.mirth.connect.connectors.smtp.SmtpConnector.setAttachments on bean class 'class com.mirth.connect.connectors.smtp.SmtpConnector' - argument type mismatch - had objects of type "java.lang.String" but expected signature "java.util.List"
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2235)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2151)
	at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1957)
	at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2064)
	at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1017)
	at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:830)
	at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:433)
	at com.mirth.connect.server.controllers.MuleEngineController.registerConnector(MuleEngineController.java:728)
	at com.mirth.connect.server.controllers.MuleEngineController.configureOutboundRouter(MuleEngineController.java:540)
	at com.mirth.connect.server.controllers.MuleEngineController.registerChannel(MuleEngineController.java:358)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:212)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:60)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2170)
	... 34 more

I doesn't put any attachment on the mail, so I don't know why fails with an "empty list". I see on code, if i'm not wrong, that the attachment list is transformed with an XML parser to a HTML list, and this error says that Mirth expects a list type, not an String.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1938
Reporter: mlizana
Created: 2011-09-07T05:40:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Tested attachments with the following MIME types: text/plain, text/xml, and application/pdf.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-10-25T10:00:48.000-0700
