### ISSUE TITLE
JMS Connection not reconnecting properly if the session is closed

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1918]
The JMS session is being closed; however, the JMS Transformer is not retrying to connect. Here's the stack trace we're getting:

ERROR 2011-09-16 08:12:09,504 [_vmConnector#9904205.b091c4d2-073e-4c90-b9c5-af14aeb154c5.receiver.1] org.mule.impl.DefaultComponentExceptionStrategy: Caught exception in Exception Strategy for: b091c4d2-073e-4c90-b9c5-af14aeb154c5: org.mule.umo.transformer.TransformerException: The Session is closed (javax.jms.IllegalStateException)
org.mule.umo.transformer.TransformerException: The Session is closed (javax.jms.IllegalStateException)
        at com.mirth.connect.connectors.jms.transformers.AbstractJmsTransformer.transformToMessage(AbstractJmsTransformer.java:157)
        at com.mirth.connect.connectors.jms.transformers.MessageObjectToJMSMessage.doTransform(MessageObjectToJMSMessage.java:39)
        at com.mirth.connect.connectors.jms.JmsMessageDispatcher.dispatchMessage(JmsMessageDispatcher.java:127)
        at com.mirth.connect.connectors.jms.JmsMessageDispatcher.doSend(JmsMessageDispatcher.java:252)
        at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:164)
        at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
        .....
Caused by: javax.jms.IllegalStateException: The Session is closed
        at org.apache.activemq.ActiveMQSession.checkClosed(ActiveMQSession.java:659)
        at org.apache.activemq.ActiveMQSession.configureMessage(ActiveMQSession.java:647)
        at org.apache.activemq.ActiveMQSession.createTextMessage(ActiveMQSession.java:377)
        at com.mirth.connect.connectors.jms.JmsMessageUtils.getMessageForObject(JmsMessageUtils.java:55)
        at com.mirth.connect.connectors.jms.transformers.AbstractJmsTransformer.transformToMessage(AbstractJmsTransformer.java:116)
        ... 27 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1947
Reporter: malcomm
Created: 2011-09-16T15:19:39.000-0700

**Comment by rbeckman-nextgen** [comment]
Attaching File: AbstractJmsTransformer.java.patch

I see where the Exception listener is being registered; however, by the time the exception notification happens, it's too late. Unfortunately, JMS core does not have a handy "checkClosed" method that ActiveMQ has.

The patch is in AbstractJmsTransformer and it just puts a simple while loop and a way to break out after 2 retry attempts. Not 100% if it makes sense to do at this level, but this was my first attempt.

Imported Comment. Original Details:
Author: malcomm
Created: 2011-09-16T15:48:57.000-0700

**Comment by rbeckman-nextgen** [comment]
Hi Marcus, 

How are you producing the stack trace? I've tried stopping the ActiveMQ server and sending a message, but unfortunately the behavior I see that is the channel stops processing until the server is start back up again.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-11-21T16:36:58.000-0800

**Comment by rbeckman-nextgen** [comment]
Unable to reproduce stacktrace.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-11-23T17:28:49.000-0800
