### ISSUE TITLE
Channel stops pulling db messages when sql server failed and restarted

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1932]
While 2 channel were pulling for messages from the SQL database, the sql server did a restart and on the Mirth side there was an exception on two channels as noted in the log "Exception occurred in channel"  java.sql.SQLException: I/O Error: Connection reset by peer: socket write error Query: SELECT top 1 [ID] as mid
      ,[RECEIVED_DATE]
      ,CAST(HL7_Transaction as varchar(MAX)) AS SOURCE_HL7
  FROM [INTEGRATION_NEW_TRANSACTIONS] where PROCESSED_DATE is NULL
ORDER BY [RECEIVED_DATE] asc

 Parameters: []

at org.apache.commons.dbutils.QueryRunner.rethrow(QueryRunner.java:542)

at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:399)

at com.mirth.connect.connectors.jdbc.JdbcMessageReceiver.getMessages(JdbcMessageReceiver.java:266)

at org.mule.providers.TransactedPollingMessageReceiver$1.doInTransaction(TransactedPollingMessageReceiver.java:91)

at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:72)

at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:104)

at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)

at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)

at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)

at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)

at java.lang.Thread.run(Unknown Source)

This was recorder on both channels.  The sql recovered but after that point the messages were not being pulled.  We stopped the channels and the status of them read "Stopped"  Trying to restart the channels we got messages "Error starting the channel due to a problem at one of the endpoints"
  
org.mule.umo.provider.ConnectorException: There is already a listener registered on this connector on endpointUri: jdbc://query. Connector that caused exception is: com.mirth.connect.connectors.jdbc.JdbcConnector@6c1194fa

at org.mule.providers.AbstractConnector.registerListener(AbstractConnector.java:500)

at org.mule.impl.model.AbstractModel.registerListeners(AbstractModel.java:231)

at org.mule.impl.model.AbstractModel.startComponent(AbstractModel.java:493)

at org.mule.management.mbeans.ModelService.startComponent(ModelService.java:50)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source)

at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source)

at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(Unknown Source)

at com.sun.jmx.mbeanserver.PerInterface.invoke(Unknown Source)

at com.sun.jmx.mbeanserver.MBeanSupport.invoke(Unknown Source)

at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)

at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)

at javax.management.remote.rmi.RMIConnectionImpl.doOperation(Unknown Source)

at javax.management.remote.rmi.RMIConnectionImpl.access$200(Unknown Source)

at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(Unknown Source)

at java.security.AccessController.doPrivileged(Native Method)

at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(Unknown Source)

at javax.management.remote.rmi.RMIConnectionImpl.invoke(Unknown Source)

at sun.reflect.GeneratedMethodAccessor674.invoke(Unknown Source)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.lang.reflect.Method.invoke(Unknown Source)

at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)

at sun.rmi.transport.Transport$1.run(Unknown Source)

at java.security.AccessController.doPrivileged(Native Method)

at sun.rmi.transport.Transport.serviceCall(Unknown Source)

at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)

at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)

at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)

at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

at java.lang.Thread.run(Unknown Source) 

The only way this stopped was to restart the entire service.  
The channels should have been able fail gracefully from the server stop and be able to pick up instead of leaving the listener "orphaned".

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1961
Reporter: johnvoigt
Created: 2011-09-26T06:30:16.000-0700

**Comment by rbeckman-nextgen** [comment]
DBReader use "connection.isclosed()" to test if the connection is fine, but java doesn't set the connection to close unless "connection.closed()" is invoked. So, when the dbFails mirth never re-tries the connection

With this patch the connection is always closed after an exception.

Imported Comment. Original Details:
Author: albertosaez
Created: 2011-10-02T16:46:20.000-0700

**Comment by rbeckman-nextgen** [comment]
A new version. 

Apache pools has an error an for some kind of driver (as the informix) launch an unexpected error at the "isValid" method, so it's needed to catch it

Imported Comment. Original Details:
Author: albertosaez
Created: 2011-10-02T17:48:02.000-0700

**Comment by rbeckman-nextgen** [comment]
We've refactored the patch and attached a new version.  Alberto, let me know if you see any issues with this new patch.

Imported Comment. Original Details:
Author: jacobb
Created: 2011-11-22T11:45:44.000-0800

**Comment by rbeckman-nextgen** [comment]
Changed the database logic to check for a valid connection, reconnect, and retry if necessary

Imported Comment. Original Details:
Author: jacobb
Created: 2011-11-22T16:30:26.000-0800
