### ISSUE TITLE
Logs fails

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1934]
Some times in dashboard server log we have:

[2011-09-26 15:09:11,083]  ERROR (com.mirth.connect.server.controllers.DefaultMessageObjectController:248): could not log message: id=19e8486e-2546-4d8a-8b5b-d71f2403cb3a
com.ibatis.common.jdbc.exception.NestedSQLException:   --- The error occurred in oracle/oracle-message.xml.  --- The error occurred while applying a parameter map.  --- Check the Message.insert-message-param.  --- Check the statement (update failed).  --- Cause: java.sql.SQLException: ORA-01461: can bind a LONG value only for insert into a LONG column
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeUpdate(MappedStatement.java:107)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:393)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:58)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.writeMessageToDatabase(DefaultMessageObjectController.java:245)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.updateMessage(DefaultMessageObjectController.java:185)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.setStatus(DefaultMessageObjectController.java:894)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.setError(DefaultMessageObjectController.java:814)
	at com.mirth.connect.connectors.js.JavaScriptMessageDispatcher.doDispatch(JavaScriptMessageDispatcher.java:95)

This happens mainly with one channel (database reader -> 4 destination ) , the other 10 channels properly log.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1963
Reporter: flytaylor
Created: 2011-09-26T08:19:30.000-0700

**Comment by rbeckman-nextgen** [comment]
We have this issue in the past and we only solve it by updating Oracle's version.

What encoding are you using in MIrth? Try setting Oracle's encoding to the same than MIrth. Even better, be sure than both are using UTF-8

Imported Comment. Original Details:
Author: albertosaez
Created: 2011-09-27T02:11:17.000-0700

**Comment by rbeckman-nextgen** [comment]
Oracle use WE8ISO8859P1 encoding. Where I can found Mirth encoding setting ?

Imported Comment. Original Details:
Author: flytaylor
Created: 2011-10-05T01:45:05.000-0700

**Comment by rbeckman-nextgen** [comment]
Mirth prints the ecoding at the startup lines in the mirth.log

If you can't change the encoding of datatabse, try to set Mirth's one to the same, by adding the the following line to the .vmoptions file

-Dfile.encoding=ISO-8859-1

But the best option is to update your oracle version

Imported Comment. Original Details:
Author: albertosaez
Created: 2011-10-05T06:13:41.000-0700

**Comment by rbeckman-nextgen** [comment]
Mirth uses windows-1252  charset. I will change it.

Thank Alberto.


Imported Comment. Original Details:
Author: flytaylor
Created: 2011-10-07T03:41:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Not sure if this will solves the issue as windows-1252 is basically ISO-8858-1, seriously try to update your oracle instance (not to 11g, but to a newer release of Oracle 10)

Imported Comment. Original Details:
Author: albertosaez
Created: 2011-10-09T09:03:28.000-0700

**Comment by rbeckman-nextgen** [comment]
Have not heard of this issue in 3.0.  If a similar issue still exists, please create a new issue with a way to reproduce it.

Imported Comment. Original Details:
Author: jacobb
Created: 2013-10-17T13:21:29.000-0700
