### ISSUE TITLE
RTF Files Generated From Document Writer Produce Blank Files

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1937]
Document writer connectors produce blank rtf files even though the same html template works for pdfs. This can happen when copy and pasting from another source into the template field of the connector since it seems like there are some invalid hidden or special characters that get copied over.

This is the resulting error:

ERROR-401: Document connector error
ERROR MESSAGE:	Error writing document
java.lang.ClassCastException: com.lowagie.text.Table cannot be cast to com.lowagie.text.TextElementArray
	at com.lowagie.text.xml.SAXiTextHandler.handleStartingTags(Unknown Source)
	at com.lowagie.text.html.SAXmyHtmlHandler.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at com.lowagie.text.html.HtmlParser.go(Unknown Source)
	at com.mirth.connect.connectors.doc.DocumentMessageDispatcher.writeDocument(DocumentMessageDispatcher.java:170)
	at com.mirth.connect.connectors.doc.DocumentMessageDispatcher.doDispatch(DocumentMessageDispatcher.java:90)
	at com.mirth.connect.connectors.doc.DocumentMessageDispatcher.doSend(DocumentMessageDispatcher.java:180)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:164)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:61)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:176)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:143)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:225)
	at com.mirth.connect.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:221)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Thread.java:680)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1966
Reporter: jeffc
Created: 2011-09-30T11:34:50.000-0700

**Comment by rbeckman-nextgen** [comment]
I've attached a channel that demonstrates this.

There are 4 destinations, the first two produce pdf files and the last two produce rtfs:

Works - PDF
Works as PDF but not as RTF
Works - RTF
Doesn't Work - RTF

They all have the same visible template, but destination 4 still fails. Destinations 2 and 4 both have some special characters that the connector doesn't seem to like with rtf files, which results in the java.lang.ClassCastException: com.lowagie.text.Table cannot be cast to com.lowagie.text.TextElementArray error.

So, destination 1-3 process correctly, but destination 4 fails.

Imported Comment. Original Details:
Author: jeffc
Created: 2011-09-30T11:43:07.000-0700

**Comment by rbeckman-nextgen** [comment]
This bug occurs when an HTML element in the template contains both a space character and a nested element. For example:

` <tr>  <td>Bar</td></tr>`

You can see this in the attached channel by viewing the contents of the template from destination 4 in a text editor and enabling the display of special characters. You will see several spaces followed by a tab, which was likely done to line it up.

This _may_ have been resolved in a newer version of iText, unfortunately we cannot upgrade due to licensing restrictions.

One option would be to automatically strip out white spaces from within the XML elements. There are XSL transforms for doing this, but this could cause issues with the template contents.

Another option would be to allow viewing of tabs and spaces along with line endings in the text field, which would have made it easier to spot this bug.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-10-20T17:15:15.000-0700

**Comment by rbeckman-nextgen** [comment]
This issue still exists with iText 2.1.7 (the latest version we can use).  That being said, it may be fixable by using an HTMLWorker instead of HtmlParser and writing the document out differently, or by simply eliminating whitespace between elements from the passed in template before parsing.

Imported Comment. Original Details:
Author: jacobb
Created: 2013-01-04T15:29:39.000-0800
