### ISSUE TITLE
Web Service Sender no longer saves fault responses

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1953]
When a web service response a fault, the fault is lost as mirth only saves the message

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1982
Reporter: albertosaez
Created: 2011-10-10T17:21:47.000-0700

**Comment by rbeckman-nextgen** [comment]
Attaching an updated patch for the current 3.x trunk.

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-10T08:10:18.000-0800

**Comment by rbeckman-nextgen** [comment]
Apparently this _**did**_ work in 1.8, but no longer works in 3.x. Had someone ask about this today. They were trying to migrate a Web Service Sender (SOAP Sender) from 1.8 to 3.0, and that fault information is now completely lost.

Imported Comment. Original Details:
Author: narupley
Created: 2014-10-10T09:14:36.000-0700

**Comment by rbeckman-nextgen** [comment]
[http://www.mirthcorp.com/community/forums/showthread.php?t=11829]

Imported Comment. Original Details:
Author: narupley
Created: 2014-10-13T07:11:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Here's an example of what 1.8.x showed:

`ERROR-410: SOAP Connector error
ERROR MESSAGE:	Error invoking WebService
AxisFault
 faultCode: {http://schemas.xmlsoap.org/soap/envelope/}Server
 faultSubcode: 
 faultString: javax.xml.ws.soap.SOAPFaultException
 faultActor: 
 faultNode: 
 faultDetail: 
	{http://xml.apache.org/axis/}stackTrace:javax.xml.ws.soap.SOAPFaultException
	at org.apache.axis.message.SOAPFaultBuilder.createFault(SOAPFaultBuilder.java:222)
	at org.apache.axis.message.SOAPFaultBuilder.endElement(SOAPFaultBuilder.java:129)
	at org.apache.axis.encoding.DeserializationContext.endElement(DeserializationContext.java:1087)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2804)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:1870)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.invokeWebService(AxisMessageDispatcher.java:295)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.doSend(AxisMessageDispatcher.java:330)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:207)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:695)

	{http://xml.apache.org/axis/}hostname:somehost.wat.com

javax.xml.ws.soap.SOAPFaultException
	at org.apache.axis.message.SOAPFaultBuilder.createFault(SOAPFaultBuilder.java:222)
	at org.apache.axis.message.SOAPFaultBuilder.endElement(SOAPFaultBuilder.java:129)
	at org.apache.axis.encoding.DeserializationContext.endElement(DeserializationContext.java:1087)
	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanEndElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2804)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:1870)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.invokeWebService(AxisMessageDispatcher.java:295)
	at com.webreach.mirth.connectors.soap.axis.AxisMessageDispatcher.doSend(AxisMessageDispatcher.java:330)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:167)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:45)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:180)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:147)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:207)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:695)`

Imported Comment. Original Details:
Author: narupley
Created: 2015-01-14T13:52:11.000-0800

**Comment by rbeckman-nextgen** [comment]
SOAPFault's may now be caught and stored within the message's response.

Imported Comment. Original Details:
Author: jaysenp
Created: 2015-01-16T09:41:17.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified that when a SOAP fault is caught, the actual fault data is stored as the response. Here's an example:

`<SOAP-ENV:Fault xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <faultcode xmlns:S="http://schemas.xmlsoap.org/soap/envelope/">S:Server</faultcode>
    <faultstring>testing</faultstring>
    <detail>
        <ns2:Exception xmlns:ns2="http://webservice.custom.com/" xmlns:ns4="http://www.w3.org/2003/05/soap-envelope">
            <message>testing</message>
        </ns2:Exception>
    </detail>
</SOAP-ENV:Fault>`

Imported Comment. Original Details:
Author: narupley
Created: 2015-02-12T17:24:52.000-0800
