### ISSUE TITLE
Ftp fails to retrieve files in rev. 2.1.1.5429

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1958]
ftp fails to connect and retrieve files.  Test read fails.  Channel deploys with fatal errors.

Get the following erroSr:

2011-10-12 21:52:31,238]  ERROR (com.mirth.connect.connectors.file.filesystems.FtpConnection:133): listFiles.changeWorkingDirectory: 550-550 XCWD valid $volume.subvolume format required.

>>>>> This is notable since I am reading from the root directory, and there should be no changing of working directory at all.

Other errors:

[2011-10-12 21:52:31,254]  FATAL (org.mule.impl.DefaultComponentExceptionStrategy:84): The error is: java.io.IOException: Ftp error: 550
java.lang.Exception: java.io.IOException: Ftp error: 550
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Unknown Source)Caused by: java.io.IOException: Ftp error: 550
	at com.mirth.connect.connectors.file.filesystems.FtpConnection.listFiles(FtpConnection.java:134)
	at com.mirth.connect.connectors.file.FileMessageReceiver.listFiles(FileMessageReceiver.java:416)
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:104)
	... 5 more

[2011-10-12 21:52:31,254]  FATAL (org.mule.impl.DefaultComponentExceptionStrategy:83): The Default Component Exception Strategy has been invoked but there is no current event on the context

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1987
Reporter: hl7360
Created: 2011-10-12T22:24:09.000-0700

**Comment by rbeckman-nextgen** [comment]
I should also add that a manually initiated ftp connection to the address succeeds with no problems.

Imported Comment. Original Details:
Author: hl7360
Created: 2011-10-12T22:25:38.000-0700

**Comment by rbeckman-nextgen** [comment]
This should be resolved as part of MIRTH-1873.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-11-21T16:13:43.000-0800

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-1873

Imported Comment. Original Details:
Author: jacobb
Created: 2011-12-20T11:43:31.000-0800
