### ISSUE TITLE
The Check File Age option on the File Reader works randomly when using ftp connector

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1961]
ftp inbound connector problem: (using check file age option)   (the problem occurs on short files - few ko)

When a file is being written by the source application and mirth ftp inbound connector read the file,  the mirth channel is then blocked althrough remaining started in the dashboard.
All the following files created by the application in the source directory, are not integrated by the Mirth connector.
Although the connector is started in the state, the following log is produced:
2011-10-17 15:36:31,463]  ERROR (com.mirth.connect.connectors.file.FileMessageReceiver:250): Error reading file //C53871.hst
Could not completely read file C53871.hst

[2011-10-17 15:36:31,700]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: 21699d00-746e-47fc-8745-ae8c4ef6a62d: org.mule.MuleException: Failed to read payload data
org.mule.MuleException: Failed to read payload data
	at com.mirth.connect.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:251)
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:118)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Thread.java:662)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-1990
Reporter: bruno.martin@chu-dijon.fr
Created: 2011-10-18T01:09:28.000-0700

**Comment by rbeckman-nextgen** [comment]
Confirmed by Help Desk. Case 18349. Possibly related to Mirth-1913.
See Nov 2 follow-up email to engineering for details.

Imported Comment. Original Details:
Author: hdmoscm
Created: 2011-11-03T06:56:02.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-1913

Imported Comment. Original Details:
Author: jacobb
Created: 2013-10-16T13:17:07.000-0700
