### ISSUE TITLE
Error when connecting to SFTP directory with space in name

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1982]
If you try to use the File Reader in SFTP mode to connect to a directory that has spaces in the name, you will see the following error:

[2011-11-11 11:23:14,645]  FATAL (org.mule.impl.DefaultComponentExceptionStrategy:84): The error is: 2: No such file 
java.lang.Exception: 2: No such file 
        at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124) 
        at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97) 
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290) 
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061) 
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575) 
        at java.lang.Thread.run(Thread.java:662)Caused by: 2: No such file 
        at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2297) 
        at com.jcraft.jsch.ChannelSftp._realpath(ChannelSftp.java:1831) 
        at com.jcraft.jsch.ChannelSftp.cd(ChannelSftp.java:268) 
        at com.mirth.connect.connectors.file.filesystems.SftpConnection.listFiles(SftpConnection.java:134) 
        at com.mirth.connect.connectors.file.FileMessageReceiver.listFiles(FileMessageReceiver.java:416) 
        at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:104) 
        ... 5 more 

This is because the space in the name is encoded as "%20" when it is saved. To fix this, the name should be escaped before the "cd" command is performed.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2014
Reporter: geraldb
Created: 2011-11-15T09:53:08.000-0800

**Comment by rbeckman-nextgen** [comment]
Spaces in the directory that were encoded as %20 are now decoded before the "cd" command.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-11-15T10:03:12.000-0800
