### ISSUE TITLE
Email Sender with empty body causes NullPointerException

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1993]
I'm trying to use an email sender with an empty body in version 2.1.1.5490. It is a customer requirement for the email body to be empty and only have a subject and attachment. When I use an email sender with an empty body I get a NullPointerException when I try to execute it. The error text is below.

I can provide an example channel that reproduces the problem but I don't know how to attach it to this bug.

I've tried plaintext and HTML and I've tried it on two different SMTP servers (gmail and a private server).

ERROR-402: SMTP connector error
ERROR MESSAGE:	Error sending email
java.lang.NullPointerException
	at com.sun.mail.handlers.text_plain.writeTo(text_plain.java:135)
	at javax.activation.ObjectDataContentHandler.writeTo(Unknown Source)
	at javax.activation.DataHandler.writeTo(Unknown Source)
	at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:264)
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1301)
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1008)
	at javax.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:415)
	at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1287)
	at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2072)
	at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2040)
	at javax.mail.Transport.send(Transport.java:119)
	at com.mirth.connect.connectors.email.SmtpMessageDispatcher.sendMailMessage(SmtpMessageDispatcher.java:200)
	at com.mirth.connect.connectors.email.SmtpMessageDispatcher.doDispatch(SmtpMessageDispatcher.java:157)
	at com.mirth.connect.connectors.email.SmtpMessageDispatcher.doSend(SmtpMessageDispatcher.java:188)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:164)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:54)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:176)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:143)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:225)
	at com.mirth.connect.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:221)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2029
Reporter: tzimme02
Created: 2011-12-08T05:29:06.000-0800

**Comment by rbeckman-nextgen** [comment]
After creating the task I see how to attach files.  I attached an example channel that will reproduce the problem.  You'll have to fill out the details for your own SMTP server.

Imported Comment. Original Details:
Author: tzimme02
Created: 2011-12-08T05:30:45.000-0800

**Comment by rbeckman-nextgen** [comment]
This is because setMsg/setHtmlMsg is always called regardless of whether the body string is null or empty. There just needs to be a check around that block so that those methods are only conditionally called. I'll attach patches for this, for both 2.2.1 and 3.0 Beta 1.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-05T12:15:25.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 6181 (2.x) and 6182 (3.0).

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-05T12:33:19.000-0800

**Comment by rbeckman-nextgen** [comment]
Tested attached channel in 2x and 3x with empty body. Email sent without errors as expected.

Imported Comment. Original Details:
Author: matts
Created: 2013-04-01T13:34:01.000-0700
