### ISSUE TITLE
org.eclipse.jetty.io.EofException in server log

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#1999]
The following error occasionally appears in the server log:

[2011-12-20 17:06:41,537]  ERROR (com.mirth.connect.server.servlets.ChannelStatusServlet:86): org.eclipse.jetty.io.RuntimeIOException: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.UncheckedPrintWriter.setError(UncheckedPrintWriter.java:107)
	at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:280)
	at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:295)
	at org.eclipse.jetty.io.UncheckedPrintWriter.print(UncheckedPrintWriter.java:460)
	at com.mirth.connect.server.servlets.ChannelStatusServlet.doPost(ChannelStatusServlet.java:83)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:475)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:1068)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:805)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:149)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:96)
	at java.io.ByteArrayOutputStream.writeTo(Unknown Source)
	at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:258)
	at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:107)
	at org.eclipse.jetty.server.HttpWriter.write(HttpWriter.java:96)
	at org.eclipse.jetty.io.UncheckedPrintWriter.write(UncheckedPrintWriter.java:271)
	... 26 more

See this thread for more reports of this bug:

http://www.mirthcorp.com/community/forums/showthread.php?t=5961

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2036
Reporter: geraldb
Created: 2011-12-21T09:08:59.000-0800

**Comment by rbeckman-nextgen** [comment]
This bug has been reported in the Jetty issue tracker, but there is no fix yet:

http://jira.codehaus.org/browse/JETTY-1240

Imported Comment. Original Details:
Author: geraldb
Created: 2011-12-21T09:10:15.000-0800

**Comment by rbeckman-nextgen** [comment]
It looks like this occurs in either the ChannelStatusServlet or ChannelStatisticsServelet, which are the ones most frequently hit from the dashboard.

Imported Comment. Original Details:
Author: geraldb
Created: 2011-12-21T09:20:47.000-0800

**Comment by rbeckman-nextgen** [comment]
Added catch for org.eclipse.jetty.io.RuntimeIOException

Imported Comment. Original Details:
Author: jacobb
Created: 2012-02-10T10:55:25.000-0800

**Comment by emoryDossmannSCP** [comment]
I'm unable to reach the link provided for the Jira. Has this issue been resolved yet? If so, what was the resolution?
