### ISSUE TITLE
Reprocessing a single message by pressing enter causes message to reprocess twice

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2001]
In the Channel Messages window, when you highlight a single message and then reprocess it, pressing 'Enter' to select the OK button, two new messages are sent through the channel.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2038
Reporter: narupley
Created: 2011-12-21T13:01:53.000-0800

**Comment by rbeckman-nextgen** [comment]
It only processes one new message for me.  Are you sure you're not just seeing the copy of the message on the Source connector plus one copy for the Destination connector?

Imported Comment. Original Details:
Author: jacobb
Created: 2011-12-21T13:22:58.000-0800

**Comment by rbeckman-nextgen** [comment]
Hmm, nope, I am aware of the separate copies for each channel connector, but this is actually reprocessing two new messages. So for example, if I click on Send Message, manually type something in, and send it, then one message is processed, and I see two entries in the Channel Messages window. Then, if I select the source connector message and reprocess it, two new source connector messages are generated (ergo, four new entries are shown in the Channel Messages window, and I can then see six total entries).

This may be linked to a bigger issue, I'm not sure. When I first posted this bug it was for 2.2 RC1, and since then I just went back to 2.1. Then, when 2.2 came out I decided to try again, and the same thing occurs. When I first did the upgrade, everything was working perfectly for about half a day, at which point this reprocessing issue came up again. Then the very next day, I started up my Mirth Connect service again, and everything is haywire. The service manager generated a pop-up that said "service could not be started," and yet I could see that it was started (whether it "successfully" started is another issue I suppose). Then when I logged into Administrator, everything takes an exorbitant amount of time, from loading the 18 channels I have on this small instance, to disabling/enabling a channel. Also, nothing will deploy either... I get the following error:

[2012-01-25 07:21:58,870]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:311): Unable to stop channel 26833595-60aa-4710-993e-b398911959e7 before undeploying it.
java.lang.NullPointerException
	at com.mirth.connect.server.controllers.DefaultChannelStatusController.getState(DefaultChannelStatusController.java:266)
	at com.mirth.connect.server.controllers.DefaultChannelStatusController.stopChannel(DefaultChannelStatusController.java:82)
	at com.mirth.connect.server.controllers.MuleEngineController.undeployChannels(MuleEngineController.java:309)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:197)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:63)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Unknown Source)

Again, this exact same behaviour happened when I attempted to upgrade to 2.2 RC1. Right now I'm just doing it on my laptop, on which I'm running Windows 7 Professional 64-bit, plenty of RAM and CPU speed. For the database, I'm using MySQL 5.5. I'm pretty sure this has something to do with Connect 2.2, because all previous versions have run perfectly, without a single hitch, on this same environment...

Imported Comment. Original Details:
Author: narupley
Created: 2012-01-25T04:25:43.000-0800

**Comment by rbeckman-nextgen** [comment]
What version of Java are you running?  So you're saying the first time you tried to reprocess a single message, it worked fine, then it started messing up after awhile?  Anything in the logs in the meantime?

Imported Comment. Original Details:
Author: jacobb
Created: 2012-01-26T14:04:10.000-0800

**Comment by rbeckman-nextgen** [comment]
I'm running Java version 1.6.0_26. All my MySQL tables are InnoDB. This actually happens with Derby as well, so I don't think it's necessarily a straight database issue. Also, sometimes it happens on the very first reprocessing attempt, and sometimes it happens on the second or third.

I cranked the logging up to DEBUG and reproduced the issue; I've attached the logs. I was using MySQL during the time the logs were recorded.

I've also attached a video to show what happens (it's an avi within a rar within a zip, sorry lol); I recorded it after I switched to Derby.

Imported Comment. Original Details:
Author: narupley
Created: 2012-01-27T04:10:18.000-0800

**Comment by rbeckman-nextgen** [comment]
I found the bug.  It happens the second time for you because you press Enter to perform the reprocess.  There's a bug that causes this to press OK twice.  Either click OK or press space for now.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-01-27T10:35:17.000-0800

**Comment by rbeckman-nextgen** [comment]
Removed the key listener for Enter on the OK button for reprocessing a message and on the Generate button in the Database Dialog.  MIRTH-2021 added this behavior to all buttons, so leaving these key listeners cause the ok button actions to be triggered twice.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-01-27T11:08:50.000-0800

**Comment by rbeckman-nextgen** [comment]
Wow, great catch; I never even thought of that... thanks!

Imported Comment. Original Details:
Author: narupley
Created: 2012-01-27T11:12:37.000-0800
