### ISSUE TITLE
Could not log message, error occurred while applying a parameter map for 'channelMap' property

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2025]
The following error occurs when non-strings are stored in the maps:

[2012-01-17 14:36:20,196]  ERROR (com.mirth.connect.server.controllers.DefaultMessageObjectController:243): could not log message: id=7518c1d8-d4c3-467a-baa8-c7c12025199c
com.ibatis.common.jdbc.exception.NestedSQLException:   --- The error occurred in derby/derby-message.xml.  --- The error occurred while applying a parameter map.  --- Check the Message.insert-message-param.  --- Check the parameter mapping for the 'channelMap' property.  --- Cause: com.thoughtworks.xstream.converters.ConversionException: Could not call org.mozilla.javascript.xmlimpl.XMLList.writeObject() : Could not call org.mozilla.javascript.ImporterTopLevel.writeObject() : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : ---- Debugging information ----message             : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject()cause-exception     : com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceExceptioncause-message       : -------------------------------message             : Could not call org.mozilla.javascript.ImporterTopLevel.writeObject()cause-exception     : com.thoughtworks.xstream.converters.ConversionExceptioncause-message       : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : -------------------------------message             : Could not call org.mozilla.javascript.xmlimpl.XMLList.writeObject()cause-exception     : com.thoughtworks.xstream.converters.ConversionExceptioncause-message       : Could not call org.mozilla.javascript.ImporterTopLevel.writeObject() : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : ---- Debugging information ----message             : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject()cause-exception     : com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceExceptioncause-message       : --------------------------------------------------------------
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeUpdate(MappedStatement.java:110)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:393)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:58)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.writeMessageToDatabase(DefaultMessageObjectController.java:240)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.updateMessage(DefaultMessageObjectController.java:180)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.setStatus(DefaultMessageObjectController.java:889)
	at com.mirth.connect.server.controllers.DefaultMessageObjectController.setSuccess(DefaultMessageObjectController.java:813)
	at com.mirth.connect.connectors.file.FileMessageDispatcher.doDispatch(FileMessageDispatcher.java:103)
	at com.mirth.connect.connectors.file.FileMessageDispatcher.doSend(FileMessageDispatcher.java:139)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:164)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:54)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:176)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:143)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:225)
	at com.mirth.connect.connectors.http.HttpMessageReceiver.processData(HttpMessageReceiver.java:182)
	at com.mirth.connect.connectors.http.HttpMessageReceiver.access$400(HttpMessageReceiver.java:49)
	at com.mirth.connect.connectors.http.HttpMessageReceiver$RequestHandler.handle(HttpMessageReceiver.java:67)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:943)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:879)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Unknown Source)Caused by: com.thoughtworks.xstream.converters.ConversionException: Could not call org.mozilla.javascript.xmlimpl.XMLList.writeObject() : Could not call org.mozilla.javascript.ImporterTopLevel.writeObject() : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : ---- Debugging information ----message             : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject()cause-exception     : com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceExceptioncause-message       : -------------------------------message             : Could not call org.mozilla.javascript.ImporterTopLevel.writeObject()cause-exception     : com.thoughtworks.xstream.converters.ConversionExceptioncause-message       : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : -------------------------------message             : Could not call org.mozilla.javascript.xmlimpl.XMLList.writeObject()cause-exception     : com.thoughtworks.xstream.converters.ConversionExceptioncause-message       : Could not call org.mozilla.javascript.ImporterTopLevel.writeObject() : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : ---- Debugging information ----message             : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject()cause-exception     : com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceExceptioncause-message       : --------------------------------------------------------------
	at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteObject(SerializationMethodInvoker.java:103)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doMarshal(SerializableConverter.java:205)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:54)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:86)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:78)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:63)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:63)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:86)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:78)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:63)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:98)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:38)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:845)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:834)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:815)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:805)
	at com.mirth.connect.model.converters.ObjectXMLSerializer.toXML(ObjectXMLSerializer.java:124)
	at com.mirth.connect.server.sqlmap.extensions.SerializedObjectTypeHandler.setParameter(SerializedObjectTypeHandler.java:23)
	at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
	at com.ibatis.sqlmap.engine.mapping.parameter.ParameterMap.setParameter(ParameterMap.java:166)
	at com.ibatis.sqlmap.engine.mapping.parameter.ParameterMap.setParameters(ParameterMap.java:126)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:78)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.sqlExecuteUpdate(MappedStatement.java:216)
	at com.ibatis.sqlmap.engine.mapping.statement.MappedStatement.executeUpdate(MappedStatement.java:94)
	... 44 moreCaused by: com.thoughtworks.xstream.converters.ConversionException: Could not call org.mozilla.javascript.ImporterTopLevel.writeObject() : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : ---- Debugging information ----message             : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject()cause-exception     : com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceExceptioncause-message       : -------------------------------message             : Could not call org.mozilla.javascript.ImporterTopLevel.writeObject()cause-exception     : com.thoughtworks.xstream.converters.ConversionExceptioncause-message       : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : -------------------------------
	at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteObject(SerializationMethodInvoker.java:103)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doMarshal(SerializableConverter.java:205)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:54)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:86)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:78)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:63)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter$1.defaultWriteObject(SerializableConverter.java:166)
	at com.thoughtworks.xstream.core.util.CustomObjectOutputStream.defaultWriteObject(CustomObjectOutputStream.java:80)
	at org.mozilla.javascript.ScriptableObject.writeObject(ScriptableObject.java:2828)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteObject(SerializationMethodInvoker.java:99)
	... 68 moreCaused by: com.thoughtworks.xstream.converters.ConversionException: Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject() : ---- Debugging information ----message             : Could not call org.mozilla.javascript.NativeIterator$StopIteration.writeObject()cause-exception     : com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceExceptioncause-message       : -------------------------------
	at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteObject(SerializationMethodInvoker.java:103)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doMarshal(SerializableConverter.java:205)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:54)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:86)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:78)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:63)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:63)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:86)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:78)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:63)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter$1.defaultWriteObject(SerializableConverter.java:166)
	at com.thoughtworks.xstream.core.util.CustomObjectOutputStream.defaultWriteObject(CustomObjectOutputStream.java:80)
	at org.mozilla.javascript.ScriptableObject.writeObject(ScriptableObject.java:2828)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteObject(SerializationMethodInvoker.java:99)
	... 80 moreCaused by: com.thoughtworks.xstream.core.TreeMarshaller$CircularReferenceException: 
	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:83)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:78)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:63)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter$1.defaultWriteObject(SerializableConverter.java:166)
	at com.thoughtworks.xstream.core.util.CustomObjectOutputStream.defaultWriteObject(CustomObjectOutputStream.java:80)
	at org.mozilla.javascript.ScriptableObject.writeObject(ScriptableObject.java:2828)
	at sun.reflect.GeneratedMethodAccessor77.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.thoughtworks.xstream.converters.reflection.SerializationMethodInvoker.callWriteObject(SerializationMethodInvoker.java:99)
	... 97 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2064
Reporter: jacobb
Created: 2012-01-17T15:22:54.000-0800

**Comment by rbeckman-nextgen** [comment]
Added back the old MapTypeHandler and set it to be used for maps instead of the SerializedObjectTypeHandler. Bug caused by MIRTH-1915.


Imported Comment. Original Details:
Author: jacobb
Created: 2012-01-18T11:11:55.000-0800
