### ISSUE TITLE
database reader - ORA-00911: invalid character Query

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2047]
When using the integrated query builder, Oracle is throwing an error since the carriage return are trimmed from the query

[2012-02-03 11:16:37,523] FATAL (org.mule.impl.DefaultComponentExceptionStrategy:8 4): The error is: ORA-00911: invalid character
Query: SELECT OEN_ESO_ADMIN.MESSAGE_ID AS OEN_ESO_ADMIN_MESSAGE_ID, 
OEN_ESO_ADMIN.MESSAGE AS OEN_ESO_ADMIN_MESSAGE
FROM OEN_ESO_ADMIN
WHERE OEN_ESO_ADMIN.PROCESS_STATUS_FLAG = 10
AND OEN_ESO_ADMIN.MESSAGE_TYPE='ADT';

Parameters: []
java.sql.SQLException: ORA-00911: invalid character Query: SELECT OEN_ESO_ADMIN.MESSAGE_ID AS OEN_ESO_ADMIN_MESSAGE_ID, OEN_ESO_ADMIN.MESSAGE AS OEN_ESO_ADMIN_MESSAGEFROM OEN_ESO_ADMINWHERE OEN_ESO_ADMIN.PROCESS_STATUS_FLAG = 10AND OEN_ESO_ADMIN.MESSAGE_TYPE='ADT'; Parameters: []
at org.apache.commons.dbutils.QueryRunner.rethrow(Que ryRunner.java:542)
at org.apache.commons.dbutils.QueryRunner.query(Query Runner.java:399)
at com.mirth.connect.connectors.jdbc.JdbcMessageRecei ver.getMessages(JdbcMessageReceiver.java:266)
at org.mule.providers.TransactedPollingMessageReceive r$1.doInTransaction(TransactedPollingMessageReceiv er.java:91)
at org.mule.transaction.TransactionTemplate.execute(T ransactionTemplate.java:72)
at org.mule.providers.TransactedPollingMessageReceive r.poll(TransactedPollingMessageReceiver.java:104)
at org.mule.providers.PollingMessageReceiver.run(Poll ingMessageReceiver.java:97)
at org.mule.impl.work.WorkerContext.run(WorkerContext .java:290)
at edu.emory.mathcs.backport.java.util.concurrent.Thr eadPoolExecutor.runWorker(ThreadPoolExecutor.java: 1061)
at edu.emory.mathcs.backport.java.util.concurrent.Thr eadPoolExecutor$Worker.run(ThreadPoolExecutor.java :575)
at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2087
Reporter: wello007
Created: 2012-02-03T06:08:20.000-0800

**Comment by rbeckman-nextgen** [comment]
Reproduced in 2.1.1 and in 3.0 trunk. This only appears to happen if the statement is terminated with a semi-colon.

Imported Comment. Original Details:
Author: brentm
Created: 2013-10-18T16:38:50.000-0700

**Comment by rbeckman-nextgen** [comment]
The semi-colon appears to be the cause of the problem and this was resolved in MIRTH-2097. Without a semi-colon, I couldn't reproduce this error and I believe the carriage returns were likely only removed in the printed error message.

Imported Comment. Original Details:
Author: brentm
Created: 2013-10-21T09:12:50.000-0700
