### ISSUE TITLE
NullPointerException on generateAck during an undeploy or redeploy

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2054]
When redeploying a channel, generateAck can throw a NullPointerException when trying to read the deployed channel cache to get the inbound protocol.  This is because the channel was removed from the deployed channel cache during the undeploy.

[2012-02-08 16:07:09,621]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: 0187dbb6-95f9-4a4c-b9cd-0afbaea2c3d8: java.lang.NullPointerException
java.lang.NullPointerException 
at com.mirth.connect.connectors.mllp.MllpMessageReceiver$TcpWorker.generateACK(MllpMessageReceiver.java:543) 
at com.mirth.connect.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:509)
at com.mirth.connect.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:431) 
at com.mirth.connect.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:348)
at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290) 
at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575) 
at java.lang.Thread.run(Thread.java:662)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2095
Reporter: jacobb
Created: 2012-02-08T14:48:18.000-0800

**Comment by rbeckman-nextgen** [comment]
Retrieve the inboundProtocol as a part of the TCP Worker so that it always exists as long as the TCP Worker is still around.  Default back to the general channel cache if there is an issue getting it from the deployed channel cache.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-02-08T15:45:39.000-0800
