### ISSUE TITLE
Webservices sender - Could not find a type when loading the WSDL

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2104]
Imported Issue. Original Details:
Jira Issue Key: MIRTH-2152
Reporter: wello007
Created: 2012-05-15T23:44:19.000-0700

**Comment by rbeckman-nextgen** [comment]
ERROR 2012-05-15 10:50:39,506 [SwingWorker] com.eviware.soapui.SoapUI: An error occured [error: src-resolve.a: Could not find type 'CS'. Do you mean to refer to the type named cs@urn:hl7-org:v3?], see error log for details
ERROR 2012-05-15 10:50:39,507 [SwingWorker] soapui.errorlog: org.apache.xmlbeans.XmlException: error: src-resolve.a: Could not find type 'CS'. Do you mean to refer to the type named cs@urn:hl7-org:v3?
org.apache.xmlbeans.XmlException: error: src-resolve.a: Could not find type 'CS'. Do you mean to refer to the type named cs@urn:hl7-org:v3?
	at org.apache.xmlbeans.impl.schema.SchemaTypeSystemCompiler.compile(SchemaTypeSystemCompiler.java:225)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.xmlbeans.XmlBeans.compileXmlBeans(XmlBeans.java:667)
	at org.apache.xmlbeans.XmlBeans.compileXsd(XmlBeans.java:553)
	at com.eviware.soapui.impl.wsdl.support.xsd.SchemaUtils.buildSchemaTypes(SchemaUtils.java:287)
	at com.eviware.soapui.impl.wsdl.support.xsd.SchemaUtils.loadSchemaTypes(SchemaUtils.java:194)
	at com.eviware.soapui.impl.support.definition.support.XmlSchemaBasedInterfaceDefinition.loadSchemaTypes(XmlSchemaBasedInterfaceDefinition.java:79)
	at com.eviware.soapui.impl.wsdl.support.wsdl.WsdlInterfaceDefinition.load(WsdlInterfaceDefinition.java:61)
	at com.eviware.soapui.impl.wsdl.support.wsdl.WsdlContext.loadDefinition(WsdlContext.java:66)
	at com.eviware.soapui.impl.wsdl.support.wsdl.WsdlContext.loadDefinition(WsdlContext.java:30)
	at com.eviware.soapui.impl.support.definition.support.AbstractDefinitionContext.cacheDefinition(AbstractDefinitionContext.java:268)
	at com.eviware.soapui.impl.support.definition.support.AbstractDefinitionContext.access$400(AbstractDefinitionContext.java:44)
	at com.eviware.soapui.impl.support.definition.support.AbstractDefinitionContext$Loader.construct(AbstractDefinitionContext.java:235)
	at com.eviware.soapui.support.swing.SwingWorkerDelegator.construct(SwingWorkerDelegator.java:46)
	at com.eviware.soapui.support.swing.SwingWorker$2.run(SwingWorker.java:149)
	at java.lang.Thread.run(Unknown Source)

Imported Comment. Original Details:
Author: wello007
Created: 2012-05-15T23:47:34.000-0700

**Comment by rbeckman-nextgen** [comment]
Is there a public web service we can refer to to reproduce this problem?

Imported Comment. Original Details:
Author: jacobb
Created: 2013-10-17T17:49:54.000-0700
