### ISSUE TITLE
Getting weird NPE in MC Dashboard

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2131]
Been having issues all day preparing for a demo, finally started the Java Console and see I'm getting the following NPE:

Java Web Start 1.6.0_33
Using JRE version 1.6.0_33-b03-424-11M3720 Java HotSpot(TM) 64-Bit Server VM
User home directory = /Users/stevek
----------------------------------------------------
c:   clear console window
f:   finalize objects on finalization queue
g:   garbage collect
h:   display this help message
m:   print memory usage
o:   trigger logging
p:   reload proxy configuration
q:   hide console
r:   reload policy configuration
s:   dump system and deployment properties
t:   dump thread list
v:   dump thread stack
0-5: set trace level to <n>
----------------------------------------------------
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mirth.connect.client.ui.ImageCellRenderer.getTableCellRendererComponent(ImageCellRenderer.java:39)
	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7023)
	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7410)
	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6925)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:167)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:147)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:194)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:388)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:398)
	at javax.swing.DefaultListSelectionModel.addSelectionInterval(DefaultListSelectionModel.java:501)
	at javax.swing.JTable.addRowSelectionInterval(JTable.java:2156)
	at com.mirth.connect.client.ui.DashboardPanel.updateTable(DashboardPanel.java:237)
	at com.mirth.connect.client.ui.Frame$17.done(Frame.java:2318)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:717)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:814)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:95)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:824)
	at javax.swing.Timer.fireActionPerformed(Timer.java:291)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:221)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:682)
	at java.awt.EventQueue.access$000(EventQueue.java:85)
	at java.awt.EventQueue$1.run(EventQueue.java:643)
	at java.awt.EventQueue$1.run(EventQueue.java:641)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:87)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:652)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2186
Reporter: steven_kehlet
Created: 2012-07-09T13:40:45.000-0700

**Comment by rbeckman-nextgen** [comment]
I can pretty reliably reproduce it by stopping a channel. Logging out/back in makes the dashboard responsive again to "Refresh" etc.


Imported Comment. Original Details:
Author: steven_kehlet
Created: 2012-07-09T13:48:37.000-0700

**Comment by rbeckman-nextgen** [comment]
This issue appears to only affect Mac OSX clients so far. 

Java sometimes calls the getTableCellRendererComponent method of a TableCellRenderer with a hard-coded null value, but doesn't do anything with the returned Component. The culprit is in JTable.getAccessibleChild (line 7023). The result is that the client Dashboard or other pages could become unresponsive or have display glitches

http://stackoverflow.com/questions/3054775/java-swing-jtable-strange-behavior-from-getaccessiblechild-method-resulting

This means we must explicitly check for null values in all custom implementations of TableCellRenderer. A patch has been attached to this comment. 

Imported Comment. Original Details:
Author: wayneh
Created: 2012-10-15T11:29:06.000-0700

**Comment by rbeckman-nextgen** [comment]
Added check for null "value" in ImageCellRenderer.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-11-09T13:13:14.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified that this no longer occurs in the 2.x branch and the main branch.

Imported Comment. Original Details:
Author: wayneh
Created: 2012-12-20T12:06:03.000-0800
