### ISSUE TITLE
Last line of Javascript in code template threw errors, unable to deploy channels

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2146]
There was a problem deploying channels and the errors below popped up and the deploy failed.
We narrowed it down to a code template, comment line in Javascript.
"//}"

After we removed that line, it was able to deploy channels again, it was the last line, but there are still comments before it.

Here is what the comment looked like in the code template:

//	var outString = new String(mString);
//	var padLength = new Number(mLength);
//	if (outString=='null'){
//		outString=''
//	}
//	while( outString.length<padLength)
//	{
//		outString = ' ' + outString;
//	}
//    if 
//	return outString;
//}
	// write code here.
//}

The errors in deploy seemed to only occur in channels with transformers, even ones that didn't call any templates.  The comments will work if /* and */ is used instead.

ERROR 1: 

[2012-08-14 17:35:27,272]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:376): Failed to configure outbound router.
org.mule.umo.lifecycle.InitialisationException: Initialisation Failure: invalid return (5f03ca21-35b2-411f-bb79-26ab956dab6d#791)
	at com.mirth.connect.connectors.js.JavaScriptConnector.initFromServiceDescriptor(JavaScriptConnector.java:69)
	at org.mule.providers.AbstractServiceEnabledConnector.doInitialise(AbstractServiceEnabledConnector.java:54)
........

ERROR 2:

[2012-08-14 17:36:48,230]  ERROR (com.mirth.connect.server.mule.transformers.JavaScriptTransformer:179): ERROR-300: Transformer error
com.mirth.connect.server.MirthJavascriptTransformerException: 
CONNECTOR:
	TransactionLogger
SCRIPT SOURCE:
	Filter/Transformer
LINE NUMBER:
	799
LINE SOURCE:
	}
DETAILS:
	syntax error

ERROR 3:

[2012-08-14 17:36:48,204]  ERROR (com.mirth.connect.server.controllers.MuleEngineController:369): Failed to configure inbound router.
org.mule.umo.lifecycle.InitialisationException: Initialisation Failure: CONNECTOR:
	sourceConnectorSCRIPT SOURCE:
	Filter/TransformerLINE NUMBER:
	827LINE SOURCE:
	}DETAILS:
	syntax error

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2203
Reporter: johnsond
Created: 2012-08-14T10:44:28.000-0700

**Comment by rbeckman-nextgen** [comment]
I have attached the log files for the errors, reproduced on my test machine, logs start on 8-14

Imported Comment. Original Details:
Author: johnsond
Created: 2012-08-14T10:45:05.000-0700

**Comment by rbeckman-nextgen** [comment]
Code template that had problems, last comment line needed to be removed

Imported Comment. Original Details:
Author: johnsond
Created: 2012-08-14T10:46:51.000-0700

**Comment by rbeckman-nextgen** [comment]
Simple channel with a transformer that couldn't deploy

Imported Comment. Original Details:
Author: johnsond
Created: 2012-08-14T10:47:49.000-0700

**Comment by rbeckman-nextgen** [comment]
Related to ticket [ 20495 ] CMFT - Error when deploying channel

Imported Comment. Original Details:
Author: johnsond
Created: 2012-08-14T10:48:44.000-0700

**Comment by rbeckman-nextgen** [comment]
This also affected 2.2.1.5861

Imported Comment. Original Details:
Author: johnsond
Created: 2012-08-14T10:54:02.000-0700

**Comment by rbeckman-nextgen** [comment]
If you have this code:
\\
\\
`{ // outString='' // }`
\\
That's incorrect syntax. In JavaScript (similar to a lot of languages), line comments cause everything in that line (after the //) to be ignored by the compiler. So you have a non-ignored open bracket, without any closing bracket, and hence the syntax error.

If there is a syntax error, the Administrator will not allow you to save it. But, you can technically import an invalid code template via the CLI, or by importing a server config that contains an invalid code template. There should be validation done to ensure that can't happen.

Imported Comment. Original Details:
Author: narupley
Created: 2013-10-18T13:38:44.000-0700

**Comment by rbeckman-nextgen** [comment]
The fact that channels aren't able to deploy when there are invalid code templates is expected. However the fact that users can actually save invalid code templates is still an issue, and will be addressed with MIRTH-3019.

Imported Comment. Original Details:
Author: narupley
Created: 2013-10-18T13:54:06.000-0700
