### ISSUE TITLE
NPE: Unable to stop channel before undeploying it

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2186]
We cannot undeploy our channels, which makes it hard to modify them and redeploy them:

ERROR 2012-10-12 17:17:15,971 [qtp31766529-36] com.mirth.connect.server.controllers.MuleEngineController: Unable to stop channel 158b42f6-804a-4cb7-aaa2-a51b68c4a1e5 before undeploying it.
java.lang.NullPointerException
        at com.mirth.connect.server.controllers.DefaultChannelStatusController.getState(DefaultChannelStatusController.java:266)
        at com.mirth.connect.server.controllers.DefaultChannelStatusController.stopChannel(DefaultChannelStatusController.java:82)
        at com.mirth.connect.server.controllers.MuleEngineController.undeployChannels(MuleEngineController.java:309)
        at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:197)
        at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:63)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
        at java.lang.Thread.run(Thread.java:722)

Looking at https://svn.mirthcorp.com/connect/tags/2.2.1/server/src/com/mirth/connect/server/controllers/DefaultChannelStatusController.java, line 266 is:

        } finally {
            jmxConnection.close(); // Line 266
        }

The jmxConnection reference is null because the earlier call to JMXConnectionFactory.createJMXConnection() either threw an Exception or returned null. The original exception is being swallowed by the NPE in the finally block.

That jmxConnection.close() needs to have a null-check surrounding it.

This was reported in MIRTH-2094 and dismissed as harmless. It is **not** harmless because the channel cannot be undeployed: a server restart is necessary to change channel configuration. Also, if there is an underlying exception (which may explain why the JMX connection can't be made), it is being hidden by the NPE. Finally, the NPE may turn an ignorable exception (which might actually allow the channel to undeploy) into a possibly non-ignorable exception (the NPE itself) because the original is swallowed.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2244
Reporter: cschultz@chadis.com
Created: 2012-10-12T10:39:18.000-0700

**Comment by rbeckman-nextgen** [comment]
Added null check around jmxConnection.close() to prevent "Unable to stop channel before undeploying it" NPE.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-11-09T13:08:34.000-0800

**Comment by rbeckman-nextgen** [comment]
We now perform null checks around all jmxConnection.close() statements. This should allow the underlying cause behind why the jmxConnection could not be obtained to be revealed. 

Imported Comment. Original Details:
Author: wayneh
Created: 2013-05-22T12:40:34.000-0700
