### ISSUE TITLE
Cannot load private extensions when using Java 7u6

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2201]
Steps to reproduce:
1) install a private extension
2) try to launch mirth connect via webstart, you will see a stacktrace:

java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: java.security.InvalidKeyException: Wrong key usage
	at com.sun.deploy.security.TrustDecider.doCheckRevocationStatus(Unknown Source)
	at com.sun.deploy.security.TrustDecider.validateChain(Unknown Source)
	at com.sun.deploy.security.TrustDecider.isAllPermissionGranted(Unknown Source)
	at com.sun.javaws.security.AppPolicy.grantUnrestrictedAccess(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResourcesHelper(Unknown Source)
	at com.sun.javaws.security.JNLPSignedResourcesHelper.checkSignedResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareAllResources(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
	at com.sun.javaws.Launcher.launch(Unknown Source)
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.security.cert.CertPathValidatorException: java.security.InvalidKeyException: Wrong key usage
	at sun.security.provider.certpath.OCSPResponse.verifyResponse(OCSPResponse.java:541)
	at sun.security.provider.certpath.OCSPResponse.<init>(OCSPResponse.java:494)
	at sun.security.provider.certpath.OCSP.check(OCSP.java:261)
	at sun.security.provider.certpath.OCSP.check(OCSP.java:165)
	at sun.security.provider.certpath.OCSP.check(OCSP.java:130)
	at com.sun.deploy.security.TrustDecider.doOCSPEEValidation(Unknown Source)
	... 16 more
Caused by: java.security.InvalidKeyException: Wrong key usage
	at java.security.Signature.initVerify(Signature.java:490)
	at sun.security.provider.certpath.OCSPResponse.verifyResponse(OCSPResponse.java:524)
	... 21 more

This is potentially a bug with java 7u6, see this link for more details: https://forums.oracle.com/forums/thread.jspa?threadID=2434846

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2259
Reporter: dschramm
Created: 2012-11-07T09:13:22.000-0800

**Comment by rbeckman-nextgen** [comment]
Official bug report:

http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7198537

Potential workaround is to set the "Enable online certificate validation" to true:

http://www.java.net/forum/topic/jdk/java-se-snapshots-project-feedback/os-x-jdk-7u6-will-not-run-signed-jnlp-apps

Imported Comment. Original Details:
Author: geraldb
Created: 2012-11-07T09:19:47.000-0800

**Comment by rbeckman-nextgen** [comment]
The workaround did not work for me.

Imported Comment. Original Details:
Author: dschramm
Created: 2012-11-07T09:25:38.000-0800

**Comment by rbeckman-nextgen** [comment]
In the meantime, just uninstall Java 7. Here is how to do it:

http://www.java.com/en/download/help/mac_uninstall_java.xml
then
http://support.apple.com/kb/HT5559?viewlocale=en_US

Imported Comment. Original Details:
Author: dschramm
Created: 2012-11-07T09:44:55.000-0800

**Comment by rbeckman-nextgen** [comment]
Java 1.7.0_05 and lower, or 1.7.0_10 and higher should work.  This was broken in versions 1.7.0_06 through 1.7.0_09.

Imported Comment. Original Details:
Author: jacobb
Created: 2012-12-26T17:54:08.000-0800

**Comment by rbeckman-nextgen** [comment]
This should be fixed with the latest cert from DigiCert.  The certificate has also been updated to one that won't expire until 2016.

Imported Comment. Original Details:
Author: jacobb
Created: 2013-03-29T10:15:30.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified on both the 2.x branch and the 3.0 trunk that private plugins don't cause webstart to fail anymore (tested with 1.7.0_09).

Imported Comment. Original Details:
Author: narupley
Created: 2013-04-03T10:10:57.000-0700
