### ISSUE TITLE
Mirth doesn't start on some systems.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#223]
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.webreach.mirth.server.controllers.SystemLogger.<init>(SystemLogger.java:43)
    at com.webreach.mirth.server.Mirth.<init>(Mirth.java:65)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:494)
    at java.lang.Class.newInstance0(Class.java:350)
    at java.lang.Class.newInstance(Class.java:303)
    at com.webreach.mirth.server.launcher.Launcher.main(Launcher.java:38)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Error occurred.  Cause: com.ibatis.common.xml.NodeletException: Error parsing XML.  Cause: java.net.ConnectException: Connection timed out: connect
    at com.webreach.mirth.server.util.SqlConfig.<clinit>(SqlConfig.java:24)
    ... 9 more
Caused by: java.lang.RuntimeException: Error occurred.  Cause: com.ibatis.common.xml.NodeletException: Error parsing XML.  Cause: java.net.ConnectException: Connection timed out: connect
    at com.ibatis.sqlmap.engine.builder.xml.SqlMapConfigParser.parse(SqlMapConfigParser.java:84)
    at com.ibatis.sqlmap.client.SqlMapClientBuilder.buildSqlMapClient(SqlMapClientBuilder.java:62)
    at com.webreach.mirth.server.util.SqlConfig.<clinit>(SqlConfig.java:22)
    ... 9 more
Caused by: com.ibatis.common.xml.NodeletException: Error parsing XML.  Cause: java.net.ConnectException: Connection timed out: connect
    at com.ibatis.common.xml.NodeletParser.parse(NodeletParser.java:52)
    at com.ibatis.sqlmap.engine.builder.xml.SqlMapConfigParser.parse(SqlMapConfigParser.java:81)
    ... 11 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:333)
    at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:195)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:182)
    at java.net.Socket.connect(Socket.java:516)
    at java.net.Socket.connect(Socket.java:466)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:157)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:365)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:477)
    at sun.net.www.http.HttpClient.<init>(HttpClient.java:214)
    at sun.net.www.http.HttpClient.New(HttpClient.java:287)
    at sun.net.www.http.HttpClient.New(HttpClient.java:299)
    at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:796)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:748)
    at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:673)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:917)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:973)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:905)
    at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:872)
    at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:282)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDispatcher.dispatch(XMLDocumentScannerImpl.java:1021)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:368)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:834)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:148)
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:250)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:292)
    at com.ibatis.common.xml.NodeletParser.createDocument(NodeletParser.java:147)
    at com.ibatis.common.xml.NodeletParser.parse(NodeletParser.java:49)
    ... 12 more

-Chris:
	
Strange - this issue seems to be due to not being able to reach the apache.org site to resolve the ibatis DTD:

http://www.mail-archive.com/dev@ibatis.apache.org/msg01758.html

It should use the DTD from the JAR (as specified by the Apache developers) but we'll look into this.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-204
Reporter: albertosaez
Created: 2006-12-19T09:52:18.000-0800

**Comment by rbeckman-nextgen** [comment]
I'm having the same problem for MIRTH 1.3.1

The problem is clearly related to the ibates and its search for the DTD.

Imported Comment. Original Details:
Author: albertosaez
Created: 2006-12-23T11:17:42.000-0800
