### ISSUE TITLE
Message functions are not supported.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2269]
A filter is set up in the channel's source to check message type with function messageObject.getType() available in Message Functions Reference. After it's deployed and a ADT message is sent, the following error is thrown:

ERROR-300: Transformer error
ERROR MESSAGE:	Error evaluating filter/transformer
com.mirth.connect.server.MirthJavascriptTransformerException: 
CHANNEL:	test-ADT
CONNECTOR:	sourceConnector
SCRIPT SOURCE:	
SOURCE CODE:	
13: function doScript() {
14: var newMessage = message;
15: msg = new XML(newMessage);
16: if (msg.namespace('') != undefined) { default xml namespace = msg.namespace(''); } else { default xml namespace = ''; }
17: function filterRule1() {
18: if (messageObject.getType() == 'ADT-A01' ||
19:     messageObject.getType() == 'ADT-A02' ||
20:     messageObject.getType() == 'ADT-A03' ||
21:     messageObject.getType() == 'ADT-A04' ||
22:     messageObject.getType() == 'ADT-A05' ||
LINE NUMBER:	18
DETAILS:	TypeError: Cannot find function getType in object message 1-0 (RECEIVED).
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:149)
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:110)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:679)

It's also found that other functions availabe in the Message Funtions Reference are not supported. 

Because the the channels to receive data for our product all rely on the Message Functions, I set the priority to be Blocker. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2332
Reporter: gepingwu
Created: 2013-01-16T14:57:29.000-0800

**Comment by rbeckman-nextgen** [comment]
The MessageObject class has been replaced with ConnectorMessage. In version 2.x, the type and version were (mainly) HL7-specific fields. In 3.0, you can still access the message type and trigger with:

msg['MSH']['MSH.9']['MSH.9.1'].toString() + '-' + msg['MSH']['MSH.9']['MSH.9.2'].toString()

In 3.0 you also have the ability to use custom metadata columns, and this is how 3.0 will provide the ability to easily view/search on the HL7 type/version in the message browser. It's not currently in Beta 1, but we're also considering giving certain data types (like HL7) the ability to automatically add their own metadata columns: MIRTH-2334

Imported Comment. Original Details:
Author: narupley
Created: 2013-01-16T15:56:46.000-0800

**Comment by rbeckman-nextgen** [comment]
If messageOjbect is no longer supported, please remove its functions from Reference in a channel to avoid confusion. 

Besides, is ConnectorMessage supported by v3.0.0-beta? How can I find more info about it? Thanks!! 

Imported Comment. Original Details:
Author: gepingwu
Created: 2013-01-17T05:59:28.000-0800

**Comment by rbeckman-nextgen** [comment]
That's a good point, and is already on our roadmap for the next beta release: MIRTH-2309

You still have access to the messageObject variable, but now it's an instance of ImmutableConnectorMessage. In the meantime, you can view the API for it here: http://www.mirthcorp.com/community/fisheye/browse/~br=trunk/Mirth/trunk/donkey/src/main/java/com/mirth/connect/donkey/model/message/ImmutableConnectorMessage.java?r=6137

Imported Comment. Original Details:
Author: narupley
Created: 2013-01-17T08:54:36.000-0800

**Comment by rbeckman-nextgen** [comment]
Rest assured, old api's will be converted or supported in some form in the 3.0 GA.  The 3.0 beta is meant for creating channels from scratch to test the engine and it's new features like queuing, durability, recovery, destination chaining, etc.

Imported Comment. Original Details:
Author: jacobb
Created: 2013-01-17T14:00:09.000-0800
