### ISSUE TITLE
Files loss with FTP file reader when a file read Exception occurs 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2283]
When an exception occurs in the processFile function while reading a file, the file is removed from source directory even if not transferred. 

The ERROR directory is empty so the file should stay in the source directory but not deleted in order to retry the transfert.

Configuration :
Timeout : 10000
Passive Mode : Yes
Validate Connection : Yes
Polling Type : Interval
Polling Frequency : 30000
Delete File after read : Yes
CheckFileAge : Yes
File Age : 10000
SortFilesBy : Name
Error Move to Directory : empty

[2013-02-01 15:37:20,439] ERROR (org.mule.impl.DefaultComponentExceptionStrategy:9 5): Caught exception in Exception Strategy for: 242f50fe-22ad-42da-94e8-ec127e7a5598: org.mule.MuleException: Failed to read payload data
org.mule.MuleException: Failed to read payload data
at com.mirth.connect.connectors.file.FileMessageRecei ver.processFile(FileMessageReceiver.java:251)
at com.mirth.connect.connectors.file.FileMessageRecei ver.poll(FileMessageReceiver.java:118)
at org.mule.providers.PollingMessageReceiver.run(Poll ingMessageReceiver.java:97)
at org.mule.impl.work.WorkerContext.run(WorkerContext .java:290)
at edu.emory.mathcs.backport.java.util.concurrent.Thr eadPoolExecutor.runWorker(ThreadPoolExecutor.java: 1061)
at edu.emory.mathcs.backport.java.util.concurrent.Thr eadPoolExecutor$Worker.run(ThreadPoolExecutor.java :575)
at java.lang.Thread.run(Unknown Source)

[2013-02-01 15:37:20,299] ERROR (com.mirth.connect.connectors.file.FileMessageRece iver:250): Error reading file //source/lab/GS1H2191.hpr
null 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2346
Reporter: thierry dubreu
Created: 2013-02-02T05:30:23.000-0800

**Comment by rbeckman-nextgen** [comment]
This is because the delete operation is performed whether or not the message was successfully dispatched. Instead, the file should only be deleted if a routing error did not occur.

Imported Comment. Original Details:
Author: narupley
Created: 2013-02-04T09:37:00.000-0800

**Comment by rbeckman-nextgen** [comment]
Currently there's a bug where you can't define the error move-to directory to the same as the read directory. If that's fixed, users will be able to keep the file in the same directory.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-22T14:56:02.000-0700

**Comment by rbeckman-nextgen** [comment]
Current Ideas:

After Processing Action: <Combo box with None/Move/Delete>
Move Dir: <Text Field>
Move Name: <Text Field>
Error Reading Action: <Combo box with None/Move/Delete>
Error in Response Action: <Combo box with None/Move/Delete>
Error Dir: <Text Field>
Error Name: <Text Field>

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-22T16:34:10.000-0700

**Comment by rbeckman-nextgen** [comment]
Hi,

in the version 2, for the source code : http://www.mirthcorp.com/community/fisheye/browse/~br=trunk/Mirth/trunk/server/src/com/mirth/connect/connectors/file/FileMessageReceiver.java?r1=5841&r2=5881


                } catch (Throwable t) {
                    logger.error("Error reading file " + file.getAbsolutePath() + "\n" + t.getMessage());
                    fileProcessedException = new MuleException(new Message(Messages.FAILED_TO_READ_PAYLOAD, file.getName()));

---> Here you get a not null fileProcessedException, but just after you never test the result of this exception, so you will always delete the file 
if the destinationDir is not null

                }

                // move the file if needed
                if (destinationDir != null) {
                    deleteFile(destinationName, destinationDir, true);

                    resultOfFileMoveOperation = renameFile(file.getName(), readDir, destinationName, destinationDir);

                    if (!resultOfFileMoveOperation) {
                        throw new MuleException(new Message("file", 4, pathname(file.getName(), readDir), pathname(destinationName, destinationDir)));
                    }
                } else if (fileConnector.isAutoDelete()) {
                    // adapter.getPayloadAsBytes();

---> The file is deleted because the only test to delete a file is the "Delete File After Read" is true. event if fileProcessedException is not null

                    resultOfFileMoveOperation = deleteFile(file.getName(), readDir, false);

                    if (!resultOfFileMoveOperation) {
                        throw new MuleException(new Message("file", 3, pathname(file.getName(), readDir)));
                    }
                }


Imported Comment. Original Details:
Author: thierry dubreu
Created: 2013-03-24T14:06:27.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed along with MIRTH-2445. Now users have the options to move/delete the file if it was successfully processed, if it failed to be processed, or if an ERROR response status was returned.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-29T17:04:55.000-0700

**Comment by rbeckman-nextgen** [comment]
Tested reading in a large file with a FTP Reader that triggers a file read exception. Set Error Reading Action to Move and Error Move-to Directory to a local folder. When file read exception occurred, file was moved to my specified directory as expected.

Imported Comment. Original Details:
Author: matts
Created: 2013-04-04T10:00:51.000-0700
