### ISSUE TITLE
Changing the destination connector type causes queue items to be stuck if regenerate template is disabled

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2301]
Destination connector properties are based on the connector type. By changing the type, the properties will be cast to the wrong properties object. Example below.

java.lang.ClassCastException: com.mirth.connect.connectors.tcp.TcpDispatcherProperties cannot be cast to com.mirth.connect.connectors.vm.VmDispatcherProperties
	at com.mirth.connect.connectors.vm.VmDispatcher.send(VmDispatcher.java:77)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:410)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.run(DestinationConnector.java:313)
	at java.lang.Thread.run(Unknown Source)

One possible solution may be to force template regeneration if this exception is detected.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2365
Reporter: wayneh
Created: 2013-02-22T12:45:40.000-0800

**Comment by rbeckman-nextgen** [comment]
Mark the message as ERRORED (removing it from the queue).

Imported Comment. Original Details:
Author: jacobb
Created: 2013-05-15T12:38:46.000-0700

**Comment by rbeckman-nextgen** [comment]
If the destination connector type is changed, all messages that were queued before the change will now error. 

Imported Comment. Original Details:
Author: wayneh
Created: 2013-05-16T15:10:44.000-0700

**Comment by rbeckman-nextgen** [comment]
The sent content should be created and stored before the message is placed in the queue. Otherwise, it's possible to send a previously queued message using completely different connector properties.

Imported Comment. Original Details:
Author: narupley
Created: 2013-06-26T16:25:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 6552: Fixed bug that caused only the first message in the queue to have its sent properties generated and stored. Before, subsequent messages in the queue did not have sent content stored, so it was possible to send a previously queued message using the **new** connector properties. Now since the sent data is always being stored beforehand that won't happen.

Imported Comment. Original Details:
Author: narupley
Created: 2013-06-26T16:41:50.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that queued messages are errored out if the connector type is changed. This happens even if the queued message was never attempted to be sent in the first place, because the sent content is being stored before placing the message in the queue.

Imported Comment. Original Details:
Author: narupley
Created: 2013-06-26T17:11:04.000-0700
