### ISSUE TITLE
ConcurrentModifictionException when undeploying channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2335]
Got the below exception when trying to undeploy a channel using the Administrator. The channel disappeared form the dashboard and could not be deployed without a MC restart.

ERROR 2013-03-13 15:23:52,159 [RMI TCP Connection(13)-158.147.146.31] com.mirth.connect.connectors.mllp.MllpConnector: Could not stop queue thread
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at com.mirth.connect.connectors.mllp.MllpMessageDispatcher.doDispose(MllpMessageDispatcher.java:490)
	at org.mule.providers.QueueEnabledConnector.stopQueueThread(QueueEnabledConnector.java:83)
	at org.mule.providers.QueueEnabledConnector.stopDispatchers(QueueEnabledConnector.java:108)
	at org.mule.impl.model.AbstractModel.stopDispatchers(AbstractModel.java:453)
	at org.mule.impl.model.AbstractModel.stopComponent(AbstractModel.java:479)
	at org.mule.management.mbeans.ModelService.stopComponent(ModelService.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(Unknown Source)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
INFO  2013-03-13 15:23:52,159 [RMI TCP Connection(13)-158.147.146.31] org.mule.impl.model.seda.SedaModel: mule 453756c7-d467-4caf-99ce-3820849e3052 has been stopped successfully
ERROR 2013-03-13 15:23:52,159 [qtp655346340-30] com.mirth.connect.connectors.mllp.MllpConnector: Could not stop queue thread
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at com.mirth.connect.connectors.mllp.MllpMessageDispatcher.doDispose(MllpMessageDispatcher.java:490)
	at org.mule.providers.QueueEnabledConnector.stopQueueThread(QueueEnabledConnector.java:83)
	at org.mule.providers.QueueEnabledConnector.stopDispatchers(QueueEnabledConnector.java:108)
	at org.mule.impl.model.AbstractModel.stopDispatchers(AbstractModel.java:453)
	at org.mule.impl.model.AbstractModel.unregisterComponent(AbstractModel.java:218)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterChannel(MuleEngineController.java:831)
	at com.mirth.connect.server.controllers.MuleEngineController.undeployChannels(MuleEngineController.java:315)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:197)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:63)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Unknown Source)
INFO  2013-03-13 15:23:52,175 [qtp655346340-30] org.mule.impl.model.seda.SedaModel: The component: 453756c7-d467-4caf-99ce-3820849e3052 has been unregistered and disposing
INFO  2013-03-13 15:23:52,175 [qtp655346340-30] com.mirth.connect.connectors.vm.VMConnector: Disposing Connector: com.mirth.connect.connectors.vm.VMConnector
INFO  2013-03-13 15:23:52,175 [qtp655346340-30] com.mirth.connect.connectors.vm.VMConnector: Connector com.mirth.connect.connectors.vm.VMConnector has been disposed.
INFO  2013-03-13 15:23:52,175 [qtp655346340-30] com.mirth.connect.connectors.mllp.MllpConnector: Disposing Connector: com.mirth.connect.connectors.mllp.MllpConnector
ERROR 2013-03-13 15:23:52,175 [qtp655346340-30] com.mirth.connect.server.controllers.MuleEngineController: Error undeploying channels.
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at com.mirth.connect.connectors.mllp.MllpMessageDispatcher.doDispose(MllpMessageDispatcher.java:490)
	at org.mule.providers.AbstractMessageDispatcher.dispose(AbstractMessageDispatcher.java:222)
	at org.mule.providers.AbstractConnector.disposeDispatchers(AbstractConnector.java:365)
	at org.mule.providers.AbstractConnector.dispose(AbstractConnector.java:329)
	at org.mule.MuleManager.unregisterConnector(MuleManager.java:508)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterConnectors(MuleEngineController.java:862)
	at com.mirth.connect.server.controllers.MuleEngineController.unregisterChannel(MuleEngineController.java:838)
	at com.mirth.connect.server.controllers.MuleEngineController.undeployChannels(MuleEngineController.java:315)
	at com.mirth.connect.server.controllers.MuleEngineController.deployChannels(MuleEngineController.java:197)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:63)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:547)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:941)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:409)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:875)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:47)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.content(HttpConnection.java:936)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:801)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:224)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:51)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:586)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:44)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2399
Reporter: dgtombs
Created: 2013-03-13T12:29:00.000-0700

**Comment by rbeckman-nextgen** [comment]
I can also reproduce the issue by stopping the channel. It does not happen every time.

ERROR 2013-03-13 15:50:53,876 [RMI TCP Connection(15)-158.147.146.31] com.mirth.connect.connectors.mllp.MllpConnector: Could not stop queue thread
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at com.mirth.connect.connectors.mllp.MllpMessageDispatcher.doDispose(MllpMessageDispatcher.java:490)
	at org.mule.providers.QueueEnabledConnector.stopQueueThread(QueueEnabledConnector.java:83)
	at org.mule.providers.QueueEnabledConnector.stopDispatchers(QueueEnabledConnector.java:108)
	at org.mule.impl.model.AbstractModel.stopDispatchers(AbstractModel.java:453)
	at org.mule.impl.model.AbstractModel.stopComponent(AbstractModel.java:479)
	at org.mule.management.mbeans.ModelService.stopComponent(ModelService.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source)
	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(Unknown Source)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(Unknown Source)
	at com.sun.jmx.mbeanserver.PerInterface.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.MBeanSupport.invoke(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.rmi.server.UnicastServerRef.dispatch(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at sun.rmi.transport.Transport$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(Unknown Source)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
INFO  2013-03-13 15:50:53,876 [RMI TCP Connection(15)-158.147.146.31] org.mule.impl.model.seda.SedaModel: mule 453756c7-d467-4caf-99ce-3820849e3052 has been stopped successfully

Imported Comment. Original Details:
Author: dgtombs
Created: 2013-03-13T12:52:52.000-0700

**Comment by rbeckman-nextgen** [comment]
The issue looks to be happening because doDispose is removing a socket from a collection while also iterating through it, so that can be fixed. It won't apply to 3.0 though since the TCP dispatcher works differently, and doesn't use the Mule ModelService. Can you attach the channel(s) you're using?

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-13T12:56:19.000-0700

**Comment by rbeckman-nextgen** [comment]
I was able to reproduce this by using a bunch of channels sending via LLP to a single unsynchronized channel, which in turn uses an LLP Sender to dispatch to somewhere else. The key is emulating the race condition where at least two client sockets haven't yet been disposed by the time stopComponent or unregisterComponent is called from Mule.

I'll attach a patch for 2.2.1, and the issue is no longer applicable in 3.0.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-13T13:15:18.000-0700

**Comment by rbeckman-nextgen** [comment]
Cool! Thanks for the quick fix.

Imported Comment. Original Details:
Author: dgtombs
Created: 2013-03-13T13:23:13.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed as of revision 6190.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-13T13:33:08.000-0700

**Comment by rbeckman-nextgen** [comment]
So if I understand your comment correctly, this issue will only appear when the LLP Sender has open socket connections? So as long as it hasn't sent any messages for a while it should be OK?

Imported Comment. Original Details:
Author: dgtombs
Created: 2013-03-19T08:44:15.000-0700

**Comment by rbeckman-nextgen** [comment]
Generally yes, though if Keep Connection Open is enabled on the connector then open sockets may still exist even if no messages have been sent for a while (MIRTH-2260).

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-19T08:48:40.000-0700

**Comment by rbeckman-nextgen** [comment]
OK, thanks. (I like your Commander Keen avatar, by the way!)

Imported Comment. Original Details:
Author: dgtombs
Created: 2013-03-19T09:26:18.000-0700

**Comment by rbeckman-nextgen** [comment]
If only JIRA had a way to "+1" your comment.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-19T09:29:55.000-0700
