### ISSUE TITLE
Re-deploying a channel whilst it is reprocessing a batch of messages results in many errors

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2337]
[2013-03-17 10:31:50,895]  ERROR (com.mirth.connect.server.controllers.DonkeyMessageController:403): com.mirth.connect.donkey.server.channel.ChannelException

ERROR 2013-03-17 10:31:49,851 [Thread-9403] com.mirth.connect.server.controllers.DonkeyEngineController: Could not find channel to route to for channel id: c1f9405b-fe5b-43d8-acd0-9487ba9a9693

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2401
Reporter: seaston
Created: 2013-03-17T03:43:34.000-0700

**Comment by rbeckman-nextgen** [comment]
This is expected in some sense; if a channel is paused, stopped, or undeployed, then the reprocessing task can no longer dispatch messages to the channel. One thing to note here is that if the channel was undeployed, then the "Could not find channel" DEC exception shows up in the server log (along with the currently somewhat useless DMC log entry). However, if the channel was paused or stopped, then **only** the DMC "com.mirth.connect.donkey.server.channel.ChannelException" entry shows in the log, without any reason.

Essentially this comes down to better exception handling for reprocess tasks. Instead of logging out 1-2 exceptions for -every- message in a reprocess task, one thing we can do is keep track (in DMC.reprocessMessages) of how many messages failed and the last cause, and log a single entry at the end. Then in DEC and SourceConnector, we can throw more meaningful exceptions, indicating that either the source connector has been stopped, or that the channel has been undeployed altogether. That way if the channel is undeployed for example, instead of hundreds of log entry suddenly showing up, you would see something like:

[2013-03-17 09:32:06,231]  ERROR (com.mirth.connect.server.controllers.DonkeyMessageController:458): 155 out of 161 messages failed to be reprocessed.
com.mirth.connect.donkey.server.channel.ChannelException: Could not find channel to route to for channel id: ae30ab60-9315-468f-920b-d000cfd796fe
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:379)
	at com.mirth.connect.server.controllers.DonkeyMessageController.reprocessMessages(DonkeyMessageController.java:450)
	at com.mirth.connect.server.servlets.MessageObjectServlet$1.run(MessageObjectServlet.java:176)
	at java.lang.Thread.run(Unknown Source)

Or if the channel was paused/stopped:

[2013-03-17 09:31:39,513]  ERROR (com.mirth.connect.server.controllers.DonkeyMessageController:458): 153 out of 157 messages failed to be reprocessed.
com.mirth.connect.donkey.server.channel.ChannelException: Source connector is currently stopped.
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:117)
	at com.mirth.connect.connectors.vm.VmReceiver.dispatchRawMessage(VmReceiver.java:54)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:387)
	at com.mirth.connect.server.controllers.DonkeyMessageController.reprocessMessages(DonkeyMessageController.java:450)
	at com.mirth.connect.server.servlets.MessageObjectServlet$1.run(MessageObjectServlet.java:176)
	at java.lang.Thread.run(Unknown Source)

I'll attach a patch with my suggestions, and review it with the team on Monday.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-17T09:45:44.000-0700

**Comment by rbeckman-nextgen** [comment]
I'd like to comment that this does not only happen when reprocessing messages.  If you have a channel set up with channel sender destination, then undeploy the channel you are sending to, you get the same multiple errors for each message subsequently processed, even if the sending channel writter is set to 'Attempt first' before queueing.  Should it not just queue whilst the destination channel is in an undeployed state?
Simon

Imported Comment. Original Details:
Author: seaston
Created: 2013-03-17T12:53:07.000-0700

**Comment by rbeckman-nextgen** [comment]
Regarding the Channel Writer: If you have your queue enabled (Attempt First or Always) and the downstream channel isn't deployed and started, then it -will- queue on the destination connector until it is able to send it. It will also output entries to the server log for every dispatch attempt, which is what you're seeing (the message should still be queued though). With the changes outlined in my previous comment, those server log errors would go away and the message would just be queued; you would then be able to go into the message browser and view the Errors tab to see why it was queued.

Let us know if you're experiencing something different or if I've misunderstood you, but as far as I can tell on my side, a Channel Writer with queuing enabled will continue to queue even if the channel in question is paused/stopped/undeployed.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-17T15:31:00.000-0700

**Comment by rbeckman-nextgen** [comment]
Nick, Yes, Perhaps my comment was not as clear as it could have been.  The messages are still queued when the receiving channel is undeployed, but you get a  "Could not find channel to route to for channel id: 93ad0e4e-73ab-4357-b69d-afa92dee728a" type message in the server log for each message processed.  Your code suggestion should fix that hopefully :-)


Imported Comment. Original Details:
Author: seaston
Created: 2013-03-18T02:46:04.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 6197: Added logging to SourceConnector and removed logging from DonkeyMessageController (reprocessMessages) and JavaScriptReceiver, so that routing errors aren't logged twice, and the server log entry displays relevant information if the channel is paused/stopped/undeployed.

We decided that logging an entry per failed message in a reprocess task is the intended behaviour, and that Channel Writers should cause log entries to display for each queue attempt. When MIRTH-2388 is implemented, it will provide users a way to view currently running tasks (like message reprocessing) and halt them if need be.

Imported Comment. Original Details:
Author: narupley
Created: 2013-03-18T12:30:46.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified one entry is logged per failed message in a reprocess task and the server log entries display relevant info if the channel is paused/stopped/undeployed. IE> "...Source connector is currently stopped. Channel Id:..."

Imported Comment. Original Details:
Author: matts
Created: 2013-04-01T15:34:44.000-0700
