### ISSUE TITLE
Add batch support to all data types

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2416]
Batch support shouldn't be limited to only Delimited Text and HL7, and only the File Reader / LLP Listener. The enabling / disabling of batching would probably make more sense as a general data type batch property, rather than having to enable it on both the data type and the source connector settings. This would be useful for almost all data types (except maybe DICOM?). All of them should always include a batch script at least, though really Raw and DICOM may be the only ones that -only- have a batch script... all the other data types would probably have some other useful batch options specific to their own protocols.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2480
Reporter: narupley
Created: 2013-04-04T08:23:34.000-0700

**Comment by rbeckman-nextgen** [comment]
Batch scripting has been added to all data types except for DICOM. An additional option has been added to the batch properties to select which method is being used to split the batch. 

The XML data type has multiple batch splitting options in additional the JavaScript: element name, level, and custom XPath query.

Additional data type specific batching may be added for EDI and NCPDP in the future.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-07-29T09:16:17.000-0700

**Comment by rbeckman-nextgen** [comment]
The default value for XML "split by level" should be 1 instead of 0 right? And should 0 even be allowed? For XML it would essentially be the same as if batching was disabled altogether.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-03T15:35:37.000-0700

**Comment by rbeckman-nextgen** [comment]
I think 0 works like this. You would get two messages for the following. Do you think this should be disallowed or work at 1?

`
<root>
    <child>
    </child>
</root>
<root>
    <child>
    </child>
</root>
`

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-03T15:46:23.000-0700

**Comment by rbeckman-nextgen** [comment]
That's an invalid XML message though. Just to confirm I tried it, and the batch adaptor was having none of it:
\\
\\
`Channel Writer error
ERROR MESSAGE: Error routing message to channel id: f3e624e4-2126-4e18-883b-d53e53c28947
com.mirth.connect.donkey.server.message.batch.BatchMessageException: Failed to retrieve batch message at sequence number 1
	at com.mirth.connect.donkey.server.message.batch.BatchAdaptor.getMessage(BatchAdaptor.java:52)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchBatchMessage(SourceConnector.java:230)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:501)
	at com.mirth.connect.connectors.vm.VmDispatcher.send(VmDispatcher.java:157)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:591)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:336)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:224)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1626)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1125)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:196)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:509)
	at com.mirth.connect.server.servlets.MessageObjectServlet$2.run(MessageObjectServlet.java:190)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.xml.xpath.XPathExpressionException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:471)
	at com.mirth.connect.plugins.datatypes.xml.XMLBatchAdaptor.getMessageFromReader(XMLBatchAdaptor.java:129)
	at com.mirth.connect.plugins.datatypes.xml.XMLBatchAdaptor.getNextMessage(XMLBatchAdaptor.java:82)
	at com.mirth.connect.donkey.server.message.batch.BatchAdaptor.getMessage(BatchAdaptor.java:35)
	... 12 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at com.sun.org.apache.xpath.internal.jaxp.XPathImpl.evaluate(XPathImpl.java:466)
	... 15 more`

We **could** still make it work for "XML" messages like that, but you would have to rework your batch adaptor code to accommodate it.

In any case I still think the default level should be 1, since that would by far be the largest use-case.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-03T15:49:21.000-0700

**Comment by rbeckman-nextgen** [comment]
If it's not legal then we won't bother (for now). Regarding whether 0 should be allowed then, where it will be the same as having no batch adaptor, I'm fine either way. Not sure if there's ever any reason to leave batch on but not want to do anything. If you're sure 0 is useless then feel free to validate against it and change the default.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-03T16:03:07.000-0700

**Comment by rbeckman-nextgen** [comment]
Updated the default value for the XML batch "level" property to 1. I think for now it's probably best to just allow 0 as well, since technically users can also effectively cause "no-ops" with the other settings, like if they choose an element name that happens to be the root node name, or if they selected the root node ("/") with an XPath query.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-03T16:11:05.000-0700

**Comment by rbeckman-nextgen** [comment]
If an XPath query doesn't match any nodes, then null is returned from the XML batch adaptor and it causes a NullPointerException later on:
\\
\\
`Channel Writer error
ERROR MESSAGE: Error routing message to channel id: f3e624e4-2126-4e18-883b-d53e53c28947
java.lang.NullPointerException
	at com.mirth.connect.connectors.vm.VmDispatcher.send(VmDispatcher.java:159)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:591)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:336)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:224)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1626)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1125)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:196)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:509)
	at com.mirth.connect.server.servlets.MessageObjectServlet$2.run(MessageObjectServlet.java:190)
	at java.lang.Thread.run(Thread.java:680)`

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-04T07:40:12.000-0700

**Comment by rbeckman-nextgen** [comment]
What should happen in this case, just send the whole message?

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-04T10:30:18.000-0700

**Comment by rbeckman-nextgen** [comment]
From the Channel Writer perspective, shouldn't it be as if it successfully dispatched the message but didn't get a response? Like if you send a message but the channel uses None for the response, the Channel Writer still shows "SENT: successfully dispatched to...". It's still true here, the message was successfully dispatched, it's just that the downstream channel decided not to do anything with it (which the upstream channel has no control over).

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-04T11:30:54.000-0700

**Comment by rbeckman-nextgen** [comment]
Another bug with this:

The current migration code causes all channels from 2.x or earlier to break. The batch properties element created is given a version attribute, and getting the value from the current attribute value. But if that channel is being migrated from 2.x, the version attribute will not yet exist. There's no need to set the attribute anyway since the migration controller is going to re-serialize the model and update the database, and at that point the migratable converter is going to add the attribute for us.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-05T11:26:32.000-0700

**Comment by rbeckman-nextgen** [comment]
> If an XPath query doesn't match any nodes, then null is returned from the XML batch adaptor and it causes a NullPointerException later on: 


Looks like this is a more general issue than just for XML. The batch adaptor is supposed to return null to indicate there are no messages left in the batch. This is the correct behavior. When the batch is complete the first or last DispatchResult is returned based off of the source connector settings. However if there were zero messages in the batch the returned DispatchResult will be null. We have never checked whether DispatchResult is null because it was not previously possible. This begs the question of what should be returned if no messages are in the batch. Or we could just throw an exception to indicate there were no messages in the batch.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-07T17:07:00.000-0700

**Comment by rbeckman-nextgen** [comment]
> The current migration code causes all channels from 2.x or earlier to break. The batch properties element created is given a version attribute, and getting the value from the current attribute value. But if that channel is being migrated from 2.x, the version attribute will not yet exist. There's no need to set the attribute anyway since the migration controller is going to re-serialize the model and update the database, and at that point the migratable converter is going to add the attribute for us.


Agreed and fixed.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-07T18:26:40.000-0700

**Comment by rbeckman-nextgen** [comment]
> Looks like this is a more general issue than just for XML. The batch adaptor is supposed to return null to indicate there are no messages left in the batch. This is the correct behavior. When the batch is complete the first or last DispatchResult is returned based off of the source connector settings. However if there were zero messages in the batch the returned DispatchResult will be null. We have never checked whether DispatchResult is null because it was not previously possible. This begs the question of what should be returned if no messages are in the batch. Or we could just throw an exception to indicate there were no messages in the batch.

\\
Well, one solution is to _start_ checking for null in everything that calls dispatchRawMessage or dispatchBatchMessage. Seems like it's "correct" for null to be returned if nothing was actually dispatched, so it should be up to the caller to handle null values as a "no messages were dispatched" signal. I don't think it should be an exception because nothing is really "incorrect". A channel may be receiving a bunch of XML messages with varying structure, and a particular XPath query may find matches in some messages but not others, and that may be exactly what the user wants to do.
\\
\\
\\
Another solution is to have the batch code return a dummy DispatchResult by default if nothing is actually dispatched. For example consider the following:

`--- SourceConnector.java	(revision 7335)
+++ SourceConnector.java	(working copy)
@@ -216,1 +216,2 @@
+        responseHandler.setDispatchResult(new DispatchResult(0, null, null, false, false));
 `
\\
I prefer the first solution but obviously it's more work.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-08T08:21:13.000-0700

**Comment by rbeckman-nextgen** [comment]
Now checking for null wherever a batch DispatchResult could potentially be used. Currently it is only used in HTTP, TCP, Web Service receivers, as well as the VmDispatcher and VMRouter. 

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-08T13:55:02.000-0700

**Comment by rbeckman-nextgen** [comment]
In Channel, we are now putting values (destination set, batch Id) directly into the source map that is retrieved from the RawMessage. This map could be an unmodifiable or singleton map which causes the put to fail. Therefore we should always create a new map and the values from the RawMessage source map.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-16T12:44:49.000-0700

**Comment by rbeckman-nextgen** [comment]
Since the source map that's passed into a raw message can be unmodifiable/singleton itself, it could fail to add the destination set (or batch Id). Therefore we always need to create a new source map in the channel and add all the values from the RawMessage's source map.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-16T13:14:08.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that batch support works for all data types and all the issues brought up here have been resolved.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-19T07:36:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Just kidding... looks like a call to set the -encryptor- batch properties in the EDI batch adaptor factory was missed.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-19T15:55:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Do people really want batch support for EDI?

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-19T16:05:27.000-0700

**Comment by rbeckman-nextgen** [comment]
Yes, my state is waiting on this. I hope you are not stopping work on it.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-19T16:09:35.000-0700
