### ISSUE TITLE
Concurrent Modification Exception while processing incoming LLP (moderate load)

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#243]
Exception occurred while processing several messages at the same time - only happened once out of 50+K messages over the last week or so.

Error writing to the database
java.util.ConcurrentModificationException
    at java.util.HashMap$Ha:censored:erator.nextEntry(HashMap.java:787)
    at java.util.HashMap$EntryIterator.next(HashMap.java:829)
    at java.util.HashMap$EntryIterator.next(HashMap.java:827)
    at org.mule.providers.TemplateValueReplacer.loadContext(TemplateValueReplacer.java:55)
    at org.mule.providers.TemplateValueReplacer.replaceValues(TemplateValueReplacer.java:29)
    at org.mule.providers.jdbc.JdbcUtils.getParams(JdbcUtils.java:106)
    at org.mule.providers.jdbc.JdbcMessageDispatcher.doDispatch(JdbcMessageDispatcher.java:113)
    at org.mule.providers.AbstractMessageDispatcher$Worker.run(AbstractMessageDispatcher.java:257)
    at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
    at java.lang.Thread.run(Thread.java:595)

Quote from Chris:  Ah very interesting...it appears that values are being modified in a hash-map while Mirth is trying to iterate through it. This points to an area where we need to synchronize the threads. Can you add this to the JIRA? I'll try to get a fix for this in 1.3.2 (coming withing a week).

Additional info available if needed - I haven't deleted anything from the PGSQL DB.

thanks - mike

Imported Issue. Original Details:
Jira Issue Key: MIRTH-224
Reporter: mnowlin
Created: 2006-12-30T21:35:51.000-0800

**Comment by rbeckman-nextgen** [comment]
Synchronized map modification

Imported Comment. Original Details:
Author: chrisl
Created: 2007-01-02T15:25:20.000-0800

**Comment by rbeckman-nextgen** [comment]
Reopened for fix in 1.3.3

Imported Comment. Original Details:
Author: chrisl
Created: 2007-01-10T10:37:37.000-0800
