### ISSUE TITLE
webadmin in 3.0 can't login in a mapped local ip.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2478]
I have mapped a local ip to a wan ip+port, for example, localhost 192.168.1.100:10000 to a wan ip(118.122.165.33) :100000
I can do login with administrator (GUI), but can't do with webadmin: error :

I added debug info:  ===https://118.122.165.33:10013

ERROR 2013-05-06 21:23:01,861 [qtp180831905-202] Server: com.mirth.connect.client.core.ClientException: java.net.ConnectException: Connection refused
ERROR 2013-05-06 21:23:01,862 [qtp180831905-202] Server:        at com.mirth.connect.client.core.ServerConnection.executePostMethod(Unknown Source)
ERROR 2013-05-06 21:23:01,862 [qtp180831905-202] Server:        at com.mirth.connect.client.core.Client.login(Unknown Source)
ERROR 2013-05-06 21:23:01,862 [qtp180831905-202] Server:        at com.mirth.connect.webadmin.action.LoginActionBean.login(LoginActionBean.java:39)
ERROR 2013-05-06 21:23:01,863 [qtp180831905-202] Server:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
ERROR 2013-05-06 21:23:01,863 [qtp180831905-202] Server:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
ERROR 2013-05-06 21:23:01,864 [qtp180831905-202] Server:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
ERROR 2013-05-06 21:23:01,864 [qtp180831905-202] Server:        at java.lang.reflect.Method.invoke(Method.java:601)
ERROR 2013-05-06 21:23:01,865 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
ERROR 2013-05-06 21:23:01,865 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
ERROR 2013-05-06 21:23:01,865 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
ERROR 2013-05-06 21:23:01,866 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
ERROR 2013-05-06 21:23:01,866 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
ERROR 2013-05-06 21:23:01,867 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
ERROR 2013-05-06 21:23:01,867 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
ERROR 2013-05-06 21:23:01,868 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
ERROR 2013-05-06 21:23:01,868 [qtp180831905-202] Server:        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
ERROR 2013-05-06 21:23:01,869 [qtp180831905-202] Server:        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
ERROR 2013-05-06 21:23:01,869 [qtp180831905-202] Server:        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1329)
ERROR 2013-05-06 21:23:01,869 [qtp180831905-202] Server:        at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
ERROR 2013-05-06 21:23:01,870 [qtp180831905-202] Server:        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1300)
ERROR 2013-05-06 21:23:01,870 [qtp180831905-202] Server:        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)
ERROR 2013-05-06 21:23:01,871 [qtp180831905-202] Server:        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
ERROR 2013-05-06 21:23:01,871 [qtp180831905-202] Server:        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:559)
ERROR 2013-05-06 21:23:01,872 [qtp180831905-202] Server:        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
ERROR 2013-05-06 21:23:01,872 [qtp180831905-202] Server:        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
ERROR 2013-05-06 21:23:01,872 [qtp180831905-202] Server:        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
ERROR 2013-05-06 21:23:01,873 [qtp180831905-202] Server:        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
ERROR 2013-05-06 21:23:01,873 [qtp180831905-202] Server:        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
ERROR 2013-05-06 21:23:01,874 [qtp180831905-202] Server:        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
ERROR 2013-05-06 21:23:01,874 [qtp180831905-202] Server:        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
ERROR 2013-05-06 21:23:01,875 [qtp180831905-202] Server:        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
ERROR 2013-05-06 21:23:01,875 [qtp180831905-202] Server:        at org.eclipse.jetty.server.Server.handle(Server.java:363)
ERROR 2013-05-06 21:23:01,876 [qtp180831905-202] Server:        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
ERROR 2013-05-06 21:23:01,876 [qtp180831905-202] Server:        at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
ERROR 2013-05-06 21:23:01,876 [qtp180831905-202] Server:        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
ERROR 2013-05-06 21:23:01,876 [qtp180831905-202] Server:        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
ERROR 2013-05-06 21:23:01,877 [qtp180831905-202] Server:        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
ERROR 2013-05-06 21:23:01,877 [qtp180831905-202] Server:        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
ERROR 2013-05-06 21:23:01,877 [qtp180831905-202] Server:        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
ERROR 2013-05-06 21:23:01,878 [qtp180831905-202] Server:        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
ERROR 2013-05-06 21:23:01,878 [qtp180831905-202] Server:        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
ERROR 2013-05-06 21:23:01,878 [qtp180831905-202] Server:        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
ERROR 2013-05-06 21:23:01,878 [qtp180831905-202] Server:        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
ERROR 2013-05-06 21:23:01,879 [qtp180831905-202] Server:        at java.lang.Thread.run(Thread.java:722)
ERROR 2013-05-06 21:23:01,879 [qtp180831905-202] Server: Caused by: java.net.ConnectException: Connection refused
ERROR 2013-05-06 21:23:01,880 [qtp180831905-202] Server:        at java.net.PlainSocketImpl.socketConnect(Native Method)
ERROR 2013-05-06 21:23:01,880 [qtp180831905-202] Server:        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
ERROR 2013-05-06 21:23:01,880 [qtp180831905-202] Server:        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
ERROR 2013-05-06 21:23:01,880 [qtp180831905-202] Server:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
ERROR 2013-05-06 21:23:01,881 [qtp180831905-202] Server:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:391)
ERROR 2013-05-06 21:23:01,881 [qtp180831905-202] Server:        at java.net.Socket.connect(Socket.java:579)
ERROR 2013-05-06 21:23:01,881 [qtp180831905-202] Server:        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:612)
ERROR 2013-05-06 21:23:01,882 [qtp180831905-202] Server:        at org.apache.commons.ssl.Java14.connectSocket(Java14.java:190)
ERROR 2013-05-06 21:23:01,882 [qtp180831905-202] Server:        at org.apache.commons.ssl.Java14.buildSocket(Java14.java:153)
ERROR 2013-05-06 21:23:01,882 [qtp180831905-202] Server:        at org.apache.commons.ssl.JavaImpl.createSocket(JavaImpl.java:206)
ERROR 2013-05-06 21:23:01,882 [qtp180831905-202] Server:        at org.apache.commons.ssl.SSL.createSocket(SSL.java:543)
ERROR 2013-05-06 21:23:01,883 [qtp180831905-202] Server:        at org.apache.commons.ssl.SSLClient.createSocket(SSLClient.java:221)
ERROR 2013-05-06 21:23:01,883 [qtp180831905-202] Server:        at org.apache.commons.ssl.HttpSecureProtocol.createSocket(HttpSecureProtocol.java:90)
ERROR 2013-05-06 21:23:01,883 [qtp180831905-202] Server:        at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:706)
ERROR 2013-05-06 21:23:01,884 [qtp180831905-202] Server:        at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1321)
ERROR 2013-05-06 21:23:01,884 [qtp180831905-202] Server:        at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:386)
ERROR 2013-05-06 21:23:01,884 [qtp180831905-202] Server:        at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:170)
ERROR 2013-05-06 21:23:01,885 [qtp180831905-202] Server:        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:396)
ERROR 2013-05-06 21:23:01,885 [qtp180831905-202] Server:        at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:324)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2543
Reporter: lin_xd
Created: 2013-05-06T08:13:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Is this still an issue for you with 3.0.0?

Imported Comment. Original Details:
Author: jacobb
Created: 2013-10-16T13:20:01.000-0700

**Comment by rbeckman-nextgen** [comment]
I reproduced this problem by running a mirth connect server instance on the network at 10.10.14.234:8080 and then on a separate Ubuntu VM I ran this command to redirect 10.10.14.234:8080 to localhost:8081

redir --lport 8081 --laddr=localhost --cport 8080 --caddr 10.10.14.234

Accessing the WebAdmin via localhost:8081 resulted in a failed login even with valid credentials. The problem is that WebAdmin was grabbing the server's address from the request url (localhost:8081), which is only accessible on the Ubuntu machine.

It's now fixed so that it looks up the server's address from mirth.properties instead of the request url.

Imported Comment. Original Details:
Author: brentm
Created: 2013-11-04T16:43:39.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified this now works. Tested by redirecting both the HTTP and HTTPS addresses, and also tested redirecting using the same port as well as different ports.

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-13T11:10:23.000-0800
