### ISSUE TITLE
High concurrency causes JavaScript type errors

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2483]
ERROR-300: Transformer error
ERROR MESSAGE: Error evaluating filter/transformer
com.mirth.connect.server.MirthJavascriptTransformerException: 
CHANNEL:	Channel 0
CONNECTOR:	sourceConnector
SCRIPT SOURCE:	
SOURCE CODE:	
392: }
393: 
394: function getXV(SegmentRoot, newSegmentPath)
395: {
396:     var segment = smartCreateSegmentXML(SegmentRoot, newSegmentPath);
397:     return segment.parent()[segment.name()];
398: }
399: 
400: function deleteXV(SegmentRoot, newSegmentPath)
401: {
LINE NUMBER:	397
DETAILS:	TypeError: name is not a function, it is xml.
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:397 (getXV)
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:687
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:676
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:2177
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:2164
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:2823 (doTransform)
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:2826 (doScript)
	at 7f032f12-ffd8-44bc-b7ab-6923a4c260f5:2828
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:127)
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:680)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2549
Reporter: adriang
Created: 2013-05-10T08:30:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Steps to reproduce in 2.2.1 (same steps for 3.0 but with a 3.0 channel)

Import code templates
Import global script
Clone Channel_0 100x
Read in sample.xml

Imported Comment. Original Details:
Author: adriang
Created: 2013-05-10T08:39:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Required files will be uploaded once we are given permission to do so by the client

Imported Comment. Original Details:
Author: adriang
Created: 2013-05-10T09:04:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Required files have been uploaded

Imported Comment. Original Details:
Author: adriang
Created: 2013-05-15T14:56:32.000-0700

**Comment by rbeckman-nextgen** [comment]
Test to see if this is still an issue in 3.0.0.


Imported Comment. Original Details:
Author: jacobb
Created: 2013-11-04T13:44:17.000-0800

**Comment by rbeckman-nextgen** [comment]
When we last tested this, it was indeed an issue with 2.x and 3.0 (at the time it was a build somewhere between Beta 2 and RC 1). Will test again though.

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-04T13:51:46.000-0800

**Comment by rbeckman-nextgen** [comment]
Confirmed that this is still happening in 3.0 GA. Still don't know how to fix it though, as it appears to be a threading issue in Rhino.

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-04T16:31:08.000-0800
