### ISSUE TITLE
Cloning a destination connector causes a NullPointerException when deploying a channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2516]
Steps to reproduce:

1. Create a simple Channel Reader/Writer channel, save it, but do not deploy it.
2. Close down and restart the Administrator client.
3. Go to the Channels view, double-click the channel you created.
4. Click on the Destinations tab.
5. Click the Clone Destination task, and then click Save Changes.
6. Return to the Channels view and deploy the channel.
7. The channel will fail to deploy, with the following exception:

[2013-05-24 11:06:21,166]  ERROR (com.mirth.connect.server.controllers.DonkeyEngineController:177): Error deploying channel bb0d7d45-e63b-4d4c-a21f-d4c4982833f3.
com.mirth.connect.donkey.server.DeployException
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannel(DonkeyEngineController.java:198)
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannels(DonkeyEngineController.java:175)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:63)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:680)Caused by: java.lang.NullPointerException
	at com.mirth.connect.server.controllers.DonkeyEngineController.createDestinationConnector(DonkeyEngineController.java:760)
	at com.mirth.connect.server.controllers.DonkeyEngineController.convertToDonkeyChannel(DonkeyEngineController.java:485)
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannel(DonkeyEngineController.java:196)
	... 27 more

This is happening because the connector properties of the cloned destination of the Channel being passed into DEC are null.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2583
Reporter: narupley
Created: 2013-05-24T11:57:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 6403: Fixed a NullPointerException caused by cloning a destination under certain circumstances. The makeDestinationTable function causes saveDestinationPanel() to be called before the destination connector settings panel has been setup correctly, so the properties of the first destination connector in the current channel are being set to null. Then when the destination gets cloned, null gets copied over to the new destination. When the channel is saved, the first destination has its properties correctly populated from the destination connector settings panel, but the second (cloned) destination doesn't have its properties populated, so it remains null and is saved to the database that way. Finally when the channel is deployed, the NPE happens in DonkeyEngineController.

This is fixed by saving the settings of the currently selected destination connector after calling makeDestinationTable when the Edit Channel view is first entered. That way currentChannel always has the most up-to-date connector settings even after QueueSettingsPanel.setProperties runs.

Imported Comment. Original Details:
Author: narupley
Created: 2013-05-24T12:09:29.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that destination connectors can be cloned properly and can be deployed.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-06-25T11:03:22.000-0700
