### ISSUE TITLE
A segment with segment ID only with StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#253]
Errors out with following sample message. Without error with PV1|.

MSH|^~\&|REG|CH||CWHC|20061221090035||ADT^A01|10599072|P|2.2|
EVN|A01|20061221090035|||JJL
PID|||||name^name^name^^^||19780710|F|||5408 address ST^^VANCOUVER^BC^^^|||||M||||
PV1

Caused by: com.webreach.mirth.model.converters.SerializerException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at com.webreach.mirth.model.converters.HAPIMessageSerializer.deserialize(HAPIMessageSerializer.java:54)
    at com.webreach.mirth.server.mule.transformers.HL7ToMessageObject.doTransform(HL7ToMessageObject.java:80)
    ... 30 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(Unknown Source)
    at ca.uhn.hl7v2.parser.PipeParser.doParse(PipeParser.java:239)
    at ca.uhn.hl7v2.parser.Parser.parse(Parser.java:151)
    at com.webreach.mirth.model.converters.HAPIMessageSerializer.deserialize(HAPIMessageSerializer.java:52)
    ... 31 more
ERROR 2007-01-19 15:23:17,265 [6d613b7c-1924-412d-84b8-746a85d0d55d_source_connector._tcpEndpoint#1513433877.receiver.4] org.mule.impl.DefaultComponentExceptionStrategy: Caught exception in Exception Strategy for: 6d613b7c-1924-412d-84b8-746a85d0d55d: org.mule.umo.MessagingException: Failed to invoke UMO Component: 6d613b7c-1924-412d-84b8-746a85d0d55d. Message payload is of type: java.lang.String
org.mule.umo.MessagingException: Failed to invoke UMO Component: 6d613b7c-1924-412d-84b8-746a85d0d55d. Message payload is of type: java.lang.String
    at org.mule.impl.DefaultLifecycleAdapter.onCall(DefaultLifecycleAdapter.java:193)
    at org.mule.impl.DefaultLifecycleAdapter.intercept(DefaultLifecycleAdapter.java:232)
    at org.mule.impl.InterceptorsInvoker.execute(InterceptorsInvoker.java:53)
    at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:230)
    at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
    at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
    at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
    at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
    at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
    at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
    at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
    at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:243)
    at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.processData(TcpMessageReceiver.java:304)
    at org.mule.providers.tcp.TcpMessageReceiver$TcpWorker.run(TcpMessageReceiver.java:275)
    at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
    at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.mule.umo.transformer.TransformerException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1 (com.webreach.mirth.model.converters.SerializerException)
    at com.webreach.mirth.server.mule.transformers.HL7ToMessageObject.doTransform(HL7ToMessageObject.java:94)
    at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
    at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
    at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
    at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
    at org.mule.impl.MuleEventContext.getTransformedMessage(MuleEventContext.java:100)
    at com.webreach.mirth.server.mule.components.Channel.onCall(Channel.java:34)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.mule.model.DynamicEntryPoint.invokeCurrent(DynamicEntryPoint.java:168)
    at org.mule.model.DynamicEntryPoint.invoke(DynamicEntryPoint.java:90)
    at org.mule.impl.DefaultLifecycleAdapter.onCall(DefaultLifecycleAdapter.java:177)
    ... 17 more
Caused by: com.webreach.mirth.model.converters.SerializerException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at com.webreach.mirth.model.converters.HAPIMessageSerializer.deserialize(HAPIMessageSerializer.java:54)
    at com.webreach.mirth.server.mule.transformers.HL7ToMessageObject.doTransform(HL7ToMessageObject.java:80)
    ... 30 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(Unknown Source)
    at ca.uhn.hl7v2.parser.PipeParser.doParse(PipeParser.java:239)
    at ca.uhn.hl7v2.parser.Parser.parse(Parser.java:151)
    at com.webreach.mirth.model.converters.HAPIMessageSerializer.deserialize(HAPIMessageSerializer.java:52)
    ... 31 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-235
Reporter: is980491
Created: 2007-01-20T10:50:46.000-0800

**Comment by rbeckman-nextgen** [comment]
Can be parsed with non-strict parser

Imported Comment. Original Details:
Author: chrisl
Created: 2007-03-21T02:16:45.000-0700
