### ISSUE TITLE
SQL Server deadlocks when pruning messages

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2621]
I had a JavaScript Reader channel (pruning enabled) that was basically just blasting a bunch of messages. At the same time, I ran the data pruner. When I did that, both the pruner and channel processing seemed to stop for a good 15-20 seconds, after which I got this:

`[2013-06-27 18:48:45,546]  ERROR (com.mirth.connect.donkey.server.channel.Channel:961): Error processing message.
com.mirth.connect.donkey.server.channel.ChannelException: com.mirth.connect.donkey.server.data.DonkeyDaoException: java.sql.SQLException: Transaction (Process ID 56) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:920)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:130)
	at com.mirth.connect.connectors.js.JavaScriptReceiver.poll(JavaScriptReceiver.java:100)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:111)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)Caused by: com.mirth.connect.donkey.server.data.DonkeyDaoException: java.sql.SQLException: Transaction (Process ID 56) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertContent(JdbcDao.java:233)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMessageContent(JdbcDao.java:161)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:98)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:61)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:907)
	... 5 moreCaused by: java.sql.SQLException: Transaction (Process ID 56) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
	at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:372)
	at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2894)
	at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2334)
	at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:643)
	at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:614)
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:573)
	at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.executeUpdate(JtdsPreparedStatement.java:707)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertContent(JdbcDao.java:230)
	... 10 more`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2689
Reporter: narupley
Created: 2013-06-27T15:48:28.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed deadlock problems with the Data Pruner when running SQL Server.

Updated the data pruner statements for SQL Server so that it is forced to use the "pruneMessagesByIds" mode and so that it does not rely on cascade deletion. This resolves a contention issue between the pruner and message processing.

Imported Comment. Original Details:
Author: brentm
Created: 2013-07-02T13:19:48.000-0700

**Comment by rbeckman-nextgen** [comment]
It should be noted that when the pruner block size is not set (or if it is set too high), SQL Server will escalate the lock acquired by the pruner to a table lock, which will temporarily block message processing on a given channel while it is being pruned.

Imported Comment. Original Details:
Author: brentm
Created: 2013-07-02T13:26:31.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that no more deadlocks appear to be occurring for SQL Server when messages are being processed and the pruner runs.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-07-02T15:16:17.000-0700
