### ISSUE TITLE
Exception in File Reader when inbound data type is XML and batch processing enabled

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2659]
If a File Reader is configured to process batch files, and the inbound data type is set to XML, the following exception occurs upon each read:

----------------------
[2013-07-05 13:44:32,509]  ERROR (com.mirth.connect.connectors.file.FileReceiver:276): Unable to route: java.lang.Exception: Data type XML does not support batch processing.

	at com.mirth.connect.connectors.file.FileReceiver.processBatch(FileReceiver.java:395)

	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:252)

	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:181)

	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:106)

	at java.util.TimerThread.mainLoop(Timer.java:512)

	at java.util.TimerThread.run(Timer.java:462)
----------------------

If XML batch processing is not supported, the batch option should be disabled and defaulted to No if the inbound data type is set to XML.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2729
Reporter: ericb
Created: 2013-07-05T13:49:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Obviated by MIRTH-2480

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-20T14:23:27.000-0700
