### ISSUE TITLE
Add a "Paused" initial state to channels

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2730]
Imported Issue. Original Details:
Jira Issue Key: MIRTH-2802
Reporter: narupley
Created: 2013-07-24T14:50:06.000-0700

**Comment by rbeckman-nextgen** [comment]
Added in revision 6706. 

Imported Comment. Original Details:
Author: narupley
Created: 2013-07-24T17:24:07.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that channels can now be deployed with an initial state of Paused

Imported Comment. Original Details:
Author: wayneh
Created: 2013-08-01T14:23:42.000-0700

**Comment by rbeckman-nextgen** [comment]
If a TCP Listener channel is deployed in the Paused state and then stopped, a NullPointerException is thrown:
\\
\\
`[2013-08-09 15:39:52,846]  ERROR (com.mirth.connect.donkey.server.channel.Channel:688): Error stopping Source connector for channel test (b69fc216-cd4e-45ac-b5ed-836696b225a9).
com.mirth.connect.donkey.server.StopException: java.lang.NullPointerException
	at com.mirth.connect.donkey.server.channel.SourceConnector.stop(SourceConnector.java:116)
	at com.mirth.connect.donkey.server.channel.Channel.stop(Channel.java:686)
	at com.mirth.connect.donkey.server.channel.Channel.access$2500(Channel.java:80)
	at com.mirth.connect.donkey.server.channel.Channel$StopTask.call(Channel.java:1909)
	at com.mirth.connect.donkey.server.channel.Channel$StopTask.call(Channel.java:1894)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:680)Caused by: java.lang.NullPointerException
	at com.mirth.connect.connectors.tcp.TcpReceiver.onStop(TcpReceiver.java:218)
	at com.mirth.connect.donkey.server.channel.SourceConnector.stop(SourceConnector.java:96)
	... 9 more`

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-09T15:41:39.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed the above issue in r6780.

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-09T15:43:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified the TCP Listener issue when deploying the channel with initial state Paused has been fixed.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-08-12T11:20:44.000-0700
