### ISSUE TITLE
Transformer errors that occur outside of rhino are not stored.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2750]
Imported Issue. Original Details:
Jira Issue Key: MIRTH-2822
Reporter: wayneh
Created: 2013-08-02T10:59:11.000-0700

**Comment by rbeckman-nextgen** [comment]
Confirmed that exceptions happening in the task (e.g. FilterTransformerTask) but outside the actual script execution will be caught and stored as the Processing Error. Tested by throwing another Context.exit() at the end of the task and saw the following stored error:

`Filter/Transformer error
java.lang.IllegalStateException: Calling Context.exit without previous Context.enter
	at org.mozilla.javascript.Context.exit(Context.java:426)
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:147)
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:1)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:680)`

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-05T15:05:04.000-0700
