### ISSUE TITLE
Deadlock detected when removing messages for a halted channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2766]
I'll attach the channels I used. 

First channel (Sender):
* TCP Listener 
* Source queue ON
* 10 max connections
* TCP Sender
* Queue always
* 500 queue threads

Second channel (Receiver):
* TCP Listener
* Source queue ON
* 500 max connections

Deploy both channels, then start blasting messages at the first one. Stop the destination connector and let a couple thousand messages queue up. Then start the destination back up and wait a bit until the connected socket count on the second channel is near the max (500). Then stop and halt the first channel, go into the message browser, and Remove All Messages. I fairly consistently get a deadlock:

`ERROR 2013-08-07 14:58:43,041 [SwingWorker-pool-1-thread-3] com.mirth.connect.client.ui.Frame: com.mirth.connect.client.core.ClientException: method failed: HTTP/1.1 500 org.postgresql.util.PSQLException: ERROR: deadlock detected   Detail: Process 37166 waits for AccessExclusiveLock on relation 10933565 of database 10925057; blocked by process 37169. Process 37169 waits for RowShareLock on relation 10933557 of database 10925057; blocked by process 37166.   Hint: See server log for query details.
com.mirth.connect.client.core.ServerConnection.executePostMethod(ServerConnection.java:130)
com.mirth.connect.client.core.Client.clearMessages(Client.java:908)
com.mirth.connect.client.ui.RemoveMessagesDialog$3.doInBackground(RemoveMessagesDialog.java:147)
com.mirth.connect.client.ui.RemoveMessagesDialog$3.doInBackground(RemoveMessagesDialog.java:1)
javax.swing.SwingWorker$1.call(SwingWorker.java:277)
java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
java.util.concurrent.FutureTask.run(FutureTask.java:138)
javax.swing.SwingWorker.run(SwingWorker.java:316)
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
java.lang.Thread.run(Thread.java:680)`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2838
Reporter: narupley
Created: 2013-08-07T15:13:56.000-0700

**Comment by rbeckman-nextgen** [comment]
This doesn't always result in a deadlock, but instead will allow the Remove All Messages operation to execute, and then the destination queue is still trying to finish. So you get a bunch of these messages:



`[2013-08-08 09:05:11,137]  ERROR (com.mirth.connect.connectors.tcp.TcpDispatcher:504): Error processing queued message 846324-1 (SENT) for channel 2564930e-8a2f-4929-8131-61c296d7f465 (Destination 1). This error is expected if the message was manually removed from the queue.
com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: ERROR: insert or update on table "d_mc2" violates foreign key constraint "mc2_fkey"  Detail: Key (message_id, metadata_id)=(846324, 1) is not present in table "d_mm2".
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertContent(JdbcDao.java:246)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMessageContent(JdbcDao.java:174)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:98)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:61)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.run(DestinationConnector.java:492)
	at java.lang.Thread.run(Thread.java:680)Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "d_mc2" violates foreign key constraint "mc2_fkey"  Detail: Key (message_id, metadata_id)=(846324, 1) is not present in table "d_mm2".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:332)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertContent(JdbcDao.java:243)
	... 6 more`



The main issue here I think is that the channel state is getting set to STOPPED before the destination connector states are finished stopping.

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-08T09:07:06.000-0700

**Comment by rbeckman-nextgen** [comment]
This happens also when halting a channel in recovery (STARTING), but for a slightly different reason. Basically there are two issues:

1. In the _stop(List<Integer> metaDataIds)_ method, if any exception is caught stopping a connector, the channel state is updated to STOPPED. However that should happen if the exception was an InterruptedException, because that indicates that the channel is being halted.

2. In the DestinationConnector _halt()_ method, the connector state is not always set to STOPPED. If an InterruptedException occurs while joining a queue thread, a HaltException is thrown immediately.

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-08T10:29:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 6770: Fixed issue that caused the channel state to be set to STOPPED before a destination's state was set from STOPPING to STOPPED. This can lead to deadlocks when removing all messages, because the server thinks that the channel is stopped and lets the operation go through.

In the stop(metaDataIds) method, if an exception is caught somewhere while stopping the connectors, only set the channel state to STOPPED if the exception is **not** an InterruptedException. This is because if the channel was halted, that halt operation will eventually stop the channel correctly.

A similar change was made in StartTask when an error occurs. When that happens the connectors are stopped in a rollback attempt, and if an exception happens _there_, we were then calling halt directly. Instead we never call halt from the StartTask; we just let the halt operation proceed as normal (it will set the state eventually). Same thing in the StartTask, only set the channel state to STOPPED if the exception thrown is **not** an InterruptedException.

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-08T12:13:10.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that the cases described above do not seem to cause deadlocks anymore. Furthermore, even if it did deadlock when removing all messages, it probably isn't too big a deal since they were about to remove all their messages anyway.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-08-09T12:29:00.000-0700
