### ISSUE TITLE
Exporting a channel from the channel edit page no longer works

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2774]
A NullPointerException occurs in the client console:
\\
`Exception in thread "AWT-EventQueue-2" java.lang.RuntimeException: No method called doExport on class com.mirth.connect.client.ui.Frame with no arguments
	at java.beans.EventHandler.invokeInternal(EventHandler.java:477)
	at java.beans.EventHandler.access$000(EventHandler.java:278)
	at java.beans.EventHandler$1.run(EventHandler.java:429)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.beans.EventHandler.invoke(EventHandler.java:427)
	at com.sun.proxy.$Proxy10.actionPerformed(Unknown Source)
	at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at org.jdesktop.swingx.JXHyperlink.fireActionPerformed(JXHyperlink.java:264)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2846
Reporter: narupley
Created: 2013-08-09T13:01:33.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 6778: Fixed NullPointerException happening when exporting a channel from the channel edit page.

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-09T13:06:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2013-08-09T13:45:37.000-0700
