### ISSUE TITLE
ConcurrentModificationException when deploying a large amount of channels at once

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2792]
You can reproduce this by creating 100 or so channels and deploying them all at once. You'll see entries in the server log:
\\
\\
> [2013-08-15 13:29:07,068]  ERROR (com.mirth.connect.model.converters.ObjectXMLSerializer:142): java.util.ConcurrentModificationException

\\
\\
{quote}[2013-08-15 13:29:07,069]  ERROR (com.mirth.connect.server.servlets.ExtensionServlet:166): com.mirth.connect.donkey.util.xstream.SerializerException: java.util.ConcurrentModificationException

	at com.mirth.connect.model.converters.ObjectXMLSerializer.serialize(ObjectXMLSerializer.java:143)

	at com.mirth.connect.server.servlets.ExtensionServlet.doPost(ExtensionServlet.java:131)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)

	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)

	at org.eclipse.jetty.server.Server.handle(Server.java:363)

	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)

	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)

	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)

	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)

	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)

	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)

	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

	at java.lang.Thread.run(Thread.java:680)
Caused by: java.util.ConcurrentModificationException

	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:793)

	at java.util.HashMap$EntryIterator.next(HashMap.java:834)

	at java.util.HashMap$EntryIterator.next(HashMap.java:832)

	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:55)

	at com.thoughtworks.xstream.core.TreeMarshaller.convert(TreeMarshaller.java:70)

	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)

	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)

	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)

	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)

	at com.thoughtworks.xstream.XStream.marshal(XStream.java:895)

	at com.thoughtworks.xstream.XStream.marshal(XStream.java:884)

	at com.thoughtworks.xstream.XStream.toXML(XStream.java:857)

	at com.mirth.connect.model.converters.ObjectXMLSerializer.serialize(ObjectXMLSerializer.java:137)

	... 26 more{quote}
\\
\\
And in the client as well:
\\
\\
> ERROR 2013-08-15 13:29:07,071 [SwingWorker-pool-1-thread-6] com.mirth.connect.model.converters.ObjectXMLSerializer: com.mirth.connect.donkey.util.DonkeyElement$DonkeyElementException: java.io.EOFException: no more data available - expected end tag </map> to close start tag <map> from line 1, parser stopped on END_TAG seen ...</object-array>\n  </entry>... \@613:11

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2864
Reporter: narupley
Created: 2013-08-15T13:32:19.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revision 6815.

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-15T13:55:05.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2013-08-15T14:57:36.000-0700
