### ISSUE TITLE
Error exporting messages from CLI

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2803]
An exception occurs when attempting to export messages from the CLI. Possibly a build problem, because it works fine when running from eclipse.

$exportmessages messages.xml e65665ce-cc68-4cb2-ab9d-5984b789864c xml 100
Exporting messages to file: messages.xml
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
	at com.install4j.runtime.launcher.Launcher.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/jce/provider/BouncyCastleProvider
	at com.mirth.connect.model.EncryptionSettings.<clinit>(EncryptionSettings.java:29)
	at sun.reflect.GeneratedSerializationConstructorAccessor18.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at com.thoughtworks.xstream.converters.reflection.Sun14ReflectionProvider.newInstance(Sun14ReflectionProvider.java:75)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.instantiateNewInstance(AbstractReflectionConverter.java:428)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:233)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1058)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1030)
	at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:158)
	at com.mirth.connect.client.core.Client.getEncryptionSettings(Client.java:520)
	at com.mirth.connect.client.core.Client.getEncryptor(Client.java:800)
	at com.mirth.connect.cli.CommandLineInterface.commandExportMessages(CommandLineInterface.java:903)
	at com.mirth.connect.cli.CommandLineInterface.executeStatement(CommandLineInterface.java:284)
	at com.mirth.connect.cli.CommandLineInterface.runConsole(CommandLineInterface.java:213)
	at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:178)
	at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:147)
	at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:90)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 33 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2875
Reporter: brentm
Created: 2013-08-19T16:50:25.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed this error and others with exporting messages from CLI.

Imported Comment. Original Details:
Author: brentm
Created: 2013-08-21T15:35:52.000-0700
