### ISSUE TITLE
Deleting queued message causes SQL exception and message sent to destination over and over

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2818]
Here's my setup:

As my destination, I set up HL7 Inspector to listen on port 6660.
In Mirth Connect, create a channel with a Channel Reader as the source, TCP Sender (MLLP transmission mode) sending to 6660 as the destination.  For Queue Settings, set to Attempt First.  Leave everything else as defaults.

With HL7 Inspector listening, send a message to the channel.  Sends through fine.  Now, stop HL7 Inspector.  Send another message to the channel.  Since HL7 Inspector is no longer listening, the message is queued.  Everything good so far.

Now go into the message view for the channel and delete the message.  The message data is gone.  Start the HL7 Inspector listening again.  Even though the message has been deleted, on each retry interval, you get the following exception in the server log:

2013-08-24 09:52:16,708]  ERROR (com.mirth.connect.connectors.tcp.TcpDispatcher:498): Error processing queued message 2-1 (SENT) for channel 13e934ea-410b-44d7-acc4-a800cc83cf22 (Destination 1). This error is expected if the message was manually removed from the queue.
com.mirth.connect.donkey.server.data.DonkeyDaoException: java.sql.SQLIntegrityConstraintViolationException: INSERT on table 'D_MC2' caused a violation of foreign key constraint 'MC2_FKEY' for key (2,1).  The statement has been rolled back.
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.storeContent(JdbcDao.java:289)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.storeMessageContent(JdbcDao.java:222)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:103)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:61)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.run(DestinationConnector.java:486)
	at java.lang.Thread.run(Thread.java:680)Caused by: java.sql.SQLIntegrityConstraintViolationException: INSERT on table 'D_MC2' caused a violation of foreign key constraint 'MC2_FKEY' for key (2,1).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeLargeUpdate(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeUpdate(Unknown Source)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.storeContent(JdbcDao.java:285)
	... 6 moreCaused by: java.sql.SQLException: INSERT on table 'D_MC2' caused a violation of foreign key constraint 'MC2_FKEY' for key (2,1).  The statement has been rolled back.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 17 moreCaused by: ERROR 23503: INSERT on table 'D_MC2' caused a violation of foreign key constraint 'MC2_FKEY' for key (2,1).  The statement has been rolled back.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.execute.ForeignKeyRIChecker.doCheck(Unknown Source)
	at org.apache.derby.impl.sql.execute.GenericRIChecker.doCheck(Unknown Source)
	at org.apache.derby.impl.sql.execute.RISetChecker.doFKCheck(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 11 more

Additionally, HL7 Inspector will now receive the message over and over again (whatever the retry interval is).  And since the message data is deleted, the only recourse is to stop/undeploy the channel.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2892
Reporter: ericb
Created: 2013-08-24T09:59:16.000-0700

**Comment by rbeckman-nextgen** [comment]
I was able to reproduce this; you have to let the queue thread attempt to send it at least once, and _then_ delete the queued message. That way _canAcquire_ is set to false, but the queue thread still holds the same connector message in memory. When we catch such an exception in the queue thread we always invalidate the queue (DestinationConnector:501), but we also need to set _canAcquire_ back to true as well so that it will get the connector message from the queue itself rather than using the in-memory reference (which is now incorrect since the corresponding message in the database has been deleted).

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-24T10:45:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revision 6850.

Imported Comment. Original Details:
Author: narupley
Created: 2013-08-26T15:15:13.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that deleting a queued message that was already attempted once no longer causes the message to be sent over and over. The SQL Exception still occurs once but that is expected.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-08-30T10:38:57.000-0700
