### ISSUE TITLE
Setting a different http contextpath does not work properly

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2846]
Setting a different http contextpath does not work properly.  This is because the trailing slash is not handled properly.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2920
Reporter: jacobb
Created: 2013-09-04T15:54:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Allow different context paths by making sure the context path always begins with a slash, does not end with a slash, and then append urls that begin with slashes.


Imported Comment. Original Details:
Author: jacobb
Created: 2013-09-04T18:29:06.000-0700

**Comment by rbeckman-nextgen** [comment]
This still doesn't work with the Server Manager. When launching the administrator it's still trying to point to the URL without the correct context path. 
\\
`CouldNotLoadArgumentException[ Could not load file/URL specified: http://localhost:9080/webstart.jnlp?time=1378419742823]
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

Imported Comment. Original Details:
Author: narupley
Created: 2013-09-05T15:25:04.000-0700

**Comment by rbeckman-nextgen** [comment]
Changed the Launch Administrator button to use the user-defined context path, and updated the contextPath logic to match the server.


Imported Comment. Original Details:
Author: jacobb
Created: 2013-09-05T16:05:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that different context paths now work as expected, in both 2.x and 3.0.

Imported Comment. Original Details:
Author: narupley
Created: 2013-09-05T16:33:42.000-0700
