### ISSUE TITLE
Error when launching CLI in Windows after running installer

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2857]
The following error appears when launching the CLI after running the installer in Windows (the CLI is still functional):

log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: C:\Program Files\Mirth Connect\logs\mirth.log (Access is denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
        at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
        at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:809)
        at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:735)
        at org.apache.log4j.PropertyConfigurator.configureRootCategory(PropertyConfigurator.java:615)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:502)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:547)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:483)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:117)
        at com.mirth.connect.cli.launcher.CommandLineLauncher.<clinit>(CommandLineLauncher.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
        at com.exe4j.runtime.WinLauncher.main(Unknown Source)
        at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)
Connected to Mirth Connect server @ https://127.0.0.1:8443 (3.0.0.6902)
$

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2931
Reporter: brentm
Created: 2013-09-06T10:38:18.000-0700

**Comment by rbeckman-nextgen** [comment]
This happened because the CLI was trying to load the Server's log4.properties file and cannot access it without administrator privileges.

The CLI now loads it's log4j configuration from a separate log4j-cli.properties file, which resolves this problem and eliminates the error.

Imported Comment. Original Details:
Author: brentm
Created: 2013-09-06T17:30:12.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that the CLI now has its own log4j properties file which does not require write access to the Mirth log folder. The error no longer appears when the CLI is not run with administrator privileges.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-09-06T17:47:09.000-0700
