### ISSUE TITLE
Error deploying JMS listener channel,which is working in 2.2.1

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2909]
Working channel in 2.2.1 is giving error in 3.0.0

In 2.2.1 the activemq-all-5.1.0.jar was copied in mirthconenct/lib/externals. But in 3.0.0 since there is no folder called lib,I copied the same to /server-lib/externals.

While deploying the channel,its giving error.

ERROR 2013-10-10 12:50:36,715 [Thread-1] com.mirth.connect.server.Mirth: http.port port is already in use: 8081
ERROR 2013-10-10 12:50:36,716 [Thread-1] com.mirth.connect.server.Mirth: https.port port is already in use: 8443
ERROR 2013-10-10 12:52:04,313 [pool-3-thread-1] com.mirth.connect.donkey.server.channel.Channel: Error stopping Source connector for channel RIS-HIS Patient Update - 34 (e86e6a5c-d09f-4132-adb6-1dd27f1df4b7).
com.mirth.connect.donkey.server.StopException: Failed to close JMS connection
	at com.mirth.connect.connectors.jms.JmsReceiver.onStop(JmsReceiver.java:99)
	at com.mirth.connect.donkey.server.channel.SourceConnector.stop(SourceConnector.java:102)
	at com.mirth.connect.donkey.server.channel.Channel.stop(Channel.java:688)
	at com.mirth.connect.donkey.server.channel.Channel.access$2500(Channel.java:79)
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1868)
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1780)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mirth.connect.donkey.server.StopException: Failed to close the JMS connection
	at com.mirth.connect.connectors.jms.JmsClient.stop(JmsClient.java:148)
	at com.mirth.connect.connectors.jms.JmsReceiver.onStop(JmsReceiver.java:97)
	... 10 more
Caused by: org.apache.activemq.ConnectionClosedException: The connection is already closed
	at org.apache.activemq.ActiveMQConnection.checkClosed(ActiveMQConnection.java:1271)
	at org.apache.activemq.ActiveMQConnection.checkClosedOrFailed(ActiveMQConnection.java:1258)
	at org.apache.activemq.ActiveMQConnection.stop(ActiveMQConnection.java:497)
	at org.apache.activemq.ActiveMQConnection.close(ActiveMQConnection.java:552)
	at com.mirth.connect.connectors.jms.JmsClient.stop(JmsClient.java:146)
	... 11 more
ERROR 2013-10-10 12:52:04,426 [Thread-2] com.mirth.connect.server.controllers.DonkeyEngineController: Error deploying channel e86e6a5c-d09f-4132-adb6-1dd27f1df4b7.
com.mirth.connect.donkey.server.StartException: com.mirth.connect.donkey.server.StartException: Failed to initialize JMS message consumer for destination "topic://dynamicTopics/dhl7PatientUpdateSubsc"
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1880)
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1780)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)
Caused by: com.mirth.connect.donkey.server.StartException: Failed to initialize JMS message consumer for destination "topic://dynamicTopics/dhl7PatientUpdateSubsc"
	at com.mirth.connect.connectors.jms.JmsReceiver.onStart(JmsReceiver.java:88)
	at com.mirth.connect.donkey.server.channel.SourceConnector.start(SourceConnector.java:88)
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1858)
	... 6 more
Caused by: javax.naming.NamingException: scheme topic not recognized
	at org.apache.activemq.jndi.ReadOnlyContext.lookup(ReadOnlyContext.java:211)
	at javax.naming.InitialContext.lookup(InitialContext.java:392)
	at com.mirth.connect.connectors.jms.JmsClient.getDestination(JmsClient.java:190

)
	at com.mirth.connect.connectors.jms.JmsReceiver.onStart(JmsReceiver.java:70)
	... 8 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2987
Reporter: sajugn@gmail.com
Created: 2013-10-10T01:29:55.000-0700

**Comment by rbeckman-nextgen** [comment]
Just a note: all custom libs should be put into the custom-lib folder.  You should not be modifying the contents of server-lib.

Imported Comment. Original Details:
Author: jacobb
Created: 2013-10-10T11:26:54.000-0700

**Comment by rbeckman-nextgen** [comment]
Can you attach an export of your channel?

Thanks

Imported Comment. Original Details:
Author: brentm
Created: 2013-10-10T11:55:52.000-0700

**Comment by rbeckman-nextgen** [comment]
Channel attached.

Imported Comment. Original Details:
Author: sajugn@gmail.com
Created: 2013-10-10T22:23:49.000-0700

**Comment by rbeckman-nextgen** [comment]
Please try removing the "topic://" prefix from your destination name and let us know if that resolves the problem.

Imported Comment. Original Details:
Author: brentm
Created: 2013-10-14T13:04:31.000-0700

**Comment by rbeckman-nextgen** [comment]
Thanks Brent, 

Now I am able to deploy the channel,but while receiving the message i am getting an error in Source Connector.

Raw Message : 2233389

Error :
DelimitedSerializer error
ERROR MESSAGE: Error converting delimited text to XML
java.lang.NullPointerException
	at com.mirth.connect.plugins.datatypes.delimited.DelimitedReader.getRecord(DelimitedReader.java:181)
	at com.mirth.connect.plugins.datatypes.delimited.DelimitedReader.parse(DelimitedReader.java:102)
	at com.mirth.connect.plugins.datatypes.delimited.DelimitedSerializer.toXML(DelimitedSerializer.java:94)
	at com.mirth.connect.donkey.server.channel.FilterTransformerExecutor.processConnectorMessage(FilterTransformerExecutor.java:91)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1187)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:907)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:177)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:154)
	at com.mirth.connect.connectors.jms.JmsReceiver$JmsReceiverMessageListener.onMessage(JmsReceiver.java:141)
	at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:967)
	at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:122)
	at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:192)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:122)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:43)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)

Imported Comment. Original Details:
Author: sajugn@gmail.com
Created: 2013-10-14T22:56:07.000-0700

**Comment by rbeckman-nextgen** [comment]
The Delimited Text issue appears to be separate from this JMS issue; I've added it as MIRTH-3002.

Imported Comment. Original Details:
Author: narupley
Created: 2013-10-15T08:18:38.000-0700

**Comment by rbeckman-nextgen** [comment]
Added migration logic to prevent this from happening in the future when migrating from 2.x to 3.0.0. Existing instances of 3.0.0 will need to have the topic or queue prefix removed from the destination name (either //topic:, topic://, //queue: or queue://).

Imported Comment. Original Details:
Author: brentm
Created: 2013-10-15T09:08:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that the topic/queue prefixes are removed upon migration from 2.x to 3.0.

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-13T10:00:47.000-0800
