### ISSUE TITLE
Message containing ascii zero (null) character causes error

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2910]
Even with the 'Remove Illegal XML characters' replacement in the pre-processor, Message fails with the following error if it contains ascii 0:

I tested the same message against version 2.2.3 and it processed fine.

[2013-10-10 21:50:48,457]  ERROR (com.mirth.connect.donkey.server.channel.Channel:970): Error processing message.
com.mirth.connect.donkey.server.channel.ChannelException: com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:929)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:177)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:154)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:524)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:391)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)Caused by: com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertContent(JdbcDao.java:244)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMessageContent(JdbcDao.java:172)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:98)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:61)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:903)
	... 9 moreCaused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:332)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertContent(JdbcDao.java:241)
	... 14 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-2988
Reporter: seaston
Created: 2013-10-10T14:14:59.000-0700

**Comment by rbeckman-nextgen** [comment]
This is because we now store the original raw data, so the "Remove Invalid Characters" function in the References tab no longer has the desired effect. Any 2.x channels that were doing this in the preprocessor specifically for these kinds of storage issues will break in 3.0 now...

A fix in the meantime is to move that code from the preprocessor to an attachment script, which now can be technically used as a sort of "pre-preprocessor".

Imported Comment. Original Details:
Author: narupley
Created: 2013-10-10T14:40:27.000-0700

**Comment by rbeckman-nextgen** [comment]
Yes Nick, I've tried this and can confirm that it is a good 'work-around' for the time being.
Simon

Imported Comment. Original Details:
Author: seaston
Created: 2013-10-11T06:49:16.000-0700

**Comment by rbeckman-nextgen** [comment]
We've determined that this issue only affects Postgres and the only character that causes this problem is 0x00 because the 0x00 character is not allowed in Postgres for text data types. This is not directly related to illegal XML characters, and those characters (except 0x00 of course) can still be removed just fine in the Preprocessor. This problem only exists for ASCII data, because binary data will be Base64 encoded.

Since this should be pretty rare, we have decided not to make any changes for this issue at this time. As stated above, these characters can still be stripped by using a Javascript attachment handler and adding

message = message.replace(/\x00/g, '');

As a side note, if you are expected the 0x00 character to be present in ASCII messages, it may be worth asking why it is there. 

Imported Comment. Original Details:
Author: wayneh
Created: 2013-10-30T17:56:30.000-0700

**Comment by rbeckman-nextgen** [comment]
Well for one thing, the problem doesn't only exist for ASCII data, it also exists for _all other_ text encodings. And in some encodings, 0x00 does not indicate a NUL character. For example, in IBM 00863 (used in Canada), 0x00 denotes Ç (U+00C7). So in at least some cases, it should be perfectly valid to have those characters in the message, and removing them in a preprocessor/attachment script would not be correct, strictly speaking.

I'd agree that it's not a common issue, but it's also not a "rare" issue. I can remember around a dozen people on the forums who had this issue in 2.x. Most of our clients are on PostgreSQL, so that's already one of the two checkboxes needed to cause the issue; if they _did_ need to read in text data that happened to have control characters, they would have to encode in Base64 instead, or else remove those characters altogether.

Does the issue only occur with PostgreSQL? What about with, say, MySQL with a default charset of UTF-8? Obviously it's the charset that's causing this to happen, but maybe other databases still allow inserts and just ignore those characters or something.

_**If**_ it's okay to just strip the message of those characters, then it's an easy workaround: use an attachment script. But is it okay that we're basically turning the JavaScript attachment handler into a "pre-preprocessor" in this way? If clients use and depend on this workaround, then we can't easily change the behaviour of attachment handlers later (at the very least, we would need to preserve the ability to modify the inbound string message before and data is committed to the database).

If it's not okay to strip out those characters, then one workaround is to change the default charset for PostgreSQL. I don't know if this is possible for appliances though. Another workaround would be to Base64 encode the message instead, but that's definitely not ideal, because it basically defeats the purpose of being able to read in a text file. If it's an HL7 message then they wouldn't be able to transform it like they would normally.

It sounds like the more common case is that the user doesn't care if the characters are stripped out, so as mentioned before there's an easy workaround. Plus, there's not really much we can do from the Mirth Connect side, because we don't have control over what the database decides is valid or invalid. Though certainly this issue affects (and will affect) more than a few people, in the end I still think we're fine leaving it how it is.

Imported Comment. Original Details:
Author: narupley
Created: 2014-02-11T06:36:56.000-0800

**Comment by rbeckman-nextgen** [comment]
My issue is not with a database, but a file reader source, but I disagree with leaving this as is.  "TypeError: An invalid XML character (Unicode: 0x1a) was found in the element content of the document." is occurring on 5 of our channels.  I have tried:

DATA TYPE JAVA BATCH SCRIPT
var newmessage = message.replace(/[\n\r]$/,""); 
return newmessage;





var line = '', message = '', discard = true;
reader.mark(8192);
while ((line = reader.readLine()) != null) {
	if (line.trim().isEmpty(? ](| /^[FB)[HT]S.*/.test(line)) {
		if (/^[FB][HT]S.*/.test(line))
			discard = true;
		reader.mark(8192);
		continue;
	}
	if (/^[A-Z][A-Z0-9]{2}.*/.test(line)) {
		if (/^MSH.*/.test(line) && message != '') {
			reader.reset();
			return message;
		}
		discard = false;
		message += line + '\r';
	} else if (!discard)
		message = message.trim() + line + '\r';
	reader.mark(8192);
}
return message;



PREPROCESSOR

var newMessage = '';
newMessage = message.replace(/\r/g,'\r\n');
return newMessage;

or

 you need a Record Delimiter of \r and Ignore Carriage Returns unchecked. 
 
 var i = -1, str = '';
while ((i = reader.read()) != -1) {
	str += String.fromCharCode(i);
	if (i == 13) {
		reader.mark(1);
		var j = reader.read();
		if (j == 10)
			str += String.fromCharCode(i);
		else
			reader.reset();
		break;
	}
	else if (i == 10)
		break;
}
return str;

var line = '', message = '', discard = true;

if (sourceMap.get('batchComplete') = true)
{
  default xml namespace = '';
}

while (msg[patient][patientid]<'0')
tmp[patientid] = 0
if (sourceMap.get('batchComplete') = true)
		{break};

Still no resolution.  To say "I still think we're fine leaving it how it is." is hard to believe. Please reconsider and help correct this issue. I am a huge fan of yours' Nick and this surprises me.  

Imported Comment. Original Details:
Author: csummer
Created: 2015-01-14T07:55:58.000-0800

**Comment by rbeckman-nextgen** [comment]
Sorry to let you down :(

Looking at your specific scenario though, I don't understand how your code relates to the "invalid XML character (Unicode: 0x1a)" error. Where in your code are you replacing SUB (0x1A) characters? Your preprocessor should instead be something like this:

`message.replace('\x1A', '');`
\\
There's even already a template for this in the References list:
\\
\\
+**Remove Illegal XML Characters**+:
`var newMessage = message.replace(/[\x00-\x08]]([\x0B-\x0C)|[\x0E-\x1F]/g, '');`

The error you're getting is an E4X XML limitation that only occurs when the message enters the filter/transformer. It should have nothing to do with this issue, because this issue deals with the fact that the pre-preprocessor raw data is being stored in the database.

Imported Comment. Original Details:
Author: narupley
Created: 2015-01-14T08:05:31.000-0800

**Comment by rbeckman-nextgen** [comment]
Thank you for getting back with me.  Just a little frustrated right now.  I used the reference “Remove illegal XML Characters” and I also put the  “message.replace(‘\x1A’, ‘ ‘); in the preprocessor script tab.  Then my source transformer returns <delimiter\>  with an error message like “Unable to parse ‘ ‘.”   The line it errors on is  “msg = new XML(connectorMessage.getTransformedData());” Any clue to what is happening?

Imported Comment. Original Details:
Author: csummer
Created: 2015-01-14T08:25:11.000-0800

**Comment by rbeckman-nextgen** [comment]
You should not be using typographic quotes (like ‘ ’). Use neutral quotes (like ' '). Also if there's more than one SUB character, use /\x1A/g instead. Since this has nothing to do with this issue, you should post this in the forums instead.

Imported Comment. Original Details:
Author: narupley
Created: 2015-01-14T08:30:23.000-0800

**Comment by rbeckman-nextgen** [comment]
Ok.

From: Nick Rupley (JIRA) [mailto:issues@mirthcorp.com]
Sent: Wednesday, January 14, 2015 11:31 AM
To: Cynthia Summer - Acuity Service Center
Subject: [JIRA] (MIRTH-2988) Message containing ascii zero (null) character causes error

[cid:image001.png@01D02FEE.D8CA1A70]

Nick Rupley<http://www.mirthcorp.com/community/issues/secure/ViewProfile.jspa?name=narupley> commented on [Bug] MIRTH-2988<http://www.mirthcorp.com/community/issues/browse/MIRTH-2988>




Re: Message containing ascii zero (null) character causes error<http://www.mirthcorp.com/community/issues/browse/MIRTH-2988>



You should not be using typographic quotes (like ‘ ’). Use neutral quotes (like ' '). Also if there's more than one SUB character, use /\x1A/g instead. Since this has nothing to do with this issue, you should post this in the forums instead.


[Add Comment]<http://www.mirthcorp.com/community/issues/browse/MIRTH-2988#add-comment>

Add Comment<http://www.mirthcorp.com/community/issues/browse/MIRTH-2988#add-comment>






This message was sent by Atlassian JIRA (v6.2.7#6265-sha1:91604a8)

[Atlassian logo]






Imported Comment. Original Details:
Author: csummer
Created: 2015-01-14T08:41:11.000-0800
