### ISSUE TITLE
Clear all Statistics Error

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2942]
Clicking the 'Clear All Statistics' server task results in the following error

[2013-10-21 17:48:57,390]  ERROR (com.mirth.connect.server.servlets.ChannelStatisticsServlet:113): java.lang.NullPointerException

	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.resetAllStatistics(JdbcDao.java:1517)

	at com.mirth.connect.donkey.server.controllers.ChannelController.resetAllStatistics(ChannelController.java:101)

	at com.mirth.connect.server.servlets.ChannelStatisticsServlet.doPost(ChannelStatisticsServlet.java:107)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)

	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)

	at org.eclipse.jetty.server.Server.handle(Server.java:363)

	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)

	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)

	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)

	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)

	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)

	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)

	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3022
Reporter: seaston
Created: 2013-10-21T09:53:31.000-0700

**Comment by rbeckman-nextgen** [comment]
Screenshot of Administrator error

Imported Comment. Original Details:
Author: seaston
Created: 2013-10-21T09:55:43.000-0700

**Comment by rbeckman-nextgen** [comment]
NB: Some of the channel stats appear to have been reset before the error, but not all

Imported Comment. Original Details:
Author: seaston
Created: 2013-10-21T09:56:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Are you able to reproduce this every time?  How many channels do you have?  Was this a clean install of Mirth Connect 3.0 or an upgrade?

Imported Comment. Original Details:
Author: jacobb
Created: 2013-10-23T17:10:38.000-0700

**Comment by rbeckman-nextgen** [comment]
It appears that if there are any disabled channels when the server is starting, the Clear All Statistics task will throw this error until all of those disabled channels are deployed. They do not need to remain deployed, only be deployed at least once since the server started. This only affects channels that existed before the server started AND have already been deployed at least once in their lifetime.

This is a bug and will be fixed for 3.0.1. In the meantime if you need to use Clear All Statistics, just deploy all your channels, and then undeploy the unnecessary ones.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-10-23T17:39:55.000-0700

**Comment by rbeckman-nextgen** [comment]
In response to Jacob and Wayne, Yes, this can be reproduced every time.  I have 56 channels, but only 53 are active and deployed.  This was not a clean install, but an upgrade to version 2.2.3.
Wayne's comment would be true in my case that I had channels deployed which are no longer deployed, and some deployed that have now been deleted.
Simon

Imported Comment. Original Details:
Author: seaston
Created: 2013-10-24T00:32:50.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that the exception is no longer thrown when the server starts up with disabled channels.

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-13T13:31:03.000-0800
