### ISSUE TITLE
Attachment data with replacement tokens do not get reattached correctly

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2949]
For example, if the attachment content contains a "$" character, you'll get the following error:
\\
\\
`[2013-10-25 10:37:58,200]  ERROR (com.mirth.connect.server.util.AttachmentUtil:40): Error reattaching attachments
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:808)
	at java.util.regex.Matcher.replaceAll(Matcher.java:906)
	at java.lang.String.replaceAll(String.java:2162)
	at com.mirth.connect.server.util.AttachmentUtil.reAttachMessage(AttachmentUtil.java:35)
	at com.mirth.connect.server.util.DICOMUtil.reAttachMessage(DICOMUtil.java:170)
	at org.mule.providers.TemplateValueReplacer.loadContextFromMessageObject(TemplateValueReplacer.java:161)
	at org.mule.providers.TemplateValueReplacer.replaceValues(TemplateValueReplacer.java:85)
	at org.mule.providers.TemplateValueReplacer.replaceValues(TemplateValueReplacer.java:79)
	at com.mirth.connect.connectors.vm.VMMessageDispatcher.routeTemplatedMessage(VMMessageDispatcher.java:178)
	at com.mirth.connect.connectors.vm.VMMessageDispatcher.doSend(VMMessageDispatcher.java:265)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:164)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:54)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:176)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:143)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:225)
	at com.mirth.connect.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:222)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Thread.java:724)`

This is because AttachmentUtil just does a replaceAll on the message, and the attachment content is used verbatim in the replacement parameter. Backspaces are currently escaped, but nothing else.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3029
Reporter: narupley
Created: 2013-10-25T10:37:03.000-0700

**Comment by rbeckman-nextgen** [comment]
This has been fixed along with the changes for MIRTH-2267.

Imported Comment. Original Details:
Author: narupley
Created: 2013-10-25T10:37:36.000-0700
