### ISSUE TITLE
Broken Pipe on TCP connector

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2968]
I have seen this error occur twice since upgrading to version 3.0 so am assuming it is a bug of sorts with version 3.0:

TCP Sender error
ERROR MESSAGE: Broken pipe
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
	at java.io.BufferedOutputStream.flush(Unknown Source)
	at com.mirth.connect.connectors.tcp.TcpDispatcher.send(TcpDispatcher.java:224)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:540)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.run(DestinationConnector.java:457)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3051
Reporter: seaston
Created: 2013-11-08T03:41:38.000-0800

**Comment by rbeckman-nextgen** [comment]
Restarting the client side of the interface seems to fix the problem, but if you are closing the log, please can you explain what the cause of the error is, and if it is due to better logging in version 3.0?
Thank you,
Simon

Imported Comment. Original Details:
Author: seaston
Created: 2013-11-08T04:14:09.000-0800

**Comment by rbeckman-nextgen** [comment]
That occurs when the remote side closes its side of the connection while the local side is still sending data. So in short yes, it is due to better logging in 3.0.

You said you've only come across the issue twice so far right? You said that you need to "restart the client-side interface to fix the problem". Does that mean that when it happens, it's not just one message that errors out, but all subsequent messages error out as well?

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-08T08:37:33.000-0800

**Comment by rbeckman-nextgen** [comment]
That's helpful Nick.  What happens is that the same message repeatedly fails.  You can see in the first screenshot that the message has processing errors and the others are backed up behind it.  What I don't understand is why I don't see the retry count incrementing, and why stopping and restarting the Mirth Connect side of the interface does not just reset the connection.

Imported Comment. Original Details:
Author: seaston
Created: 2013-11-08T08:58:31.000-0800

**Comment by rbeckman-nextgen** [comment]
Sorry Nick - send attempts was not displayed for some reason - this is why I thought I did not see this increment.  See third attachment

Imported Comment. Original Details:
Author: seaston
Created: 2013-11-08T09:11:21.000-0800

**Comment by rbeckman-nextgen** [comment]
Ohh okay, so by "restarting the client side of the interface", you actually meant restarting the server-side, right? That is, the TCP server interface hosted by one of your clients, I'm assuming.

Even without restarting the Mirth Connect channel, the TCP Sender will create a whole new connection if an error occurred. So when the "broken pipe" error occurs, the TCP Sender catches that, logs it out, closes the client-side socket, and continues to queue the message. On the next send attempt, it will create a whole new client-side socket, establishing a new TCP connection. 

My guess is that the server you're connecting to isn't handling all of this gracefully. First, it seems that it's closing the connection prematurely (that's how you run into the "broken pipe" error in the first place). Second, it seems that it's not handling remote socket closure "correctly". After the initial error, the server may be holding on to the connection for some sort of wait period or something like that, causing subsequent new client connections to also block or get rejected.

Of course this is all speculation; the only way to know for sure what is happening is by taking a network capture and catching the issue in the act of occurring. Just to clarify, you said it's only happened twice so far since you upgraded to 3.0 right? So it's not a common thing?

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-08T09:16:23.000-0800

**Comment by rbeckman-nextgen** [comment]
Yes, sorry - bit of confusion here.  Yes, I do mean restarting the server or listening side of the interface.

Yes, since upgrading it has happened twice, so not common, but I have not noticed this happening before which is why I jumped to the conclusion that it was something to do with 3.0.  It needs a more detailed examination, but the trouble is when it breaks, they want you to get it going again quickly!

Imported Comment. Original Details:
Author: seaston
Created: 2013-11-08T09:20:22.000-0800

**Comment by rbeckman-nextgen** [comment]
Well disregarding the "broken pipe" error, did you ever experience scenarios with 2.x where messages would stop sending and you needed to restart the remote interface?

Imported Comment. Original Details:
Author: narupley
Created: 2013-11-08T09:24:16.000-0800

**Comment by rbeckman-nextgen** [comment]
Well Nick I could not honestly say that I did not / have not.  As you infer, I accept it probably has happened before, nobody would have been aware of exactly what was happening.  Another example of how much better 3.0 in helping us to debug problems.  Thank you as always for taking the time to help and inform.
Simon

Imported Comment. Original Details:
Author: seaston
Created: 2013-11-08T09:30:17.000-0800

**Comment by rbeckman-nextgen** [comment]
Closing this issue. In 2.x you likely wouldn't have seen the "broken pipe" errors just because they usually didn't make their way into the server log. I wasn't ever able to reproduce this where it was Mirth Connect doing something wrong rather than the server (or some connectivity problem).

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-05T16:36:49.000-0800
