### ISSUE TITLE
Schema migration fails under MySQL 5.0 / 5.1

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2978]
See related forum post:

http://www.mirthcorp.com/community/forums/showthread.php?t=9243&page=2

To reproduce:

Set up a Mirth Connect 2.x instance running on a MySQL 5.1.52 database. Then attempt to migrate it to Mirth Connect 3.0.0. The following error will appear in the console and the server will halt with the schema left partially migrated:

ERROR 2013-11-14 09:26:56,071 [main] com.mirth.connect.server.Mirth: Failed to migrate database schema
com.mirth.connect.model.util.MigrationException: Failed to execute script: mysql-9-3.0.0-1.sql
	at com.mirth.connect.server.migration.Migrator.executeScript(Migrator.java:87)
	at com.mirth.connect.server.migration.Migrate3_0_0.migrate(Migrate3_0_0.java:46)
	at com.mirth.connect.server.migration.ServerMigrator.migrate(ServerMigrator.java:63)
	at com.mirth.connect.server.controllers.DefaultMigrationController.migrate(DefaultMigrationController.java:85)
	at com.mirth.connect.server.Mirth.startup(Mirth.java:235)
	at com.mirth.connect.server.Mirth.run(Mirth.java:154)
	at com.mirth.connect.server.Mirth.main(Mirth.java:107)
Caused by: java.sql.SQLException: Can't execute the given command because you have active locked tables or an active transaction
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4187)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4119)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2809)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2758)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:894)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:732)
	at com.mirth.connect.server.migration.Migrator.executeScript(Migrator.java:84)
	... 6 more
INFO  2013-11-14 09:26:56,073 [Thread-4] com.mirth.connect.server.Mirth: shutting down mirth due to normal request

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3061
Reporter: brentm
Created: 2013-11-14T09:27:43.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed error when migrating to version 3.0.0 when using a MySQL 5.0.x or 5.1.x database.

There was a bug in these versions of MySQL (http://bugs.mysql.com/bug.php?id=54462) that left the previous transaction open when switching from autocommit off to autocommit on.

As a workaround, added a START TRANSACTION statement to the beginning of the mysql 3.0.0 migration script that will force the previous transaction to close.

Tested with MySQL 5.1.52 and verified that it resolves the migration problem.

Also tested with the latest MySQL 5.6.14 and verified that migration still works with this version as well.

Imported Comment. Original Details:
Author: brentm
Created: 2013-11-14T11:30:01.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified. Tested with MySQL 5.1.30.

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-04T10:05:42.000-0800
