### ISSUE TITLE
Memory leak in Frame when logging out of the Administrator

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#2991]
If you log out and in several times in the Administrator without shutting it down, you will eventually get an OutOfMemoryError.

To reproduce, log in, do anything in the Administrator like create a simple channel, then log out and in at least 5 or so times.

{noformat}
2013-11-26 17:07:02.837 java[68217:507] java.lang.OutOfMemoryError: Java heap space
	at java.awt.image.DataBufferInt.<init>(DataBufferInt.java:75)
	at java.awt.image.Raster.createPackedRaster(Raster.java:470)
	at java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1032)
	at sun.java2d.opengl.CGLGraphicsConfig.createCompatibleImage(CGLGraphicsConfig.java:201)
	at java.awt.GraphicsConfiguration.createCompatibleImage(GraphicsConfiguration.java:178)
	at sun.lwawt.macosx.CPlatformView.createBackBuffer(CPlatformView.java:134)
	at sun.lwawt.macosx.CPlatformWindow.createBackBuffer(CPlatformWindow.java:403)
	at sun.lwawt.LWWindowPeer.replaceSurfaceData(LWWindowPeer.java:1015)
	at sun.lwawt.LWWindowPeer.replaceSurfaceData(LWWindowPeer.java:988)
	at sun.lwawt.LWWindowPeer.notifyReshape(LWWindowPeer.java:624)
	at sun.lwawt.macosx.CPlatformWindow.deliverMoveResizeEvent(CPlatformWindow.java:885)
2013-11-26 17:07:02.841 java[68217:507] (
	0   CoreFoundation                      0x00007fff8bf3641c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff8ee48e75 objc_exception_throw + 43
	2   CoreFoundation                      0x00007fff8bf35fc9 -[NSException raise] + 9
	3   JavaNativeFoundation                0x000000011035c539 JNFCallVoidMethod + 209
	4   liblwawt.dylib                      0x0000000111160f34 -[AWTWindow _deliverMoveResizeEvent] + 310
	5   CoreFoundation                      0x00007fff8bf04fcc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	6   CoreFoundation                      0x00007fff8bdf8c5d _CFXNotificationPost + 2893
	7   Foundation                          0x00007fff831eb4aa -[NSNotificationCenter postNotificationName:object:userInfo:] + 68
	8   AppKit                              0x00007fff8d43e2d1 -[NSWindow _setFrameCommon:display:stashSize:] + 1958
	9   liblwawt.dylib                      0x00000001111632c4 __Java_sun_lwawt_macosx_CPlatformWindow_nativeSetNSWindowBounds_block_invoke_1 + 352
	10  JavaNativeFoundation                0x000000011035e5f5 +[JNFRunLoop _performCopiedBlock:] + 20
	11  Foundation                          0x00007fff8324c0de __NSThreadPerformPerform + 229
	12  CoreFoundation                      0x00007fff8be678f1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	13  CoreFoundation                      0x00007fff8be59062 __CFRunLoopDoSources0 + 242
	14  CoreFoundation                      0x00007fff8be587ef __CFRunLoopRun + 831
	15  CoreFoundation                      0x00007fff8be58275 CFRunLoopRunSpecific + 309
	16  HIToolbox                           0x00007fff8a614f0d RunCurrentEventLoopInMode + 226
	17  HIToolbox                           0x00007fff8a614cb7 ReceiveNextEventCommon + 479
	18  HIToolbox                           0x00007fff8a614abc _BlockUntilNextEventMatchingListInModeWithFilter + 65
	19  AppKit                              0x00007fff8d31d28e _DPSNextEvent + 1434
	20  AppKit                              0x00007fff8d31c8db -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	21  libosxapp.dylib                     0x00000001111f6b56 -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 124
	22  AppKit                              0x00007fff8d3109cc -[NSApplication run] + 553
	23  libosxapp.dylib                     0x00000001111f69b9 +[NSApplicationAWT runAWTLoopWithApp:] + 156
	24  liblwawt.dylib                      0x000000011115081a -[AWTStarter starter:] + 1591
	25  Foundation                          0x00007fff8324c0de __NSThreadPerformPerform + 229
	26  CoreFoundation                      0x00007fff8be678f1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	27  CoreFoundation                      0x00007fff8be59062 __CFRunLoopDoSources0 + 242
	28  CoreFoundation                      0x00007fff8be587ef __CFRunLoopRun + 831
	29  CoreFoundation                      0x00007fff8be58275 CFRunLoopRunSpecific + 309
	30  java                                0x000000010af5a42d CreateExecutionEnvironment + 871
	31  java                                0x000000010af54bdc JLI_Launch + 1952
	32  java                                0x000000010af5a78a main + 101
	33  java                                0x000000010af54434 start + 52
)
{noformat}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3074
Reporter: brentm
Created: 2013-11-26T17:11:28.000-0800

**Comment by rbeckman-nextgen** [comment]
Frame is not being garbage collected because there are still references to it. Some dialogs we have do not use dispose when they are "hidden", and instead only use setVisible(false). Those dialogs can not be GC'd until they are disposed, even if there are no more explicit references to them (losing a reference to a dialog or frame without disposing it leads to a memory leak).

MIRTH-2940 is slated to make the hide behavior consistent, and this issue gives more reason to be disposing of the dialogs so we don't have to worry about cleaning them up later.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-12-05T17:31:51.000-0800

**Comment by rbeckman-nextgen** [comment]
Confirmed that this issue has existed since 2.2.1, but is more severe in 3.x

Imported Comment. Original Details:
Author: wayneh
Created: 2013-12-06T10:34:21.000-0800

**Comment by rbeckman-nextgen** [comment]
Found the bigger problem. The KeyboardFocusManager used in Frame is still holding a reference to Frame somehow. Possibly explained in one of the following links.
http://www.javalobby.org/java/forums/t19468.html
https://forums.oracle.com/thread/1291090

`
        KeyboardFocusManager.getCurrentKeyboardFocusManager().addKeyEventDispatcher(new KeyEventDispatcher() {

            @Override
            public boolean dispatchKeyEvent(KeyEvent e) {
                // Update the state of the accelerator key (CTRL on Windows)
                updateAcceleratorKeyPressed(e);
                return false;
            }
        });
`

We can fix the problem by storing a reference to the KeyEventDispatcher and removing it from the KeyboardFocusManager during the logout process.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-12-06T12:32:33.000-0800

**Comment by rbeckman-nextgen** [comment]
The issue I mentioned in my first comment does not seem to be a problem as far I as I can tell because we are calling super(PlatformUI.MIRTH_FRAME); in the dialogs. This causes the dialogs to be disposed when the Frame itself is disposed. We just need to make sure that we are calling the super method in all of our dialogs.

However I'd still recommend disposing of the dialogs when we look at MIRTH-2940.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-12-06T12:37:35.000-0800

**Comment by rbeckman-nextgen** [comment]
The main issue which affected all OS's has been fixed in which the Frame leaked each time the user logged off. There still seems to be a less common issue on OSX if the user edits a channel and then logs off. In these cases it is still possible for the Frame to leak, but it doesn't seem to be guaranteed. We initially thought that this was caused by https://bugs.openjdk.java.net/browse/JDK-8029147, but it appears that Java 6u65 on OSX still has this issue. That doesn't mean the issue in the link isn't necessarily a problem, just that there is something else going on as well. Since the larger problem problem has been fixed I'm resolving this issue and creating a new ticket (MIRTH-3090) to track the OSX problem.

Imported Comment. Original Details:
Author: wayneh
Created: 2013-12-06T17:40:29.000-0800

**Comment by rbeckman-nextgen** [comment]
Tested in Windows 7 by logging out and in dozens of times and verified that it does not run out of memory.

Logging out and in several times in OSX still appears to have a memory leak even without editing a channel or doing anything, although it appears to be a slower leak in this case.

Imported Comment. Original Details:
Author: brentm
Created: 2013-12-09T10:29:21.000-0800
