### ISSUE TITLE
Code templates with a comment at the end can cause channels to fail to deploy, and other errors

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3009]
The code templates are just concatenated together with no line breaks. So say you had the following templates:
\\
\\
`function test1() {\n
	logger.info('test1 ran');\n
}\n
// comment`

`function test2() {logger.info('test2 ran');}\n`

When a channel is deployed the actual code becomes:
\\
\\
`function test1() {\n
	logger.info('test1 ran');\n
}\n
// commentfunction test2() {logger.info('test2 ran');}\n`

So syntactically test2() is inside a line comment, and it won't actually be included in the channel code. Similarly, consider a code template like this at the end of the list:
\\
\\
`function test() {}\n
// comment`

If that code template is the last one to be appended, then the actual channel code will be:
\\
\\
`function test() {}\n
// commentfunction validate(mapping, defaultValue, replacement) {\n
var result = mapping;\n
...`

So later on if the channel uses the validate function (like in a Mapper step), it will cause the following error:
\\
\\
`ReferenceError: "validate" is not defined.
	at 87d16251-f024-47aa-b462-dd14d1056971:30 (doTransform)
	at 87d16251-f024-47aa-b462-dd14d1056971:33 (doScript)
	at 87d16251-f024-47aa-b462-dd14d1056971:35
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:134)
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:100)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3094
Reporter: narupley
Created: 2013-12-11T09:31:58.000-0800

**Comment by rbeckman-nextgen** [comment]
Very simple fix; attaching a patch for it.

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-11T09:39:05.000-0800

**Comment by rbeckman-nextgen** [comment]
Revisions 7086 and 7087: Code templates are now always appended to scripts with a terminating line feed.

Imported Comment. Original Details:
Author: narupley
Created: 2014-03-06T19:31:55.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-10T18:00:56.000-0700
