### ISSUE TITLE
Unable to start Mirth Connect after upgrading from 3.0.0 to 3.0.1 with the Advanced Alerting plugin installed

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3012]
* Install Mirth Connect 3.0.0
* Install the Advanced Alerting plugin, and create an alert.
* Upgrade to 3.0.1.
* The server will fail to start, with the following error:
\\
\\
`2013-12-12 07:59:27,302 [Thread-1] Server: Exception in thread "Thread-1" java.lang.AbstractMethodError
ERROR 2013-12-12 07:59:27,304 [Thread-1] Server: 	at com.mirth.connect.model.converters.MigratableConverter.migrateElement(MigratableConverter.java:110)
ERROR 2013-12-12 07:59:27,304 [Thread-1] Server: 	at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:89)
ERROR 2013-12-12 07:59:27,304 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
ERROR 2013-12-12 07:59:27,304 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
ERROR 2013-12-12 07:59:27,304 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
ERROR 2013-12-12 07:59:27,304 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:79)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:72)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:66)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:61)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
ERROR 2013-12-12 07:59:27,305 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
ERROR 2013-12-12 07:59:27,306 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.MapConverter.putCurrentEntryIntoMap(MapConverter.java:90)
ERROR 2013-12-12 07:59:27,306 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:78)
ERROR 2013-12-12 07:59:27,307 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.MapConverter.populateMap(MapConverter.java:72)
ERROR 2013-12-12 07:59:27,307 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.collections.MapConverter.unmarshal(MapConverter.java:67)
ERROR 2013-12-12 07:59:27,307 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
ERROR 2013-12-12 07:59:27,307 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
ERROR 2013-12-12 07:59:27,307 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:355)
ERROR 2013-12-12 07:59:27,307 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:306)
ERROR 2013-12-12 07:59:27,307 [Thread-1] Server: 	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:234)
ERROR 2013-12-12 07:59:27,308 [Thread-1] Server: 	at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:92)
ERROR 2013-12-12 07:59:27,308 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
ERROR 2013-12-12 07:59:27,308 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
ERROR 2013-12-12 07:59:27,308 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
ERROR 2013-12-12 07:59:27,308 [Thread-1] Server: 	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
ERROR 2013-12-12 07:59:27,309 [Thread-1] Server: 	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
ERROR 2013-12-12 07:59:27,309 [Thread-1] Server: 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1058)
ERROR 2013-12-12 07:59:27,309 [Thread-1] Server: 	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1030)
ERROR 2013-12-12 07:59:27,309 [Thread-1] Server: 	at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:168)
ERROR 2013-12-12 07:59:27,310 [Thread-1] Server: 	at com.mirth.connect.server.migration.ServerMigrator.migrateSerializedData(ServerMigrator.java:263)
ERROR 2013-12-12 07:59:27,310 [Thread-1] Server: 	at com.mirth.connect.server.migration.ServerMigrator.migrateSerializedData(ServerMigrator.java:74)
ERROR 2013-12-12 07:59:27,310 [Thread-1] Server: 	at com.mirth.connect.server.controllers.DefaultMigrationController.migrateSerializedData(DefaultMigrationController.java:125)
ERROR 2013-12-12 07:59:27,310 [Thread-1] Server: 	at com.mirth.connect.server.Mirth.startup(Mirth.java:248)
ERROR 2013-12-12 07:59:27,310 [Thread-1] Server: 	at com.mirth.connect.server.Mirth.run(Mirth.java:154)`

This is because an [AbstractMethodError](http://docs.oracle.com/javase/6/docs/api/java/lang/AbstractMethodError.html) is being thrown, which isn't caught in our catch clauses. We removed the "catch (LinkageError e)" clause a while back because we didn't think we needed it, but apparently we actually do need it still.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3097
Reporter: narupley
Created: 2013-12-12T08:11:07.000-0800

**Comment by rbeckman-nextgen** [comment]
I think this would also happen if you just uninstalled the Advanced Alerting plugin, because the advanced model would remain in the alert table, so the next time the server starts it would encounter the same issue.

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-12T08:25:29.000-0800

**Comment by rbeckman-nextgen** [comment]
This is currently affecting a lot of appliance users; if you tried to upgrade from 3.0.0 to 3.0.1, the only workaround is to _manually_ install the plugin:

* Get the correct Advanced Alerting plugin zip, for 3.0.0 or 3.0.1, and upload it to the appliance.
* Extract the zip file, and copy the alert folder into the Mirth Connect extensions folder.
* Add the following entry to appdata/extension.properties: "Advanced\ Alerting = true"

Unfortunately this also means that if you installed the plugin and want to _uninstall_ it you're out of luck currently, unless you wipe out the alert table, or manually convert the alerts in the database to the normal model instead of the advanced model.

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-12T08:45:24.000-0800

**Comment by rbeckman-nextgen** [comment]
Actually I spoke too soon. This is _not_ a problem if you just uninstall the plugin. It's only a problem if you have the plugin installed and then try to upgrade to 3.0.1.

When you just uninstall the plugin, the next time Mirth Connect starts you'll see serialization errors appear in the log, but the server will start up just fine. Any alerts which were converted to the advanced model however, will not show up in the alerts list. You'll have to reinstall the plugin, or just create them again.

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-12T09:20:39.000-0800

**Comment by rbeckman-nextgen** [comment]
After more testing we determined that manually uninstalling the plugin will work as well for a workaround. So:

* Delete the "alert" folder from the extensions directory.
* Remove the "Advanced\ Alerting = true" entry from appdata/extension.properties. (optional)
* You should be able to start up Mirth Connect now. Log in, and navigate to the Extensions view.
* Install the 3.0.1 build of the Advanced Alerting plugin. This won't be an automatic appliance update, so you'll have to manually download the zip file from the customer portal.
* Restart Mirth Connect, and it should come up fine this time.

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-12T10:13:29.000-0800

**Comment by rbeckman-nextgen** [comment]
For this issue, we'll just add the catch for the LinkageError, so if this happens in the future, at least the server will still be able to start.

There's a larger issue though; the reason this error was thrown in the first place is because an outdated version of a class was on the classpath. Even though the Advanced Alerting plugin was incompatible, its JARs were still being loaded. That issue will be handled with MIRTH-3098

Imported Comment. Original Details:
Author: narupley
Created: 2013-12-12T13:45:39.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 7082: Added LinkageError catches on deserialization in ObjectXMLSerializer.

Imported Comment. Original Details:
Author: narupley
Created: 2014-03-06T13:01:32.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified. Note that users will still get an error that their alerts failed to migrate until they install the updated extension.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-10T20:28:38.000-0700
