### ISSUE TITLE
SFTP fails with "File not found: /"

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3016]
The host and port are specified as:

example.com:9516

The text input to the right of the / is empty.

We have used the File Reader / SFTP connector before. The only thing we can think of is some problem with the way the SFTP Java classes interacts with the remote Windows FTP server.

The connection works fine from the command-line.

This looked promising, but it didn't help: http://www.mirthcorp.com/community/issues/browse/MIRTH-566

FATAL 2013-12-17 10:39:55,087 [6275e14e-b051-42cc-b244-246f6076defa_source_connector._fileEndpoint#1408054581.rec
eiver.1] org.mule.impl.DefaultComponentExceptionStrategy: The error is: 2: File not found: /
java.lang.Exception: 2: File not found: /
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:10

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3101
Reporter: john-from-iora
Created: 2013-12-17T09:26:57.000-0800

**Comment by rbeckman-nextgen** [comment]
A bit more of the stack trace:

FATAL 2013-12-17 10:38:23,811 [6275e14e-b051-42cc-b244-246f6076defa_source_connector._fileEndpoint#1408054581.rec
eiver.1] org.mule.impl.DefaultComponentExceptionStrategy: The error is: 2: File not found: /
java.lang.Exception: 2: File not found: /
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:10
61)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:5
75)
	at java.lang.Thread.run(Thread.java:724)
Caused by: 2: File not found: /
	at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2297)
	at com.jcraft.jsch.ChannelSftp._stat(ChannelSftp.java:1750)
	at com.jcraft.jsch.ChannelSftp.cd(ChannelSftp.java:269)
	at com.mirth.connect.connectors.file.filesystems.SftpConnection.cwd(SftpConnection.java:165)
	at com.mirth.connect.connectors.file.filesystems.SftpConnection.listFiles(SftpConnection.java:135)
	at com.mirth.connect.connectors.file.FileMessageReceiver.listFiles(FileMessageReceiver.java:416)
	at com.mirth.connect.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:104)
	... 5 more


Imported Comment. Original Details:
Author: john-from-iora
Created: 2013-12-17T09:29:35.000-0800

**Comment by rbeckman-nextgen** [comment]
Ah.

The problem is that the entire remote path must be specified. Would be a nice one for pop-up help.


Imported Comment. Original Details:
Author: john-from-iora
Created: 2013-12-17T09:52:22.000-0800
