### ISSUE TITLE
PDF Writer gives NoClassDefFoundError when using Encrypted=Yes

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3024]
When using the options encrypted=Yes and Document type='PDF' with a Document Writer Destination in Mirth 3.0.1 (upgraded from 2.2.3) it gives the following error when running the channel:

( On Mirth version 2.2.3 there are no Errors, and the channel works correct.)

[2014-01-07 11:59:14,252]  ERROR (com.mirth.connect.donkey.server.channel.Channel:1020): Error processing message.
com.mirth.connect.donkey.server.channel.ChannelException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DEREncodable
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:979)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:177)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:154)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.processRecord(DatabaseReceiver.java:207)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.processResultSet(DatabaseReceiver.java:173)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.poll(DatabaseReceiver.java:122)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:141)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DEREncodable
	at com.mirth.connect.donkey.server.channel.Channel.handleDestinationChainThrowable(Channel.java:1497)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1424)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:955)
	... 8 moreCaused by: java.lang.NoClassDefFoundError: org/bouncycastle/asn1/DEREncodable
	at com.lowagie.text.pdf.PdfEncryption.<init>(Unknown Source)
	at com.lowagie.text.pdf.PdfWriter.setEncryption(Unknown Source)
	at com.lowagie.text.pdf.PdfStamper.setEncryption(Unknown Source)
	at com.lowagie.text.pdf.PdfStamper.setEncryption(Unknown Source)
	at com.lowagie.text.pdf.PdfEncryptor.encrypt(Unknown Source)
	at com.mirth.connect.connectors.doc.DocumentDispatcher.writeDocument(DocumentDispatcher.java:171)
	at com.mirth.connect.connectors.doc.DocumentDispatcher.send(DocumentDispatcher.java:105)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:588)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:336)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:224)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1422)
	... 9 moreCaused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.DEREncodable
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 20 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3110
Reporter: amc_cru
Created: 2014-01-07T04:24:32.000-0800

**Comment by rbeckman-nextgen** [comment]
Just to add a little bit more information... In addition to seeing the above error stack trace in the Server Log, the Document Writer will generate an invalid zero-length PDF file.

Also, IME, I can easily reproduce this bug 100% of the time when using encryption with a password.

Imported Comment. Original Details:
Author: ericb
Created: 2014-01-07T14:14:36.000-0800

**Comment by rbeckman-nextgen** [comment]
I think it is related to the latest version of iText not being compatible with the latest Bouncycastle. See http://sourceforge.net/mailarchive/message.php?msg_id=29107259

I solved it by replacing Bouncycastle 1.50 with 1.46. So replace bcprov-jdk15on-150.jar with bcprov-jdk15on-146.jar 

Imported Comment. Original Details:
Author: epfreed
Created: 2014-01-20T07:49:45.000-0800

**Comment by rbeckman-nextgen** [comment]
Due to MIRTH-2963, we can't revert BouncyCastle below bcprov-jdk15on-150.jar. One option is that we can still use iText + Flying Saucer to generate the PDF, but we can use a different library such as PDFBox to encrypt it. We appear to be using standard 128-bit encryption (not AES) and PDFBox seems to provide the same features.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-03-04T18:24:49.000-0800

**Comment by rbeckman-nextgen** [comment]
We are now using Apache PDFBox (which is compatible with the latest verion of BouncyCastle) to perform the encryption instead of iText. iText is still used to generate the original PDF.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-03-05T13:01:50.000-0800

**Comment by rbeckman-nextgen** [comment]
This only appears to work on Windows, not OSX/Linux.

Imported Comment. Original Details:
Author: narupley
Created: 2014-04-07T14:33:13.000-0700

**Comment by rbeckman-nextgen** [comment]
So what's happening is that it _**is**_ encrypting the PDF text/graphics groups, even on OSX/Linux. However if you look at the dictionaries, the permission flags are actually different:

2.2.3:
\\
{panel}﻿36 20 30 20 6F 62 6A 3C 3C 2F 55 20 28 30 A4 66 76 C4 FE 0B 59 5C 62 5C 5C D0 BC 97 B3 22 D8 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 29 2F 4C 65 6E 67 74 68 20 31 32 38 2F 56 20 32 2F 4F 20 28 3E 1B 2C 4F 88 CF 5E 7D 2E 20 37 FC C1 05 3C 74 85 DE B2 E9 9B D2 7C 72 69 FF 80 40 FD 5B 73 FE 29 {color:red}**2F 50 20 2D 31 38 33 36*{color} 2F 46 69 6C 74 65 72 2F 53 74 61 6E 64 61 72 64 {color:blue}*2F 52 20 33**{color} 3E 3E 0A 65 6E 64 6F 62 6A 0A{panel}

3.0.2:
\\
{panel}37 20 30 20 6F 62 6A 0A 3C 3C 0A 2F 46 69 6C 74 65 72 20 2F 53 74 61 6E 64 61 72 64 0A 2F 56 20 32 0A {color:blue}**2F 52 20 33 0A*{color} 2F 4C 65 6E 67 74 68 20 31 32 38 0A {color:red}*2F 50 20 2D 31 33 32 34 0A**{color} 2F 4F 20 3C 36 41 39 46 32 36 46 39 46 42 42 46 46 46 36 33 33 37 36 35 35 36 33 42 42 33 31 43 32 39 30 34 37 35 32 37 33 34 38 31 34 45 37 32 42 35 36 35 39 37 46 37 37 34 43 46 39 30 30 33 39 37 31 46 3E 0A 2F 55 20 3C 37 42 46 30 38 32 42 34 36 44 34 30 44 42 44 33 35 42 42 36 31 44 34 30 46 42 33 32 30 45 31 37 32 38 42 46 34 45 35 45 34 45 37 35 38 41 34 31 36 34 30 30 34 45 35 36 46 46 46 41 30 31 30 38 3E 0A 3E 3E 0A 65 6E 64 6F 62 6A 0A{panel}

Bold/red parts are the permissions sections. In 2.2.3 it shows -1836 (two's complement 100011010100 ~2~), but in 3.0.0 it shows -1324 (two's complement 101011010100 ~2~). From the [PDF 1.4 specifications](http://partners.adobe.com/public/developer/en/pdf/PDFReference.pdf), that 10th bit is:

> _(Revision 3 only)_ Extract text and graphics (in support of accessibility to disabled users or for other purposes).


Note that both libraries _are_ using R3 (sections indicated in bold/blue). So that can be fixed by passing in false for setCanExtractForAccessibility. However that's not the only problem.

In 2.x, we used the iText built-in classes to handle PDF encryption, and just passed in null for the owner password. However this did _not_ mean that an owner password wasn't being set. Behind the scenes, when null was passed in, the PdfEncryption class would actually generate a "random" password, based on the current time and JVM free memory. With PDFBox though, null means null (well, empty string actually), so by default we're always using an empty string for the owner password. What this means is that even though we're encrypting the PDF, it's trivial. Anybody can decrypt it without knowing the user password, because they know the owner password (or more accurately, the owner password is the same as the default "no-op" of an empty string). Only when _both_ the owner and user passwords are supplied is the file actually protected.

It looks like Adobe Reader just hides this fact, and always asks for a password if it detects an encryption dictionary, regardless of whether it needs it or not. However Preview on OSX and Document Viewer on Ubuntu (and probably the default PDF readers of all other Linux GUI distros) are more intelligent, and automatically decrypt the file for you when they can. So it _appeared_ to be an OS-related issue, but it was just coincidental because of the PDF reader applications that were used.

Imported Comment. Original Details:
Author: narupley
Created: 2014-04-07T15:56:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7123: Fixed bug (due to switching to PDFBox) that caused owner passwords to not be set anymore on encrypted PDFs. First, content extraction (for accessibility) is now set to false, the same as it was in 2.x. Second, we're now generating a pseudorandom owner password ourselves in the dispatcher, the same way as was being done in 2.x (internally in iText).

Imported Comment. Original Details:
Author: narupley
Created: 2014-04-07T16:30:16.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-10T18:56:28.000-0700
