### ISSUE TITLE
JMS Writer does not work anymore

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#303]
In Version 1.3.2 the JMS Writer could write a Message to my JMS Server (openJMS) but now in Version 1.4.0 i get always this error.
And i use the same Properties as in 1.3.2. I tried different things but nothing works. 

ERROR-407: JMS Connector error
ERROR MESSAGE:    Jms Error
org.mule.umo.transformer.TransformerException: null (java.lang.NullPointerException)
    at com.webreach.mirth.server.mule.providers.jms.transformers.AbstractJmsTransformer.transformToMessage(AbstractJmsTransformer.java:150)
    at com.webreach.mirth.server.mule.providers.jms.transformers.MessageObjectToJMSMessage.doTransform(MessageObjectToJMSMessage.java:32)
    at com.webreach.mirth.server.mule.providers.jms.JmsMessageDispatcher.dispatchMessage(JmsMessageDispatcher.java:118)
    at com.webreach.mirth.server.mule.providers.jms.JmsMessageDispatcher.doSend(JmsMessageDispatcher.java:244)
    at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
.....

Imported Issue. Original Details:
Jira Issue Key: MIRTH-286
Reporter: orlowjb3
Created: 2007-03-29T01:55:23.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed JMS dispatcher to set proper property on MOtoJMS transformer and correctly update message status.

Imported Comment. Original Details:
Author: chrisl
Created: 2007-04-19T19:37:52.000-0700
