### ISSUE TITLE
Web Service Sender Error: ouldn't create SOAP message due to exception: Unable to create StAX reader or writer

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3031]
Every now and then one or more channels which use the web service sender suddenly have every message resulting in an error. Usually we can workaround this by restarting the affected channels and reprocessing the ERRORED messages. But we have not yet been able to figure the steps required to reproduce the error.

The error and stacktrace is below:

{noformat}
Web Service Sender error
ERROR MESSAGE: Error invoking web service
com.sun.xml.internal.ws.protocol.soap.MessageCreationException: Couldn't create SOAP message due to exception: Unable to create StAX reader or writer
	at com.sun.xml.internal.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:348)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:254)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:203)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:122)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:95)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:626)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:585)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:570)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:467)
	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:308)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.doInvoke(DispatchImpl.java:177)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.invoke(DispatchImpl.java:203)
	at com.mirth.connect.connectors.ws.WebServiceDispatcher.send(WebServiceDispatcher.java:288)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:588)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:336)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:224)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1422)
	at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1524)
	at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1511)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.sun.xml.internal.ws.streaming.XMLReaderException: Unable to create StAX reader or writer
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory$Default.doCreate(XMLStreamReaderFactory.java:367)
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.doCreate(XMLStreamReaderFactory.java:193)
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.create(XMLStreamReaderFactory.java:143)
	at com.sun.xml.internal.ws.encoding.StreamSOAPCodec.decode(StreamSOAPCodec.java:290)
	at com.sun.xml.internal.ws.encoding.StreamSOAPCodec.decode(StreamSOAPCodec.java:118)
	at com.sun.xml.internal.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:343)
	... 19 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:219)
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(XMLStreamReaderImpl.java:189)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.getXMLStreamReaderImpl(XMLInputFactoryImpl.java:277)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:139)
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory$Default.doCreate(XMLStreamReaderFactory.java:365)
	... 24 more
{noformat}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3117
Reporter: daigoba66
Created: 2014-01-16T04:44:40.000-0800

**Comment by rbeckman-nextgen** [comment]
I mislabeled the database: it should be Postgres. This is Mirth running on a Virtual Appliance.

Imported Comment. Original Details:
Author: daigoba66
Created: 2014-01-16T04:45:33.000-0800

**Comment by rbeckman-nextgen** [comment]
Do you have anymore information about the behavior you are seeing? So far we are unable to reproduce this. Are you sure that all the messages will error until you restart the channel, and that it isn't an intermittent problem? Are you sure that all messages begin to send successfully again immediately after the channel?

One thing you could try is to enable the destination queue. That way if a message fails to send with this error, the message will be queued and will automatically retry until it is sent. If the queued messages continue to fail with the same error until the channel is restarted, then that could be an indication that there is a bug in the sender

Imported Comment. Original Details:
Author: wayneh
Created: 2014-03-07T14:48:59.000-0800

**Comment by rbeckman-nextgen** [comment]
After taking a closer look at the stack trace, it appears the problem was caused by this Java bug (https://bugs.openjdk.java.net/browse/JDK-8028111) which appeared in Java 7u45. It appears to have been fixed in Java 7u51 so updating your JRE should resolve the problem.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-03-18T13:27:57.000-0700
