### ISSUE TITLE
Mirth Connect 3.0.1 MySQL column alias trouble

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3038]
http://www.mirthcorp.com/community/forums/showthread.php?t=9896

I've added the following code template:

function getClientID(client) {

var dbConn = DatabaseConnectionFactory.createDatabaseConnection (
'com.mysql.jdbc.Driver',
'jdbc:mysql://' + globalMap.get('MySQLHost') + ":" + globalMap.get('MySQLPort') + '/labgw',
globalMap.get('MySQLUser'),
globalMap.get('MySQLPassword')
);

var selectClientIDQuery =
"SELECT id AS clients_id " +
"FROM clients " +
"WHERE client = '" + client + "' " +
"LIMIT 1;";

var selectClientIDQueryResult = dbConn.executeCachedQuery(selectClientIDQuery);
var client;

if (selectClientIDQueryResult.next()) {
// clientID = selectClientIDQueryResult.getString('clients_id');
clientID = selectClientIDQueryResult.getString('id');
}
else {
clientID = "";
}

return clientID;
}

...which is called in a test channel's Deploy Script as follows:

globalChannelMap.put('ClientId',getClientID('bopeep'));
return;

The channel deploys without error with the code template above. If, however, I uncomment the

// clientID = selectClientIDQueryResult.getString('clients_id');

...and comment the

clientID = selectClientIDQueryResult.getString('id');

I get the following error and the channel fails to deploy. No such failure occurs with Mirth Connect 2.2.1.5861.

What would have changed in the 3.0.1 MySQL JDBC driver to cause this?

[2014-01-17 17:27:03,772] ERROR (com.mirth.connect.server.util.javascript.JavaScri ptUtil:464): Error executing 1a81cb2f-0e41-41ae-ac40-d0bd12858699_Deploy script from channel: 1a81cb2f-0e41-41ae-ac40-d0bd12858699
com.mirth.connect.server.MirthJavascriptTransforme rException: SOURCE CODE:
186: 187:
var selectClientIDQueryResult = dbConn.executeCachedQuery(selectClientIDQuery);188 :
var client;189: 190:
if (selectClientIDQueryResult.next()) {191:

clientID = selectClientIDQueryResult.getString('clients_id'); 192: //

clientID = selectClientIDQueryResult.getString('id');193:
}194:
else {195:
clientID = "";LINE NUMBER:
191DETAILS:
Wrapped java.sql.SQLException: Invalid column name
at 1a81cb2f-0e41-41ae-ac40-d0bd12858699_Deploy:191 (getClientID)
at 1a81cb2f-0e41-41ae-ac40-d0bd12858699_Deploy:342 (doScript)
at 1a81cb2f-0e41-41ae-ac40-d0bd12858699_Deploy:345
at com.mirth.connect.server.util.javascript.JavaScrip tUtil.executeScript(JavaScriptUtil.java:489)
at com.mirth.connect.server.util.javascript.JavaScrip tUtil$2.call(JavaScriptUtil.java:343)
at java.util.concurrent.FutureTask$Sync.innerRun(Futu reTask.java:334)
at java.util.concurrent.FutureTask.run(FutureTask.jav a:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker( ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)Caused by: java.sql.SQLException: Invalid column name
at com.sun.rowset.CachedRowSetImpl.getColIdxByName(Ca chedRowSetImpl.java:1639)
at com.sun.rowset.CachedRowSetImpl.getString(CachedRo wSetImpl.java:2481)
at sun.reflect.GeneratedMethodAccessor36.invoke(Unkno wn Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(De legatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:601)
at org.mozilla.javascript.MemberBox.invoke(MemberBox. java:126)
at org.mozilla.javascript.NativeJavaMethod.call(Nativ eJavaMethod.java:225)
at org.mozilla.javascript.Interpreter.interpretLoop(I nterpreter.java:1473)
at org.mozilla.javascript.Interpreter.interpret(Inter preter.java:815)
at org.mozilla.javascript.InterpretedFunction.call(In terpretedFunction.java:109)
at org.mozilla.javascript.ContextFactory.doTopCall(Co ntextFactory.java:394)
at org.mozilla.javascript.ScriptRuntime.doTopCall(Scr iptRuntime.java:3110)
at org.mozilla.javascript.InterpretedFunction.exec(In terpretedFunction.java:120)
at com.mirth.connect.server.util.javascript.JavaScrip tTask.executeScript(JavaScriptTask.java:49)
at com.mirth.connect.server.util.javascript.JavaScrip tUtil.executeScript(JavaScriptUtil.java:484)
... 6 more 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3124
Reporter: jballou
Created: 2014-01-20T13:18:57.000-0800

**Comment by rbeckman-nextgen** [comment]
Note that this workaround appears to address the problem:

http://bugs.mysql.com/bug.php?id=40256

> Suggested fix:
> force the driver url to have useOldAliasMetadataBehavior as true (which has default value of false in v5.1.6)
>
> ex :
> url = "jdbc:mysql://localhost:3306/mydb?useOldAliasMetadataBehavior=true" 

Imported Comment. Original Details:
Author: jballou
Created: 2014-01-21T07:53:25.000-0800

**Comment by rbeckman-nextgen** [comment]
> Suggested fix:
> force the driver url to have useOldAliasMetadataBehavior as true (which has default value of false in v5.1.6)
>
> ex :
> url = "jdbc:mysql://localhost:3306/mydb?useOldAliasMetadataBehavior=true" 

So is this SOP for Mirth 3.0.1/MySQL 5.1.X?

Upgrading Java to 1.7.0_51 as suggested at the following didn't resolve the problem:

http://stackoverflow.com/questions/15184709/cachedrowsetimpl-getstring-based-on-column-label

Can anyone confirm this is the related bug?

http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=7046875

Imported Comment. Original Details:
Author: jballou
Created: 2014-01-23T09:19:09.000-0800

**Comment by rbeckman-nextgen** [comment]
Thanks Justin for doing most of the initial legwork for this issue. 

We've determined that since MySQL's behavior is JDBC compliant, it should not be necessary to specify "useOldAliasMetadataBehavior" in the connection string. We've decided to create a subclass of CachedRowSetImpl as described in http://stackoverflow.com/questions/15184709/cachedrowsetimpl-getstring-based-on-column-label, so DatabaseConnection now returns a MirthCachedRowSet instead of CachedRowSetImpl. When 3.0.2 is released, you should be able to safely remove the "useOldAliasMetadataBehavior=true" section of the connection string and the alias will still work. Even if you forget to edit the connection string, your Javascript code should still continue to work.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-03-31T13:37:19.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that the MirthCachedRowSet has been added and works as expected. Also when you call executeCachedQuery, etc. on a DatabaseConnection object, that will also return the new object.

However, note that this will **not** apply if you call dbConn.getConnection() to get the underlying java.sql.Connection object, and then create manual cached row sets / hashtables from that using your own prepared statements or calls. If your JavaScript doing that, you'll still need that URL parameter.

Imported Comment. Original Details:
Author: narupley
Created: 2014-04-02T12:50:40.000-0700
