### ISSUE TITLE
"Failed to process row retrieved from database error" not registering as an error on channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3039]
I have a database reader channel that's been throwing the error pasted below for each row it retrieves.
While I'm not sure what the illegal character is as this channel was working,  the errors are not included on the channel error count, so I missed them.

Thanks

------

[2014-01-21 08:04:14,990]  ERROR (com.mirth.connect.connectors.jdbc.DatabaseReceiver:212): Failed to process row retrieved from the database in channel "Test N95V2  Employee Notifier"
org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at org.apache.xerces.dom.CoreDocumentImpl.createElement(Unknown Source)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.resultMapToXml(DatabaseReceiver.java:240)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.processRecord(DatabaseReceiver.java:207)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.processResultSet(DatabaseReceiver.java:173)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.poll(DatabaseReceiver.java:122)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:141)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3125
Reporter: bostad
Created: 2014-01-21T05:32:27.000-0800

**Comment by rbeckman-nextgen** [comment]
Ideally, this should never happen. The Database Reader _should_ be able to take any valid ResultSet and convert it into XML. If an exception gets thrown from `resultMapToXML`, it should be considered a flaw in our code, not a problem with the user's query (though the latter may still be true). If the issue is that a particular column contains characters that are invalid XML (for example, anything less than 0x20 excluding 0x09/0x0A/0x0D), we should detect that ahead of time and perhaps automatically encode the column in Base64 (add an encoding attribute too).

Imported Comment. Original Details:
Author: narupley
Created: 2014-01-21T06:44:05.000-0800

**Comment by rbeckman-nextgen** [comment]
By any chance are you connecting to an external SQL Server database? If so, it is likely the same issue as MIRTH-1071. If not, could you describe the table you are reading from, particularly what column types are included in the SELECT?

Thanks

Imported Comment. Original Details:
Author: brentm
Created: 2014-02-03T09:50:31.000-0800

**Comment by rbeckman-nextgen** [comment]
Solution is.... returned fields data type should be char/varchar. No Integer/Double/Float/DateTime etc. cast/convert Non-Char fields.
It worked for me.

Imported Comment. Original Details:
Author: rbarot
Created: 2014-03-31T04:29:16.000-0700

**Comment by rbeckman-nextgen** [comment]
@Nick I was able to reproduce this and it seems to be an issue with specific column names when they are quoted.  I think the case that fails is if the column has an underscore and ends with a number.  

For instance this +works+:  > SELECT TOP 1 [isa01] FROM myTable

But this will raise the +error+ mentioned: > SELECT TOP 1 [2100A_nm103] FROM myTable

However this +works+:  > SELECT TOP 1 2100A_nm103 FROM myTable


The third example should show that the column is a supported type and that it's a column name issue.  But these are the data types
{quote}  CREATE TABLE myTable ([isa01] CHAR(10), [2100A_nm103] VARCHAR(40))
  INSERT INTO myTable ([isa01], [2100A_nm103]) VALUES ('00','Aetna'){quote}


Imported Comment. Original Details:
Author: kevinfosterng
Created: 2017-05-10T14:21:14.000-0700

**Comment by rbeckman-nextgen** [comment]
Actually it's probably because your column name _starts_ with a number. The corresponding XML tag <2100A_nm103> is invalid according to the parser (and probably the XML specifications). In this case we should probably append an underscore to the beginning of the tag name to prevent that.

Since this issue is very old and I don't think it's exactly the same as what you've encountered (even if the end result is the same error stacktrace), go ahead and create a new issue for it.

Imported Comment. Original Details:
Author: narupley
Created: 2017-05-10T14:27:21.000-0700
