### ISSUE TITLE
Importing a transformer into a destination does not reconcile the source outbound data type

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3067]
If you import a transformer into a destination connector and the inbound data type is different than the source outbound, no auto-reconciliation is done (like automatically switching it to the source outbound, prompting the user, etc.). If you deploy the channel that particular destination will actually use the inbound data type that was imported, rather than the source outbound.

In addition, you can observe irregularities or exceptions in the Administrator, because the data type table nodes are expecting different property groups than what may or may not exist for the data type plugin. For example, if you have a channel where all data types are Raw, and you import a destination transformer that has an inbound data type of HL7 v2.x, and then attempt to select the destination in the Set Data Types dialog, the client will throw the following:
\\
\\
`Exception in thread "AWT-EventQueue-2" java.lang.NullPointerException
	at com.mirth.connect.client.ui.DataTypePropertiesTableNode.isDefaultProperty(DataTypePropertiesTableNode.java:146)
	at com.mirth.connect.client.ui.DataTypePropertiesTableModel.isDefaultProperties(DataTypePropertiesTableModel.java:193)
	at com.mirth.connect.client.ui.DataTypePropertiesTableModel.isDefaultProperties(DataTypePropertiesTableModel.java:199)
	at com.mirth.connect.client.ui.DataTypePropertiesTableModel.isDefaultProperties(DataTypePropertiesTableModel.java:199)
	at com.mirth.connect.client.ui.DataTypePropertiesPanel.updateDefaultButton(DataTypePropertiesPanel.java:207)
	at com.mirth.connect.client.ui.DataTypePropertiesPanel.setDataTypeProperties(DataTypePropertiesPanel.java:260)
	at com.mirth.connect.client.ui.DataTypePropertiesPanel.setDataTypeProperties(DataTypePropertiesPanel.java:240)
	at com.mirth.connect.client.ui.DataTypesDialog$6.valueChanged(DataTypesDialog.java:446)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:154)
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(DefaultListSelectionModel.java:685)
	at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(BasicTableUI.java:953)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(BasicTableUI.java:1166)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at org.jdesktop.swingx.JXTreeTable.processMouseEvent(JXTreeTable.java:396)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:154)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:182)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:221)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:219)
	at java.awt.Dialog.show(Dialog.java:1082)
	at java.awt.Component.show(Component.java:1651)
	at java.awt.Component.setVisible(Component.java:1603)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at com.mirth.connect.client.ui.DataTypesDialog.<init>(DataTypesDialog.java:120)
	at com.mirth.connect.client.ui.ChannelSetup.changeDataTypesButtonActionPerformed(ChannelSetup.java:2659)
	at com.mirth.connect.client.ui.ChannelSetup.access$900(ChannelSetup.java:85)
	at com.mirth.connect.client.ui.ChannelSetup$9.actionPerformed(ChannelSetup.java:1636)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6505)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3154
Reporter: narupley
Created: 2014-02-20T15:59:39.000-0800

**Comment by rbeckman-nextgen** [comment]
This bug SUCKS!

Imported Comment. Original Details:
Author: stickybandit
Created: 2014-02-20T16:11:51.000-0800

**Comment by rbeckman-nextgen** [comment]
When importing a transformer into a destination connector, if the imported inbound data type does not match the existing inbound data type, the inbound data type and inbound properties will no longer be overwritten. If the imported and existing data type matches, then the inbound properties WILL be overwritten.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-03-04T15:31:32.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified that this issue no longer occurs.

Imported Comment. Original Details:
Author: narupley
Created: 2014-04-02T11:16:43.000-0700
