### ISSUE TITLE
Allow parallelization of message processing through a single channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3079]
Currently only one message can process through a channel. This is by design  for things like message order preservation and the serial nature of the global channel map.

However, this can severely hamper message throughput for channels that don't actually _need_ message order or any other benefits that the "single message conduit" paradigm might bring. Especially for "stateless" Web Service / HTTP Listener channels, requests tend to be mutually exclusive and don't necessarily need to be ordered in any specific way. This can be true for HL7 interfaces as well, particularly for servers that accept QRY messages and return a set of results (immunizations, syndromic surveillance, etc.). In 2.x, the parallelization part existed when unsynchronizing a channel, but you couldn't actually respond from a destination or custom response.

So in essence, this feature would provide some way for multiple messages to process through a channel at the same time. Obviously certain sacrifices would have to be made:
* Message order is not guaranteed. So a message that was received first is not guaranteed to be sent out first, and the associated response is not guaranteed to be sent back to the source first. Also, depending on how this is implemented, the overall message ID may not accurately reflect the true order of messages as they were received by the channel.
* Collisions and overwriting of shared memory (like things stored in the global or global channel maps) could happen across different messages, without appropriate checks. With the current structure, if a counter is kept in the global channel map, then it's guaranteed to be accurate across multiple messages. However that would no longer be true.
* Scripts for different messages can be running at the same time, and in indeterminate order. So for example if you are using a transformer to call out to a database, you should expect that multiple instances of the same transformer could be doing that at the same time. Any queries/updates/etc. should be written appropriately to prevent deadlocks or other problems.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3167
Reporter: narupley
Created: 2014-03-03T08:42:06.000-0800

**Comment by rbeckman-nextgen** [comment]
Here's one of the more recent forum threads regarding this issue, though there have been several in the past, and also people on IRC talking about it.

[http://www.mirthcorp.com/community/forums/showthread.php?p=37933#post37933]

Imported Comment. Original Details:
Author: narupley
Created: 2014-03-04T09:49:53.000-0800

**Comment by rbeckman-nextgen** [comment]
I would find this very useful indeed.  I'm currently developing a channel to receive an HL7 QBP-Q21 message and respond with RSP-K21.  It's not passing the messages on, just using the inbound message to perform a database query and respond.  I do not care about message order in this scenario, just want to allow multiple connections and have multiple queries being processed at one time.

The same logic would apply to a web service channel that I set up some time ago that is basically doing a database look up and returning a response.

kind regards,
Simon

Imported Comment. Original Details:
Author: seaston
Created: 2014-04-17T04:57:21.000-0700

**Comment by rbeckman-nextgen** [comment]
In my use case I have many (up to 100) senders sending to a single channel via a TCP Listener. The TCP Listener is set to respond after processing. I'd like to preserve order for messages from a particular connection, but not necessarily between connections. So the ideal for me would be a thread per connection.

Imported Comment. Original Details:
Author: dgtombs
Created: 2014-08-13T07:45:46.000-0700

**Comment by rbeckman-nextgen** [comment]
One thread per connection was actually the MC v2 behavior, right? So this pure single-threading issue is new in MC v3?

Imported Comment. Original Details:
Author: dgtombs
Created: 2014-08-13T08:21:39.000-0700

**Comment by rbeckman-nextgen** [comment]
It was and still _**is**_ one thread per connection. It's just that when it comes time to dispatch a message through the channel, a synchronization block only allows one thread to get in at any given time.

In 2.x, the synchronization was only done at the destination dispatcher. So multiple threads could process through the preprocessor, source filter/transformer, and destination filter/transformer, but when it came time to send the message, that's when only one thread was allowed. In 3.x it's essentially the same, except that the synchronization is done around the entire message lifecycle (basically from the preprocessor to the postprocessor). That's done for preservation of message order, and to ensure that filters/transformers/scripts are thread-safe.

In 2.x you could turn off the "Synchronized" option on a channel, and then multiple threads _would_ be able to process asynchronously even at the point of destination dispatch. However the internal Mule worker thread cap was 10, so at most 10 threads could be running concurrently. However that really only "worked" for JavaScript Writers, because multiple threads would spin up multiple Rhino contexts anyway, so it was "by accident" thread-safe. That was not true for other destination connectors though like the LLP Sender. If you tried to use an LLP Sender on an unsynchronized channel, you would likely run into all sorts of weird issues.

Imported Comment. Original Details:
Author: narupley
Created: 2014-08-13T08:34:57.000-0700

**Comment by rbeckman-nextgen** [comment]
OK, thanks for the explanation.

The net result for my above use case, though, is that in 2.x message order was preserved as much as I needed it to be and yet I was able to get messages through the filters/transformers concurrently. But now in 3.x all message processing through filters/transformers is synchronous. Based on my load test measurements, this results in about 1/5 the throughput as before.

Imported Comment. Original Details:
Author: dgtombs
Created: 2014-08-13T11:16:42.000-0700

**Comment by rbeckman-nextgen** [comment]
Yeah that sounds about right, unfortunately. We now have multiple destination queue threads, but that doesn't really help if you want to run the filters/transformers concurrently and if you want to preserve order within a single TCP Listener connection.

Imported Comment. Original Details:
Author: narupley
Created: 2014-08-13T11:24:00.000-0700

**Comment by rbeckman-nextgen** [comment]
Would this issue cover that feature request or shall I open another?

Imported Comment. Original Details:
Author: dgtombs
Created: 2014-08-13T14:07:18.000-0700

**Comment by rbeckman-nextgen** [comment]
What specific feature are you referring to? If it's the ability to run filters/transformers concurrently then yes, this issue would satisfy that.

Imported Comment. Original Details:
Author: narupley
Created: 2014-08-13T14:10:36.000-0700

**Comment by rbeckman-nextgen** [comment]
To be specific: the ability to run filters/transformers concurrently but preserve order within a single TCP connection.

Imported Comment. Original Details:
Author: dgtombs
Created: 2014-08-14T05:00:40.000-0700

**Comment by rbeckman-nextgen** [comment]
My use case is a bit different but parallelization would be great. For now, using version 2 of Mirth, I have two strategies: one is to have n channels cloned, each one with a different TCP port and a load-balancer in front, like HAproxy. The other is to implement "asynchronous" Javascript transformers that run on different threads. With this approach, the channel receives a message and immediately sends a response (automatic) and then the "asynchronous" process sends the application ack/response. Of course, all messages are marked as SENT and you have to access the database directly and update status, for instance. No postprocessor, also.

Imported Comment. Original Details:
Author: santosam
Created: 2014-11-21T08:34:36.000-0800

**Comment by rbeckman-nextgen** [comment]
[http://www.mirthcorp.com/community/forums/showthread.php?t=12476]

Imported Comment. Original Details:
Author: narupley
Created: 2014-12-16T09:10:13.000-0800

**Comment by rbeckman-nextgen** [comment]
[http://www.mirthcorp.com/community/forums/showthread.php?t=13272]

Imported Comment. Original Details:
Author: narupley
Created: 2015-03-12T07:39:10.000-0700

**Comment by rbeckman-nextgen** [comment]
This channel feature could be a checkbox in the channel editor that says  'Asynchronous' instead of the terms I put in MIRTH-3675 (duplicate).
And when it is checked a popup window shows the Mirth Connect user the help information and safety measures required when using this feature.


Imported Comment. Original Details:
Author: stickybandit
Created: 2015-03-24T10:21:36.000-0700

**Comment by rbeckman-nextgen** [comment]
[http://www.mirthcorp.com/community/forums/showthread.php?t=16487]

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-23T15:45:59.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7888: Channels now allow parallel message processing across multiple threads. A new feature, the maximum processing threads, has been added to the source connector settings. This determines the maximum number of "main message processing" threads to allow. By default and on migration it will be 1, which means that everything will behave exactly as it does currently. However if you set that value to something greater than 1, then messages coming from different sources can now process simultaneously. The channel process lock is now a semaphore, with a configurable number of permits. So if the permits are set to 2, then the first two dispatch threads will be able to process, but all others will block until one of the two permits is available.

Imported Comment. Original Details:
Author: narupley
Created: 2016-01-20T18:29:21.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 7908: When using the source queue this feature would have been useless, since there was only one thread polling and processing from it. Therefore, we added the ability for the source queue to poll in multiple threads as well. When the max processing threads is greater than zero and the source queue is on, there will be multiple queue consumers all processing messages through the channel. The source queue now has a set of "checked out" message IDs similar to the destination queue, to prevent the same message being polled in multiple threads.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-05T17:38:30.000-0800

**Comment by rbeckman-nextgen** [comment]
For testing it's important to test all places in the main message processing thread that were single-threaded but now can run simultaneously:

* Batch adaptors
* Attachment handlers
* Preprocessor
* Source Filter / Transformer
* Destination Filter / Transformer (should already be since it can be used in multiple queue threads)
* Postprocessor

Also should test out multiple destination chains. Both source queuing and destination queuing should be tested, since now there are multiple possible producers and consumers for every queue.

Imported Comment. Original Details:
Author: narupley
Created: 2016-03-30T09:45:06.000-0700

**Comment by rbeckman-nextgen** [comment]
rev 7978 - Found issue with source queue parallelization.

Since we depend on the in memory buffer for queued messages there is an inconsistency filling the queue buffer and processing messages that can lead to duplicate messages being processed. 

SourceConnector.poll() is synchronized but a message can be picked up for processing and another thread can enter this method and require that fillBuffer() be called. If the buffer is filled while while a message is currently being processed then the database has no way of knowing that the message is currently "checked out" by the source connector. The message will be added to the source queue buffer again. If the checked out message finishes and is removed from the checkedOut set before the buffer iterator finds it again then it will be processed again. 

This is kind of hard to read but the idea in this case is that messages 176901 and 176902 are checked out and the buffer is filled while they are checked out. Shortly after the messages are removed from checked out.
`
ERROR 2016-04-06 15:22:27,402 [Source Queue Thread 13 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176902 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,402 [Source Queue Thread 13 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176902
ERROR 2016-04-06 15:22:27,414 [Source Queue Thread 20 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176883
ERROR 2016-04-06 15:22:27,414 [Source Queue Thread 20 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176901 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,414 [Source Queue Thread 20 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176901
ERROR 2016-04-06 15:22:27,447 [Source Queue Thread 8 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176881
ERROR 2016-04-06 15:22:27,447 [Source Queue Thread 8 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176900 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,447 [Source Queue Thread 8 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176900
ERROR 2016-04-06 15:22:27,457 [Source Queue Thread 10 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176882
ERROR 2016-04-06 15:22:27,457 [Source Queue Thread 10 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176899 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,457 [Source Queue Thread 10 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176899
ERROR 2016-04-06 15:22:27,509 [Source Queue Thread 3 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176880
ERROR 2016-04-06 15:22:27,509 [Source Queue Thread 3 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176898 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,509 [Source Queue Thread 3 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176898
ERROR 2016-04-06 15:22:27,794 [Source Queue Thread 12 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176879
ERROR 2016-04-06 15:22:27,794 [Source Queue Thread 12 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FILLING BUFFER
ERROR 2016-04-06 15:22:27,945 [Source Queue Thread 12 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176884 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,946 [Source Queue Thread 12 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176884
ERROR 2016-04-06 15:22:27,971 [Source Queue Thread 20 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176901
ERROR 2016-04-06 15:22:27,971 [Source Queue Thread 20 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176885 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,971 [Source Queue Thread 20 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176885
ERROR 2016-04-06 15:22:27,971 [Source Queue Thread 13 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176902
`

When the buffer iterator returns the message again we see that it has actually been processed by the source queue before but it has no way of knowing that it has already been processed in the current implementation.

`
ERROR 2016-04-06 15:22:27,974 [Source Queue Thread 6 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176901 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,974 [Source Queue Thread 6 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176901
ERROR 2016-04-06 15:22:27,974 [Source Queue Thread 6 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: MESSAGE ID: 176901 ALREADY HAS BEEN PROCESSED BY SOURCE QUEUE
ERROR 2016-04-06 15:22:27,983 [Source Queue Thread 7 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: CONNECTOR MESSAGE BEING REMOVED FROM CHECKED OUT: 176877
ERROR 2016-04-06 15:22:27,983 [Source Queue Thread 7 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.queue.SourceQueue: FOUND CONNECTOR MESSAGE IN QUEUE 176902 CHECKED OUT CONTAIN RESULT: false
ERROR 2016-04-06 15:22:27,983 [Source Queue Thread 7 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: QUEUED THREAD POLLING MESSAGE: 176902
ERROR 2016-04-06 15:22:27,983 [Source Queue Thread 7 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: MESSAGE ID: 176902 ALREADY HAS BEEN PROCESSED BY SOURCE QUEUE
`

Errors you would see:
`
ERROR 2016-04-06 15:22:28,487 [Source Queue Thread 6 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: An error occurred in channel TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8) while processing message ID 176901 from the source queue
com.mirth.connect.donkey.server.data.DonkeyDaoException: Failed to insert connector message meta data
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMetaData(JdbcDao.java:525)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:114)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:85)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:67)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1657)
	at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1794)
	at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1774)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "d_mcm21_pkey"
  Detail: Key (message_id, metadata_id)=(176901, 0) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMetaData(JdbcDao.java:522)
	... 7 more
ERROR 2016-04-06 15:22:28,494 [Source Queue Thread 7 on TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8)] com.mirth.connect.donkey.server.channel.Channel: An error occurred in channel TCP Listener Batch 7004 (2591f75f-563d-4752-952b-a589906d69e8) while processing message ID 176902 from the source queue
com.mirth.connect.donkey.server.data.DonkeyDaoException: Failed to insert connector message meta data
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMetaData(JdbcDao.java:525)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:114)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:85)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:67)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1657)
	at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1794)
	at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1774)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "d_mcm21_pkey"
  Detail: Key (message_id, metadata_id)=(176902, 0) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:420)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:366)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeUpdate(PreparedStatementProxy.java:61)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMetaData(JdbcDao.java:522)
	... 7 more
`

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-04-06T16:22:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed the above bug. When finish is called the source queue will now always remove the message from the buffer.

Imported Comment. Original Details:
Author: narupley
Created: 2016-04-06T17:22:25.000-0700

**Comment by rbeckman-nextgen** [comment]
Nice.  Interested to use this feature ASAP.

Imported Comment. Original Details:
Author: stickybandit
Created: 2016-04-07T08:41:43.000-0700

**Comment by rbeckman-nextgen** [comment]
rev 7982 - Destination queue depend on the in memory buffer to have messages put in it with messageId in order of insertion. Now that we have multiple threads generating message ids it is now possible to put a higher message id after a lower one. Looking into this.

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-04-07T17:13:02.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7986: Made tweak to the destination queue to more correctly handle rotation now that we allow multiple processing threads. Now that there are multiple simultaneous producers for the destination queue, it's possible that messages can be added to the buffer out of order (which is fine). This really only matters for rotation because we used the message IDs to determine when to sleep for the retry interval in the queue thread. Now instead of just checking the last message ID, we also go directly to the queue and check whether the current thread ID is flagged for rotation. This is done by the queue data source when the rotation actually occurs.

Because messages by multiple producers can be out of order, it's possible that a message with a higher ID can be committed to the database first. For queues with rotation on, this means that there can be bursts of smaller queries to grab messages _earlier_ than that first one. Overall this should be fine, since once those messages finish the max message ID will again be set and the next batch of messages will be retrieved.

Imported Comment. Original Details:
Author: narupley
Created: 2016-04-08T19:02:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Another addendum to the above, in r7992. Made optimizations to how the destination queue handles rotation, so that bursts of small buffer queries are avoided when using multiple processing threads. The reason this happens is because when multiple processing threads are used, messages can be added to the queue out of order. So it's possible that a high message ID is added first, setting the max message ID. Then even if no message has been returned to the queue, the buffer select is still being unnecessarily limited by the max message ID, when it should really only matter when rotateQueue is actually called.

Now, the max message ID is only set when a message gets returned to the queue (the minimum ID is also set at this time). When the rotation actually occurs, the min/max IDs are reset, starting the cycle over.

Imported Comment. Original Details:
Author: narupley
Created: 2016-04-12T15:54:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Looks like the commit from rev 7987 can have some negative effects on the destination queue buffer when using thread assignment variables. The size of the queue will be slightly higher than the buffer size and if none of the messages currently in the buffer match the thread assignment variable then it will fill the buffer. This is the expected optimization but in the case where there is a queue building up, large number of threads and values in the same magnitude as threads...you can end up calling fillBuffer() hundreds of times within a couple seconds. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-04-12T17:46:17.000-0700

**Comment by rbeckman-nextgen** [comment]
Reverted the optimization mentioned above.

Imported Comment. Original Details:
Author: narupley
Created: 2016-04-12T17:59:23.000-0700

**Comment by rbeckman-nextgen** [comment]
rev 7996 - Confirmed that the above issues have all been resolved. This feature adds a good amount of complexity to mirth connect so it would be good to read through all the info in this ticket when using this feature. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-04-14T12:57:12.000-0700

**Comment by rbeckman-nextgen** [comment]
There may be a lot of complexity, but I was hoping a user could keep it simple by just the following...
a) I want parallel processing for this channel.
b) I don't care about order
c) I don't rely on dynamic values in the global map or the global channel map.
d) I want full flow rather than queued messages.

Imported Comment. Original Details:
Author: stickybandit
Created: 2016-04-15T08:51:02.000-0700
