### ISSUE TITLE
Not able to use certain Java objects in JavaScript conditional expressions

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3080]
Try the following in a 2.x preprocessor:
\\
\\
`logger.info(typeof messageObject);`

It outputs "undefined", as expected. However in 3.x it will now throw an error:
\\
\\
`[2014-03-03 09:09:23,887]  ERROR (com.mirth.connect.server.util.javascript.JavaScriptUtil:464): Error executing Preprocessor script from channel: 880e07cc-0729-42c5-a146-29c4b3253f9c
com.mirth.connect.server.MirthJavascriptTransformerException: SOURCE CODE:
	187:     }188: }189: function doScript() {190: // Modify the message variable below to pre process data191: 192: logger.info(typeof messageObject);193: 194: return message; 195: }LINE NUMBER:
	192DETAILS:
	Invalid JavaScript value of type com.mirth.connect.server.userutil.MessageObject
	at 880e07cc-0729-42c5-a146-29c4b3253f9c_Preprocessor:192 (doScript)
	at 880e07cc-0729-42c5-a146-29c4b3253f9c_Preprocessor:196
	at com.mirth.connect.server.util.javascript.JavaScriptUtil.executeScript(JavaScriptUtil.java:489)
	at com.mirth.connect.server.util.javascript.JavaScriptUtil.executePreprocessorScripts(JavaScriptUtil.java:183)
	at com.mirth.connect.server.transformers.JavaScriptPreprocessor$JavaScriptPreProcessorTask.call(JavaScriptPreprocessor.java:57)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)`
\\
\\
In addition, try this code:
\\
\\
`if (messageObject)
	logger.info('messageObject exists');`

In 2.x, it throws an error:
\\
\\
`[2014-03-03 09:14:51,142]  ERROR (com.mirth.connect.server.util.JavaScriptUtil:264): Error executing Preprocessor script from channel: faf8272e-b76d-4cd6-984f-55b23cdb21de
com.mirth.connect.server.MirthJavascriptTransformerException: SOURCE CODE:
	1: String.prototype.trim = function() { return this.replace(/^\s+](\s+$/g,"").replace(/^\t+|\t+$/g,""); };function $(string) { if (globalChannelMap.containsKey(string)) { return globalChannelMap.get(string);} else if (globalMap.containsKey(string)) { return globalMap.get(string);} else { return ''; `function addAttachment(data, type) {var attachment = Packages.com.mirth.connect.server.controllers.MessageObjectController.getInstance().createAttachment(data, type);muleContext.getProperties().get('attachments').add(attachment); 2: return attachment; }3: function $gc(key, value){if (arguments.length == 1){return globalChannelMap.get(key); }else if (arguments.length == 2){globalChannelMap.put(key, value); `function $g(key, value){if (arguments.length == 1){return globalMap.get(key); }else if (arguments.length == 2){globalMap.put(key, value); `function doScript() {4: // Modify the message variable below to pre process data5: if (messageObject)6: 
	logger.info('messageObject exists');7: return message; 8: }LINE NUMBER:
	5DETAILS:
	ReferenceError: "messageObject" is not defined.
	at faf8272e-b76d-4cd6-984f-55b23cdb21de_Preprocessor:5 (doScript)
	at faf8272e-b76d-4cd6-984f-55b23cdb21de_Preprocessor:9
	at com.mirth.connect.server.util.JavaScriptUtil.executeScript(JavaScriptUtil.java:289)
	at com.mirth.connect.server.util.JavaScriptUtil.executePreprocessorScripts(JavaScriptUtil.java:166)
	at com.mirth.connect.server.mule.transformers.JavaScriptPreprocessor.transform(JavaScriptPreprocessor.java:40)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:225)
	at com.mirth.connect.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:222)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:97)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Thread.java:724)`

However in 3.x you now get warnings from Rhino:
\\
\\
`[2014-03-03 09:14:40,233)  ERROR (Server:146): RHINO USAGE WARNING: Missed Context.javaToJS() conversion:
[2014-03-03 09:14:40,233]  ERROR (Server:146): Rhino runtime detected object message 9-0 (RECEIVED) of class com.mirth.connect.server.userutil.MessageObject where it expected String, Number, Boolean or Scriptable instance. Please check your code for missing Context.javaToJS() call.`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3168
Reporter: narupley
Created: 2014-03-03T09:14:35.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 7097: Fixed bug that caused JavaScript operators (like == or typeof) to not work with Java objects under certain conditions. Now, all Java objects placed in JavaScript contexts are first wrapped using Context.javaToJS. This has no effect on certain objects like strings/numbers, but in general a Java object will be wrapped in a NativeJavaObject, which will then be used in the actual scope. This should have no effect on existing channel code, except that certain expressions that _would_ have thrown an exception or logged a warning will no longer do that.

Imported Comment. Original Details:
Author: narupley
Created: 2014-03-12T16:04:29.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-10T19:42:07.000-0700
