### ISSUE TITLE
Channel start task is called even when the channel is paused

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3116]
When a channel's start() method is called, it always submits a StartTask. However even if the current channel state is PAUSED instead of STOPPED, it will go through all the normal start stuff as if the channel was stopped. This happens to not be an issue most of the time because we check specific connector states before calling start() on them. However it can definitely cause issues when using the source queue.

Create a channel that uses the source queue, and feed it messages faster than it can process them. Then pause the channel, so that the source queue thread is still running. On a separate Administrator that thinks the channel is stopped, attempt to start the channel. Instead of submitting a ResumeTask, a StartTask is submitted instead, and a _second_ source queue thread is actually started up. Aside from obvious message order concerns, this also causes SQL exceptions:
\\
`ERROR 2014-03-24 09:44:14,146 [Thread-33] com.mirth.connect.donkey.server.channel.Channel: An error occurred in channel test (98764927-a0e9-4a58-8933-00889b0b9ae5) while processing message ID 44 from the source queue
com.mirth.connect.donkey.server.data.DonkeyDaoException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO D_MC1 (METADATA_ID, MESSAGE_ID, CONTENT_TYPE, CONTENT, DATA_TYPE, IS_ENCRYPTED)
		VALUES ('0', '44', '2', 'dummy', 'HL7V2', '0') was aborted.  Call getNextException to see the cause.
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.executeBatchInsertMessageContent(JdbcDao.java:219)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:100)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:56)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1394)
	at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1528)
	at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1515)
	at java.lang.Thread.run(Thread.java:680)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO D_MC1 (METADATA_ID, MESSAGE_ID, CONTENT_TYPE, CONTENT, DATA_TYPE, IS_ENCRYPTED)
		VALUES ('0', '44', '2', 'dummy', 'HL7V2', '0') was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2619)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2752)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.executeBatchInsertMessageContent(JdbcDao.java:217)
	... 7 more`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3204
Reporter: narupley
Created: 2014-03-24T10:03:42.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7106: Fixed bug that caused start tasks to actually get executed if the current channel state is PAUSED. Now, channels are only started via StartTask if the current state is STOPPED. If a channel is paused, a ResumeTask should be sent instead.

Imported Comment. Original Details:
Author: narupley
Created: 2014-03-24T12:23:01.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-10T17:05:15.000-0700
