### ISSUE TITLE
No longer able to sort on the dashboard status column

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3123]
Most likely because of the new tree table. This is what occurs:
\\
`Exception in thread "AWT-EventQueue-2" java.lang.ClassCastException: com.mirth.connect.client.ui.CellData cannot be cast to java.lang.Comparable
	at com.mirth.connect.client.ui.AbstractSortableTreeTableNode$Row.checkAndSetColumnType(AbstractSortableTreeTableNode.java:232)
	at com.mirth.connect.client.ui.AbstractSortableTreeTableNode$Row.<init>(AbstractSortableTreeTableNode.java:220)
	at com.mirth.connect.client.ui.AbstractSortableTreeTableNode.sort(AbstractSortableTreeTableNode.java:178)
	at com.mirth.connect.client.ui.SortableTreeTableModel.doSort(SortableTreeTableModel.java:323)
	at com.mirth.connect.client.ui.SortableTreeTableModel.doFullSort(SortableTreeTableModel.java:291)
	at com.mirth.connect.client.ui.SortableTreeTableModel.sort(SortableTreeTableModel.java:163)
	at com.mirth.connect.client.ui.SortableTreeTableModel.setKeys(SortableTreeTableModel.java:276)
	at com.mirth.connect.client.ui.SortableTreeTableModel.setColumnAndToggleSortOrder(SortableTreeTableModel.java:383)
	at com.mirth.connect.client.ui.DashboardPanel$4.mouseClicked(DashboardPanel.java:234)
	at java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:270)
	at java.awt.Component.processMouseEvent(Component.java:6508)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3320)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4501)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:735)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:694)
	at java.awt.EventQueue$3.run(EventQueue.java:692)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:708)
	at java.awt.EventQueue$4.run(EventQueue.java:706)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:705)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3211
Reporter: narupley
Created: 2014-03-31T09:57:52.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revision 7117. CellData now implements Comparable.

Imported Comment. Original Details:
Author: narupley
Created: 2014-03-31T14:59:59.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2014-04-10T18:07:41.000-0700
