### ISSUE TITLE
HTTP Listener fails to start if the context path ends with a slash '/'

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3145]
Appears that Jetty fails when the context path has a trailing slash. We should check for it and remove it.

`
[2014-04-15 08:55:27,521]  ERROR (com.mirth.connect.server.controllers.DonkeyEngineController:191): Error deploying channel 20aae280-4f8f-4904-8d90-48185825bc87.
com.mirth.connect.donkey.server.StartException: com.mirth.connect.donkey.server.StartException: Failed to start HTTP Listener
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1962)
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1861)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)Caused by: com.mirth.connect.donkey.server.StartException: Failed to start HTTP Listener
	at com.mirth.connect.connectors.http.HttpReceiver.onStart(HttpReceiver.java:110)
	at com.mirth.connect.donkey.server.channel.SourceConnector.start(SourceConnector.java:88)
	at com.mirth.connect.donkey.server.channel.Channel$StartTask.call(Channel.java:1939)
	... 6 moreCaused by: java.lang.IllegalArgumentException: ends with /
	at org.eclipse.jetty.server.handler.ContextHandler.setContextPath(ContextHandler.java:1237)
	at com.mirth.connect.connectors.http.HttpReceiver.onStart(HttpReceiver.java:101)
	... 8 more
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3234
Reporter: brentm
Created: 2014-04-15T08:57:06.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed with revision 7183. Trailing slashes are now always removed.

Imported Comment. Original Details:
Author: narupley
Created: 2014-06-03T12:16:32.000-0700

**Comment by rbeckman-nextgen** [comment]
Created a simple channel with an http listener in 3.0.3 and added a context path with a trailing slash. The channel deployed but was unable to start. I exported this channel and imported it into 3.1 and was able to verify the channel successfully starts. Ensured that context paths with leading slashes or without trailing slashes still works as expected.

Imported Comment. Original Details:
Author: jaysenp
Created: 2014-08-20T14:16:48.000-0700
