### ISSUE TITLE
Mirth 3.0.X versions flood mirth.log files with Connection reset error messages.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3150]
In the Mirth 3.0.X versions during a simple connection reset the mirth.log files get flooded with error messages that don't need to be there.

Can these be changed to a INFO level so that we do not loose valuable Error messages in the roll over of the mirth.log files and also make it easier to locate actual errors that are important in the fault isolation process?

ERROR 2014-04-17 16:07:49,130 [pool-185-thread-1] com.mirth.connect.connectors.tcp.TcpReceiver: Error receiving message (TCP Listener "Source" on channel 3503a0b3-0449-4221-8e48-3d4ecdc2b0ca).
java.net.SocketException: Connection reset
at java.net.SocketInputStream.read(SocketInputStream.java:196)
at java.net.SocketInputStream.read(SocketInputStream.java:122)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:121)
at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:554)
at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:458)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3239
Reporter: hdmoscm
Created: 2014-04-18T06:19:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Well, that's a valid error message, it indicates that a client is sending RST rather than a FIN packet. But it seems that it's so prevalent (and it doesn't actually cause messages to be lost necessarily) that yeah, we should probably change the log level of it. But instead of INFO, it'd make more sense as WARN. The root level is ERROR by default so those entries would still not show up in the logs.

Imported Comment. Original Details:
Author: narupley
Created: 2014-04-18T07:14:32.000-0700

**Comment by rbeckman-nextgen** [comment]
It seems like logging to separate areas based on the channel or connector it's coming from might be a useful approach at some point.

Imported Comment. Original Details:
Author: jacobb
Created: 2014-04-18T11:14:12.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7157: Changed the log level for connection reset exceptions from ERROR to WARN for the TCP Listener.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-09T15:51:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Reproduced in 3.0.2 and verified that in 3.0.3 the messages are now WARN level.

Imported Comment. Original Details:
Author: brentm
Created: 2014-05-15T09:00:01.000-0700

**Comment by iurkenty** [comment]
I still get an Error on these
![image](https://user-images.githubusercontent.com/105752711/217614522-24d986fe-b8b5-487b-abb7-1dc32d4a1987.png)
