### ISSUE TITLE
Allow multiple channel status operations to occur simultaneously from the same request

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3151]
In 3.0.2, it was made so if one user was starting/stopping multiple channels at once, only one request would be sent to the server. The server then performs all of the operations sequentially. While better for the client, this also means that if one channel is having problems starting/stopping, it may prevent other channels from doing so in the meantime. We should use an executor and have multiple thread workers performing these tasks simultaneously. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3240
Reporter: wayneh
Created: 2014-04-18T07:45:56.000-0700

**Comment by rbeckman-nextgen** [comment]
Now up to 10 operations can occur simultaneously per request

Imported Comment. Original Details:
Author: wayneh
Created: 2014-05-09T14:12:26.000-0700

**Comment by rbeckman-nextgen** [comment]
It seems that the way we're currently doing it, when 10 submissions are currently running and an 11th gets submitted, the executor immediately rejects it:

`[2014-05-14 11:51:23,919]  ERROR (com.mirth.connect.server.servlets.ChannelStatusServlet:212): java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@214f4609 rejected from java.util.concurrent.ThreadPoolExecutor@5b7f09f4[Running, pool size = 10, active threads = 10, queued tasks = 0, completed tasks = 0]

	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2048)

	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:821)

	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1372)

	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:110)

	at com.mirth.connect.server.servlets.ChannelStatusServlet.doPost(ChannelStatusServlet.java:131)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)

	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)

	at org.eclipse.jetty.server.Server.handle(Server.java:363)

	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)

	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)

	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)

	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)

	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)

	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)

	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

	at java.lang.Thread.run(Thread.java:744)

`

That can be easily reproduced by just starting up 11 default Channel Reader/Writer channels.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-14T12:02:44.000-0700

**Comment by rbeckman-nextgen** [comment]
The executors that allow multiple channel status operations now use a LinkedBlockingQueue instead of SynchronousQueue to prevent tasks from being rejected if there are no free threads.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-05-14T12:20:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-14T13:37:19.000-0700

**Comment by rbeckman-nextgen** [comment]
I had thought it wasn't possible for the servlet to get a request where the job count is 0, so I didn't check against that case on the servlet. However, it seems it is possible currently (MIRTH-3278). So we should check against this case manually.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-05-14T14:25:56.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that if a request is sent with a job count of 0, it gets ignored without generating an error.

Imported Comment. Original Details:
Author: brentm
Created: 2014-05-15T13:24:36.000-0700
