### ISSUE TITLE
MLLP Source Error shows up in console log, but not on channel itself

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3170]
Hello, this is in .7140.

After upgrading we noticed an error notification in the console telling us that a channel had thrown an error receiving a message due to a mismatch in the EoM Bytes. 

The issue I'm reporting as that there was no indication in the channel statistics that this had occurred.   It was pure luck that I had spotted the error in the console as this channel doesn't see much traffic.

The message also did not appear in the message browser.

As a result of this,  we were forced to go into Meditech and run audit trails to find what message hadn't gone.

Changing the expected EoM bytes eliminated the problem that alerted us to this issue.

The error message is pasted below:

[2014-05-01 10:13:01,031]  ERROR (com.mirth.connect.connectors.tcp.TcpReceiver:657): Error receiving message (TCP Listener "Source" on channel 7be8c64c-2f4c-4d9f-b4d1-06db52ccfbca).
com.mirth.connect.model.transmission.framemode.FrameStreamHandlerException: End of message bytes (<FS><CR>) not detected. Last bytes received: <CR><FF>
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:221)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:558)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3259
Reporter: bostad
Created: 2014-05-01T08:59:31.000-0700

**Comment by rbeckman-nextgen** [comment]
The channel never received a message because of the frame encoding issues, so it's correct that nothing was shown in the message browser. It's basically the same thing as failing a TCP handshake (except in this case it's specific to MLLP). If the handshake itself fails, you should expect the connection to be invalidated immediately. It's the same as when you go to a secure HTTPS website and the certificate validation fails, so the browser doesn't show _anything_ until you either trust the certificate or ignore the warning. The actual HTML or whatever on the page wasn't even pulled down yet at all, because the initial handshake failed.

Would you expect the error statistic to increment when this happens? Because if we do that, then you may look at the dashboard and see a bunch of errors, yet when you look in the message browser you don't see any errored messages. So I think incrementing the statistics would lead to a lot of undue confusion. And actually having a message show up in the message browser wouldn't be correct either, because in most cases there _is_ no message.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-01T09:59:45.000-0700

**Comment by rbeckman-nextgen** [comment]
Okay, that makes perfect sense.  The only issue is if I'm not watching the console (which is most of the time),  I won't have any other indication that messages aren't going.

If I set up a source alert on the channel,  would it fire in this instance?



Imported Comment. Original Details:
Author: bostad
Created: 2014-05-01T10:05:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Yes indeed it would!

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-01T10:07:36.000-0700

**Comment by rbeckman-nextgen** [comment]
Awesome, thanks Nick.
We can close this ticket.

Imported Comment. Original Details:
Author: bostad
Created: 2014-05-01T10:15:20.000-0700
