### ISSUE TITLE
Suspected Memory Leak in Web Service Sender

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3172]
My Mirth Connect channel must query Mirth Match using method findIdentitiesByTraits(). MirthMatchClient returns a java.util.List<EisResultSetElement> which to the best of my knowledge cannot be converted into a JavaScript array of EisResultSetElement without writing a custom Java transformer class (I am submitting a separate Jira ticket for that).
Using Web Service Sender works very well for a few tens of thousands of messages but then starts to fail with the error below. I suspect that the Web Service Sender creates too many connections and does not garbage collect them properly.

Web Service Sender error
ERROR MESSAGE: Error invoking web service
com.sun.xml.internal.ws.protocol.soap.MessageCreationException: Couldn't create SOAP message due to exception: Unable to create StAX reader or writer
	at com.sun.xml.internal.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:348)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.createResponsePacket(HttpTransportPipe.java:254)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:203)
	at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:122)
	at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:95)
	at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:626)
	at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:585)
	at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:570)
	at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:467)
	at com.sun.xml.internal.ws.client.Stub.process(Stub.java:308)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.doInvoke(DispatchImpl.java:177)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.invoke(DispatchImpl.java:203)
	at com.mirth.connect.connectors.ws.WebServiceDispatcher.send(WebServiceDispatcher.java:288)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:588)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:336)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:224)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1422)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:955)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:177)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:154)
	at com.mirth.connect.connectors.file.FileReceiver.processBatchMessage(FileReceiver.java:591)
	at com.mirth.connect.plugins.datatypes.delimited.DelimitedBatchAdaptor.processBatch(DelimitedBatchAdaptor.java:65)
	at com.mirth.connect.connectors.file.FileReceiver.processBatch(FileReceiver.java:447)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:313)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:239)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:194)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:141)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Caused by: com.sun.xml.internal.ws.streaming.XMLReaderException: Unable to create StAX reader or writer
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory$Default.doCreate(XMLStreamReaderFactory.java:367)
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.doCreate(XMLStreamReaderFactory.java:193)
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory.create(XMLStreamReaderFactory.java:143)
	at com.sun.xml.internal.ws.encoding.StreamSOAPCodec.decode(StreamSOAPCodec.java:290)
	at com.sun.xml.internal.ws.encoding.StreamSOAPCodec.decode(StreamSOAPCodec.java:118)
	at com.sun.xml.internal.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:343)
	... 28 more
Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: JAXP00010001: The parser has encountered more than "64000" entity expansions in this document; this is the limit imposed by the JDK.
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.setInputSource(XMLStreamReaderImpl.java:219)
	at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.<init>(XMLStreamReaderImpl.java:189)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.getXMLStreamReaderImpl(XMLInputFactoryImpl.java:277)
	at com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(XMLInputFactoryImpl.java:139)
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory$Default.doCreate(XMLStreamReaderFactory.java:365)
	... 33 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3261
Reporter: aitougan
Created: 2014-05-02T07:27:19.000-0700

**Comment by rbeckman-nextgen** [comment]
First, you can convert from a java.util.List to a JavaScript array by using the toArray() function.

Regarding this issue, it's not a memory leak as far as I can see; it's a rather well-known entity expansion limit in the JDK:

[https://bugs.openjdk.java.net/browse/JDK-6315411]
[https://bugs.openjdk.java.net/browse/JDK-8029038]
[https://bugs.openjdk.java.net/browse/JDK-8028111]
[https://blogs.oracle.com/joew/entry/jdk_7u45_aws_issue_123]

If you're certain that it's a memory leak on the Mirth Connect side, please give us a self-contained test case that we can reproduce it with.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-02T07:38:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Well, since this is not a bug, I guess it should be closed...

Imported Comment. Original Details:
Author: aitougan
Created: 2014-05-02T07:58:22.000-0700

**Comment by rbeckman-nextgen** [comment]
On Fri, May 2, 2014 at 7:43 AM, Alex Aitougan <alexa@mirthcorp.com> wrote:
> I understand it’s not your fault, but does it mean I cannot send more than 64,000 queries over WS without rebooting?

\\
\\
Not necessary 64,000 queries no, it means that the StAX parser will not expand more than that many entities in a single document. This is to guard against [DDoS attacks](http://en.wikipedia.org/wiki/Billion_laughs), though as I linked before, there is debate as to how effective or reasonable the current limit is. Many people who process large documents find the limit quite stringent. Though there are several ways around it if you really need to increase the limit (also linked in a previous comment). For example, one solution is to specify "\-DentityExpansionLimit" in the JVM options.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-02T07:59:41.000-0700

**Comment by rbeckman-nextgen** [comment]
The document I am sending (below) has less than 3,000 characters. I don't know how is it being interpreted as having more than 64,000 entities. Also, per Steve K. Java options are not to be messed with.

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:eis="http://eis.ejb.match.mirth.com/">
   <soapenv:Header/>
   <soapenv:Body>
      <eis:FindIdentitiesByTraits>
         
         <entityTypeName>PATIENT</entityTypeName>
         
         <entityId></entityId>
         
         <sourceId>
            
            
            
            <domainId>TEST_FS</domainId>
            
            
            
            
            
            
         </sourceId>
         
         <eisId></eisId>
         
         <traits>
            
            <traits><traitID>LASTNAME</traitID><value>REDDY</value></traits>
            <traits><traitID>FIRSTNAME</traitID><value>EAMONN</value></traits>
            <traits><traitID>MIDDLENAME</traitID><value></value></traits>
            <traits><traitID>GENDER</traitID><value>M</value></traits>
            <traits><traitID>DATEOFBIRTH</traitID><value>05/05/2010</value></traits>
            <traits><traitID>ADDRESS</traitID><value>124 Ledge St Apt 1R</value></traits>
            <traits><traitID>LOCALITY</traitID><value>North Providence</value></traits>
            <traits><traitID>STATE</traitID><value>RI</value></traits>
            <traits><traitID>POSTALCODE</traitID><value>02904</value></traits>
            <traits><traitID>PHONE</traitID><value>(401)952-8204</value></traits>
         </traits>
         
         <searchQualifiers>
            
            
            
            
            
            
            
            <identifierDomainLimiters>EASTSIDE</identifierDomainLimiters>
            
            <matchingModuleName>FELLEGISUNTERSEARCH</matchingModuleName>
            <maxResultSetSize>100</maxResultSetSize>
            
            
            
            
            
            
            <searchConfidenceLevel>20</searchConfidenceLevel>
            
            
         </searchQualifiers>
      </eis:FindIdentitiesByTraits>
   </soapenv:Body>
</soapenv:Envelope>


Imported Comment. Original Details:
Author: aitougan
Created: 2014-05-02T08:06:53.000-0700

**Comment by rbeckman-nextgen** [comment]
That I don't know off the top of my head then. There is probably some caching going on that's causing the expansion limit to be reached across multiple documents, most likely when a lot of messages are sent in short succession. Whether that's a problem with JAX-WS / StAX / JDK or with Mirth Connect I don't know; I would need some sort of test case to reproduce with.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-02T08:15:23.000-0700

**Comment by rbeckman-nextgen** [comment]
I agree that this is not something that can be easily fixed

Imported Comment. Original Details:
Author: aitougan
Created: 2014-05-02T08:18:47.000-0700

**Comment by rbeckman-nextgen** [comment]
I don't know what it means (and whether it belongs here), but MM client gives the following (related) warning:

[2014-05-02 15:43:51,434]  ERROR (Server:146): Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.


Imported Comment. Original Details:
Author: aitougan
Created: 2014-05-02T08:46:34.000-0700

**Comment by rbeckman-nextgen** [comment]
That variable "result" is not a java.util.List, it's some Status object.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-02T08:50:36.000-0700

**Comment by rbeckman-nextgen** [comment]
the .toArray() really did the trick. Just needed to find the right object to stick it to.

Imported Comment. Original Details:
Author: aitougan
Created: 2014-05-02T09:11:53.000-0700

**Comment by rbeckman-nextgen** [comment]
I ran into this one today. I don't have a reliable way to replicate this at the moment but I had a couple Ws sender channels blasting a listener and eventually the server ran into this after some hours of it.

`
ERROR 2014-10-03 10:23:08,136 [pool-42-thread-1] com.sun.xml.internal.ws.transport.http.HttpAdapter: Couldn't create SOAP message due to exception: Unable to create StAX reader or writer
com.sun.xml.internal.ws.protocol.soap.MessageCreationException: Couldn't create SOAP message due to exception: Unable to create StAX reader or writer
	at com.sun.xml.internal.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:283)
	at com.sun.xml.internal.ws.transport.http.HttpAdapter.decodePacket(HttpAdapter.java:266)
	at com.sun.xml.internal.ws.transport.http.HttpAdapter.access$500(HttpAdapter.java:82)
	at com.sun.xml.internal.ws.transport.http.HttpAdapter$HttpToolkit.handle(HttpAdapter.java:446)
	at com.sun.xml.internal.ws.transport.http.HttpAdapter.handle(HttpAdapter.java:233)
	at com.sun.xml.internal.ws.transport.http.server.WSHttpHandler.handleExchange(WSHttpHandler.java:95)
	at com.sun.xml.internal.ws.transport.http.server.WSHttpHandler.handle(WSHttpHandler.java:80)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:65)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:68)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:566)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:536)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: com.sun.xml.internal.ws.streaming.XMLReaderException: Unable to create StAX reader or writer
	at com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory$Default.doCreate(XMLStreamReaderFactory.java:366)
`

Imported Comment. Original Details:
Author: eduardoa
Created: 2014-10-03T10:23:18.000-0700

**Comment by rbeckman-nextgen** [comment]
This is a duplicate of MIRTH-3117. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2014-10-06T09:35:26.000-0700
