### ISSUE TITLE
Lost backend database connection requires a server restart

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3173]
With the current connection pooling we're using, if connectivity to the database is completely dropped for a period of time and then comes back up, the server will not gracefully reconnect. The cached connections are still being used, or the pool apparently isn't correctly tossing and grabbing new connections as needed.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3262
Reporter: narupley
Created: 2014-05-05T09:31:54.000-0700

**Comment by rbeckman-nextgen** [comment]
https://issues.apache.org/jira/browse/DBCP-391

It appears there is a bug in the version of DBCP we're using (1.4) where connections may not be returned to the pool when certain errors occur. This was fixed in the 1.5.1 and 2.0 branches. 1.5.1 is unreleased and there is no timeline for it. 2.0 is released but it requires Java 7. Therefore pain.

I can duplicate and confirm that once all the connections in the pool have been used and "failed", Mirth Connect will block the next time it tries to retrieve a connection from the pool.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-07-23T09:56:27.000-0700

**Comment by rbeckman-nextgen** [comment]
Welp, time to require Java 7

Imported Comment. Original Details:
Author: narupley
Created: 2014-07-23T10:00:58.000-0700

**Comment by rbeckman-nextgen** [comment]
One additional note, as long as there are still connections in the pool that have not errored, the connection pool DOES successfully reconnect even if I restart the database. Of course we may have messages that are unfinished and not recovered until the next time the channel is started, but currently it seems as if the connections not being returned to the pool is 100% of the problem.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-07-23T10:11:47.000-0700

**Comment by rbeckman-nextgen** [comment]
There's also MIRTH-1965 which _may_ require Java 7 (additional testing is needed).

Imported Comment. Original Details:
Author: narupley
Created: 2014-07-23T13:58:34.000-0700

**Comment by rbeckman-nextgen** [comment]
Confirmed that this issue is fixed in DBCP2.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-18T06:33:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Was finally able to build the 1.5.X branch and can confirm that it also fixes this issue. Using this build would allow us to still support Java 6. Of course this is a SNAPSHOT build and there may be unforeseen consequences in using it.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-18T07:24:30.000-0700

**Comment by rbeckman-nextgen** [comment]
It doesn't **seem** like there have been that many changes for 1.5.1. I'm warming up to the idea of using the snapshot build. Seems like most of the bugs they fixed were outstanding for at least a couple of years. I looked through the list and nothing seems to crazy.

https://issues.apache.org/jira/browse/DBCP-405?jql=fixVersion%20%3D%201.5.1%20AND%20project%20%3D%20DBCP

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-18T10:02:43.000-0700

**Comment by rbeckman-nextgen** [comment]
I took a look as well, doesn't seem too bad. With sufficient testing on our side, I don't see why we couldn't use the 1.5.x snapshot.

Imported Comment. Original Details:
Author: narupley
Created: 2014-08-18T10:08:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Interestingly enough, it seems that only PostgreSQL leaks connections on DBCP 1.4. All of the other database appear to still release their connections when the connection is lost.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-18T11:51:16.000-0700

**Comment by rbeckman-nextgen** [comment]
Updated dbcp from 1.4 to the latest snapshot build of 1.5. The latest build fixes a bug where connections are not released back to the pool when network connectivity is lost. This appeared to happen primarily with Postgres. If an official build of 1.5 is released we should upgrade to that instead. 

In the future we may want to upgrade to dbcp2 which will require all users to be on Java7.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-18T12:24:42.000-0700

**Comment by rbeckman-nextgen** [comment]
I'm finding problems with the latest 1.5 snapshot build. When the number of connections in use reaches the max, seemingly random connections begin to fail. I believe its the same issue as this http://qnalist.com/questions/4743611/dbcp2-connection-pool-leak. According to the comments, {quote}It's possible that DBCP2 is less forgiving
than earlier versions when it comes to sloppy resource management.{quote} so its possibly a separate bug in our code. It's a very difficult thing to debug though.

I have not tried DBCP2 yet to see if I run into the same problems, I think we probably will since the link above is referring to DBCP2.

One possible alternative we can try is tomcat-jdbc (http://tomcat.apache.org/tomcat-8.0-doc/jdbc-pool.html)

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-20T16:23:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Ugh after debugging and modifying the DBCP source, I've determined that the new problems are indeed a bug in the 1.5 branch. This bug was introduced specifically when fixing the original problem that we were having (https://issues.apache.org/jira/browse/DBCP-391). It has since been fixed in the DBCP2 branch, but NOT in 1.5. Therefore we may be back to square one. I don't know if I would be able to backport the fix into the 1.5 branch since there's been intermediate changes which I am unsure about.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-20T18:26:13.000-0700

**Comment by rbeckman-nextgen** [comment]
Did what I said I wasn't going to do in the previous comment.

Backporting the fix for https://issues.apache.org/jira/browse/DBCP-391 into the 1.4 release.
This fix actually introduced a new bug that was only fixed on the DBCP2 branch at revision 1568674.
Therefore I've also backported the fix for the new bug as well. 
It will (probably) work.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-21T18:18:42.000-0700

**Comment by rbeckman-nextgen** [comment]
After the database goes down and comes back up, everything seems to reconnect and start working again. Everything _except_ for trying to load the Administrator settings panel for some reason:
\\
`[2014-09-19 08:14:01,280]  ERROR (com.mirth.connect.server.servlets.UserServlet:203): java.lang.NullPointerException
	at com.mirth.connect.server.servlets.UserServlet.isCurrentUser(UserServlet.java:302)
	at com.mirth.connect.server.servlets.UserServlet.doPost(UserServlet.java:180)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
`
\\
\\
EDIT: Well, I had it happen the one time, but it isn't happening again... it's probably something unrelated to the database connection changes. I mean there are plenty of places where connectivity drops aren't handled gracefully (NPEs all over the place), but those are separate from this particular issue.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-19T08:18:05.000-0700

**Comment by rbeckman-nextgen** [comment]
Tested on all databases (even Derby) and verified that when connectivity drops and comes back, channels eventually start working again. For some reason the Oracle driver seems to take a while to fully reconnect, but eventually it does.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-19T09:33:56.000-0700
