### ISSUE TITLE
Attempting to search messages by text fails with an error

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3187]
Attempting text search in Channel Messages fails with the following error:

[2014-05-14 10:28:22,501]  ERROR (com.mirth.connect.server.servlets.MessageObjectServlet:294): org.apache.ibatis.exceptions.PersistenceException: 
*## Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 185
*## The error may exist in postgres/postgres-message.xml
*## The error may involve Message.searchCustomMetaDataTable-Inline
*## The error occurred while setting parameters
*## SQL: SELECT MESSAGE_ID AS MESSAGE_ID, METADATA_ID AS METADATA_ID       FROM D_MCM15       WHERE MESSAGE_ID  >=  ?             AND MESSAGE_ID  <=  ?                         AND           ()
*## Cause: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 185

	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:23)

	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:104)

	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:95)

	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:606)

	at org.apache.ibatis.session.SqlSessionManager$SqlSessionInterceptor.invoke(SqlSessionManager.java:282)

	at com.sun.proxy.$Proxy7.selectList(Unknown Source)

	at org.apache.ibatis.session.SqlSessionManager.selectList(SqlSessionManager.java:171)

	at com.mirth.connect.server.controllers.DonkeyMessageController.searchText(DonkeyMessageController.java:1065)

	at com.mirth.connect.server.controllers.DonkeyMessageController.searchAll(DonkeyMessageController.java:872)

	at com.mirth.connect.server.controllers.DonkeyMessageController.searchMessages(DonkeyMessageController.java:641)

	at com.mirth.connect.server.controllers.DonkeyMessageController.getMessages(DonkeyMessageController.java:192)

	at com.mirth.connect.server.servlets.MessageObjectServlet.doPost(MessageObjectServlet.java:97)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)

	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)

	at org.eclipse.jetty.server.Server.handle(Server.java:363)

	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)

	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)

	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)

	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)

	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)

	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)

	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)

	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

	at java.lang.Thread.run(Thread.java:744)
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 185

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)

	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)

	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)

	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)

	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)

	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:379)

	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:56)

	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:70)

	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:57)

	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)

	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:141)

	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:105)

	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:81)

	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:101)

	... 37 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3276
Reporter: aitougan
Created: 2014-05-14T07:36:28.000-0700

**Comment by rbeckman-nextgen** [comment]
This occurs when you do a text search on a channel that has no custom metadata columns of type STRING defined. Luckily that is an uncommon case, since even on import / migration we add the SOURCE/TYPE columns on all channels.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-14T07:48:53.000-0700

**Comment by rbeckman-nextgen** [comment]
In DonkeyMessageController.searchText we should only be executing the searchCustomMetaDataTable query if there are actually any STRING metadata columns to search in. Attaching a patch for it.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-14T08:29:01.000-0700

**Comment by rbeckman-nextgen** [comment]
Yes, adding those two metadata fields fixed the problem for me.

Imported Comment. Original Details:
Author: aitougan
Created: 2014-05-14T08:31:38.000-0700

**Comment by rbeckman-nextgen** [comment]
Yeah so that would be the workaround, just add at least one STRING type custom metadata column on your channel. It can be a dummy column that never actually gets populated; it just has to exist.

That's only a workaround though. With this fix you shouldn't _need_ to have any custom metadata columns on a channel for text searching to work.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-14T08:41:35.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revision 7162.

Imported Comment. Original Details:
Author: narupley
Created: 2014-05-14T09:15:53.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2014-05-15T10:34:07.000-0700
