### ISSUE TITLE
Extensions fail to load

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3192]
I imported a channel for scheduling channels off of the wiki (it upgraded it from 2.2 to 3.0).  Everything seemed fine.  I was also changing a code template for calling another channel to send an email in a post processor script.  I had found the smtp configuration and filled it in with what worked in a channel.  When I launched the channel it seemed to take a long time.  Then it said my channel was invalid an extension was missing.  I rebooted server, I launched mirth connect administrator and got error after error about the extensions.  Looking at the installed connectors and plugins I see many lines that are enabled but a completely blank after that column, so they have no name, auther, url or version.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3281
Reporter: borric74
Created: 2014-05-16T08:22:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Note I can not edit any of the channels either.

Channel "TestLabRecieveChannel" is invalid and cannot be edited. 

Your Mirth Connect installation is missing required connectors for this channel:
     Channel Writer
     TCP Listener

Original cause:
-1 : -1

Imported Comment. Original Details:
Author: borric74
Created: 2014-05-16T08:31:57.000-0700

**Comment by rbeckman-nextgen** [comment]
What version of Java are you using on both the Server and the machine running the Administrator?

Imported Comment. Original Details:
Author: wayneh
Created: 2014-05-16T08:54:09.000-0700

**Comment by rbeckman-nextgen** [comment]
Saved out all channels and deleted channels that had changes
No Effect.

Upgrading to 3.02 Resolved the problem

Imported Comment. Original Details:
Author: borric74
Created: 2014-05-16T09:01:21.000-0700

**Comment by rbeckman-nextgen** [comment]
I suspect you may have been running Java 8 for either the Server or the Administrator (http://www.mirth.com/community/forums/showthread.php?t=10283). Can you confirm so we can close this issue?

Imported Comment. Original Details:
Author: wayneh
Created: 2014-05-16T09:10:28.000-0700

**Comment by rbeckman-nextgen** [comment]
Server and Administrator are running from the same machine and the java that is loaded is:
Java 8.5
Build 1.8.0_05-b13


Note: All the extensions seemed to load but a few of the channels still failed to load:

[2014-05-16 13:16:29,131]  ERROR (com.mirth.connect.server.controllers.DonkeyEngineController:191): Error deploying channel 375b4bee-569c-4978-b468-394fe49ed1a8.
com.mirth.connect.donkey.server.DeployException
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannel(DonkeyEngineController.java:212)
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannels(DonkeyEngineController.java:189)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:64)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)Caused by: java.lang.NullPointerException
	at com.mirth.connect.plugins.datatypes.hl7v2.ER7BatchAdaptor.<init>(ER7BatchAdaptor.java:33)
	at com.mirth.connect.plugins.datatypes.hl7v2.HL7v2DataTypeServerPlugin.getBatchAdaptor(HL7v2DataTypeServerPlugin.java:48)
	at com.mirth.connect.server.message.DataTypeFactory.getDataType(DataTypeFactory.java:33)
	at com.mirth.connect.server.controllers.DonkeyEngineController.setCommonConnectorProperties(DonkeyEngineController.java:904)
	at com.mirth.connect.server.controllers.DonkeyEngineController.createSourceConnector(DonkeyEngineController.java:738)
	at com.mirth.connect.server.controllers.DonkeyEngineController.convertToDonkeyChannel(DonkeyEngineController.java:549)
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannel(DonkeyEngineController.java:210)
	... 27 more

Imported Comment. Original Details:
Author: borric74
Created: 2014-05-16T11:20:31.000-0700

**Comment by rbeckman-nextgen** [comment]
Thanks for the confirmation. Java 8 is not supported on 3.0.0 or 3.0.1. The issue was fixed for 3.0.2 (MIRTH-3207). Any channels or alerts you created while using 3.0.1 w/ Java 8 are probably missing data types or other information. So make sure you're only using new channels that were created with 3.0.2 or importing channels creating from before upgrading to 3.0.1

Imported Comment. Original Details:
Author: wayneh
Created: 2014-05-16T11:26:34.000-0700

**Comment by rbeckman-nextgen** [comment]
Thank you.
I remember having trouble with Java 8 at first for security reasons but I fixed it and did not have any problems until today.
I have recreated a few simple channels and imported others from before and they seem ok now.




Brett Thomson
Chief Information Officer
2700 Technology Forest Blvd., Suite 250 | The Woodlands, TX 77381
Phone: 800.603.7896 | Fax: 832.550.2941
bthomson@intellicure.com<mailto:bthomson@intellicure.com> | www.Intellicure.com<http://www.Intellicure.com>

From: Wayne Huang (JIRA) [mailto:issues@mirthcorp.com]
Sent: Friday, May 16, 2014 1:28 PM
To: Brett Thomson
Subject: [JIRA] (MIRTH-3281) Extensions fail to load

[cid:image001.png@01CF710B.51782140]

Wayne Huang<http://www.mirthcorp.com/community/issues/secure/ViewProfile.jspa?name=wayneh> edited a comment on [Bug] MIRTH-3281<http://www.mirthcorp.com/community/issues/browse/MIRTH-3281>




Re: Extensions fail to load<http://www.mirthcorp.com/community/issues/browse/MIRTH-3281>


Thanks for the confirmation. Java 8 is not supported on 3.0.0 or 3.0.1. The issue was fixed for 3.0.2 (MIRTH-3207). Any channels or alerts you created while using 3.0.1 w/ Java 8 are probably missing data types  or other information . So make sure you're only using new channels that were created with 3.0.2 or importing channels creating from before upgrading to 3.0.1


[Add Comment]<http://www.mirthcorp.com/community/issues/browse/MIRTH-3281#add-comment>

Add Comment<http://www.mirthcorp.com/community/issues/browse/MIRTH-3281#add-comment>






This message was sent by Atlassian JIRA (v6.2#6252-sha1:aa34325)

[Atlassian logo]






Imported Comment. Original Details:
Author: borric74
Created: 2014-05-16T11:44:04.000-0700
