### ISSUE TITLE
HTTP Listener does not parse array query parameters correctly

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3210]
If you specify multiple parameters with the same key, the HTTP Listener will throw an exception:

`[2014-05-29 09:24:16,408]  ERROR (com.mirth.connect.connectors.http.HttpMessageConverter:85): Error converting HTTP request.
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954)
	at com.mirth.connect.connectors.http.HttpMessageConverter.httpRequestToXml(HttpMessageConverter.java:49)
	at com.mirth.connect.connectors.http.HttpReceiver.processData(HttpReceiver.java:255)
	at com.mirth.connect.connectors.http.HttpReceiver.access$300(HttpReceiver.java:48)
	at com.mirth.connect.connectors.http.HttpReceiver$RequestHandler.handle(HttpReceiver.java:144)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1040)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:976)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:744)`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3304
Reporter: narupley
Created: 2014-05-29T09:25:14.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicates MIRTH-2182.

Imported Comment. Original Details:
Author: narupley
Created: 2014-06-03T07:41:47.000-0700
