### ISSUE TITLE
HTTP Listener fails to receive tunnel-proxied messages

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3243]
If your HTTP Listener received a proxied request and the entire target URL is specified in the URI section of the method line, the receiver will fail:

`[2014-06-12 14:18:48,531]  ERROR (com.mirth.connect.connectors.http.HttpMessageConverter:84): Error converting HTTP request.
java.net.MalformedURLException: For input string: "9002localhost:9002"
	at java.net.URL.<init>(URL.java:619)
	at java.net.URL.<init>(URL.java:482)
	at java.net.URL.<init>(URL.java:431)
	at com.mirth.connect.connectors.http.HttpMessageConverter.httpRequestToXml(HttpMessageConverter.java:42)
	at com.mirth.connect.connectors.http.HttpMessageAdapter.setMessage(HttpMessageAdapter.java:38)
	at com.mirth.connect.connectors.http.HttpMessageAdapter.<init>(HttpMessageAdapter.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:271)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:278)
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageAdapter(ConnectorServiceDescriptor.java:270)
	at org.mule.providers.AbstractServiceEnabledConnector.getMessageAdapter(AbstractServiceEnabledConnector.java:149)
	at com.mirth.connect.connectors.http.HttpMessageReceiver.processData(HttpMessageReceiver.java:182)
	at com.mirth.connect.connectors.http.HttpMessageReceiver.access$400(HttpMessageReceiver.java:49)
	at com.mirth.connect.connectors.http.HttpMessageReceiver$RequestHandler.handle(HttpMessageReceiver.java:67)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:943)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:879)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:110)
	at org.eclipse.jetty.server.Server.handle(Server.java:349)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:441)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:919)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:582)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:218)
	at org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:50)
	at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:245)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:598)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:533)
	at java.lang.Thread.run(Thread.java:744)Caused by: java.lang.NumberFormatException: For input string: "9002localhost:9002"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:217)
	at java.net.URL.<init>(URL.java:614)
	... 30 more`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3340
Reporter: narupley
Created: 2014-06-12T15:05:54.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7197: The HTTP Listener now validates the request URL returned from Jetty, and builds it up manually instead if it was invalid.

Imported Comment. Original Details:
Author: narupley
Created: 2014-06-12T15:08:09.000-0700

**Comment by rbeckman-nextgen** [comment]
Just to clarify this is specific to HTTP CONNECT tunneling which is a way for http proxy servers to handle https requests but forwarding a tcp connection(triggered by the CONNECT method).

Verified using firefox, TCP Sender and HTTP Sender(3.1 SSL Proxy). Here is what the request looks like:
`
CONNECT test:443 HTTP/1.1
Host: test
Proxy-Connection: Keep-Alive
`

Result in 3.0.3:
`
[2014-09-09 11:04:46,178]  ERROR (com.mirth.connect.connectors.http.HttpMessageConverter:85): Error converting HTTP request.
java.net.MalformedURLException: For input string: "443test:443"
`

Result in 3.1.0:
`
<HttpRequest>
    <RemoteAddress>10.10.12.135</RemoteAddress>
    <RequestUrl>http://test:443</RequestUrl>
    <Method>CONNECT</Method>
    <RequestPath/>
    <RequestContextPath/>
    <Header>
        <Host>test</Host>
        <Proxy-Connection>Keep-Alive</Proxy-Connection>
    </Header>
    <Content multipart="no"/>
</HttpRequest>
`

It is important to note that the HTTP Listener wont act as a proxy server but is just now able to handle this request.





Imported Comment. Original Details:
Author: eduardoa
Created: 2014-09-09T12:28:28.000-0700
