### ISSUE TITLE
Cannot Stop or Halt a Webservice Sender channel that is waiting for a response

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3267]
During development of a new channel recently I have picked up a problem with the webservice sender connector in that if no response is received by the sender, the channel will hang (because you cannot set a timeout) but also it is impossible to stop or halt the channel without killing the mcservice process.  I have been able to reproduce this.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3366
Reporter: seaston
Created: 2014-07-15T13:56:04.000-0700

**Comment by rbeckman-nextgen** [comment]
Mine is a different channel but I am also unable to kill (stop/halt) it with this error:

[2015-04-23 09:49:36,269]  ERROR (com.mirth.connect.server.channel.LoggingTaskHandler:24): com.mirth.connect.donkey.server.HaltException: Halt channel task for MM Auto-Merge (40963c0c-f796-49fa-920a-79261d574af6) terminated by another halt notification.

	at com.mirth.connect.donkey.server.channel.Channel.halt(Channel.java:765)

	at com.mirth.connect.server.controllers.DonkeyEngineController$HaltTask.execute(DonkeyEngineController.java:1407)

	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:59)

	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)

	at java.util.concurrent.FutureTask.run(FutureTask.java:262)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException

	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireInterruptibly(AbstractQueuedSynchronizer.java:896)

	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1221)

	at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:340)

	at com.mirth.connect.donkey.server.channel.DefaultChannelProcessLock.acquire(DefaultChannelProcessLock.java:19)

	at com.mirth.connect.donkey.server.channel.Channel.obtainProcessLock(Channel.java:1383)

	at com.mirth.connect.donkey.server.channel.Channel.halt(Channel.java:1010)

	at com.mirth.connect.donkey.server.channel.Channel.halt(Channel.java:761)

	... 7 more



Imported Comment. Original Details:
Author: aitougan
Created: 2015-04-23T09:56:22.000-0700

**Comment by rbeckman-nextgen** [comment]
The fact that you can't set a timeout has been fixed in 3.1 with MIRTH-2289. So now, this should only be a problem if your timeout is still set to 0.

Imported Comment. Original Details:
Author: narupley
Created: 2015-04-23T13:39:49.000-0700
