### ISSUE TITLE
Allow all new users to register their information upon first login

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3273]
Currently, only the first user that logs in to a server can register their information. We need to allow ALL users to register when they first log in. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3372
Reporter: leilanim
Created: 2014-07-18T10:33:50.000-0700

**Comment by rbeckman-nextgen** [comment]
A user preferences table has also been added to keep track of user-specific properties--in this case, a first login flag. 

Imported Comment. Original Details:
Author: leilanim
Created: 2014-08-06T19:16:15.000-0700

**Comment by rbeckman-nextgen** [comment]
On migration, all existing users need their first login flag set to false otherwise everyone will get the registration notice including the admin user again.

UpdateSettings needs migration because some of the properties it contains were added/removed. Otherwise importing an old server configuration will fail.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-08-12T10:12:38.000-0700

**Comment by rbeckman-nextgen** [comment]
The dialog says "You also have the option of changing your account password". However it's not an option, it's required. The user is unable to press the Finish button until the password fields are filled in.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-04T12:23:35.000-0700

**Comment by rbeckman-nextgen** [comment]
The reason it says that is because they can leave it the same if they want to, but they do have to re-enter it.

Imported Comment. Original Details:
Author: jacobb
Created: 2014-09-04T13:21:12.000-0700

**Comment by rbeckman-nextgen** [comment]
The 'update.enabled', 'update.url', and 'firstlogin' are still being inserted into the configuration table when the schema is being created. These need to be removed.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-10T10:24:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Removed 'update.url', 'update.'enabled', and 'firstlogin' from configuration table. 

As for the dialog, that's actually what it said originally so it remains as is because what Jake said.

Imported Comment. Original Details:
Author: leilanim
Created: 2014-09-10T16:50:13.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that users are able to register their information upon first login. They are still required to enter their current password into the dialog even if they do not wish to update their password or register their information.

Imported Comment. Original Details:
Author: jaysenp
Created: 2014-09-11T10:36:44.000-0700

**Comment by rbeckman-nextgen** [comment]
The SQL migration code added actually causes upgrades to 3.1.0 to fail when there are multiple users:
\\
\\
`ERROR 2014-10-03 09:23:04,675 [Thread-1] com.mirth.connect.server.Mirth: Failed to migrate database schema
com.mirth.connect.model.util.MigrationException: Failed to execute script: postgres-3.0.3-3.1.0.sql
	at com.mirth.connect.server.migration.Migrator.executeScript(Migrator.java:91)
	at com.mirth.connect.server.migration.Migrator.executeScript(Migrator.java:74)
	at com.mirth.connect.server.migration.Migrate3_1_0.migrate(Migrate3_1_0.java:35)
	at com.mirth.connect.server.migration.ServerMigrator.migrate(ServerMigrator.java:64)
	at com.mirth.connect.server.controllers.DefaultMigrationController.migrate(DefaultMigrationController.java:90)
	at com.mirth.connect.server.Mirth.startup(Mirth.java:236)
	at com.mirth.connect.server.Mirth.run(Mirth.java:163)
Caused by: org.postgresql.util.PSQLException: ERROR: more than one row returned by a subquery used as an expression
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:397)
	at com.mirth.connect.server.migration.Migrator.executeScript(Migrator.java:88)
	... 6 more`

Imported Comment. Original Details:
Author: narupley
Created: 2014-10-03T09:28:52.000-0700

**Comment by rbeckman-nextgen** [comment]
The query

`INSERT INTO PERSON_PREFERENCE (PERSON_ID, NAME, VALUE) VALUES ((SELECT ID FROM PERSON), 'firstlogin', 'false')`

should probably be

`INSERT INTO PERSON_PREFERENCE (PERSON_ID, NAME, VALUE) SELECT ID, 'firstlogin', 'false' FROM PERSON`

Imported Comment. Original Details:
Author: wayneh
Created: 2014-10-03T09:44:51.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed the above in revision 7411. All database deltas have been updated to the suggested query. SQL Server was actually already doing this, but the query was updated anyway to be consistent with the others.

Imported Comment. Original Details:
Author: narupley
Created: 2014-10-03T12:32:28.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified

Imported Comment. Original Details:
Author: wayneh
Created: 2014-10-03T12:53:22.000-0700
