### ISSUE TITLE
Users should not be able to add custom metadata columns that already exist

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3311]
If you create a channel that uses MESSAGE_ID or METADATA_ID as one of its custom metadata columns, it will actually let you deploy the channel the first time. However the second time you deploy it, it will error:

`[2014-08-18 08:38:13,150]  ERROR (com.mirth.connect.server.controllers.DonkeyEngineController:191): Error deploying channel 1d8f6781-e1ce-4ec9-abb3-f022fe51f0da.
com.mirth.connect.donkey.server.DeployException: Failed to deploy channel.
	at com.mirth.connect.donkey.server.channel.Channel.deploy(Channel.java:420)
	at com.mirth.connect.donkey.server.Donkey.deployChannel(Donkey.java:154)
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannel(DonkeyEngineController.java:244)
	at com.mirth.connect.server.controllers.DonkeyEngineController.deployChannels(DonkeyEngineController.java:189)
	at com.mirth.connect.server.controllers.DonkeyEngineController.redeployAllChannels(DonkeyEngineController.java:328)
	at com.mirth.connect.server.servlets.EngineServlet.doPost(EngineServlet.java:54)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)Caused by: java.util.concurrent.ExecutionException: com.mirth.connect.donkey.server.data.DonkeyDaoException: Failed to add meta-data column
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.mirth.connect.donkey.server.channel.Channel.deploy(Channel.java:395)
	... 30 moreCaused by: com.mirth.connect.donkey.server.data.DonkeyDaoException: Failed to add meta-data column
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.addMetaDataColumn(JdbcDao.java:1479)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:122)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:56)
	at com.mirth.connect.donkey.server.channel.Channel$DeployTask.updateMetaDataColumns(Channel.java:1824)
	at com.mirth.connect.donkey.server.channel.Channel$DeployTask.call(Channel.java:1731)
	at com.mirth.connect.donkey.server.channel.Channel$DeployTask.call(Channel.java:1706)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 moreCaused by: org.postgresql.util.PSQLException: ERROR: column "MESSAGE_ID" of relation "d_mcm1" already exists
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:372)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:300)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.addMetaDataColumn(JdbcDao.java:1473)
	... 10 more`

The UI shouldn't even allow users to type in those reserved columns.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3410
Reporter: narupley
Created: 2014-08-18T08:38:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Currently, if you create a Custom Metadata column with the same name as an existing column, you are warned upon saving. Should this operate in the same fashion, checking the reserved names upon saving, or should it completely disallow the user from adding in one of these reserved column names at the time of entry?

Imported Comment. Original Details:
Author: jaysenp
Created: 2014-10-09T15:22:28.000-0700

**Comment by rbeckman-nextgen** [comment]
I would lean towards prompting on save. That way the user would know **why** it's not letting them save the channel. "MESSAGE_ID" seems ubiquitous enough that some people would probably try to use it, and if we just disallowed that column name with a custom cell editor, users wouldn't know why, and would probably think it to be a bug.

Imported Comment. Original Details:
Author: narupley
Created: 2014-10-09T15:31:42.000-0700

**Comment by rbeckman-nextgen** [comment]
For consistency's sake, do it on save and show a specific message indicating which column name is reserved. There is some precedence for showing the warning message immediately after editing the column name. I think we do it for some of the alert stuff. But we'll just do it on save here to be consistent with this page.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-10-09T17:24:04.000-0700

**Comment by rbeckman-nextgen** [comment]
We are now checking all table entries against the reserved database table column names and warning upon saving if any are found.

Imported Comment. Original Details:
Author: jaysenp
Created: 2014-10-29T17:22:00.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that users are no longer able to add reserved column names in the UI. It doesn't work for migrated channels because no validation is done server-side though, but that's probably fine. 

Imported Comment. Original Details:
Author: narupley
Created: 2014-11-10T09:55:23.000-0800
