### ISSUE TITLE
HTTP Sender throws NullPointerException if a 204 response is received

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3326]
If a 200 response is received with no payload that's fine, since there will still be an entity body (albeit a blank one). However if a 204 response is received, there's _**no**_ entity whatsoever. At the HttpComponents level, httpResponse.getEntity() returns null. Because of that, the dispatcher is incorrectly throwing a NullPointerException.
\\
\\
A temporary workaround for 3.x:
\\
\\
* Set response data types to Raw to unlock hidden achievement "Always Run Response Transformer"

* Put this in the response transformer: `if (/.**java\.lang\.NullPointerException.**/.test(responseErrorMessage)) {
	responseStatus = SENT;
	responseStatusMessage = 'No Content';
}`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3425
Reporter: narupley
Created: 2014-08-29T08:36:45.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revision 7317. When the entity itself is null, an empty string is used for the response data.

Imported Comment. Original Details:
Author: narupley
Created: 2014-08-29T08:38:30.000-0700

**Comment by rbeckman-nextgen** [comment]
Confirmed npe no longer thrown on 204 response.

Old channel error:
`
HTTP Sender error
ERROR MESSAGE: Error connecting to HTTP server
java.lang.NullPointerException
	at java.lang.String.<init>(String.java:481)
	at com.mirth.connect.connectors.http.HttpDispatcher.send(HttpDispatcher.java:195)
`

Successful dispatch response:
`
<HttpResponse>
    <Status>HTTP/1.1 204 No Content</Status>
    <Header>
        <Field>
            <Name>Content-Type</Name>
            <Value>text/plain</Value>
        </Field>
        <Field>
            <Name>Server</Name>
            <Value>Jetty(7.6.7.v20120910)</Value>
        </Field>
    </Header>
    <Body multipart="no"/>
</HttpResponse>
`


Imported Comment. Original Details:
Author: eduardoa
Created: 2014-08-29T17:33:26.000-0700
