### ISSUE TITLE
Retrieving the next message Id is not atomic for all databases

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3333]
SQL Server, MySQL, and Derby use two separate queries which is not atomic. This isn't a problem for a single MC server because the query is never called simultanously. However if multiple MC servers are connecting to the same database then they could each retrieve the same message Id. 

Probably the best way to handle it is to use an auto increment column and to use the JDBC RETURN_GENERATED_KEYS option, but unfortunately this would be a very difficult migration problem. 

One other option is to create a table with only an auto increment column and use RETURN_GENERATED_KEYS. Since this would be inserting a new record per ID, we would have to clean up the table periodically or after each ID.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3432
Reporter: wayneh
Created: 2014-09-02T16:05:46.000-0700

**Comment by rbeckman-nextgen** [comment]
The operation to retrieve the next message ID is now atomic for SQL Server, MySQL and Derby.

Sequences are now held in a D_MSQ[localChannelId] table for each channel and the D_MESSAGE_SEQUENCES table has been removed.

Selecting the next message ID now obtains an update lock on the sequence row, which will prevent two concurrent connections from selecting and updating the sequence value at the same time.

Separate sequence tables for each channel are necessary for SQL Server, since SQL Server may sometimes escalate a row lock to a page or table lock, even if the ROWLOCK hint is given. If that were to happen in a single, shared sequence table, one channel may block other channels and degrade performance.

Migration code has been added to migrate the old sequence values to the new sequence tables.

Imported Comment. Original Details:
Author: brentm
Created: 2014-09-18T11:00:49.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that key constraint errors no longer happen when processing a message at the same time on two different servers. Also tested migration and verified that the old sequences table is correctly migrated to the channel-specific tables.

Imported Comment. Original Details:
Author: narupley
Created: 2014-09-25T12:15:22.000-0700

**Comment by rbeckman-nextgen** [comment]
When upgrading from 2.x the D_MESSAGE_SEQUENCES table will not exist which causes an exception thrown during migration.

{quote}
com.mirth.connect.model.util.MigrationException: Failed to migrate message sequences.
	at com.mirth.connect.server.migration.Migrate3_1_0.migrateMessageSequences(Migrate3_1_0.java:94)
	at com.mirth.connect.server.migration.Migrate3_1_0.migrate(Migrate3_1_0.java:36)
	at com.mirth.connect.server.migration.ServerMigrator.migrate(ServerMigrator.java:64)
	at com.mirth.connect.server.controllers.DefaultMigrationController.migrate(DefaultMigrationController.java:90)
	at com.mirth.connect.server.Mirth.startup(Mirth.java:236)
	at com.mirth.connect.server.Mirth.run(Mirth.java:163)
Caused by: java.sql.SQLSyntaxErrorException: Table/View 'D_MESSAGE_SEQUENCES' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver40.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.ibatis.datasource.pooled.PooledConnection.invoke(PooledConnection.java:246)
	at com.sun.proxy.$Proxy8.prepareStatement(Unknown Source)
	at com.mirth.connect.server.migration.Migrate3_1_0.migrateMessageSequences(Migrate3_1_0.java:75)
	... 5 more
Caused by: java.sql.SQLException: Table/View 'D_MESSAGE_SEQUENCES' does not exist.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory40.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 24 more
Caused by: ERROR 42X05: Table/View 'D_MESSAGE_SEQUENCES' does not exist.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindTableDescriptor(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromBaseTable.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.FromList.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.SelectNode.bindNonVTITables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bindTables(Unknown Source)
	at org.apache.derby.impl.sql.compile.DMLStatementNode.bind(Unknown Source)
	at org.apache.derby.impl.sql.compile.CursorNode.bindStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 18 more
{quote}

Imported Comment. Original Details:
Author: wayneh
Created: 2014-09-30T13:52:18.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed the message sequence migration so that it only performs the migration if the D_MESSAGE_SEQUENCES table exists. If the user is migrating from version 2.x or if no channels had been previously deployed, then this table would not exist and the migration would throw an exception without this added check.

Imported Comment. Original Details:
Author: brentm
Created: 2014-09-30T16:13:45.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified that migration now works if the D_MESSAGE_SEQUENCES table does not exist.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-10-01T14:20:46.000-0700
