### ISSUE TITLE
Require Java 7 for Mirth Connect

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3348]
Many of the libraries we use are starting to reduce support for Java 6 and we've had some issues that are only fixed in Java 7 and above as well. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3448
Reporter: wayneh
Created: 2014-09-10T15:25:03.000-0700

**Comment by rbeckman-nextgen** [comment]
3.2.0 is now the target release version for this change.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-10-28T16:49:23.000-0700

**Comment by rbeckman-nextgen** [comment]
Once this is done, we can remove TLSv1 from the list of default supported TLS protocols (MIRTH-3492).

Imported Comment. Original Details:
Author: narupley
Created: 2014-11-07T10:12:53.000-0800

**Comment by rbeckman-nextgen** [comment]
Right now the only problem with this is the BouncyCastle jar will not run under webstart when built with Java 7. The following exception occurs

`
java.io.IOException: invalid SHA1 signature file digest for org/bouncycastle/jcajce/provider/digest/Whirlpool$Digest.class
	at com.sun.deploy.cache.CacheEntry$10.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.deploy.cache.CacheEntry.writeFileToDisk(Unknown Source)
	at com.sun.deploy.cache.CacheEntry.writeFileToDisk(Unknown Source)
	at com.sun.deploy.cache.Cache.downloadResourceToTempFile(Unknown Source)
	at com.sun.deploy.cache.Cache.downloadResourceToCache(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.actionDownload(Unknown Source)
	at com.sun.deploy.net.DownloadEngine.downloadResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.deploy.cache.ResourceProviderImpl.getResource(Unknown Source)
	at com.sun.javaws.LaunchDownload$DownloadTask.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
`

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-02T17:08:19.000-0800

**Comment by rbeckman-nextgen** [comment]
Others have had this problem but with no solution
http://bouncy-castle.1462172.n4.nabble.com/Version-1-50-WebStart-signature-not-verified-td4656642.html

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-02T17:15:25.000-0800

**Comment by rbeckman-nextgen** [comment]
Oh look. Someone on our forums found the answer for us.
http://www.mirthcorp.com/community/forums/showthread.php?t=11228

> In this post they detected that the default sigining algorithm was changed from SHA-1 to SHA-256 between Java 6 and Java 7. In some jars, the Manifest file contained two signatures, one for SHA1 and one for SHA256. The solution was to adjust the jar signer to explicitly use SHA1 as digest algorithm.


Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-02T17:30:47.000-0800

**Comment by rbeckman-nextgen** [comment]
For this issue, on our release notes / upgrade guide / wiki pages somewhere we should have a compatibility matrix showing various versions of Mirth Connect and what versions of Java are supported. People still get confused on the forums about this. IIRC official Java 7 support started with 2.2.1.

As a side note, might also be useful for supported backend database versions.

Imported Comment. Original Details:
Author: narupley
Created: 2014-12-03T09:01:31.000-0800

**Comment by rbeckman-nextgen** [comment]
-Looks like BouncyCastle 1.51 fixes the issue without requiring us to downgrade the digestalg. We should update that instead (MIRTH-3540).-

On testing again this is not the case. See MIRTH-3540 for more information.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-03T09:59:54.000-0800

**Comment by rbeckman-nextgen** [comment]
Building with Java 7 fails for me in Eclipse on OSX:

`jspc:

BUILD FAILED
/Users/nickr/Documents/Eclipse 4/workspace/Server/mirth-build.xml:30: The following error occurred while executing this line:
/Users/nickr/Documents/Eclipse 4/workspace/webadmin/build.xml:47: org.apache.jasper.JasperException: PWC6149: The -uriroot option must specify a pre-existing directory`

Could be related to this: [GLASSFISH-17429](https://java.net/jira/browse/GLASSFISH-17429)

Imported Comment. Original Details:
Author: narupley
Created: 2014-12-09T09:45:28.000-0800

**Comment by rbeckman-nextgen** [comment]
I think I found the problem to the above. The WebAdmin project points to this container in its classpath:

`<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.6">
	<attributes>
		<attribute name="owner.project.facets" value="java"/>
	</attributes>
</classpathentry>`

It looks like several extensions also still point to the same JavaSE-1.6 path.

Imported Comment. Original Details:
Author: narupley
Created: 2014-12-09T11:28:05.000-0800

**Comment by rbeckman-nextgen** [comment]
The JspC call specified compiler vm 1.6 as well. 

`
<target name="jspc" depends="init">
		<taskdef classname="org.apache.jasper.JspC" name="jasper2" classpathref="compile.jspc" />
		<jasper2 validateXml="false"
            uriroot="${webadmin}/${build.web}"
            addWebXmlMappings="true"
            webXmlFragment="${webadmin}/${build.web}/WEB-INF/generated_web.xml"
            compilerSourceVM="1.6"
            compilerTargetVM="1.6"
            outputDir="${webadmin}/${build.src}"
            verbose="9" />
	</target>
`

So did it work for you after you changed the classpath?

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-09T11:41:24.000-0800

**Comment by rbeckman-nextgen** [comment]
It did, even without changing anything in the actual build file. In fact if I try to change it to 1.7 it fails with:

`jspc:

BUILD FAILED
/Users/nickr/Documents/Eclipse 2/workspace/Server/mirth-build.xml:30: The following error occurred while executing this line:
/Users/nickr/Documents/Eclipse 2/workspace/webadmin/build.xml:47: java.lang.IllegalArgumentException: PWC6309: Illegal compilerSourceVM: 1.7`

Imported Comment. Original Details:
Author: narupley
Created: 2014-12-09T11:43:38.000-0800

**Comment by rbeckman-nextgen** [comment]
I get the same error if I change the build file to 1.7

It's the same error mentioned in https://netbeans.org/bugzilla/show_bug.cgi?id=201414, which is linked in the original link you added.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-09T11:45:44.000-0800

**Comment by rbeckman-nextgen** [comment]
Updated the WebAdmin classpath to not reference Java 6 directly. 

However, for the build file we will be leaving the compilerSourceVM and compilerTargetVM as 1.6 for the time being. So far, it does not appear to have any ill effect.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-15T08:25:59.000-0800

**Comment by rbeckman-nextgen** [comment]
As far as I can tell the builds are working fine with Java 7 now.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-09T17:19:30.000-0800

**Comment by rbeckman-nextgen** [comment]
We've been building with Java 7 for a while now and have already started using Java 7 specific libraries and syntax so there's no chance we're still accidentally building with Java 6. The builds have been tested on both Java 7 and Java 8 and everything looks stable.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-15T18:10:33.000-0800
