### ISSUE TITLE
Improve Channel tag management UI

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3395]
* Add ability to specify a color for each tag
* Don’t use a pop-up dialog anymore, something inline, like an editable table for example
* Tags should be sortable
* Should retain the ability to autocomplete as they start typing
* Evaluate whether or not we should move this out of the channel summary screen and into it’s own tab/panel somewhere, that way the user can manage tags for multiple channels at once
* At the same time, also keep in mind how this may relate to or overlap with the new channel group feature that will also be added (MIRTH-1243)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3498
Reporter: wayneh
Created: 2014-10-22T12:50:08.000-0700

**Comment by rbeckman-nextgen** [comment]
Test Result from Oct 26th using JRE version 1.8.0_111-b14
||Test Scenario / Description||Status||Issue
||TAGS view||
|Able to add tag|passed| |
|Able to remove tag|passed| |
|Able to select / deselect / select all /select all channels|passed| |
|Able to filter Channels (Tags View)|passed| |
|Able to sort Tag name and available columns|passed| |
|Able to view Channel Count|passed| |
|Able to apply Background/Foreground|passed| |
||CHANNELS view||
|Able to switch between Tag Text & Tag icons|passed| |
|Able to Filter by Tag in Channel view|passed| |
|Able to create new tag from new Channel|passed | |
|Import Channel Groups and verify Tags being imported|passed| |
|Import Channel and verify Tags being imported|passed| |
|Export Channel and verify Tag information included in xml file|passed| |
||USER AUTH||
|Create user with Manage Tags Role|passed|
|Login as user and verify role|passed|limited if user without channel view permission|
||DASHBOARD view
|Able to Filter by Tag or Channel in Dashboard|passed| |
|Able to switch Dashboard view with Tags for Cluster vs Node|passed| |
|Able to remove tag of deployed channel, Dashboard update, no rev |passed| |
|Able to add tag of deployed channel,Dashboard update, no rev |passed| |


Imported Comment. Original Details:
Author: minht
Created: 2016-11-09T13:26:02.000-0800

**Comment by rbeckman-nextgen** [comment]
PENDING ISSUES 
**using latest Java update (Window platform)**
*  Import will cut off long tags, maintaining 12 digits max => resulting in “un-intended” same tag if the differences were at 12 digits or after
*  Import will remove tags with special characters or space from older channels => loss of tags during upgrade
*  Duplicate tags
** Create Tag1,Tag2,Tag3 from Tags View
** Create new channel or edit existing channel, apply “tag3” by copy and paste the name from text editor, Save Changes
** Check Channel View for list of tag names
** Go to Tags View to verify if “tag3” and “Tag3” both exist

**using older JRE version 1.8.0_66-b17 (on Ubuntu)**
* Cannot assign Tag from Channel View
* Cannot view Tag from Channel View
* Cannot Filter in Channel View
* Cannot Filter in Dashboard
* Exception on java console after launching MC
`Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: ReferenceError: Can't find variable: $
	at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:128)
	at com.sun.webkit.dom.JSObject.callImpl(Native Method)
	at com.sun.webkit.dom.JSObject.call(JSObject.java:98)
	at com.mirth.connect.client.ui.components.tag.MirthTagWebBrowser$2.run(MirthTagWebBrowser.java:130)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745) `





Imported Comment. Original Details:
Author: minht
Created: 2016-11-09T13:29:23.000-0800

**Comment by rbeckman-nextgen** [comment]
ROCKSOLID-6 Tag / Filter Improvements
ROCKSOLID-47

Imported Comment. Original Details:
Author: minht
Created: 2017-01-17T14:14:21.000-0800
