### ISSUE TITLE
Duplicate key violation after removing results on a channel with messages queued on source

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3437]
To reproduce, blast messages at a channel with source queueing turned on and let messages queue up on the source. Then go to the message browser and remove results. This error should appear after at least a few tries.

{noformat}
ERROR 2014-12-03 10:29:31,148 [Thread-23] com.mirth.connect.donkey.server.channel.Channel: An error occurred in channel TCP Listener 1 (57bd25e4-1142-4f3d-86be-490e57dad496) while processing message ID 1578 from the source queue
com.mirth.connect.donkey.server.data.DonkeyDaoException: Failed to insert connector message meta data
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMetaData(JdbcDao.java:507)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:102)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:56)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1604)
	at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1738)
	at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1725)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "d_mcm3_pkey"
  Detail: Key (message_id, metadata_id)=(1578, 0) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:365)
	at com.zaxxer.hikari.proxy.PreparedStatementJavassistProxy.executeUpdate(PreparedStatementJavassistProxy.java)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.insertMetaData(JdbcDao.java:504)
	... 7 more
{noformat}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3541
Reporter: brentm
Created: 2014-12-03T11:02:05.000-0800

**Comment by rbeckman-nextgen** [comment]
A similar thing happens if the destination connector has a queued message that is removed. However we catch the exception and indicate in the log that "This error is expected if the message was manually removed from the queue." in that case. In lieu of preventing users from deleting queued messages, we could also try to catch this type of exception for the source queue. However maybe we should look into not allowing deleting a queued message unless the channel is stopped.

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-22T19:15:39.000-0800

**Comment by rbeckman-nextgen** [comment]
Unable to reproduce this anymore, will have to do testing again to see whether this is still an issue or not

Imported Comment. Original Details:
Author: narupley
Created: 2018-11-19T13:05:41.000-0800
