### ISSUE TITLE
Allow more source connectors in binary mode to store attachments

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3445]
See MIRTH-2799 for additional discussion. Basically, one things users ask for is "How do I read in a PDF in binary mode and store it as an attachment?" Right now since the regex/JavaScript attachment handlers don't support binary data, there's no non-hacky way to accomplish that.

When the message comes in as a byte array, I doubt that users are going to need to parse through the array and only take out a certain part of it or something like that. DICOM is the exception, but we already have a dedicated handler for that. That said, maybe there should be a separate handler specifically to store all the incoming data as an attachment. We should still automatically Base64 encode it first since that's our standard for how to store attachment data.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3549
Reporter: narupley
Created: 2014-12-15T07:52:45.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 8086: The Regex and JavaScript attachment handlers now support binary data. When a binary message is received the bytes are simply converted to a Base64 string first and that is used for the incoming message.


Imported Comment. Original Details:
Author: narupley
Created: 2016-07-13T12:29:01.000-0700

**Comment by rbeckman-nextgen** [comment]
**Test environment (OS(s) and JRE version):** virtual Window 7 with JRE version 1.8.0_91-b14
**Version(s)/Build(s) to test new features:** mirthconnect-3.5.0.8088.b2012-windows-x64
**What being tested:**
* Create new channel with Source = File Reader & Destination = Channel Writer
** Source connector > File Reader setting: File Name pattern = *.pdf & File Type = Binary
*** Channel Summary > Properties > Attachment = REGEX ` set "([\s\S]**)" as the regex `
** Save & Deploy channel
* Provide several pdf files for this channel to read from
* Verify number of msg received and sent to match number of pdf files
* Select to View Messages > on Attachments tab > select to View Attachment
* Repeat with Channel Summary > Properties > Attachment = Javascript, `return addAttachment(message, 'application/pdf'); `

**Observation:**
Able to view attachment (pdf file) when using Regex & JS attachment handlers

**Additional Info:**
Before, this channel would fail to process any message with the following error in server.log
`[2016-07-15 13:36:02,401]  ERROR (com.mirth.connect.donkey.server.channel.Channel:1395): Error processing attachments for channel mirth3549-javascript handler (91c7a745-4b79-454c-89c8-8bb05b768e25).
com.mirth.connect.donkey.model.message.attachment.AttachmentException: Binary data not supported for Regex attachment handler
	at com.mirth.connect.server.attachments.regex.RegexAttachmentHandler.initialize(RegexAttachmentHandler.java:42)
	at com.mirth.connect.donkey.server.channel.Channel.createAndStoreSourceMessage(Channel.java:1376)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1179)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:170)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:354)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:247)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:203)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) `

Imported Comment. Original Details:
Author: minht
Created: 2016-07-15T14:14:29.000-0700

**Comment by rbeckman-nextgen** [comment]
FYI with JavaScript you'd actually want to return the attachment replacement token, not the attachment itself:

`return addAttachment(message, 'application/pdf').getAttachmentId();`

Imported Comment. Original Details:
Author: narupley
Created: 2016-07-15T14:18:36.000-0700

**Comment by rbeckman-nextgen** [comment]
Zup i see the difference now 
the raw message from my return statement => ` com.mirth.connect.server.userutil.Attachment@36df7069 `
the raw message from your return statement  => ` ${ATTACH:b44b6b2f-304b-4b41-90d7-f5646253efcc} `

Imported Comment. Original Details:
Author: minht
Created: 2016-07-15T16:18:45.000-0700
