### ISSUE TITLE
Message Archiver error: Could not write file, Ran out of memory retrieving query results

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3447]
I am trying to setup message archiving on a client site. I am getting this error on two channels:

ERROR 2014-12-15 00:01:44,888 [pool-2-thread-558] com.mirth.connect.server.userutil.SerializerFactory: The getHL7Serializer() method is deprecated and will soon be removed. Please use the "Convert HL7 v2.x" templates from the References tab instead. Look at the tooltips to see the available property keys. The new method will strip namespaces by default unless the 'stripNamespaces' property is set to false.
ERROR 2014-12-15 00:06:02,487 [Thread-564] com.mirth.connect.plugins.datapruner.DataPruner: Failed to prune messages for channel CDM to Mirth Results - OLD (c547bf4b-ccb2-4da9-a976-65a8653bcd52). Attempts remaining: 3.
com.mirth.connect.plugins.datapruner.DataPrunerException: com.mirth.connect.util.MessageExporter$MessageExportException: com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:553)
	at com.mirth.connect.plugins.datapruner.DataPruner.pruneChannel(DataPruner.java:429)
	at com.mirth.connect.plugins.datapruner.DataPruner.run(DataPruner.java:301)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mirth.connect.util.MessageExporter$MessageExportException: com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:537)
	... 3 more
Caused by: com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.getMessageContent(JdbcDao.java:2031)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.getConnectorMessageFromResultSet(JdbcDao.java:1993)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.getConnectorMessages(JdbcDao.java:1452)
	at com.mirth.connect.plugins.datapruner.DataPruner.getMessagesForArchive(DataPruner.java:579)
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:515)
	... 3 more
Caused by: org.postgresql.util.PSQLException: Ran out of memory retrieving query results.
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1898)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:304)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.getMessageContent(JdbcDao.java:2015)
	... 7 more
Caused by: java.lang.OutOfMemoryError: Java heap space
ERROR 2014-12-15 00:09:20,166 [Thread-564] com.mirth.connect.plugins.datapruner.DataPruner: Failed to prune messages for channel CDM to Mirth Results - OLD (c547bf4b-ccb2-4da9-a976-65a8653bcd52). Attempts remaining: 2.
com.mirth.connect.plugins.datapruner.DataPrunerException: com.mirth.connect.util.MessageExporter$MessageExportException: Failed to export message: Could not write to "file:///folders/archive/messages/2014-12-15-00-00-00/.c547bf4b-ccb2-4da9-a976-65a8653bcd52/2014-02-28 11:55:53.819.hl7" because it is currently in use.
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:553)
	at com.mirth.connect.plugins.datapruner.DataPruner.pruneChannel(DataPruner.java:429)
	at com.mirth.connect.plugins.datapruner.DataPruner.run(DataPruner.java:301)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mirth.connect.util.MessageExporter$MessageExportException: Failed to export message: Could not write to "file:///folders/archive/messages/2014-12-15-00-00-00/.c547bf4b-ccb2-4da9-a976-65a8653bcd52/2014-02-28 11:55:53.819.hl7" because it is currently in use.
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:527)
	... 3 more
Caused by: org.apache.commons.vfs2.FileSystemException: Could not write to "file:///folders/archive/messages/2014-12-15-00-00-00/.c547bf4b-ccb2-4da9-a976-65a8653bcd52/2014-02-28 11:55:53.819.hl7" because it is currently in use.
	at org.apache.commons.vfs2.provider.DefaultFileContent.getOutputStream(DefaultFileContent.java:457)
	at com.mirth.connect.util.messagewriter.MessageWriterVfs.write(MessageWriterVfs.java:142)
	at com.mirth.connect.util.messagewriter.MessageWriterArchive.write(MessageWriterArchive.java:52)
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:521)
	... 3 more
ERROR 2014-12-15 00:11:45,482 [Thread-564] com.mirth.connect.plugins.datapruner.DataPruner: Failed to prune messages for channel CDM to Mirth Results - OLD (c547bf4b-ccb2-4da9-a976-65a8653bcd52). Attempts remaining: 1.
com.mirth.connect.plugins.datapruner.DataPrunerException: com.mirth.connect.util.MessageExporter$MessageExportException: Failed to export message: Could not write to "file:///folders/archive/messages/2014-12-15-00-00-00/.c547bf4b-ccb2-4da9-a976-65a8653bcd52/2014-02-28 11:55:53.819.hl7" because it is currently in use.
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:553)
	at com.mirth.connect.plugins.datapruner.DataPruner.pruneChannel(DataPruner.java:429)
	at com.mirth.connect.plugins.datapruner.DataPruner.run(DataPruner.java:301)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mirth.connect.util.MessageExporter$MessageExportException: Failed to export message: Could not write to "file:///folders/archive/messages/2014-12-15-00-00-00/.c547bf4b-ccb2-4da9-a976-65a8653bcd52/2014-02-28 11:55:53.819.hl7" because it is currently in use.
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:527)
	... 3 more
Caused by: org.apache.commons.vfs2.FileSystemException: Could not write to "file:///folders/archive/messages/2014-12-15-00-00-00/.c547bf4b-ccb2-4da9-a976-65a8653bcd52/2014-02-28 11:55:53.819.hl7" because it is currently in use.
	at org.apache.commons.vfs2.provider.DefaultFileContent.getOutputStream(DefaultFileContent.java:457)
	at com.mirth.connect.util.messagewriter.MessageWriterVfs.write(MessageWriterVfs.java:142)
	at com.mirth.connect.util.messagewriter.MessageWriterArchive.write(MessageWriterArchive.java:52)
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:521)
	... 3 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3551
Reporter: dans
Created: 2014-12-15T09:06:27.000-0800

**Comment by rbeckman-nextgen** [comment]
How much memory is allocated on the server? The archiver currently retrieves 1000 messages at a time. If they are large messages then they could run out of memory. There is already an issue to make the archive batch size configurable (MIRTH-3531). For now is it possible to increase the server's heap size?

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-15T09:10:30.000-0800

**Comment by rbeckman-nextgen** [comment]
Heap for MC is set to 3GB. I can't increase it anymore. I started message archiving about a week ago and it keeps failing on two channels everyday. 

Imported Comment. Original Details:
Author: dans
Created: 2014-12-15T09:15:12.000-0800

**Comment by rbeckman-nextgen** [comment]
In the meantime, unfortunately there's no fix, either the heap size must be increased or archiving cannot happen. You could also change the content from XML to Source Raw or something, so that less data will be archived.

Imported Comment. Original Details:
Author: narupley
Created: 2014-12-15T09:23:01.000-0800

**Comment by rbeckman-nextgen** [comment]
The "currently in use" message is due to (MIRTH-3205). Both will be fixed in 3.2.

You could disable archiving for those two channels for the time being if the other channels work fine. You could also try lowering the message storage settings down to "Production" for those channels if it isn't already and see if that does it. Keep in mind that depending on the state of the server the amount of available memory could change each time the archiver runs. 

Imported Comment. Original Details:
Author: wayneh
Created: 2014-12-15T09:28:19.000-0800
