### ISSUE TITLE
Error thrown when stopping an http receiver with initial state paused

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3452]
1. Create a channel with an http receiver and initial state "paused".
2. Deploy the channel
3. Stop the channel
=> the following error is thrown:

----------

[2014-12-19 10:13:08,325]  ERROR (com.mirth.connect.donkey.server.channel.Channel:901): Error stopping Source connector for channel XXX (ed5e3bec-85b4-4ac0-9c04-234c76483311).
com.mirth.connect.donkey.server.ConnectorTaskException: Failed to stop HTTP Listener
	at com.mirth.connect.connectors.http.HttpReceiver.onStop(HttpReceiver.java:258)
	at com.mirth.connect.donkey.server.channel.SourceConnector.stop(SourceConnector.java:121)
	at com.mirth.connect.donkey.server.channel.Channel.stop(Channel.java:897)
	at com.mirth.connect.donkey.server.channel.Channel.stop(Channel.java:697)
	at com.mirth.connect.server.controllers.DonkeyEngineController$UndeployTask.execute(DonkeyEngineController.java:1287)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:59)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

----------

The reason is an hidden NullpointerException thrown by line 256:
server.stop();

Indeed, since the connector has never been started, the "server" variable is not initialized (null).

----------

Correction => add a statement like:

if (server != null) server.stop();

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3556
Reporter: daniel
Created: 2014-12-19T04:24:43.000-0800

**Comment by rbeckman-nextgen** [comment]
The problem occurs on standby Mirth Appliances in a cluster, since the http connector have a paused initial state in this case. Whenever a synchronization happens, the channel is stopped and such an error is thrown. Beside confusing the users, it probably has no negative side effects.

Imported Comment. Original Details:
Author: daniel
Created: 2014-12-19T04:28:19.000-0800

**Comment by rbeckman-nextgen** [comment]
This also has the consequence that undeploying a channel fails first - the channel remains deployed in the state "stopped".
A second undeploy task is needed for the undeployment to happen really.

Imported Comment. Original Details:
Author: daniel
Created: 2014-12-19T05:48:46.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 7498/7499.

Imported Comment. Original Details:
Author: narupley
Created: 2014-12-19T06:36:37.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified this issue existed in older builds. This no longer happens as of 3.2.

Imported Comment. Original Details:
Author: jaysenp
Created: 2015-01-19T17:56:05.000-0800
