### ISSUE TITLE
Improve archiver performance for channels with large amount of messages stored

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3476]
The query that the archiver runs with the block size (that will be made user configurable with MIRTH-3531) does not scale down well when the block size is lowered. This will cause extremely slow performance if that value is lowered for memory concerns.

Instead that query should only be called with large block sizes. We should be using that query to only retrieve message Ids and then simply retrieve each message individually. We're already retrieving connector messages and content individually for each message so we can add one more query to obtain the message object. When this is done there is no need for a block size anymore as only a single message will be cached at a time. Therefore we can probably revert MIRTH-3531 at that time.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3581
Reporter: wayneh
Created: 2015-01-20T18:08:39.000-0800

**Comment by rbeckman-nextgen** [comment]
I want to point out that archiver performance is partially based on the number of connector metadata messages there are. For instance if there are 1,000,000 messages with metadata but only 100,000 of those messages actually have content, then the archiver still has to check all 1,000,000 messages each time it is run to verify that there is no content that can be archived. This is one explanation for seeing a long archive time when the number of messages actually archived is fairly low. However hopefully with these changes the performance is good enough even with this limitation.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-21T14:29:09.000-0800

**Comment by rbeckman-nextgen** [comment]
The algorithm used to archive messages has been updated. -We are now only caching a single message at any given time which means heap usage should not be an issue anymore-. Furthermore, the batching query when used with a low limit incurs a lot of overhead and dramatically slows down archiving. Therefore we are now running the batching query for archiving with the same limit as if only the pruner was running (100000). This only retrieves message Ids and received dates. Then for each message Id we retrieve the message and content and write the message out immediately. So far it seems that it can save a significant amount of time if there are lots of messages stored for a given channel

Note to testers:  You'll need to test lots of different configurations of channels, metadata/content prune days, and archiver settings (ie. content type, compressed, etc) to verify that the archived results are expected in each of those different scenarios.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-21T14:30:29.000-0800

**Comment by rbeckman-nextgen** [comment]
Actually we are now actually retrieving multiple messages with a single query for each table (d_m, d_mm, d_mc, d_mcm) so setting a block size will in fact improve performance now. It's still important to test many different archiving configurations as mentioned above to ensure the output has not changed unintentionally.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-26T13:15:03.000-0800

**Comment by rbeckman-nextgen** [comment]
A NPE was encountered when manually starting up the Data Pruner/Archiver. Steps to reproduce are as follows:
1. Create a channel with the following settings: Remove Content on Completion, Prune metadata/content set to 0 days.
2. Deploy and dispatch a message.
3. Edit this channel and then remove the 'Remove Content on Completion' flag from before. 
4. Deploy and dispatch a message. There should now be two messages, one without content and one with content.
5. Run the archiver and refresh.

This channel should have failed to prune/archive.

[2015-01-26 16:11:04,542]  ERROR (com.mirth.connect.plugins.datapruner.DataPruner:342): Failed to prune messages for channel pruner take 2 (50377dc9-7758-412d-8c37-19e5f1fd4d46).
java.lang.NullPointerException
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.getMessages(JdbcDao.java:1430)
	at com.mirth.connect.plugins.datapruner.DataPruner.archiveAndGetIdsToPrune(DataPruner.java:565)
	at com.mirth.connect.plugins.datapruner.DataPruner.pruneChannel(DataPruner.java:445)
	at com.mirth.connect.plugins.datapruner.DataPruner.run(DataPruner.java:312)
	at java.lang.Thread.run(Thread.java:744)

Imported Comment. Original Details:
Author: jaysenp
Created: 2015-01-26T16:22:06.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed NullPointerException when archiving if no source encoded content exists. In this case we should not bother trying to set the destination raw.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-26T16:26:33.000-0800

**Comment by rbeckman-nextgen** [comment]
I tested this issue across multiple databases using the default block size (which at the time was 1000 rows) and compared this to the same data set using 3.1.X by importing the messages back into a test channel. It seems in each case, the pruner was about twice as fast as before. The data used for comparison sake was a mix of hl7 messages and messages with content removed on completion.

No NPEs were encountered over the course of this test.

Imported Comment. Original Details:
Author: jaysenp
Created: 2015-02-02T15:55:45.000-0800
