### ISSUE TITLE
Alert Channel missing in Mirth 3.0.3

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3477]
I am using 3.0.3.7171 version. Our server has Windows 2012 Operating System. I have created an Alert under the Alerts tab. Under the 'Settings' tab I have configured the Alerts settings.
The Alert system was working perfectly. However, suddenly I don't see the Alert Channel anymore on the right panel. When I tried to create a new Alert channel with the same name, it says the Alert Channel already exists. If I right Click on the right panel, I see the option - Refresh, New Alert, Import Alert, Export All Alerts. If I try Export All Alerts, I am able to export the existing alert.

Its strange that I don't see the Alert channel on the right panel. Its Blank.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3582
Reporter: jagadish0912
Created: 2015-01-21T00:55:37.000-0800

**Comment by rbeckman-nextgen** [comment]
I have attached the Settings and Alert screen shots. On the Alert Tab, the right panel is Blank. Its has 3 Alert Channels but not visible. If I export Alll Alerts, I see the xml files.

Imported Comment. Original Details:
Author: jagadish0912
Created: 2015-01-21T01:05:25.000-0800

**Comment by rbeckman-nextgen** [comment]
Please check your log file and see if there is any information contained there.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-21T05:49:27.000-0800

**Comment by rbeckman-nextgen** [comment]
Hello Wayne,
Thank you for your quick response.
I saw the log file, it actually does not log an error.

I copying a section of log file here:

ERROR 2015-01-21 01:09:18,529 [qtp2001463498-35] com.mirth.connect.server.servlets.AlertServlet: com.mirth.connect.server.controllers.ControllerException: org.apache.ibatis.exceptions.PersistenceException: 
*## Error querying database.  Cause: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLException: I/O Error: Connection reset by peer: socket write error
*## The error may exist in sqlserver/sqlserver-alert.xml
*## The error may involve Alert.getAlert
*## The error occurred while executing a query
*## Cause: org.apache.ibatis.transaction.TransactionException: Error configuring AutoCommit.  Your driver may not support getAutoCommit() or setAutoCommit(). Requested setting: false.  Cause: java.sql.SQLException: I/O Error: Connection reset by peer: socket write error
	at com.mirth.connect.server.controllers.DefaultAlertController.getAlerts(DefaultAlertController.java:156)
	at com.mirth.connect.server.controllers.DefaultAlertController.getAlertStatusList(DefaultAlertController.java:84)
	at com.mirth.connect.server.servlets.AlertServlet.doPost(AlertServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.ibatis.exceptions.PersistenceException: 


I appreciate your help.
Waiting for your response.

Regards,
Jags


Imported Comment. Original Details:
Author: jagadish0912
Created: 2015-01-21T09:41:54.000-0800

**Comment by rbeckman-nextgen** [comment]
Are you using MySql as your database? It's possible that the connection was closed by the server due to the wait_timeout setting. Have you tried restarting the server and seeing if that resolves the issue? If this problem occurs after you are idle for a while, then it may be because of the MyBatis connections not being validated. This has been fixed for 3.2.0 (MIRTH-3484). However you should first see if a MC server restart fixes the problem.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-21T11:05:47.000-0800

**Comment by rbeckman-nextgen** [comment]
I just noticed that you are using SQL Server, however the same suggestions apply. Restarting your server will likely fix things. Most likely the connection that was cached in the MyBatis connection pool was broken somehow and MyBatis is failing to recover it, so MIRTH-3484 is still likely the same issue.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-21T16:11:45.000-0800

**Comment by rbeckman-nextgen** [comment]
Wayne,
Wow restarting the server just resolved the issue. Now, I see the alerts back.

Thank you so much for your advice, Wayne.

Mirth team Rocks !! 

Regards,
Jags

Imported Comment. Original Details:
Author: jagadish0912
Created: 2015-01-21T23:14:16.000-0800
