### ISSUE TITLE
Batch queries randomly throw ArrayIndexOutOfBoundsExceptions with Oracle 12 JDBC Drivers

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3490]
This is really strange. I was randomly getting the following exception on the batch insert queries for Oracle. I tested and verified that the old JDBC driver we were using before MIRTH-3444 does not have this problem. This does not necessarily mean that we want to revert the driver however

`
java.lang.ArrayIndexOutOfBoundsException: -1
	at oracle.jdbc.driver.OraclePreparedStatement.setupDbaBindBuffers(OraclePreparedStatement.java:3528)
	at oracle.jdbc.driver.OraclePreparedStatement.setupBindBuffers(OraclePreparedStatement.java:3046)
	at oracle.jdbc.driver.OraclePreparedStatement.executeBatch(OraclePreparedStatement.java:12194)
	at oracle.jdbc.driver.OracleStatementWrapper.executeBatch(OracleStatementWrapper.java:246)
`

This seemed to occur only when using the HikariCP connection pool at first but once I figured out what was causing it I was able to reproduce it with DBCP. 

There are two reasons why this is occuring.

1. We are caching prepared statements for each connection.
2. The batch and non-batch content insertion queries are using the same cached prepared statement object.

It appears if for a single connection several thousand of the non-batch queries get executed with no batch query in between, then on the next batch query this exception will occur. Since the batch queries occur whenever a message is processed through the source connector, its pretty rare for a connection to have the non-batch query run several thousand times in a row without a batch query running. However it is more likely if queuing is enabled. For some reason, the way Hikari chooses which connection to return makes this issue more likely to occur with it, but ultimately the connection pool is not the cause of the problem at all.

None of the other databases appear to have this problem so it may be a but with the Oracle 12 JDBC drivers. Rather than downgrade, there are two ways we can fix this issue.

1. Duplicate the insertMessageContent query in default.xml and create batchInsertMessageContent so that the batch and non-batch queries will use a different PreparedStatement object
2. Calling PreparedStatement.clearBatch before the batch also appears to fix this problem. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3597
Reporter: wayneh
Created: 2015-01-29T19:29:27.000-0800

**Comment by rbeckman-nextgen** [comment]
oracle pls

Imported Comment. Original Details:
Author: narupley
Created: 2015-01-29T19:43:42.000-0800

**Comment by rbeckman-nextgen** [comment]
You may also want to compile your findings in an Oracle forum post like we did for that PostgreSQL corruption bug. Also since it seems like it's easy to reproduce, we could try testing it out with each successive version of the driver between our current one and the previous one, to isolate which version this issue would have started happening in.

Imported Comment. Original Details:
Author: narupley
Created: 2015-01-29T19:46:53.000-0800

**Comment by rbeckman-nextgen** [comment]
I tried to file a bug report but I couldn't figure out where. I think its behind a login wall for their customers. A forum post is a good idea though.

I've already tested different version of the JDBC driver and it seems like 12.1.0.1 is where it began. I've also tested out using both Oracle 11g and 12c and that appears to be irrelevant. All that matters is the driver. 



Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-30T11:02:20.000-0800

**Comment by rbeckman-nextgen** [comment]
Attaching TestOracleBatch.java which allows us to reproduce the issue outside of Mirth Connect. All you have to do is change the connection properties at the top and set the number of non batch queries to run before the batch query. 20000 will fail and 10000 will succeed.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-30T11:04:06.000-0800

**Comment by rbeckman-nextgen** [comment]
Added a forum post but it needs to be approved before it will become public
https://community.oracle.com/message/12819755#12819755

Imported Comment. Original Details:
Author: wayneh
Created: 2015-01-30T11:15:12.000-0800

**Comment by rbeckman-nextgen** [comment]
Looks like I posted in the General Database forum which was incorrect. Someone mentioned there was a JDBC forum, but neither was the correct place to post bugs (without giving me the correct place to post bugs). I tried to move my thread to the JDBC forum at which point 

{quote}
Moderation Notification

Your content has been rejected: 
{quote}

Quite a stark difference from interactions with the Postgres or HikariCP developers.

Funny because the comment I got was that the forums were for asking questions so I could get help, but since I had already provided a workaround and it wasn't a question anymore, I was not supposed to post there. Seems like they don't want our help, but we tried.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-02T11:07:39.000-0800

**Comment by rbeckman-nextgen** [comment]
Batch queries now have their own cached prepared statement object to prevent strange ArrayIndexOutOfBoundsExceptions with the latest Oracle 12 JDBC drivers.

Also calling clearBatch() after each executeBatch() for good measure in case any implementations do not do so automatically.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-02T13:04:55.000-0800

**Comment by rbeckman-nextgen** [comment]
Closing this as it seems I'm the only person in the world to have experienced it and therefore I am also the foremost expert on fixing it.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-15T18:25:01.000-0800
