### ISSUE TITLE
Unable to halt Web Service Sender if stuck reading at the socket level

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3506]
When the Web Service Sender invokes a dispatch and for whatever reason a connectivity issue causes the remote side to never respond, it's possible to get into a situation where the thread dispatching the message is hung, and cannot even be halted. This is similar to other issues we've seen with the TCP and File (FTP) connectors. Unfortunately in this case it's not as easy, since the dispatching is all done internally by JAX-WS. There's currently no way (that I know of) to grab the underlying socket and force-close it. I think we would have to override some stuff to make that happen, which may be quite an undertaking knowing JAX-WS...

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3614
Reporter: narupley
Created: 2015-02-09T10:15:32.000-0800

**Comment by rbeckman-nextgen** [comment]
FYI there _are_ methods to invoke dispatches asynchronously and return Future objects. But cancelling them would likely have just as much effect as interrupting the socket read thread itself (which is what's currently happening with a halt), which is to say that it would have no effect.

Imported Comment. Original Details:
Author: narupley
Created: 2015-02-09T10:21:27.000-0800

**Comment by rbeckman-nextgen** [comment]
It looks like there is absolutely no way via JAX-WS to grab a handle to the underlying Socket. The most we could do is create a new daemon thread specifically for the dispatch, and then when it fails simply forget about it. In other words, allow a thread leak. We _could_ only do this when the socket timeout is 0, since that's the only time when it's truly non-recoverable.

Imported Comment. Original Details:
Author: narupley
Created: 2015-08-25T09:44:40.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7759: The Web Service Sender will now submit a task to an executor if the socket timeout is 0. Then when the connector is halted, it will shutdown the executor (interrupting all tasks), and log an error to indicate a possible thread leak. This way, the dispatch thread is actually interruptible now, so the connector can actually be halted.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-03T15:24:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Halting the channel while a message is stuck leads to the same log entry twice:

`
ERROR 2015-09-08 17:08:18,281 [pool-13-thread-1] com.mirth.connect.connectors.ws.WebServiceDispatcher: Error halting Web Service Sender: 1 request failed to be halted. This can potentially lead to a thread leak if the requests continue to hang.
ERROR 2015-09-08 17:08:18,386 [pool-13-thread-1] com.mirth.connect.connectors.ws.WebServiceDispatcher: Error halting Web Service Sender: 1 request failed to be halted. This can potentially lead to a thread leak if the requests continue to hang.
`

The message also has a NullPointerException in the error tab
`
Web Service Sender error
ERROR MESSAGE: Error creating web service dispatch
java.lang.NullPointerException
	at com.mirth.connect.connectors.ws.WebServiceDispatcher.send(WebServiceDispatcher.java:555)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:738)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:436)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:155)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1653)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1156)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:529)
	at com.mirth.connect.server.servlets.MessageObjectServlet$2.run(MessageObjectServlet.java:189)
	at java.lang.Thread.run(Thread.java:745)
`

Imported Comment. Original Details:
Author: eduardoa
Created: 2015-09-08T17:12:54.000-0700

**Comment by rbeckman-nextgen** [comment]
In the current state the halt works correctly for endpoint dispatch but the ws sender can still be stuck stopping forever if the wsdl address does not respond. I think this only affects the first message that is sent because the wsdl is cached after that. Not sure if this fix should apply to a unresponsive wsdl location. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2015-09-08T17:17:19.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed all of the above issues. When the initial WSDL request is made the client object is now cached beforehand, and in the stop/halt methods the client is forcefully closed.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-08T17:49:50.000-0700

**Comment by rbeckman-nextgen** [comment]
Nick, if the message fails to fetch the wsdl and you halt the channel should the message status be errored? At the moment is it stuck as Received(gray message).

Imported Comment. Original Details:
Author: eduardoa
Created: 2015-09-08T18:37:55.000-0700

**Comment by rbeckman-nextgen** [comment]
Any halt (across any connector) should cause the message to be immediately stopped (where possible). In that case yes the message will be unfinished, and will show up as grey/italic in the message browser.

If you don't halt the channel but instead just stop it and it eventually stops but the WSDL could not be retrieved for whatever reason, then in that case yes the status should be ERROR. That _should_ be happening still.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-08T19:22:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Rev 7785
Verified that the Web Service Sender can now be halted if the socket timeout is set to 0. 

One thing to note is that if you halt the channel when it is fetching the wsdl it might still leave the message as incomplete. Attempts at starting the channel will lead to it trying to finish that message. If the channel was being dispatched to the endpoint then it you will see an error in the message browser. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2015-09-08T19:27:36.000-0700

**Comment by rbeckman-nextgen** [comment]
Reopening because that's actually incorrect... either way the message should be left unfinished instead of letting it finish as ERROR.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-08T19:50:42.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7786: Fixed bug where the message was being finished with the status of ERROR when the dispatch task is interrupted. This was happening because the executor clears the interrupted flag of the current thread. Donkey relies on the isInterrupted checks in order to leave a message as unfinished.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-08T19:54:41.000-0700

**Comment by rbeckman-nextgen** [comment]
Rev 7787
The behavior is now consistent with Nick's last comments. If you halt the channel while a message is processing, the message will be left unfinished. Attempts to start the channel after this will lead to retrying this message. You can remove the message when the channel is stopped. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2015-09-09T10:50:44.000-0700
