### ISSUE TITLE
Case insensitivity of SQL Server and MySQL users can cause exceptions

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3512]
SQL Server and MySQL string comparisons are case insensitive by default, which causes a few side effects regarding users. Note that passwords are not affected the same way since only the hash is stored.

1a. If a user "admin" exists, and a users logs in as Admin/ADMIN/admiN/etc, the credentials will work but the user is greeted with a NullPointerException upon logging in. 
1b. In Postgres/Oracle/Derby, attempting to login with the wrong case would fail.

2a. If a user "admin" exists, it is not possible to create another user with Admin/ADMIN/admiN/etc.
2b. In Postgres/Oracle/Derby, it is possible to create users with the same letters and different casing.

3. With User Authorization plugin installed, logging in with the wrong casing will cause the login process to hang at Loading Extensions with a different NPE
`
java.lang.NullPointerException
	at com.mirth.connect.plugins.auth.client.SecureAuthorizationController.initialize(SecureAuthorizationController.java:47)
	at com.mirth.connect.client.ui.Frame.setupFrame(Frame.java:392)
	at com.mirth.connect.client.ui.Mirth.<init>(Mirth.java:62)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:438)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
`

Example of the NPE you will see when logging in without User Authorization installed
`
[2015-02-11 04:35:00,589]  ERROR (com.mirth.connect.server.servlets.UserServlet:160): java.lang.NullPointerException
	at com.mirth.connect.server.servlets.UserServlet.isCurrentUser(UserServlet.java:260)
	at com.mirth.connect.server.servlets.UserServlet.doPost(UserServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3621
Reporter: nreddy
Created: 2015-02-11T07:50:40.000-0800

**Comment by rbeckman-nextgen** [comment]
You'll need to give more specifics. Do you have a reliable method to reproduce this? If not this issue may be closed. Also since you're using 3.0.0, have to tried it out on newer versions? This sounds familiar, like a bug which has already been fixed, though I'm not sure exactly which one.

Imported Comment. Original Details:
Author: narupley
Created: 2015-02-11T07:53:44.000-0800

**Comment by rbeckman-nextgen** [comment]
Looks like it came up here MIRTH-3262. 

I'm pretty sure i've seen this exception before as well but only when something weird happens with my client session. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2015-02-11T10:28:19.000-0800

**Comment by rbeckman-nextgen** [comment]
-Appears to be a duplicate of MIRTH-3262. If you still run into this after upgrading then please open a new issue.-

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-11T10:52:15.000-0800

**Comment by rbeckman-nextgen** [comment]
Seems like this still happens even in 3.2. Looking at the code, I can see why. On the initial login, if the request to get the current user fails, then null is returned instead. Then when LoginPanel passes null into client.getUserPreferences, it causes an NPE to happen on the server side.

[http://www.mirthcorp.com/community/forums/showthread.php?t=13345]

Imported Comment. Original Details:
Author: narupley
Created: 2015-03-04T08:12:03.000-0800

**Comment by rbeckman-nextgen** [comment]
Okay, so I know what is causing it -- at least in my case. Line 1614 in com.mirth.connect.client.ui.Frame:

[CODE]

if (user.getUsername().equals(PlatformUI.USER_NAME)) {
...

[/CODE]

My username is actually "Jon.Lent", but I regularly type it in as "jon.lent" and it authenticates fine. It still authenticates fine, but when the getCurrentUser() enumerates the list of current users looking for the login name, it does the comparison in a case-sensitive manner. When it fails to match because of the case difference, a null user object is returned and eventually causes an NPE in the Administrator tool. So either the equals() should be replaced with equalsIgnoreCase() or the authentication should fail becuase of the inexact match on the user name.

Personally, I liked the old behavior which would make the user name case insensitive.


Imported Comment. Original Details:
Author: jonathanlent
Created: 2015-03-04T10:49:57.000-0800

**Comment by rbeckman-nextgen** [comment]
This is possibly the worst issue title I've seen. "NPE"

Imported Comment. Original Details:
Author: jacobb
Created: 2015-03-04T13:57:37.000-0800

**Comment by rbeckman-nextgen** [comment]
How about "Using MS-SQLServer causes null pointer exceptions when case of username differs from what is stored in database"?

Expected behavior:
When the username supplied at the administrator login does not exactly match the value in the database, the login should fail.

Observed behavior:
When the username supplied at the administrator login differs only in case from the stored value and the back-end database is MS SQLServer, the user will authenticate successfully. When the administration UI appears, a benign error dialog will appear complaining of a null-pointer exception in isCurrentUser(). This will reappear every time the user navigates to the Administrator tab. If the installation has the User Authorization extension installed, the login will halt at "loading extensions..." and a null-pointer exception will be thrown from client.SecureAuthorizationController.initialize().

Steps to reproduce
1. Configure an environment to run Mirth Connect 3.2 with a MS SQLServer 2008 R2 back end. Default values are used when creating the database.
2. Use a known account, say admin/admin to authenticate to the installation and validate that the account can actually complete the login process
3. With the authorization extension disabled or uninstalled, login to the same instance using Admin/admin. This will produce a null-pointer exception when the UI completes the loading process and any time you navigate to the Administrator tab.
4. With the authorization extension installed and enabled, login to the same instance using Admin/admin. This will halt the login process at "loading extensions..." and a NullPointerException will be shown in the java console.

Imported Comment. Original Details:
Author: jonathanlent
Created: 2015-03-04T15:06:36.000-0800

**Comment by rbeckman-nextgen** [comment]
Patched the mybatis file to force case-sensitive behavior when searching for username. This makes a SQL Server installation behave like the other databases.

Imported Comment. Original Details:
Author: jonathanlent
Created: 2015-03-04T15:32:42.000-0800

**Comment by rbeckman-nextgen** [comment]
Thanks [~jonathanlent] for doing some of the legwork on this. It appears that the workaround is simple regardless if User Auth is installed or not, just make sure to use the correct casing of the user and there won't be any problems. Since it's a simple workaround we'll push this back to 3.3.0 so we have more time to discuss what the correct behavior should be for these databases.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-03-10T14:13:29.000-0700

**Comment by rbeckman-nextgen** [comment]
PostgreSQL has a column type called CITEXT which is case-insensitive. I'm not sure if MC can tolerate a PostgreSQL version-bump... CITEXT requires PostgreSQL 8.4+.

Oracle has a session parameter called NLS_COMP which can make Oracle work in a case-insensitive way.

Derby requires a startup parameter to make it case-insensitive as well: collation=TERRITORY_BASED:PRIMARY.

Or you can just put TOLOWER() around everything in. your queries. :)

Imported Comment. Original Details:
Author: cschultz@chadis.com
Created: 2019-04-04T20:53:11.000-0700
