### ISSUE TITLE
FTP Reader sometimes throws 426 error

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3523]
`
ERROR 2015-02-13 21:13:18,630 [Timer-2] com.mirth.connect.connectors.file.filesystems.FtpConnection: closeReadFile.completePendingCommand: 426-426 Connection closed; aborted transfer of "/New Text Document.txt"

ERROR 2015-02-13 21:13:18,630 [Timer-2] com.mirth.connect.connectors.file.FileReceiver: Unable to dispatch message to channel 2d151a72-d32f-4d66-9070-541af0fd20f2: java.io.IOException: Ftp error: 426
	at com.mirth.connect.connectors.file.filesystems.FtpConnection.closeReadFile(FtpConnection.java:251)
	at com.mirth.connect.connectors.file.FileReceiver.getBytesFromFile(FileReceiver.java:502)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:318)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:221)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:177)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:131)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

ERROR 2015-02-13 21:13:25,347 [Timer-2] com.mirth.connect.connectors.file.FileReceiver: Unable to dispatch message to channel 2d151a72-d32f-4d66-9070-541af0fd20f2: com.mirth.connect.donkey.server.channel.ChannelException
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1115)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:191)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:169)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:325)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:221)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:177)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:131)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)
`

Googling for this error only finds this thread on our own forum from 2011.
http://www.mirthcorp.com/community/forums/showthread.php?t=5617

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3632
Reporter: wayneh
Created: 2015-02-13T21:34:14.000-0800

**Comment by rbeckman-nextgen** [comment]
Looks like we're actually throwing the exception because completePendingCommand is returning false in FtpConnector. In FileReceiver we're actually closing the input stream before completePendingCommand is called inside closeReadFile()

`
is.close();
con.closeReadFile();
`

It seems that maybe we're not supposed to close the inputstream until after completePendingCommand is called 
http://www.codejava.net/java-se/networking/ftp/java-ftp-file-download-tutorial-and-example

I tried switching the two lines and didn't get anymore 426 errors, but I did eventually get a 550 error and socket timeout (which could be caused by something else). We'll have to do more tests to confirm whether the 550 is related or not

`
ERROR 2015-02-15 14:44:57,891 [Timer-2] com.mirth.connect.connectors.file.filesystems.FtpConnection: closeReadFile.completePendingCommand: 550-550 can't access file.

ERROR 2015-02-15 14:44:57,893 [Timer-2] com.mirth.connect.connectors.file.FileReceiver: Unable to dispatch message to channel 4f850add-7274-4201-9943-e8bb317a229b: java.io.IOException: Ftp error: 550
	at com.mirth.connect.connectors.file.filesystems.FtpConnection.closeReadFile(FtpConnection.java:251)
	at com.mirth.connect.connectors.file.FileReceiver.getBytesFromFile(FileReceiver.java:501)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:318)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:221)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:177)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

ERROR 2015-02-15 14:45:07,918 [Timer-2] com.mirth.connect.connectors.file.FileReceiver: Unable to dispatch message to channel 4f850add-7274-4201-9943-e8bb317a229b: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.read(BufferedReader.java:175)
	at org.apache.commons.net.io.CRLFLineReader.readLine(CRLFLineReader.java:58)
	at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:314)
	at org.apache.commons.net.ftp.FTP.__getReply(FTP.java:294)
	at org.apache.commons.net.ftp.FTP.getReply(FTP.java:692)
	at org.apache.commons.net.ftp.FTPClient.completePendingCommand(FTPClient.java:1813)
	at com.mirth.connect.connectors.file.filesystems.FtpConnection.closeReadFile(FtpConnection.java:249)
	at com.mirth.connect.connectors.file.FileReceiver.getBytesFromFile(FileReceiver.java:501)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:318)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:221)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:177)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:131)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
`

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-15T14:48:00.000-0800

**Comment by rbeckman-nextgen** [comment]
Seems like the 550 errors were due to listFiles possibly including some temp files. Whatever is going on there it doesn't seem to be related to this fix.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-15T16:06:07.000-0800

**Comment by rbeckman-nextgen** [comment]
con.closeReadFile() (and therefore completePendingCommand as well) is now called before is.close() which should fix this issue.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-15T16:06:56.000-0800

**Comment by rbeckman-nextgen** [comment]
Note to testers: To reproduce, set up FileZilla Server, insert a file into the shared folder, and create a FTP Reader with a poll interval of 1ms. You should get the error pretty quickly, within a few thousand messages. After this change you should not be able to get this error anymore. Also verify that nothing weird happens with the new build such as the aforementioned 550 errors.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-15T18:36:58.000-0800

**Comment by rbeckman-nextgen** [comment]
Rev 7614: Verified that a simple ftp reader with high volume will run into this pretty frequently:

`
[2015-02-17 10:43:47,541]  ERROR (com.mirth.connect.connectors.file.filesystems.FtpConnection:250): closeReadFile.completePendingCommand: 426-426 Connection closed; aborted transfer of "/test/0b5899b9-f48e-4f3a-902e-d0acbfdc1859.txt"
`

Verified on revision 7623 that this is no longer happening. I haven't ran into any of the 550 errors that were mentioned. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2015-02-17T10:50:49.000-0800
