### ISSUE TITLE
Remove JDBC-ODBC Bridge Driver from dbdrivers.xml for new installations

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3525]
It appears that the JDBC-ODBC Bridge has been removed by Oracle in Java 8. 
http://docs.oracle.com/javase/8/docs/technotes/guides/jdbc/

I can confirm that using it with Java 8 will yield an exception similar to 
`
Caused by: java.lang.ClassNotFoundException: sun.jdbc.odbc.JdbcOdbcDriver
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.mirth.connect.connectors.jdbc.DatabaseConnectorService.invoke(DatabaseConnectorService.java:62)
	... 27 more
`

We won't remove it when users upgrade, but we will no longer include it for new installations. Users that wish to remain on Java 7 so they can continue to use the bridge can always add the entry back to dbdrivers.xml. For reference, it is
`
<driver class="sun.jdbc.odbc.JdbcOdbcDriver" name="Sun JDBC-ODBC Bridge" template="jdbc:odbc:DSN" selectLimit="" />
`

According to http://docs.oracle.com/javase/7/docs/technotes/guides/jdbc/bridge.html
{quote}
Oracle recommends that you use JDBC drivers provided by the vendor of your database instead of the JDBC-ODBC Bridge.
{quote}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3634
Reporter: wayneh
Created: 2015-02-15T18:59:21.000-0800

**Comment by rbeckman-nextgen** [comment]
I've mostly seen this used for Access. Are there other options?

Imported Comment. Original Details:
Author: jacobb
Created: 2015-02-23T10:51:09.000-0800

**Comment by rbeckman-nextgen** [comment]
http://ucanaccess.sourceforge.net/site.html
http://www.easysoft.com/products/data_access/jdbc-access-gateway/getting-started.html

The first one is open source under LGPL. Haven't tested them out myself.

Imported Comment. Original Details:
Author: wayneh
Created: 2015-02-23T10:54:52.000-0800

**Comment by rbeckman-nextgen** [comment]
[This SO post](http://stackoverflow.com/questions/9863482/jdbc-with-ms-access) mentions these two open-source alternatives, both are LGPL:

http://jackcess.sourceforge.net/
http://ucanaccess.sourceforge.net/site.html

Imported Comment. Original Details:
Author: brentm
Created: 2015-02-23T10:56:17.000-0800
