### ISSUE TITLE
HTTP Sender cannot send messages with gzip encoding enabled

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3563]
To reproduce, create a channel with an HTTP Sender destination with header Content-Encoding: gzip.

All messages will error out with this error:
`
HTTP Sender error
ERROR MESSAGE: Error connecting to HTTP server
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.String
	at com.mirth.connect.connectors.http.HttpDispatcher.buildHttpRequest(HttpDispatcher.java:502)
	at com.mirth.connect.connectors.http.HttpDispatcher.send(HttpDispatcher.java:265)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:747)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:445)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:155)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1656)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1155)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:191)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:517)
	at com.mirth.connect.server.servlets.MessageObjectServlet$2.run(MessageObjectServlet.java:190)
	at java.lang.Thread.run(Thread.java:745)
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3674
Reporter: brentm
Created: 2015-03-20T14:24:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 7655/7656. Both the HTTP Listener and Sender now consistently check for the possibility of multiple headers when retrieving the accept/content encoding.

Imported Comment. Original Details:
Author: narupley
Created: 2015-04-06T09:45:47.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified in an older build that sending messages using an HTTP Sender causes messages to error when using gzip encoding. Using a newer build, I was able to successfully send messages using the same exported channels. I also verified the code changes within my IDE as well.

Imported Comment. Original Details:
Author: jaysenp
Created: 2015-05-22T10:38:55.000-0700
