### ISSUE TITLE
Mirth CLI Error Exporting Config 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3578]
While connected to a remote server via the Mirth cli this error happens when runing exportcfg command.
Confirmed that only happens on remote client an not on the server itself.
Both client and server are using 3.2.1. but server is on linux and client is on windows.
`
Connected to Mirth Connect server @ https://192.168.4.196:8443 (3.2.1.7650)
$java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
        at com.exe4j.runtime.WinLauncher.main(Unknown Source)
        at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)
Caused by: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field com.mirth.connect.model.ServerConfiguration.resourceProperties
---- Debugging information ----
field               : resourceProperties
class               : com.mirth.connect.model.ServerConfiguration
required-type       : com.mirth.connect.model.Connector
converter-type      : com.mirth.connect.model.converters.MigratableConverter
version             : not available
-------------------------------
        at com.mirth.connect.model.converters.ObjectXMLSerializer.handleDeserializationException(ObjectXMLSerializer.java:300)
        at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:193)
        at com.mirth.connect.client.core.Client.getServerConfiguration(Client.java:189)
        at com.mirth.connect.cli.CommandLineInterface.commandExportConfig(CommandLineInterface.java:653)
        at com.mirth.connect.cli.CommandLineInterface.executeStatement(CommandLineInterface.java:276)
        at com.mirth.connect.cli.CommandLineInterface.runConsole(CommandLineInterface.java:225)
        at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:190)
        at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:156)
        at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:98)
        ... 12 more
Caused by: com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field com.mirth.connect.model.ServerConfiguration.resourceProperties
---- Debugging information ----
field               : resourceProperties
class               : com.mirth.connect.model.ServerConfiguration
required-type       : com.mirth.connect.model.Connector
converter-type      : com.mirth.connect.model.converters.MigratableConverter
version             : not available
-------------------------------
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.handleUnknownField(AbstractReflectionConverter.java:495)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:351)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
        at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:99)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
        at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
        at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
        at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:188)
        ... 19 more
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3690
Reporter: hugosoares2
Created: 2015-04-09T08:39:34.000-0700

**Comment by rbeckman-nextgen** [comment]
Are you sure the CLI instance you're using is from version 3.2.1? Try downloading it directly from [our website](http://www.mirthcorp.com/community/downloads?form=false), under the "Mirth Connect 3.2.1 Command Line Interface" header.

Imported Comment. Original Details:
Author: narupley
Created: 2015-04-09T08:48:13.000-0700

**Comment by rbeckman-nextgen** [comment]
I just installed Mirth cli again from this installer:
mirthconnect-3.2.1.7650.b40-windows-x64.exe

The error continues...

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-04-20T04:04:52.000-0700

**Comment by rbeckman-nextgen** [comment]
I am not able to reproduce that, unless I connect using incorrect versions, like a 3.1.1 CLI to a 3.2.1 server.

Imported Comment. Original Details:
Author: narupley
Created: 2015-04-20T07:53:48.000-0700

**Comment by rbeckman-nextgen** [comment]
Same here, I get that exact exception when using a 3.1.1 CLI connecting to 3.2.1, but it works fine if the CLI is 3.2.1.

Tested using CLI on Windows connecting to MC 3.2.1 on a separate Linux machine.

Imported Comment. Original Details:
Author: brentm
Created: 2015-04-20T08:22:54.000-0700

**Comment by rbeckman-nextgen** [comment]
I installed another server and client and now it is working fine. I guess something was wrong with my old set up even though both server and client were on the same version... 

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-04-29T03:03:44.000-0700

**Comment by rbeckman-nextgen** [comment]
I guess you can close this issue as it is not reproducible.

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-04-29T03:05:05.000-0700
