### ISSUE TITLE
Can't open Set Data Types dialog after changing data type in source filter

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3582]
OK, this is one of those weird bugs where it only happens if you follow a particular sequence of steps, but is 100% repeatable if you do.

Steps:
1) Create new channel.  Name or don't name the channel, doesn't matter.
2) Edit source filter
3) On Message Templates tab, change the data type from HL7 v2 to something else (e.g., EDI/X12).
4) Go back to Summary tab.
5) Click Set Data Types button on Summary tab.  Nothing happens.

The button appears "pressed", but the dialog never opens.  As far as I can tell, this only happens with those exact steps above.  For example, if you edit the source transformer (instead of the source filter) and change the DT there, everything works as expected.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3694
Reporter: ericb
Created: 2015-04-14T13:43:42.000-0700

**Comment by rbeckman-nextgen** [comment]
I can see this in the client console:

`Exception in thread "AWT-EventQueue-2" java.lang.NullPointerException
	at com.mirth.connect.client.ui.DataTypePropertiesTableNode.getValueAt(DataTypePropertiesTableNode.java:62)
	at com.mirth.connect.client.ui.DataTypePropertiesPanel$2.getTreeCellRendererComponent(DataTypePropertiesPanel.java:103)
	at org.jdesktop.swingx.JXTree$DelegatingRenderer.getTreeCellRendererComponent(JXTree.java:1243)
	at javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:2807)
	at javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:492)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1360)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1496)
	at javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.expand(VariableHeightLayoutCache.java:1288)
	at javax.swing.tree.VariableHeightLayoutCache.ensurePathIsExpanded(VariableHeightLayoutCache.java:984)
	at javax.swing.tree.VariableHeightLayoutCache.setExpandedState(VariableHeightLayoutCache.java:182)
	at javax.swing.plaf.basic.BasicTreeUI.updateExpandedDescendants(BasicTreeUI.java:1696)
	at javax.swing.plaf.basic.BasicTreeUI$Handler.treeExpanded(BasicTreeUI.java:3805)
	at javax.swing.JTree.fireTreeExpanded(JTree.java:2763)
	at javax.swing.JTree.setExpandedState(JTree.java:3625)
	at org.jdesktop.swingx.JXTreeTable$TreeTableCellRenderer.setExpandedState(JXTreeTable.java:2843)
	at javax.swing.JTree.expandPath(JTree.java:2211)
	at javax.swing.JTree.expandRow(JTree.java:2226)
	at org.jdesktop.swingx.JXTree.expandAll(JXTree.java:516)
	at org.jdesktop.swingx.JXTreeTable.expandAll(JXTreeTable.java:1584)
	at com.mirth.connect.client.ui.DataTypePropertiesPanel.setDataTypeProperties(DataTypePropertiesPanel.java:263)
	at com.mirth.connect.client.ui.DataTypePropertiesPanel.setDataTypeProperties(DataTypePropertiesPanel.java:240)
	at com.mirth.connect.client.ui.DataTypesDialog$6.valueChanged(DataTypesDialog.java:446)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
	at javax.swing.DefaultListSelectionModel.addSelectionInterval(DefaultListSelectionModel.java:497)
	at javax.swing.tree.DefaultTreeSelectionModel.resetRowSelection(DefaultTreeSelectionModel.java:778)
	at org.jdesktop.swingx.JXTreeTable$ListToTreeSelectionModelWrapper.resetRowSelection(JXTreeTable.java:2146)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:291)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
	at com.mirth.connect.client.ui.DataTypesDialog.toggleEditMode(DataTypesDialog.java:153)
	at com.mirth.connect.client.ui.DataTypesDialog.<init>(DataTypesDialog.java:104)
	at com.mirth.connect.client.ui.ChannelSetup.changeDataTypesButtonActionPerformed(ChannelSetup.java:2927)
	at com.mirth.connect.client.ui.ChannelSetup.access$1500(ChannelSetup.java:93)
	at com.mirth.connect.client.ui.ChannelSetup$10.actionPerformed(ChannelSetup.java:1867)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3322)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Looks like setting the data type in a filter doesn't update the inbound data type in the cached Transformer object, even though it does update the inbound data type _properties_. The accept method in TransformerPane does update both the data type and properties.

Imported Comment. Original Details:
Author: narupley
Created: 2015-04-14T13:57:31.000-0700

**Comment by rbeckman-nextgen** [comment]
The DataTypesDialog is a bit different in 2.2.X and doesn't prevent the dialog from actually popping up. However, the settings still wont persist from whatever is selected as the data type within the filter.

Imported Comment. Original Details:
Author: jaysenp
Created: 2015-04-23T16:09:16.000-0700

**Comment by rbeckman-nextgen** [comment]
Reproduced in 3.2.1, verified the data types dialog now appears in 3.2.2 and the data type selected in the filter persists.

Imported Comment. Original Details:
Author: brentm
Created: 2015-06-02T14:43:42.000-0700
