### ISSUE TITLE
Web Service dispatcher does not queue on SocketExceptions

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3595]
The question is, do it should?

Someone received the following NoRouteToHostException which is a SocketException. From what I've seen this may be caused by firewall issues which is not really something that's meant to be temporary. The queue is intended to be for recoverable errors and if a firewall rule is in place it's not going to make a difference how many times the connector attempts to send the message. 

This one is probably in a gray area and I'd be curious what actual circumstances this occurs in. Javadocs (https://docs.oracle.com/javase/7/docs/api/java/net/NoRouteToHostException.html) indicate that "Typically, the remote host cannot be reached because of an intervening firewall, or if an intermediate router is down." The second example could be a valid use case for queueing.

`
Web Service Sender error
ERROR MESSAGE: Error invoking web service
com.sun.xml.internal.ws.client.ClientTransportException: HTTP transport error: java.net.NoRouteToHostException: No route to host
                at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:117)
                at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:208)
                at com.sun.xml.internal.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:130)
                at com.sun.xml.internal.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:124)
                at com.sun.xml.internal.ws.api.pipe.Fiber.__doRun(Fiber.java:1121)
                at com.sun.xml.internal.ws.api.pipe.Fiber._doRun(Fiber.java:1035)
                at com.sun.xml.internal.ws.api.pipe.Fiber.doRun(Fiber.java:1004)
                at com.sun.xml.internal.ws.api.pipe.Fiber.runSync(Fiber.java:862)
                at com.sun.xml.internal.ws.client.Stub.process(Stub.java:448)
                at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.doInvoke(DispatchImpl.java:250)
                at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.invoke(DispatchImpl.java:289)
                at com.mirth.connect.connectors.ws.WebServiceDispatcher.send(WebServiceDispatcher.java:479)
                at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:747)
                at com.mirth.connect.donkey.server.channel.DestinationConnector.run(DestinationConnector.java:636)
                at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.NoRouteToHostException: No route to host
                at java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
                at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.net.Socket.connect(Socket.java:589)
                at java.net.Socket.connect(Socket.java:538)
                at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
                at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
                at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
                at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1147)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
                at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1282)
                at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1257)
                at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
                at com.sun.xml.internal.ws.transport.http.client.HttpClientTransport.getOutput(HttpClientTransport.java:104)
                ... 14 more
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3708
Reporter: wayneh
Created: 2015-05-01T11:48:21.000-0700

**Comment by rbeckman-nextgen** [comment]
IMO do it definitely should.

The queue is for recoverable errors, but let's also define what "recoverable" means. I don't think it _just_ means something that will eventually resolve itself without any intervention... it should also include issues that are not intentional, yet still require some intervention to resolve (like adding a rule).

If you send a message and the server returns a >= 400 response, or a SOAP fault, then the endpoint you're sending to is clearly saying "I read you loud and clear, but this request is invalid". Those are intentional errors. But if you can't send the request in the first place (or can't receive the response), then I think we should always err on the side of caution and queue the message. The point of persistent queuing (without any advanced things like rotation or queue threads obviously) is to ensure messages get sent in order. If networking problems occur, there's usually no way the dispatcher can know whether the message was actually received. So we shouldn't skip that message on a possibly incorrect assumption and allow other messages to post out of order.

Imported Comment. Original Details:
Author: narupley
Created: 2015-05-01T12:31:52.000-0700

**Comment by rbeckman-nextgen** [comment]
The WS Dispatcher will now catch any NoRouteToHostExceptions and queue the failed message.

Imported Comment. Original Details:
Author: jaysenp
Created: 2015-07-31T17:14:45.000-0700

**Comment by rbeckman-nextgen** [comment]
**Server(s) and URLs Used:** 
Mirth Connect Sender running on MacOSX
Listener/Destination on Win7 = minh-vWin7.hq.mirthcorp.com / 10.10.14.198
Listener/Destination on CenOS = minh-vMA-380 / 10.10.14.172
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.2.2.7680.b56-unix
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.3.0.7719.b1682-unix
**How Tested (list tests run):**
Attempted to create network error using Firewall & hosts file. I however was not able to recreate the same Exception nor observe the reported behavior. I have tried the followings:
* Scenario1: using Window firewall ON
* Scenario2: start with Window firewall OFF then turn ON
* Scenario3: Using local hosts file on MacOSX to resolve destination hostname
* Scenario4: Turning off/suspend the destination VM
In all cases, I was getting same behaviors on both builds, either QUEUED or ERRORED msgs.
Will need further discussion with DEVs to verify this ticket.

Imported Comment. Original Details:
Author: minht
Created: 2015-08-24T13:47:32.000-0700

**Comment by rbeckman-nextgen** [comment]
I think in a case like this debugging through the code and verifying it should suffice. I modified the code to manually throw a NoRouteToHostException, and the message was correctly queued.

Imported Comment. Original Details:
Author: narupley
Created: 2015-08-24T13:55:01.000-0700
