### ISSUE TITLE
FTP file connectors fail to test connection for directories with spaces in them

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3601]
The server log will show a URISyntaxException when this happens. This is because the file connector service just appends the host and directory together, assuming that any special characters are already encoded. However during actual message processing getEndpointURI is used instead, which creates a URI object using a different method. So even if you replace spaces with "%20", no URISyntaxException will occur, but a CWD on the actual connection will likely fail because the directory being changed to contains the literal characters "%20" rather than an actual space.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3714
Reporter: narupley
Created: 2015-05-18T13:02:28.000-0700

**Comment by rbeckman-nextgen** [comment]
Does this affect SMB and the other method types as well?

Imported Comment. Original Details:
Author: wayneh
Created: 2015-05-18T13:38:40.000-0700

**Comment by rbeckman-nextgen** [comment]
It appears that it is the same issue for SMB: [http://www.mirthcorp.com/community/forums/showthread.php?t=14409]

Imported Comment. Original Details:
Author: narupley
Created: 2015-06-08T12:20:45.000-0700

**Comment by rbeckman-nextgen** [comment]
It looks like all method types (except for File) were affected. Now all method types can successfully test connections for directories with spaces in them.

Imported Comment. Original Details:
Author: leilanim
Created: 2015-09-03T16:39:14.000-0700

**Comment by rbeckman-nextgen** [comment]
**Server(s) and URLs Used:** Run Mirth Connect on local OSX Yosemite 10.10
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.2.2.7680.b56-unix
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.3.0.7776.b1763
**How Tested (list tests run):**
* Setup FTP server with user = anonymous, directory = My FTP Directory
* Run Mirth Connect
* Create new channel with Source = File Reader 
* From File Reader Setting > method = ftp, Fill in FTP information
* Select Test Read 

**Verified Fixed:**
Able to Test Read at MC 330

**Additional Information:**
I also tried with Destination Connector / File Writer / Test Write and that does not have the same behavior. Only reproducing error with Test Read. 

Imported Comment. Original Details:
Author: minht
Created: 2015-09-10T15:16:12.000-0700

**Comment by rbeckman-nextgen** [comment]
ERROR in server.log
`[2015-09-10 15:24:29,380]  ERROR (com.mirth.connect.server.servlets.ExtensionServlet:166): java.net.URISyntaxException: Illegal character in path at index 21: ftp://10.10.14.177/My FTP Directory
	at java.net.URI$Parser.fail(URI.java:2829)
	at java.net.URI$Parser.checkChars(URI.java:3002)
	at java.net.URI$Parser.parseHierarchical(URI.java:3086)
	at java.net.URI$Parser.parse(URI.java:3034)
	at java.net.URI.<init>(URI.java:595)
	at com.mirth.connect.connectors.file.FileReaderService.invoke(FileReaderService.java:60)
	at com.mirth.connect.plugins.ssl.server.SecureFileReaderService.invoke(Unknown Source)
	at com.mirth.connect.server.controllers.DefaultExtensionController.invokeConnectorService(DefaultExtensionController.java:411)
	at com.mirth.connect.server.servlets.ExtensionServlet.doPost(ExtensionServlet.java:142)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:447)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:225)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1038)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:374)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:972)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:363)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:483)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:931)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:992)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:627)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:51)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
`

Imported Comment. Original Details:
Author: minht
Created: 2015-09-10T15:37:20.000-0700

**Comment by rbeckman-nextgen** [comment]
verified ability to test read Directory Name with spaces using mirthconnect-3.3.0.7776.b1763

Imported Comment. Original Details:
Author: minht
Created: 2015-09-10T16:06:28.000-0700
