### ISSUE TITLE
Not able to connect to ftp reader/writer 

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3629]
Try setting up channel as file reader/writer, selecting method as ftp, provide ftp connection details, click Test Readr/Writer button to test will display popup saying Unable to connect to: ftp://.
If you ingnore this error and deploy the channel you will receive time error.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3743
Reporter: meta
Created: 2015-06-26T21:12:46.000-0700

**Comment by rbeckman-nextgen** [comment]
You'll need to provide more information so that we can reproduce the problem you're seeing. How do you know it's not just a connectivity/networking error between you and the FTP server?

Imported Comment. Original Details:
Author: narupley
Created: 2015-06-26T21:14:13.000-0700

**Comment by rbeckman-nextgen** [comment]
I'm able to connect to that ftp server via ftp client but the same fails in Mirth.

Imported Comment. Original Details:
Author: meta
Created: 2015-06-26T21:23:55.000-0700

**Comment by rbeckman-nextgen** [comment]
Does the directory you're using have a space in it? If so you may be running into MIRTH-3714. Otherwise, more information on exactly what the problem/error is would be needed...

Imported Comment. Original Details:
Author: narupley
Created: 2015-06-26T21:26:48.000-0700

**Comment by rbeckman-nextgen** [comment]
I'm reading so space dosen't seem to be the issue. 
The error I get is :-
 [2015-06-27 00:35:03,406]  ERROR (com.mirth.connect.connectors.file.FileReceiver:181): Error polling in channel: 82ae73c6-d3c7-4263-899c-e6adfe9a3ea4
java.io.IOException: Ftp error: 550
	at com.mirth.connect.connectors.file.filesystems.FtpConnection.listFiles(FtpConnection.java:154)
	at com.mirth.connect.connectors.file.FileReceiver.listFiles(FileReceiver.java:526)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:177)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:131)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

Imported Comment. Original Details:
Author: meta
Created: 2015-06-26T21:38:06.000-0700

**Comment by rbeckman-nextgen** [comment]
An FTP 550 response code means permission was denied, or the CWD failed because the directory doesn't exist. Make sure your credentials are correct and the directory you're trying to connect to is correct. Also look on the FTP server side to see exactly why the error is occurring.

Imported Comment. Original Details:
Author: narupley
Created: 2015-06-26T21:46:18.000-0700

**Comment by rbeckman-nextgen** [comment]
I have the required permissions, tried creating file and changing dir from ftp client.
Could be http://www.mirthcorp.com/community/forums/showthread.php?t=6074


Imported Comment. Original Details:
Author: meta
Created: 2015-06-26T22:03:23.000-0700

**Comment by rbeckman-nextgen** [comment]
What are you using for your directory? If it's blank, then a "CWD /" will be issued, and perhaps that's why the server is rejecting it. Instead, try putting the absolute path of the folder you want to connect to. Like if the home directory your server puts you in is /usr/user1, then use "usr/user1" in the directory field. 

Imported Comment. Original Details:
Author: narupley
Created: 2015-06-26T22:17:05.000-0700

**Comment by rbeckman-nextgen** [comment]
I tried all combination, tried root and directory 2 level but they all fail. 

Imported Comment. Original Details:
Author: meta
Created: 2015-06-26T22:26:27.000-0700
