### ISSUE TITLE
Donkey NullPointerException getting destination resources

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3634]
This strange issue happened on a channel that has multiple destinations in wich some use the defualt resource and others don't.
Somehow this particular connector (wich uses the default resource) always throws this error.
I was able to solve it by setting the default resource on the channel level.

By looking at .DestinationChain ln 179 I was able to see that props.getResourceIds() is likely returning null.
`
2015-07-16 12:28:07,955]  ERROR (com.mirth.connect.donkey.server.channel.DestinationChain:179): Error processing destination MFN^M13_Add_General.mconn for channel 1f566e6d-3e35-479b-8146-e2fa043d5d36.
java.lang.NullPointerException
                at java.util.LinkedHashSet.<init>(LinkedHashSet.java:168)
                at com.mirth.connect.donkey.model.channel.DestinationConnectorProperties.<init>(DestinationConnectorProperties.java:67)
                at com.mirth.connect.connectors.tcp.TcpDispatcherProperties.<init>(TcpDispatcherProperties.java:78)
                at com.mirth.connect.connectors.tcp.TcpDispatcherProperties.clone(TcpDispatcherProperties.java:266)
                at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:411)
                at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:155)
                at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1656)
                at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1155)
                at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:191)
                at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:517)
                at com.mirth.connect.server.controllers.DonkeyMessageController.reprocessMessages(DonkeyMessageController.java:437)
                at com.mirth.connect.server.servlets.MessageObjectServlet$1.run(MessageObjectServlet.java:169)
                at java.lang.Thread.run(Thread.java:745)
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3749
Reporter: hugosoares2
Created: 2015-07-16T06:03:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Does it happen in 3.2.2? Also, did you clone the destination? If so, it may be related to MIRTH-3707.

Imported Comment. Original Details:
Author: narupley
Created: 2015-07-16T08:27:36.000-0700

**Comment by rbeckman-nextgen** [comment]
Yes, the destination was cloned.  Since we corrected the problem (as stated above) we were not able to reproduce the problem again. No point testing 3.2.2. since we cant reproduce it... Probably an issue with the cloning feature...

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-07-17T08:19:49.000-0700

**Comment by rbeckman-nextgen** [comment]
Yeah, sounds like the same issue as MIRTH-3707 then, which was fixed in 3.2.2. I'll go ahead and mark this as a duplicate.

Imported Comment. Original Details:
Author: narupley
Created: 2015-07-17T08:26:17.000-0700
