### ISSUE TITLE
JSON token marker does not correctly color the last entry

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3665]
The JSON token marker correctly colors all key properties except the very last one.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3781
Reporter: jaysenp
Created: 2015-09-10T15:40:54.000-0700

**Comment by rbeckman-nextgen** [comment]
Remaining issues with the JSON syntax highlighter have been fixed.

QA, please test using JSON documents that contain a variety of data types within multiple levels of nested arrays and objects.

The color coding is as follows:
Keys: blue
Strings: purple
Numeric: red
Booleans: green
Null: green
Symbols: black

Imported Comment. Original Details:
Author: leilanim
Created: 2016-01-04T17:39:19.000-0800

**Comment by rbeckman-nextgen** [comment]
[~leilanim] problem not fixed but rather behaving differently

**Server(s) and URLs Used:** virtual Window 7 with Java 8 Update 71
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.3.0.7801.b1804
**Version(s)/Build(s) to verify:** mirthconnect-3.3.1.7882.b97-windows-x64 & mirthconnect-3.4.0.7892.b1858-windows-x64
**How Tested (list tests run):**
* Create/import test channel with data type = JSON, Source/Destination = Channel Reader/Writer
* Deploy channel
* Send JSON message and record syntax highlighting
* View messages, record raw message for comparison (see attached screenshots)

**Additional info:**
* in MC 3.3.0: Key after array value is not colored/highlighted properly
* in MC 3.3.1 & 3.4.0: 
** Key after object value is not colored/highlighted properly
** Key after null or boolean is not colored/highlighted properly
** Getting "Exception in thread "AWT-EventQueue-2" java.util.NoSuchElementException" in client log

Imported Comment. Original Details:
Author: minht
Created: 2016-01-29T15:52:02.000-0800

**Comment by rbeckman-nextgen** [comment]
Client log when Select to View messages (after sent JSON document with nested object/array)
`Exception in thread "AWT-EventQueue-2" java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(Unknown Source)
	at java.util.ArrayDeque.pop(Unknown Source)
	at org.syntax.jedit.tokenmarker.JSONTokenMarker.markTokensImpl(JSONTokenMarker.java:81)
	at org.syntax.jedit.tokenmarker.TokenMarker.markTokens(TokenMarker.java:57)
	at org.syntax.jedit.JEditTextArea._offsetToX(JEditTextArea.java:704)
	at org.syntax.jedit.JEditTextArea.scrollTo(JEditTextArea.java:581)
	at org.syntax.jedit.JEditTextArea.scrollToCaret(JEditTextArea.java:543)
	at org.syntax.jedit.JEditTextArea.select(JEditTextArea.java:1323)
	at org.syntax.jedit.JEditTextArea$DocumentHandler.insertUpdate(JEditTextArea.java:2072)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source)
	at org.syntax.jedit.SyntaxDocument.fireInsertUpdate(SyntaxDocument.java:150)
	at javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
	at javax.swing.text.AbstractDocument.insertString(Unknown Source)
	at org.syntax.jedit.MirthPlainDocument.insertString(MirthPlainDocument.java:122)
	at org.syntax.jedit.JEditTextArea.setText(JEditTextArea.java:1024)
	at com.mirth.connect.client.ui.components.MirthSyntaxTextArea.setText(MirthSyntaxTextArea.java:167)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.setCorrectDocument(MessageBrowser.java:984)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.updateDescriptionMessages(MessageBrowser.java:1742)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.MessageListSelected(MessageBrowser.java:1695)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.access$1400(MessageBrowser.java:117)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser$11.valueChanged(MessageBrowser.java:1099)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JTable.changeSelectionModel(Unknown Source)
	at javax.swing.JTable.changeSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressedDND(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at org.jdesktop.swingx.JXTreeTable.processMouseEvent(JXTreeTable.java:396)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source) `

Imported Comment. Original Details:
Author: minht
Created: 2016-01-29T16:02:28.000-0800

**Comment by rbeckman-nextgen** [comment]
JSON test message
` {
"Patient" : {
	"PID":{
		"mrn" : {
			"id":1922,
			"version": [1.0, 1.1, 2.1]
		},
		"name" : {"first" : "CLYDE", "last" : "DIXON"},
		"dob" : "06/15/1961",
		"ssn" : 123456789,
		"address":{"street" : "1 avenue", "street2" : null, "city" : "costa mesa", "zip" : 99887, "country" : null}
	},
	"AL":{ 
		"AL1": [
			1000,
			{"pollen" : true},
			{"peanut" : false},
			{"aspirin": false},
			"any special instruction"
			],
		"AL2": ["epidemic",null]
	}
}
}  `

Imported Comment. Original Details:
Author: minht
Created: 2016-01-29T16:03:40.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed remaining highlighting issues.

Imported Comment. Original Details:
Author: leilanim
Created: 2016-02-01T16:40:34.000-0800

**Comment by rbeckman-nextgen** [comment]
Following exception thrown when viewing a JSON message in Message Browser:

{quote}
Exception in thread "AWT-EventQueue-2" java.util.NoSuchElementException
  at java.util.ArrayDeque.removeFirst(Unknown Source)
  at java.util.ArrayDeque.pop(Unknown Source)
  at org.syntax.jedit.tokenmarker.JSONTokenMarker.markTokensImpl(JSONTokenMarker.java:83)
  at org.syntax.jedit.tokenmarker.TokenMarker.markTokens(TokenMarker.java:57)
  at org.syntax.jedit.JEditTextArea._offsetToX(JEditTextArea.java:704)
  at org.syntax.jedit.JEditTextArea.scrollTo(JEditTextArea.java:581)
  at org.syntax.jedit.JEditTextArea.scrollToCaret(JEditTextArea.java:543)
  at org.syntax.jedit.JEditTextArea.select(JEditTextArea.java:1323)
{quote}

Imported Comment. Original Details:
Author: leilanim
Created: 2016-02-03T15:39:53.000-0800

**Comment by rbeckman-nextgen** [comment]
Added null checks to JSON token marker.

Imported Comment. Original Details:
Author: leilanim
Created: 2016-02-03T15:45:35.000-0800

**Comment by rbeckman-nextgen** [comment]
Tested with mirthconnect-3.3.2.7909.b103-windows-x64
* No longer getting "java.util.NoSuchElementException"
* When "Format XML Messages" is selected, json syntax is properly formatted (pretty printed) & highlighted
* Without "Format XML Messages", input text "any special instruction" is in blue (should be purple)
Screenshot comparison
!json_msgFormat_MC332.png!

Imported Comment. Original Details:
Author: minht
Created: 2016-02-09T11:19:45.000-0800

**Comment by rbeckman-nextgen** [comment]
attached msgFormat screenshot & json input message for  DEVs review

Imported Comment. Original Details:
Author: minht
Created: 2016-02-09T11:25:28.000-0800

**Comment by rbeckman-nextgen** [comment]
Thanks, Mindy. I found the problem. Looks like an easy fix so I'm just gonna reopen this.

Imported Comment. Original Details:
Author: leilanim
Created: 2016-02-10T12:27:43.000-0800

**Comment by rbeckman-nextgen** [comment]
Okay, the fix is in!

Imported Comment. Original Details:
Author: leilanim
Created: 2016-02-10T12:32:00.000-0800

**Comment by rbeckman-nextgen** [comment]
Tested with **mirthconnect-3.3.2.7911.b104-unix**
All issues are resolved, JSON msg is highlighted correctly without "Format XML Messages"  !corrected_json_msg.png!

Imported Comment. Original Details:
Author: minht
Created: 2016-02-11T09:35:51.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified JSON msg with mirthconnect-3.3.2.7911.b104

Imported Comment. Original Details:
Author: minht
Created: 2016-02-11T09:36:26.000-0800
