### ISSUE TITLE
Code relying on Object toString() behavior fails in 3.3

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3677]
Before, the .toString() method merely returned the \[\[Class\]\] property of the object, like "\[object Object\]". However in 3.3 since that has been overridden to return a JSON string, any code that relied on the old method won't work.

One example of this that someone brought up is using an external JavaScript library like [Moment.js](http://momentjs.com/).

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3794
Reporter: narupley
Created: 2015-09-21T07:36:23.000-0700

**Comment by rbeckman-nextgen** [comment]
Revisions 7825/7826: The toString() method for JavaScript objects/arrays is no longer overridden, and should be ECMA-compliant (or at least whatever Rhino was doing before). The transformer code will now call JSON.stringify for objects/arrays instead. In JSSU we still check and stringify though, just in case Object.prototype.toString was overridden.

Imported Comment. Original Details:
Author: narupley
Created: 2015-09-24T16:16:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Researching ticket background and scenario on Forum thread _http://www.mirthcorp.com/community/forums/showthread.php?t=16289&highlight=moment.js


Imported Comment. Original Details:
Author: minht
Created: 2015-10-07T11:03:32.000-0700

**Comment by rbeckman-nextgen** [comment]
Full Transformer Error when running channel at MC 3.3.0
`ERROR MESSAGE: Error evaluating transformer
com.mirth.connect.server.MirthJavascriptTransformerException: 
CHANNEL:	mirth3794_externalJavaScriptlibrary
CONNECTOR:	sourceConnector
SCRIPT SOURCE:	TRANSFORMER
SOURCE CODE:	
109: //! moment.js
110: //! version : 2.10.6
111: //! authors : Tim Wood, Iskren Chernev, Moment.js contributors
112: //! license : MIT
113: //! momentjs.com
114: !function(a,b){"object"==typeof exports&&"undefined"!=typeof 
… 
116: function stopOnErrorCount(cid, errorCount) {
117: 	var channelStatisticsController = Packages.com.mirth.connect.server.controllers.ChannelStatisticsController.getInstance();
118: 	var channelStatusController = Packages.com.mirth.connect.server.controllers.ChannelStatusController.getInstance();
LINE NUMBER:	114
DETAILS:	TypeError: Cannot find function toJSON in object <HL7Message><MSH><MSH.1>|</MSH.1><MSH.2>
...</HL7Message>.
...
com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:154)
	at com.mirth.connect.server.transformers.JavaScriptFilterTransformer$FilterTransformerTask.call(JavaScriptFilterTransformer.java:119)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)`

Imported Comment. Original Details:
Author: minht
Created: 2015-10-07T14:29:16.000-0700

**Comment by rbeckman-nextgen** [comment]
**Server(s) and URLs Used:** Run Mirth Connect on local OSX Yosemite 10.10
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.3.0.7801.b1804
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.3.1.7832.b80-unix
**How Tested (list tests run):**
* Run Mirth Connect
* Create a Code Template of Type “Compiled Code Block”, 
using “moment.min.js” Javascript minified library
http://momentjs.com/downloads/moment.min.js
* Create channel using default Source/Destination = Channel Reader/Writer
* Edit Source (or Destination) Transformer > Add New Step > Type = JavaScript and paste in code
`var now = moment().format('MMMM Do YYYY, h:mm:ss a').toString(); 
logger.info("Current time is "+now);`
* Save & Deploy Channel
* Send HL7 msg to channel and verify the result

**Additional Info:**
* I started with mirthconnect-3.2.2.7680.b56-unix to create channel and verify it working, then upgraded to MC330 with the same channel to verify failure, then upgraded to MC331 to verify the issue is fixed
* the transformer code works with and without **.toString()** method

**Verified Fixed:**
At MC330.7801, channel failed with the following transformer error
`DETAILS:	TypeError: Cannot find function toJSON in object <HL7Message><MSH><MSH.1>|</MSH.1><MSH.2>
...</HL7Message>`

At MC331.7832, same channel deployed and received msg successfully. Current time is logged to server.log with proper format 
`INFO  2015-10-07 14:24:20,623 [pool-4-thread-1] transformer: Current time is October 7th 2015, 2:24:20 pm`



Imported Comment. Original Details:
Author: minht
Created: 2015-10-07T14:29:51.000-0700

**Comment by rbeckman-nextgen** [comment]
attached test channel & code template used for this test

Imported Comment. Original Details:
Author: minht
Created: 2015-10-07T14:34:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified working transformer code using "moment.js" library at mirthconnect-3.3.1.7832.b80

Imported Comment. Original Details:
Author: minht
Created: 2015-10-07T14:44:03.000-0700
