### ISSUE TITLE
Exception in Channel using FTP Reader

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#368]
org.apache.commons.net.ftp.parser.ParserInitializationException: Error initializing parser
	at org.apache.commons.net.ftp.parser.DefaultFTPFileEntryParserFactory.createFileEntryParser(DefaultFTPFileEntryParserFactory.java:129)
	at org.apache.commons.net.ftp.FTPClient.initiateListParsing(FTPClient.java:2358)
	at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2141)
	at org.apache.commons.net.ftp.FTPClient.listFiles(FTPClient.java:2188)
	at com.webreach.mirth.server.mule.providers.ftp.FtpMessageReceiver.listFiles(FtpMessageReceiver.java:134)
	at com.webreach.mirth.server.mule.providers.ftp.FtpMessageReceiver.poll(FtpMessageReceiver.java:72)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:73)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)

Is this similar to the problem at http://javafoo.wordpress.com/2005/07/14/apachecommonsnet-parserinitializationexception/

Imported Issue. Original Details:
Jira Issue Key: MIRTH-358
Reporter: gturrill
Created: 2007-05-16T23:47:13.000-0700

**Comment by rbeckman-nextgen** [comment]
Channel configuration.

Imported Comment. Original Details:
Author: gturrill
Created: 2007-05-16T23:55:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Further testing to a Linux box indicates that this appears to be a Solaris issue. A successful transfer was achieved using the FTP Reader on Linux.

Imported Comment. Original Details:
Author: gturrill
Created: 2007-05-17T00:27:48.000-0700

**Comment by rbeckman-nextgen** [comment]
The problem appears to be with pre Solaris 2.6 only. I have successfully run an FTP Reader on Solaris 2.6 and Solaris 10

Imported Comment. Original Details:
Author: gturrill
Created: 2007-05-17T17:09:02.000-0700

**Comment by rbeckman-nextgen** [comment]
Solaris issue.

Imported Comment. Original Details:
Author: chrisl
Created: 2007-05-24T01:44:47.000-0700
