### ISSUE TITLE
Messages consisting of just spaces will throw an exception when viewed in the Message Browser

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3699]
If you send a message that only contains blank spaces and try to view it in the Message Browser, the Administrator will hang and an Index Out of Range exception will be thrown.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3816
Reporter: leilanim
Created: 2015-10-12T12:09:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Messages with only spaces are once again viewable in Message Browser.

Imported Comment. Original Details:
Author: leilanim
Created: 2015-10-12T12:52:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Exception found on Client Console (Java console log)
`Exception in thread "AWT-EventQueue-2" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(Unknown Source)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.setCorrectDocument(MessageBrowser.java:971)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.updateDescriptionMessages(MessageBrowser.java:1743)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.MessageListSelected(MessageBrowser.java:1696)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser.access$1400(MessageBrowser.java:117)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser$11.valueChanged(MessageBrowser.java:1100)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
	at javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
	at javax.swing.JTable.changeSelectionModel(Unknown Source)
	at javax.swing.JTable.changeSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressedDND(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at org.jdesktop.swingx.JXTreeTable.processMouseEvent(JXTreeTable.java:396)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

Imported Comment. Original Details:
Author: minht
Created: 2015-10-13T16:51:02.000-0700

**Comment by rbeckman-nextgen** [comment]
**Server(s) and URLs Used:** Run Mirth Connect on local OSX Yosemite 10.10
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.3.0.7801.b1804
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.3.1.7844.b85
**How Tested (list tests run):**
* Enable client console (Java > Control Panel > Advanced > Java Console > show console)
* Run Mirth Connect
* Create new Channel with default Source/Destination = Channel Reader/Writer
* Save & Deploy Channel
* Send msg consisting a line of just spaces 
* Verify msg sent successfully, then select to View Messages, record the behavior

**Verified Fixed:**
At MC 330, getting Exception when select to view message, Administrator console is still responding to other requests, just not view message for the blank msg. This behavior is not observed at MC 331 (no exception thrown and able to view message)   

**Additional Info:** 
tested with both OSX and Windows, problem is fixed

Imported Comment. Original Details:
Author: minht
Created: 2015-10-14T10:18:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Successfully verified fixed at mirthconnect-3.3.1.7844.b85

Imported Comment. Original Details:
Author: minht
Created: 2015-10-14T10:20:31.000-0700
