### ISSUE TITLE
Deadlock issue on updateStatistics.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3705]
We are having a serious issue with one of our channel. Mirth seem to have a deadlock issue on updateStatistics that cause message loss for certain destinations.

StackTrace :  ERROR 2015-10-20 08:30:33,826 [Thread-60] com.mirth.connect.donkey.server.channel.Channel: An error occurred in channel channelA (e3fa4bd4-ebd9-435b-8d58-b0a1f14396cb) while processing message ID 9987235 from the source queue
java.lang.RuntimeException: com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: ERREUR: Bloquage mortel détecté
  Détail : Le processus 4336 attend ShareLock sur transaction 429655868 ; bloqué par le processus 4444.
Le processus 4444 attend ShareLock sur transaction 429655869 ; bloqué par le processus 4336.
  Indice : Voir les journaux applicatifs du serveur pour les détails sur la requête.
	at com.mirth.connect.donkey.server.channel.Channel.handleDestinationChainThrowable(Channel.java:1503)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1442)
	at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1530)
	at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1517)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.donkey.server.data.DonkeyDaoException: org.postgresql.util.PSQLException: ERREUR: Bloquage mortel détecté
  Détail : Le processus 4336 attend ShareLock sur transaction 429655868 ; bloqué par le processus 4444.
Le processus 4444 attend ShareLock sur transaction 429655869 ; bloqué par le processus 4336.
  Indice : Voir les journaux applicatifs du serveur pour les détails sur la requête.
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.updateStatistics(JdbcDao.java:398)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.addChannelStatistics(JdbcDao.java:331)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.commit(JdbcDao.java:1696)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.executeTasks(BufferedDao.java:133)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:74)
	at com.mirth.connect.donkey.server.data.buffered.BufferedDao.commit(BufferedDao.java:61)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:288)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:38)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
Caused by: org.postgresql.util.PSQLException: ERREUR: Bloquage mortel détecté
  Détail : Le processus 4336 attend ShareLock sur transaction 429655868 ; bloqué par le processus 4444.
Le processus 4444 attend ShareLock sur transaction 429655869 ; bloqué par le processus 4336.
  Indice : Voir les journaux applicatifs du serveur pour les détails sur la requête.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2101)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1834)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:510)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:386)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:332)
	at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.updateStatistics(JdbcDao.java:377)
	... 12 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3822
Reporter: zidore
Created: 2015-10-21T07:02:11.000-0700

**Comment by rbeckman-nextgen** [comment]
This should be resolved with MIRTH-3447... feel free to open up a new issue if you find that it still occurs in 3.4.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-09T10:35:14.000-0800
