### ISSUE TITLE
When using JSON, the tmp variable is not correctly initialized in response transformers

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3707]
When using an outbound JSON template, the tmp variable will just be null.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3824
Reporter: narupley
Created: 2015-10-22T09:18:52.000-0700

**Comment by rbeckman-nextgen** [comment]
Tmp variable is no longer null for JSON templates.

Imported Comment. Original Details:
Author: leilanim
Created: 2015-12-15T13:44:23.000-0800

**Comment by rbeckman-nextgen** [comment]
Processing Error at MC 331.7856
` Response Transformer error
ERROR MESSAGE: Error evaluating response transformer
com.mirth.connect.server.MirthJavascriptTransformerException: 
CHANNEL:	mirth3824_json response transformer
CONNECTOR:	Destination 1
SCRIPT SOURCE:	response
SOURCE CODE:	
44: msg = new String(response.getMessage()) 
45: tmp = JSON.parse(template);
46: function doTransform() {
47: 
48: 
49: tmp['ResponseKey1'] = "first key response";
50: tmp['ResponseKey2'] = "second key response";
51: if ('xml' === typeof msg) {
52:     if (msg.hasSimpleContent()) {
53:         msg = msg.toXMLString();
LINE NUMBER:	49
DETAILS:	TypeError: Cannot set property "ResponseKey1" of null to "first key response"
	at ddc218fe-facf-4a98-a012-716f63298fad:49 (doTransform)
	at ddc218fe-facf-4a98-a012-716f63298fad:72 (doScript)
	at ddc218fe-facf-4a98-a012-716f63298fad:74
	at com.mirth.connect.server.transformers.JavaScriptResponseTransformer$ResponseTransformerTask.call(JavaScriptResponseTransformer.java:160)
	at com.mirth.connect.server.transformers.JavaScriptResponseTransformer$ResponseTransformerTask.call(JavaScriptResponseTransformer.java:118)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

Imported Comment. Original Details:
Author: minht
Created: 2016-02-03T11:05:05.000-0800

**Comment by rbeckman-nextgen** [comment]
**Server(s) and URLs Used:** virtual Window 7 with JRE version 1.8.0_71-b15 
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.3.1.7856.b91-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.3.1.7901.b100-windows-x64
**How Tested (list tests run):**
* Imported the attached test channel or create Test Channel as followed:
** Channel Summary > Set Data Type = raw for Source & Destination connector inbound & outbound, 
** Set Data Type > expand Destination > Response > Inbound = raw, Outbound = JSON 
** Channel Source & Destination = Channel Reader/Writer
** Channel Destination > Edit Response > Message Templates > Outbound Message Template = JSON with the following template:
`{
	"ResponseKey1":"One",
	"ResponseKey2":"Two"
}`
** Select Add New Step on the left panel > set type = JavaScript
`tmp['Response1'] = "first key response";
tmp['Response2'] = "second key response";`

* Save & deploy channel 
* From Dashboard > select Channel > Send raw text message 

**Verified Fixed:**
in MC 331.7856.b91, channel failed with "Response Transformer error" (see previous comment)
in MC 331.7901.b100, channel processed successfully with the following Processed Response
`{"ResponseKey1":"first response key","ResponseKey2":"second response key"}`


Imported Comment. Original Details:
Author: minht
Created: 2016-02-03T11:55:14.000-0800

**Comment by rbeckman-nextgen** [comment]
**Additional Info:** getting this Exception on client java log when select to View Message at new build (MC 331.7901.b100)
`Exception in thread "AWT-EventQueue-2" java.util.NoSuchElementException
	at java.util.ArrayDeque.removeFirst(Unknown Source)
	at java.util.ArrayDeque.pop(Unknown Source)
	at org.syntax.jedit.tokenmarker.JSONTokenMarker.markTokensImpl(JSONTokenMarker.java:83)
	at org.syntax.jedit.tokenmarker.TokenMarker.markTokens(TokenMarker.java:57)
	at org.syntax.jedit.JEditTextArea._offsetToX(JEditTextArea.java:704)
	at org.syntax.jedit.JEditTextArea.scrollTo(JEditTextArea.java:581)
	at org.syntax.jedit.JEditTextArea.scrollToCaret(JEditTextArea.java:543)
	at org.syntax.jedit.JEditTextArea.select(JEditTextArea.java:1323)
	at org.syntax.jedit.JEditTextArea$DocumentHandler.insertUpdate(JEditTextArea.java:2072)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source)
	at org.syntax.jedit.SyntaxDocument.fireInsertUpdate(SyntaxDocument.java:150)
	at javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
	at javax.swing.text.AbstractDocument.insertString(Unknown Source)
	at org.syntax.jedit.MirthPlainDocument.insertString(MirthPlainDocument.java:122)
	at org.syntax.jedit.JEditTextArea.setText(JEditTextArea.java:1024)
	at com.mirth.connect.client.ui.components.MirthSyntaxTextArea.setText(MirthSyntaxTextArea.java:167)
	at com.mirth.connect.client.ui.browsers.message.MessageBrowser$10.done(MessageBrowser.java:1023)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

Imported Comment. Original Details:
Author: minht
Created: 2016-02-03T13:49:39.000-0800

**Comment by rbeckman-nextgen** [comment]
Is that happening when the JSON document has incorrect syntax or something? If so, that seems expected to me. It's the same thing if you use the XML data type and put some incorrect XML into an inbound template. An error shows up in the client log, but it's really just benign, especially considering most users don't have the client-side Java console enabled.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-03T13:53:41.000-0800

**Comment by rbeckman-nextgen** [comment]
java.util.NoSuchElementException will be fixed as part of MIRTH3781

Imported Comment. Original Details:
Author: minht
Created: 2016-02-03T15:23:44.000-0800

**Comment by rbeckman-nextgen** [comment]
tmp variable is properly initialized in Response Transformer, verified with mirthconnect-3.3.1.7901.b100

Imported Comment. Original Details:
Author: minht
Created: 2016-02-03T15:29:45.000-0800
