### ISSUE TITLE
Administrator cannot launch if a single client plugin fails to start

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3709]
LoadedExtensions.startPlugins loops through all client extensions and calls their start() methods. However it doesn't catch any runtime exceptions thrown by each plugin. If one plugin does throw a runtime exception from it's start() method, it's not caught until it reaches the LoginPanel.loginButtonActionPerformed, at which point the Administrator will fail to start up.

It would be nicer if the exeption was caught, logged and the Administrator is allowed to continue starting up.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3826
Reporter: brentm
Created: 2015-10-24T16:02:12.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed. If any plugin fails to start, the administrator should still launch.

Imported Comment. Original Details:
Author: jaysenp
Created: 2016-07-18T17:46:00.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** Running Java HotSpot(TM) 64-Bit Server VM 1.8.0_92 on Mac OS X (10.10.5, x86_64)
**Version(s)/Build(s) to reproduce error:** Mirth Connect 3.4.2 (Built on January 24, 2017)
**Version(s)/Build(s) to verify fixes:** Mirth Connect 3.5.0 (Built on January 24, 2017)
**How Tested:** 
* From Eclipse IDE, launch MC server & MC client in debug mode
* Verify commit in “LoadedExtensions.java”, line #215-222
* Look for one of the Client Plugin (Quick Type hierarchy)
* Pick "Text View" for this test"
* Edit TextViewer.java to throw RuntimeException during start():
`public void start() {
    throw new RuntimeException(); //testing MIRTH-3826
}`
* Launch MC server & MC client
* Verify MC client launch successfully

**Verified Fixed:** with latest build, MC Client threw an error but continue to launch successfully
`ERROR 2017-01-25 15:09:22,638 [SwingWorker-pool-1-thread-1] com.mirth.connect.client.ui.Frame: Could not start plugin: Text Viewer
java.lang.RuntimeException
at com.mirth.connect.plugins.textviewer.TextViewer.start(TextViewer.java:113)
at com.mirth.connect.client.ui.LoadedExtensions.startPlugins(LoadedExtensions.java:221)
at com.mirth.connect.client.ui.Frame.setupFrame(Frame.java:412)
at com.mirth.connect.client.ui.Mirth.<init>(Mirth.java:63)
at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:475)
at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:1)
at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)`

**Observed Failure:** with MC 342, MC client FAILED to launch with
`java.lang.RuntimeException
	at com.mirth.connect.plugins.textviewer.TextViewer.start(TextViewer.java:94)
	at com.mirth.connect.client.ui.LoadedExtensions.startPlugins(LoadedExtensions.java:213)
	at com.mirth.connect.client.ui.Frame.initializeExtensions(Frame.java:539)
	at com.mirth.connect.client.ui.Frame.setupFrame(Frame.java:401)
	at com.mirth.connect.client.ui.Mirth.<init>(Mirth.java:63)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:475)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:1)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

Imported Comment. Original Details:
Author: minht
Created: 2017-01-25T15:13:17.000-0800

**Comment by rbeckman-nextgen** [comment]
RS-23

Imported Comment. Original Details:
Author: minht
Created: 2017-01-25T15:14:56.000-0800
