### ISSUE TITLE
Stackoverflow while restoring config from 3.2.1 to 3.3.1

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3711]
While restoring a config from 3.2.1 to a 3.3.1 this error occurs:

ERROR 2015-11-02 15:18:51,876 [qtp1780462417-45] com.mirth.connect.server.servlets.ConfigurationServlet: java.lang.StackOverflowError
	at java.util.regex.Pattern$GroupHead.match(Unknown Source)
	at java.util.regex.Pattern$Loop.match(Unknown Source)
	at java.util.regex.Pattern$GroupTail.match(Unknown Source)
	at java.util.regex.Pattern$BranchConn.match(Unknown Source)
	at java.util.regex.Pattern$CharProperty.match(Unknown Source)
	at java.util.regex.Pattern$Branch.match(Unknown Source)
	at java.util.regex.Pattern$GroupHead.match(Unknown Source)
	at java.util.regex.Pattern$Loop.match(Unknown Source)

This config file can be restored with success on 3.2.1.
I have tested with other config files on this 3.3.1 and they work  so it is a particular issue with this config file.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3828
Reporter: hugosoares2
Created: 2015-11-02T07:34:32.000-0800

**Comment by rbeckman-nextgen** [comment]
Log file with full stacktrace

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-11-02T07:35:54.000-0800

**Comment by rbeckman-nextgen** [comment]
I've noticed this also, but I cannot get it to occur reliably (the same config file will restore without issue on the first or second or third attempt). Occurs in Client and Command.
I've attached a similar stack trace.

Server is installed on Linux, running Command from Linux, running client from Win7 x64

Imported Comment. Original Details:
Author: plew
Created: 2015-11-12T14:16:20.000-0800

**Comment by rbeckman-nextgen** [comment]
In my case I needed to remove a code template from the original file in order to successfully import into 3.3.1.
Basically this fucntion code template had no function declaration.(the code was commented)

/**
function etc(){
}
*/

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-11-13T02:13:44.000-0800

**Comment by rbeckman-nextgen** [comment]
This behavior also occurs if the javascript doc of a function is too detailed (using many tags). The function parsing the header seems to be recursive and thus finally by causing an overflow of the stack. 

A simple fix is to increase the stack size. E.g. changing the first line of the resource section in Mirth-Aministrator.jnlp to the following, fixes the issue:

<j2se href="http://java.sun.com/products/autodl/j2se" max-heap-size="2048m" version="1.6+" java-vm-args="-Xss1M"/>

For the mirth service add the option -Xss1M to mcservice.vmoptions

Parameter -Xss determines the stack size. Default on X86_64 systems is 128k

Details: https://docs.oracle.com/cd/E13150_01/jrockit_jvm/jrockit/jrdocs/refman/optionX.html#wp1024112

Please find further details in this thread: http://www.mirthproject.org/community/forums/showthread.php?t=217831

Imported Comment. Original Details:
Author: odo
Created: 2017-11-14T02:00:40.000-0800

**Comment by rbeckman-nextgen** [comment]
Duplicates MIRTH-4064

Imported Comment. Original Details:
Author: narupley
Created: 2018-06-11T08:29:59.000-0700
