### ISSUE TITLE
Allow access to the isolated context classloader in JavaScript

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3718]
Sometimes in JavaScript you need to instantiate and use classes from a specific version of a library, perhaps different than a version already included with Mirth Connect. Because the classloader used in the Rhino context has the overall server classloader as its parent, that will take precedence when looking up classes. So instead, if there was a way from within JavaScript to grab the isolated classloader (with no parent), then users would still be able to do this. We already do this in a roundabout way for database connections: MIRTH-3649

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3835
Reporter: narupley
Created: 2015-11-11T07:32:03.000-0800

**Comment by rbeckman-nextgen** [comment]
I think you should consider the concept of classloader priorities. So If explicitly define a resource dependency for a context (channel or connector) I am stating that I want to use the classes from that resource library first and if they do not exist use the ones from other loaders. This aproach would be natural and there would be no need to import classes differently on my JS code.

I guess this could be very similar to what java servlet containers or application servers do.
example: http://www.eclipse.org/jetty/documentation/current/jetty-classloading.html

Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-11-12T01:58:09.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 7913: Added a new ContextFactory userutil class, which can be used to retrieve the resource IDs, application classloader, and isolated (resource libraries only) classloader from within JavaScript.

Classloader priorities is an interesting idea; we'll consider that in the future. In the meantime though this should be sufficient to satisfy fringe cases where you need to load/instantiate a class from a specific library and _not_ from the overall server classpath.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-10T17:29:07.000-0800

**Comment by rbeckman-nextgen** [comment]
It would be good if contextFactory could be highlighted in our javascript editors. Other things injected in the scope do this so we should do this here too. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-03-31T15:40:08.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 7967: Added contextFactory to the list of highlighted identifiers.

Imported Comment. Original Details:
Author: narupley
Created: 2016-03-31T16:03:55.000-0700

**Comment by rbeckman-nextgen** [comment]
rev 7967 - This looks good. Isolated class loader can now be used to avoid  conflicts between resources and mirth connect libraries.

Here is a small test that loads a class with an isolated class loader
`
var contextClassLoader = java.lang.Thread.currentThread().getContextClassLoader();
var isolatedClassLoader = contextFactory.getIsolatedClassLoader();

logger.info("Normal context class loader");
getPostgresDriverVersion(contextClassLoader);
logger.info("Isolated class loader");
getPostgresDriverVersion(isolatedClassLoader);

function getPostgresDriverVersion(classLoader){
	var clazz = classLoader.loadClass("org.postgresql.Driver");
	var majorField = clazz.getField("MAJORVERSION");
	var minorField = clazz.getField("MINORVERSION");
	logger.info("Major version: " +majorField.get(null) +" Minor Version: " +minorField.get(null));
}
`

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-03-31T16:37:44.000-0700

**Comment by rbeckman-nextgen** [comment]
I need to use a newer version of HAPI so I appreciate that this is supposed to make things easier.  Unfortunately, actually using a class obtained this way seems very messy.

I originally got around the name collision issue by (manually) changing the namespace for all of HAPI.  It was painful, but it made imports unambiguous.  I'm continuing to use the namespaced version in this example as it ensures I'm not colliding with something in core:

- If you don't remove `Packages.`, you get a "Wrapped java.lang.ClassNotFoundException: Packages.com.ambassador.hl7v2.parser.CustomModelClassFactory".  Easy enough.
- When I try to call `new clazz(<args>)`, it says "is not a function, it is object".  Normally this is a bad path/missing JAR.  For many reasons (no `ClassNotFoundException` and subsequent behaviors), this doesn't seem to be the case here.
- Along with echoing the `Packages` issue, [this thread](http://www.mirthproject.org/community/forums/showthread.php?t=217134) suggests calling `newInstance()`.  I'm pretty sure they're right, but I need to pass args.  Unfortunately, passing args to `clazz.newInstance()` results in the error "Can't find method java.lang.Class.newInstance(java.util.HashMap)."
- [This SO answer](https://stackoverflow.com/a/234617) appears to show you how to work around the args issue.  Unfortunately `java.util.HashMap.class` doesn't exist.  If I drop the `class`, I get "NoSuchMethodException: com.ambassador.hl7v2.parser.CustomModelClassFactory.<init>(java.util.HashMap)".
- The signature in the Javadocs is actually `CustomModelClassFactory(Map<String,String[]> map)`.  Running the call `getDeclaredConstructor(java.util.Map)` does return the constructor `public com.ambassador.hl7v2.parser.CustomModelClassFactory(java.util.Map)`.  Looks good.

^^ These last few steps demonstrate that we're referencing the right class since it knows the class has the `Map` constructor but not the `HashMap` constructor.

Now we try to call `newIstance` on the constructor (with the arguments) and...

`
ERROR  (com.mirth.connect.server.channel.ErrorTaskHandler:25): com.mirth.connect.donkey.server.DeployException: Failed to deploy channel 7533537f-89d6-427a-9693-ea711d52f92b.
	... 
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.ambassador.hl7v2.parser.CustomModelClassFactory
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.executeScript(JavaScriptTask.java:150)
	at com.mirth.connect.server.util.javascript.JavaScriptUtil.executeScript(JavaScriptUtil.java:542)
	at com.mirth.connect.server.util.javascript.JavaScriptUtil$2.doCall(JavaScriptUtil.java:379)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:113)
	... 4 more
`

Even though I've definitely found and worked with the target class, it seems like I'm back at square one.  I hope I'm doing something wrong.  There's a huge, circuitous process to even get the right constructor and then it can't find the right class anyway.

Imported Comment. Original Details:
Author: ambsw
Created: 2019-07-17T13:46:37.000-0700

**Comment by rbeckman-nextgen** [comment]
[~ambsw], you shouldn't have to rename packages.

Try this with your updated HAPI library in a resource directory. When using an isolated ClassLoader, you need to include all dependencies in the resource dir as well, even if the server already has them.

`
var iso = Packages(contextFactory.getIsolatedClassLoader());
var myHashMap = new java.util.HashMap();
// build HashMap...
var factory = new iso.ca.uhn.hl7v2.parser.CustomModelClassFactory(myHashMap);
`


Imported Comment. Original Details:
Author: agermano
Created: 2019-11-14T14:48:24.000-0800
