### ISSUE TITLE
Add Basic authentication mode to HTTP Authentication settings

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3724]
This would add the ability to authenticate using the basic access authentication protocol ([https://en.wikipedia.org/wiki/Basic_access_authentication]).

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3841
Reporter: narupley
Created: 2015-11-24T10:24:28.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 7897: Added Basic authentication mode. Properties include the realm and user/pass credentials. For the Web Service Listener, the previous credentials table has been moved here, and the properties will migrate as such to 3.4.

Imported Comment. Original Details:
Author: narupley
Created: 2016-02-01T12:49:40.000-0800

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_71-b15 
**Version(s)/Build(s) to verify new feature:** mirthconnect-3.4.0.7918.b1877-windows-x64
**How Tested (list tests run):**
* Create 2 test channels using HTTP Sender (Destination) & HTTP Listener (Source)
* For each channel, configure HTTP Authentication using Basic Authentication, 
* For Credentials, create several users with different combination (admin/admin, user1/<empty>, ./., <empty>/admin, <long user name>/<long pw>)
* Deploy Listener channel, verify Test Connection from Sender channel
* Test sending raw msg  with different username/pw combination
=> Verify “responseStatusLine” = HTTP/1.1 200 OK
* Test with wrong name and/or password
=> Verify “responseStatusLine” = HTTP/1.1 401 Unauthorized
* Test sending msgs using Google app "Postman", verify response code &  headers (realm)
  
**Observation:**
* Realm field requires at least one character, no limit in length
* Credentials requires at least one pair of username/password, not allow duplicate username
* Username & password can be blank or at any length, with any characters (although channel won’t be able to authenticate blank username, instead getting status 401)
* Username & password are case sensitive
* Able to add multiple users (no restriction on number of users ?)
* HTTP “Test Connection” does not authenticate (does not verify username/password)
(whereas WSDL “Get Operations” will verify with authentication)


Imported Comment. Original Details:
Author: minht
Created: 2016-02-18T13:26:23.000-0800

**Comment by rbeckman-nextgen** [comment]
Content of "Sent" message from HTTP Sender
`URL: http://localhost:8090
METHOD: POST
USERNAME: admin

[HEADERS]
Sender Property 1: Sender Property 1 Value as text message

[PARAMETERS]

[CONTENT]
MSH](^~\&||LAB1||SITE1|200812091126|SECURITY|ADT^A01^ADT_A01|MSG00001|P|2.5|EVN|A01|200812091126||PID|1||1001||OHALLAHAN^COLLEEN^^||19850704|F||2106-3|1200 N ELM STREET^^NEWPORT BEACH^CA^92660-1020^US^H|OC|(949) 555-1234|(949) 555-5678||S||NK1|1|OHALLAHAN^BRITTANY^M|SIS^SISTER||||N^NEXT-OF-KINPV1|1|I|2000^2012^01||||001122^ZOIDBERG^JOHN^|||SUR||||1|A0||||12345`

Content of Source "headers" mappings from HTTP Listener
`{authorization=[Basic YWRtaW46YWRtaW4=), content-length=[366], accept-encoding=[gzip,deflate], sender property 1=[Sender Property 1 Value as text message], connection=[keep-alive], host=[localhost:8090], user-agent=[Apache-HttpClient/4.5.1 (Java/1.8.0_71)], content-type=[text/plain; charset=UTF-8]}`

Imported Comment. Original Details:
Author: minht
Created: 2016-02-18T14:32:57.000-0800

**Comment by rbeckman-nextgen** [comment]
**Version(s)/Build(s) to verify new feature:** mirthconnect-3.4.0.7931.b1890 & ssl-3.4.0.7931.b1953
**How tested:**
* Install SSL extension
* Configure SSL certificate
* Use the same test channels, enable SSL on both Listener & Sender 
* Verify messages sent successfully

**Observation:**
Tested Basic Authentication mode with SSL enabled successfully 

Imported Comment. Original Details:
Author: minht
Created: 2016-02-29T15:01:52.000-0800

**Comment by rbeckman-nextgen** [comment]
Successfully verified Basic Authentication mode using HTTP Listener & Sender 

Imported Comment. Original Details:
Author: minht
Created: 2016-02-29T15:02:39.000-0800

**Comment by rbeckman-nextgen** [comment]
Channels with a Web Service Listener and that don't have any pluginProperties node already in the XML will fail to migrate to 3.4 with an underlying NPE.

Imported Comment. Original Details:
Author: narupley
Created: 2016-03-31T13:33:07.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed the above bug.

Imported Comment. Original Details:
Author: narupley
Created: 2016-03-31T13:46:48.000-0700

**Comment by rbeckman-nextgen** [comment]
ERROR importing channel from MC 303
`Channel "MIRTH3841_WSDL Listener 8081" is invalid.  Original cause:
An error occurred while attempting to migrate serialized object element: properties : An error occurred while attempting to migrate serialized object element: properties
---- Debugging information ----
message             : An error occurred while attempting to migrate serialized object element: properties
cause-exception     : com.mirth.connect.donkey.util.xstream.SerializerException
cause-message       : An error occurred while attempting to migrate serialized object element: properties
class               : com.mirth.connect.connectors.ws.WebServiceReceiverProperties
required-type       : com.mirth.connect.connectors.ws.WebServiceReceiverProperties
converter-type      : com.mirth.connect.model.converters.MigratableConverter
class[1]            : com.mirth.connect.model.Connector
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: An error occurred while attempting to migrate serialized object element: properties : An error occurred while attempting to migrate serialized object element: properties
---- Debugging information ----
message             : An error occurred while attempting to migrate serialized object element: properties
cause-exception     : com.mirth.connect.donkey.util.xstream.SerializerException
cause-message       : An error occurred while attempting to migrate serialized object element: properties
class               : com.mirth.connect.connectors.ws.WebServiceReceiverProperties
required-type       : com.mirth.connect.connectors.ws.WebServiceReceiverProperties
converter-type      : com.mirth.connect.model.converters.MigratableConverter
class[1]            : com.mirth.connect.model.Connector
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:99)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:99)
at com.mirth.connect.model.converters.ChannelConverter.unmarshal(ChannelConverter.java:80)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:206)
at com.mirth.connect.client.ui.ChannelPanel.importChannel(ChannelPanel.java:1229)
at com.mirth.connect.client.ui.ChannelPanel.doImportChannel(ChannelPanel.java:1217)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at sun.reflect.misc.Trampoline.invoke(Unknown Source)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
at java.beans.EventHandler.invokeInternal(Unknown Source)
at java.beans.EventHandler.access$000(Unknown Source)
at java.beans.EventHandler$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.beans.EventHandler.invoke(Unknown Source)
at com.sun.proxy.$Proxy46.actionPerformed(Unknown Source)
at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at org.jdesktop.swingx.JXHyperlink.fireActionPerformed(JXHyperlink.java:264)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.mirth.connect.donkey.util.xstream.SerializerException: An error occurred while attempting to migrate serialized object element: properties
at com.mirth.connect.model.converters.MigratableConverter.migrateElement(MigratableConverter.java:140)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:88)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 76 more
Caused by: java.lang.NullPointerException
at com.mirth.connect.connectors.ws.WebServiceReceiverProperties.migrate3_4_0(WebServiceReceiverProperties.java:125)
at com.mirth.connect.model.converters.MigratableConverter.migrateElement(MigratableConverter.java:137)
... 78 more
 enable channel`

Imported Comment. Original Details:
Author: minht
Created: 2016-04-05T21:04:48.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_77-b03
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.0.7958.b1917-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.4.0.7972.b1931-windows-x64
**How Tested:**
* Download the attached test channels (Archives.zip)
( WSDL & HTTP Listener channels from Mirth Connect 3.0.3 instance)
* Import channels using Channel Tasks > Import Channel
* Verify import successfully 
* Deploy channels
* Verify deploy successfully and able to receive msgs
* Repeat this test using Drag & Drop to Import

**Observation:**
 After FIXED 
=> successfully imported channels using both methods, 
=> also deployed listener channels and successfully sent & rec'd msgs  

Imported Comment. Original Details:
Author: minht
Created: 2016-04-05T21:23:11.000-0700

**Comment by rbeckman-nextgen** [comment]
test channels from MC 303

Imported Comment. Original Details:
Author: minht
Created: 2016-04-05T21:27:31.000-0700

**Comment by rbeckman-nextgen** [comment]
successfully verified import NPE error with latest build

Imported Comment. Original Details:
Author: minht
Created: 2016-04-05T21:28:12.000-0700
