### ISSUE TITLE
Mirth does not boot after OutOgMemoryError

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3732]
During a deployment of a lot of channels Mirth gave an outofmemory error. After killing the process (during deployment) and assigning more memory to the mirth process I get several log entries like bellow during boot. Mirth ends up the boot process normally with:
INFO  2015-12-02 19:32:56,384 [Thread-1] com.mirth.connect.server.Mirth: Web server running at http://192.168.105.25:8080/ and https://192.168.105.25:8443/

But I cannot enter the admin console, it says "Mirth still starting or unavailable". This is extremelly bad because this installation is now corrupted.

ERROR 2015-12-02 19:27:48,461 [pool-45-thread-1] com.mirth.connect.server.channel.LoggingTaskHandler: java.lang.NullPointerException
	at com.mirth.connect.donkey.server.channel.Channel.updateCurrentState(Channel.java:219)
	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.doDeploy(DonkeyEngineController.java:1203)
	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.execute(DonkeyEngineController.java:1185)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:59)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3849
Reporter: hugosoares2
Created: 2015-12-02T11:40:19.000-0800

**Comment by rbeckman-nextgen** [comment]
Before all those log entries I also got this one:
ERROR 2015-12-02 19:26:53,394 [Thread-1] com.mirth.connect.server.Mirth: com.mirth.connect.donkey.server.data.DonkeyDaoException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'mirthpnb1.d_ms233' doesn't exist



Imported Comment. Original Details:
Author: hugosoares2
Created: 2015-12-02T11:41:00.000-0800
