### ISSUE TITLE
Hiding or moving the ID column on the Channels view causes errors

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3739]
`Exception in thread "AWT-EventQueue-2" java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.String
	at com.mirth.connect.client.ui.ChannelPanel$8.isHighlighted(ChannelPanel.java:434)
	at org.jdesktop.swingx.decorator.AbstractHighlighter.highlight(AbstractHighlighter.java:170)
	at org.jdesktop.swingx.decorator.CompoundHighlighter.doHighlight(CompoundHighlighter.java:235)
	at org.jdesktop.swingx.decorator.AbstractHighlighter.highlight(AbstractHighlighter.java:172)
	at org.jdesktop.swingx.JXTable.prepareRenderer(JXTable.java:3555)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
	at javax.swing.plaf.ComponentUI.update(Unknown Source)
	at javax.swing.JComponent.paintComponent(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3856
Reporter: narupley
Created: 2015-12-22T08:51:29.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 7874/7875.

Imported Comment. Original Details:
Author: narupley
Created: 2015-12-22T08:55:55.000-0800

**Comment by rbeckman-nextgen** [comment]
**Server(s) and URLs Used:** virtual Window 7 with JRE version 1.8.0_71-b15 
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.3.1.7856.b91-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.3.1.7901.b100-windows-x64
**How Tested (list tests run):**
* Clear Java cache before launching Mirth Connect (using javaws -clearcache)
* Enable Java console from Window Start > All Programs > Java > Configure Java > Advanced > Java console > select "Show console"
* Launching Mirth Connect console > Channels > on the right panel, select Filter > Restore to Default (see screenshot)
* From Filter list, select to show "Local ID" column,  check Java console for any log message
* From Filter list, select to hide "ID" column, check Java console for any log message
* From Channel listing, click and drag "ID" column to another space, check Java console for any log message 

**Additional Info:** Once the Exception occurs, Channels view becomes sluggish, some columns are white-out, have to select "Restore Default" from Filter list to get back to normal 

**Verified Fixed:**
Problem does not exhibit with mirthconnect-3.3.1.7901.b100-windows-x64

Imported Comment. Original Details:
Author: minht
Created: 2016-02-04T15:03:30.000-0800

**Comment by rbeckman-nextgen** [comment]
Verified no longer getting java exception when moving or hiding ID column with mirthconnect-3.3.1.7901.b100-windows-x64

Imported Comment. Original Details:
Author: minht
Created: 2016-02-04T15:04:30.000-0800
