### ISSUE TITLE
NullPointerException when using JavaScript batch processing with an empty script

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3751]
This appears to happen for all data types except Delimited Text. For delimited text an appropriate BatchMessageException is thrown when the script is empty, but the other data types don't do this.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3869
Reporter: narupley
Created: 2016-01-18T11:49:15.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 7888: All batch adaptors that support scripts now correctly check if the script is empty before attempting to do anything else.

Imported Comment. Original Details:
Author: narupley
Created: 2016-01-20T18:30:26.000-0800

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_77-b03
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.3.2.7909.b103-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.4.0.7958.b1917-windows-x64
**How Tested:**
* Create Test Channel with 
** Source = Channel Reader/Writer, Process Batch = "Yes"
** Destination = Channel Writer
* Channel Summary > Set Data Types 
** change Source Connector Inbound = "HL7 v2"
** Inbound Properties > Split Batch By = "JavaScript", without editting script
* Save and deploy channel
* Send HL7 batch message to Test Channel
* Repeat test with other data types except for DICOM (Delimited,EDI,HL7 v2,HL7 v3,JSON,NCPDP,Raw,XML)

**Observation:**
Before fixes, users were getting a generic error _java.lang.NullPointerException_ in _Server Log_  
`[2016-03-29 16:34:07,351]  ERROR (com.mirth.connect.plugins.datatypes.raw.RawBatchAdaptor:137): java.lang.NullPointerException
[2016-03-29 16:34:43,608]  ERROR (com.mirth.connect.plugins.datatypes.hl7v2.ER7BatchAdaptor:219): java.lang.NullPointerException `

FIXED => users will see a more descriptive error indicating "No batch script was set."
`[2016-03-29 16:03:10,600]  ERROR (com.mirth.connect.server.api.servlets.MessageServlet:110): Error processing batch message
com.mirth.connect.donkey.server.message.batch.BatchMessageException: No batch script was set.
	at com.mirth.connect.plugins.datatypes.hl7v2.ER7BatchAdaptor.getMessageFromReader(ER7BatchAdaptor.java:180)
	at com.mirth.connect.plugins.datatypes.hl7v2.ER7BatchAdaptor.getNextMessage(ER7BatchAdaptor.java:102)
	at com.mirth.connect.donkey.server.message.batch.BatchAdaptor.getMessage(BatchAdaptor.java:37)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchBatchMessage(SourceConnector.java:230)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:1044)
	at com.mirth.connect.server.api.servlets.MessageServlet$2.run(MessageServlet.java:106)
	at java.lang.Thread.run(Unknown Source)`



Imported Comment. Original Details:
Author: minht
Created: 2016-03-29T16:50:01.000-0700

**Comment by rbeckman-nextgen** [comment]
Successfully verified BatchMessageException with Delimited,EDI,HL7 v2,HL7 v3,JSON,NCPDP,Raw,XML data types

Imported Comment. Original Details:
Author: minht
Created: 2016-03-29T16:51:31.000-0700

**Comment by rbeckman-nextgen** [comment]
DELIMITED TEXT
`[2016-03-29 16:24:28,200]  ERROR (com.mirth.connect.server.api.servlets.MessageServlet:110): Error processing batch message
com.mirth.connect.donkey.server.message.batch.BatchMessageException: No batch script was set.
	at com.mirth.connect.plugins.datatypes.delimited.DelimitedBatchAdaptor.getMessage(DelimitedBatchAdaptor.java:230)
	at com.mirth.connect.plugins.datatypes.delimited.DelimitedBatchAdaptor.getMessageFromReader(DelimitedBatchAdaptor.java:103)
	at com.mirth.connect.plugins.datatypes.delimited.DelimitedBatchAdaptor.getNextMessage(DelimitedBatchAdaptor.java:94)
	at com.mirth.connect.donkey.server.message.batch.BatchAdaptor.getMessage(BatchAdaptor.java:37)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchBatchMessage(SourceConnector.java:230)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:1044)
	at com.mirth.connect.server.api.servlets.MessageServlet$2.run(MessageServlet.java:106)
	at java.lang.Thread.run(Unknown Source)`

EDI `
	at com.mirth.connect.plugins.datatypes.edi.EDIBatchAdaptor.getMessageFromReader(EDIBatchAdaptor.java:100)
	at com.mirth.connect.plugins.datatypes.edi.EDIBatchAdaptor.getNextMessage(EDIBatchAdaptor.java:70)
`

HL7 `
        at com.mirth.connect.plugins.datatypes.hl7v2.ER7BatchAdaptor.getMessageFromReader(ER7BatchAdaptor.java:180)
	at com.mirth.connect.plugins.datatypes.hl7v2.ER7BatchAdaptor.getNextMessage(ER7BatchAdaptor.java:102)
...
	at com.mirth.connect.plugins.datatypes.hl7v3.HL7V3BatchAdaptor.getMessageFromReader(HL7V3BatchAdaptor.java:99)
	at com.mirth.connect.plugins.datatypes.hl7v3.HL7V3BatchAdaptor.getNextMessage(HL7V3BatchAdaptor.java:70)
`

JSON `
	at com.mirth.connect.plugins.datatypes.json.JSONBatchAdaptor.getMessageFromReader(JSONBatchAdaptor.java:99)
	at com.mirth.connect.plugins.datatypes.json.JSONBatchAdaptor.getNextMessage(JSONBatchAdaptor.java:70)
`

NDPDP `
	at com.mirth.connect.plugins.datatypes.ncpdp.NCPDPBatchAdaptor.getMessageFromReader(NCPDPBatchAdaptor.java:99)
	at com.mirth.connect.plugins.datatypes.ncpdp.NCPDPBatchAdaptor.getNextMessage(NCPDPBatchAdaptor.java:70)
`

RAW `
	at com.mirth.connect.plugins.datatypes.raw.RawBatchAdaptor.getMessageFromReader(RawBatchAdaptor.java:99)
	at com.mirth.connect.plugins.datatypes.raw.RawBatchAdaptor.getNextMessage(RawBatchAdaptor.java:70)
`

XML `
	at com.mirth.connect.plugins.datatypes.xml.XMLBatchAdaptor.getMessageFromReader(XMLBatchAdaptor.java:146)
	at com.mirth.connect.plugins.datatypes.xml.XMLBatchAdaptor.getNextMessage(XMLBatchAdaptor.java:87)
`

Imported Comment. Original Details:
Author: minht
Created: 2016-03-29T16:52:19.000-0700
