### ISSUE TITLE
Importing a channel that has empty code template libraries fails

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3790]
If the channel has a code template library but that library doesn't have any code templates, the import will fail:

`Exception in thread "AWT-EventQueue-2" java.lang.NullPointerException
        at com.mirth.connect.client.ui.codetemplate.CodeTemplateImportDialog.updateImportButton(CodeTemplateImportDialog.java:1465)
        at com.mirth.connect.client.ui.codetemplate.CodeTemplateImportDialog.initComponents(CodeTemplateImportDialog.java:521)
        at com.mirth.connect.client.ui.codetemplate.CodeTemplateImportDialog.<init>(CodeTemplateImportDialog.java:121)
        at com.mirth.connect.client.ui.Frame.importChannel(Frame.java:3402)
        at com.mirth.connect.client.ui.Frame.doImport(Frame.java:3306)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at java.beans.EventHandler.invokeInternal(EventHandler.java:482)
        at java.beans.EventHandler.access$000(EventHandler.java:279)
        at java.beans.EventHandler$1.run(EventHandler.java:430)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.beans.EventHandler.invoke(EventHandler.java:428)
        at com.sun.proxy.$Proxy10.actionPerformed(Unknown Source)
        at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at org.jdesktop.swingx.JXHyperlink.fireActionPerformed(JXHyperlink.java:264)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6535)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6300)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4891)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
        at java.awt.Container.dispatchEventImpl(Container.java:2280)
        at java.awt.Window.dispatchEventImpl(Window.java:2750)
        at java.awt.Component.dispatchEvent(Component.java:4713)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3909
Reporter: narupley
Created: 2016-04-06T12:30:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revision 7976. The conflicts object on the library table node is now always being created, so it should never be null even if the library doesn't have any code templates.

Imported Comment. Original Details:
Author: narupley
Created: 2016-04-06T12:33:09.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_77-b03
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.0.7973.b1932-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.4.0.7958.b1917-windows-x64
**How Tested:**
* Using fresh install instance of Mirth Connect
* From Channels > Channel Tasks > Edit Code Templates 
** code template & library should be empty 
** select New Library to create “Library 1” > Save Changes
* From Settings > Administrator > System Preferences > 
Import code template libraries with channels = YES
Export code template libraries with channels = YES
* From Channels > Create New Channel > 
** provide channel name 
** select Set Dependencies > Code Template Libraries > select Library 1 > OK
** Save Changes
* Export Channel 
* Remove existing Channel
* Import Channel from exported file  

**Observation:**
* Before fixed => import failed with "java.lang.NullPointerException"
* After FIXED, import test channel successfully 
* After FIXED,{color:red} import getting below Exception when Code Template Library already exists {color}
`ERROR 2016-04-08 09:32:51,677 [AWT-EventQueue-2] com.mirth.connect.client.ui.Frame: Unable to save code template libraries: There is already a code template library with the name Library 1
java.lang.Exception: There is already a code template library with the name Library 1
at com.mirth.connect.server.controllers.DefaultCodeTemplateController.updateLibraries(DefaultCodeTemplateController.java:163)
at com.mirth.connect.server.controllers.DefaultCodeTemplateController.updateLibrariesAndTemplates(DefaultCodeTemplateController.java:551)
at com.mirth.connect.server.api.servlets.CodeTemplateServlet.updateLibrariesAndTemplates(CodeTemplateServlet.java:139)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.server.api.providers.MirthResourceInvocationHandlerProvider$1.invoke(MirthResourceInvocationHandlerProvider.java:211)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
at com.mirth.connect.server.MethodFilter.doFilter(MethodFilter.java:37)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at com.mirth.connect.server.api.providers.ApiOriginFilter.doFilter(ApiOriginFilter.java:35)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Unknown Source) `

Imported Comment. Original Details:
Author: minht
Created: 2016-04-08T09:57:11.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed the above bug in r7985.

Imported Comment. Original Details:
Author: narupley
Created: 2016-04-08T11:43:46.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified with mirthconnect-3.4.0.7985.b1944-windows-x64, no longer getting exception when import channel with an existing code template

Imported Comment. Original Details:
Author: minht
Created: 2016-04-08T14:44:42.000-0700

**Comment by rbeckman-nextgen** [comment]
Successfully verified import channel with empty code template library

Imported Comment. Original Details:
Author: minht
Created: 2016-04-08T14:45:23.000-0700
