### ISSUE TITLE
Channel Viewing causes java.lang.IllegalArgumentException in java log

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3794]
`Exception in thread "AWT-EventQueue-2" java.lang.IllegalArgumentException: column must be valid, was-1
	at org.jdesktop.swingx.JXTreeTable.isHierarchical(JXTreeTable.java:2022)
	at org.jdesktop.swingx.JXTreeTable.getToolTipText(JXTreeTable.java:1459)
	at javax.swing.ToolTipManager$insideTimerAction.actionPerformed(ToolTipManager.java:663)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3913
Reporter: minht
Created: 2016-04-08T13:29:52.000-0700

**Comment by rbeckman-nextgen** [comment]
ISSUE DESCRIPTION
**OS(s) /JREs Used:** Window 7 as well as MacOSx 10.10.5
**Issue found /exists in Version(s)/Build(s):** during 3.4 testing when Channel Group view was introduced
mirthconnect-3.4.0.7982.b1941-unix 
mirthconnect-3.4.0.7982.b1941-windows-x64
**Is the Issue Consistent (list details):** Only getting this exception when scroll up & down Channel list with white space on the far right
**Pre-Steps:**
Need to have around 50 channels or enough to see the scroll bar (attached config file)
Make sure java log is enabled to capture the exception
**Steps to Reproduce:**
* Restore the attached Config file
* Go to Channels > Columns Setting > Uncheck Description
* Scroll up and down to view channels
* Switch view between Channel Group to Channels list

Imported Comment. Original Details:
Author: minht
Created: 2016-04-08T13:58:53.000-0700
