### ISSUE TITLE
Command Line Interface libraries not being included correctly

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3814]
Not all of the Jersey-related libraries are being included correctly in cli-lib. To fix this in the meantime, just copy the following from server-lib to cli-lib:
\\
\\
* javassist-3.19.0-GA.jar
\\
\\
* **donkey/**
** guava-18.0.jar
\\
\\
* **javax/**
** javax.annotation-api-1.2.jar
** javax.inject-2.4.0-b31.jar
** javax.ws.rs-api-2.0.1.jar
\\
\\
* **jersey/**
** jersey-client-2.22.1.jar
** jersey-common-2.22.1.jar
** jersey-guava-2.22.1.jar
** jersey-media-multipart-2.22.1.jar
** jersey-proxy-client-2.22.1.jar
\\
\\
*** *ext/**
*** hk2-api-2.4.0-b31.jar
*** hk2-locator-2.4.0-b31.jar
*** hk2-utils-2.4.0-b31.jar
*** mimepull-1.9.6.jar
\\
\\
* **swagger/**
** swagger-annotations-1.5.4.jar
\\
\\
*** *ext/**
*** reflections-0.9.10.jar

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3934
Reporter: narupley
Created: 2016-04-21T08:47:32.000-0700

**Comment by rbeckman-nextgen** [comment]
Similar problem for the server manager, except it only matters when the service is actually attempted to be started.

Imported Comment. Original Details:
Author: narupley
Created: 2016-05-06T15:58:55.000-0700

**Comment by rbeckman-nextgen** [comment]
Revisions 8023/8024: Fixed issues with the CLI and Server Manager where certain libraries weren't being correctly included. The manager controller will now also correctly check for status values of 0 and 3, and close the Client object after using it.

Imported Comment. Original Details:
Author: narupley
Created: 2016-05-06T16:39:33.000-0700

**Comment by rbeckman-nextgen** [comment]
Error starting mccommand in 3.4.0
`C:\Program Files\Mirth Connect>mccommand.exe
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:53)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.exe4j.runtime.LauncherEngine.launch(Unknown Source)
        at com.exe4j.runtime.WinLauncher.main(Unknown Source)
        at com.install4j.runtime.launcher.WinLauncher.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: org/glassfish/jersey/client/spi/ConnectorProvider
        at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:175)
        at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:161)
        at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:104)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.client.spi.ConnectorProvider
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 15 more
 `

Imported Comment. Original Details:
Author: minht
Created: 2016-05-10T10:45:52.000-0700

**Comment by rbeckman-nextgen** [comment]
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.0.8000.b1959-windows-x64
**Version(s)/Build(s) to verify fixes:** 
Windows
mirthconnect-3.4.1.8024.b122-windows-x64.exe
mirthconnect-3.4.1.8024.b122-windows-x64.zip
Unix/Linux 
mirthconnect-3.4.1.8024.b122-unix.sh
mirthconnect-3.4.1.8024.b122-unix.tar.gz
mirthconnect-3.4.1.8024.b122-linux.rpm

**How Tested:**
* Install Mirth Connect
* Launch Mirth Connect Server Manager, 
* Stop/Start/Restart MC services from Server Manager > verify status message
* Launch Administrator from Server Manager > verify login connection
* Run mccommand.exe or ./mccommand 
* Run mcservice status/start/stop
* Run mcserver.exe or ./mcserver

**Observation:**
* Successfully launch Mirth Connect Server Manager and able to start/stop/restart service
* Verified service start/stop successfully
!infomsg.png!

!infomsgUbuntu.png!

* Successfully launch Command Line Interface 
`mtran@minh-vUbuntu:/usr/local/mirthconnect$ java -jar mirth-cli-launcher.jar
Connected to Mirth Connect server @ https://127.0.0.1:8443 (3.4.1.8024)
$quit
Disconnected from server.
mtran@minh-vUbuntu:/usr/local/mirthconnect$ ./mccommand
Connected to Mirth Connect server @ https://127.0.0.1:8443 (3.4.1.8024)
$quit
Disconnected from server.`
`C:\Program Files\Mirth Connect>mccommand -a https://localhost:8447
Connected to Mirth Connect server @ https://localhost:8447 (3.4.1.8024)
$quit 
Disconnected from server.` 

Imported Comment. Original Details:
Author: minht
Created: 2016-05-10T14:53:41.000-0700

**Comment by rbeckman-nextgen** [comment]
File Count with **mirthconnect-3.4.1.8024.b122**
`C:\Program Files\Mirth Connect\server-lib>dir *.* /w /s
     Total Files Listed:
             126 File(s)     70,221,322 bytes
              35 Dir(s)  36,793,491,456 bytes free

C:\Program Files\Mirth Connect\cli-lib>dir *.* /w /s
     Total Files Listed:
              42 File(s)     22,828,409 bytes
               2 Dir(s)  36,793,491,456 bytes free

mtran@minh-vUbuntu:/usr/local/mirthconnect$ find server-lib -type f | wc -l
126
mtran@minh-vUbuntu:/usr/local/mirthconnect$ find cli-lib -type f | wc -l
42
`

File Count with **mirthconnect-3.4.0.8000.b1959**
`C:\Program Files\Mirth Connect\server-lib>dir *.* /w /s
     Total Files Listed:
             126 File(s)     70,221,135 bytes
              35 Dir(s)  37,222,703,104 bytes free

C:\Program Files\Mirth Connect\cli-lib>dir *.* /w /s
     Total Files Listed:
              26 File(s)     17,102,880 bytes
               2 Dir(s)  37,222,703,104 bytes free

USING ./mirthconnect-3.4.0.8000.b1959-unix.sh
mtran@minh-vUbuntu:/usr/local/MC340$ find server-lib -type f | wc -l
126
mtran@minh-vUbuntu:/usr/local/MC340$ find cli-lib -type f | wc -l
26

USING TAR.GZ mirthconnect-3.4.0.8000.b1959-unix 
Minhs-iMac:mirthconnect-3.4.0.8000.b1959-unix minhtran$ find server-lib -type f | wc -l
     126
Minhs-iMac:mirthconnect-3.4.0.8000.b1959-unix minhtran$ find cli-lib -type f | wc -l
      26`

Imported Comment. Original Details:
Author: minht
Created: 2016-05-10T15:45:32.000-0700

**Comment by rbeckman-nextgen** [comment]
Successfully verified Mirth Connect CLI using mirthconnect-3.4.1.8024.b122

Imported Comment. Original Details:
Author: minht
Created: 2016-05-10T16:16:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Running CLI interface on MacOSx
`Minhs-iMac:mirthconnect-3.4.1.8024.b122-unix minhtran$ ./mccommand
Connected to Mirth Connect server @ https://127.0.0.1:8443 (3.4.1.8024)
$user add cli-user cli-user CLI USER QA cli-user@mirthcorp.com
User "cli-user" added successfully.
$quit
Disconnected from server.
Minhs-iMac:mirthconnect-3.4.1.8024.b122-unix minhtran$ ./mccommand -u cli-user -p cli-user 
Connected to Mirth Connect server @ https://127.0.0.1:8443 (3.4.1.8024)
$codetemplate library list
Name                    Id                                    Revision  Last Modified
----------------------  ------------------------------------  --------  -------------------
CustomJS                6a32d94d-408c-4e10-9799-e45e150b5c1f  1         2016-05-10 16:07:02
FHIR Helper Functions   a084db27-49e0-4c67-893b-ffcc9f1d6e94  2         2016-05-10 16:07:21
RequiredforMirthResult  f1a44910-4070-45ac-83ca-cb34312eb280  2         2016-05-10 16:07:21
$status
ID					Status		Name
$channel list
ID					Enabled		Name
823699bf-6257-481c-8c8a-5ade277994fa	NO		9104_Listener_FilterTransformer
b159c4c4-9d04-4275-8023-46321cd4e391	NO		9104_Listener_simpleMLLP
5e1f40ff-7476-4b0e-81b1-93acddf1caaa	NO		9104_Sender_MLLP
7a0d10a8-0eea-4c6f-b93c-6885e7a98a64	NO		ChannelMap_Counter_1s`

Imported Comment. Original Details:
Author: minht
Created: 2016-05-10T16:16:55.000-0700
