### ISSUE TITLE
LLP Listener 2.x to 3.x migration is incorrect when record separator is zero

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3856]
For the migration we are concatenating the end of message and record separator fields together. However in 2.x the record separator wasn't used at all if it happened to be 0x00. So we should check for that and ignore it in migration if that's the case.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3978
Reporter: narupley
Created: 2016-06-07T08:33:01.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 8059/8060. Note that this would only really have affected the "Hex" mode in 2.x, because if you had a literal `<NUL>` character in that property for the "ASCII" mode, the channel won't import anyway. That's correct, since that character isn't valid per the XML specifications.

Imported Comment. Original Details:
Author: narupley
Created: 2016-06-07T09:15:36.000-0700

**Comment by rbeckman-nextgen** [comment]
Error sending msgs to LLP Listener imported from MC 2.x verison
`[2016-07-01 11:18:18,485]  ERROR (com.mirth.connect.connectors.tcp.TcpReceiver:739): Error receiving message (TCP Listener "Source" on channel fcbb916a-e0e1-47a3-8914-bde2d94bb92e).
com.mirth.connect.model.transmission.framemode.FrameStreamHandlerException: End of message bytes (<FS><NUL>) not detected. Last bytes received: <CR><FS>
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:221)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.readBytes(TcpReceiver.java:806)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:613)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:505)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source) `

Imported Comment. Original Details:
Author: minht
Created: 2016-07-01T15:19:22.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_91-b14
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.1.8057.b139-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.5.0.8076.b1999-windows-x64

**PRE-STEPS:** (or used the attached test channels)
* Download and install MC 2.x version ( mirthconnect-2.2.3.6825.b80-windows-x64)
* Create LLP Listener channel with
	Source = LLP Listener, Frame Encoding = Hex, Record Separator Char = 0x00 
        !LLP223.png!
	Destination = Channel Writer
* Save & Export Listener Channel for Upgrade test

**How Tested:**
* Launch Mirth Connect instance at 3.x version
* Import Listener channel from above
* Listener channel > TCP Listener MLLP setting > Verify "End of Message Bytes" coding
* Deploy Listener channel 
* Create & deploy an LLP Sender channel (at 3.x) to send HL7 message to Listener channel
* Verify able send msg to Listener channel

**Verified Fixed:**
There is no error during Import/Upgrade. However, the MLLP setting is upgraded as followed:
_imported to MC 3.4.1 (incorrect)_: **<VT><Message Data><FS><NULL>**
!LLP341.png!

_imported to MC 3.5.0 (**fixed, record separator is ignored*)_: *<VT><Message Data><FS>**
!LLP350.png!

**Additional Info:**
Default setting for MLLP Sender/Listener =>Record Separator Char = **0x0D**
MLLP Sample Frame <VT> <Message Data> <FS> <CR>

Imported Comment. Original Details:
Author: minht
Created: 2016-07-01T15:32:44.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified with mirthconnect-3.5.0.8076.b1999

Imported Comment. Original Details:
Author: minht
Created: 2016-07-06T13:08:54.000-0700

**Comment by rbeckman-nextgen** [comment]
Can we put the FS Character code for File writer?

currently this feature is missing in File writer destination

its available for MLLP.

Imported Comment. Original Details:
Author: luxnixs_28
Created: 2020-02-18T00:56:44.000-0800
