### ISSUE TITLE
Possible race condition when starting TCP Listeners

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3857]
In the onStart() method getCurrentState() is checked in a while loop to ensure it's STARTED. However that thread is started immediately afterwards, and the current state is set after onStart() finishes. So it's possible that the TCP Listener is started but no sockets are ever accepted from the server socket.

[http://www.mirthcorp.com/community/forums/showthread.php?t=216085]

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3979
Reporter: narupley
Created: 2016-06-07T10:01:00.000-0700

**Comment by rbeckman-nextgen** [comment]
The code has been modified so that race conditions will no longer occur sporadically.

Imported Comment. Original Details:
Author: jaysenp
Created: 2016-07-18T17:43:35.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** Running Java HotSpot(TM) 64-Bit Server VM 1.8.0_92 on Mac OS X (10.10.5, x86_64)
**Version(s)/Build(s) to reproduce error:** Mirth Connect 3.4.2 (Built on January 24, 2017)
**Version(s)/Build(s) to verify fixes:** Mirth Connect 3.5.0 (Built on January 24, 2017)
**How Tested:** 
* From Eclipse IDE, launch MC server & MC client in debug mode
* Edit file “TcpReceiver.java”, at line #266/267  _thread.start();_, add the followings
` try {
    Thread.sleep(1000);
} catch (InterruptedException e) {
	// TODO Auto-generated catch block
	e.printStackTrace();
} `
* Create Listener channel with Source = TCP Listener port 6661
* Create Sender channel with Destination = TCP Sender, port 661
* Deploy both channels
* Send an HL7 message to Sender channel
* Verify msg received on Listener channel

**Verified Fixed:** with the latest build, Listener was able to receive msgs
**Observed Failure:** Sender channel failed to send message with the following error
`TCP Sender error
ERROR MESSAGE: Timeout waiting for response: Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:120)
	at com.mirth.connect.connectors.tcp.TcpDispatcher.send(TcpDispatcher.java:265)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:822)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:476)
	at com.mirth.connect.donkey.server.channel.DestinationChain.doCall(DestinationChain.java:121)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:63)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1715)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1198)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:1053)
	at com.mirth.connect.server.api.servlets.MessageServlet$2.run(MessageServlet.java:106)
	at java.lang.Thread.run(Thread.java:745)`

Imported Comment. Original Details:
Author: minht
Created: 2017-01-25T14:02:31.000-0800

**Comment by rbeckman-nextgen** [comment]
RS-22

Imported Comment. Original Details:
Author: minht
Created: 2017-01-25T14:03:05.000-0800
