### ISSUE TITLE
Allow plugins to modify properties on server config restore

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3873]
There needs to be a hook when restoring server configurations so that plugins can choose to modify and/or migrate properties first. Right now all properties from the config immediately overwrite whatever is in the database. Sometimes an intelligent merge needs to be done instead.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3995
Reporter: narupley
Created: 2016-07-08T12:46:18.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 8081: Added interface so that plugins can modify properties on server config restore before they are saved to the database.

Imported Comment. Original Details:
Author: narupley
Created: 2016-07-08T12:53:53.000-0700

**Comment by rbeckman-nextgen** [comment]
ERROR in server log when restoring config with mismatched users vs roles (User Authorization plugin)

`[2016-07-12 14:52:06,013]  ERROR (com.mirth.connect.server.controllers.DefaultConfigurationController:718): Error restoring User Authorization properties.
com.mirth.connect.client.core.ControllerException: At least one user must have the Administrator role.
	at com.mirth.connect.plugins.auth.server.SecureAuthorizationController.modifyPropertiesOnRestore(Unknown Source)
	at com.mirth.connect.plugins.auth.server.UserAuthorizationService.modifyPropertiesOnRestore(Unknown Source)
	at com.mirth.connect.server.controllers.DefaultConfigurationController.setServerConfiguration(DefaultConfigurationController.java:713)
	at com.mirth.connect.server.api.servlets.ConfigurationServlet.setServerConfiguration(ConfigurationServlet.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.mirth.connect.server.api.providers.MirthResourceInvocationHandlerProvider$1.invoke(MirthResourceInvocationHandlerProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at com.mirth.connect.server.MethodFilter.doFilter(MethodFilter.java:37)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at com.mirth.connect.server.api.providers.ApiOriginFilter.doFilter(ApiOriginFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Unknown Source)`

ERROR in client log (Popup window as well as java console log)
`ERROR 2016-07-12 15:09:49,695 [SwingWorker-pool-51-thread-3] com.mirth.connect.client.ui.Frame: You are not authorized to perform this action.

HTTP/1.1 403 Forbidden
com.mirth.connect.client.core.ForbiddenException: HTTP/1.1 403 Forbidden
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:395)
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:210)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:144)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
at com.sun.proxy.$Proxy42.getServerSettings(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:249)
at com.sun.proxy.$Proxy42.getServerSettings(Unknown Source)
at com.mirth.connect.client.core.Client.getServerSettings(Client.java:598)
at com.mirth.connect.client.ui.SettingsPanelServer$1.doInBackground(SettingsPanelServer.java:83)
at com.mirth.connect.client.ui.SettingsPanelServer$1.doInBackground(SettingsPanelServer.java:76)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)`

Imported Comment. Original Details:
Author: minht
Created: 2016-07-12T14:58:21.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_91-b14
**Version(s)/Build(s) for observation:** mirthconnect-3.4.1.8057.b139-windows-x64
**Version(s)/Build(s) to verify new behavior:** mirthconnect-3.5.0.8082.b2008-windows-x64
**How Tested:**
* Launch a new Mirth Connect instance 
* Login & register the first user as "admin" (default userid = 1)
* Install User Authorization plugin/extension and restart MC services
* Add new role = Administrator and assign this role to user "admin"
* Backup current Config ( admin_config.xml)
* Create new user = "tester"  and assign "administrator" role to this user (userid = 2)
* Logout of Mirth Connect and log back in as "tester" user
* Remove "admin" user
* Backup new Config (tester_config.xml)
* Restore Config from the initial backup (admin_config.xml)
* Verify restore operation

**Verified Improvement:** 
* Previously Restore Config will overwrite the existing User Auth properties and prevent existing user from viewing or logging in Admin Console after restore completes.
With the new Improvement, Restore Config will restore everything else but not User Auth properties if there is no current user to match the (to-be-restored) Administrator roles
`com.mirth.connect.client.core.ControllerException: At least one user must have the Administrator role. `
* UserAuth is now associated with Username instead of userID.

Imported Comment. Original Details:
Author: minht
Created: 2016-07-12T16:42:20.000-0700

**Comment by rbeckman-nextgen** [comment]
When a user name is modified, user auth does not reflect the change and causes this user to lose his privileges. We need a way to coordinate any changes to existing user with his User Auth properties.  

Imported Comment. Original Details:
Author: minht
Created: 2016-07-13T10:24:10.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 8192: Fixed issue where changing usernames wouldn't preserve User Auth roles. The authorization controller now has a method to handle changing usernames, and the user controller calls out to this conditionally when updating users.

Imported Comment. Original Details:
Author: narupley
Created: 2017-02-20T11:01:16.000-0800
