### ISSUE TITLE
DICOM attachment viewer causes Administrator to hang when viewing invalid data

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3877]
If you have attachment data that is not a valid DICOM file but has the MIME type "DICOM" anyway, the attachment viewer will hang forever in the Administrator. What's actually happening in the background is that DicomDecoder is entering an infinite loop when there aren't at least 128 bytes in the Base64 input stream.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-3999
Reporter: narupley
Created: 2016-07-13T10:00:27.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 8086: Fixed issue where the DICOM attachment viewer would cause the Administrator to hang for invalid DICOM data. We now use a BufferedInputStream and attempt to read at least 128 bytes beforehand to ensure that the Base64 input stream is valid before allowing it to go to the ij plugin.


Imported Comment. Original Details:
Author: narupley
Created: 2016-07-13T12:30:31.000-0700

**Comment by rbeckman-nextgen** [comment]
**Test environment (OS(s) and JRE version):** virtual Window 7 with JRE version 1.8.0_91-b14
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.1.8057.b139-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.5.0.8088.b2012-windows-x64
**What being tested:**
* Create new channel with Source = File Reader & Destination = Channel Writer
** Source connector > File Reader setting: File Name pattern = *.pdf & File Type = Text , Encoding = Window-1256
** Channel Summary > Properties > Set Data Types => Inbound & Outbound = DICOM 
** Channel Summary > Properties > Attachment = JavaScript 
`return addAttachment(FileUtil.encode(new java.lang.String(message).getBytes('windows-1256')), 'application/dicom').getAttachmentId();`
* Save & Deploy channel
* Provide pdf files for this channel to read from
* From Dashboard > View Messages > select a message > Attachments > View Attachment

**Additional Info:**
* If using DICOM attachment handler, channel will reject input msg with invalid dicom data (see error in separate comment), thus no message being processed for this channel setup. 
* Therefore, JavaScript attachment handler was used to recreate this ticket
* User can now attach binary data via JavaScript & Regex attachment handlers (File Type = Binary). The above channel setup was meant for pre-3.5.0
 
**Verify FIXED:**
Now, when select DICOM viewer for invalid dicom data, an Error window will pop up, indicating "Attachment is not a valid DICOM file", instead of hanging/loading viewer as before

BEFORE - View attachment at MC 3.4.1
!Viewer341.png!

NOW - View attachment at MC 3.5.0
!Viewer350.png!

Imported Comment. Original Details:
Author: minht
Created: 2016-07-21T10:24:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Error processing invalid Dicom data if using DICOM attachment handler 
`[2016-07-21 10:20:45,211]  ERROR (com.mirth.connect.donkey.server.channel.Channel:1405): Error processing attachments for channel mirth3999-DICOM attachment (c2f521ed-b9ba-4af9-aa1b-728b05c6e382).
com.mirth.connect.donkey.model.message.attachment.AttachmentException: org.dcm4che2.io.DicomCodingException: Not a DICOM Stream
	at com.mirth.connect.server.attachments.dicom.DICOMAttachmentHandler.initialize(DICOMAttachmentHandler.java:54)
	at com.mirth.connect.donkey.server.channel.Channel.createAndStoreSourceMessage(Channel.java:1386)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1181)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:170)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:354)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:247)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:203)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)Caused by: org.dcm4che2.io.DicomCodingException: Not a DICOM Stream
	at org.dcm4che2.io.DicomInputStream.guessTransferSyntax(DicomInputStream.java:288)
	at org.dcm4che2.io.DicomInputStream.<init>(DicomInputStream.java:150)
	at com.mirth.connect.model.converters.DICOMConverter.byteArrayToDicomObject(DICOMConverter.java:42)
	at com.mirth.connect.server.attachments.dicom.DICOMAttachmentHandler.initialize(DICOMAttachmentHandler.java:50)
	... 10 more `

Imported Comment. Original Details:
Author: minht
Created: 2016-07-21T10:25:11.000-0700
