### ISSUE TITLE
Frozen GUI & Mirth-Service after full storage device

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3901]
Hi together,

we were experiencing one issue when the storage device on Microsoft SQL Server went full, so no storage space was left. After making some space free by deleting unneccessary backup files, the mirth service wasnt able to come back online. Even restarting the mirth service wasn't helpful.

The GUI showed us the following exception:

java.net.ConnectException: Connection refused: connect
                at java.net.DualStackPlainSocketImpl.connect0(Native Method)
                at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
                at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
                at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
                at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
                at java.net.PlainSocketImpl.connect(Unknown Source)
                at java.net.SocksSocketImpl.connect(Unknown Source)
                at java.net.Socket.connect(Unknown Source)
                at java.net.Socket.connect(Unknown Source)
                at sun.net.NetworkClient.doConnect(Unknown Source)
                at sun.net.www.http.HttpClient.openServer(Unknown Source)
                at sun.net.www.http.HttpClient.openServer(Unknown Source)
                at sun.net.www.http.HttpClient.<init>(Unknown Source)
                at sun.net.www.http.HttpClient.New(Unknown Source)
                at sun.net.www.http.HttpClient.New(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
                at java.security.AccessController.doPrivileged(Native Method)
                at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
                at com.sun.deploy.net.HttpUtils.followRedirects(Unknown Source)
                at com.sun.deploy.net.BasicHttpRequest.doRequest(Unknown Source)
                at com.sun.deploy.net.BasicHttpRequest.doRequest(Unknown Source)
                at com.sun.deploy.net.BasicHttpRequest.doGetRequest(Unknown Source)
                at com.sun.javaws.jnl.LaunchDescFactory._buildDescriptor(Unknown Source)
                at com.sun.javaws.jnl.LaunchDescFactory.buildDescriptor(Unknown Source)
                at com.sun.javaws.jnl.LaunchDescFactory.buildDescriptor(Unknown Source)
                at com.sun.javaws.Main.launchApp(Unknown Source)
                at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
                at com.sun.javaws.Main.access$000(Unknown Source)
                at com.sun.javaws.Main$1.run(Unknown Source)
                at java.lang.Thread.run(Unknown Source)

Any Ideas how to fix it? Any further information needed?

Thanks a lot.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4023
Reporter: ikkerus
Created: 2016-08-11T00:32:39.000-0700

**Comment by rbeckman-nextgen** [comment]
Issue still not assigned?

Imported Comment. Original Details:
Author: ikkerus
Created: 2017-02-07T02:15:33.000-0800
