### ISSUE TITLE
API calls fail when query parameters contain ${} characters

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3906]
[http://www.mirthcorp.com/community/forums/showthread.php?t=216400]

Workaround in the meantime: Percent-encode the $, \{, \}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4028
Reporter: narupley
Created: 2016-08-18T15:11:15.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 8100/8101.

Imported Comment. Original Details:
Author: narupley
Created: 2016-08-22T09:58:27.000-0700

**Comment by rbeckman-nextgen** [comment]
**What is the issue:** Failed to connect to database when using configuration map variable
**Steps:**  
* When I put a configuration map variable into the database reader username field, ex: $\{defaultUsername\} 
* Then try to test the connection using the Generate Select button, 
* I receive the following error:
`Could not retrieve database metadata.  Please ensure that your driver, URL, username, and password are correct.
java.lang.IllegalStateException: The template variable 'defaultUsername' has no value
com.mirth.connect.client.core.ClientException: java.lang.IllegalStateException: The template variable 'defaultUsername' has no value
at com.mirth.connect.client.core.Client$2.invoke(Client.java:267)
at com.sun.proxy.$Proxy65.getTables(Unknown Source)
at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.ui.panels.connectors.ConnectorSettingsPanel$1$1.doInBackground(ConnectorSettingsPanel.java:195)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: The template variable 'defaultUsername' has no value
at org.glassfish.jersey.client.JerseyWebTarget.getUri(JerseyWebTarget.java:134)
at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:214)
at org.glassfish.jersey.client.JerseyWebTarget.request(JerseyWebTarget.java:59)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:348)
at com.sun.proxy.$Proxy65.getTables(Unknown Source)
at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:249)
... 11 more
Caused by: java.lang.IllegalArgumentException: The template variable 'defaultUsername' has no value
at org.glassfish.jersey.uri.UriTemplate$1ValuesFromArrayStrategy.valueFor(UriTemplate.java:1020)
at org.glassfish.jersey.uri.UriTemplate.resolveTemplate(UriTemplate.java:706)
at org.glassfish.jersey.uri.UriTemplate.createUriComponent(UriTemplate.java:1030)
at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:970)
at org.glassfish.jersey.uri.UriTemplate.createURIWithStringValues(UriTemplate.java:906)
at org.glassfish.jersey.uri.UriTemplate.createURI(UriTemplate.java:871)
at org.glassfish.jersey.uri.internal.JerseyUriBuilder._build(JerseyUriBuilder.java:914)
at org.glassfish.jersey.uri.internal.JerseyUriBuilder.build(JerseyUriBuilder.java:831)
at org.glassfish.jersey.client.JerseyWebTarget.getUri(JerseyWebTarget.java:132)
... 19 more`

Imported Comment. Original Details:
Author: minht
Created: 2016-08-22T14:16:40.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_91-b14
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.1.8057.b139-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.5.0.8100.b2019-windows-x64
**How Tested:**
* Create a database name "testdb" with some tables in Postgres for this test
* Launch MC Administrator 
* Settings > Configuration Map > create 2 Mapping variables, psql = localhost and user = postgres
* Create test channel with Source & Destination = DB reader/writer
Driver = Postgres
URL = jdbc:postgresql://$\{psql\}:5432/testdb
Username = $\{user\}
* For each connector, click on \[Select\] above the SQL text box > then select Get Tables
* Verify able to view tables 

**Verified Fixed:**
Able to connect to database and view tables with the new build
!MC350.8100.png!

Imported Comment. Original Details:
Author: minht
Created: 2016-08-22T15:46:07.000-0700

**Comment by rbeckman-nextgen** [comment]
Successfully tested db connection with config map variables in DB connector using mirthconnect-3.5.0.8100.b2019-windows-x64

Imported Comment. Original Details:
Author: minht
Created: 2016-08-22T16:08:09.000-0700
