### ISSUE TITLE
Sorting in the channels view causes issues when using older versions of MC

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3911]
If you open a 3.4 Administrator and sort by anything in the channels view, then open the Administrator in version 3.2.1 or older and go to the channels view, you'll get a client-side exception and nothing will show up:

`Exception in thread "AWT-EventQueue-2" java.lang.ClassCastException: javax.swing.SortOrder cannot be cast to java.util.List
at com.mirth.connect.client.ui.components.MirthTable. setModel(MirthTable.java:104)
at com.mirth.connect.client.ui.ChannelPanel.updateCha nnelTable(ChannelPanel.java:499)
at com.mirth.connect.client.ui.ChannelPanel.makeChann elTable(ChannelPanel.java:186)
at com.mirth.connect.client.ui.ChannelPanel.<init>(Ch annelPanel.java:123)
at com.mirth.connect.client.ui.Frame.doShowChannel(Fr ame.java:1814)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Nativ e Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknow n Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Un known Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at sun.reflect.misc.Trampoline.invoke(Unknown Source)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknow n Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Un known Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
at java.beans.EventHandler.invokeInternal(Unknown Source)
at java.beans.EventHandler.access$000(Unknown Source)
at java.beans.EventHandler$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.beans.EventHandler.invoke(Unknown Source)
at com.sun.proxy.$Proxy9.actionPerformed(Unknown Source)
at org.jdesktop.swingx.action.BoundAction.actionPerfo rmed(BoundAction.java:231)
at javax.swing.AbstractButton.fireActionPerformed(Unk nown Source)
at org.jdesktop.swingx.JXHyperlink.fireActionPerforme d(JXHyperlink.java:264)
at javax.swing.AbstractButton$Handler.actionPerformed (Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed (Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseRe leased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent( Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(U nknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unkno wn Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessI mpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessI mpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessI mpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilter s(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(U nknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarch y(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source) `

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4033
Reporter: narupley
Created: 2016-08-25T08:42:22.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 8109/8110. The preference keys now have "tree" in them so that they won't conflict with earlier keys.

Imported Comment. Original Details:
Author: narupley
Created: 2016-08-25T10:25:47.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** 
MC client or host machine = local OSX Yosemite 10.10 with Java 8 Update 51 
MC server = virtual Window 7 with JRE version 1.8.0_91-b14
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.1.8057.b139-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.5.0.8119.b2030-windows-x64

**How Tested:**
On MC server, run 3 different MC instances:
* mirthconnect-3.2.1.7650.b40-windows-x64 (port 8080)  
* mirthconnect-3.4.1.8057.b139-windows-x64 (port 8084)
* mirthconnect-3.5.0.8119.b2030-windows-x64 (port 8081)

On MC client or host machine:
* Enable Java console log (Java Control Panel > Advanced > Java console = "show console")
* Launch MC Administrator for MC341 (http://10.10.15.29:8084/webadmin/Index.action)
* From Channels view, change the Column arrangements, such as, Status | Data Type | Name | Local Id | Rev ...
* Now launch MC Administrator for MC 321  (http://10.10.15.29:8080/webadmin/Index.action)
* Go to Channels 
=> not able to view Channels, getting Exception in Java console log "java.lang.ClassCastException: javax.swing.SortOrder cannot be cast to java.util.List" 
* Close MC Administrator for MC 321
* Back to MC 341 console, reset Channel View:
=> From Channels, select the Column arrangement icon on the top right corner of the window (refer to screenshots) > select "Restore Default"
* Now Launch Administrative Console for MC 321
* Verify Channels are displayed properly and there is no exception in Java console log
* Launch MC Administrator for MC350 (http://10.10.15.29:8081/webadmin/Index.action)
* From Channels view, change the Column arrangements, such as, Status | Data Type | Name | Local Id | Rev ...
* Then launch MC Administrator for MC 321  (http://10.10.15.29:8080/webadmin/Index.action)
* Verify Channels listing, expecting no issue

**Verified Fixed:**
Step 13, able to view channel listing of older MC version (MC 321 or older) and there was no java exception

Successfully verified channel listing between different MC versions with NON-default Column Arrangement

Imported Comment. Original Details:
Author: minht
Created: 2016-09-02T10:02:47.000-0700

**Comment by rbeckman-nextgen** [comment]
**Additional Observation:**
* Not an issue when launching MC Administrator on Windows (MC client). Issue is only observed on Mac OSx
* **Workaround** when encountering issue is to reset Channel View from MC 3.4.x (see step 7)
* Reference SUPPORT-4553 ticket for details 
* Reference attached screenshot for **Default** columns at different MC versions  

Imported Comment. Original Details:
Author: minht
Created: 2016-09-02T10:42:29.000-0700
