### ISSUE TITLE
Support View Attachment for multipaged tiff attachments

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3913]
Viewing a multipaged tiff attachment returns an error or does nothing at all. Below is the specific stack trace that gets returned when attempting to view a multipaged tiff file under the message browser.

`
Unsupported Image Type
javax.imageio.IIOException: Unsupported Image Type
at com.sun.imageio.plugins.jpeg.JPEGImageReader.readInternal(JPEGImageReader.java:1063)
at com.sun.imageio.plugins.jpeg.JPEGImageReader.read(JPEGImageReader.java:1034)
at com.sun.media.imageioimpl.plugins.tiff.TIFFJPEGDecompressor.decodeRaw(TIFFJPEGDecompressor.java:104)
at com.sun.media.imageio.plugins.tiff.TIFFDecompressor.decode(TIFFDecompressor.java:2010)
at com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader.decodeTile(TIFFImageReader.java:836)
at com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:1081)
at javax.imageio.ImageIO.read(ImageIO.java:1448)
at javax.imageio.ImageIO.read(ImageIO.java:1352)
at com.mirth.connect.plugins.imageviewer.ImageViewer.viewAttachments(ImageViewer.java:61)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$19.doInBackground(MessageBrowser.java:1614)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$19.doInBackground(MessageBrowser.java:1611)
at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at javax.swing.SwingWorker.run(SwingWorker.java:335)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4035
Reporter: austiny
Created: 2016-08-25T15:41:28.000-0700

**Comment by rbeckman-nextgen** [comment]
When attempting to view the attachment through the message browser (OS X)
!multipaged_example.png!

Imported Comment. Original Details:
Author: austiny
Created: 2016-08-25T15:44:01.000-0700
