### ISSUE TITLE
MirthSyntaxTextArea/JEditTextArea calls to setText can mark tokens before expected

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3919]
This can be seen in the Message Template panel or the Message Browser. 

Calling setText will fire off a DocumentHandler that will try to place the caret at the correct X offset in the last line. To calculate this offset it will check for tokens since they can change this calculation. It will just try to mark the last line for tokens but the problem is that the panel has not been painted and the rest of the lines tokens/states are undetermined. At the very least I know JsonTokenMarker depends on states having been built for previous lines before calculating the current line. 

Even though any errors should be handled gracefully, this issue could lead to unexpected inputs to the token marker that could have undesired results(MIRTH-4040). This issue could also be very inconsequential and there might not actually be very many cases where it is relevant. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4041
Reporter: eduardoa
Created: 2016-08-29T18:57:13.000-0700

**Comment by rbeckman-nextgen** [comment]
Example of an exception caused by this issue. 

`
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.syntax.jedit.tokenmarker.JSONTokenMarker.markTokensImpl(JSONTokenMarker.java:58)
	at org.syntax.jedit.tokenmarker.TokenMarker.markTokens(TokenMarker.java:57)
	at org.syntax.jedit.JEditTextArea._offsetToX(JEditTextArea.java:704)
	at org.syntax.jedit.JEditTextArea.scrollTo(JEditTextArea.java:581)
	at org.syntax.jedit.JEditTextArea.scrollToCaret(JEditTextArea.java:543)
	at org.syntax.jedit.JEditTextArea.select(JEditTextArea.java:1323)
	at org.syntax.jedit.JEditTextArea$DocumentHandler.insertUpdate(JEditTextArea.java:2072)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at org.syntax.jedit.SyntaxDocument.fireInsertUpdate(SyntaxDocument.java:150)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at org.syntax.jedit.MirthPlainDocument.insertString(MirthPlainDocument.java:122)
	at org.syntax.jedit.JEditTextArea.setText(JEditTextArea.java:1024)
	at com.mirth.connect.client.ui.components.MirthSyntaxTextArea.setText(MirthSyntaxTextArea.java:167)
	at com.mirth.connect.client.ui.TemplatePanel.setMessage(TemplatePanel.java:240)
	at com.mirth.connect.client.ui.editors.MessageTemplatePanel.setOutboundMessage(MessageTemplatePanel.java:104)
	at com.mirth.connect.client.ui.editors.TabbedTemplatePanel.setOutgoingMessage(TabbedTemplatePanel.java:115)
	at com.mirth.connect.client.ui.editors.transformer.TransformerPane.load(TransformerPane.java:206)
	at com.mirth.connect.client.ui.ChannelSetup.editTransformer(ChannelSetup.java:279)
	at com.mirth.connect.client.ui.Frame.doEditTransformer(Frame.java:2965)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at java.beans.EventHandler.invokeInternal(EventHandler.java:482)
	at java.beans.EventHandler.access$000(EventHandler.java:279)
	at java.beans.EventHandler$1.run(EventHandler.java:430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.beans.EventHandler.invoke(EventHandler.java:428)
	at com.sun.proxy.$Proxy49.actionPerformed(Unknown Source)
	at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at org.jdesktop.swingx.JXHyperlink.fireActionPerformed(JXHyperlink.java:264)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

Input could have been 
`
{"test":"channel1",
"test2":"channel1"}
`

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-08-29T18:58:21.000-0700

**Comment by rbeckman-nextgen** [comment]
At least for JsonTokenMarker it might be a good solution to give LineInfo a state of whether it has been calculated for the previous line or not. If it hasn't it could work itself backwards until it has painted back to a line where LineInfo has been calculated. 

So any call to markTokens will check if lineInfo[currentLine-1] has been calculated, if not start marking tokens backwards until a line is reached where tokens have been marked already. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-08-31T10:05:34.000-0700
