### ISSUE TITLE
Possible race condition with statistics updater when deleting channels

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3923]
If statistics for a channel have been added, but the channel is deleted before the stats updater thread has a chance to commit them, the updater thread will start throwing errors:

`ERROR 2016-09-01 10:08:45,542 [Statistics Updater Thread] com.mirth.connect.donkey.server.data.DonkeyStatisticsUpdater: Unable to update statistics.
com.mirth.connect.donkey.server.data.DonkeyDaoException: Channel ID 93c88a07-b6a9-4bb5-8a9b-59cbc006d922 does not exist
    at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.getLocalChannelId(JdbcDao.java:2721)
    at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.prepareStatement(JdbcDao.java:2613)
    at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.updateStatistics(JdbcDao.java:379)
    at com.mirth.connect.donkey.server.data.jdbc.JdbcDao.addChannelStatistics(JdbcDao.java:354)
    at com.mirth.connect.donkey.server.data.DonkeyStatisticsUpdater.commit(DonkeyStatisticsUpdater.java:87)
    at com.mirth.connect.donkey.server.data.DonkeyStatisticsUpdater.run(DonkeyStatisticsUpdater.java:52)`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4045
Reporter: narupley
Created: 2016-09-01T12:10:26.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in revisions 8116/8117. Now there's a new ChannelDoesNotExistException that gets thrown when the local channel ID cannot be found. The updater thread will catch that and remove stats for those channels IDs as necessary, and then re-attempt the commit on the next iteration.

Imported Comment. Original Details:
Author: narupley
Created: 2016-09-01T12:15:58.000-0700

**Comment by rbeckman-nextgen** [comment]
Attached channel that will reproduce this after a little bit

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-09-01T17:23:43.000-0700

**Comment by rbeckman-nextgen** [comment]
rev 8119 - This exception is no longer repeatedly thrown after the issue occurs. A new debug level log is added and after the first failure the channel is removed from the statistics. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-09-01T17:26:15.000-0700
