### ISSUE TITLE
Use of HttpComponents client should be able to recover from illegal state

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3929]
Currently places where we use the httpcomponents client we handle exceptions but it is possible for the client to get caught in a bad state. If an out of memory throwable is thrown at unfortunate times it is possible for the client to never release a connection. 

The odds of this happening are low and depend on something going seriously wrong with execution(like InternalError, OutOfMemoryError, StackOverflowError). A scenario we would like to avoid is where this happens once and all subsequent attempts to use the client fail because of an IllegalStateException. 

In the Http Sender this could manifest itself as an incomplete message and then all messages after it could lead to this failure:
`
ERROR: Error connecting to HTTP server [IllegalStateException: Connection is still allocated]
`
Since the BasicHttpClientConnectionManager only deals with one connection you would repeatedly keep trying to use this connection that is in a bad state. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4051
Reporter: eduardoa
Created: 2016-09-07T15:12:57.000-0700

**Comment by rbeckman-nextgen** [comment]
Revisions 8124/8125: Fixed issue that caused HTTP Sender destinations to become unusable after a fatal IllegalStateException or other Error occurs. This realistically only happens when the server runs out of memory for some reason, and even then there's only a small chance the client will get into such a state. If it did, restarting the connector fixed it. However now the dispatcher will gracefully recover from such errors, closing the client and allowing the next dispatch attempt to recreate it.

Similar changes were made to ServerConnection to allow it to restart itself (close and recreate the client) when a fatal error occurs. The cookie store is created and set separately so that users don't have to login again when this happens.

Imported Comment. Original Details:
Author: narupley
Created: 2016-09-08T10:03:13.000-0700

**Comment by rbeckman-nextgen** [comment]
For QA, important to test out not only the HTTP Sender, but the Administrator. In particular make sure nothing unintended happens (like kicking the user out to the login dialog) when an OOM error occurs.

Imported Comment. Original Details:
Author: narupley
Created: 2016-09-08T10:05:46.000-0700

**Comment by rbeckman-nextgen** [comment]
It is possible for an out of memory exception to be thrown even after we finished reading the response from the response entity. For instance in HttpDispatcher<383> converting the response to xml can add some overhead and push memory over the edge at this point. In this case when we call DonkeyElement.toXml().

`
responseData = HttpMessageConverter.httpResponseToXml(statusLine.toString(), headers, responseBody, responseContentType, httpDispatcherProperties.isResponseParseMultipart(), httpDispatcherProperties.isResponseIncludeMetadata(), binaryContentTypeResolver);
`

Because of this I am seeing the following exception:
`
ERROR 2016-09-08 18:27:13,994 [Destination Chain Thread 1 on HttpSender 19100 (03166ef9-ed62-4a30-a731-55a72687ff66) < Channel Dispatch Thread < JavaScript Reader Polling Thread on HttpSender 19100 (03166ef9-ed62-4a30-a731-55a72687ff66) < 03166ef9-ed62-4a30-a731-55a72687ff66_Worker-1] com.mirth.connect.donkey.server.channel.DestinationChain: Error processing destination Destination 1 for channel 03166ef9-ed62-4a30-a731-55a72687ff66.
java.lang.IllegalStateException: Connection not obtained from this manager
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.releaseConnection(BasicHttpClientConnectionManager.java:286)
	at org.apache.http.impl.execchain.ConnectionHolder.releaseConnection(ConnectionHolder.java:98)
	at org.apache.http.impl.execchain.ConnectionHolder.releaseConnection(ConnectionHolder.java:119)
	at org.apache.http.impl.execchain.ResponseEntityProxy.releaseConnection(ResponseEntityProxy.java:78)
	at org.apache.http.impl.execchain.ResponseEntityProxy.streamClosed(ResponseEntityProxy.java:141)
	at org.apache.http.conn.EofSensorInputStream.checkClose(EofSensorInputStream.java:228)
	at org.apache.http.conn.EofSensorInputStream.close(EofSensorInputStream.java:174)
	at java.util.zip.InflaterInputStream.close(InflaterInputStream.java:227)
	at java.util.zip.GZIPInputStream.close(GZIPInputStream.java:136)
	at org.apache.http.client.entity.LazyDecompressingInputStream.close(LazyDecompressingInputStream.java:97)
	at org.apache.http.util.EntityUtils.consume(EntityUtils.java:88)
	at org.apache.http.client.utils.HttpClientUtils.closeQuietly(HttpClientUtils.java:108)
	at com.mirth.connect.connectors.http.HttpDispatcher.send(HttpDispatcher.java:421)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:847)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:489)
`

Like we discussed, the problem is calling close on the client before the response, when the response was valid. So we call
`
HttpClientUtils.closeQuietly(client);
`
then after call
`
HttpClientUtils.closeQuietly(httpResponse);
`

The first one calls on BasicHttpClientConnectionManager.shutdownConnection which sets this.conn to null. Then calling close on the response does a check to release the connection but the connection on the manager has been set to null.
`
 Asserts.check(conn == this.conn, "Connection not obtained from this manager");
`
The error is kind of misleading since it makes it sound like there could be some weird issue but the real issue was the out of memory error.

The patch you sent me takes care of this issue and the oom error is added correctly to the message. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-09-08T18:43:19.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed the above issue. Now the response is closed before the client gets closed, and if the response is closed in the finally block it will always do so without throwing any exception.

Imported Comment. Original Details:
Author: narupley
Created: 2016-09-09T08:28:52.000-0700

**Comment by rbeckman-nextgen** [comment]
rev 8127 - confirmed that the above is resolved. 
I did my best testing out memory issues on the administrator(from a smithers build) but it can be kind of unpredictable. The out of memory issues I was seeing on the client were handled gracefully though. 

Imported Comment. Original Details:
Author: eduardoa
Created: 2016-09-09T16:00:15.000-0700
