### ISSUE TITLE
Configuration table should have unique/pk constraint on category and name

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3932]
There might be a reason why this wasn't done before but the way we access/create these properties is a non locking create/update which could lead to dups. Adding a table constraint would be good but I think the queries could have some safety added as well. 

I suspect this explainsthe following forum post:
http://www.mirthcorp.com/community/forums/showthread.php?t=216501

I'm not sure if we'll know exactly why the first dup was created but the getProperty method returns null every time after the dup is created. This will lead to infinite properties to be created. 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4054
Reporter: eduardoa
Created: 2016-09-19T12:24:20.000-0700

**Comment by rbeckman-nextgen** [comment]
stack trace from forum post 
`
[2016-09-19 09:03:37,993] WARN (com.mirth.connect.server.controllers.DefaultConfi gurationController:839): Could not retrieve property: category=core, name=channelDependencies
org.apache.ibatis.exceptions.TooManyResultsExcepti on: Expected one result (or null) to be returned by selectOne(), but found: 132229
at org.apache.ibatis.session.defaults.DefaultSqlSessi on.selectOne(DefaultSqlSession.java:63)
at sun.reflect.GeneratedMethodAccessor15.invoke(Unkno wn Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Un known Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.ibatis.session.SqlSessionManager$SqlSes sionInterceptor.invoke(SqlSessionManager.java:282)
at com.sun.proxy.$Proxy6.selectOne(Unknown Source)
at org.apache.ibatis.session.SqlSessionManager.select One(SqlSessionManager.java:151)
at com.mirth.connect.server.controllers.DefaultConfig urationController.getProperty(DefaultConfiguration Controller.java:837)
at com.mirth.connect.server.controllers.DefaultConfig urationController.saveProperty(DefaultConfiguratio nController.java:855)
at com.mirth.connect.server.controllers.DefaultConfig urationController.setChannelDependencies(DefaultCo nfigurationController.java:934)
at com.mirth.connect.server.controllers.DefaultConfig urationController.getChannelDependencies(DefaultCo nfigurationController.java:919)
at com.mirth.connect.server.api.servlets.Configuratio nServlet.getChannelDependencies(ConfigurationServl et.java:332)
at sun.reflect.GeneratedMethodAccessor62.invoke(Unkno wn Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Un known Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.server.api.providers.MirthResour ceInvocationHandlerProvider$1.invoke(MirthResource InvocationHandlerProvider.java:211)
at org.glassfish.jersey.server.model.internal.Abstrac tJavaResourceMethodDispatcher$1.run(AbstractJavaRe sourceMethodDispatcher.java:144)
at org.glassfish.jersey.server.model.internal.Abstrac tJavaResourceMethodDispatcher.invoke(AbstractJavaR esourceMethodDispatcher.java:161)
at org.glassfish.jersey.server.model.internal.JavaRes ourceMethodDispatcherProvider$TypeOutInvoker.doDis patch(JavaResourceMethodDispatcherProvider.java:20 5)
at org.glassfish.jersey.server.model.internal.Abstrac tJavaResourceMethodDispatcher.dispatch(AbstractJav aResourceMethodDispatcher.java:99)
at org.glassfish.jersey.server.model.ResourceMethodIn voker.invoke(ResourceMethodInvoker.java:389)
at org.glassfish.jersey.server.model.ResourceMethodIn voker.apply(ResourceMethodInvoker.java:347)
at org.glassfish.jersey.server.model.ResourceMethodIn voker.apply(ResourceMethodInvoker.java:102)
at org.glassfish.jersey.server.ServerRuntime$2.run(Se rverRuntime.java:326)
at org.glassfish.jersey.internal.Errors$1.call(Errors .java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors .java:267)
at org.glassfish.jersey.internal.Errors.process(Error s.java:315)
at org.glassfish.jersey.internal.Errors.process(Error s.java:297)
at org.glassfish.jersey.internal.Errors.process(Error s.java:267)
at org.glassfish.jersey.process.internal.RequestScope .runInScope(RequestScope.java:317)
at org.glassfish.jersey.server.ServerRuntime.process( ServerRuntime.java:305)
at org.glassfish.jersey.server.ApplicationHandler.han dle(ApplicationHandler.java:1154)
at org.glassfish.jersey.servlet.WebComponent.serviceI mpl(WebComponent.java:471)
at org.glassfish.jersey.servlet.WebComponent.service( WebComponent.java:425)
at org.glassfish.jersey.servlet.ServletContainer.serv ice(ServletContainer.java:383)
at org.glassfish.jersey.servlet.ServletContainer.serv ice(ServletContainer.java:336)
at org.glassfish.jersey.servlet.ServletContainer.serv ice(ServletContainer.java:223)
at org.eclipse.jetty.servlet.ServletHolder.handle(Ser vletHolder.java:812)
at org.eclipse.jetty.servlet.ServletHandler$CachedCha in.doFilter(ServletHandler.java:1669)
at com.mirth.connect.server.MethodFilter.doFilter(Met hodFilter.java:37)
at org.eclipse.jetty.servlet.ServletHandler$CachedCha in.doFilter(ServletHandler.java:1652)
at com.mirth.connect.server.api.providers.ApiOriginFi lter.doFilter(ApiOriginFilter.java:35)
at org.eclipse.jetty.servlet.ServletHandler$CachedCha in.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle( ServletHandler.java:585)
at org.eclipse.jetty.server.session.SessionHandler.do Handle(SessionHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.do Handle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(S ervletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.do Scope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.do Scope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.han dle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerList.handl e(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.ha ndle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java :499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpCh annel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable (HttpConnection.java:257)
at org.eclipse.jetty.io.AbstractConnection$2.run(Abst ractConnection.java:544)
at org.eclipse.jetty.util.thread.QueuedThreadPool.run Job(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.r un(QueuedThreadPool.java:555)
at java.lang.Thread.run(Unknown Source)
`


Imported Comment. Original Details:
Author: eduardoa
Created: 2016-09-19T12:24:53.000-0700

**Comment by rbeckman-nextgen** [comment]
Revision 8226: Added primary key constraint to the configuration table.

Imported Comment. Original Details:
Author: narupley
Created: 2017-03-29T13:06:52.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_111-b14
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.4.2.8129.b167-windows-x64
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.5.0.8227.b2148-windows-x64
**Test Steps:**
* Test migration of database with existing duplicate rows in configuration table => expect migration to fail with error.
* Test migration with Derby, Postgres, mySQL & Oracle => expect no issue
* Manually add duplicate entry in Configuration Map table => expect to fail
* General regression test of Settings > Server & Date Pruner

Imported Comment. Original Details:
Author: minht
Created: 2017-03-31T15:17:46.000-0700

**Comment by rbeckman-nextgen** [comment]
ROCKSOLID-331

Imported Comment. Original Details:
Author: minht
Created: 2017-03-31T15:17:58.000-0700
