### ISSUE TITLE
Unable to Webstart on MS Vista w/Service

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#394]
The wrapper.log error is below:

STATUS | wrapper  | 2007/06/01 23:23:54 | Launching a JVM...
INFO   | jvm 1    | 2007/06/01 23:23:55 | Wrapper (Version 3.2.1) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2007/06/01 23:23:55 | 
STATUS | wrapper  | 2007/06/01 23:23:59 | Mirth started.
INFO   | jvm 1    | 2007/06/01 23:24:18 | WARN  2007-06-01 23:24:18,964 [Thread-0] org.mortbay.jetty.servlet.WebApplicationContext: Configuration error on jar:file:/C:/Program%20Files/Mirth/web/webapps/mirth.war!/
INFO   ]( jvm 1    | 2007/06/01 23:24:18 | java.io.IOException: The system cannot find the path specified
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at java.io.File.checkAndCreate(Unknown Source)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at java.io.File.createTempFile(Unknown Source)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at org.mortbay.http.ContextLoader.<init>(ContextLoader.java:111)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at org.mortbay.http.HttpContext.initClassLoader(HttpContext.java:1199)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at org.mortbay.jetty.servlet.WebApplicationContext.doStart(WebApplicationContext.java:456)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at org.mortbay.util.Container.start(Container.java:72)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at org.mortbay.http.HttpServer.doStart(HttpServer.java:708)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at org.mortbay.util.Container.start(Container.java:72)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at com.webreach.mirth.server.Mirth.startWebServer(Mirth.java:262)
INFO   | jvm 1    | 2007/06/01 23:24:18 | 	at com.webreach.mirth.server.Mirth.run(Mirth.java:89)
INFO   | jvm 1    | 2007/06/01 23:24:20 | WARN  2007-06-01 23:24:20,433 [Thread-0) com.webreach.mirth.server.Mirth: Could not start web server.
INFO   | jvm 1    | 2007/06/01 23:24:20 | org.mortbay.util.MultiException[java.io.IOException: The system cannot find the path specified]
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.http.HttpServer.doStart(HttpServer.java:686)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.util.Container.start(Container.java:72)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at com.webreach.mirth.server.Mirth.startWebServer(Mirth.java:262)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at com.webreach.mirth.server.Mirth.run(Mirth.java:89)
INFO   | jvm 1    | 2007/06/01 23:24:20 | java.io.IOException: The system cannot find the path specified
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at java.io.File.checkAndCreate(Unknown Source)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at java.io.File.createTempFile(Unknown Source)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.http.ContextLoader.<init>(ContextLoader.java:111)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.http.HttpContext.initClassLoader(HttpContext.java:1199)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.jetty.servlet.WebApplicationContext.doStart(WebApplicationContext.java:456)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.util.Container.start(Container.java:72)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.http.HttpServer.doStart(HttpServer.java:708)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at org.mortbay.util.Container.start(Container.java:72)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at com.webreach.mirth.server.Mirth.startWebServer(Mirth.java:262)
INFO   | jvm 1    | 2007/06/01 23:24:20 | 	at com.webreach.mirth.server.Mirth.run(Mirth.java:89)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-384
Reporter: chrisl
Created: 2007-06-01T23:36:16.000-0700

**Comment by rbeckman-nextgen** [comment]
Same as service issue

Imported Comment. Original Details:
Author: admin
Created: 2007-07-26T15:28:12.000-0700

**Comment by rbeckman-nextgen** [comment]
This bug was tested and I could not reproduce it in 1.6.0 using Windows Vista Ultimate and the 1.6 JRE.  It may have been fixed as a result of some other changes.

Imported Comment. Original Details:
Author: jacobb
Created: 2007-08-21T17:00:31.000-0700
