### ISSUE TITLE
Failed to connect with SMB in File Writer with lose connection

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3965]
Hello,

In a Destination Channel, File Writer Connector Type with method SMB connection with user and password.

Basic it works, but the problem is that if the remote SMB address does not respond one time, we are forced to restart the Mirth Service completely.

Not possible to communicate with this SMB address (Test button not work) via Mirth, but via Windows Explorer it's work.

We restart Mirth Service and it's work again,,,

This error message:

==========================================================
System Time: 1480681298370
Date: Dec 2, 2016 1:21:38 PM
Global Map Var: ${globalMapVariable}
Error: Destination Connector (File Writer) error ERROR MESSAGE: Error writing file
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/172.25.1.15
jcifs.util.transport.TransportException: Connection timeout
	at jcifs.util.transport.Transport.connect(Transport.java:174)
	at jcifs.smb.SmbTransport.connect(SmbTransport.java:307)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)
	at jcifs.smb.SmbFile.connect(SmbFile.java:954)
	at jcifs.smb.SmbFile.connect0(SmbFile.java:880)
	at jcifs.smb.SmbFile.exists(SmbFile.java:1415)
	at com.mirth.connect.connectors.file.filesystems.SmbFileConnection.writeFile(SmbFileConnection.java:277)
	at com.mirth.connect.connectors.file.FileDispatcher.send(FileDispatcher.java:170)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:822)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:476)
	at com.mirth.connect.donkey.server.channel.DestinationChain.doCall(DestinationChain.java:121)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:63)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1715)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1198)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:170)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:354)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:247)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:203)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

	at jcifs.smb.SmbTransport.connect(SmbTransport.java:309)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)
	at jcifs.smb.SmbFile.connect(SmbFile.java:954)
	at jcifs.smb.SmbFile.connect0(SmbFile.java:880)
	at jcifs.smb.SmbFile.exists(SmbFile.java:1415)
	at com.mirth.connect.connectors.file.filesystems.SmbFileConnection.writeFile(SmbFileConnection.java:277)
	at com.mirth.connect.connectors.file.FileDispatcher.send(FileDispatcher.java:170)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:822)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:476)
	at com.mirth.connect.donkey.server.channel.DestinationChain.doCall(DestinationChain.java:121)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:63)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1715)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1198)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:170)
	at com.mirth.connect.connectors.file.FileReceiver.processFile(FileReceiver.java:354)
	at com.mirth.connect.connectors.file.FileReceiver.processFiles(FileReceiver.java:247)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:203)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

Error Message: Failed to connect: 0.0.0.0<00>/172.25.1.15 Error Type: Destination Connector Channel ID: 6cd83eab-d200-447f-98ab-648570755ed2
Channel Name: Test -  HL
Connector Name: Copy HL7 File
Connector Type: File Writer
==========================================================

Thanks

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4087
Reporter: nesswaw
Created: 2016-12-02T06:30:37.000-0800

**Comment by rbeckman-nextgen** [comment]
Same issue here ... e.g. when the remote file server has been rebooted ...

Wireshark log:

4	2017-06-22 10:32:05.083105	10.188.218.133	10.150.4.31	NBSS	126	Session request, to *SMBSERVER<20> from JCIFS218_133_3D<00>
5	2017-06-22 10:32:05.083999	10.150.4.31	10.188.218.133	NBSS	60	Negative session response, Called name not present

Can indeed only be solved by rebooting the Mirth Connect service ...

Imported Comment. Original Details:
Author: nico
Created: 2017-06-22T02:20:24.000-0700

**Comment by rbeckman-nextgen** [comment]
We had some similar isues,
it seems as if it is related to some resolving problems with nmb

Try to replace the IP with a machine name (by entering it in /etc/hosts) that solved the problem for us


Imported Comment. Original Details:
Author: piet
Created: 2017-08-21T01:45:05.000-0700
