### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3967]
I have two mirth installs that are version 2.2.3.6825 that are experiencing an error.  I have pasted the stack trace below.  Can someone help us understand what is breaking and how to fix.

ERROR-410: Web Service Connector error
ERROR MESSAGE:	Error connecting to web service.
javax.xml.ws.WebServiceException: java.lang.IllegalArgumentException: faultCode argument for createFault was passed NULL
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.doInvoke(Unknown Source)
	at com.sun.xml.internal.ws.client.dispatch.DispatchImpl.invoke(Unknown Source)
	at com.mirth.connect.connectors.ws.WebServiceMessageDispatcher.processMessage(WebServiceMessageDispatcher.java:177)
	at com.mirth.connect.connectors.ws.WebServiceMessageDispatcher.doDispatch(WebServiceMessageDispatcher.java:106)
	at com.mirth.connect.connectors.ws.WebServiceMessageDispatcher.doSend(WebServiceMessageDispatcher.java:205)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:164)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:54)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:176)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:143)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:487)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:266)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:238)
	at com.mirth.connect.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:484)
	at com.mirth.connect.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:444)
	at com.mirth.connect.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:361)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1061)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:575)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: faultCode argument for createFault was passed NULL
	at com.sun.xml.internal.messaging.saaj.soap.ver1_1.SOAPFactory1_1Impl.createFault(Unknown Source)
	at com.sun.xml.internal.ws.fault.SOAP11Fault.getProtocolException(Unknown Source)
	at com.sun.xml.internal.ws.fault.SOAPFaultBuilder.createException(Unknown Source)
	... 29 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4089
Reporter: sumeetahluwalia
Created: 2016-12-07T11:53:19.000-0800

**Comment by rbeckman-nextgen** [comment]
Please only create issues if they are demonstrable bugs with clear steps to reproduce. Ideas for new features / improvements are fine too. But the issue tracker here isn't for general support problems. Try the forums first: [http://www.mirthcorp.com/community/forums/forumdisplay.php?f=6]

Imported Comment. Original Details:
Author: narupley
Created: 2016-12-07T12:09:31.000-0800
