### ISSUE TITLE
Getting Exception when View Messages of newly Cloned channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3980]
**What is the issue:** Cannot View Messages for a newly cloned channel
**OS(s) /JREs Used:** virtual Window 7 with JRE version 1.8.0_111-b14
**Issue found /exists in Version(s)/Build(s):** MC 342.8129
**Is the Issue Consistent (list details):** Only affecting Cloned channel, not an issue with new channel.
**Expected Behavior:** On a newly created channel, you can click on View Messages and expect to see an empty list

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4102
Reporter: minht
Created: 2017-01-06T14:00:03.000-0800

**Comment by rbeckman-nextgen** [comment]
`com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.mapper.CannotResolveClassException: com.mirth.connect.donkey.server.data.ChannelDoesNotExistException
com.mirth.connect.client.core.ClientException: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.mapper.CannotResolveClassException: com.mirth.connect.donkey.server.data.ChannelDoesNotExistException
at com.mirth.connect.client.core.ServerConnection.executeAsync(ServerConnection.java:295)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:145)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
at com.sun.proxy.$Proxy63.getMaxMessageId(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:249)
at com.sun.proxy.$Proxy63.getMaxMessageId(Unknown Source)
at com.mirth.connect.client.core.Client.getMaxMessageId(Client.java:1601)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser.generateMessageFilter(MessageBrowser.java:550)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser.runSearch(MessageBrowser.java:562)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser.loadChannel(MessageBrowser.java:362)
at com.mirth.connect.client.ui.Frame$23.done(Frame.java:2934)
at javax.swing.SwingWorker$5.run(Unknown Source)
at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
at sun.swing.AccumulativeRunnable.run(Unknown Source)
at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
at javax.swing.Timer.fireActionPerformed(Unknown Source)
at javax.swing.Timer$DoPostEvent.run(Unknown Source)
at java.awt.event.InvocationEvent.dispatch(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.mapper.CannotResolveClassException: com.mirth.connect.donkey.server.data.ChannelDoesNotExistException
at com.mirth.connect.model.converters.ObjectXMLSerializer.handleDeserializationException(ObjectXMLSerializer.java:318)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:211)
at com.mirth.connect.client.core.api.providers.XmlMessageBodyReader.readFrom(XmlMessageBodyReader.java:51)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
at com.mirth.connect.client.core.MirthClientResponse.readEntity(MirthClientResponse.java:40)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:449)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:413)
at com.mirth.connect.client.core.ServerConnection.executeAsync(ServerConnection.java:274)
... 42 more
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: com.mirth.connect.donkey.server.data.ChannelDoesNotExistException
at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:206)
... 54 more`

Imported Comment. Original Details:
Author: minht
Created: 2017-01-06T14:01:19.000-0800

**Comment by rbeckman-nextgen** [comment]
Bumping; I just hit this exact exception. Cloned a channel and saved. This pops up when you try to view messages. Ubuntu 14; Java version: 1.8.0_161; Mirth Connect Server 3.5.1.

Edit (IMPORTANT!): After deploying the channel the exception goes away.

Imported Comment. Original Details:
Author: lam
Created: 2018-03-08T05:55:47.000-0800

**Comment by rbeckman-nextgen** [comment]
I think this issue is not related to cloned channel. You will get this exception when View Messages for any channel that has NOT been deployed

Imported Comment. Original Details:
Author: minht
Created: 2018-05-17T09:23:21.000-0700
