### ISSUE TITLE
Sometimes deploying a channel can cause the Administrator to kick you out to the login window

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3988]
When this happens, you'll likely see the following in the client console:

`com.mirth.connect.client.core.ClientException: java.net.SocketException: Connection reset
	at com.mirth.connect.client.core.ServerConnection.executeAbortPending(ServerConnection.java:351)
	at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:147)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
	at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
	at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
	at com.sun.proxy.$Proxy65.deployChannels(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.mirth.connect.client.core.Client$2.invoke(Client.java:249)
	at com.sun.proxy.$Proxy65.deployChannels(Unknown Source)
	at com.mirth.connect.client.core.Client.deployChannels(Client.java:1450)
	at com.mirth.connect.client.ui.Frame$20.doInBackground(Frame.java:2644)
	at com.mirth.connect.client.ui.Frame$20.doInBackground(Frame.java:2640)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.mirth.connect.client.core.ServerConnection.executeAbortPending(ServerConnection.java:327)
	... 26 more`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4110
Reporter: narupley
Created: 2017-02-02T12:57:32.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 8189: Connection Reset errors will no longer cause the Administrator to kick the user out to the login panel. This was causing too many false-negatives where a RST could happen even if the server connection was overall fine. Typically this was seen when deploying a channel after a long period since the last deploy.

To reduce the number of warning dialogs that can show up, many places in Frame/ChannelPanel were wrapped in an invokeLater call when showing errors. This is because a lot of these calls were actually happening in background threads anyway.

Imported Comment. Original Details:
Author: narupley
Created: 2017-02-19T13:15:50.000-0800

**Comment by rbeckman-nextgen** [comment]
**MC Server OS(s) and JRE version:** Mirth H1000-2 Hosted Appliance, http://roundup.corp.mirthcorp.com/appliances/MINHMR
**MC Client OS(s) and JRE version:**  local OSX Yosemite 10.10 with JRE build 1.8.0_92-b14
**Version(s)/Build(s) to verify fixes:** Mirth Connect 3.5.0.8195 (Built on February 20, 2017) (Appliance Update # 9073)
**Version(s)/Build(s) to reproduce failure:** Mirth Connect 3.4.1.8057  (Appliance Update #8435)
**System Status:**
Appliance Version	3.10.4
Mirth Connect Version	3.5.0.8197
Java 8 (64 bit) Version	1.8.0_121-b13
PostgreSQL Version	9.4.5
**Test Steps:**
* Launch the Administrator Console (client side)
* Enter the Edit Channel view for a channel
* Leave it there for half an hour
* Save and Deploy Channel
* Verify successfully deploy channel and there is no NPE and no longer being kicked out
* Verify there was no interruption in any function using the same Administrator Console 

Imported Comment. Original Details:
Author: minht
Created: 2017-02-23T13:02:42.000-0800

**Comment by rbeckman-nextgen** [comment]
RS-445

Imported Comment. Original Details:
Author: minht
Created: 2017-02-23T13:04:53.000-0800
