### ISSUE TITLE
Status Bar updater thread never gets cleaned up during logout/login

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#3993]
There's a thread used to update the server time display in the Administrator every 30 seconds. On logout the thread is not cleaned up in any way, so on subsequent login you'll now have multiple updater threads. Theoretically if you were to logout and login with a single Administrator thousands of times, you'd run out of memory and/or be unable to spawn new threads.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4115
Reporter: narupley
Created: 2017-02-19T12:32:56.000-0800

**Comment by rbeckman-nextgen** [comment]
Revision 8188: Fixed issue causing multiple status bar updater threads to spawn for every logout/login.

Imported Comment. Original Details:
Author: narupley
Created: 2017-02-19T12:41:20.000-0800

**Comment by rbeckman-nextgen** [comment]
**MC Server OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_111-b14
**MC Client OS(s) and JRE version:**  local OSX Yosemite 10.10 with JRE build 1.8.0_92-b14
**Version(s)/Build(s) to verify fixes:** Mirth Connect 3.5.0.8195 (Built on February 20, 2017)
**Version(s)/Build(s) to reproduce failure:** Mirth Connect 3.4.1.8057 
**Test Steps:**
* Launch MC server
* Launch & login MC administrator console (MC client)
* Locate PID for client console >  ps -ef | grep java  or grep "Mirth Connect Administrator" 

* Locate & collect status bar thread using thread dump >  jstack $pid | grep StatusBar 

* Log out of MC console
* Locate & collect status bar thread again
* Repeat login, logout & collect status bar thread 
* Verify status bar thread gets cleaned up after logout

**Observed output at MC 3.41:**  after 2 logouts => status bar thread remained after logout
`Minhs-iMac:~ minhtran$ jstack 46496 | grep StatusBar
	at com.mirth.connect.client.ui.StatusBar$1.run(StatusBar.java:91)
	at com.mirth.connect.client.ui.StatusBar$1.run(StatusBar.java:91)
	at com.mirth.connect.client.ui.StatusBar$1.run(StatusBar.java:91)`

**Observed output at MC 3.5.0:** after 2 logouts => status bar thread is cleaned up after logout
`Minhs-iMac:~ minhtran$ jstack 46801 | grep StatusBar -B 3
"Thread-31" #182 daemon prio=5 os_prio=31 tid=0x00007fa56867f800 nid=0x13bab waiting on condition [0x000000017a865000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.mirth.connect.client.ui.StatusBar$1.run(StatusBar.java:99)
Minhs-iMac:~ minhtran$ jstack 46801 ]( grep StatusBar -B 3
"Thread-33" #186 daemon prio=5 os_prio=31 tid=0x00007fa568422000 nid=0x143df waiting on condition [0x000000017a11c000)
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at com.mirth.connect.client.ui.StatusBar$1.run(StatusBar.java:99)`

Imported Comment. Original Details:
Author: minht
Created: 2017-02-22T08:56:31.000-0800

**Comment by rbeckman-nextgen** [comment]
RS-442

Imported Comment. Original Details:
Author: minht
Created: 2017-02-22T08:57:10.000-0800
