### ISSUE TITLE
"Failed to process row retrieved from database error"

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4032]
Database reader errors, unable to read columns that start with a number when the query has the column names quoted.

{quote}
[2017-05-10 14:56:31,790]  ERROR (com.mirth.connect.connectors.jdbc.DatabaseReceiver:217): Failed to process row retrieved from the database in channel "Eligibility Export"
org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
	at org.apache.xerces.dom.CoreDocumentImpl.createElement(Unknown Source)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.resultMapToXml(DatabaseReceiver.java:234)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.processRecord(DatabaseReceiver.java:201)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.processResultSet(DatabaseReceiver.java:161)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.poll(DatabaseReceiver.java:118)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
{quote}

For instance this works:
> SELECT TOP 1 [isa01] FROM myTable

But this will raise the error mentioned:
> SELECT TOP 1 [2100A_nm103] FROM myTable

However this works:
> SELECT TOP 1 2100A_nm103 FROM myTable

Cloned from MIRTH-3125 per request.  The errors show up in the server log, but do not increment the channel Errored counter.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4155
Reporter: kevinfosterng
Created: 2017-05-10T15:01:57.000-0700

**Comment by rbeckman-nextgen** [comment]
ROCKSOLID-875

Imported Comment. Original Details:
Author: christ
Created: 2020-04-13T14:44:40.000-0700
