### ISSUE TITLE
Performing operations across hundreds of channels at once fails

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4048]
If you try to delete hundreds of channels at once, the request will fail with a 414 because the URI is too long. We should probably add an equivalent non-RESTful POST endpoint where the channel IDs are put in the body instead, and have the client use that endpoint instead if the number of IDs is greater than some limit.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4171
Reporter: narupley
Created: 2017-05-23T13:13:45.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_144-b01
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.5.0.b187-windows-x64
**Verified Fixed:** with mirthconnect-3.5.0.b188-windows-x64

**How Tested:**
* Create 200 channels & Save
* Select all channels to delete
* Verify operation is successful

**Observed Failure:**
Error in client log when trying to delete 200 channels from MC Administrator
`
ERROR 2017-08-15 10:02:42,643 [AWT-EventQueue-2] com.mirth.connect.client.ui.Frame: Method failed: HTTP/1.1 414 URI Too Long
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 414 URI Too Long
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:471)
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:243)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:153)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
at com.sun.proxy.$Proxy52.removeChannels(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:253)
at com.sun.proxy.$Proxy52.removeChannels(Unknown Source)
at com.mirth.connect.client.core.Client.removeChannels(Client.java:1011)
at com.mirth.connect.client.ui.ChannelPanel$5.doInBackground(ChannelPanel.java:2205)
at com.mirth.connect.client.ui.ChannelPanel$5.doInBackground(ChannelPanel.java:2196)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source`

Imported Comment. Original Details:
Author: minht
Created: 2017-08-15T11:16:29.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified fixed by deleting 300 channels at once successfully (operation took a while but no error)

Imported Comment. Original Details:
Author: minht
Created: 2017-08-15T11:28:39.000-0700
