### ISSUE TITLE
Issue with destination set filter validation

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4068]
A reproducible error occurs in the administrator when you do the following:

Add a destination set filter step.
Add a javascript transformer step.
Save the channel - this errors and disables the channel.
If you enable the channel, edit the javascript transformer again and save the channel the same error with destination set filter validation happens.

I will attach a sample channel.  This has happened a number of times on different channels.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4191
Reporter: seaston
Created: 2017-06-29T01:22:46.000-0700

**Comment by rbeckman-nextgen** [comment]
Sample channel to demonstrate the issue.

Imported Comment. Original Details:
Author: seaston
Created: 2017-06-29T01:23:23.000-0700

**Comment by rbeckman-nextgen** [comment]
Adding reproduction steps on behalf of [~tamika_king]:

1. Download the MC jnlp

2. Launch and login

3. Make a small change to the channel (changing anything but the source transformer, as editing the source transformer is the work-around)

4. Save

5. NullPointerExceptions will then pop up regarding validateElement (dependent on how many destination set filters you have. Followed by a error in source connector regarding exceptions raised in validation

6. The channel will then be saved, but disabled after ~2 seconds

Imported Comment. Original Details:
Author: narupley
Created: 2017-07-27T14:08:58.000-0700

**Comment by rbeckman-nextgen** [comment]
**OS(s) and JRE version:** virtual Window 7 with JRE version 1.8.0_144-b01
**Version(s)/Build(s) to reproduce failure:** mirthconnect-3.5.0.8232
**Version(s)/Build(s) to verify fixes:** mirthconnect-3.5.0.b190-windows-x64.zip
**How Tested:**
Steps to reproduce error:
* Create test channel as followed:
** Source = Channel Reader > Edit Transformer > Add New Step > select Type = "Destination Set Filter"
** Destinations = Channel Writer > Edit Transformer > Add New Step > select Type = "JavaScript"
* Save channel

**Observed Failure:**
Exception when trying to Save Channel
`java.lang.NullPointerException
at com.mirth.connect.client.ui.editors.BaseEditorPane.validateElement(BaseEditorPane.java:871)
at com.mirth.connect.client.ui.editors.BaseEditorPane.validateElement(BaseEditorPane.java:865)
at com.mirth.connect.client.ui.ChannelSetup.validateTransformerSteps(ChannelSetup.java:1626)
at com.mirth.connect.client.ui.ChannelSetup.checkAllForms(ChannelSetup.java:1579)
at com.mirth.connect.client.ui.ChannelSetup.saveChanges(ChannelSetup.java:1213)
at com.mirth.connect.client.ui.Frame$22.doInBackground(Frame.java:2887)
at com.mirth.connect.client.ui.Frame$22.doInBackground(Frame.java:2883)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)`  
**Verified Fixed:**
- Able to save & deploy Channel using the same steps
- Able to import, save, enable & disable attached channel from MIRTH-4191

Imported Comment. Original Details:
Author: minht
Created: 2017-08-17T12:00:05.000-0700

**Comment by rbeckman-nextgen** [comment]
Verified fixed with mirthconnect-3.5.0.b190-windows-x64.zip

Imported Comment. Original Details:
Author: minht
Created: 2017-08-17T12:00:44.000-0700

**Comment by rbeckman-nextgen** [comment]
Do we have the fix for mac if so what version. Currently i am running 3.5.0.8232 i see the same error

Imported Comment. Original Details:
Author: rishikvr
Created: 2017-09-13T18:15:17.000-0700
