### ISSUE TITLE
Logging out while channel group unsaved changes are present causes error on save

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4070]
If you have unsaved group changes, logout, and choose to save upon being prompted, the channel groups will be saved, but after logout you'll receive the following error:

`Error loading tags: com.mirth.connect.client.core.ClientException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_502,503,854418300) has been shut down
com.mirth.connect.client.core.ClientException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_502,503,854418300) has been shut down
at com.mirth.connect.client.core.Client$2.invoke(Client.java:271)
at com.sun.proxy.$Proxy43.getChannelTags(Unknown Source)
at com.mirth.connect.client.core.Client.getChannelTags(Client.java:838)
at com.mirth.connect.client.ui.tag.SettingsPanelTags.refresh(SettingsPanelTags.java:157)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:589)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:576)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:419)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:416)
at com.mirth.connect.client.ui.QueuingSwingWorker.doInBackground(QueuingSwingWorker.java:96)
at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)
Caused by: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_502,503,854418300) has been shut down
at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:106)
at org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:173)
at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:526)
at org.glassfish.jersey.process.internal.RequestScope$Instance.remove(RequestScope.java:532)
at org.glassfish.jersey.process.internal.RequestScope$Instance.release(RequestScope.java:549)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:446)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
at com.sun.proxy.$Proxy43.getChannelTags(Unknown Source)
at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:253)
... 14 more
Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_502,503,854418300) has been shut down
at org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2270)
at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandleImpl(ServiceLocatorImpl.java:639)
at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:632)
at org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:650)
at org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:103)
... 27 more`

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4193
Reporter: narupley
Created: 2017-07-05T07:32:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Hi Nick,

I see similar issue happening in 3.5.1 version. Hope it will be prioritized and resolved asap.

Thank you,
Arvind

Imported Comment. Original Details:
Author: callmeonnet
Created: 2018-02-06T12:16:48.000-0800

**Comment by rbeckman-nextgen** [comment]
I get the same error in 3.8.1 when logging out, even if I was not prompted to save any group changes.

Imported Comment. Original Details:
Author: fluancefg
Created: 2020-01-24T03:00:39.000-0800
