### ISSUE TITLE
Messages with \.br\ get an error with the non-strict parser.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#408]
Messages that have \.br\ are not encoded properly with the non-strict parser.  The strict parser works fine.  Mirth should encode these if the sending facility did not.

ERROR-300: Transformer error
ERROR MESSAGE:	Error evaluating transformer
com.webreach.mirth.model.converters.SerializerException: org.xml.sax.SAXParseException: Element or attribute do not match QName production: QName::=(NCName':')?NCName. 
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:157)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:50)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateTransformerScript(JavaScriptTransformer.java:393)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:278)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:243)
	at com.webreach.mirth.server.mule.providers.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:362)
	at com.webreach.mirth.server.mule.providers.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:284)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException: Element or attribute do not match QName production: QName::=(NCName':')?NCName. 
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLEntityScanner.scanQName(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanAttribute(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:152)
	... 19 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-398
Reporter: jacobb
Created: 2007-06-11T12:43:00.000-0700

**Comment by rbeckman-nextgen** [comment]
Unable to reproduce. Error was with line breaks.

Imported Comment. Original Details:
Author: admin
Created: 2007-07-26T16:40:48.000-0700
