### ISSUE TITLE
Could not generate all endpoints for API-client with swagger.json

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4096]
With attempt to generate API-client with `swagger-codegen generate -l php -i ./swagger.json` occure errors. 

Almost all of them can be skipped, but one of them prevents to use Alerts tag endpoints.

```
Exception in thread "main" java.lang.RuntimeException: Could not generate api file for 'Alerts'
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:495)
        at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:700)
        at io.swagger.codegen.cmd.Generate.run(Generate.java:285)
        at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
        at java.util.TreeMap.put(TreeMap.java:563)
        at java.util.TreeSet.add(TreeSet.java:255)
        at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
        at java.util.TreeSet.addAll(TreeSet.java:312)
        at io.swagger.codegen.DefaultGenerator.processOperations(DefaultGenerator.java:897)
        at io.swagger.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:412)
        ... 3 more
```

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4220
Reporter: brutto
Created: 2017-10-10T02:00:50.000-0700

**Comment by rbeckman-nextgen** [comment]
Found that this exception prevent not only one model generation, but unable to generate next stuff. In my case there are no any controller to use API. Only models. 

Imported Comment. Original Details:
Author: brutto
Created: 2017-10-10T03:13:47.000-0700

**Comment by rbeckman-nextgen** [comment]
Found the core of this problem: method throw Exception only with `parameters.in|name` properties have the same values = `body`. =/

Imported Comment. Original Details:
Author: brutto
Created: 2017-10-13T08:08:17.000-0700
