### ISSUE TITLE
Channels fail to deploy after importing configurations

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4106]
When importing configurations to Mirth Connect 3.5.1, channels become enabled but nothing happens if I try deploying a channel.

In the event logs, there is an entry for 'Deploy Channels', but when we deploy the channel it takes me to the dashboard with the channel still undeployed. Additionally, there are no entries in mirth.log indicating an error.

-------------------Steps to Reproduce-------------------
1. Configuration is imported (tested as a previously working configuration)
2. Check the configuration table's channelMetadata value to see channels are missing their entries
2. Attempt to deploy enabled channels fail with no error messages 
3. In event log, it shows that a channel is deployed 
4. Checking channelMetadata for the channel results in no entry found

Additionally, we've run into this issue from system restarts as well. Reproducing with the configuration method above seems to require that we delete all channels and then import the configuration again.

-------------------Workaround-------------------
1. Disable channel
2. Enable channel
3. Deploy channel

With the workaround, it seems that when we disable and enable the channel, the channel's entry into the channelMetadata is now present and we can deploy the channel.

A better workaround (if you have a lot of channels) is to create a group to house channels that are to be left in a disabled state. Then if you run into the issue during restarts, you can quickly disable/enable/deploy channels that are not working

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4230
Reporter: jili54178
Created: 2017-12-08T08:57:42.000-0800

**Comment by rbeckman-nextgen** [comment]
Encountered the same issue today (also on Mirth 3.5.1) but with a Sql Server backend...

Imported Comment. Original Details:
Author: nicovn
Created: 2018-01-24T02:46:29.000-0800

**Comment by rbeckman-nextgen** [comment]
To [~jili54178]
I was not able to reproduce the exact same issue. Can you please confirm if any of what i observed here ?

**What is the issue:** Not able to deploy channel "Generator-0001", no error in deploy but channel in 
**OS(s) /JREs Used:** Win7 with Java Web Start 11.161.2.12 amd64 with Postgres (also reproduced with minh-vMA-test on Appliance 3.10.4)
` INFO  (com.mirth.connect.server.Mirth:448): Running Java HotSpot(TM) 64-Bit Server VM 1.8.0_161 on Windows 7 (6.1, amd64), postgres, with charset windows-1252.`
**Issue found /exists in Version(s)/Build(s):** MC351.b195
**Is the Issue Consistent (list details):**
* Problem only occurs with a particular channel, named "Generator-0001" and with **unexpected** channelID of "abc"
* Problem only occurs when using Postgres, not an issue when using Derby
* Event entry for "Deploy Channels" is showing empty value for this channel deployment (whereas others would contain the proper channel ID), such as 
`Channel[id=e8a15648-cbcc-4359-9c53-62a9b7841d8c,name=Generator-0002]`

**Steps to Reproduce:**
* Launch MC instance with postgres database
* Restore config from "RS-1711 Config.xml", uncheck box to "Deploy channels after imports"
* Wait for restore to complete, go to Channels, deploy the first channel "Generator-0001"
* No channel is deployed
* Edit this channel caused exception 
`com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
class[1]            : com.mirth.connect.client.core.ControllerException
version             : not available
-------------------------------
com.mirth.connect.client.core.ClientException: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
class[1]            : com.mirth.connect.client.core.ControllerException
version             : not available
-------------------------------
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:264)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:153)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:379)
at com.sun.proxy.$Proxy52.updateChannel(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:255)
at com.sun.proxy.$Proxy52.updateChannel(Unknown Source)
at com.mirth.connect.client.core.Client.updateChannel(Client.java:1007)
at com.mirth.connect.client.core.Client.updateChannel(Client.java:997)
at com.mirth.connect.client.ui.Frame.updateChannel(Frame.java:1535)
at com.mirth.connect.client.ui.ChannelSetup.saveChanges(ChannelSetup.java:1253)
at com.mirth.connect.client.ui.Frame$22.doInBackground(Frame.java:2892)
at com.mirth.connect.client.ui.Frame$22.doInBackground(Frame.java:2888)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
class[1]            : com.mirth.connect.client.core.ControllerException
version             : not available
-------------------------------
at com.mirth.connect.model.converters.ObjectXMLSerializer.handleDeserializationException(ObjectXMLSerializer.java:320)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:213)
at com.mirth.connect.client.core.api.providers.XmlMessageBodyReader.readFrom(XmlMessageBodyReader.java:51)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
at com.mirth.connect.client.core.MirthClientResponse.readEntity(MirthClientResponse.java:40)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:464)
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:243)
... 29 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
class[1]            : com.mirth.connect.client.core.ControllerException
version             : not available
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.converters.extended.ThrowableConverter.unmarshal(ThrowableConverter.java:70)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:208)
... 40 more
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: org.postgresql.util.PSQLException
at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:401)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.converters.extended.ThrowableConverter.unmarshal(ThrowableConverter.java:70)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 53 more`

Imported Comment. Original Details:
Author: minht
Created: 2018-04-10T16:25:59.000-0700

**Comment by rbeckman-nextgen** [comment]
The reason the config Minh Tran posted caused that issue is because a channel inside the config has an incorrect ID. Right now the server expects channel IDs to be 36 characters long, but the channel in the config has an ID of "abc". So that causes issues with database queries.

But I have no idea if that's the same issue that Jason Li ran into. It doesn't sound like it.

Pushing out this issue until more concrete reproduction steps are found.

Imported Comment. Original Details:
Author: narupley
Created: 2018-11-19T09:16:39.000-0800
