### ISSUE TITLE
Bad regex sends exception

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4119]
When a bad regex is used in text search, it sends an exception to the end-user which might think that there's a problem.
Even if the regex is bad, it shouldn't return such an exception.
Try to put "^**2018$**" in text search (without the quotes) and tick regex.
You'll get the following exception:

com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
version             : not available
-------------------------------
com.mirth.connect.client.core.ClientException: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
version             : not available
-------------------------------
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:264)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:153)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:379)
at com.sun.proxy.$Proxy61.getMessages(Unknown Source)
at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:255)
at com.sun.proxy.$Proxy61.getMessages(Unknown Source)
at com.mirth.connect.client.core.Client.getMessages(Client.java:1733)
at com.mirth.connect.client.core.PaginatedMessageList.getItems(PaginatedMessageList.java:68)
at com.mirth.connect.util.PaginatedList.loadPageNumber(PaginatedList.java:73)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$9.doInBackground(MessageBrowser.java:786)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$9.doInBackground(MessageBrowser.java:779)
at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
version             : not available
-------------------------------
at com.mirth.connect.model.converters.ObjectXMLSerializer.handleDeserializationException(ObjectXMLSerializer.java:320)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:213)
at com.mirth.connect.client.core.api.providers.XmlMessageBodyReader.readFrom(XmlMessageBodyReader.java:51)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
at com.mirth.connect.client.core.MirthClientResponse.readEntity(MirthClientResponse.java:40)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:464)
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:243)
... 27 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: org.postgresql.util.PSQLException : org.postgresql.util.PSQLException
---- Debugging information ----
message             : org.postgresql.util.PSQLException
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : org.postgresql.util.PSQLException
class               : com.mirth.connect.client.core.api.PersistenceException
required-type       : com.mirth.connect.client.core.api.PersistenceException
converter-type      : com.thoughtworks.xstream.converters.extended.ThrowableConverter
version             : not available
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:208)
... 38 more
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: org.postgresql.util.PSQLException
at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:401)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.converters.extended.ThrowableConverter.unmarshal(ThrowableConverter.java:70)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 45 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4243
Reporter: fluancefg
Created: 2018-02-20T04:06:41.000-0800

**Comment by rbeckman-nextgen** [comment]
As Jira broke my regex, I've attached a printscreen.

Imported Comment. Original Details:
Author: fluancefg
Created: 2018-02-20T04:10:04.000-0800
