### ISSUE TITLE
UTF-8 files cause errors

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#416]
UTF-8 files under windows are not interpeted by the engine.  

Here is the stack trace generated when trying to get a UTF-8 file through the channel

ERROR-300: Transformer error
ERROR MESSAGE:	Error evaluating transformer
com.webreach.mirth.model.converters.SerializerException: org.xml.sax.SAXParseException: White space is required between the processing instruction target and data.
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:157)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:50)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateTransformerScript(JavaScriptTransformer.java:393)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:278)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
	at com.webreach.mirth.server.mule.providers.file.FileMessageReceiver.processFile(FileMessageReceiver.java:197)
	at com.webreach.mirth.server.mule.providers.file.FileMessageReceiver.poll(FileMessageReceiver.java:111)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:73)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException: White space is required between the processing instruction target and data.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.scanPIData(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanPIData(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.scanPI(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:152)
	... 20 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-406
Reporter: daigno
Created: 2007-06-20T13:17:53.000-0700

**Comment by rbeckman-nextgen** [comment]
the UTF-8 file used to generate the stack trace

Imported Comment. Original Details:
Author: daigno
Created: 2007-06-20T13:19:11.000-0700

**Comment by rbeckman-nextgen** [comment]
This is due to the UTF-8 implementation in JAVA:
http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=4508058

In order to handle the [BOM] character, just include this in your preprocessor:

return message.substring(1);


Imported Comment. Original Details:
Author: admin
Created: 2007-07-27T01:06:53.000-0700
