### ISSUE TITLE
Broken DICOM attachment viewer in 3.5.2

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4163]
I'm receiving DICOM files in a DICOM listener. From the channel messages (logs), on 3.4.2 when a log was clicked, the image viewer showed the image correctly, now I can only see a small black square and the window says the zoom is 3.1%, but the zoom level can't be changed. Tried many key combination to increase the zoom but doesn't work. 

Test files I'm using worked OK in the previous Mirth v3.4.2 DICOM viewer
https://github.com/ppazos/cabolabs-mirth/tree/master/mirth/3.5.2/C05_dicom_rcv/CTSTUDY

Here is the screenshot of the broken viewer
https://ibb.co/iB8hQd

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4287
Reporter: ppazos
Created: 2018-06-04T13:14:33.000-0700

**Comment by rbeckman-nextgen** [comment]
Today I tested this on 3.6.1 and the same behavior is there, the image has zoom 3.1% on the attachment viewer.

But a strange exception was thrown when trying to view one of the DICOM attachments received:

Method failed: HTTP/1.1 500 Internal Server Error
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 500 Internal Server Error
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:529)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:453)
at com.mirth.connect.client.core.ServerConnection.executeAsync(ServerConnection.java:302)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:168)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:379)
at com.sun.proxy.$Proxy62.getDICOMMessage(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:265)
at com.sun.proxy.$Proxy62.getDICOMMessage(Unknown Source)
at com.mirth.connect.client.core.Client.getDICOMMessage(Client.java:1736)
at com.mirth.connect.client.core.Client.getDICOMMessage(Client.java:1725)
at com.mirth.connect.plugins.dicomviewer.DICOMViewer.viewAttachments(DICOMViewer.java:41)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$19.doInBackground(MessageBrowser.java:1629)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$19.doInBackground(MessageBrowser.java:1626)
at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
at java.lang.StringCoding.decode(StringCoding.java:215)
at java.lang.String.<init>(String.java:463)
at java.lang.String.<init>(String.java:515)
at org.apache.commons.codec.binary.StringUtils.newStringUsAscii(StringUtils.java:319)
at com.mirth.connect.server.util.DICOMMessageUtil.getDICOMRawData(DICOMMessageUtil.java:63)
at com.mirth.connect.server.util.DICOMMessageUtil.getDICOMRawData(DICOMMessageUtil.java:79)
at com.mirth.connect.server.api.servlets.MessageServlet.getDICOMMessage(MessageServlet.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.mirth.connect.server.api.providers.MirthResourceInvocationHandlerProvider$1.invoke(MirthResourceInvocationHandlerProvider.java:219)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336)

Imported Comment. Original Details:
Author: ppazos
Created: 2018-11-15T14:06:02.000-0800
