### ISSUE TITLE
com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: null : null

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4169]
Error loading channels

com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[216]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
com.mirth.connect.client.core.ClientException: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[216]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
at com.mirth.connect.client.core.Client$2.invoke(Client.java:286)
at com.sun.proxy.$Proxy54.getChannelSummary(Unknown Source)
at com.mirth.connect.client.core.Client.getChannelSummary(Client.java:971)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:581)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:576)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:419)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:416)
at com.mirth.connect.client.ui.QueuingSwingWorker.doInBackground(QueuingSwingWorker.java:96)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[216]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
at com.mirth.connect.model.converters.ObjectXMLSerializer.createSerializerException(ObjectXMLSerializer.java:417)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserializeList(ObjectXMLSerializer.java:372)
at com.mirth.connect.client.core.api.providers.XmlMessageBodyReader.readFrom(XmlMessageBodyReader.java:48)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
at com.mirth.connect.client.core.MirthClientResponse.readEntity(MirthClientResponse.java:40)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834)
at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368)
at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:867)
at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:379)
at com.sun.proxy.$Proxy54.getChannelSummary(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:265)
... 13 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[216]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserializeList(ObjectXMLSerializer.java:354)
... 38 more
Caused by: java.lang.NullPointerException
at com.thoughtworks.xstream.io.xml.DomReader.reassignCurrentElement(DomReader.java:120)
at com.thoughtworks.xstream.io.xml.AbstractDocumentReader.moveUp(AbstractDocumentReader.java:70)
at com.thoughtworks.xstream.io.ReaderWrapper.moveUp(ReaderWrapper.java:40)
at com.thoughtworks.xstream.io.path.PathTrackingReader.moveUp(PathTrackingReader.java:42)
at com.mirth.connect.model.InvalidChannel.<init>(InvalidChannel.java:27)
at com.mirth.connect.model.converters.ChannelConverter.unmarshal(ChannelConverter.java:83)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 67 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4293
Reporter: mmonisky
Created: 2018-06-11T11:24:18.000-0700

**Comment by rbeckman-nextgen** [comment]
I saw this same error today repeatedly when I took a Mirth 3.4.2 channel and imported it into Mirth 3.6.0. It happened to me with 2 different 3.4.2 channels. Now my Mirth is broken, as my channels will not load - after restarting Mirth.

Imported Comment. Original Details:
Author: vsortiz
Created: 2018-07-22T11:10:17.000-0700

**Comment by kaziff** [comment]
I am facing this error on blank mirth fresh installation.


ERROR 2023-05-18 09:33:30.966 [qtp1769423321-81] com.mirth.connect.model.converters.ObjectXMLSerializer: com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$EmptySet
converter           : com.mirth.connect.model.converters.MigratableConverter
message[1]          : Unable to make field private static final long java.util.Collections$EmptySet.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @3f50a6c0
converter[1]        : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
-------------------------------
