### ISSUE TITLE
Accented characters are not interpreted correctly by the XML parser

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#417]
When reading file with accented characters (after removing the Windows UTF header see MIRTH-406) the parser generates an error.

Please see stack trace below.  If all accented characters are removed from the file it is processed without error

ERROR-300: Transformer error
ERROR MESSAGE:	Error evaluating transformer
com.webreach.mirth.model.converters.SerializerException: org.xml.sax.SAXParseException: The entity "Eacute" was referenced, but not declared.
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:157)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:50)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateTransformerScript(JavaScriptTransformer.java:393)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:278)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
	at com.webreach.mirth.server.mule.providers.file.FileMessageReceiver.processFile(FileMessageReceiver.java:197)
	at com.webreach.mirth.server.mule.providers.file.FileMessageReceiver.poll(FileMessageReceiver.java:111)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:73)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.xml.sax.SAXParseException: The entity "Eacute" was referenced, but not declared.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEntityReference(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:152)
	... 20 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-407
Reporter: daigno
Created: 2007-06-20T13:23:38.000-0700

**Comment by rbeckman-nextgen** [comment]
The file used to generate the problem

Imported Comment. Original Details:
Author: daigno
Created: 2007-06-20T13:27:30.000-0700

**Comment by rbeckman-nextgen** [comment]
Applied and tested Alberto's patch.

Imported Comment. Original Details:
Author: admin
Created: 2007-07-26T23:48:47.000-0700
