### ISSUE TITLE
When i exported the channels in my local mirth machine . I'm not able to see or view rest of my channels there was warning contact support

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4197]
Hi 
I exported one of the free channel source from internet and my mirth was corrupted and unable to open rest of the channels . Here is the error

com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[7]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
com.mirth.connect.client.core.ClientException: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[7]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
at com.mirth.connect.client.core.Client$2.invoke(Client.java:286)
at com.sun.proxy.$Proxy56.getChannelSummary(Unknown Source)
at com.mirth.connect.client.core.Client.getChannelSummary(Client.java:971)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:581)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:576)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:419)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:416)
at com.mirth.connect.client.ui.QueuingSwingWorker.doInBackground(QueuingSwingWorker.java:96)
at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.donkey.util.xstream.SerializerException: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[7]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
at com.mirth.connect.model.converters.ObjectXMLSerializer.createSerializerException(ObjectXMLSerializer.java:417)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserializeList(ObjectXMLSerializer.java:372)
at com.mirth.connect.client.core.api.providers.XmlMessageBodyReader.readFrom(XmlMessageBodyReader.java:48)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
at com.mirth.connect.client.core.MirthClientResponse.readEntity(MirthClientResponse.java:40)
at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834)
at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368)
at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:867)
at org.glassfish.jersey.client.JerseyInvocation.access$800(JerseyInvocation.java:92)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:379)
at com.sun.proxy.$Proxy56.getChannelSummary(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:265)
... 13 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: null : null
---- Debugging information ----
cause-exception     : java.lang.NullPointerException
cause-message       : null
class               : com.mirth.connect.model.Channel
required-type       : com.mirth.connect.model.Transformer
converter-type      : com.mirth.connect.model.converters.ChannelConverter
path                : /list/channelSummary[7]/channelStatus/channel/sourceConnector/transformer/steps
class[1]            : com.mirth.connect.model.ChannelStatus
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : com.mirth.connect.model.ChannelSummary
class[3]            : java.util.ArrayList
converter-type[2]   : com.thoughtworks.xstream.converters.collections.CollectionConverter
version             : not available
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readItem(AbstractCollectionConverter.java:71)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.addCurrentElementToCollection(CollectionConverter.java:98)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:91)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.populateCollection(CollectionConverter.java:85)
at com.thoughtworks.xstream.converters.collections.CollectionConverter.unmarshal(CollectionConverter.java:80)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserializeList(ObjectXMLSerializer.java:354)
... 38 more
Caused by: java.lang.NullPointerException
at com.thoughtworks.xstream.io.xml.DomReader.reassignCurrentElement(DomReader.java:120)
at com.thoughtworks.xstream.io.xml.AbstractDocumentReader.moveUp(AbstractDocumentReader.java:70)
at com.thoughtworks.xstream.io.ReaderWrapper.moveUp(ReaderWrapper.java:40)
at com.thoughtworks.xstream.io.path.PathTrackingReader.moveUp(PathTrackingReader.java:42)
at com.mirth.connect.model.InvalidChannel.<init>(InvalidChannel.java:27)
at com.mirth.connect.model.converters.ChannelConverter.unmarshal(ChannelConverter.java:83)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 67 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4321
Reporter: saireddy
Created: 2018-09-05T16:23:30.000-0700

**Comment by rbeckman-nextgen** [comment]
Attached screen shot for better understanding .
WSDL =These are the channels ,exported in my local mirth machine . Now not able to see the rest of the channels . Getting warning errors. 

Imported Comment. Original Details:
Author: saireddy
Created: 2018-09-05T16:27:20.000-0700
