### ISSUE TITLE
Mirth Shell keeps looking for deprecated class OutputFormat

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#420]
When trying to import a channel with the shell Java throws an exception:

(mirth) [admin@imstest1] {mirth} CLASSPATH=lib/log4j-1.2.13.jar:conf/:lib/commons-cli-1.0.jar:lib/log4j-1.2.13.jar:lib/xstream-1.2.jar:lib/commons-httpclient-3.0.1.jar:lib/xpp3_min-1.1.3.4.O.jar:mirth-server.jar:mirth-client-core.jar:lib/jetty/commons-logging.jar:lib/mule/commons-codec-1.3.jar /usr/local/Intelerad/3rd_Party/jre-1.5.0/bin/java -jar shell.jar -a https://127.0.0.1:8443 -u admin -p admin -v 0.0.0
Connected to Mirth server @ https://127.0.0.1:8443 (1.5.0.2272)
$import /home/admin/sean/output/channel-main.xml
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/xml/serialize/OutputFormat
        at com.webreach.mirth.model.converters.DocumentSerializer.toXML(DocumentSerializer.java:64)
        at com.webreach.mirth.model.util.ImportConverter.convertChannel(ImportConverter.java:218)
        at com.webreach.mirth.server.tools.Shell.doImportChannel(Shell.java:692)
        at com.webreach.mirth.server.tools.Shell.executeStatement(Shell.java:436)
        at com.webreach.mirth.server.tools.Shell.run(Shell.java:116)
        at com.webreach.mirth.server.tools.Shell.main(Shell.java:71)

I am declaring the CLASSPATH explicitly here, but I also get it when using the default classpath.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-410
Reporter: seamims
Created: 2007-07-09T14:39:49.000-0700

**Comment by rbeckman-nextgen** [comment]
The classpath was incorrect in the shell launcher script.

Imported Comment. Original Details:
Author: jacobb
Created: 2007-07-26T17:23:50.000-0700
