### ISSUE TITLE
Error in deploying channels

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4207]
we discovered that the channels are suddenly undeployed, we didn't make any change on Mirth on that day. Even after trying to deploy the channels manually we encountred the same issue. This is the first time we see this error.
The logs show that there is an exception in deployement, please see below.

For your information, we noticed several shutdown and startup of Mirth service.
After restarting the whole Docker container, the channels were deployed succefully again.

Any idea why this deployment exception happened?
How can we avoid this error?
Any way to be automatically notified about these kind of errors in case they happen in the future?

Mirth connect version: 3.5.0.8232

ERROR (com.mirth.connect.server.channel.ErrorTaskHandler:25): com.mirth.connect.donkey.server.DeployException: class "com.mirth.connect.connectors.js.JavaScriptDispatcher"'s signer information does not match signer information of other classes in the same package
at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.doDeploy(DonkeyEngineController.java:1749)
at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.execute(DonkeyEngineController.java:1731)
at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:67)
at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.SecurityException: class "com.mirth.connect.connectors.js.JavaScriptDispatcher"'s signer information does not match signer information of other classes in the same package
at java.lang.ClassLoader.checkCerts(ClassLoader.java:898)
at java.lang.ClassLoader.preDefineClass(ClassLoader.java:668)
at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.mirth.connect.server.controllers.DonkeyEngineController.createDestinationConnector(DonkeyEngineController.java:1449)
at com.mirth.connect.server.controllers.DonkeyEngineController.createChannelFromModel(DonkeyEngineController.java:1148)
at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.doDeploy(DonkeyEngineController.java:1747)
... 7 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4331
Reporter: eden
Created: 2018-10-03T02:02:39.000-0700

**Comment by rbeckman-nextgen** [comment]
Kind reminder.
Any solution for this issue?
Related posts on forum:
https://www.mirthcorp.com/community/forums/showthread.php?t=218637
https://www.mirthcorp.com/community/forums/showthread.php?t=218621

Imported Comment. Original Details:
Author: eden
Created: 2018-10-09T01:22:03.000-0700

**Comment by rbeckman-nextgen** [comment]
Can you please provide reproduction steps and/or an exported channel that reproduces the issue?

Imported Comment. Original Details:
Author: jakehbradley
Created: 2018-10-25T14:47:29.000-0700
