### ISSUE TITLE
LLP: Assumes Start of Message character is always at beginning of connection in Strict LLP Validatoin

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#423]
We send messages to Mirth that do not have the start of message ([SOM]) character at the very beginning.  There is logging information at the beginning.

eg. 

[2007-07-12 14:40:53.897 Thread-89_39466 anibal333.dyn.intelerad]
[SOM]
MSH](^~\&|OET_IHE|Intelerad|Hl7GatewayServer|Intelerad|20070621083351||ORM^O01|||2.3||||||
PID|||88||McGuire^Sean^||20061212|M|||||||||||||||||||||||
PV1||||||||^^^|||||||||||1000||||||||||||||||||||||||||||||||||
ORC||1000|1000||IP|||||||||||||||||||||
OBR|1|1000|1000|^Frogtest|RO|200706210832||||||||||||1000|1000|1000||||CR|||||||^|||||||||||||||||

When Strict LLP Validation is on, we get an exception complaining that the expected start of message character is not found (exception text taken from an earlier failure, but it's the same message):

FATAL 2007-07-05 10:43:05,396 [efb23569-bb28-4c63-b043-aa7f0e51573a_source_connector._mllpEndpoint#716452775.receiver.2) org.mule.impl.DefaultComponentExceptionStrategy: The error is: Message violates the minimal lower layer protocol: no start of message indicator received
java.io.IOException: Message violates the minimal lower layer protocol: no start of message indicator received
        at com.webreach.mirth.server.mule.providers.mllp.protocols.LlpProtocol.readLLP(LlpProtocol.java:145)
        at com.webreach.mirth.server.mule.providers.mllp.protocols.LlpProtocol.read(LlpProtocol.java:191)
        at com.webreach.mirth.server.mule.providers.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:270)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Thread.java:619)

As a workaround we need to turn off Strict LLP Validation and turn on "Wait for End of Message Char", but this shouldn't be the case.

Please take a look at:

HL7 Implementation Guide (HL7 2.3)

C.2.3.2 Initiating and Responding section "Responding System Processing" (pg C-4):

2. Receive the block that contains the initial message.

   To receive a block:
        a) Ignore all incoming characters until a Start Block character is received. Any time
           another Start Block character is received before the end of a block, ignore all
           previous characters. Receive characters until <EB> <CR> is recognized. This is the
           end of the block.

Strict LLP Validation should be throwing out everything until it has received a block between a start block character (0x0B) and an end block character (0x1C) and determine this to be the message.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-413
Reporter: seamims
Created: 2007-07-16T09:09:02.000-0700

**Comment by rbeckman-nextgen** [comment]
Added the ability to receive messages that have data before the start of message character.  Data before the start of message character is ignored.

Imported Comment. Original Details:
Author: jacobb
Created: 2007-07-27T17:52:37.000-0700
