### ISSUE TITLE
FHIR extension fhir-3.6.1.b237 not working, got many exceptions running administrator

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4231]
Installed the FHIR Extension, rebooted administrator and server, run again, login into administrator, and got many exceptions>

Could not load code template plugin: com.mirth.connect.connectors.fhir.client.FhirListe nerCodeTemplatePlugin
java.lang.ClassNotFoundException: com.mirth.connect.connectors.fhir.client.FhirListe nerCodeTemplatePlugin
at java.net.URLClassLoader.findClass(URLClassLoader.j ava:381)
at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(ClassLoader.java:4 24)
at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(ClassLoader.java:3 57)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.mirth.connect.client.ui.LoadedExtensions.initi alize(LoadedExtensions.java:155)
at com.mirth.connect.client.ui.Frame.setupFrame(Frame .java:407)
at com.mirth.connect.client.ui.Mirth.<init>(Mirth.jav a:63)
at com.mirth.connect.client.ui.LoginPanel$8.handleSuc cess(LoginPanel.java:524)
at com.mirth.connect.client.ui.LoginPanel$8.doInBackg round(LoginPanel.java:443)
at com.mirth.connect.client.ui.LoginPanel$8.doInBackg round(LoginPanel.java:414)
at javax.swing.SwingWorker$1.call(SwingWorker.java:29 5)
at java.util.concurrent.FutureTask.run(FutureTask.jav a:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker( ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

Could not load plugin class: com.mirth.connect.plugins.fhir.client.FhirModelBui lderStepPlugin
java.lang.ClassNotFoundException: com.mirth.connect.plugins.fhir.client.FhirModelBui lderStepPlugin
at java.net.URLClassLoader.findClass(URLClassLoader.j ava:381)
at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
at java.lang.ClassLoader.loadClass(ClassLoader.java:4 24)
at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
at java.lang.ClassLoader.loadClass(ClassLoader.java:3 57)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.mirth.connect.client.ui.LoadedExtensions.initi alize(LoadedExtensions.java:184)
at com.mirth.connect.client.ui.Frame.setupFrame(Frame .java:407)
at com.mirth.connect.client.ui.Mirth.<init>(Mirth.jav a:63)
at com.mirth.connect.client.ui.LoginPanel$8.handleSuc cess(LoginPanel.java:524)
at com.mirth.connect.client.ui.LoginPanel$8.doInBackg round(LoginPanel.java:443)
at com.mirth.connect.client.ui.LoginPanel$8.doInBackg round(LoginPanel.java:414)
at javax.swing.SwingWorker$1.call(SwingWorker.java:29 5)
at java.util.concurrent.FutureTask.run(FutureTask.jav a:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker( ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748) 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4355
Reporter: ppazos
Created: 2018-12-16T11:58:53.000-0800

**Comment by rbeckman-nextgen** [comment]
Please Follow the steps below and check if the problem is solved:

1- Open the localhost page of Mirth Web admin. Usually it is http://127.0.0.1:8443
2- Click on Launch Mirth Connect Administrator button.
3- It should download webstart.jnlp file.
4- Run the file and update java if needed.
5- Mirth Connect should be launched successfully.




Imported Comment. Original Details:
Author: ahmed
Created: 2019-02-28T03:20:13.000-0800
