### ISSUE TITLE
Unable to open a channel that has SSLProperties in Mirth Connect without SSL Plugin

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4238]
Client previously had the SSL manager plugin installed but has uninstalled the plugin.  

After uninstalling, he is unable to edit, enable or deploy his channels.

He is seeing the following error:  

Channel "IncomingTestresult" is invalid and cannot be edited. Original cause:
com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
---- Debugging information ----
message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
cause-exception : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class : java.util.HashSet
required-type : java.util.HashSet
converter-type : com.thoughtworks.xstream.converters.collections.CollectionConverter
path : /list/channelSummary[35]/channelStatus/channel/sourceConnector/properties/responseConnectorPluginProperties/com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class[1] : com.mirth.connect.connectors.tcp.TcpReceiverProperties
converter-type[1] : com.mirth.connect.model.converters.MigratableConverter
class[2] : com.mirth.connect.model.Connector
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
---- Debugging information ----
message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
cause-exception : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class : java.util.HashSet
required-type : java.util.HashSet
converter-type : com.thoughtworks.xstream.converters.collections.CollectionConverter
path : /list/channelSummary[35]/channelStatus/channel/sourceConnector/properties/responseConnectorPluginProperties/com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class[1] : com.mirth.connect.connectors.tcp.TcpReceiverProperties
converter-type[1] : com.mirth.connect.model.converters.MigratableConverter
class[2] : com.mirth.connect.model.Connector
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:101)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:101)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshall

Nick Rupley mentioned that this seems to be a problem with the TCP Listener specifically because it stores extra SSL settings for the Respond on New Connection feature.  Other connector types, like TCP Sender, work just fine after uninstalling the SSL Manager.

In the meantime you can fix by editing the channel XML and taking out the SSLConnectorProperties

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4362
Reporter: han
Created: 2019-01-09T13:17:28.000-0800

**Comment by rbeckman-nextgen** [comment]
I had this issue last week. I got around it by doing this:
1. Export the channel to your local machine.
2. Open the XML file in a text editor (e.g., Sublime Text).
3. Look for "ssl".
4. Remove everything from the parent node. For example, <pluginProperties>sampleSslText</pluginProperties> will now be <pluginProperties></pluginProperties> or <pluginProperties/>.
5. Save the file.
5. Now import the file to Mirth.

Imported Comment. Original Details:
Author: ashishshetty1992
Created: 2019-01-22T06:34:54.000-0800

**Comment by rbeckman-nextgen** [comment]
Ah, just read the last line of your description.

Imported Comment. Original Details:
Author: ashishshetty1992
Created: 2019-01-22T06:39:14.000-0800

**Comment by addis144** [comment]
This is still an issue.  Cannot Import channels that have a ssl plugin into a server that does not have the plugin. 
This is important for testing, debugging, or rework of production channels. 

 Original cause:```

com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
---- Debugging information ----
message             : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class               : java.util.HashSet
required-type       : java.util.HashSet
converter-type      : com.thoughtworks.xstream.converters.collections.CollectionConverter
path                : /channel/sourceConnector/properties/responseConnectorPluginProperties/com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class[1]            : com.mirth.connect.connectors.tcp.TcpReceiverProperties
converter-type[1]   : com.mirth.connect.model.converters.MigratableConverter
class[2]            : com.mirth.connect.model.Connector
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
---- Debugging information ----
message             : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class               : java.util.HashSet
required-type       : java.util.HashSet
converter-type      : com.thoughtworks.xstream.converters.collections.CollectionConverter
path                : /channel/sourceConnector/properties/responseConnectorPluginProperties/com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
class[1]            : com.mirth.connect.connectors.tcp.TcpReceiverProperties
converter-type[1]   : com.mirth.connect.model.converters.MigratableConverter
class[2]            : com.mirth.connect.model.Connector
-------------------------------
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:101)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:101)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshallField(AbstractReflectionConverter.java:474)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doUnmarshal(AbstractReflectionConverter.java:406)
at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
at com.mirth.connect.model.converters.MigratableConverter.unmarshal(MigratableConverter.java:101)
at com.mirth.connect.model.converters.ChannelConverter.unmarshal(ChannelConverter.java:79)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:290)
at com.mirth.connect.client.ui.ChannelPanel.importChannel(ChannelPanel.java:1425)
at com.mirth.connect.client.ui.ChannelPanel.doImportChannel(ChannelPanel.java:1413)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at sun.reflect.misc.Trampoline.invoke(Unknown Source)
at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at sun.reflect.misc.MethodUtil.invoke(Unknown Source)
at java.beans.EventHandler.invokeInternal(Unknown Source)
at java.beans.EventHandler.access$000(Unknown Source)
at java.beans.EventHandler$1.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.beans.EventHandler.invoke(Unknown Source)
at com.sun.proxy.$Proxy46.actionPerformed(Unknown Source)
at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at org.jdesktop.swingx.JXHyperlink.fireActionPerformed(JXHyperlink.java:264)
at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.awt.Component.processMouseEvent(Unknown Source)
at javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.awt.Component.processEvent(Unknown Source)
at java.awt.Container.processEvent(Unknown Source)
at java.awt.Component.dispatchEventImpl(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.awt.Container.dispatchEventImpl(Unknown Source)
at java.awt.Window.dispatchEventImpl(Unknown Source)
at java.awt.Component.dispatchEvent(Unknown Source)
at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.awt.EventQueue.access$500(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.awt.EventQueue$3.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.awt.EventQueue$4.run(Unknown Source)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: com.mirth.connect.plugins.ssl.model.SSLConnectorPluginProperties
at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
at com.thoughtworks.xstream.core.util.HierarchicalStreams.readClassType(HierarchicalStreams.java:29)
at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:133)
at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1157)
at com.mirth.connect.model.converters.ObjectXMLSerializer.deserialize(ObjectXMLSerializer.java:290)
at com.mirth.connect.model.converters.PluginPropertiesConverter.unmarshal(PluginPropertiesConverter.java:83)
at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)
... 86 more
```

**Comment by addis144** [comment]
@cturczynskyj - Please open this issue again.  This blocks the ability to move channels between servers with ssl plugin and workstations without it.  See post above.
