### ISSUE TITLE
Broken Autocomplete on 3.7+

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4297]
Autocomplete with local variables is broken. 

Tested in editor.  See screenshot. 

var testStr = '';
var testnum = 1;
var testArr = [];

 test

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4422
Reporter: addis144
Created: 2019-06-12T14:05:37.000-0700

**Comment by rbeckman-nextgen** [comment]
Hi, i experience the exact same problem (3.8). In certain cases it even totally freezes the admin client : this bug is not so minor.
This appears in Java console as soon as autocompletion tries to run : 

Using JRE version 1.8.0_221-b11 Java HotSpot(TM) 64-Bit Server VM
Java home directory = c:\program files\java\jre1.8.0_221
User home directory = C:\Users\mlarcelet
----------------------------------------------------
c:  Clear console window
s:  Dump system properties
----------------------------------------------------
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: org.mozilla.javascript.ast.WhileLoop cannot be cast to org.mozilla.javascript.ast.DoLoop
	at org.fife.rsta.ac.js.ast.parser.JavaScriptAstParser.processDoNode(JavaScriptAstParser.java:412)
	at org.fife.rsta.ac.js.ast.parser.JavaScriptAstParser.iterateNode(JavaScriptAstParser.java:160)
	at org.fife.rsta.ac.js.ast.parser.JavaScriptAstParser.addCodeBlock(JavaScriptAstParser.java:103)
	at org.fife.rsta.ac.js.ast.parser.JavaScriptAstParser.convertAstNodeToCodeBlock(JavaScriptAstParser.java:61)
	at org.fife.rsta.ac.js.SourceCompletionProvider.iterateAstRoot(SourceCompletionProvider.java:423)
	at org.fife.rsta.ac.js.SourceCompletionProvider.getCompletionsImpl(SourceCompletionProvider.java:229)
	at com.mirth.connect.client.ui.components.rsta.ac.js.MirthSourceCompletionProvider.getCompletionsImpl(MirthSourceCompletionProvider.java:54)
	at org.fife.ui.autocomplete.CompletionProviderBase.getCompletions(CompletionProviderBase.java:102)
	at org.fife.ui.autocomplete.LanguageAwareCompletionProvider.getCompletionsImpl(LanguageAwareCompletionProvider.java:157)
	at org.fife.ui.autocomplete.CompletionProviderBase.getCompletions(CompletionProviderBase.java:102)
	at org.fife.ui.autocomplete.AutoCompletion.refreshPopupWindow(AutoCompletion.java:801)
	at org.fife.rsta.ac.js.JavaScriptLanguageSupport$JavaScriptAutoCompletion.refreshPopupWindow(JavaScriptLanguageSupport.java:580)
	at org.fife.ui.autocomplete.AutoCompletion.doCompletion(AutoCompletion.java:287)
	at org.fife.ui.autocomplete.AutoCompletion$AutoActivationListener.actionPerformed(AutoCompletion.java:1279)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


Imported Comment. Original Details:
Author: mlarcelet
Created: 2019-08-28T06:19:06.000-0700
