### ISSUE TITLE
File Writer error on alert

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4357]
Actual:
```
File Writer error
ERROR MESSAGE: Error writing file
java.lang.IllegalArgumentException: Unable to create EvictionPolicy instance of type org.apache.commons.pool2.impl.DefaultEvictionPolicy
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setEvictionPolicyClassName(BaseGenericObjectPool.java:607)
	at org.apache.commons.pool2.impl.GenericObjectPool.setConfig(GenericObjectPool.java:321)
	at org.apache.commons.pool2.impl.GenericObjectPool.<init>(GenericObjectPool.java:117)
	at com.mirth.connect.connectors.file.FileConnector.getConnectionPool(FileConnector.java:292)
	at com.mirth.connect.connectors.file.FileConnector.getConnection(FileConnector.java:185)
	at com.mirth.connect.connectors.file.FileDispatcher.send(FileDispatcher.java:165)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:888)
	at com.mirth.connect.donkey.server.channel.DestinationConnector.process(DestinationConnector.java:518)
	at com.mirth.connect.donkey.server.channel.DestinationChain.doCall(DestinationChain.java:121)
	at com.mirth.connect.donkey.server.channel.DestinationChain.call(DestinationChain.java:63)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1759)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1221)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:1091)
	at com.mirth.connect.server.alert.action.ChannelProtocol.doCustomDispatch(ChannelProtocol.java:63)
	at com.mirth.connect.server.alert.AlertWorker$ActionTask.call(AlertWorker.java:188)
	at com.mirth.connect.server.alert.AlertWorker$ActionTask.call(AlertWorker.java:117)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool2.impl.DefaultEvictionPolicy
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.setEvictionPolicyClassName(BaseGenericObjectPool.java:598)
	... 20 more
```

Expected:
No error

Steps to reproduce:
- Create a channel (I was using an http to s3 channel) ("Test channel")
- Create another channel for errors ("Error channel")
- - Data Types: all RAW
- - Channel source connector (default settings)
- - S3 destination connector
- - - Template: `test`
- Create a new alert
- - Trigger on any error
- - Enable for "Test channel"
- - Write to error channel for action
- - Template: `test`

Notes:
If I open the channel messages and "reprocess" the message in the error channel history, it works. And subsequent alerts also work. But upon server restart, alerts cause the above error.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4482
Reporter: lleblow
Created: 2020-02-26T14:43:25.000-0800

**Comment by rbeckman-nextgen** [comment]
How do I edit this issue? I'd like to add to the "steps to reproduce"

Imported Comment. Original Details:
Author: lleblow
Created: 2020-02-26T14:45:21.000-0800

**Comment by brad-az** [comment]
I am seeing the same issue in 3.10.1.  Can this be reopened?

**Comment by scrumgelist** [comment]
Same issue - Mirth 4.1.1 - cannot seem to find a solution and the manual intervention of resending is less than satisfactory.  Please  advise.
