### ISSUE TITLE
Mirth connect code throws  java.lang.ArrayIndexOutOfBoundsException:  when MSH6 is |^^|

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#4382]
Create an HL7v2.x channel and set the channel reader return to Auto-Generate on Destinations Complete.  
Send in an HL7 message with MSH6  as |^^|.
Send test message to channel.  

You will get the following....

java.lang.Exception: Error generating HL7v2 ACK.
	at com.mirth.connect.plugins.datatypes.hl7v2.HL7v2AutoResponder.generateACK(HL7v2AutoResponder.java:188)
	at com.mirth.connect.plugins.datatypes.hl7v2.HL7v2AutoResponder.getResponse(HL7v2AutoResponder.java:73)
	at com.mirth.connect.donkey.server.channel.ResponseSelector.getResponse(ResponseSelector.java:91)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1236)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:192)
	at com.mirth.connect.server.controllers.DonkeyEngineController.dispatchRawMessage(DonkeyEngineController.java:1091)
	at com.mirth.connect.server.userutil.VMRouter.routeMessageByChannelId(VMRouter.java:104)
	at sun.reflect.GeneratedMethodAccessor128.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1479)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:405)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3508)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:120)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.executeScript(JavaScriptTask.java:150)
	at com.mirth.connect.connectors.js.JavaScriptDispatcher$JavaScriptDispatcherTask.doCall(JavaScriptDispatcher.java:149)
	at com.mirth.connect.connectors.js.JavaScriptDispatcher$JavaScriptDispatcherTask.doCall(JavaScriptDispatcher.java:122)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at com.mirth.connect.plugins.datatypes.hl7v2.HL7v2ACKGenerator.generateAckResponse(HL7v2ACKGenerator.java:111)
	at com.mirth.connect.plugins.datatypes.hl7v2.HL7v2AutoResponder.generateACK(HL7v2AutoResponder.java:183)
	... 25 more

I tried putting... 
message=message.replace("|^^|","||");
...in the pre-processor, but it didn't fix it.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-4507
Reporter: stickybandit
Created: 2020-04-28T14:52:34.000-0700

**Comment by joshmc82** [comment]
Can we re-open this? I ran into this again just today on 3.10.1 (Also tested on 3.12.0)
Example MSH Header:
`MSH|^~\&|OSCAR|Default Facility||^^|20100629112229||^^|||2.6||||`
Impact: The source sender will continue to send the same message over and over because we can't send an Ack. Some systems may have a set number of retry attempts, but that's not a guarantee. 
A side impact here is that it doesn't show these errors when you click on the "ERROR" status box and Search. The only way to find these is to check the "Has Error" box on the Advanced Search.
