### ISSUE TITLE
Launch Administrator from Web Dashboard fails

### ISSUE THREAD

**Issue by Pasayadaan** [nextgenhealthcare/connect#4434]
Installed 3.10
Web Dashboard is visible. Also runs Administrator from desktop app.
But from browser logged into Web Dashboard then selected Launch Administrator throws error
localhost:8443/webadmin/://localhost:/webstart.jnlp?
HTTP ERROR 404 Not Found
URI:	/webadmin/://localhost:/webstart.jnlp
STATUS:	404
MESSAGE:	Not Found
SERVLET:	default

**Comment by kfrancis** [comment]
Same issue here. I think it's because the server is pooched on start:

ERROR 2020-11-24 16:05:20,211 [Main Server Thread] Server: Exception in thread "Main Server Thread" java.lang.NoSuchMethodError: 'void org.eclipse.jetty.server.session.SessionHandler.setSessionCache(org.eclipse.jetty.server.session.SessionCache)'
ERROR 2020-11-24 16:05:20,211 [Main Server Thread] Server: 	at com.mirth.connect.server.MirthWebServer.<init>(MirthWebServer.java:297)
ERROR 2020-11-24 16:05:20,211 [Main Server Thread] Server: 	at com.mirth.connect.server.Mirth.startWebServer(Mirth.java:401)
ERROR 2020-11-24 16:05:20,226 [Main Server Thread] Server: 	at com.mirth.connect.server.Mirth.startup(Mirth.java:281)
ERROR 2020-11-24 16:05:20,226 [Main Server Thread] Server: 	at com.mirth.connect.server.Mirth.run(Mirth.java:162)

**Comment by kfrancis** [comment]
I figured it out in my case, which was that I did the updates out of order and everything in the db was mangled.

**Comment by Mattoje** [comment]
Same problem,
installed 3.10.1, tried on a centos8 with rpm and on an Ubuntu 18.04.5 with the installer.
On both VM the same error:

HTTP ERROR 404 Not Found
URI:    /webadmin/://www.example.com:/webstart.jnlp
STATUS: 404
MESSAGE:        Not Found
SERVLET:        default
Powered by Jetty:// 9.4.21.v20190926

**Comment by pacmano1** [comment]
Why aren't you all using the mirth administrator launcher (the standalone tool from the download page)?

**Comment by Mattoje** [comment]
We are, or at least i am, but a dead link is a bug and i'm reporting it
