### ISSUE TITLE
[BUG] ClassNotFoundException: org.apache.commons.beanutils.DynaBean when importing configmap from CLI

### ISSUE THREAD

**Issue by fridlik** [nextgenhealthcare/connect#4463]
**Describe the bug**
I am not able to import ConfigMap from cli (using `mccommand`) due to the missing libraries.

The problem is caused by 2 missing libraries in `cli-lib` folder:
- commons-beanutils-1.9.3.jar
- commons-text-1.8.jar 

**To Reproduce**
1. Install mirth
2. create a configmap file and save it as /tmp/configmap.properties, e.g. 
    ```.properties
    MyKey = value
    ```
3. connect to mirth using `mccommand`
4. run `importmap /tmp/configmap.properties`

**Expected behavior**
Config map will be imported

**Actual behavior**
the exception is thrown:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mirth.connect.cli.launcher.CommandLineLauncher.main(CommandLineLauncher.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.UnixLauncher.main(UnixLauncher.java:62)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/beanutils/DynaBean
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.sun.proxy.$Proxy45.<clinit>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
	at org.apache.commons.configuration2.builder.fluent.Parameters.createParametersProxy(Parameters.java:306)
	at org.apache.commons.configuration2.builder.fluent.Parameters.properties(Parameters.java:245)
	at com.mirth.connect.client.core.PropertiesConfigurationUtil.getDefaultParameters(PropertiesConfigurationUtil.java:91)
	at com.mirth.connect.client.core.PropertiesConfigurationUtil.createBuilder(PropertiesConfigurationUtil.java:39)
	at com.mirth.connect.client.core.PropertiesConfigurationUtil.create(PropertiesConfigurationUtil.java:52)
	at com.mirth.connect.cli.CommandLineInterface.commandImportMap(CommandLineInterface.java:1401)
	at com.mirth.connect.cli.CommandLineInterface.executeStatement(CommandLineInterface.java:318)
	at com.mirth.connect.cli.CommandLineInterface.runConsole(CommandLineInterface.java:237)
	at com.mirth.connect.cli.CommandLineInterface.runShell(CommandLineInterface.java:200)
	at com.mirth.connect.cli.CommandLineInterface.run(CommandLineInterface.java:164)
	at com.mirth.connect.cli.CommandLineInterface.<init>(CommandLineInterface.java:107)
	... 11 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.beanutils.DynaBean
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 30 more
```

**Environment (please complete the following information):**
 - OS: Centos 7
 - Java 8
 - Connect Version 3.10.1

**Workaround(s)**
There are missing 2 libraries in `cli-lib` folder:
- commons-beanutils-1.9.3.jar
- commons-text-1.8.jar 

I took these libs from `client-lib` folder and it works

**Comment by tonygermano** [comment]
User `@thaddeus.k` in Slack confirmed this same issue. This appears to be related to commit https://github.com/nextgenhealthcare/connect/commit/4ab4078d9f4ca3790387c493015e32a45425f2b8 and the update to `commons-configuration2-2.7`. The [pom file](https://repo1.maven.org/maven2/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.pom) actually lists `commons-text-1.8` and `commons-beanutils-1.9.4` (not 1.9.3) as dependencies.

**Comment by cturczynskyj** [comment]
We do have an internal issue for this already. Your workaround should work for the time being.
