### ISSUE TITLE
[Docs] Save Message before it gets to the Channel

### ISSUE THREAD

**Issue by cldparisi** [nextgenhealthcare/connect#4486]
is it possibile to save message before it gests to the channel?

I need it because in log there are a lot of errors: "Start of message byte (<VT>) not detected"
And I want view the message  

ERROR 2021-03-31 03:32:12,188 [TCP Receiver Thread on CDI IN (ab23da21-2038-435e-9b84-2090e689f3f1) < pool-16-thread-6] com.mirth.connect.connectors.tcp.TcpReceiver: Error receiving message (TCP Listener "Source" on channel ab23da21-2038-435e-9b84-2090e689f3f1).
com.mirth.connect.model.transmission.framemode.FrameStreamHandlerException: Start of message byte (<VT>) not detected. First byte received: G
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:205)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.readBytes(TcpReceiver.java:813)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:620)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:511)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.model.transmission.framemode.FrameStreamHandlerException: Start of message byte (<VT>) not detected. First byte received: G
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:136)
	... 7 more

**Comment by pacmano1** [comment]
I'd think in that case you would fire up a network sniffer to catch the raw message before it even hits mirth.

**Comment by cturczynskyj** [comment]
It sounds like some messages are formatted incorrectly and are missing the start byte that defines the beginning of a message. At this point, there isn't a way to save the message because the message is defined by the start and end bytes but we don't even have those. It could be that your channel or whoever is sending to your channel has configured the start and end bytes incorrectly.

To add, @pacmano1 has a good suggestion which I think would help you troubleshoot.

If you have more questions about troubleshooting this your best bet for assistance would be the [forums](https://forums.mirthproject.io/) or [slack channel](https://forums.mirthproject.io/forum/mirth-connect/support/15720-join-the-mirth-connect-slack-channel).
