### ISSUE TITLE
[BUG] DatabaseConnectionFactory.createDatabaseConnection with a custom driver fails on Java9+

### ISSUE THREAD

**Issue by is-simon** [nextgenhealthcare/connect#4587]
**Describe the bug**
When using a custom driver, the DatabaseConnectionFactory.createDatabaseConnection fails but only when NextGen Connect runs on a Java9+ installation (it works on Java8). This was tested using a custom oracle JDBC driver. Note that we did configured the VM options properly according to [this guide](https://github.com/nextgenhealthcare/connect#5-running-nextgen-connect-in-java-9-or-greater) 

1. In the settings, create a new resource with a custom driver (for our tests, we used the oracle jdbc driver that comes with connect 3.5.1 and made a resource with it in a connect 3.10.0 installation).
2. Create a new channel with a database reader as source connector.
2. Go to the Summary tab / Set Dependencies / Library Resources Tab, be sure that only the resource with the custom driver is checked.
3. Set the Database Reader "Use JavaScript" to true
4. Use the following script:

```
var dbConn;
try {
	dbConn = DatabaseConnectionFactory.createDatabaseConnection('oracle.jdbc.OracleDriver','jdbc:oracle:thin:@host:port:dbname','user','password');
	var result = dbConn.executeCachedQuery('select sysdate from dual');
	return result;
} finally {
	if (dbConn) { 
		dbConn.close();
	}
}
```

**Expected behavior**
Should work using the usual way with Java 9+ the same as with Java 8 (the generated template doesn't work). If we restart the same Connect installation using Java 8, the code above works properly.

**Actual behavior**
An exception is thrown:
```
[2021-06-09 12:05:27,866]  ERROR  (com.mirth.connect.connectors.jdbc.DatabaseReceiverScript:123): An error occurred while polling for messages, retrying after 10000 ms...
com.mirth.connect.server.util.javascript.JavaScriptExecutorException: java.lang.NoClassDefFoundError: java/sql/Driver
	at com.mirth.connect.server.util.javascript.JavaScriptUtil.execute(JavaScriptUtil.java:75)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiverScript.poll(DatabaseReceiverScript.java:104)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiver.poll(DatabaseReceiver.java:134)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)Caused by: java.lang.NoClassDefFoundError: java/sql/Driver
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.mirth.connect.connectors.jdbc.CustomDriver.<init>(CustomDriver.java:40)
	at com.mirth.connect.server.userutil.DatabaseConnectionFactory.initializeDriverAndGetInfo(DatabaseConnectionFactory.java:145)
	at com.mirth.connect.server.userutil.DatabaseConnectionFactory.getCustomDriverInfo(DatabaseConnectionFactory.java:167)
	at com.mirth.connect.server.userutil.DatabaseConnectionFactory.createDatabaseConnection(DatabaseConnectionFactory.java:54)
	at jdk.internal.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1669)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1009)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.executeScript(JavaScriptTask.java:150)
	at com.mirth.connect.server.util.javascript.JavaScriptUtil.executeScript(JavaScriptUtil.java:542)
	at com.mirth.connect.connectors.jdbc.DatabaseReceiverScript$SelectTask.doCall(DatabaseReceiverScript.java:177)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:113)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)Caused by: java.lang.ClassNotFoundException: java.sql.Driver
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 43 more
```

**Environment:**
 - OS: Windows
 - Java OpenJDK 11 (works on Oracle JDK 8 202)
 - Connect Version 3.10.0

**Workaround(s)**
We found a workaround here:
https://forums.mirthproject.io/forum/mirth-connect/support/18551-mirth-3-8-openjdk11-and-ms-sql-jdbc?p=104017#post104017
which is to create the database connection this way:
```
var dbConn;
try {
	var driver = new com.mirth.connect.connectors.jdbc.CustomDriver(java.lang.Thread.currentThread().getContextClassLoader(), "oracle.jdbc.OracleDriver");
	var info = new java.util.Properties();
	info.setProperty("user", "user");
	info.setProperty("password", "password");
	var dbConn = new com.mirth.connect.server.userutil.DatabaseConnection(driver, "jdbc:oracle:thin:@host:port:dbname", info);
	var result = dbConn.executeCachedQuery('select sysdate from dual');
	return result;
} finally {
	if (dbConn) { 
		dbConn.close();
	}
}
```

Note that we didn't found any `--add-modules` VM options that could made that code works.

By the way, by default, NextGen is using `oracle.jdbc.driver.OracleDriver` instead of `oracle.jdbc.OracleDriver` for Oracle driver. The first one is deprecated, see [here](https://stackoverflow.com/a/6202721)

**Comment by cturczynskyj** [comment]
Added an internal issue to add the ability to use the newer Oracle package.
