### ISSUE TITLE
Can't start channels that use the file reader connector type

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#486]
I have trunk revision 2624 checked out and I can't seem to start or deploy channels that uses the file reader connector. This used to work before.

The following is the error from the event log.

org.mule.umo.lifecycle.InitialisationException: Failed to create "Message Receiver" with "com.webreach.mirth.connectors.file.FileMessageReceiver"
	at com.webreach.mirth.connectors.file.FileConnector.createReceiver(FileConnector.java:195)
	at org.mule.providers.AbstractConnector.registerListener(AbstractConnector.java:514)
	at org.mule.impl.model.AbstractModel.registerListeners(AbstractModel.java:221)
	at org.mule.impl.model.AbstractModel.start(AbstractModel.java:353)
	at org.mule.MuleManager.start(MuleManager.java:730)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:207)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:200)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:171)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:124)
Caused by: org.mule.providers.service.ConnectorServiceException: Failed to create "Message Receiver" with "file"
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageReceiver(ConnectorServiceDescriptor.java:321)
	at com.webreach.mirth.connectors.file.FileConnector.createReceiver(FileConnector.java:192)
	... 9 more
Caused by: java.lang.NullPointerException
	at org.mule.providers.TemplateValueReplacer.replaceValuesFromGlobal(TemplateValueReplacer.java:69)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.<init>(FileMessageReceiver.java:82)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:271)
	at org.mule.util.ClassHelper.instanciateClass(ClassHelper.java:278)
	at org.mule.providers.service.ConnectorServiceDescriptor.createMessageReceiver(ConnectorServiceDescriptor.java:319)
	... 10 more

{}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-476
Reporter: nilesh
Created: 2007-08-09T17:40:50.000-0700

**Comment by rbeckman-nextgen** [comment]
It looks like changing line 69 on TemplateValueReplacer.jave to 
if (template == null || template.indexOf('$') == -1){
should fix this issue.

Imported Comment. Original Details:
Author: nilesh
Created: 2007-08-09T17:59:51.000-0700
