### ISSUE TITLE
[BUG]  thread "JavaFX Application Thread" netscape.javascript.JSException: Invalid function reference

### ISSUE THREAD

**Issue by linxd** [nextgenhealthcare/connect#5017]
**Describe the bug**
startup management client ,in console got error: 
  thread "JavaFX Application Thread" netscape.javascript.JSException: Invalid function reference

**To Reproduce**
just start up 3.12 development version
 Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: Invalid function reference
	at com.sun.webkit.dom.JSObject.callImpl(Native Method)
	at com.sun.webkit.dom.JSObject.call(JSObject.java:125)
	at com.mirth.connect.client.ui.components.tag.MirthTagWebBrowser$3.run(MirthTagWebBrowser.java:162)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:185)
	at java.lang.Thread.run(Unknown Source)

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happens.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Linux (CentOS), Windows 10, MacOS]
 - Java Distribution/Version [e.g. oracke Java 8 (311)]
 - Connect Version [e.g. 3.12.]

**Workaround(s)**
Are there one or more workarounds for this issue currently?

**Additional context**

**Comment by jonbartels** [comment]
You really need to complete this section for this issue report - "Environment (please complete the following information)"

I suspect you need a JDK with JavaFX. 

https://github.com/nextgenhealthcare/connect/search?q=javafx&type=discussions turns up some relevant information.
