### ISSUE TITLE
Trailing linefeed in messages causes Mirth to throw exception and stop processing

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#510]
Our system is Linux based and our HL7 system stores queued messages in text files.  On Linux/Unix it's customary to have trailing linefeeds at the end of text files, so the queues messages have these (\n) (aka. ASCII 0x0a).

When we send these files to Mirth we see Mirth can parse the message fine but then the thread terminates with the following thrown exception:

INFO  2007-08-23 11:16:39,933: MSH|^~\&|LAB|CCF|||20040920080937||ORM^O01|42640000009|P|2.1|^MPID|||56797971||RESULTSREVIEW^TESTPATIENT^||19650525|M||||||||||56797971|^MPV1||O|UNK
O^|||||^MORC|CA|30725991^EPIC_EC||||||||||||||^Duplicate|^MOBR||30725991^EPIC_EC||CBCDIF^CBC and Differential|||200409200805|||||||L|^|00593^||||M10274|UNKO||||X||^ONCE^^200409200
805^^|^^|
ERROR 2007-08-23 11:16:40,016: Bytes received violate the MLLP: no start of message indicator received.

ERROR 2007-08-23 11:16:40,019: Caught exception in Exception Strategy for: MessageSink: java.io.IOException: Message violates the minimal lower layer protocol: no start of message
 indicator received
java.io.IOException: Message violates the minimal lower layer protocol: no start of message indicator received
        at com.webreach.mirth.connectors.mllp.protocols.LlpProtocol.readLLP(LlpProtocol.java:138)
        at com.webreach.mirth.connectors.mllp.protocols.LlpProtocol.read(LlpProtocol.java:176)
        at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:333)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Thread.java:619)

It looks like Mirth is parsing the message fine.  When it hits the EOM of the message it sees that there are still bytes in the stream (namely our \n) and it expects that to be another message.  So it scans for the SOM character.  However, it runs into the end of the stream before it gets the SOM.  So it throws an exception saying it cannot find the SOM.  All processing on the channel seems to stop.

See HL7 Implementation Guide (C.2.4 Responding System Processing):

Responding System Processing. The responding system follows these steps:
  1. (Optional) Perform a listen function if required by the environment.
  2. Receive the block that contains the initial message.
     To receive a block:
          a) Ignore all incoming characters until a Start Block character is received. 
              Any time another Start Block character is received before the end of a block, 
              ignore all previous characters. Receive characters until <EB> <CR> is 
              recognized. This is the end of the block.
          b) If a block is received that does not have the proper:
                 1) Block Format,
                 2) Checksum (xxx),
                 3) Block Size (ccccc) or
                 4) Has too many characters to be received in a single block, construct 
                      and send a NAK block (type t = 'N') that includes the appropriate reason 
                      code in the data field.
           c) If the receive block is valid, go to the next step.
  3. Give the initiation message to the application.
  4. Application creates a response and makes a block.
  5. Send the response message.
  6. Disconnect if required.

Section 2a) is the "reading" part.  Mirth is now correctly ignoring characters at the start of our message, but by the same logic it should also be ignoring all characters after EOM until another SOM is found.  Strictly speaking, I don't think an error should be thrown at all because when Mirth hits the end of stream it hasn't read a SOM yet, so it shouldn't even consider itself to be potentially inside a message at all.

This behaviour didn't happen in Mirth 1.5.  It was only after changes were made to address MIRTH-413.

I believe this is the code that's choking on the trailing linefeed:

while ((c != START_MESSAGE) && (c != -1)) {
			try {
				c = myReader.read();
			} catch (Exception e) {
				c = -1;
			}
		}
		
		if (c == -1) {  // End of stream reached without start of message character.
			String message = myReader.toString();
			logger.error("Bytes received violate the MLLP: no start of message indicator received.\r\n" + message);
			throw new IOException("Message violates the minimal lower layer protocol: no start of message indicator received");
		}

See, since only <LF> in in the stream it will keep reading until MyReader.read() throws an exception, which is caught and c is set to -1.  Then the "if" condition below is satisfied and Mirth throws the exception.

This happens even when I turn off Strict LLP, so we don't really have a workaround for it.  So it's crucial we have resolution before we can deploy Mirth.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-500
Reporter: seamims
Created: 2007-08-23T13:42:57.000-0700

**Comment by rbeckman-nextgen** [comment]
Updated LLP protocol to not throw IOException when in-stream characters are detected outside of SOM and EOM chars.
Updated logging to set an info statement rather than error or warn.

Imported Comment. Original Details:
Author: chrisl
Created: 2007-08-28T15:10:43.000-0700
