### ISSUE TITLE
[BUG] Advanced Clustering Plugin generates database errors

### ISSUE THREAD

**Issue by mcswaip1** [nextgenhealthcare/connect#5246]
**Describe the bug**

When using the Advanced Clustering Plugin, we consistently get the following error (that never seems to go away):

> [2022-06-17 12:32:27,127]  ERROR  (com.mirth.connect.plugins.clusteringadvanced.server.o:196): An error occurred while attempting to update the cluster global map.
java.sql.BatchUpdateException: Violation of PRIMARY KEY constraint 'M_CLUSTER_GLOBAL_MAPS_PKEY'. Cannot insert duplicate key in object 'dbo.M_CLUSTER_GLOBAL_MAPS'. The duplicate key value is (5c9457c6-5a23-4c27-8f46-7c407c0ef0d5, 2e227e16-5613-4d27-a70e-4b96087bcf93, timeZoneId).
	at net.sourceforge.jtds.jdbc.JtdsStatement.executeBatch(JtdsStatement.java:1069)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at com.mirth.connect.plugins.clustering.server.database.Statement.executeBatch(SourceFile:203)
	at com.mirth.connect.plugins.clusteringadvanced.server.o.a(SourceFile:165)
	at com.mirth.connect.plugins.clusteringadvanced.server.q.execute(SourceFile:145)
	at com.mirth.connect.plugins.clustering.server.core.NodeUpdater$NodeUpdateTaskTask.run(SourceFile:161)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

The value that the error is mentioning has not changed so really there should be no issue.

**To Reproduce**
Setup steps (if required). Example:
1. Using Mirth 4.0.0
2. Load several channels that all use global channel maps

1. Send an HL7 message to one of the channels
2. See error

**Expected behavior**
If the value has not changed no error should occur.

**Actual behavior**
The error occurs and floods the logs.

**Screenshots**
![image](https://user-images.githubusercontent.com/20447369/174299878-bd975b56-fe08-4bc6-bf8c-3f76ed70f1fa.png)
![image](https://user-images.githubusercontent.com/20447369/174299978-0f61e363-7ec0-4a67-8ec3-811136e04496.png)

**Environment (please complete the following information):**
 - OS: Linux in container under kubernetes
 - Java Distribution/Version: OpenJDK 11, Java 8 (201)
 - Connect Version: 4.0.0

**Workaround(s)**
No workaround

**Additional context**
This is occurring in a Kubernetes cluster with 3 nodes.

**Comment by RunnenLate** [comment]
I see this is closed and hopefully fixed in the next version, but as a workaround, ensure that all globalMap values being added using the same case.  For example, if adding globalMap.put('**v**ariable', value) and then the call is made globalMap.put('**V**ariable', value) this will trigger the error.  Use the .toUpperCase() or .toLowerCase() when adding the globalMap name to avoid this error.

**Comment by tonygermano** [comment]
From slack conversation, this seems to be an issue for databases that are set up to use case insensitive collation by default (especially SQL Server,) which causes the unique constraint to also be case insensitive, when this should not be the case.

A potential fix (at least for SQL Server) is to set the collation explicitly on the column when creating the table to one which is case sensitive.

**Comment by RunnenLate** [comment]
I can confirm this does fix the issue 

updating the collation on that Map_Keys column  on the M_CLUSTER_GLOBAL_MAPS table and its dependencies from SQL_Latin1_General_CP1_CI_AS to SQL_Latin1_General_CP1_CS_AS

Any new value will not be visible within the Global Maps tab within Connect but it is still accessible via the GlobalMaps function

![image](https://user-images.githubusercontent.com/2079191/180090092-5080d204-a325-41ee-bc70-0f5e26482b2c.png)
![image](https://user-images.githubusercontent.com/2079191/180090406-f10abb8d-b342-47e5-8e62-cb813bc870e5.png)
![image](https://user-images.githubusercontent.com/2079191/180090648-386b1100-e302-4775-bed3-11dba248f58a.png)
![image](https://user-images.githubusercontent.com/2079191/180090366-a2355a94-7f30-44b8-afb2-0288929ccbef.png)
