### ISSUE TITLE
[BUG] Client Error when select Clear Statistics from Dashboard

### ISSUE THREAD

**Issue by pladesma** [nextgenhealthcare/connect#5309]
**Describe the bug**
Getting Exception in Client Java Console as well as Error pop-up in Administrator when select to “Clear Statistics”

**To Reproduce**

1. Install Connect build mirthconnect-4.0.1.b2745-unix.tar.gz or later
2. Create a test channel (HTTP Sender & Listener) & Deploy
3. Send a message to test channel to generate statistics
4. From Dashboard > select test channel > select "Clear Statistics" > getting Error
5. Using API endpoint to clear statistics also failed with status 500

**Expected behavior**
Statistics are cleared with no errors occurring.

**Actual behavior**
The following error appears in the Administrator client and the statistics aren't cleared:

```
Method failed: HTTP/1.1 500 Server Error
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 500 Server Error
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:532)
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:256)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:166)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:379)
at com.sun.proxy.$Proxy66.clearStatistics(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:269)
at com.sun.proxy.$Proxy66.clearStatistics(Unknown Source)
at com.mirth.connect.client.core.Client.clearStatistics(Client.java:1608)
at com.mirth.connect.client.ui.Frame$25.doInBackground(Frame.java:3857)
at com.mirth.connect.client.ui.Frame$25.doInBackground(Frame.java:3853)
at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at javax.swing.SwingWorker.run(SwingWorker.java:334)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.mirth.connect.client.core.EntityException: {
"servlet":"org.glassfish.jersey.servlet.ServletContainer-34922865",
"message":"Request failed.",
"url":"/api/4.0.1/channels/_clearStatistics",
"status":"500"
}
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:529)
... 27 more
```

Also the following endpoint is failing status 500 (see more details in the comments section below)

[https://localhost:8444/api/#/Channel Statistics/clearStatistics](https://localhost:8444/api/#/Channel%20Statistics/clearStatistics)

`curl -X POST "https://localhost:8444/api/channels/_clearStatistics?received=true&filtered=true&sent=true&error=true" -H "accept: application/xml" -H "Content-Type: application/json" -H "X-Requested-With: OpenAPI" -d "{ \"map\": { \"entry\": { \"string\": \"8057c7a3-7c6c-4500-99c0-1a0c890a9993\", \"list\": { \"null\": null, \"int\": [ 0, 1 ] } } }}"`

**Environment (please complete the following information):**
 - OS: MacOS, Linux, Windows
 - Java Distribution/Version: Oracle JDK 8
 - Connect Version 4.0.1

**Comment by pladesma** [comment]
Just a note that this defect never actually made it into a release, so it shouldn't have ever affected anyone.
