### ISSUE TITLE
File Reader/Writer in SMB mode encounters IllegalAccessError in 4.1.0

### ISSUE THREAD

**Issue by narupley** [nextgenhealthcare/connect#5327]
**Describe the bug**
When using SMB on File Connectors in 4.1.0, this error may be encountered:
```
ERROR 2022-07-31 11:24:06.016 com.mirth.connect.connectors.file.FileReceiver: Error polling in channel: d8f03730-21f1-49d8-8bb3-676efe40051f
java.lang.IllegalAccessError: failed to access class org.bouncycastle.asn1.DEROutputStream from class jcifs.spnego.NegTokenInit (org.bouncycastle.asn1.DEROutputStream and jcifs.spnego.NegTokenInit are in unnamed module of loader java.net.URLClassLoader @18a136ac)
    at jcifs.spnego.NegTokenInit.toByteArray(NegTokenInit.java:158) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SpnegoContext.initSecContext(SpnegoContext.java:207) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbSessionImpl.createToken(SmbSessionImpl.java:656) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbSessionImpl.sessionSetupSMB2(SmbSessionImpl.java:538) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbSessionImpl.sessionSetup(SmbSessionImpl.java:483) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:369) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbSessionImpl.send(SmbSessionImpl.java:347) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbTreeImpl.treeConnect(SmbTreeImpl.java:611) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbTreeConnection.connectTree(SmbTreeConnection.java:614) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:568) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:551) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279) ~[jcifs-ng-2.1.3.jar:?]
    at jcifs.smb.SmbFile.listFiles(SmbFile.java:1256) ~[jcifs-ng-2.1.3.jar:?]
    at com.mirth.connect.connectors.file.filesystems.SmbFileConnection.listFiles(SmbFileConnection.java:207) ~[file-server.jar:?]
    at com.mirth.connect.connectors.file.FileReceiver.listFiles(FileReceiver.java:647) ~[file-server.jar:?]
    at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:239) ~[file-server.jar:?]
    at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49) ~[donkey-server.jar:?]
    at org.quartz.core.JobRunShell.run(JobRunShell.java:213) ~[quartz-all-2.1.7.jar:?]
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557) ~[quartz-all-2.1.7.jar:?]
```

It looks like this is a known issue in the third-party library we're using for SMB, jcifs-ng. We just need to update to the latest version there.

**Workaround(s)**
The following applies only to version 4.1.0:
* Replace extensions/file/lib/jcifs-ng-2.1.3.jar with the attached jcifs-ng-2.1.8.jar
* Replace extensions/file/file-server.jar with the attached file-server.jar
* Update both source.xml and destination.xml in extensions/file to point to jcifs-ng-2.1.8.jar
* Restart MC

[jcifs-ng-2.1.8.jar.zip](https://github.com/nextgenhealthcare/connect/files/9252952/jcifs-ng-2.1.8.jar.zip)
[file-server.jar.zip](https://github.com/nextgenhealthcare/connect/files/9252966/file-server.jar.zip)

**Comment by pacmano1** [comment]
@twest-mirthconnect , the release notes for 4.1.0 should likely have an Errata section pointing to this issue.

**Comment by tonygermano** [comment]
Also, the fix should be pushed to github so people can build it themselves.

**Comment by mjhca** [comment]
Also affects client-lib as it contains jcifs-ng-2.1.3.jar.  But you cannot just replace the jar file as then the administrator client fails to launch with 
`com.mirth.connect.client.launcher.q: java.lang.Exception: Error verifying entry "META-INF/MANIFEST.MF" in JAR file jcifs-ng-2.1.8.jar`

**Comment by mjhca** [comment]
This fix also seems to introduce a new issue for the file reader with SMB2, possibly because the jcifs-ng-2.1.8.jar is unsigned?

Specifically:
` java.lang.SecurityException: class "jcifs.internal.smb2.nego.NegotiateContextResponse"'s signer information does not match signer information of other classes in the same package`

Full trace:

`[2022-08-22 08:42:00.165]  ERROR  (com.mirth.connect.connectors.file.FileReceiver:27): Error polling in channel: 9659baca-94e6-44b0-a529-6b405b9b65ef
com.mirth.connect.connectors.file.FileConnectorException: Error listing files in dir [/Export/] for pattern [\d{10}.pdf]
	at com.mirth.connect.connectors.file.filesystems.SmbFileConnection.listFiles(SmbFileConnection.java:223)
	at com.mirth.connect.connectors.file.FileReceiver.listFiles(FileReceiver.java:647)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:239)
	at com.mirth.connect.donkey.server.channel.PollConnectorJob.execute(PollConnectorJob.java:49)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)Caused by: jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/10.0.1.60
	at jcifs.smb.SmbTransportImpl.ensureConnected(SmbTransportImpl.java:689)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:220)
	at jcifs.smb.SmbTransportPoolImpl.getSmbTransport(SmbTransportPoolImpl.java:48)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:565)
	at jcifs.smb.SmbTreeConnection.connectHost(SmbTreeConnection.java:489)
	at jcifs.smb.SmbTreeConnection.connect(SmbTreeConnection.java:465)
	at jcifs.smb.SmbTreeConnection.connectWrapException(SmbTreeConnection.java:426)
	at jcifs.smb.SmbFile.ensureTreeConnected(SmbFile.java:559)
	at jcifs.smb.SmbEnumerationUtil.doEnum(SmbEnumerationUtil.java:221)
	at jcifs.smb.SmbEnumerationUtil.listFiles(SmbEnumerationUtil.java:279)
	at jcifs.smb.SmbFile.listFiles(SmbFile.java:1270)
	at com.mirth.connect.connectors.file.filesystems.SmbFileConnection.listFiles(SmbFileConnection.java:207)
	... 5 moreCaused by: jcifs.util.transport.TransportException: java.lang.SecurityException: class "jcifs.internal.smb2.nego.NegotiateContextResponse"'s signer information does not match signer information of other classes in the same package
	at jcifs.util.transport.Transport.run(Transport.java:769)
	at java.base/java.lang.Thread.run(Thread.java:832)Caused by: java.lang.SecurityException: class "jcifs.internal.smb2.nego.NegotiateContextResponse"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:514)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:422)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:416)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:415)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at jcifs.smb.SmbTransportImpl.negotiate(SmbTransportImpl.java:530)
	at jcifs.smb.SmbTransportImpl.doConnect(SmbTransportImpl.java:706)
	at jcifs.util.transport.Transport.run(Transport.java:742)
	... 1 more`
