### ISSUE TITLE
[BUG] Can't edit user with different country as admin

### ISSUE THREAD

**Issue by swobspace** [nextgenhealthcare/connect#5329]
**Describe the bug**
With version 4.1.0 I can create users, but if the country differs accidently from the admin user, the user is not longer editable. So no correction is possible, only to delete and recreate the user with the same country as the admin user.

**To Reproduce**
1. Fresh 4.1.0 installation
2. Set Country for your admin user
3. add a new new user with a different country
4. try right-mouse-click and edit user -> won't work
5. create a user with the same country as the admin user
6. try to edit the user -> works as expected.

**Expected behavior**
Each user should be editable.

**Actual behavior**
Only user with the same country are editable

**Environment (please complete the following information):**
- Windows 2016 Server
- Adoptium OpenJDK17U-jdk_x64_windows_hotspot_17.0.4_8
- Postgres 14.4
- mirth connect 4.1.0

**Workaround(s)**
Delete the user and recreate it with the correct country.

**Comment by jonbartels** [comment]
I tried this on my local 4.1.0 installation.

My admin user was in the US.
I created a user in Vietnam.
I was able to edit the user. 

I think I followed the right steps. Can you post a video showing the process?
Please launch MC with the Console enabled and capture any errors there. Anything in `mirth.log`?

**Comment by swobspace** [comment]
I can create and edit a user with country Vietnam too. My admin user has country 'Germany', a user with country 'United States' produces the following error on trying edit. There is no other output from the Mirth Administrator. Just choose 'edit' and no reaction. Except for the error output in the console. 

```
Using JRE version 1.8.0_181-b13 Java HotSpot(TM) 64-Bit Server VM
Java home directory = /opt/mirth-administrator-launcher/jre
User home directory = /home/wob
----------------------------------------------------
c:  Clear console window
s:  Dump system properties
----------------------------------------------------
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mirth.connect.client.ui.UserEditPanel.countryActionPerformed(UserEditPanel.java:540)
	at com.mirth.connect.client.ui.UserEditPanel.access$600(UserEditPanel.java:46)
	at com.mirth.connect.client.ui.UserEditPanel$7.actionPerformed(UserEditPanel.java:378)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at com.mirth.connect.client.ui.UserEditPanel.setUser(UserEditPanel.java:132)
	at com.mirth.connect.client.ui.UserDialog.<init>(UserDialog.java:44)
	at com.mirth.connect.client.ui.Frame.doEditUser(Frame.java:2808)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at java.beans.EventHandler.invokeInternal(EventHandler.java:482)
	at java.beans.EventHandler.access$000(EventHandler.java:279)
	at java.beans.EventHandler$1.run(EventHandler.java:430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.beans.EventHandler.invoke(EventHandler.java:428)
	at com.sun.proxy.$Proxy60.actionPerformed(Unknown Source)
	at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.mirth.connect.client.ui.UserEditPanel.countryActionPerformed(UserEditPanel.java:540)
	at com.mirth.connect.client.ui.UserEditPanel.access$600(UserEditPanel.java:46)
	at com.mirth.connect.client.ui.UserEditPanel$7.actionPerformed(UserEditPanel.java:378)
	at javax.swing.JComboBox.fireActionEvent(JComboBox.java:1258)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:586)
	at com.mirth.connect.client.ui.UserEditPanel.setUser(UserEditPanel.java:132)
	at com.mirth.connect.client.ui.UserDialog.<init>(UserDialog.java:44)
	at com.mirth.connect.client.ui.Frame.doEditUser(Frame.java:2808)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at java.beans.EventHandler.invokeInternal(EventHandler.java:482)
	at java.beans.EventHandler.access$000(EventHandler.java:279)
	at java.beans.EventHandler$1.run(EventHandler.java:430)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.beans.EventHandler.invoke(EventHandler.java:428)
	at com.sun.proxy.$Proxy60.actionPerformed(Unknown Source)
	at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jonbartels** [comment]
The error is coming from this line:
https://github.com/nextgenhealthcare/connect/blob/0974c6ad4d6fc683d544f6f23da0def551812ecc/client/src/com/mirth/connect/client/ui/UserEditPanel.java#L540

**Comment by swobspace** [comment]
Hmmm, both user (Vietnam and United States) have an empty phone number. The first user is editable, but not the second.

**Comment by jonbartels** [comment]
I logged out of MC 4.1.0 so I can't test but I wonder if the empty phone is treated as empty-string or null.

What this line is trying to do is put the phone number, if given, into the localized format. If it can't get a phone number or a country then the line will fail.

**Comment by swobspace** [comment]
Okay. Since I have no needs for users with country 'United States' I will delete the problematic user and recreate it with the correct country. I'm closing this issue. Feel free to reopen it if anybody triggers the same problem.

**Comment by jonbartels** [comment]
This could be related to https://github.com/nextgenhealthcare/connect/discussions/5321

**Comment by tonygermano** [comment]
Country field was added in 4.1.0. User from a prior version wouldn't have one. Also, phone was not a required field prior to 4.1.0.

https://github.com/nextgenhealthcare/connect/commit/612f2422edea6b919268dc27e0c60b87a3f0f8e2
