### ISSUE TITLE
After adding a Channel when we click on 'Deploy All' and go to Dashboard page, it does not display any existing (enabled) channels

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#535]
Following was found in the 
1.) Mirth.log FILE: 

WARN  2007-09-07 19:37:12,736 [SocketListener1-1] org.mortbay.jetty.context./: /webstart.jnlp?time=1189174025487: 
java.lang.NullPointerException
	at com.webreach.mirth.server.servlets.WebStartServlet.doGet(WebStartServlet.java:126)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:604)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.mortbay.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:666)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
	at org.mortbay.http.HttpServer.service(HttpServer.java:909)
	at org.mortbay.http.HttpConnection.service(HttpConnection.java:816)
	at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:982)
	at org.mortbay.http.HttpConnection.handle(HttpConnection.java:833)
	at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:244)
	at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
------------------------

2.) wrapper.log FILE: 

INFO   ]( jvm 2    | 2007/09/07 19:36:04 | WARN  2007-09-07 19:36:04,710 [Thread-0) com.webreach.mirth.server.Mirth: Error deploying channels.
INFO   | jvm 2    | 2007/09/07 19:36:04 | org.mule.config.ConfigurationException: Failed to parse configuration resource "C:\Program Files\Mirth\conf\mule-config.xml" (org.mule.config.ConfigurationException)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:196)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:229)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:186)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
INFO   | jvm 2    | 2007/09/07 19:36:04 | Caused by: org.mule.config.ConfigurationException: Failed to parse configuration resource "C:\Program Files\Mirth\conf\mule-config.xml"
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:121)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	... 3 more
INFO   | jvm 2    | 2007/09/07 19:36:04 | Caused by: org.mule.umo.lifecycle.InitialisationException: Initialisation Failure: missing ; before statement (beee8f47-0b99-4cb2-a103-486a8e87b2da#3)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2919)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.commons.digester.Digester.createSAXException(Digester.java:2945)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.commons.digester.Digester.endElement(Digester.java:1133)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.apache.commons.digester.Digester.parse(Digester.java:1685)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
INFO   | jvm 2    | 2007/09/07 19:36:04 | 	... 5 more
STATUS | wrapper  | 2007/09/07 19:36:51 | <-- Wrapper Stopped
STATUS | wrapper  | 2007/09/07 19:36:59 | --> Wrapper Started as Service
STATUS | wrapper  | 2007/09/07 19:36:59 | Launching a JVM...
INFO   | jvm 1    | 2007/09/07 19:37:01 | Wrapper (Version 3.2.1) http://wrapper.tanukisoftware.org
INFO   | jvm 1    | 2007/09/07 19:37:01 | 
INFO   | jvm 1    | 2007/09/07 19:37:12 | WARN  2007-09-07 19:37:12,736 [SocketListener1-1] org.mortbay.jetty.context./: /webstart.jnlp?time=1189174025487: 
INFO   | jvm 1    | 2007/09/07 19:37:12 | java.lang.NullPointerException
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at com.webreach.mirth.server.servlets.WebStartServlet.doGet(WebStartServlet.java:126)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:604)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:666)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.http.HttpServer.service(HttpServer.java:909)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.http.HttpConnection.service(HttpConnection.java:816)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:982)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.http.HttpConnection.handle(HttpConnection.java:833)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:244)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
INFO   | jvm 1    | 2007/09/07 19:37:12 | 	at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
INFO   | jvm 1    | 2007/09/07 19:37:28 | Mirth 1.6.1.2750 (August 29, 2007) server successfully started: Fri Sep 07 19:37:28 IST 2007
INFO   | jvm 1    | 2007/09/07 19:37:28 | This product includes software developed by SymphonySoft Limited (http://www.symphonysoft.com) and its contributors.
INFO   | jvm 1    | 2007/09/07 19:37:28 | Running Java 1.6.0_02 on Windows XP (5.1, x86)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-527
Reporter: mac_3785
Created: 2007-09-07T13:08:42.000-0700

**Comment by rbeckman-nextgen** [comment]
You have a Javascript error in your code: Caused by: org.mule.umo.lifecycle.InitialisationException: Initialisation Failure: missing ; before statement (beee8f47-0b99-4cb2-a103-486a8e87b2da#3) 


Imported Comment. Original Details:
Author: chrisl
Created: 2007-09-07T15:13:46.000-0700
