### ISSUE TITLE
[BUG] Issue with Tiff conversion using jai_imageio.jar

### ISSUE THREAD

**Issue by RunnenLate** [nextgenhealthcare/connect#5350]
**Describe the bug**
within the jai_imageio.jar file when trying to read() a tiff file the following class is called when trying to decompress `TIFFCodecLibFaxDecompressor`  This class is trying to import libraries that are not included within Mirth
```
import com.sun.medialib.codec.g3fax.Decoder;
import com.sun.medialib.codec.g4fax.Decoder;
```

```
      } else if (compression == 4) {
        try {
          this.decompressor = new TIFFCodecLibFaxDecompressor(compression);
        } catch (RuntimeException re) {}
        if (this.decompressor == null)
          this.decompressor = new TIFFFaxDecompressor(); 
      } else if (compression == 3) {
        try {
          this.decompressor = new TIFFCodecLibFaxDecompressor(compression);
        } catch (RuntimeException re) {}
  ```      

This is causing an error every time a tiff conversion is trying to occur.  

```JavaScript Writer error
ERROR MESSAGE: Error evaluating JavaScript Writer
java.lang.NoClassDefFoundError: com/sun/medialib/codec/g3fax/Decoder
	at com.sun.media.imageioimpl.plugins.tiff.TIFFImageReader.read(TIFFImageReader.java:913)
	at javax.imageio.ImageIO.read(ImageIO.java:1448)
	at javax.imageio.ImageIO.read(ImageIO.java:1352)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226)
	at org.mozilla.javascript.BaseFunction.construct(BaseFunction.java:361)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1713)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1009)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.executeScript(JavaScriptTask.java:150)
	at com.mirth.connect.connectors.js.JavaScriptDispatcher$JavaScriptDispatcherTask.doCall(JavaScriptDispatcher.java:230)
	at com.mirth.connect.connectors.js.JavaScriptDispatcher$JavaScriptDispatcherTask.doCall(JavaScriptDispatcher.java:190)
	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:113)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.sun.medialib.codec.g3fax.Decoder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more
```

**To Reproduce**

1. Create a Channel and use the following code to read in a base64 encoded Tiff Image.  This will cause the error to be thrown.  
```
var tiffBytes = org.apache.commons.codec.binary.Base64.decodeBase64(tiff.toString());
	//Covert bytes to ByteInputSteam
	var bais = new java.io.ByteArrayInputStream(tiffBytes);
	//Covert ByteInputSteamt to BufferImage
	var image = new javax.imageio.ImageIO.read(bais);
```

**Expected behavior**
The tiff is converted to a BufferImage

**Actual behavior**
An error is given occurs everytime

**Environment (please complete the following information):**
CentOS 7, Java 8, Mirth Tested in Mirth Connection 3.9 - Current

**Workaround(s)**
If the jai_imageio.jar file that is located at /mirthconnect/extentions/dicom/lib/ a newer version of the .jar 
https://repo1.maven.org/maven2/com/sun/media/jai_imageio/1.1/

**Additional context**

**Comment by pladesma** [comment]
It sounds like you're missing some additional dependencies. `com/sun/medialib/codec/g3fax/Decoder` isn't included in Mirth Connect, so you probably need to find the correct JAR that includes that class, and include that in your Directory Resource.

**Comment by RunnenLate** [comment]
Correct, it's not included but why is Mirth connect using a jai_imageio.jar that references this if it's not included by default.  They should either update the jai_imageio.jar to remove this or included them so as to not cause the failure.
