### ISSUE TITLE
[BUG] NullPointerException in client if clipboard is empty during login

### ISSUE THREAD

**Issue by tonygermano** [nextgenhealthcare/connect#5388]
**Describe the bug**
The mirth client throws a NullPointerException if the clipboard is empty during login.

**Expected behavior**
Login should occur when the clipboard is empty.

**Actual behavior**
```
java.lang.NullPointerException
	at com.mirth.connect.client.ui.actions.PasteAction.isEnabled(PasteAction.java:39)
	at java.desktop/javax.swing.AbstractAction.setEnabledFromAction(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.configurePropertiesFromAction(Unknown Source)
	at java.desktop/javax.swing.JMenuItem.configurePropertiesFromAction(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.setAction(Unknown Source)
	at java.desktop/javax.swing.JPopupMenu.add(Unknown Source)
	at com.mirth.connect.client.ui.components.MirthSyntaxTextArea.<init>(MirthSyntaxTextArea.java:80)
	at com.mirth.connect.client.ui.components.MirthSyntaxTextArea.<init>(MirthSyntaxTextArea.java:53)
	at com.mirth.connect.client.ui.EditMessageDialog.initComponents(EditMessageDialog.java:435)
	at com.mirth.connect.client.ui.EditMessageDialog.<init>(EditMessageDialog.java:69)
	at com.mirth.connect.client.ui.Frame.setupFrame(Frame.java:541)
	at com.mirth.connect.client.ui.Mirth.<init>(Mirth.java:66)
	at com.mirth.connect.client.ui.LoginPanel$8.handleSuccess(LoginPanel.java:556)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:445)
	at com.mirth.connect.client.ui.LoginPanel$8.doInBackground(LoginPanel.java:416)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Java Distribution/Version: OpenJDK 11
 - Connect Version: 4.1.0

**Workaround(s)**
Copy something to the clipboard before logging in.

**Additional context**
https://github.com/nextgenhealthcare/connect/blob/00c2496bb4236f1c8a5a7cedafc00abf486623f1/client/src/com/mirth/connect/client/ui/actions/PasteAction.java#L38-L39

In line 38, the call to [getContents](https://docs.oracle.com/en/java/javase/11/docs/api/java.datatransfer/java/awt/datatransfer/Clipboard.html#getContents(java.lang.Object)) can return null if the clipboard is empty, causing the exception to be thrown on line 39.

Probably just needs to return false if `contents` is null.

**Comment by JackieK5** [comment]
@tonygermano, @ChristopherSchultz  The Connect dev team is planning to pull this (and the associated PR) into the next sprint but they have some questions about recreating the issue since they have never seen this.  Are there steps you can provide that will always reproduce this error, including how to ensure the clipboard is empty?  Is there anything else required for this issue to occur?  Thanks
