### ISSUE TITLE
Method failed: HTTP/1.1 500 Server Error

### ISSUE THREAD

**Issue by itsaboutcode** [nextgenhealthcare/connect#5391]
**Describe the bug**
Getting **Method failed: HTTP/1.1 500 Server Error** error.

**To Reproduce**
1. Just do the fresh installation of windows server 2019 on AWS.
2. Install the latest version of Java JDK and JRE
3. install the latest version 4.1.0 and you get this error.

**Screenshots**
<img width="518" alt="Screenshot 2022-08-29 at 5 27 17 PM" src="https://user-images.githubusercontent.com/204423/187202033-32d42ff1-adee-40a6-82e6-c3c7c1561284.png">

**Environment (please complete the following information):**
 - OS: Windows Server 2019
 - Java Distribution/Version [Java Version 8 Update 341]
 - Connect Version [4.1.0]

**Additional context**

```
Method failed: HTTP/1.1 500 Server Error
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 500 Server Error
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:533)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:457)
at com.mirth.connect.client.core.ServerConnection.executeAsync(ServerConnection.java:303)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:169)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
at com.sun.proxy.$Proxy68.getDashboardChannelInfo(Unknown Source)
at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:270)
at com.sun.proxy.$Proxy68.getDashboardChannelInfo(Unknown Source)
at com.mirth.connect.client.core.Client.getDashboardChannelInfo(Client.java:1221)
at com.mirth.connect.client.ui.Frame$12.doInBackground(Frame.java:2422)
at com.mirth.connect.client.ui.Frame$12.doInBackground(Frame.java:2405)
at com.mirth.connect.client.ui.QueuingSwingWorker.doInBackground(QueuingSwingWorker.java:97)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.client.core.EntityException: {
"servlet":"org.glassfish.jersey.servlet.ServletContainer-7ac94c86",
"message":"Request failed.",
"url":"/api/4.1.0/channels/statuses/initial",
"status":"500"
}
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:530)
... 28 more
```

**Comment by jonbartels** [comment]
The errors shown are from the GUI front-end.

What errors, if any, are recorded on the server in `mirth.log`?

**Comment by adil-appifytech** [comment]
Hi @jonbartels - Attached is the log file I got

[mirth_log.txt](https://github.com/nextgenhealthcare/connect/files/9446145/mirth_log.txt)

**Comment by jonbartels** [comment]
Lets see here:
`Running Java HotSpot(TM) 64-Bit Server VM 18.0.2.1 on Windows Server 2019 (10.0, amd64), derby, with charset UTF-8.`
Java 18

Then a whole mess of errors from XStream about:
`Unable to make field private static final long java.util.Collections$EmptySet.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @1f2781cf`

A search: https://github.com/nextgenhealthcare/connect/search?q=opens+java.util&type=discussions

Turns up this workaround: https://github.com/nextgenhealthcare/connect/issues/4602#issuecomment-1066927559

Tweak vmoptions and restart MC server and try it.

**Comment by adil-appifytech** [comment]
Hi @jonbartels - 

I put `--add-opens=java.sql.rowset/com.sun.rowset=ALL-UNNAMED` in `mcserver.vmoptions` but still facing the same issue.

**Comment by jonbartels** [comment]
Are you running MC as a `server` or as a `service`? `mcserver.vmoptions` and `mcservice.vmoptions` apply to different ways of running MC

**Comment by adil-appifytech** [comment]
@jonbartels - I did changed in both `mcserver.vmoptions` and `mcservice.vmoptions`, same issue

**Comment by ab-20-m** [comment]
@adil-appifytech Are you applying the full contents of `docs/mcservice-java9+.vmoptions` to the `mcservice.vmoptions` and `mcserver.vmoptions` files or just adding the single `--add-opens` statement? You need to add all of the `--add-opens` from the `mcservice-java9+.vmoptions` file.

**Comment by adil-appifytech** [comment]
@ab-20-m - This is what my file look like.

<img width="705" alt="Screenshot 2022-08-30 at 12 03 38 AM" src="https://user-images.githubusercontent.com/10629648/187280500-40e5462a-ec19-4720-9b1f-21d726a0444d.png">

**Comment by jonbartels** [comment]
Oh. This explains it https://docs.nextgen.com/bundle/Mirth_User_Guide_41/page/connect/connect/topics/c_Using_Java_9_or_greater_mirth_connect_ug.html

**Comment by adil-appifytech** [comment]
@jonbartels - Thanks. Last link you shared did the trick :)
