### ISSUE TITLE
com.mirth.connect.connectors.file.FileReceiver: Error polling in channel

### ISSUE THREAD

**Issue by dcardiel** [nextgenhealthcare/connect#5430]
I have the following problem with the Mirth Connect application, in which this channel has communication with an SSH server.

Do you know what exactly it refers to?

ERROR 2022-09-14 22:18:21,274 [Timer-1] com.mirth.connect.connectors.file.FileReceiver: Error polling in channel: 0c708f73-8567-454a-84ff-3d11bfd70cd4
com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out: connect
	at com.jcraft.jsch.Util.createSocket(Util.java:389)
	at com.jcraft.jsch.Session.connect(Session.java:215)
	at com.mirth.connect.connectors.file.filesystems.SftpConnection.<init>(SftpConnection.java:115)
	at com.mirth.connect.connectors.file.filesystems.FileSystemConnectionFactory.makeObject(FileSystemConnectionFactory.java:97)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1188)
	at com.mirth.connect.connectors.file.FileConnector.getConnection(FileConnector.java:197)
	at com.mirth.connect.connectors.file.FileReceiver.listFiles(FileReceiver.java:538)
	at com.mirth.connect.connectors.file.FileReceiver.poll(FileReceiver.java:192)
	at com.mirth.connect.donkey.server.channel.PollConnector$PollConnectorTask.run(PollConnector.java:141)
	at java.util.TimerThread.mainLoop(Unknown Source)
	at java.util.TimerThread.run(Unknown Source)

**Comment by pacmano1** [comment]
You should try the connection from a standard ssh/sftp client at the console of the mirth server.   That just seems to be a network problem.
