### ISSUE TITLE
[BUG] Mirth Connect 4.1.1.b303 creates corrupted keystore.jks when using "encryption.properties = 1"

### ISSUE THREAD

**Issue by NoraTheExplorer** [nextgenhealthcare/connect#5466]
**Describe the bug**
If the mcserver.exe is started and no ${dir.appdata}/keystore.jks is present, a new keystore.jks is created with the passwords provided in the conf/mirth.properties in the properties "keystore.storepass" and "keystore.keypass". 
If the password matches excactly "81uWxplDtB" this will be replaced by a random one generated by mirth or some lib.
You can also specify custom passwords as long as the keystore.jks does not exist yet.
Anyhow, if the propertie "encryption.properties" is present in the mirth.properties and its value is set to "1", the keystore.jks is created with non matching passwords.

**To Reproduce**
1. Stop the mirthserver (mcserver.exe) if running
2. delete the appdata directory
3. Open your 'conf/mirth.properties' 
4. change the property 'keystore.storepass' to a secure password
5. change the property 'keystore.keypass' to a secure password
6. change/add the property 'encryption.properties' and set its value to 1 
7. start the mcserver.exe 
8. See error: 
```
ERROR 2022-10-13 12:16:48.576 [Main Server Thread] Server: Exception in thread "Main Server Thread" java.lang.RuntimeException: com.mirth.commons.encryption.EncryptionException: javax.crypto.BadPaddingException: pad block corrupted
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.connect.server.controllers.DefaultConfigurationController.initializeDatabaseSettings(DefaultConfigurationController.java:1256)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.connect.server.Mirth.startup(Mirth.java:221)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.connect.server.Mirth.run(Mirth.java:168)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server: Caused by: com.mirth.commons.encryption.EncryptionException: javax.crypto.BadPaddingException: pad block corrupted
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.commons.encryption.KeyEncryptor.decrypt(KeyEncryptor.java:76)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.connect.server.controllers.DefaultConfigurationController.updateDatabasePassword(DefaultConfigurationController.java:1263)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.connect.server.controllers.DefaultConfigurationController.initializeDatabaseSettings(DefaultConfigurationController.java:1248)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      ... 2 more
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server: Caused by: javax.crypto.BadPaddingException: pad block corrupted
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2205)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.commons.encryption.KeyEncryptor.decrypt(KeyEncryptor.java:84)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      at com.mirth.commons.encryption.KeyEncryptor.decrypt(KeyEncryptor.java:73)
ERROR 2022-10-13 12:16:48.592 [Main Server Thread] Server:      ... 4 more
```

**Expected behavior**
I'd expect the mcserver.exe to start normally using the new keystore with the new passwords.

**Actual behavior**
The keystore.jks gets created but the passwords seem to be "corrupted". I assume internally these given passwords will be encrypted and then this encryption string is used as the password to create it. Anyway the plain passwords from the conf/mirth.properties are used to access the keystore later and that will fail.

**Environment (please complete the following information):**
 - OS: Windows Server 2022 Standard Eval
 - Java Distribution: OpenJDK 17.0.4.1 provided by Microsoft
 - Connect Version: 4.1.1

**Workaround(s)**
1. Stop the mirthserver (mcserver.exe) if running
2. delete the appdata directory
3. Open your 'conf/mirth.properties' 
4. change the property 'keystore.storepass' to a secure password
5. change the property 'keystore.keypass' to a secure password
6. change/add the property 'encryption.properties' and set its value to 0 
7. start the mcserver.exe 
8. stop the mcserver.exe 
9. change property 'encryption.properties' and set its value to 1
10. start the mcserver.exe

**Additional context**
We need the 'encryption.properties' set to 1 so the property 'database.password' gets encrypted on the first start.
With that, people getting access to that file are not able to read out the password.

**Suggestion**
1. the keystore.jks should be created with the plain, unecrypted passwords provided in the mirth.properties
2. after the keystore.jks has been created and the encrpytion.properties is set to 1, the passwords in the mirth.config shall be replaced with the encrypted string like the database.password: {enc}ENCRYPTPWD\r\n
3. as an alternative, just don't consider the keypass and storepass for encryption if enabled.

**Comment by jonbartels** [comment]
I have another keystore bug I'm picking at. I can try your repro steps later this week.

Does this bug only happen if the keystore exists and is later deleted or does it happen on a fresh deployment of Mirth Connect? IOW if you start with no keystore at all and a non-default storepass is there still an error *OR* must the keystore have existed and then be deleted?

The first error bubbles up from: https://github.com/nextgenhealthcare/connect/blob/0974c6ad4d6fc683d544f6f23da0def551812ecc/server/src/com/mirth/connect/server/controllers/DefaultConfigurationController.java#L1231

The second errror from "additional context" comes from:
https://github.com/nextgenhealthcare/connect/blob/0974c6ad4d6fc683d544f6f23da0def551812ecc/server/src/com/mirth/connect/server/controllers/DefaultConfigurationController.java#L1203

Both errors seem to be around the usage of keystores for DB encryption. IDK if that is significant or not.

**Comment by NoraTheExplorer** [comment]
> Both errors seem to be around the usage of keystores for DB encryption. IDK if that is significant or not.

Hi @jonbartels, I just played it through again and yes, it is definitely related.
I just changed the whole bug report.

**Comment by rogin** [comment]
Unable to replicate using Mirth 4.1.1 Windows x64 zip file. Is there any other info you can provide, @NoraTheExplorer?

Java versions tested: Oracle 1.8, Zulu 21
DBs tested: derby, PG 17

Test setup:

- Download and extract the zip.
- Edit `conf/mirth.properties` with values from spreadsheet.
- Set java that `mcserver.exe` will use; I wrote directly into new file `.install4j/pref_jre.cfg`
- If you're not using derby as the backend, create the DB.
- Start `mcserver.exe`
- Verify the server started successfully.
- Reset for next test:
    - Delete `appdata` folder
    - If the DB is not derby, drop and recreate schema
    - Verify `database.password` in `conf/mirth.properties` is correct as it may have been overwritten

Test results: [TestResults_5466.xlsx](https://github.com/user-attachments/files/21171233/TestResults_5466.xlsx)
