### ISSUE TITLE
SQLException while inserting message in derby

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#550]
I've configured a channel (llp2jms-jboss) with a LLP reader and a JMS writer which writes ADT messages to a queue (JNDI name HL7broadcast).

A message driven bean listens within the JBoss instance where also Mirth is deployed to the queue and successfully receives the ADT messages.

As a second step I'm trying to configure a channel (jms-jboss2file) with a JMS reader to file writer.

After successfully deploying both channels and sending a ADT message via llp to the first channel I see that both channels received and sent one message in the Mirth administrator dashboard. Both one received and one sent.

When I try to view the channel messages of the jms-jboss2file channel in the dashboard by double-clicking on the entry, the channel message list is empty.

The JBoss log indicates that there was a Mirth exception while inserting the message in derby.

The main error message seems to be the following lines:

08:17:11,984 ERROR [MessageObjectController] could not log message: id=eb2ecc57-68de-4ecb-b50d-576b0d1ae146
com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in derby/derby-message.xml.
--- The error occurred while applying a parameter map.
--- Check the Message.insert-message-param.
--- Check the parameter mapping for the 'channelMap' property.
--- Cause: java.lang.NullPointerException

The full stacktrace at the end of this message.

Is this some derby misconfiguration in Mirth? Or some DB inconsistency?

This is a fresh install of Mirth 1.6.1 and this are the first messages processed.

All subsequent message processing of jms-jboss2file fail with the same exception.

08:17:11,984 ERROR [MessageObjectController] could not log message: id=eb2ecc57-68de-4ecb-b50d-576b0d1ae146
com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in derby/derby-message.xml.
--- The error occurred while applying a parameter map.
--- Check the Message.insert-message-param.
--- Check the parameter mapping for the 'channelMap' property.
--- Cause: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:94)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)

        at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:291)
        at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
        at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
        at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
        at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
        at com.webreach.mirth.connectors.jms.JmsMessageReceiver.onMessage(JmsMessageReceiver.java:113)
        at org.jboss.mq.SpyMessageConsumer.run(SpyMessageConsumer.java:682)
        at java.lang.Thread.run(Thread.java:595)
Caused by: java.lang.NullPointerException
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        ... 20 more

Caused by:
java.lang.NullPointerException
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)

        at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:291)
        at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
        at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
        at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
        at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
        at com.webreach.mirth.connectors.jms.JmsMessageReceiver.onMessage(JmsMessageReceiver.java:113)
        at org.jboss.mq.SpyMessageConsumer.run(SpyMessageConsumer.java:682)
        at java.lang.Thread.run(Thread.java:595)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-542
Reporter: level420
Created: 2007-09-30T23:28:55.000-0700

**Comment by rbeckman-nextgen** [comment]
I've installed and configured Mirth to use postgres instead of derby with the same result.

Imported Comment. Original Details:
Author: level420
Created: 2007-09-30T23:36:15.000-0700

**Comment by rbeckman-nextgen** [comment]
Can you post your channel. It appears there is something in the channel mapping that can not be serialized to the database.

Imported Comment. Original Details:
Author: chrisl
Created: 2007-10-30T14:11:21.000-0700

**Comment by rbeckman-nextgen** [comment]
Here is a (fresh) stacktrace of the attached channel while receiving a message via JMS-reader. Please not that the attached channel has a channel writer destination and not a file writer destination as written in the issue description:

2007-10-31 10:36:17,706 ERROR [com.webreach.mirth.server.controllers.MessageObjectController] could not log message: id=ffc529c6-acfd-44cf-8e8a-027dc7b124ce
com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in derby/derby-message.xml.  
--- The error occurred while applying a parameter map.  
--- Check the Message.insert-message-param.  
--- Check the parameter mapping for the 'channelMap' property.  
--- Cause: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:94)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)
        at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:291)
        at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
        at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
        at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
        at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
        at com.webreach.mirth.connectors.jms.JmsMessageReceiver.onMessage(JmsMessageReceiver.java:113)
        at org.jboss.mq.SpyMessageConsumer.run(SpyMessageConsumer.java:682)
        at java.lang.Thread.run(Thread.java:595)
Caused by: java.lang.NullPointerException
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        ... 20 more

Caused by: 
java.lang.NullPointerException
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)
        at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:291)
        at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
        at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
        at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
        at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
        at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
        at com.webreach.mirth.connectors.jms.JmsMessageReceiver.onMessage(JmsMessageReceiver.java:113)
        at org.jboss.mq.SpyMessageConsumer.run(SpyMessageConsumer.java:682)
        at java.lang.Thread.run(Thread.java:595)
2007-10-31 10:36:19,097 ERROR [com.webreach.mirth.server.controllers.MessageObjectController] could not log message: id=56fbae8c-1fab-4451-be43-793389bde373
com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in derby/derby-message.xml.  
--- The error occurred while applying a parameter map.  
--- Check the Message.insert-message-param.  
--- Check the parameter mapping for the 'channelMap' property.  
--- Cause: java.lang.NullPointerException
Caused by: java.lang.NullPointerException
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:94)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)
        at com.webreach.mirth.server.controllers.MessageObjectController.setStatus(MessageObjectController.java:539)
        at com.webreach.mirth.server.controllers.MessageObjectController.setSuccess(MessageObjectController.java:515)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.routeTemplatedMessage(VMMessageDispatcher.java:231)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.doSend(VMMessageDispatcher.java:274)
        at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
        at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
        at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
        at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
        at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
        at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
        at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
        at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
        at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
        at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
        at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
        at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
        at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
        at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
        at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
        at com.webreach.mirth.connectors.jms.JmsMessageReceiver.onMessage(JmsMessageReceiver.java:113)
        at org.jboss.mq.SpyMessageConsumer.run(SpyMessageConsumer.java:682)
        at java.lang.Thread.run(Thread.java:595)
Caused by: java.lang.NullPointerException
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        ... 29 more

Caused by: 
java.lang.NullPointerException
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)
        at com.webreach.mirth.server.controllers.MessageObjectController.setStatus(MessageObjectController.java:539)
        at com.webreach.mirth.server.controllers.MessageObjectController.setSuccess(MessageObjectController.java:515)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.routeTemplatedMessage(VMMessageDispatcher.java:231)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.doSend(VMMessageDispatcher.java:274)
        at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
        at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
        at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
        at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
        at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
        at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
        at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
        at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
        at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
        at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
        at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
        at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
        at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
        at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
        at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
        at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
        at com.webreach.mirth.connectors.jms.JmsMessageReceiver.onMessage(JmsMessageReceiver.java:113)
        at org.jboss.mq.SpyMessageConsumer.run(SpyMessageConsumer.java:682)
        at java.lang.Thread.run(Thread.java:595)


Imported Comment. Original Details:
Author: level420
Created: 2007-10-31T03:00:50.000-0700

**Comment by rbeckman-nextgen** [comment]
Gerald - see if you can take a look at this, not too sure on the JMS side here...

Imported Comment. Original Details:
Author: chrisl
Created: 2007-11-01T17:55:52.000-0700

**Comment by rbeckman-nextgen** [comment]
We've tested this with ActiveMQ without a problem.  It may be a problem when using JNDI, but we haven't had this report elsewhere.  We need to test on JBoss in order to run the same scenario.

Imported Comment. Original Details:
Author: jacobb
Created: 2007-11-08T14:43:21.000-0800

**Comment by rbeckman-nextgen** [comment]
I've just encountered the same problem using the same Mirth with Jboss 4.2.2

Imported Comment. Original Details:
Author: straujo
Created: 2007-12-09T07:25:37.000-0800

**Comment by rbeckman-nextgen** [comment]
The root of this problem is that an Object is being added to the channelMap that cannot be serialized when it comes time to persist the MessageObject to the database. If this is unique to the JMS connector, then some code is inserting an Object that is causing this problem. I would also look at the template to make sure nothing weird is put in there.

Imported Comment. Original Details:
Author: geraldb
Created: 2008-02-28T17:00:26.000-0800
