### ISSUE TITLE
Unable to delete channel in Mirth Connect Mirth Connect 4.1.1 (Built on August 24, 2022) 

### ISSUE THREAD

**Issue by stefan-huettemann** [nextgenhealthcare/connect#5535]
**Describe the bug**
Unable to delete channel in Mirth Connect Mirth Connect 4.1.1 (Built on August 24, 2022) 

We run Mirth Connect 4.1.1 (Built on August 24, 2022) using a PostgreSQL 14 database and  OpenJDK 64-Bit Server VM 17.0.4.1 on Windows

We experience an error when trying to delete a channel. (Either a channel created by importing or by creating from Mirth Connect Administrator.

**To Reproduce**

1. Create a new Channel Group
2. Create a new Channel
3. Delete Channel 

**Expected behavior**
Well, we expect, that the channel gets deleted.

**Actual behavior**
Server Error. See Stacktrace.

**Stacktrace**

```
INFO  2022-11-17 15:25:33.125 [Main Server Thread] com.mirth.connect.server.Mirth: Mirth Connect 4.1.1 (Built on August 24, 2022) server successfully started.INFO  2022-11-17 15:25:33.136 [Main Server Thread] com.mirth.connect.server.Mirth: This product was developed by NextGen Healthcare (https://www.nextgen.com) and its contributors (c)2005-2022.INFO  2022-11-17 15:25:33.137 [Main Server Thread] com.mirth.connect.server.Mirth: Running OpenJDK 64-Bit Server VM 17.0.4.1 on Windows Server 2019 (10.0, amd64), postgres, with charset windows-1252.INFO  2022-11-17 15:25:33.192 [Main Server Thread] com.mirth.connect.server.Mirth: Web server running
at http://10.10.184.2:10080/ and https://10.10.184.2:10443/ERROR 2022-11-17 15:27:36.593 [Channel RemoveTask Thread on (19e40919-4c65-4c57-bdca-cd336897c45f) < pool-8-thread-2] com.mirth.connect.server.channel.LoggingTaskHandler: com.mirth.connect.client.core.ControllerException: org.apache.ibatis.exceptions.PersistenceException:### Error updating database.  Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'value' in 'class java.lang.String'### Cause: org.apache.ibatis.reflection.ReflectionException: There is no getter for property named 'value' in 'class java.lang.String'
	at com.mirth.connect.server.controllers.DefaultChannelController.removeChannel(DefaultChannelController.java:578)
	at com.mirth.connect.server.controllers.DonkeyEngineController$RemoveTask.execute(DonkeyEngineController.java:2232)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:67)
	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Environment (please complete the following information):**
 - Windows
 - Mirth Connect 4.1.1 (Built on August 24, 2022)
 - PostgreSQL 14 database
 - OpenJDK 64-Bit Server VM 17.0.4.1

**Comment by pacmano1** [comment]
https://github.com/nextgenhealthcare/connect/issues/4602

Perhaps? See discussion on 17 down the thread.

**Comment by stefan-huettemann** [comment]
Great. Thanks. That solved the issue!
