### ISSUE TITLE
Method failed: HTTP/1.1 500 Server Error

### ISSUE THREAD

**Issue by Ramtirth123** [nextgenhealthcare/connect#5577]
Hello,

Using Mirth connect 4.2.0
Using Java: java version "17.0.5"
OS - Windows.

Getting an error 
Method failed: HTTP/1.1 500 Server Error error.-.

![image](https://user-images.githubusercontent.com/116250386/206872611-fac83221-1363-4096-ab5e-a3751015902b.png)

Error message:

Method failed: HTTP/1.1 500 Server Error
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 500 Server Error
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:533)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:457)
at com.mirth.connect.client.core.ServerConnection.executeAsync(ServerConnection.java:303)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:169)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
at com.sun.proxy.$Proxy68.getDashboardChannelInfo(Unknown Source)
at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:273)
at com.sun.proxy.$Proxy68.getDashboardChannelInfo(Unknown Source)
at com.mirth.connect.client.core.Client.getDashboardChannelInfo(Client.java:1241)
at com.mirth.connect.client.ui.Frame$12.doInBackground(Frame.java:2432)
at com.mirth.connect.client.ui.Frame$12.doInBackground(Frame.java:2415)
at com.mirth.connect.client.ui.QueuingSwingWorker.doInBackground(QueuingSwingWorker.java:97)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.client.core.EntityException: {
"servlet":"org.glassfish.jersey.servlet.ServletContainer-635962ae",
"message":"Request failed.",
"url":"/api/4.2.0/channels/statuses/initial",
"status":"500"
}
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.jav

I have added the vmoptions from the /docs/mcservice-java9+.vmoptions as per the readme files. But still seeing the same error.
Can someone please help to resolve this issue. I have spent a lot of time on this issue.

Thanks.

**Comment by pacmano1** [comment]
I don't get this:

windows 2019 standard fresh insstall
Amazon Corretto v18
Mirth 4.2.0:

![image](https://user-images.githubusercontent.com/44065187/206914310-da6d24d7-295d-4a7c-8929-888aeb933b02.png)

**Comment by pacmano1** [comment]
User error, closing.   Contents of java9+ options not added to mcservice.vmoptions.
