### ISSUE TITLE
Cannot deploy if all destinations are not enabled

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#559]
Cannot deploy when all destinations are not enabled. I get the following error:

ERROR 2007-10-05 11:44:50,009 [Thread-0] org.apache.commons.digester.Digester: Begin event threw exception
org.apache.commons.beanutils.ConversionException: UMOConnector: 7258bb68-71e2-4157-b245-348be27f3c48_destination_2_connector has not been registered with Mule
        at org.mule.config.converters.ConnectorConverter.convert(ConnectorConverter.java:61)
        at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:428)
        at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1002)
        at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:811)
        at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:298)
        at org.apache.commons.digester.SetPropertiesRule.begin(SetPropertiesRule.java:251)
        at org.mule.config.builders.MuleXmlConfigurationBuilder$ExtendedMuleSetPropertiesRule.begin(MuleXmlConfigurationBuilder.java:1017)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1361)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1685)
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
        at com.webreach.mirth.server.Mirth.startMule(Mirth.java:229)
        at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:186)
        at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
Caused by: org.apache.commons.beanutils.ConversionException: UMOConnector: 7258bb68-71e2-4157-b245-348be27f3c48_destination_2_connector has not been registered with Mule
        at org.mule.config.converters.ConnectorConverter.convert(ConnectorConverter.java:56)
        ... 24 more
WARN  2007-10-05 11:44:50,010 [Thread-0] com.webreach.mirth.server.Mirth: Error deploying channels.
org.mule.config.ConfigurationException: Failed to parse configuration resource "/Users/chris/Desktop/mirth-1.6.1.2750/conf/mule-config.xml" (org.mule.config.ConfigurationException)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:196)
        at com.webreach.mirth.server.Mirth.startMule(Mirth.java:229)
        at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:186)
        at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
Caused by: org.mule.config.ConfigurationException: Failed to parse configuration resource "/Users/chris/Desktop/mirth-1.6.1.2750/conf/mule-config.xml"
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:121)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
        ... 3 more
Caused by: org.apache.commons.beanutils.ConversionException: UMOConnector: 7258bb68-71e2-4157-b245-348be27f3c48_destination_2_connector has not been registered with Mule
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2919)
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2945)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1364)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1685)
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
        ... 5 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-551
Reporter: blackc2004
Created: 2007-10-05T12:08:31.000-0700

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-563.

Imported Comment. Original Details:
Author: jacobb
Created: 2007-10-16T11:27:10.000-0700
