### ISSUE TITLE
Mirth connect: Caused by: java.sql.SQLException: Network error IOException: Connection refused: connect

### ISSUE THREAD

**Issue by prajwal014** [nextgenhealthcare/connect#5611]
**Describe the bug**
I'm trying to run the Mirth Connect  server on Windows server 2019/2022 when trying to run mirth connect server getting error like:
Error: Caused by: java.sql.SQLException: Network error IOException: Connection refused: connect
	at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:436)
	at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:341)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:506)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at net.sourceforge.jtds.jdbc.SharedSocket.createSocketForJDBC3(SharedSocket.java:288)
	at net.sourceforge.jtds.jdbc.SharedSocket.<init>(SharedSocket.java:251)
	at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:331)
	... 35 more
ERROR 2023-01-10 12:30:17,539 [Main Server Thread] com.mirth.connect.server.Mirth: Error establishing connection to database, aborting startup. Network error IOException: Connection refused: connect
INFO  2023-01-10 12:30:17,544 [Shutdown Hook Thread] com.mirth.connect.server.Mirth: shutting down mirth due to normal request
ERROR 2023-01-10 12:30:18,627 [Shutdown Hook Thread] com.mirth.connect.server.controllers.DefaultConfigurationController: Could not retrieve property: category=core, name=channelDependencies

**Environment (please complete the following information):**
 - OS: Windows server 2019/2022
 - Java Distribution/Version: Java8 (32bit)
 - Connect Version [Mirth Connect 3.9.0]

Is it possible to run Mirth Connect on windows server 2019/2022?

**Comment by pacmano1** [comment]
Please don't post a bug without listing the things you have done to troubleshoot. Also, if you post here and on the forums, please cross reference the post. I already answered you on the forums.

**Comment by prajwal014** [comment]
> Please don't post a bug without listing the things you have done to troubleshoot. Also, if you post here and on the forums, please cross reference the post. I already answered you on the forums.

Can you please share the link i didn't find any solution related to windows server 2019

**Comment by pacmano1** [comment]
On the forums I mentioned this is a firewall or general network connectivity problem such as your connection string is not correct.  You may be missing required TLS options depending on how SQL server is configured.  Also if you java 9 or newer read the documentation on required  jvm options.  There are several github and forum threads on these topics.  Please search.

**Comment by prajwal014** [comment]
> On the forums I mentioned this is a firewall or general network connectivity problem such as your connection string is not correct. Also if you java 9 or newer read the documentation on required jvm options.

Okay thank you

**Comment by prajwal014** [comment]
Thanks
