### ISSUE TITLE
Errors in TCP Sender, Listener while using SSL extension

### ISSUE THREAD

**Issue by sitharaj1** [nextgenhealthcare/connect#5706]
**Describe the bug**
Errors in TCP Sender, Listener while using SSL extension. 
- Configured the TCP Sender - TCP Listener duo using the SSL extension
- The Error was thrown in TCP Sender Log and TCP Listener Log 
- **TCP Sender Error:**
_ERROR MESSAGE: Connection closed by remote host
java.net.SocketException: Connection closed by remote host
at sun.security.ssl.SSLSocketImpl.checkWrite(Unknown Source)
at sun.security.ssl.AppOutputStream.write(Unknown Source)
at java.io.BufferedOutputStream.flushBuffer(Unknown Source)
at java.io.BufferedOutputStream.flush(Unknown Source)
at com.mirth.connect.connectors.tcp.TcpDispatcher.send(TcpDispatcher.java:256)
at com.mirth.connect.donkey.server.channel.DestinationConnector.handleSend(DestinationConnector.java:822)
at com.mirth.connect.donkey.server.channel.DestinationConnector.run(DestinationConnector.java:669)
at java.lang.Thread.run(Unknown Source)_

**- TCP Listener Error:**
_ERROR (com.mirth.connect.connectors.tcp.TcpReceiver:747): Error receiving message (TCP Listener "Source" on channel ...................................).
java.net.SocketException: Socket is closed
at sun.security.ssl.SSLSocketImpl.getOutputStream(Unknown Source)
at com.mirth.connect.plugins.ssl.server.u.getOutputStream(SourceFile:237)
at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:573)
at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:512)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)_

**Expected behavior**
We expected a connection without any errors in both the Sender and listener logs

**Environment (please complete the following information):**
 - Connect Version 4.2

**Comment by jonbartels** [comment]
My employer also uses the NG SSL Manager and we get the same errors.

These errors are caused by something connecting to the TCP port and that thing doesn't use mutual TLS. So it connects to the port, Mirth says "hey I need your client cert" and the other system doesn't have one. The connection is then terminated before any message is created.

In my environments I suspect this is something like a monitor that pings the port or a security scan. 

I have spent some time using these two experiments to trace the problem:
* Looking at packet captures - This shows the sending IP and some information about the SSL handshake. If I remember correctly, all of these terminate with an "SSL Alert" 
* Stopping my actual channel. Create a dumb TCP listener that does NOT use SSL and uses raw message types and plain TCP (not MLLP). This lets Mirth act as a very dumb packet dump. When this debug channel is deployed it will accept connections. This will dump the raw data and the source IP address. Then you can use that information to track down what the heck is sending bad data
* Similar to the channel idea - stop the channel and get to the OS then run `nc -l 6667` (netcat) and this will dump raw TCP traffic to the console. Again SHOW what is connecting and what it is sending then make it stop.

The root cause is that some other system is trying to connect to Mirth and not using mTLS. 

Something that NextGen can do as a feature enhancement to the premium SSL Manager extension is - Improve the error message logged when SSL connections cannot be made. Improve the error message to show:
* Both the Channel ID and Channel Name
* The source IP address
* A more specific SSL error saying what was wrong with the handshake (may not be practical)
* Instead of LOGGING bad SSL connections - Record them as MC Events. This does not solve the spam problem but Events are more searchable and can persist more data
* Reduce the log level for SSL connection errors - This would silently drop untrusted connections. This could make debugging harder.

**Comment by sitharaj1** [comment]
Thanks, @jonbartels .
Please, could you suggest if you have sorted this out by means of a step-by-step process. 
This to me is too complicated - unable to get my head around it as there is little help from forums / NG Gold Support team.
Many thanks in advance.  

Any kind of response from Team NG would be massively helpful.

**Comment by narupley** [comment]
Are you sure it's an SSL issue? Maybe it's more of a TCP issue like the connection being closed too soon.

What settings are you using for both the Listener and Sender?

**Comment by pacmano1** [comment]
@jonbartels already wrote several suggestions to troubleshoot.  Debugging TLS, including errors that result from users calling your endpoint without TLS and/or missing mutual TLS, is a very complex topic.  

You can put a TLS proxy in front of Mirth to address these errors which moves the problem upstream from Mirth if in fact it is not a normal TCP transport problem like mentioned above.

**Comment by vibinernesto** [comment]
@narupley  - We are facing the same issue as well

The version of Mirth that we are using is 3.11.0

We created a certificate and shared with our counter-parts and they can do the SSL handshake fine - there was no issue on that. But when they send data to us we keep getting this error in the server log below.

Any pointers can help us more here

```
ERROR  (com.mirth.connect.connectors.tcp.TcpReceiver:746): Error receiving message (TCP Listener "Source" on channel {channel ID guid}).
java.net.SocketException: Socket is closed
	at java.base/sun.security.ssl.SSLSocketImpl.getOutputStream(SSLSocketImpl.java:1234)
	at com.mirth.connect.plugins.ssl.server.u.getOutputStream(SourceFile:237)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:572)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:511)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by narupley** [comment]
Again, what settings are being used for the TCP Listener.

That error occurs when the client side closes the connection prematurely.

If mutual authentication is used, then some clients will drop the connection if they don't see an appropriate DN in the CA list of the CertificateRequest part of the handshake, even though that is supposed to be optional.

Or, it could be protocol / cipher suite mismatch issues. Or something else. You will need to inspect your network traffic to see why.

**Comment by vibinernesto** [comment]
@narupley  we did few things to rule out that this is not connectivity issue:

- We created a channel within the same mirth and tried to send the message to another channel both **with the SSL** enabled - we got the _same error_ (i.e _java.base/sun.security.ssl.SSLSocketImpl.getOutputStream(SSLSocketImpl.java:1234_) in the server log but the messages sent successfully and the receiving channel received it.

- We tried to do the same above **without using the SSL** option then also the message from one channel came to another channel but the error in the server log is different like this.

```
(com.mirth.connect.connectors.tcp.TcpReceiver:746): Error receiving message (TCP Listener "Source" on channel {channel guid}).
com.mirth.connect.model.transmission.framemode.FrameStreamHandlerException: End of message bytes (<FS><CR>) not detected. Last bytes received: <NUL><NUL>
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:209)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.readBytes(TcpReceiver.java:813)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:620)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:511)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)Caused by: java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:115)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:168)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at com.mirth.connect.model.transmission.batch.DefaultBatchStreamReader.getNextByte(DefaultBatchStreamReader.java:28)
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:152)
	... 7 more
```
**Inbound Settings:**

Local Port: our port number
Max Processing Threads: 1
SSL Settings: Enabled (yes)

**TCP Listener Settings:**

- Transmission Mode: MLLP
- Mode: Server
- Max Conncections: 10
- Receive Timeouts: 0
- Buffer Size: 65536
- keep connection open: Yes
- Data Type Text
- Encoding: Default
- Respond to New Connection: No

**One more detail:**

In the SSL setting when we disable client authentication - then we receive data from the other side just fine. 
![image](https://user-images.githubusercontent.com/11159009/223705583-a081e719-c16f-4b74-8d17-9a483fb258aa.png)

The issue happens when we select the certificate of the client and we also select the java keystore along with that.
![image](https://user-images.githubusercontent.com/11159009/223712499-6f74662f-6655-4e7b-a8ee-3f4753339903.png)

**Comment by narupley** [comment]
As previously mentioned, if mutual authentication is used, then some clients will drop the connection if they don't see an appropriate DN in the CA list of the CertificateRequest part of the handshake, even though that is supposed to be optional.

Enable "Present Issuer DNs".

**Comment by vibinernesto** [comment]
@narupley  I enabled the "Present Issuer DNs". But the result is same.
![image](https://user-images.githubusercontent.com/11159009/223769274-86525f36-d40c-4329-ba2b-17fda69cf47e.png)

**Comment by narupley** [comment]
Okay, also make sure that client cert is in your trusted client certs list, or at least its CA cert.

If it is, then it could be something else like protocol / cipher suites. Maybe try enabling TLSv1.

Otherwise, you will need to capture network traffic and inspect the handshake, and possibly get in contact with the manager of that client side to see why the connection is being prematurely closed.

**Comment by narupley** [comment]
Also, it could be frame / MLLP related issues. If you have a Sender and Listener channel that reproduces the issue, then export and attach them here and I can take a look.

**Comment by vibinernesto** [comment]
> Okay, also make sure that client cert is in your trusted client certs list, or at least its CA cert.
> 
> If it is, then it could be something else like protocol / cipher suites. Maybe try enabling TLSv1.
> 
> Otherwise, you will need to capture network traffic and inspect the handshake, and possibly get in contact with the manager of that client side to see why the connection is being prematurely closed.

The client's are using TLS.V.1.2 and we are using the same - confirmed on that.

Could you explain how to verify if the client cert is in our trusted client certs list?

@narupley  thank you for responding on this issue

**Comment by vibinernesto** [comment]
@narupley  - this issue is fixed from my end - In the listener setting - we were having the client auth disabled has fixed the problem. 

I guess in case of  @sitharaj1  its a infra related issue that was causing the trouble. This can be closed.

**Comment by pladesma** [comment]
@sitharaj1 Would you agree that this issue can be closed?

**Comment by sitharaj1** [comment]
Hi @pladesma, sure this issue can be closed. 
I changed settings as indicated in this thread ( /5706) reimported the cert. and applied the cert. to resolve the issue. 

Thank you all for your inputs.
