### ISSUE TITLE
Disabling a destination causes error on deploy

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#571]
I have three destinations in my channel. When I disable the last channel I get the following error (It doesn't seem to matter which of the three is the last disabled channel)

ERROR 2007-10-11 11:50:08,038 [Thread-0] org.apache.commons.digester.Digester: Begin event threw exception
org.apache.commons.beanutils.ConversionException: UMOConnector: 195a6dc5-2780-428f-afe3-658040ef4932_destination_3_connector has not been registered with Mule
        at org.mule.config.converters.ConnectorConverter.convert(ConnectorConverter.java:61)
        at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:428)
        at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1002)
        at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:811)
        at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:298)
        at org.apache.commons.digester.SetPropertiesRule.begin(SetPropertiesRule.java:251)
        at org.mule.config.builders.MuleXmlConfigurationBuilder$ExtendedMuleSetPropertiesRule.begin(MuleXmlConfigurationBuilder.java:1017)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1361)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1685)
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
        at com.webreach.mirth.server.Mirth.startMule(Mirth.java:229)
        at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:186)
        at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
Caused by: org.apache.commons.beanutils.ConversionException: UMOConnector: 195a6dc5-2780-428f-afe3-658040ef4932_destination_3_connector has not been registered with Mule
        at org.mule.config.converters.ConnectorConverter.convert(ConnectorConverter.java:56)
        ... 24 more
WARN  2007-10-11 11:50:08,040 [Thread-0] com.webreach.mirth.server.Mirth: Error deploying channels.
org.mule.config.ConfigurationException: Failed to parse configuration resource "/Users/chris/Desktop/mirth-1.6.1.2750/conf/mule-config.xml" (org.mule.config.ConfigurationException)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:196)
        at com.webreach.mirth.server.Mirth.startMule(Mirth.java:229)
        at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:186)
        at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
Caused by: org.mule.config.ConfigurationException: Failed to parse configuration resource "/Users/chris/Desktop/mirth-1.6.1.2750/conf/mule-config.xml"
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:121)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
        ... 3 more
Caused by: org.apache.commons.beanutils.ConversionException: UMOConnector: 195a6dc5-2780-428f-afe3-658040ef4932_destination_3_connector has not been registered with Mule
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2919)
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2945)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1364)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1685)
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
        ... 5 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-563
Reporter: blackc2004
Created: 2007-10-11T12:16:06.000-0700

**Comment by rbeckman-nextgen** [comment]
I could not reproduce this issue.  If encountered again, please include the channel.

Imported Comment. Original Details:
Author: jacobb
Created: 2007-10-16T11:23:46.000-0700

**Comment by rbeckman-nextgen** [comment]
I emailed you the files. 

Imported Comment. Original Details:
Author: blackc2004
Created: 2007-10-16T11:29:47.000-0700
