### ISSUE TITLE
[BUG] Mirth 4.2 - Connections to Oracle DB on Channel Not getting Disconnected

### ISSUE THREAD

**Issue by johnson-cloud** [nextgenhealthcare/connect#5711]
**Describe the bug**
In older version of Mirth 3.x - It never happened, now all connections are piled up in DB - user which is used in DB reader JS to connect oracle DB:

Can anyone help?

com.mirth.connect.server.MirthJavascriptTransformerException: 
CHANNEL:	XXXX
CONNECTOR:	Destination 3
SOURCE CODE:	
201: //URL of Oracle database server
202: /*var url_mosaiq 	= "jdbc:jtds:sqlserver://servr1:1433/Queries";  
203: var url_integ 	     = "jdbc:oracle:thin:@localhost:1521:db2"; */
204: 
205: 
206: var   dbConnHope =  DatabaseConnectionFactory.createDatabaseConnection('oracle.jdbc.driver.OracleDriver','jdbc:oracle:thin:@localhost:1521:db2','user1','user123');
207: var   dbConnMosaiq = DatabaseConnectionFactory.createDatabaseConnection('oracle.jdbc.driver.OracleDriver','jdbc:jtds:sqlserver://servr1:1433/Queries','MqQueue','M0$aiqQue');
208: 
209: 
210: //properties for creating connection to Oracle database
LINE NUMBER:	206
DETAILS:	Wrapped java.sql.SQLRecoverableException: IO Error: Got minus one from a read call, connect lapse 31 ms., Authentication lapse 0 ms.
	at b1410278-f2d6-43c8-a2fb-5b3977298558_Database_Writer_3:206 (doScript)
	at b1410278-f2d6-43c8-a2fb-5b3977298558_Database_Writer_3:281
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1899) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:160) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:226) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1692) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:1013) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3578) ~[rhino-1.7.13.jar:1.7.13]
	at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:121) ~[rhino-1.7.13.jar:1.7.13]
	at com.mirth.connect.server.util.javascript.JavaScriptTask.executeScript(JavaScriptTask.java:151) ~[mirth-server.jar:?]
	at com.mirth.connect.server.util.javascript.JavaScriptUtil.executeScript(JavaScriptUtil.java:615) ~[mirth-server.jar:?]
	at com.mirth.connect.connectors.jdbc.DatabaseDispatcherScript$DatabaseDispatcherTask.doCall(DatabaseDispatcherScript.java:202) ~[jdbc-server.jar:?]
	at com.mirth.connect.server.util.javascript.JavaScriptTask.call(JavaScriptTask.java:114) ~[mirth-server.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.sql.SQLRecoverableException: IO Error: Got minus one from a read call, connect lapse 31 ms., Authentication lapse 0 ms.
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:794) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691) ~[ojdbc8-12.2.0.1.jar:12.2.0.1.0]
	at java.sql.DriverManager.getConnection(DriverManager.java:677) ~[java.sql:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:189) ~[java.sql:?]
	at com.mirth.connect.server.userutil.DatabaseConnection.<init>(DatabaseConnection.java:66) ~[mirth-server.jar:?]
	at com.mirth.connect.server.userutil.DatabaseConnectionFactory.createDatabaseConnection(DatabaseConnectionFactory.java:63) ~[mirth-server.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor106.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:138) ~[rhino-1.7.13.jar:1.7.13]

Code***********

importPackage(java.sql);

var dbConn = null;
var result =null;
var strSQL="";
var HTTPString="";
var dbConnMySQL;
var responseMSG;
var result1 = null;

try {

	dbConn =  DatabaseConnectionFactory.createDatabaseConnection('oracle.jdbc.driver.OracleDriver','jdbc:oracle:thin:@localhost:1521:db2','user1','user123');

//////////////////////////////////////////////////message code          
  }
     

return responseMSG;

}
catch (e) {
	logger.error('Error from HTTP service' + e.message);
}

finally {
     /*if (dbConn) {
           dbConn.close();
     }*/
    /* try {if (result 		!= null) 	result.close();	}catch(e){e.printStackTrace();}
     try {if (result1 		!= null) 	result1.close();	}catch(e){e.printStackTrace();}*/
     try {if (dbConn 		!= null) 	 dbConn.close();	}catch(e){e.printStackTrace();}
 
}

**Comment by johnson-cloud** [comment]
N/A
