### ISSUE TITLE
[IDEA] ASCII Notification Protocol / DICOM Tag Notification Protocol

### ISSUE THREAD

**Issue by johnson-cloud** [nextgenhealthcare/connect#5712]
I have deployed Mirth 4.2 on PG Database.

How can i create channel on ASCII Notification Protocol / DICOM Tag Notification Protocol;

Inshort These protocols sends tags as an ASCII text and attribute values in DICOM format, as an ASCII text. all attributes in DICOM format with the transfer syntax VR Little Endian Explicit. The single news is confirmed and sent in each case as a block via TCP/IP port.

I tried with MLLP with all possible settings - It doesn't work, getting below error:-

com.mirth.connect.connectors.tcp.TcpReceiver: Error receiving message (TCP Listener "Source" on channel 41831ece-46a2-4f64-a43f-14b5c126d616).
com.mirth.connect.model.transmission.framemode.FrameStreamHandlerException: Start of message byte (<VT>) not detected. First byte received: 2
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:206) ~[mirth-server.jar:?]
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.readBytes(TcpReceiver.java:814) ~[tcp-server.jar:?]
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:621) ~[tcp-server.jar:?]
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:512) ~[tcp-server.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:?]
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:?]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:115) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:168) ~[?:?]
	at java.net.SocketInputStream.read(SocketInputStream.java:140) ~[?:?]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:252) ~[?:?]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:271) ~[?:?]
	at com.mirth.connect.model.transmission.framemode.FrameStreamHandler.read(FrameStreamHandler.java:121) ~[mirth-server.jar:?]
	... 7 more

**Comment by johnson-cloud** [comment]
N/A
