### ISSUE TITLE
Got Error after launch adminstrator Window

### ISSUE THREAD

**Issue by srdotnetdeveloper** [nextgenhealthcare/connect#5754]
**Steps to Reproduce:**
Install mirth connect on new system with 8082 port
Open "Administrator UI" getting continuous error

**Exception  log is:**
Method failed: HTTP/1.1 500 Server Error
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 500 Server Error
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:533)
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:457)
at com.mirth.connect.client.core.ServerConnection.executeAsync(ServerConnection.java:303)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:169)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:430)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:381)
at com.sun.proxy.$Proxy68.getDashboardChannelInfo(Unknown Source)
at sun.reflect.GeneratedMethodAccessor39.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:273)
at com.sun.proxy.$Proxy68.getDashboardChannelInfo(Unknown Source)
at com.mirth.connect.client.core.Client.getDashboardChannelInfo(Client.java:1245)
at com.mirth.connect.client.ui.Frame$12.doInBackground(Frame.java:2431)
at com.mirth.connect.client.ui.Frame$12.doInBackground(Frame.java:2414)
at com.mirth.connect.client.ui.QueuingSwingWorker.doInBackground(QueuingSwingWorker.java:97)
at javax.swing.SwingWorker$1.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at javax.swing.SwingWorker.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.client.core.EntityException: {
"servlet":"org.glassfish.jersey.servlet.ServletContainer-404f4fea",
"message":"Request failed.",
"url":"/api/4.3.0/channels/statuses/initial",
"status":"500"
}
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:530)
... 28 more

**Comment by ab-20-m** [comment]
You need to follow the instructions for [running Mirth with Java 9+](https://github.com/nextgenhealthcare/connect#java9)

See also discussion [5392](https://github.com/nextgenhealthcare/connect/discussions/5392), [5675](https://github.com/nextgenhealthcare/connect/discussions/5675) and I'm sure there's more that can be found.

**Comment by pacmano1** [comment]
What @ab-20-m said of cousre but also:

@srdotnetdeveloper , next time you post:

- Use code blocks
- Post full platform details (mirth version, opeating system, java version)
- How you installed mirth if applicaable (used the installer, etc.).
