### ISSUE TITLE
[BUG] Ports in Use: NullPointerException

### ISSUE THREAD

**Issue by alcir** [nextgenhealthcare/connect#5849]
**Describe the bug**
If in a channel I select i.e. HTTP as Source, then I click on the Ports in Use button, nothing happens.
In the local Java console I get (full exception attacched).
```
Exception in thread "AWT-EventQueue-2" java.lang.NullPointerException
	at com.mirth.connect.client.ui.util.PortUsageDialog.setPorts(PortUsageDialog.java:127)
	at com.mirth.connect.client.ui.util.PortUsageDialog.<init>(PortUsageDialog.java:54)
...
```

Local Java Distribution/Version: Java 8

Mirth version: 4.3.0
FWIW Oracle Database

In addition, if I Invoke the channels/portsInUse api, I get a list af channels and the related ports.
`curl -s --user adminuser:pwd -k -X GET "https://127.0.0.1:8443/api/channels/portsInUse" -H  "X-Requested-With: test"`

Two additional notes:
I "updated" Mirth from 3.11 version (I mean without dropping the DB or reimporting the channels).
If I delete all the channels, then Ports in Use works.

**Comment by jonbartels** [comment]
See https://github.com/nextgenhealthcare/connect/discussions/5789
