### ISSUE TITLE
[BUG] Mirth Versions 4.4.1 and 4.4.2 custom-lib folder needs to be empty for web service listener channel to start

### ISSUE THREAD

**Issue by clarksss** [nextgenhealthcare/connect#5997]
**Describe the bug**
From the versions I have tested, Mirth Versions 4.4.1 and 4.4.2 **custom-lib** folder needs to be empty for web service listener channel to start

**To Reproduce**
Setup steps (if required). Example:
1. **add any file** to that blank **c:\program files\mirth connect\custom-lib** folder
2.  (I simply tested with a .txt and .jar file)
3. create a new channel with a "Web Service Listener"  - default settings
4. deploy channel and it won't start

1. Go to **c:\program files\mirth connect\custom-lib**
3. Add a file
5. In Mirth Connect, click Settings
6. click the Resources tab
7. click Reload Resource
8. go to (click) Channels on the left menu bar
9. Deploy the Web Service Listener channel
10. Notice the channel does not start.

**Expected behavior**
A channel with Web Service Listener will start after deploying with **custom-lib** having .jar files in there to access and use in integrations.

**Actual behavior**
A channel with Web Service Listener will NOT start after deploying channel with **custom-lib** having .jar files (or any files) in there

**Screenshots**
![image](https://github.com/nextgenhealthcare/connect/assets/151772209/024a264a-ef82-4099-9490-283cc672506b)
![image](https://github.com/nextgenhealthcare/connect/assets/151772209/1d592a86-db3b-4b40-9056-f8d72a4b2ec8)
after file exists in custom-lib folder and resource loaded and channel re-deployed
![image](https://github.com/nextgenhealthcare/connect/assets/151772209/eff3ea93-038b-4460-93b8-5f0fd1a8ee4f)

**Environment (please complete the following information):**
 - OS: Windows Server 2019 Datacenter
 - ![image](https://github.com/nextgenhealthcare/connect/assets/151772209/4a61dcef-c5b4-4de5-b430-e0c70cfd87a1)
 - ![image](https://github.com/nextgenhealthcare/connect/assets/151772209/8f371c6e-f27b-41db-b8ca-1a29ef633ff0)
 - Connect Versions Tested 4.4.1, 4.4.2

**Workaround(s)**
check this box, under the resources tab.. this seemed allow the channel to start.
![image](https://github.com/nextgenhealthcare/connect/assets/151772209/5297ff4f-1969-4ec5-92fa-6552397738f1)

**Additional context**
works in Mirth Connect 3.9.1 with Java 10.0.1  (I have not tested the versions in between 3.9.1 to 4.4.0)

**Comment by clarksss** [comment]
ERROR when trying to start the Channel:

[2023-11-22 10:01:28.898]  ERROR  (com.mirth.connect.server.channel.ErrorTaskHandler:26): com.mirth.connect.donkey.server.StartException: Failed to start channel test web service (b125f74f-fd94-4b46-b277-16bf7077bb43).

	at com.mirth.connect.donkey.server.channel.Channel.start(Channel.java:792)

	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.doDeploy(DonkeyEngineController.java:2031)

	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.execute(DonkeyEngineController.java:1835)

	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:67)

	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException

	at javax.xml.ws.Endpoint.create(Endpoint.java:161)

	at com.mirth.connect.connectors.ws.WebServiceReceiver.onStart(WebServiceReceiver.java:209)

	at com.mirth.connect.donkey.server.channel.SourceConnector.start(SourceConnector.java:106)

	at com.mirth.connect.donkey.server.channel.Channel.start(Channel.java:768)

	... 8 more

**Comment by pacmano1** [comment]
@clarksss did @narupley 's suggestion on your forum post not work?

Forum link for reference for others: https://forums.mirthproject.io/forum/mirth-connect/support/184120-web-service-listener-not-starting-since-upgrade-from-mirth-connect-3-9-1-to-4-4-1

> Most likely that is a bug in JAX-WS. Something like this: https://github.com/jakartaee/jax-ws-api/issues/161
> 
> We're still including the old javax.xml.ws module, so perhaps at some point we should upgrade to the newer jakarta.xml.ws (and probably break a lot of Web Service channels in the process...)
> 
> Anyway you can either uncheck that Default resource in your channel's Summary -> Set Dependencies -> Library Resources
> 
> Or, go to Settings -> Resources and check "Load Parent-First" on the Default resource, which seems to workaround the jax-ws bug too (because it's a classloader issue).

**Comment by clarksss** [comment]
Yes , put a checkmark in there, seemed to get the channel to start !   thanks ! ☺

**Comment by ChristopherSchultz** [comment]
I experienced the same issue moving from Mirth 4.1.1 on Java 8 to Mirth 4.4.2 on Java 11 (Amazon Coretto). I have changed the "Default Resource" (aka `custom-lib`) to *parent-first* behavior and my channels will deploy and start, now.

**Comment by ChristopherSchultz** [comment]
After testing, my SOAP-based services are working exactly as expected after enabling parent-first load-order.

**Comment by narupley** [comment]
Looks like my forum response was already copied above, but yeah, it sounds like this is a defect in the JAX-WS implementation library itself. At some point we should upgrade to the newer jakarta implementation (just a fork/continuation of the javax library I think), where it _looks_ like that has already been fixed.

**Comment by jgarrett4674** [comment]
I had the same issue starting a web service listener with custom-libs loaded when we upgraded to 4.4.1. I added the following to the mirth vmoptions files and it resolved the issue:
-Djavax.xml.ws.spi.Provider=com.sun.xml.ws.spi.ProviderImpl
I found this resolution in https://github.com/jakartaee/jax-ws-api/issues/161
