### ISSUE TITLE
Apple M2 Mirth Connect JDK17 issue

### ISSUE THREAD

**Issue by MatthiasDM** [nextgenhealthcare/connect#6026]
**Describe the bug**
Running Mirth Connect using JDK 17 produces a non working Channels and Dashboard. 
Occurs only on Mac M2 afaik! 

**To Reproduce**
Setup steps (if required). Example:
1. Setup Mirth Connect Administrator Launces to used the bundled JDK17 (or any other JDK17)
2. Check show java console
3. Start Mirth Connect

1. Go to Channels
2. Click on a row in the table
4. View the debug logs.
5. See error

**Additional context**
I need JDK 17 to develop a plugin that uses dependencies compiled with jdk > 8.

**Comment by jonbartels** [comment]
@MatthiasDM what errors are logged?

Is this similar?
https://github.com/nextgenhealthcare/connect/issues/5975

**Comment by MatthiasDM** [comment]
Ah yes it is exactly that.

Using Using JRE version 17.0.6+10-LTS OpenJDK 64-Bit Server VM

Also tried with Zulu JDK, with and without JavaFX.

The only version so far that works is the bundled java 8, but that is too old for my plugin development. 

`java.lang.IllegalArgumentException: column must be valid, was-1
	at org.jdesktop.swingx.JXTreeTable.isHierarchical(JXTreeTable.java:2022)
	at org.jdesktop.swingx.JXTreeTable.getEditingRow(JXTreeTable.java:1162)
	at java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleAt(Unknown Source)
	at java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source)
	at java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source)
	at java.desktop/sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by ab-mg-23** [comment]
Crazy out of left field idea: Can you try disabling all the OSX Accessibility features and see if it still bombs out? The part of the stack trace that caught my attention was:
```
java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleAt(Unknown Source) at
java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source) at
java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source) at
java.desktop/sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(Unknown Source) at 
```

**Comment by jonbartels** [comment]
I looked at this issue. I googled for similar errors. The apparent solution seems to be to add an `if column == -1` test to prevent the error.

I searched the Mirth code to see how it used JXTreeTable.

I can see the code being used in Mirth but it is not clear how that code is actually called. Based on the stack trace and the bug report, "Click on a row in the table", is it the onClick listener? I am not sure how to find it, but I think there is a click handler that is missing the `colIndex == -1` check.

Here is one implementation but its for the header click, not the row click:
https://github.com/nextgenhealthcare/connect/blob/c1bbf981b396279984124adbd50ddb4851b2bc76/client/src/com/mirth/connect/client/ui/SortableTreeTableModel.java#L388

Which class handles the row click for the Channel view?

**Comment by MatthiasDM** [comment]
> Crazy out of left field idea: Can you try disabling all the OSX Accessibility features and see if it still bombs out? The part of the stack trace that caught my attention was:
> 
> ```
> java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleAt(Unknown Source) at
> java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source) at
> java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source) at
> java.desktop/sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(Unknown Source) at 
> ```

I have tried this but that did not work. Any other ideas?

**Comment by jonbartels** [comment]
This issue bit me today. 

I am on an M1 Macbook on Sonoma 14.2. I had an instance fail in the same way as Matthias on Java 17 but it worked fine on Java 8. 

@ARShelleyNextGen - Check out this thread for MacOS support. Short version is that users on M1 and M2 Macs running Sonoma get errors from Mirth under Java 17 from the Launcher but not Java 8. The community is pecking at the issue but it might require the big guns from NextGen. This should also be important to NextGen so Mirth can run on later MacOS systems with modern Java versions.

**Comment by MatthiasDM** [comment]
With regards to the release yesterday of [4.5.0 ](https://github.com/nextgenhealthcare/connect/releases/tag/4.5.0) i saw that from 4.7.0 the minimum java required will be java 11.

Does this mean that if this bug is not fixed in 4.7.0, the application will not work anymore (or at least, not workable) on Apple M2 chips. Because for clarity, this bug occurs with java versions > 8.

**Comment by DevSysEngineer** [comment]
Dear all,

I am having exactly the same problem and my colleagues with the same hardware specifications are also facing the same problem. When I checked the Java console, I found that one error always comes back. When this error occurs, the interface will be slow and not always responsive to my clicks.

Hardware:
15-inch, M2, 2023
OS: Sonoma 14.3.1 (23D60)
Mirth Connect Administrator launcher 1.4.51 Java 17 bundled

```
java.lang.IllegalArgumentException: column must be valid, was-1
	at org.jdesktop.swingx.JXTreeTable.isHierarchical(JXTreeTable.java:2022)
	at org.jdesktop.swingx.JXTreeTable.getEditingRow(JXTreeTable.java:1162)
	at java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleAt(Unknown Source)
	at java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source)
	at java.desktop/sun.lwawt.macosx.CAccessibility$23.call(Unknown Source)
	at java.desktop/sun.lwawt.macosx.LWCToolkit$CallableWrapper.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by pacmano1** [comment]
If any of you set display (scaling) to "Default" and turn off all accessibility settings does this persist?   Curious.   

I mean:

![image](https://github.com/nextgenhealthcare/connect/assets/44065187/ac6d991c-b40c-4e4e-a33d-cf10491d2734)

**Comment by DevSysEngineer** [comment]
Hello @pacmano1,

I configured my display settings to default settings, but still the same problem. 

<img width="515" alt="Scherm­afbeelding 2024-02-21 om 10 14 29" src="https://github.com/nextgenhealthcare/connect/assets/3213947/528d2ef7-63cd-4fc9-9ded-1a3639c81710">

<img width="515" alt="Scherm­afbeelding 2024-02-21 om 10 13 27" src="https://github.com/nextgenhealthcare/connect/assets/3213947/0112dab9-ea86-4c8d-9505-b09da5c08372">

<img width="515" alt="Scherm­afbeelding 2024-02-21 om 10 11 52" src="https://github.com/nextgenhealthcare/connect/assets/3213947/6618cfc6-074c-4c8e-902d-1d6eb3a28180">

**Comment by TSteenhoven** [comment]
@pacmano1 

Is also tried to only use the default text-size, I had it on the highest setting. 
Alas, still the same error as @DevSysEngineer :

<img width="515" alt="Scherm­afbeelding 2024-02-28 om 20 33 51" src="https://github.com/nextgenhealthcare/connect/assets/33696006/4013b88d-eebc-4a6c-8e9e-6859be9f9112">
<img width="520" alt="Scherm­afbeelding 2024-02-28 om 20 34 28" src="https://github.com/nextgenhealthcare/connect/assets/33696006/6fc5819e-c7ec-4af8-9852-5f8477c5ae04">
<img width="522" alt="Scherm­afbeelding 2024-02-28 om 20 34 34" src="https://github.com/nextgenhealthcare/connect/assets/33696006/6db23055-726f-4973-8cff-42f79d9728f0">

**Error:** 
column must be valid, was-1
java.lang.IllegalArgumentException: column must be valid, was-1
at org.jdesktop.swingx.JXTreeTable.isHierarchical(JXTreeTable.java:2022)
at org.jdesktop.swingx.JXTreeTable.getEditingRow(JXTreeTable.java:1162)
at java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleChild(Unknown Source)
at java.desktop/javax.swing.JTable$AccessibleJTable.getAccessibleAt(Unknown Source)
at java.desktop/javax.swing.JTable$AccessibleJTable.valueChanged(Unknown Source)
at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at java.desktop/javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at java.desktop/javax.swing.DefaultListSelectionModel.changeSelection(Unknown Source)
at java.desktop/javax.swing.DefaultListSelectionModel.setSelectionInterval(Unknown Source)
at java.desktop/javax.swing.DefaultListSelectionModel.addSelectionInterval(Unknown Source)
at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.resetRowSelection(Unknown Source)
at org.jdesktop.swingx.JXTreeTable$ListToTreeSelectionModelWrapper.resetRowSelection(JXTreeTable.java:2146)
at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
at java.desktop/javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
at com.mirth.connect.client.ui.editors.BaseEditorPane.addNewElement(BaseEditorPane.java:486)
at com.mirth.connect.client.ui.editors.BaseEditorPane.addNewElement(BaseEditorPane.java:404)
at com.mirth.connect.client.ui.editors.filter.FilterPane.addNewElement(FilterPane.java:198)
at com.mirth.connect.client.ui.editors.BaseEditorPane.doAddNewElement(BaseEditorPane.java:398)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at sun.reflect.misc.Trampoline.invoke(Unknown Source)
at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at java.base/sun.reflect.misc.MethodUtil.invoke(Unknown Source)
at java.desktop/java.beans.EventHandler.invokeInternal(Unknown Source)
at java.desktop/java.beans.EventHandler$1.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.desktop/java.beans.EventHandler.invoke(Unknown Source)
at jdk.proxy2/jdk.proxy2.$Proxy66.actionPerformed(Unknown Source)
at org.jdesktop.swingx.action.BoundAction.actionPerformed(BoundAction.java:231)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
at org.jdesktop.swingx.JXHyperlink.fireActionPerformed(JXHyperlink.java:264)
at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Unknown Source)
at java.desktop/java.awt.Container.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
at java.base/java.security.AccessController.doPrivileged(Unknown Source)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by pacmano1** [comment]
I am dying here also.  I can reproduce it now consistently which is a bit of a help, but still no clue why it is happening.

**Comment by martindruart** [comment]
I have the same problem

**Comment by DevSysEngineer** [comment]
Did someone any status update or fix? It's not workable on a MacBook with this issue.

**Comment by ARShelleyNextGen** [comment]
At this time, we do not have a timeline. I will raise awareness with our product team and see if we can provide any further update related potential consideration of when this will be targeted/planned or addressed. 

cc: @JackieK5

**Comment by hgolov** [comment]
Hi all! I was experiencing the same issue, but then noticed that I could select the Java version on the Launch interface. I selected Java 8 instead of Java 17 and it's now working perfectly! I hope this helps someone.

**Comment by MatthiasDM** [comment]
> Hi all! I was experiencing the same issue, but then noticed that I could select the Java version on the Launch interface. I selected Java 8 instead of Java 17 and it's now working perfectly! I hope this helps someone.

Indeed, this is what i do now, but the problem is that as of version 4.7.0 the minimum java required will be java 11.

**Comment by pacmano1** [comment]
Actually even with Java 8 I still have problems on M2 so it is not a guaranteed fix.

**Comment by MatthiasDM** [comment]
Also this now: https://appleinsider.com/articles/24/03/16/oracle-advises-users-delay-sonoma-update-due-to-java-issue

**Comment by hgolov** [comment]
Thanks for the heads up!

**Comment by DevSysEngineer** [comment]
Any status update on this? We are still facing problems...

**Comment by TSteenhoven** [comment]
For the time being I'm probably forced to go back to our intel Macbooks, as no combination of Mirth and Java (8,11,17) provides a solution to the problem. 

Is there something that we can provide to help with analysis of the problem?

**Comment by yimengZJl** [comment]
I had the same problem

**Comment by DevSysEngineer** [comment]
Did someone any status update?

**Comment by TSteenhoven** [comment]
There resides an intel macbook on my workbench solely for connecting to Mirth Connect, is there a status update?

**Comment by ChristopherSchultz** [comment]
Also https://github.com/nextgenhealthcare/connect/issues/6357

(Apologies for re-reporting something that seems to have at least 4 issues reported, now.)

**Comment by kseniav91** [comment]
Are there any updates?
