### ISSUE TITLE
[BUG] ConcurrentModificationException when using JS Writer

### ISSUE THREAD

**Issue by york-p01033** [nextgenhealthcare/connect#6123]
**Describe the bug**
While using JS writer with 75 Threads getting the following error:

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap.putMapEntries(Unknown Source)
	at java.base/java.util.HashMap.putAll(Unknown Source)
	at com.mirth.connect.donkey.model.message.Message.getMergedConnectorMessage(Message.java:156)
	at com.mirth.connect.donkey.server.channel.Channel.finishMessage(Channel.java:1995)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1871)
	at com.mirth.connect.donkey.server.channel.Channel.processSourceQueue(Channel.java:1952)
	at com.mirth.connect.donkey.server.channel.Channel.run(Channel.java:1938)
	at java.base/java.lang.Thread.run(Unknown Source)

Error was constantly happening, but not on every message. This was done by processing a large amount of messages over a few days time. 

**Expected behavior**
This has not hindered performance or messages in any way, but wanted to report the issue so it could be corrected. Only seeing the error in the server log while messages are processing. 

**Environment (please complete the following information):**
 - OS: Linux
 - Java Distribution/Version: OpenJDK 17
 - Connect Version: 4.4.1

**Workaround(s)**
N/A

**Additional context**
Seems to be happening in donkey/src/main/java/com/mirth/connect/donkey/model/message/Message.java getMergedConnectorMessage()

Similar Issue to:
https://github.com/nextgenhealthcare/connect/issues/243

**Comment by jonbartels** [comment]
What is the code that your JS Writer is executing in the filters, transformer, response and the JS Writer itself?

What logs do you get from `mirth.log` from the server?

Show your queue and threading settings please.

#243 is similar in that it is a concurrent modification exception but that goes back to 2006 and is DB related. Mirth today is radically different than it was in '06. 

I suggest moving this to a Discussion to determine the problem, then recreate an issue if the root cause is a Mirth bug and not a channel code issue.

**Comment by is-simon** [comment]
@jonbartels I also encountered this problem with an heavy loaded channel:

`
[2025-01-06 16:30:22.369]  ERROR  (com.mirth.connect.donkey.server.channel.Channel:1375): Error processing message in channel <CHANNEL_NAME> (<CHANNEL_ID>).
com.mirth.connect.donkey.server.channel.ChannelException: 
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1325)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:194)
	at com.mirth.connect.donkey.server.channel.SourceConnector.dispatchRawMessage(SourceConnector.java:172)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:681)
	at com.mirth.connect.connectors.tcp.TcpReceiver$TcpReader.call(TcpReceiver.java:512)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap$EntryIterator.next(Unknown Source)
	at java.base/java.util.HashMap.putMapEntries(Unknown Source)
	at java.base/java.util.HashMap.putAll(Unknown Source)
	at com.mirth.connect.donkey.model.message.Message.getMergedConnectorMessage(Message.java:155)
	at com.mirth.connect.donkey.server.channel.Channel.finishMessage(Channel.java:1995)
	at com.mirth.connect.donkey.server.channel.Channel.process(Channel.java:1871)
	at com.mirth.connect.donkey.server.channel.Channel.dispatchRawMessage(Channel.java:1302)
	... 8 more
`

It is not related to the JSWriter (which I'm not using). It's not really realistic for me to analyse all the javascript code since the channel has 20+ destinations and the problem occurs only a couple times a month over millions of messages.

If we take a look at the [Message#getMergedConnectorMessage](https://github.com/nextgenhealthcare/connect/blob/development/core-models/src/com/mirth/connect/donkey/model/message/Message.java#L116), you can see that the function is built in a way that it should be thread safe, and it is not thread safe:

```java
public ConnectorMessage getMergedConnectorMessage() {
    if (mergedConnectorMessage == null) {
        mergedConnectorMessage = new ConnectorMessage();
        
        // ... build the message
    }

    return mergedConnectorMessage;
}
```
without the `synchronized` keyword, 2 threads could potentially enter the `if (mergedConnectorMessage == null)` condition on the same `Message` instance, which is not wanted I'm sure. Making the function thread-safe would take a second and would fix this issue.
