### ISSUE TITLE
[BUG] Error when adding custom metadata

### ISSUE THREAD

**Issue by mikeyw** [nextgenhealthcare/connect#6183]
**Describe the bug**
Channel has a File Reader source connector. After adding the "originalFilename" Source Map variable to channel custom metadata, an error is thrown when opening the Channel Messages viewer from the Dashboard.

**To Reproduce**

1. Set up a channel with a File Reader source connector
2. Add a new custom metadata value for the originalFilename source map variable. I used "ORIGINAL_FILENAME".
3. Save and deploy the channel
4. From the Dashboard, open the the Channel Messages viewer for the new message.

When Channel Messages is opened, the following error is displayed. Clicking OK and then clicking Search will display messages.

```
Method failed: HTTP/1.1 500 Server Error
com.mirth.connect.client.core.ClientException: Method failed: HTTP/1.1 500 Server Error
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:533)
at com.mirth.connect.client.core.ServerConnection.executeSync(ServerConnection.java:257)
at com.mirth.connect.client.core.ServerConnection.apply(ServerConnection.java:167)
at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255)
at org.glassfish.jersey.client.JerseyInvocation$3.call(JerseyInvocation.java:722)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:718)
at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:459)
at org.glassfish.jersey.client.proxy.WebResourceFactory.invoke(WebResourceFactory.java:379)
at jdk.proxy2/jdk.proxy2.$Proxy90.getMessages(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at com.mirth.connect.client.core.Client$2.invoke(Client.java:273)
at jdk.proxy2/jdk.proxy2.$Proxy90.getMessages(Unknown Source)
at com.mirth.connect.client.core.Client.getMessages(Client.java:1861)
at com.mirth.connect.client.core.PaginatedMessageList.getItems(PaginatedMessageList.java:68)
at com.mirth.connect.util.PaginatedList.loadPageNumber(PaginatedList.java:76)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$9.doInBackground(MessageBrowser.java:930)
at com.mirth.connect.client.ui.browsers.message.MessageBrowser$9.doInBackground(MessageBrowser.java:923)
at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.mirth.connect.client.core.EntityException: {
"servlet":"org.glassfish.jersey.servlet.ServletContainer-1baae01d",
"message":"Request failed.",
"url":"/api/4.4.1/channels/ff9decb8-a128-4027-b406-bd118951cb3a/messages/_search",
"status":"500"
}
at com.mirth.connect.client.core.ServerConnection.handleResponse(ServerConnection.java:530)
... 29 more
```

**Expected behavior**
Channel Messages should open and display messages

**Actual behavior**
An error message is displayed when opening Channel Messages

**Environment (please complete the following information):**
 - OS: Windows 2019 server
 - Java Distribution/Version: Oracle JDK 20
 - Connect Version: 4.4.1
 - Database: PostgreSQL 15

**Workaround(s)**
After clicking OK on the error message, clicking Search displays messages.

**Additional context**
This is happening to me when using a File Reader source, and putting a Source Map variable in custom metadata.

**Comment by pacmano1** [comment]
I don't see this.  (on linux, mirth 4.5, java 21, postgres 14.10)
