### ISSUE TITLE
Control Characters Halt Message Processing

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#620]
If control characters are present in the message it can halt message processing.  Workaround is to preprocess message so that control characters besides those used by HL7 are removed.  This occurred using FTP source and no strict parsing

Workaround preprocessor script:
// remove control characters that kill the parser
message = message.replace(/[\x00-\x09\x0E-\x1f]/g,"");

Error:

com.webreach.mirth.model.converters.SerializerException: ca.uhn.hl7v2.HL7Exception: IOException serializing XML document to string
	at com.webreach.mirth.model.converters.ER7Serializer.toXML(ER7Serializer.java:101)
	at com.webreach.mirth.model.converters.ER7Serializer.toXML(ER7Serializer.java:50)
	at com.webreach.mirth.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:17)
	at com.webreach.mirth.server.mule.adaptors.Adaptor.getMessage(Adaptor.java:41)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:250)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
	at com.webreach.mirth.server.mule.providers.ftp.FtpMessageReceiver.processFile(FtpMessageReceiver.java:207)
	at com.webreach.mirth.server.mule.providers.ftp.FtpMessageReceiver$1.run(FtpMessageReceiver.java:83)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)
Caused by: ca.uhn.hl7v2.HL7Exception: IOException serializing XML document to string
	at ca.uhn.hl7v2.parser.XMLParser.doEncode(XMLParser.java:266)
	at ca.uhn.hl7v2.parser.Parser.encode(Parser.java:221)
	at com.webreach.mirth.model.converters.ER7Serializer.toXML(ER7Serializer.java:99)
	... 20 more
Caused by: java.io.IOException: The character '' is an invalid XML character
	at org.apache.xml.serialize.BaseMarkupSerializer.fatalError(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.surrogates(Unknown Source)
	at org.apache.xml.serialize.XMLSerializer.printText(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.characters(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.serializeNode(Unknown Source)
	at org.apache.xml.serialize.XMLSerializer.serializeElement(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.serializeNode(Unknown Source)
	at org.apache.xml.serialize.XMLSerializer.serializeElement(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.serializeNode(Unknown Source)
	at org.apache.xml.serialize.XMLSerializer.serializeElement(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.serializeNode(Unknown Source)
	at org.apache.xml.serialize.XMLSerializer.serializeElement(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.serializeNode(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.serializeNode(Unknown Source)
	at org.apache.xml.serialize.BaseMarkupSerializer.serialize(Unknown Source)
	at ca.uhn.hl7v2.parser.XMLParser.doEncode(XMLParser.java:263)
	... 22 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-612
Reporter: espinoj
Created: 2007-11-08T08:46:12.000-0800

**Comment by rbeckman-nextgen** [comment]
Try using the non-strict parser or preprocessor work-around. Non-standard characters are not supported by Hapi's parser.

Imported Comment. Original Details:
Author: chrisl
Created: 2007-11-08T16:41:35.000-0800
