### ISSUE TITLE
[IDEA] Advance Alerting Plugin

### ISSUE THREAD

**Issue by shanedewitt** [nextgenhealthcare/connect#6215]
**Is your feature request related to a problem? Please describe.**
The Advance Alerting plugin can pickup channel states of starting, started, stopping and stopped. Can you also make it pickup channel state of paused?

**Describe your use case**
I was unaware that a File Reader (SFTP) connector can enter a paused state when it can no longer retrieve files due to network issue. Adding this new alert state would help with troubleshooting and resolution of business processes.

**Describe the solution you'd like**
Add new channel state in alert to trigger when channel is paused or make File Reader resume when resource becomes available again.

**Comment by kirbykn2** [comment]
Interesting, I have never seen a channel change states Started, Stopped, or Paused because of a network issue.  Have you been able to recreate this?

**Comment by shanedewitt** [comment]
It may have something to do with clustering. Here is the event log error, it references the channel that was paused.

`com.mirth.connect.plugins.clustering.server.core.RoleControllerException: Failed to start polling role.

at com.mirth.connect.plugins.clustering.server.PollingRoleController.startRole(SourceFile:36)

at com.mirth.connect.plugins.clustering.server.core.RoleManager$RoleStartTask.run(SourceFile:283)

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

at java.util.concurrent.FutureTask.run(FutureTask.java:266)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)
Caused by: com.mirth.connect.plugins.clustering.server.ChannelTaskErrorHandler$ChannelErrors: Errors occurred with the following channels/connectors: 3cfebedb-1269-4b26-a632-d37546efb4ed

at com.mirth.connect.plugins.clusteringadvanced.server.AdvancedNodeEngineController.resumePollingChannels(SourceFile:1081)

at com.mirth.connect.plugins.clustering.server.ClusterEngineController.startPolling(SourceFile:204)

at com.mirth.connect.plugins.clustering.server.PollingRoleController.startRole(SourceFile:34)

... 6 more`

**Comment by RunnenLate** [comment]
Alerting doesn't work properly while clustered, I'm still waiting on a resolution for this 2+ years on: https://github.com/nextgenhealthcare/connect/issues/5415
