### ISSUE TITLE
[BUG] Webservice Listner not work. Error while searching for service [javax.xml.ws.spi.Provider]

### ISSUE THREAD

**Issue by jacsonsoares** [nextgenhealthcare/connect#6245]
**Describe the bug**
When creating and publishing a connector with "Source Type: Webservice Listener"

**Environment (please complete the following information):**
 - OS: Doker Linux (Ubuntu)
 - Java Distribution/Version OpenJDK 11
 - Connect Version [4.5.0]

**To Reproduce**
1. Install Mirth Connect version 4.5
2. Create a "Webservice Listener" connector
3. Publish the connector.

**Workaround(s)**
Are there one or more workarounds for this issue currently?

1. Go to 'Dashboard.'
2. See error
Error: [2024-07-05 15:18:31.991]  ERROR  (com.mirth.connect.server.channel.ErrorTaskHandler:26): com.mirth.connect.donkey.server.StartException: Failed to start channel SOAP (8510eff8-36ac-4b8c-be98-2445c819ec32).

	at com.mirth.connect.donkey.server.channel.Channel.start(Channel.java:792)

	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.doDeploy(DonkeyEngineController.java:2031)

	at com.mirth.connect.server.controllers.DonkeyEngineController$DeployTask.execute(DonkeyEngineController.java:1835)

	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:67)

	at com.mirth.connect.server.channel.ChannelTask.call(ChannelTask.java:16)

	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.xml.ws.WebServiceException: Error while searching for service [javax.xml.ws.spi.Provider]

	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:61)

	at javax.xml.ws.spi.FactoryFinder$1.createException(FactoryFinder.java:58)

	at javax.xml.ws.spi.ServiceLoaderUtil.firstByServiceLoader(ServiceLoaderUtil.java:70)

	at javax.xml.ws.spi.FactoryFinder.find(FactoryFinder.java:89)

	at javax.xml.ws.spi.Provider.provider(Provider.java:96)

	at javax.xml.ws.Endpoint.create(Endpoint.java:161)

	at com.mirth.connect.connectors.ws.WebServiceReceiver.onStart(WebServiceReceiver.java:209)

	at com.mirth.connect.donkey.server.channel.SourceConnector.start(SourceConnector.java:106)

	at com.mirth.connect.donkey.server.channel.Channel.start(Channel.java:768)

	... 8 more
Caused by: java.util.ServiceConfigurationError: javax.xml.ws.spi.Provider: com.sun.xml.ws.spi.ProviderImpl not a subtype

	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)

	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)

	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)

	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)

	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)

	at javax.xml.ws.spi.ServiceLoaderUtil.firstByServiceLoader(ServiceLoaderUtil.java:63)

**Comment by pacmano1** [comment]
Fresh install:

1. Ubuntu 20 
2. openjdk-21-jre-headless
3. Mirth 4.5.

Create channel, web service listener, do not update anything but channel name, save and deploy.   Works fine.

Probably need more details.

**Comment by pacmano1** [comment]
For that matter worked fine on Docker also.  The official image from Nextgen.

**Comment by jacsonsoares** [comment]
The test was done with the official Nextgen image and unfortunately it didn't work.

**Comment by jacsonsoares** [comment]
> Fresh install:
> 
> 1. Ubuntu 20
> 2. openjdk-21-jre-headless
> 3. Mirth 4.5.
> 
> Create channel, web service listener, do not update anything but channel name, save and deploy. Works fine.
> 
> Probably need more details.



> For that matter worked fine on Docker also. The official image from Nextgen.

The test was done with the official Nextgen image and unfortunately it didn't work.

**Comment by pacmano1** [comment]
My follow up post said on docker it was fine also.

![image](https://github.com/nextgenhealthcare/connect/assets/44065187/7fb2a9db-5036-4267-9027-0f9dba441a09)

**Comment by jacsonsoares** [comment]
> Fresh install:
> 
> 1. Ubuntu 20
> 2. openjdk-21-jre-headless
> 3. Mirth 4.5.
> 
> Create channel, web service listener, do not update anything but channel name, save and deploy. Works fine.
> 
> Probably need more details.

Now yes, it worked perfectly with this script
Thank you @pacmano1 !!!

Dockerfile:

```shell

# Use the official Ubuntu 20.04 image as the base image
FROM ubuntu:20.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt-get update && \
    apt-get install -y openjdk-21-jre-headless wget gnupg && \
    rm -rf /var/lib/apt/lists/*

# Set the Java environment variables
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Download and install Mirth Connect 4.5
RUN wget -O /tmp/mirthconnect-4.5.0.b3012-unix.tar.gz https://s3.amazonaws.com/downloads.mirthcorp.com/connect/4.5.0.b3012/mirthconnect-4.5.0.b3012-unix.tar.gz && \
    tar -xzf /tmp/mirthconnect-4.5.0.b3012-unix.tar.gz -C /opt && \
    rm /tmp/mirthconnect-4.5.0.b3012-unix.tar.gz

# Set Mirth Connect environment variables
ENV MIRTH_HOME="/opt/Mirth Connect"

# Create a script to start Mirth Connect
RUN echo '#!/bin/bash\n/opt/Mirth\\ Connect/mcservice start\nwhile true; do sleep 60; done' > /opt/start-mirth.sh && \
    chmod +x /opt/start-mirth.sh

# Expose the necessary ports for Mirth Connect
EXPOSE 8443

# Define the entry point for the container
ENTRYPOINT ["/opt/start-mirth.sh"]
```

**Comment by jacsonsoares** [comment]
@pacmano1, the connector is listening correctly, but when I send a message it shows this error: 
javax.xml.soap.SOAPException: Unable to create SAAJ meta-factory: Provider com.sun.xml.internal.messaging.saaj.soap.SAAJMetaFactoryImpl not found

Please, if you know how I can solve it, I would be very grateful.

**Comment by pacmano1** [comment]
Oddly, I think java 8 is the only one that works.   I suspect some bundled jars in the mirth installer break with later java releases.    I am not a java expert - but was able to break it like you did and only fix was reverting to openjdk-8-jdk-headless.

**Comment by odoodo** [comment]
We are facing the same issue w/ Mirth 4.5.0 under Windows Server 2022 & Java 21.

Is there any fix for this itmt other than reverting to Java 8 (which unfortunately is no option for us)?
