### ISSUE TITLE
Missing JMS jar does not log an event

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#630]
Missing JMS jar does not log an event

Imported Issue. Original Details:
Jira Issue Key: MIRTH-622
Reporter: brendanh
Created: 2007-11-15T17:26:45.000-0800

**Comment by rbeckman-nextgen** [comment]
Tested locally, received this exception:

Caused by: java.lang.ClassNotFoundException: org.apache.activemq.ActiveMQConnectionFactory
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClassInternal(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at com.webreach.mirth.connectors.jms.JmsConnector.createConnectionFactory(JmsConnector.java:170)
	... 11 more


Imported Comment. Original Details:
Author: geraldb
Created: 2007-11-20T15:39:37.000-0800
