### ISSUE TITLE
[BUG] When trying to access the Mirth channel I am facing a Java Heap space issue

### ISSUE THREAD

**Issue by harvindernanda** [nextgenhealthcare/connect#6343]
While I can access the Mirth dashboard successfully I am unable to access the Mirth channel 

Issue seen as below:
java.lang.OutOfMemoryError: Java heap space
com.mirth.connect.client.core.ClientException: java.lang.OutOfMemoryError: Java heap space
at com.mirth.connect.client.core.Client$2.invoke(Client.java:294)
at com.sun.proxy.$Proxy66.getChannelSummary(Unknown Source)
at com.mirth.connect.client.core.Client.getChannelSummary(Client.java:1063)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:614)
at com.mirth.connect.client.ui.ChannelPanel.retrieveChannels(ChannelPanel.java:608)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:429)
at com.mirth.connect.client.ui.ChannelPanel$1.doInBackground(ChannelPanel.java:426)
at com.mirth.connect.client.ui.QueuingSwingWorker.doInBackground(QueuingSwingWorker.java:97)

We have tried re-starting the servers as well as increased the heap space to 4GB at the time of launch too but this did not help

**Comment by jonbartels** [comment]
This should be a Discussion not an Issue.

2-4GB on the client should be more than enough.
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/2e081152-c94e-4a93-a11f-eb08696f485d">

When you get the client error you posted, do you also see a server side error in `mirth.log`?
