### ISSUE TITLE
[BUG] Installer 5.4.2 on Windows with custom Destination Directory throws error

### ISSUE THREAD

**Issue by michael-kuss** [nextgenhealthcare/connect#6354]
**Describe the bug**
If we try to install the mirthconnect-4.5.2.b363-windows-x64 and use a custom directory on Windows Server 2022  we cannot get past the "Select Destination Directory".

**To Reproduce**
1. Double click installer
2. accept license
3. Enter directory e.g. C:\myinstallationpath\4.5.2
4. Click next
5. Popup that we are not in Program Files -> YES
6. Error -> 
![grafik](https://github.com/user-attachments/assets/f189fe52-73cc-42f2-9851-a5347d412229)

```
Exception:

In screen "Select Destination Directory [Installation location]", property "Validation expression":
java.lang.IllegalArgumentException: main message must not be null
	at com.install4j.runtime.alert.Alert.create(Alert.java:30)
	at com.install4j.runtime.installer.frontend.GUIHelper.showMessageInternal(GUIHelper.java:259)
```

**Expected behavior**
The installation should go on with the choosen directory

**Actual behavior**
You cannot get past this point of the installer

**Environment (please complete the following information):**
 - OS: Windows Server 2022
 - Corretto-17.0.13.11.1 (build 17.0.13+11-LTS)
 - Connect Version 5.5.2

**Comment by michael-kuss** [comment]
WORKAROUND:
- Install 4.5.0 and then upgrade installation to 4.5.2

**Comment by michael-kuss** [comment]
Same for the administrator launcher 1.4.2

**Comment by waslangewaehrt** [comment]
When can we expect a fix for this bug? 
Still happening with 'mirthconnect-4.5.2.b363-windows-x64',

**Comment by pacmano1** [comment]
The source code for the installer is not public. 

I am not sure I've ever seen Nextgen indicate their release plan.

If you license Mirth, I would open a support ticket.  If you don't, typically you just have to wait and see.

**Comment by pacmano1** [comment]
I did not have this problem with Corretto 21

1. Clean install of 2022.
2. Coretto 21 (not 17).
3. Installed to `c:\Mirth Connect` using same installer you referenced.

No problems.

**Comment by pacmano1** [comment]
I did not have this problem with Corretto 17.

1. Clean install of 2022.
2. Coretto 17.
3. Installed to `c:\Mirth Connect` using same installer you referenced.

No problems.

**Comment by pacmano1** [comment]
No problems with the Mirth Admin Launcher install also.

**Comment by pacmano1** [comment]
No problems with a nested directory also.  `c:\mirthism\4.5.2`

Note that I do run the installer with `Run as Administrator`.
