### ISSUE TITLE
Concurrent Modification Exception

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#696]
An old friend has shown up again...  Moderate load (had a few thousand messages backed up in persistent queues).  Got a bunch of these exceptions when Mirth 1.7 started processing them.

Very similar to MIRTH-224 I reported in the 1.3 days - the HashMap bit looks almost identical.

Thanks, Mike

ERROR 2007-12-28 09:42:38,708 [1dce3c4f-8c03-4563-a1a8-6cc2c660b4a3_destination_9_connector.dispatcher.10] com.webreach.mirth.server.controllers.MessageObjectController: could not log message: id=3bc06772-340a-4975-bbe4-f1bbeba03f73
com.ibatis.common.jdbc.exception.NestedSQLException:
--- The error occurred in postgres/postgres-message.xml.
--- The error occurred while applying a parameter map.
--- Check the Message.insert-message-param.
--- Check the parameter mapping for the 'responseMap' property.
--- Cause: java.util.ConcurrentModificationException
Caused by: java.util.ConcurrentModificationException
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:94)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:212)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:184)
        at com.webreach.mirth.server.controllers.MessageObjectController.setStatus(MessageObjectController.java:570)
        at com.webreach.mirth.server.controllers.MessageObjectController.setSuccess(MessageObjectController.java:540)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.routeTemplatedMessage(VMMessageDispatcher.java:234)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.doDispatch(VMMessageDispatcher.java:185)
        at org.mule.providers.AbstractMessageDispatcher$Worker.run(AbstractMessageDispatcher.java:257)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Thread.java:595)
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
        at java.util.HashMap$EntryIterator.next(HashMap.java:829)
        at java.util.HashMap$EntryIterator.next(HashMap.java:827)
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:23)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        ... 14 more

Caused by:
java.util.ConcurrentModificationException
        at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
        at java.util.HashMap$EntryIterator.next(HashMap.java:829)
        at java.util.HashMap$EntryIterator.next(HashMap.java:827)
        at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:23)
        at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
        at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
        at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
        at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
        at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
        at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
        at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
        at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:212)
        at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:184)
        at com.webreach.mirth.server.controllers.MessageObjectController.setStatus(MessageObjectController.java:570)
        at com.webreach.mirth.server.controllers.MessageObjectController.setSuccess(MessageObjectController.java:540)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.routeTemplatedMessage(VMMessageDispatcher.java:234)
        at com.webreach.mirth.connectors.vm.VMMessageDispatcher.doDispatch(VMMessageDispatcher.java:185)
        at org.mule.providers.AbstractMessageDispatcher$Worker.run(AbstractMessageDispatcher.java:257)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Thread.java:595)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-688
Reporter: mnowlin
Created: 2007-12-30T21:56:24.000-0800

**Comment by rbeckman-nextgen** [comment]
OK, maybe not identical...  (Just looked at the first few lines - it's late.)  :)


Imported Comment. Original Details:
Author: mnowlin
Created: 2007-12-30T22:00:26.000-0800

**Comment by rbeckman-nextgen** [comment]
Good find! It appears to be an issue with the MapTypeHandler class that we use to map our HashMap to the database. 

Imported Comment. Original Details:
Author: chrisl
Created: 2007-12-31T00:21:50.000-0800

**Comment by rbeckman-nextgen** [comment]
Changed HashMap's in the MessageObject to ConcurrentHashMap's.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-01-02T16:29:39.000-0800
