### ISSUE TITLE
Exception Deploying Channel when transactional endpoints are activated

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#697]
When defining a Channel, with the following parameters:

Summary
Incoming Data: HL7 v2.X
Transactional Endpoints: OFF

Source:
Connector Type: File Reader

Destination (1):
Connector Type: Database Writer

(all other parameters are by default or typical values)

Seems to work fine, no errors found when deploying this channel.

When changing the "use transactional endpoints" to ON, when deploying the channel, the following exception is raised:

--------------------------------------------------------
10:56:57,003 INFO  [VMConnector] removing listener on endpointUri: vm://71228e7a-5bfa-4f83-8a02-0440e78038d1
10:56:57,004 INFO  [FileConnector] removing listener on endpointUri: file:///opt/Mirth/data/incoming
10:56:57,004 INFO  [SedaModel] mule 71228e7a-5bfa-4f83-8a02-0440e78038d1 has been stopped successfully
10:56:57,301 INFO  [JdbcConnector] Stopping Connector: com.webreach.mirth.connectors.jdbc.JdbcConnector
10:56:57,302 INFO  [JdbcConnector] Disconnected: com.webreach.mirth.connectors.jdbc.JdbcConnector@e6affc
10:56:57,302 INFO  [JdbcConnector] Connector com.webreach.mirth.connectors.jdbc.JdbcConnector has been stopped
10:56:57,302 INFO  [FileConnector] Stopping Connector: com.webreach.mirth.connectors.file.FileConnector
10:56:57,302 INFO  [FileConnector] Disconnected: com.webreach.mirth.connectors.file.FileConnector@7e6fc
10:56:57,302 INFO  [FileConnector] Connector com.webreach.mirth.connectors.file.FileConnector has been stopped
10:56:57,302 INFO  [VMConnector] Stopping Connector: com.webreach.mirth.connectors.vm.VMConnector
10:56:57,302 INFO  [VMConnector] Disconnected: com.webreach.mirth.connectors.vm.VMConnector@1a022e
10:56:57,302 INFO  [VMConnector] Connector com.webreach.mirth.connectors.vm.VMConnector has been stopped
10:56:57,303 INFO  [MuleManager] Connectors have been stopped successfully
10:56:57,303 INFO  [MuleManager] Stopping agents...
10:56:57,306 INFO  [MuleManager] Agents Successfully Stopped
10:56:57,306 INFO  [TransactionalQueueManager] Stopping ResourceManager
10:56:57,306 INFO  [TransactionalQueueManager] Stopped ResourceManager
10:56:57,307 INFO  [SedaModel] Component MessageSink has been stopped successfully
10:56:57,307 INFO  [SedaModel] Component 71228e7a-5bfa-4f83-8a02-0440e78038d1 has been stopped successfully
10:56:57,307 INFO  [JdbcConnector] Disposing Connector: com.webreach.mirth.connectors.jdbc.JdbcConnector
10:56:57,307 INFO  [JdbcConnector] Connector com.webreach.mirth.connectors.jdbc.JdbcConnector has been disposed.
10:56:57,307 INFO  [FileConnector] Disposing Connector: com.webreach.mirth.connectors.file.FileConnector
10:56:57,308 INFO  [FileConnector] Connector com.webreach.mirth.connectors.file.FileConnector has been disposed.
10:56:57,308 INFO  [VMConnector] Disposing Connector: com.webreach.mirth.connectors.vm.VMConnector
10:56:57,308 INFO  [VMConnector] Connector com.webreach.mirth.connectors.vm.VMConnector has been disposed.
10:56:57,309 INFO  [SedaModel] MessageSink has been destroyed successfully
10:56:57,309 INFO  [SedaModel] 71228e7a-5bfa-4f83-8a02-0440e78038d1 has been destroyed successfully
10:56:57,309 INFO  [MuleManager] disposing agents...
10:56:57,312 INFO  [MuleManager] Agents Successfully Disposed
10:56:58,471 INFO  [MuleManager] Transformer ByteArrayToString has been initialised successfully
10:56:58,472 INFO  [MuleManager] Transformer JMSMessageToObject has been initialised successfully
10:56:58,473 INFO  [MuleManager] Transformer StringToByteArray has been initialised successfully
10:56:58,473 INFO  [MuleManager] Transformer SOAPRequestToString has been initialised successfully
10:56:58,474 INFO  [MuleManager] Transformer ResultMapToXML has been initialised successfully
10:56:58,475 INFO  [MuleManager] Transformer ObjectToString has been initialised successfully
10:56:58,475 WARN  [NoActionTransformer] java.lang.Object has been added as an exceptable sourcetype to this transformer, there will no source type checking on this transformer
10:56:58,475 INFO  [MuleManager] Transformer NoActionTransformer has been initialised successfully
10:56:58,476 INFO  [MuleManager] Transformer HttpStringToXML has been initialised successfully
10:56:58,477 INFO  [MuleManager] Transformer HttpRequestToString has been initialised successfully
10:56:58,481 INFO  [MuleManager] Transformer feaf3d5e-f332-4c89-a4c4-321dc9e4bb7e_source_preprocessor has been initialised successfully
10:56:58,502 INFO  [MuleManager] Transformer feaf3d5e-f332-4c89-a4c4-321dc9e4bb7e_source_transformer has been initialised successfully
10:56:58,561 INFO  [MuleManager] Transformer feaf3d5e-f332-4c89-a4c4-321dc9e4bb7e_destination_1_transformer has been initialised successfully
10:56:58,606 ERROR [Digester] Begin event threw exception
org.apache.commons.beanutils.ConversionException: com.webreach.mirth.server.mule.providers.jdbc.JdbcTransactionFactory
        at org.mule.config.converters.TransactionFactoryConverter.convert(TransactionFactoryConverter.java:53)
        at org.apache.commons.beanutils.ConvertUtilsBean.convert(ConvertUtilsBean.java:428)
        at org.apache.commons.beanutils.BeanUtilsBean.setProperty(BeanUtilsBean.java:1002)
        at org.apache.commons.beanutils.BeanUtilsBean.populate(BeanUtilsBean.java:811)
        at org.apache.commons.beanutils.BeanUtils.populate(BeanUtils.java:298)
        at org.apache.commons.digester.SetPropertiesRule.begin(SetPropertiesRule.java:251)
        at org.mule.config.builders.MuleXmlConfigurationBuilder$ExtendedMuleSetPropertiesRule.begin(MuleXmlConfigurationBuilder.java:1017)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1361)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1685)
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
        at com.webreach.mirth.server.Mirth.startMule(Mirth.java:229)
        at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:186)
        at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
Caused by: java.lang.ClassNotFoundException: com.webreach.mirth.server.mule.providers.jdbc.JdbcTransactionFactory
        at org.mule.util.ClassHelper.loadClass(ClassHelper.java:221)
        at org.mule.config.converters.TransactionFactoryConverter.convert(TransactionFactoryConverter.java:50)
        ... 24 more
10:56:58,609 WARN  [Mirth] Error deploying channels.
org.mule.config.ConfigurationException: Failed to parse configuration resource "/opt/Mirth/jboss-4.2.0.GA/server/mirth/deploy/mirth.sar/conf/mule-config.xml" (org.mule.config.ConfigurationException)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:196)
        at com.webreach.mirth.server.Mirth.startMule(Mirth.java:229)
        at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:186)
        at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
Caused by: org.mule.config.ConfigurationException: Failed to parse configuration resource "/opt/Mirth/jboss-4.2.0.GA/server/mirth/deploy/mirth.sar/conf/mule-config.xml"
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:121)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:202)
        at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
        ... 3 more
Caused by: org.apache.commons.beanutils.ConversionException: com.webreach.mirth.server.mule.providers.jdbc.JdbcTransactionFactory
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2919)
        at org.apache.commons.digester.Digester.createSAXException(Digester.java:2945)
        at org.apache.commons.digester.Digester.startElement(Digester.java:1364)
        at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
        at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1685)
        at org.mule.config.builders.AbstractDigesterConfiguration.process(AbstractDigesterConfiguration.java:119)
        ... 5 more
10:57:00,108 ERROR [STDERR] 02-ene-2008 10:57:00 ClientCommunicatorAdmin restart
ADVERTENCIA: Failed to restart: java.io.IOException: Failed to get a RMI stub: javax.naming.NameNotFoundException: server
10:57:00,111 ERROR [STDERR] 02-ene-2008 10:57:00 ClientCommunicatorAdmin Checker-run
ADVERTENCIA: Failed to check connection: java.rmi.NoSuchObjectException: no such object in table
10:57:00,112 ERROR [STDERR] 02-ene-2008 10:57:00 ClientCommunicatorAdmin Checker-run
ADVERTENCIA: stopping
10:57:01,661 ERROR [STDERR] 02-ene-2008 10:57:01 ClientCommunicatorAdmin restart
ADVERTENCIA: Failed to restart: java.io.IOException: Failed to get a RMI stub: javax.naming.NameNotFoundException: server
10:57:01,664 ERROR [STDERR] 02-ene-2008 10:57:01 ClientCommunicatorAdmin Checker-run
ADVERTENCIA: Failed to check connection: java.rmi.NoSuchObjectException: no such object in table
10:57:01,664 ERROR [STDERR] 02-ene-2008 10:57:01 ClientCommunicatorAdmin Checker-run
ADVERTENCIA: stopping
--------------------------------------------------------

BTW: What is the exactly meaning of "transactional endpoints" and "syncronize channel" options ?

Imported Issue. Original Details:
Jira Issue Key: MIRTH-689
Reporter: quimicefa
Created: 2008-01-02T02:13:26.000-0800

**Comment by rbeckman-nextgen** [comment]
Good find, thank you!

Transactional Endpoints: If you have multiple database destinations, they will be wrapped in a transaction (if one fails then they are all rolled back).

Synchronize Channel: Ensures all destinations are executed in order. Message is sent to Destination 1 then Mirth waits for the response before sending to Destination 2-N.



Imported Comment. Original Details:
Author: chrisl
Created: 2008-01-04T09:53:38.000-0800

**Comment by rbeckman-nextgen** [comment]
Refactored out classname and pointed to correct com.webreach.mirth.connectors.jdbc.JdbcTransactionFactory class

Imported Comment. Original Details:
Author: chrisl
Created: 2008-01-09T01:33:50.000-0800
