### ISSUE TITLE
Error Deploying valid channels

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#699]
I recently upgraded to Version 1.7.0.3191.  When trying to deploy channels, I receive this error:

java.lang.Exception: com.webreach.mirth.server.MirthJavascriptTransformerException: 
SCRIPT SOURCE:	Deploy
LINE NUMBER:	28
LINE SOURCE:	doScript()
DETAILS:	missing } after function body
	at com.webreach.mirth.server.util.JavaScriptUtil.compileScript(JavaScriptUtil.java:144)
	at com.webreach.mirth.server.controllers.ConfigurationController.compileScripts(ConfigurationController.java:322)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:225)
	at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:187)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:117)
Caused by: com.webreach.mirth.server.MirthJavascriptTransformerException: 
SCRIPT SOURCE:	Deploy
LINE NUMBER:	28
LINE SOURCE:	doScript()
DETAILS:	missing } after function body
	at com.webreach.mirth.server.util.JavaScriptUtil.compileScript(JavaScriptUtil.java:143)
	... 4 more

{}

Imported Issue. Original Details:
Jira Issue Key: MIRTH-691
Reporter: afterdark23
Created: 2008-01-03T06:04:16.000-0800

**Comment by rbeckman-nextgen** [comment]
Can you post your channel? Do you have any transformers or filters with code that is commented out or a comment on the last line?

Imported Comment. Original Details:
Author: chrisl
Created: 2008-01-04T09:55:09.000-0800

**Comment by rbeckman-nextgen** [comment]
I believe this may have something to do with using SQL Server 2k5.  I reinstalled on my local machine and am using the Derby database with success.  I tried switching the database back to Sql Server and I received the same error.  I will try to recreate my database to see if this fixes the problem.

Imported Comment. Original Details:
Author: afterdark23
Created: 2008-01-04T10:27:49.000-0800

**Comment by rbeckman-nextgen** [comment]
I found the error.  When you said "or a comment on the last line", I did organize my global script with comment sections.  I put a ";" after the last comment line and all is working now.  I didn't realize that a comment would error out the system.  This issue can be closed.  Thanks for you time!

//-------------------Trim Functions-------------------
// example of using trim, ltrim, and rtrim
//var myString = " hello my name is ";
//alert("**"+myString.trim()+"**");
//alert("**"+myString.ltrim()+"**");
//alert("**"+myString.rtrim()+"**");
String.prototype.trim = function() {
	return this.replace(/^\s+|\s+$/g,"");
}
String.prototype.ltrim = function() {
	return this.replace(/^\s+/,"");
}
String.prototype.rtrim = function() {
	return this.replace(/\s+$/,"");
}
//-----------------End Trim Functions-----------------
;

Imported Comment. Original Details:
Author: afterdark23
Created: 2008-01-04T10:46:18.000-0800

**Comment by rbeckman-nextgen** [comment]
This happened when a comment was the last line of a script.  A line break is now added before the closing } so it is not commented out.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-01-08T16:52:14.000-0800
