### ISSUE TITLE
Mirth fails to save the message state when a variable (channel val) has a null value

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#710]
When Mirth tries to save the state of  message, if one of the channel vars has a null value, the next exception is launched (and the message doesn't appear in the Dashboard):

INFO   | jvm 1    | 2008/01/09 18:04:22 | ERROR 2008-01-09 18:04:22,656 [_vmConnector#18680713.f0531cbe-46b8-40eb-8f8b-945f16c08ba8.receiver.1] com.webreach.mirth.server.controllers.MessageObjectController: could not log message: id=78e50104-108b-4411-806e-3b7d34494f55
INFO   | jvm 1    | 2008/01/09 18:04:22 | com.ibatis.common.jdbc.exception.NestedSQLException:   
INFO   | jvm 1    | 2008/01/09 18:04:22 | --- The error occurred in derby/derby-message.xml.  
INFO   | jvm 1    | 2008/01/09 18:04:22 | --- The error occurred while applying a parameter map.  
INFO   | jvm 1    | 2008/01/09 18:04:22 | --- Check the Message.insert-message-param.  
INFO   | jvm 1    | 2008/01/09 18:04:22 | --- Check the parameter mapping for the 'channelMap' property.  
INFO   | jvm 1    | 2008/01/09 18:04:22 | --- Cause: java.lang.NullPointerException
INFO   | jvm 1    | 2008/01/09 18:04:22 | Caused by: java.lang.NullPointerException
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:94)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.setStatus(MessageObjectController.java:545)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.setSuccess(MessageObjectController.java:515)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.connectors.doc.DocumentMessageDispatcher.doDispatch(DocumentMessageDispatcher.java:91)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.connectors.doc.DocumentMessageDispatcher.doSend(DocumentMessageDispatcher.java:264)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:141)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2008/01/09 18:04:22 | Caused by: java.lang.NullPointerException
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	... 33 more
INFO   | jvm 1    | 2008/01/09 18:04:22 | 
INFO   | jvm 1    | 2008/01/09 18:04:22 | Caused by: 
INFO   | jvm 1    | 2008/01/09 18:04:22 | java.lang.NullPointerException
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.sqlmap.extensions.MapTypeHandler.setParameter(MapTypeHandler.java:24)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.type.CustomTypeHandler.setParameter(CustomTypeHandler.java:46)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameter(BasicParameterMap.java:165)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.parameter.BasicParameterMap.setParameters(BasicParameterMap.java:125)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:79)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.insert(SqlMapExecutorDelegate.java:447)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.insert(SqlMapSessionImpl.java:82)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.insert(SqlMapClientImpl.java:59)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.writeMessageToDatabase(MessageObjectController.java:200)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.updateMessage(MessageObjectController.java:172)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.setStatus(MessageObjectController.java:545)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.server.controllers.MessageObjectController.setSuccess(MessageObjectController.java:515)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.connectors.doc.DocumentMessageDispatcher.doDispatch(DocumentMessageDispatcher.java:91)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.connectors.doc.DocumentMessageDispatcher.doSend(DocumentMessageDispatcher.java:264)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:492)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:271)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:230)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:141)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at edu.emory.mathcs.backport.java.util.concurrent
INFO   | jvm 1    | 2008/01/09 18:04:22 | .ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
INFO   | jvm 1    | 2008/01/09 18:04:22 | 	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-702
Reporter: albertosaez
Created: 2008-01-10T03:34:40.000-0800

**Comment by rbeckman-nextgen** [comment]
With this patch, a channel var with a null value, doesn't launch an error

Imported Comment. Original Details:
Author: albertosaez
Created: 2008-01-10T03:35:34.000-0800

**Comment by rbeckman-nextgen** [comment]
Thanks again for a great patch!

Imported Comment. Original Details:
Author: chrisl
Created: 2008-01-10T16:26:40.000-0800
