### ISSUE TITLE
Errors with the Dashboard/Message Browser

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#724]
Errors in message browser and dashboard.  Happened frequently after DICOM and DashboardConnMon was added.  Please look into why this is happening.
 
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2 >= 1
      at java.util.Vector.elementAt(Unknown Source)
      at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
      at org.jdesktop.swingx.JXTable.getValueAt(Unknown Source)
      at javax.swing.JTable.prepareRenderer(Unknown Source)
      at org.jdesktop.swingx.JXTable.prepareRenderer(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
      at javax.swing.plaf.ComponentUI.update(Unknown Source)
      at javax.swing.JComponent.paintComponent(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JSplitPane.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintWithOffscreenBuffer(Unknown Source)
      at javax.swing.JComponent.paintDoubleBuffered(Unknown Source)
      at javax.swing.JComponent._paintImmediately(Unknown Source)
      at javax.swing.JComponent.paintImmediately(Unknown Source)
      at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
      at javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(Unknown Source)
      at java.awt.event.InvocationEvent.dispatch(Unknown Source)
      at java.awt.EventQueue.dispatchEvent(Unknown Source)
      at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
      at java.util.Vector.elementAt(Unknown Source)
      at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
      at org.jdesktop.swingx.JXTable.getValueAt(Unknown Source)
      at com.webreach.mirth.client.ui.components.MirthTable.getColumnClass(MirthTable.java:66)
      at javax.swing.JTable.getCellRenderer(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
      at javax.swing.plaf.ComponentUI.update(Unknown Source)
      at javax.swing.JComponent.paintComponent(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JSplitPane.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintWithOffscreenBuffer(Unknown Source)
      at javax.swing.JComponent.paintDoubleBuffered(Unknown Source)
      at javax.swing.JComponent._paintImmediately(Unknown Source)
      at javax.swing.JComponent.paintImmediately(Unknown Source)
      at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
      at javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(Unknown Source)
      at java.awt.event.InvocationEvent.dispatch(Unknown Source)
      at java.awt.EventQueue.dispatchEvent(Unknown Source)
      at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.run(Unknown Source)
[Fatal Error] :1:6268: The content of elements must consist of well-formed character data or markup.
org.xml.sax.SAXParseException: The content of elements must consist of well-formed character data or markup.
      at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
      at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
      at com.webreach.mirth.client.ui.TreePanel.setMessage(TreePanel.java:427)
      at com.webreach.mirth.client.ui.TemplatePanel$1UpdateTimer.run(TemplatePanel.java:236)
      at java.util.TimerThread.mainLoop(Unknown Source)
      at java.util.TimerThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 4 >= 0
      at java.util.Vector.elementAt(Unknown Source)
      at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
      at org.jdesktop.swingx.JXTable.getValueAt(Unknown Source)
      at javax.swing.JTable.prepareRenderer(Unknown Source)
      at org.jdesktop.swingx.JXTable.prepareRenderer(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
      at javax.swing.plaf.ComponentUI.update(Unknown Source)
      at javax.swing.JComponent.paintComponent(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JSplitPane.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintWithOffscreenBuffer(Unknown Source)
      at javax.swing.JComponent.paintDoubleBuffered(Unknown Source)
      at javax.swing.JComponent._paintImmediately(Unknown Source)
      at javax.swing.JComponent.paintImmediately(Unknown Source)
      at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
      at javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(Unknown Source)
      at java.awt.event.InvocationEvent.dispatch(Unknown Source)
      at java.awt.EventQueue.dispatchEvent(Unknown Source)
      at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 3 >= 0
      at java.util.Vector.elementAt(Unknown Source)
      at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
      at org.jdesktop.swingx.JXTable.getValueAt(Unknown Source)
      at javax.swing.JTable.prepareRenderer(Unknown Source)
      at org.jdesktop.swingx.JXTable.prepareRenderer(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCell(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paintCells(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI.paint(Unknown Source)
      at javax.swing.plaf.ComponentUI.update(Unknown Source)
      at javax.swing.JComponent.paintComponent(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JSplitPane.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JViewport.paint(Unknown Source)
      at javax.swing.JComponent.paintChildren(Unknown Source)
      at javax.swing.JComponent.paint(Unknown Source)
      at javax.swing.JComponent.paintWithOffscreenBuffer(Unknown Source)
      at javax.swing.JComponent.paintDoubleBuffered(Unknown Source)
      at javax.swing.JComponent._paintImmediately(Unknown Source)
      at javax.swing.JComponent.paintImmediately(Unknown Source)
      at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
      at javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(Unknown Source)
      at java.awt.event.InvocationEvent.dispatch(Unknown Source)
      at java.awt.EventQueue.dispatchEvent(Unknown Source)
      at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Bounds out of range: 2161,2161
      at org.syntax.jedit.JEditTextArea.select(JEditTextArea.java:1241)
      at org.syntax.jedit.JEditTextArea$DocumentHandler.insertUpdate(JEditTextArea.java:2033)
      at javax.swing.text.AbstractDocument.fireInsertUpdate(Unknown Source)
      at org.syntax.jedit.SyntaxDocument.fireInsertUpdate(SyntaxDocument.java:151)
      at javax.swing.text.AbstractDocument.handleInsertString(Unknown Source)
      at javax.swing.text.AbstractDocument.insertString(Unknown Source)
      at org.syntax.jedit.MirthPlainDocument.insertString(MirthPlainDocument.java:115)
      at org.syntax.jedit.JEditTextArea.setText(JEditTextArea.java:985)
      at com.webreach.mirth.client.ui.components.MirthSyntaxTextArea.setText(MirthSyntaxTextArea.java:267)
      at com.webreach.mirth.client.ui.browsers.message.MessageBrowser.setCorrectDocument(MessageBrowser.java:1138)
      at com.webreach.mirth.client.ui.browsers.message.MessageBrowser.MessageListSelected(MessageBrowser.java:1043)
      at com.webreach.mirth.client.ui.browsers.message.MessageBrowser.access$2(MessageBrowser.java:1028)
      at com.webreach.mirth.client.ui.browsers.message.MessageBrowser$6.valueChanged(MessageBrowser.java:675)
      at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
      at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source)
      at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI$Handler.setValueIsAdjusting(Unknown Source)
      at javax.swing.plaf.basic.BasicTableUI$Handler.mouseReleased(Unknown Source)
      at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
      at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
      at java.awt.Component.processMouseEvent(Unknown Source)
      at javax.swing.JComponent.processMouseEvent(Unknown Source)
      at java.awt.Component.processEvent(Unknown Source)
      at java.awt.Container.processEvent(Unknown Source)
      at java.awt.Component.dispatchEventImpl(Unknown Source)
      at java.awt.Container.dispatchEventImpl(Unknown Source)
      at java.awt.Component.dispatchEvent(Unknown Source)
      at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
      at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
      at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
      at java.awt.Container.dispatchEventImpl(Unknown Source)
      at java.awt.Window.dispatchEventImpl(Unknown Source)
      at java.awt.Component.dispatchEvent(Unknown Source)
      at java.awt.EventQueue.dispatchEvent(Unknown Source)
      at java.awt.EventDispatchThread.pumpOneEventForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
      at java.awt.EventDispatchThread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-716
Reporter: brendanh
Created: 2008-01-16T11:04:43.000-0800

**Comment by rbeckman-nextgen** [comment]
This error occurs due to the global 'status' object being run and modified in the background on multiple threads by SwingWorker.

Find places where UpdateTable() is not called in done() method by SwingWorker.  and move that into done() method.

also, move server calls in the updateTable() out of the methods and refactor into doInBackground().



Imported Comment. Original Details:
Author: chrisr
Created: 2008-01-21T10:10:01.000-0800

**Comment by rbeckman-nextgen** [comment]
Moved UI change methods (updateTable) into done() method in SwingWorker

Imported Comment. Original Details:
Author: chrisr
Created: 2008-01-21T14:08:47.000-0800
