### ISSUE TITLE
Problem parsing XML HL7 valid message

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#729]
The 1.7 XML 2 HL7 parser launch an exception for messages which works fine for previous versions

Imported Issue. Original Details:
Jira Issue Key: MIRTH-721
Reporter: albertosaez
Created: 2008-01-22T09:13:14.000-0800

**Comment by rbeckman-nextgen** [comment]
This is the error this adt message launch

ERROR-300: Transformer error
ERROR MESSAGE:     Error evaluating transformer
com.webreach.mirth.model.converters.SerializerException: java.lang.ArrayIndexOutOfBoundsException: 2
            at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:190)
            at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:51)
            at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:369)
            at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:289)
            at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
            at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
            at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
            at com.webreach.mirth.server.controllers.MessageObjectController.getMessageObjectFromEvent(MessageObjectController.java:507)
            at com.webreach.mirth.connectors.file.FileMessageDispatcher.doDispatch(FileMessageDispatcher.java:74)
            at com.webreach.mirth.connectors.file.FileMessageDispatcher.doSend(FileMessageDispatcher.java:208)
            at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
            at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
            at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
            at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
            at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
            at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
            at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
            at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
            at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
            at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
            at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
            at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
            at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
            at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
            at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
            at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
            at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
            at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:236)
            at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:138)
            at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
            at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
            at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
            at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
            at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
            at com.webreach.mirth.model.converters.ER7XMLHandler.startElement(ER7XMLHandler.java:146)
            at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
            at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
            at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
            at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
            at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
            at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
            at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
            at com.webreach.mirth.model.converters.ER7Serializer.fromXML(ER7Serializer.java:185)
            ... 33 more


Imported Comment. Original Details:
Author: albertosaez
Created: 2008-01-22T09:14:48.000-0800

**Comment by rbeckman-nextgen** [comment]
Thanks for finding this!

Imported Comment. Original Details:
Author: chrisl
Created: 2008-01-22T11:05:29.000-0800

**Comment by rbeckman-nextgen** [comment]
The XML file can be successfully processed using the "Strict Parser". The non-strict default parser does not recognized two-letter segments.

(Older versions of Mirth used the Strict Parser by default, so this message would work with no change. Imported channels from versions earlier than 1.4 should still be set to use Strict Parser).

Imported Comment. Original Details:
Author: chrisl
Created: 2008-01-22T11:24:41.000-0800
