### ISSUE TITLE
CLONE -JMS Writer does not work anymore

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#766]
In Version 1.3.2 the JMS Writer could write a Message to my JMS Server (openJMS) but now in Version 1.4.0 i get always this error.
And i use the same Properties as in 1.3.2. I tried different things but nothing works. 

ERROR-407: JMS Connector error
ERROR MESSAGE:    Jms Error
org.mule.umo.transformer.TransformerException: null (java.lang.NullPointerException)
    at com.webreach.mirth.server.mule.providers.jms.transformers.AbstractJmsTransformer.transformToMessage(AbstractJmsTransformer.java:150)
    at com.webreach.mirth.server.mule.providers.jms.transformers.MessageObjectToJMSMessage.doTransform(MessageObjectToJMSMessage.java:32)
    at com.webreach.mirth.server.mule.providers.jms.JmsMessageDispatcher.dispatchMessage(JmsMessageDispatcher.java:118)
    at com.webreach.mirth.server.mule.providers.jms.JmsMessageDispatcher.doSend(JmsMessageDispatcher.java:244)
    at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
.....

Imported Issue. Original Details:
Jira Issue Key: MIRTH-759
Reporter: egfesser
Created: 2008-02-03T13:40:59.000-0800

**Comment by rbeckman-nextgen** [comment]
This issue seems to have reappeared.  I added several posts to the forums this past week, and the only reply I received was from chrisl indicating that they hoped a JMS expert would reply to me shortly.  As I have not been able to get past this issue, I am now posting this as a bug.  This is an urgent matter as I am currently trying to prove the viability of Mirth.

I am using the final release of Mirth 1.7 posted January 28, 2007 within an instance of JBossAS 4.2.2.  The ERROR-407 associated with JMS continues to be generated despite my attempts to resolve the issue. My posts to the developers forum were as follows:

----------------------------------
Just began working with the JMS Writer connector type, and the following exception is generated. There have been several other past posts that have mentioned this exception, and I am wondering whether JBossAS 4.2.2 is behind this problem. I read somewhere that Mirth is compatible with JBossAS 4.2.0, but I chose to deploy the newer version since it is the last stable release of the product prior to JBossAS 5.0.0, which is still in beta. If I do not hear from anyone, I will let you know the result after deploying with JBossAS 4.2.0. Please note that I am using Mirth 1.7 just released Monday.

2008-01-30 09:20:04,796 ERROR [com.webreach.mirth.connectors.jms.JmsConnector] Unable to create Jms connection
java.lang.IllegalArgumentException: connectionFactory cannot be null
at com.webreach.mirth.connectors.jms.Jms11Support.createConnection(Jms11Support.java:66)
at com.webreach.mirth.connectors.jms.JmsConnector.createConnection(JmsConnector.java:208)
at com.webreach.mirth.connectors.jms.JmsConnector.doConnect(JmsConnector.java:219)
at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:795)
at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java: 32)
at org.mule.providers.AbstractConnectionStrategy.connect(AbstractConnectionStrategy.java:67)
at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:789)
at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java: 32)
at org.mule.providers.AbstractConnectionStrategy.connect(AbstractConnectionStrategy.java:67)
at org.mule.providers.AbstractConnector.startConnector(AbstractConnector.java:251)
at org.mule.MuleManager.startConnectors(MuleManager.java:767)
at org.mule.MuleManager.start(MuleManager.java:728)
at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:207)
at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
at com.webreach.mirth.server.Mirth.startMule(Mirth.java:231)
at com.webreach.mirth.server.Mirth.restartMule(Mirth.java:188)
at com.webreach.mirth.server.Mirth.run(Mirth.java:118)
----------------------------------
Just noticed a message posted late Tuesday morning that Mirth 1.7 is in beta. When I upgraded from Mirth 1.6.1 early Tuesday morning, the release notes made no mention of its beta status, and instead indicated that it is a recommended upgrade.
----------------------------------
The exception is displayed as follows in Mirth Administrator as a Channel Message. My impression from previous posts was that this issue had been resolved in subsequent releases of Mirth. Based on these previous posts, I am hesitant to spend the time reverting back to prior versions of JBossAS, and it appears that versions prior to Mirth 1.6.1 are unavailable. Any point in the right direction is much appreciated!

ERROR-407: JMS Connector error
ERROR MESSAGE: Jms Error
java.lang.NullPointerException
at com.webreach.mirth.connectors.jms.Jms11Support.createSession(Jms11Support.java:74)
at com.webreach.mirth.connectors.jms.JmsConnector.getSession(JmsConnector.java:283)
at com.webreach.mirth.connectors.jms.JmsConnector.getSession(JmsConnector.java:464)
at com.webreach.mirth.connectors.jms.JmsMessageDispatcher.dispatchMessage(JmsMessageDispatcher.java: 104)
at com.webreach.mirth.connectors.jms.JmsMessageDispatcher.doSend(JmsMessageDispatcher.java:260)
at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageR eceiver.java:493)
at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:142)
at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor. java:650)
at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java :675)
at java.lang.Thread.run(Thread.java:595)
----------------------------------
The JMS queue I created seems to be working. Upon subsequent JBossAS startups, the messages sent to the queue via Mirth continue to persist. The problem appears to be associated with Mule.

2008-02-01 10:21:50,187 INFO [org.mule.MuleManager] Server endpointUri is null, not registering Mule Admin agent
2008-02-01 10:21:50,187 INFO [org.mule.util.queue.TransactionalQueueManager] Starting ResourceManager
2008-02-01 10:21:50,187 DEBUG [org.mule.util.queue.FilePersistenceStrategy] Restore retrieved 0 objects
2008-02-01 10:21:50,187 INFO [org.mule.util.queue.TransactionalQueueManager] Started ResourceManager
2008-02-01 10:21:50,187 ERROR [com.webreach.mirth.connectors.jms.JmsConnector] Unable to create Jms connection
java.lang.IllegalArgumentException: connectionFactory cannot be null
at com.webreach.mirth.connectors.jms.Jms11Support.createConnection(Jms11Support.java:66)
at com.webreach.mirth.connectors.jms.JmsConnector.createConnection(JmsConnector.java:208)
at com.webreach.mirth.connectors.jms.JmsConnector.doConnect(JmsConnector.java:219)
at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:795)
at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java: 32)
at org.mule.providers.AbstractConnectionStrategy.connect(AbstractConnectionStrategy.java:67)
at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:789)
at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java: 32)
at org.mule.providers.AbstractConnectionStrategy.connect(AbstractConnectionStrategy.java:67)
at org.mule.providers.AbstractConnector.startConnector(AbstractConnector.java:251)
at org.mule.MuleManager.startConnectors(MuleManager.java:767)
at org.mule.MuleManager.start(MuleManager.java:728)
at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:207)
at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
at com.webreach.mirth.server.Mirth.startMule(Mirth.java:231)
at com.webreach.mirth.server.Mirth.startup(Mirth.java:160)
at com.webreach.mirth.server.Mirth.run(Mirth.java:110)

Imported Comment. Original Details:
Author: egfesser
Created: 2008-02-03T13:51:33.000-0800

**Comment by rbeckman-nextgen** [comment]
I will be opening this bug as a new issue with proper assignment to Mirth 1.7 - please close this issue as it was opened in error for Mirth 1.4 - thank you.

Imported Comment. Original Details:
Author: egfesser
Created: 2008-02-03T14:13:07.000-0800

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-760

Imported Comment. Original Details:
Author: jacobb
Created: 2008-02-19T17:42:58.000-0800
