### ISSUE TITLE
mirthdb failed to start while starting the mirth server.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#775]
Upon refreshing Channels after deploying the Mirth Admin web application froze. the status bar at the right bottom read 'loading statistics' however the application froze.After closing the window and restarting the mirth server got following in the error log. However upon restarting the machine Mirth started working.

Mirth LOG contents:
WARN  2008-02-12 18:38:27,750 [Thread-0] org.mortbay.util.ThreadedServer: Failed to start: SslListener0@0.0.0.0:8443
WARN  2008-02-12 18:38:27,751 [Thread-0] org.mortbay.util.ThreadedServer: Failed to start: SocketListener1@0.0.0.0:8080
WARN  2008-02-12 18:38:27,753 [Thread-0] com.webreach.mirth.server.Mirth: Could not start web server.
org.mortbay.util.MultiException[java.net.BindException: Address already in use, java.net.BindException: Address already in use]
	at org.mortbay.http.HttpServer.doStart(HttpServer.java:686)
	at org.mortbay.util.Container.start(Container.java:72)
	at com.webreach.mirth.server.Mirth.startWebServer(Mirth.java:375)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:144)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:109)
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:359)
	at java.net.ServerSocket.bind(ServerSocket.java:319)
	at java.net.ServerSocket.<init>(ServerSocket.java:185)
	at javax.net.ssl.SSLServerSocket.<init>(SSLServerSocket.java:106)
	at com.sun.net.ssl.internal.ssl.SSLServerSocketImpl.<init>(SSLServerSocketImpl.java:106)
	at com.sun.net.ssl.internal.ssl.SSLServerSocketFactoryImpl.createServerSocket(SSLServerSocketFactoryImpl.java:71)
	at org.mortbay.http.SslListener.newServerSocket(SslListener.java:291)
	at org.mortbay.util.ThreadedServer.open(ThreadedServer.java:477)
	at org.mortbay.util.ThreadedServer.start(ThreadedServer.java:503)
	at org.mortbay.http.SocketListener.start(SocketListener.java:203)
	at org.mortbay.http.HttpServer.doStart(HttpServer.java:716)
	at org.mortbay.util.Container.start(Container.java:72)
	at com.webreach.mirth.server.Mirth.startWebServer(Mirth.java:375)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:144)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:109)
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:359)
	at java.net.ServerSocket.bind(ServerSocket.java:319)
	at java.net.ServerSocket.<init>(ServerSocket.java:185)
	at org.mortbay.util.ThreadedServer.newServerSocket(ThreadedServer.java:391)
	at org.mortbay.util.ThreadedServer.open(ThreadedServer.java:477)
	at org.mortbay.util.ThreadedServer.start(ThreadedServer.java:503)
	at org.mortbay.http.SocketListener.start(SocketListener.java:203)
	at org.mortbay.http.HttpServer.doStart(HttpServer.java:716)
	at org.mortbay.util.Container.start(Container.java:72)
	at com.webreach.mirth.server.Mirth.startWebServer(Mirth.java:375)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:144)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:109)
ERROR 2008-02-12 18:38:27,883 [Thread-0] com.webreach.mirth.server.controllers.MessageObjectController: java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
ERROR 2008-02-12 18:38:27,900 [Thread-0] com.webreach.mirth.server.controllers.ChannelStatisticsController: Could not initialize channel statistics.
ERROR 2008-02-12 18:38:27,919 [Thread-0] com.webreach.mirth.server.controllers.ConfigurationController: could not initialize configuration settings
com.webreach.mirth.server.controllers.ControllerException: error loading encryption key
	at com.webreach.mirth.server.controllers.ConfigurationController.loadEncryptionKey(ConfigurationController.java:546)
	at com.webreach.mirth.server.controllers.ConfigurationController.initialize(ConfigurationController.java:157)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:149)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:109)
Caused by: java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver30.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at com.ibatis.common.jdbc.SimpleDataSource.popConnection(SimpleDataSource.java:580)
	at com.ibatis.common.jdbc.SimpleDataSource.getConnection(SimpleDataSource.java:222)
	at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.init(JdbcTransaction.java:48)
	at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:89)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForObject(GeneralStatement.java:104)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:566)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:110)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForObject(SqlMapClientImpl.java:87)
	at com.webreach.mirth.server.controllers.ConfigurationController.loadEncryptionKey(ConfigurationController.java:531)
	... 3 more
ERROR 2008-02-12 18:38:27,935 [Thread-0] com.webreach.mirth.server.controllers.MigrationController: Could not initialize migration controller.
java.lang.Exception: java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
	at com.webreach.mirth.server.util.DatabaseUtil.executeScript(DatabaseUtil.java:131)
	at com.webreach.mirth.server.controllers.MigrationController.migrate(MigrationController.java:143)
	at com.webreach.mirth.server.controllers.MigrationController.initialize(MigrationController.java:101)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:150)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:109)
Caused by: java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver30.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at com.ibatis.common.jdbc.SimpleDataSource.popConnection(SimpleDataSource.java:580)
	at com.ibatis.common.jdbc.SimpleDataSource.getConnection(SimpleDataSource.java:222)
	at com.webreach.mirth.server.util.DatabaseUtil.executeScript(DatabaseUtil.java:105)
	... 4 more
WARN  2008-02-12 18:38:28,403 [Thread-0] com.webreach.mirth.server.controllers.ChannelController: com.webreach.mirth.server.controllers.ControllerException: java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
ERROR 2008-02-12 18:38:28,415 [Thread-0] com.webreach.mirth.server.controllers.UserController: Could not reset user status.
ERROR 2008-02-12 18:38:28,432 [Thread-0] com.webreach.mirth.server.controllers.ConfigurationController: Could not retrieve latest configuration.
java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver30.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at com.ibatis.common.jdbc.SimpleDataSource.popConnection(SimpleDataSource.java:580)
	at com.ibatis.common.jdbc.SimpleDataSource.getConnection(SimpleDataSource.java:222)
	at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.init(JdbcTransaction.java:48)
	at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:89)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForObject(GeneralStatement.java:104)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:566)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForObject(SqlMapExecutorDelegate.java:541)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:106)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForObject(SqlMapSessionImpl.java:110)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForObject(SqlMapClientImpl.java:87)
	at com.webreach.mirth.server.controllers.ConfigurationController.getLatestConfiguration(ConfigurationController.java:458)
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:198)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:158)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:109)
WARN  2008-02-12 18:38:28,435 [Thread-0] com.webreach.mirth.server.Mirth: Could not retrieve latest configuration.
java.lang.NullPointerException
	at com.webreach.mirth.server.Mirth.startMule(Mirth.java:198)
	at com.webreach.mirth.server.Mirth.startup(Mirth.java:158)
	at com.webreach.mirth.server.Mirth.run(Mirth.java:109)
WARN  2008-02-12 18:38:28,488 [DefaultQuartzScheduler_Worker-1] com.webreach.mirth.plugins.messagepruner.MessagePrunerService: could not prune message database
com.webreach.mirth.server.controllers.ControllerException: java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
	at com.webreach.mirth.server.controllers.ChannelController.getChannel(ChannelController.java:131)
	at com.webreach.mirth.plugins.messagepruner.MessagePrunerService.execute(MessagePrunerService.java:187)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:529)
Caused by: java.sql.SQLException: Failed to start database '/home/maoperator/Mirth/mirthdb', see the next exception for details.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.bootDatabase(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver30.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)
	at java.sql.DriverManager.getConnection(DriverManager.java:525)
	at java.sql.DriverManager.getConnection(DriverManager.java:171)
	at com.ibatis.common.jdbc.SimpleDataSource.popConnection(SimpleDataSource.java:580)
	at com.ibatis.common.jdbc.SimpleDataSource.getConnection(SimpleDataSource.java:222)
	at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.init(JdbcTransaction.java:48)
	at com.ibatis.sqlmap.engine.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:89)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeQueryForList(GeneralStatement.java:123)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:615)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.queryForList(SqlMapExecutorDelegate.java:589)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.queryForList(SqlMapSessionImpl.java:118)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.queryForList(SqlMapClientImpl.java:95)
	at com.webreach.mirth.server.controllers.ChannelController.getChannel(ChannelController.java:129)
	... 3 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-768
Reporter: mac_3785
Created: 2008-02-12T07:53:10.000-0800

**Comment by rbeckman-nextgen** [comment]
It looks like mirth or jetty had an error shutting down, so it errored when starting up because the port was already in use.  Sometimes it freezes like that if there is an infinite loop in a transformer script.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-02-19T18:29:39.000-0800
