### ISSUE TITLE
JMS writer fails when trying to write to a JbossMQ queue

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#796]
Mirth has a test channel configured, with a channel reader, that has only one destination of type JMS Writer.

There are two instances of Jboss running in the same box, one is a 4.2.0GA running Mirth 1.7.0, and the other one is a 4.0.3SP1 with JMS queues configured.

The channel deploys OK, but when it process a message, an exception is raised:
------
ERROR-407: JMS Connector error
ERROR MESSAGE:	Jms Error
java.lang.NullPointerException
	at com.webreach.mirth.connectors.jms.Jms11Support.createSession(Jms11Support.java:74)
	at com.webreach.mirth.connectors.jms.JmsConnector.getSession(JmsConnector.java:283)
	at com.webreach.mirth.connectors.jms.JmsConnector.getSession(JmsConnector.java:464)
	at com.webreach.mirth.connectors.jms.JmsMessageDispatcher.dispatchMessage(JmsMessageDispatcher.java:104)
	at com.webreach.mirth.connectors.jms.JmsMessageDispatcher.doSend(JmsMessageDispatcher.java:260)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:142)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:595)
------

I've tried the same configuration with a Mirth 1.6.1 but it raises another exception when creating the channel:
-------
com.webreach.mirth.client.core.ClientException: method failed: HTTP/1.1 500 com.thoughtworks.xstream.converters.ConversionException: lastModified : No ClassLoaders found for: lastModified
---- Debugging information ----
required-type       : com.webreach.mirth.model.Channel 
cause-message       : lastModified : No ClassLoaders found for: lastModified 
class               : com.webreach.mirth.model.Channel 
message             : lastModified : No ClassLoaders found for: lastModified 
line number         : 6 
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException 
-------------------------------
com.webreach.mirth.client.core.ServerConnection.executePostMethod(ServerConnection.java:98)
com.webreach.mirth.client.core.Client.updateChannel(Client.java:182)
com.webreach.mirth.client.ui.Frame.updateChannel(Frame.java:1061)
com.webreach.mirth.client.ui.ChannelSetup.saveChanges(ChannelSetup.java:905)
com.webreach.mirth.client.ui.Frame$23.doInBackground(Frame.java:2337)
com.webreach.mirth.client.ui.Frame$23.doInBackground(Frame.java:2349)
org.jdesktop.swingworker.SwingWorker$1.call(Unknown Source)
java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
java.util.concurrent.FutureTask.run(Unknown Source)
org.jdesktop.swingworker.SwingWorker.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
java.lang.Thread.run(Unknown Source)
-------

The JMS writer in both cases, is parametrized as follows:
JMS Specification: 1.1
Use JNDI: yes
provider URL: jnp://localhost:1299 (*)
Initial Context Factory: org.jnp.interfaces.NamingContextFactory
Connection Factory Name: java:/ConnectionFactory
Destination: queue/MirthIntegration
Username: guest
password: ....
Durable: no
ACK mode: auto aknowledge

(*) the port is 1299 because the jboss instance that hosts the queue is running with a "servicebindingmanager" called "ports-02".

BTW, my knowledge about how JMS work is limited, but it seems to be configured OK, as shown by mule and mirth examples about JMS writers. Now i'm trying to write an JMS client, to test if the JMS queues are working OK.

IMHO, this issue is closely related to MIRTH-525 and/or MIRTH-559

Thanks in advance.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-789
Reporter: quimicefa
Created: 2008-03-03T05:30:07.000-0800

**Comment by rbeckman-nextgen** [comment]
I've just tried to send a JMS message to the queue/MirthIntegration, on the 4.0.3SP1 instance.

the code shown in http://wiki.jboss.org/wiki/Wiki.jsp?page=QueueExample works perfectly, without any modification. The only "issue" to get the cliente working was adding the "jboss-client.jar" to the classpath of the client. With this program, I've succesfuly sent several messages to the queue.

I've tried to add this file to the "server/default/mirth.sar/lib" path, on the JMS-client Jboss [4.2.0, running mirth], but no luck (same exception in the same point), 

I don't understand why doesn't work, seems to be a classpath problem or missing jars (?)

Imported Comment. Original Details:
Author: quimicefa
Created: 2008-03-03T09:13:07.000-0800

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-760.

Your channel would probably work in 1.6.1.  The failure you are getting in that version is likely because you are trying to import a 1.7 channel into 1.6.1.  Channels are not forward-compatible.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-03-04T18:59:54.000-0800
