### ISSUE TITLE
Only ER7 is allowed for the LLP channel

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#812]
Sending HL7 in its XML form, is not allowed for the MLLp connector, as the receiver launch an exception:

(This is because the MLLP receiver pass the MLLP control characters to the protocol especific adapter)

ERROR-301: Transformer conversion error
ERROR MESSAGE:	Error adapting message
org.xml.sax.SAXParseException: Content is not allowed in trailing section.
	at org.apache.xerces.parsers.DOMParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source)
	at com.webreach.mirth.server.mule.adaptors.XMLAdaptor.populateMessage(XMLAdaptor.java:23)
	at com.webreach.mirth.server.mule.adaptors.Adaptor.getMessage(Adaptor.java:41)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:294)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:440)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:419)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:340)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:613)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-806
Reporter: albertosaez
Created: 2008-03-13T16:07:18.000-0700

**Comment by rbeckman-nextgen** [comment]
This patch removes the MLLP control characteres from the MLLP from the string passed to the protocol-specific adapter.

Wortks for ER7 & XML over MLLP

Imported Comment. Original Details:
Author: albertosaez
Created: 2008-03-13T16:09:34.000-0700

**Comment by rbeckman-nextgen** [comment]
We addressed this issue another way in recent 1.7.1 fixes.  Please check the latest to see if it works for you without this patch.  It should work now the way ER7 works, where the control characters are "trimmed" off the message.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-03-17T12:54:33.000-0700

**Comment by rbeckman-nextgen** [comment]
The previous patch was only the first step. What I need was a full HL7/XML behaviour under the MLLP protocol. This is:  For MLLP Receiver: if the channel is in XML format, then the  remote system should send back an XML-based ACK, For MLLP Sender: if the message sended is XML, then it treats the answer as XML.
Until now, The MLLP channel suppose than the message is always in ER7 syntax. 

Imported Comment. Original Details:
Author: albertosaez
Created: 2008-03-17T15:43:06.000-0700

**Comment by rbeckman-nextgen** [comment]
The patch I've posted  is not fully tested. 

Imported Comment. Original Details:
Author: albertosaez
Created: 2008-03-17T15:45:05.000-0700

**Comment by rbeckman-nextgen** [comment]
We do not have a use case for using XML over LLP.  Please use TCP to send XML over a socket.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-10-09T15:10:09.000-0700

**Comment by rbeckman-nextgen** [comment]
XML should already work over MLLP, but we need to implement automatic ACK generation for the XML spec of HL7v2 only.  It should not try to generate an ack for normal XML.  We also need to implement automatic ACK generation for the HL7v3 spec.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-10-10T11:32:20.000-0700

**Comment by rbeckman-nextgen** [comment]
Modified the ACKGenerator to generate acks for HL7 spec XML messages by converting them to and from ER7 using the strict parser.
Also added performance fix by not serializing acks to XML in order to get their response type from the MllpMessageDispatcher.

In order to use the strict parser to receive HL7v2 XML over LLP and transform it into ER7, the inbound data type has to be XML and the outbound data type has to be HL7v2 with the Strict Parser turned on in the properties.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-10-22T12:29:28.000-0700
