### ISSUE TITLE
Error in parser when changing the incoming data format

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#829]
If I create a channel with the following configuration:
 *incoming data: XML
  * source SOAP listener
  * destination: file writer

And I send a message trought the "send message" option in the mirth administrator, it's processed OK.

But if I define the same channel as above, creating it from scratch using incomiong data=hl7, save it, and then, change it to XML, when the channel receives a message trought the "send message" option or the SOAP listener, the following exception is raised:

ERROR-301: Transformer conversion error
ERROR MESSAGE:	Error adapting message
java.util.regex.PatternSyntaxException: No such group yet exists at this point in the pattern near index 1
\8
 ^
	at java.util.regex.Pattern.error(Pattern.java:1650)
	at java.util.regex.Pattern.escape(Pattern.java:1977)
	at java.util.regex.Pattern.atom(Pattern.java:1863)
	at java.util.regex.Pattern.sequence(Pattern.java:1743)
	at java.util.regex.Pattern.expr(Pattern.java:1687)
	at java.util.regex.Pattern.compile(Pattern.java:1397)
	at java.util.regex.Pattern.<init>(Pattern.java:1124)
	at java.util.regex.Pattern.compile(Pattern.java:817)
	at java.lang.String.split(String.java:2103)
	at java.lang.String.split(String.java:2145)
	at com.webreach.mirth.model.converters.ER7Serializer.getMetadataFromEncoded(ER7Serializer.java:270)
	at com.webreach.mirth.server.mule.adaptors.Adaptor.populateMetadataFromEncoded(Adaptor.java:80)
	at com.webreach.mirth.server.mule.adaptors.HL7v2Adaptor.populateMessage(HL7v2Adaptor.java:17)
	at com.webreach.mirth.server.mule.adaptors.Adaptor.convertMessage(Adaptor.java:59)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:298)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at com.webreach.mirth.server.controllers.MessageObjectController.getMessageObjectFromEvent(MessageObjectController.java:507)
	at com.webreach.mirth.connectors.file.FileMessageDispatcher.doDispatch(FileMessageDispatcher.java:74)
	at com.webreach.mirth.connectors.file.FileMessageDispatcher.doSend(FileMessageDispatcher.java:207)
	at org.mule.providers.AbstractMessageDispatcher.send(AbstractMessageDispatcher.java:166)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:191)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:130)
	at org.mule.routing.outbound.AbstractOutboundRouter.send(AbstractOutboundRouter.java:85)
	at org.mule.routing.outbound.FilteringMulticastingRouter.route(FilteringMulticastingRouter.java:89)
	at org.mule.routing.outbound.OutboundMessageRouter$1.doInTransaction(OutboundMessageRouter.java:78)
	at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:48)
	at org.mule.routing.outbound.OutboundMessageRouter.route(OutboundMessageRouter.java:82)
	at org.mule.impl.model.DefaultMuleProxy.onCall(DefaultMuleProxy.java:247)
	at org.mule.impl.model.seda.SedaComponent.doSend(SedaComponent.java:209)
	at org.mule.impl.model.AbstractComponent.sendEvent(AbstractComponent.java:277)
	at org.mule.impl.MuleSession.sendEvent(MuleSession.java:201)
	at org.mule.routing.inbound.InboundMessageRouter.send(InboundMessageRouter.java:161)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:128)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:231)
	at com.webreach.mirth.connectors.vm.VMMessageReceiver.getMessages(VMMessageReceiver.java:142)
	at org.mule.providers.TransactedPollingMessageReceiver.poll(TransactedPollingMessageReceiver.java:108)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Thread.java:595)

IMHO, when I create a channel from scratch using HL7 as incoming data, there are several UMO components of mule that are configured in the mule config using HL7 as protocol. When I change the type of incoming data, only the first UMO component is changed to XML, but the rest of components of the channel are not changed to get XML data, so a parse exception it's raised 

Thanks in advance.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-823
Reporter: quimicefa
Created: 2008-04-18T03:57:49.000-0700

**Comment by rbeckman-nextgen** [comment]
There are other issues created about this right now.  Since Mirth gives control of data types at each inbound/outbound of each connector, we don't have a good way to resolve this.  Right now, changing one data type should not change them all unless you initially create the channel with a specific data type.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-10-09T12:30:36.000-0700

**Comment by rbeckman-nextgen** [comment]
I'm facing this problem right now. There are some connectors that only speak XML (like DB Reader). 

I've created a channel with an LLP Reader with HL7 format, then defined some transformers.

Changing the source from LLP Reader to DB Reader, forces that the incoming format is XML, but I can't change the input/output format of the transformers because (pressumably) is blocked since the DB Reader speaks only XML. 

it will be an improvement at least, let the user change the input/output data type in every situation.

Imported Comment. Original Details:
Author: quimicefa
Created: 2008-11-04T07:29:45.000-0800
