### ISSUE TITLE
Text in HL7 can cause a MirthJavascriptTransformerException if it resembles an xml tag.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#837]
Example OBX segment:
OBX|47|ST|1:RPT^Radiology Report||File ?: Y < Enter>||||||F|

The "<Enter>" segment should be html encoded before the raw message is transformed into xml, otherwise it generates an error.  Then when assembling the message back into HL7, the data should be unencoded.

The error is:
ERROR-300: Transformer error
ERROR MESSAGE:	Error evaluating transformer
com.webreach.mirth.server.MirthJavascriptTransformerException: 
CHANNEL:	RAD - Incoming
CONNECTOR:	sourceConnector
SCRIPT SOURCE:	
LINE NUMBER:	1
DETAILS:	TypeError: error: </OBX.5.1> does not close tag <Enter>.
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.evaluateScript(JavaScriptTransformer.java:397)
	at com.webreach.mirth.server.mule.transformers.JavaScriptTransformer.transform(JavaScriptTransformer.java:307)
	at org.mule.transformers.AbstractEventAwareTransformer.doTransform(AbstractEventAwareTransformer.java:48)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:197)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.transformers.AbstractTransformer.transform(AbstractTransformer.java:200)
	at org.mule.impl.MuleEvent.getTransformedMessage(MuleEvent.java:251)
	at org.mule.routing.inbound.SelectiveConsumer.isMatch(SelectiveConsumer.java:61)
	at org.mule.routing.inbound.InboundMessageRouter.route(InboundMessageRouter.java:79)
	at org.mule.providers.AbstractMessageReceiver$DefaultInternalMessageListener.onMessage(AbstractMessageReceiver.java:493)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:272)
	at org.mule.providers.AbstractMessageReceiver.routeMessage(AbstractMessageReceiver.java:244)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processHL7Data(MllpMessageReceiver.java:440)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.processData(MllpMessageReceiver.java:419)
	at com.webreach.mirth.connectors.mllp.MllpMessageReceiver$TcpWorker.run(MllpMessageReceiver.java:340)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-831
Reporter: jerchap
Created: 2008-05-06T08:37:26.000-0700

**Comment by rbeckman-nextgen** [comment]
In 1.7.0, make sure the Encode Entities option is checked. This is enabled by default in 1.7.1+.

Imported Comment. Original Details:
Author: geraldb
Created: 2008-10-10T15:28:06.000-0700
