### ISSUE TITLE
Mirth launch an exception if the body template of an Mail Alert is void

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#878]
If the body of an alert has no text, the next exception is launched each time Mirth tries to send the alert:

 com.webreach.mirth.server.util.TemplateEvaluator: could not evaluate template values
java.lang.NullPointerException
        at java.io.StringReader.<init>(StringReader.java:33)
        at org.apache.velocity.app.Velocity.evaluate(Velocity.java:210)
        at com.webreach.mirth.server.util.TemplateEvaluator.evaluate(TemplateEvaluator.java:28)
        at com.webreach.mirth.server.controllers.AlertController.sentAlertEmails(AlertController.java:222)
        at com.webreach.mirth.server.controllers.AlertController.sendAlerts(AlertController.java:190)
        at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.manageResponseAck(MllpMessageDispatcher.java:399)
        at com.webreach.mirth.connectors.mllp.MllpMessageDispatcher.sendPayload(MllpMessageDispatcher.java:330)
        at com.webreach.mirth.connectors.mllp.MllpMessageResponseQueued.poll(MllpMessageResponseQueued.java:108)
        at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Thread.java:619)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-873
Reporter: albertosaez
Created: 2008-07-15T04:53:23.000-0700

**Comment by rbeckman-nextgen** [comment]
Patch to solve the issue.

The patch add too a new feature: add  the "channeid" and "channelname" context variables to the sendmail template (very useful if you're using only one alert for all channels.



Imported Comment. Original Details:
Author: albertosaez
Created: 2008-07-15T05:24:41.000-0700

**Comment by rbeckman-nextgen** [comment]
If no template is defined, then the error message is now sent by default.

Imported Comment. Original Details:
Author: geraldb
Created: 2008-07-30T17:01:08.000-0700
