### ISSUE TITLE
Add login timeout option to database connector

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#918]
Add login timeout option to database connector. Use dateSource.setLoginTimeout(int)

Imported Issue. Original Details:
Jira Issue Key: MIRTH-913
Reporter: geraldb
Created: 2008-09-11T16:05:40.000-0700

**Comment by rbeckman-nextgen** [comment]
Added "Login Timeout" to DB reader and writer panel. Default properties have already been added.

Imported Comment. Original Details:
Author: geraldb
Created: 2008-09-16T14:10:39.000-0700

**Comment by rbeckman-nextgen** [comment]
Caused by: org.mule.config.ConfigurationException: MuleManager Failed to initialise
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:209)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:194)
	... 4 more
Caused by: org.mule.providers.FatalConnectException: ReconnectStrategy "org.mule.providers.SingleAttemptConnectionStrategy" failed to reconnect receiver on endpoint "com.webreach.mirth.connectors.jdbc.JdbcConnector@6c01b9"
	at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java:34)
	at org.mule.providers.AbstractConnectionStrategy.connect(AbstractConnectionStrategy.java:67)
	at org.mule.providers.AbstractConnector.startConnector(AbstractConnector.java:254)
	at org.mule.MuleManager.startConnectors(MuleManager.java:767)
	at org.mule.MuleManager.start(MuleManager.java:728)
	at org.mule.config.builders.MuleXmlConfigurationBuilder.configure(MuleXmlConfigurationBuilder.java:207)
	... 5 more
Caused by: org.mule.providers.ConnectException: Initialisation Failure: Login timeout is not supported.
	at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:787)
	at org.mule.providers.SingleAttemptConnectionStrategy.doConnect(SingleAttemptConnectionStrategy.java:32)
	... 10 more
Caused by: java.lang.UnsupportedOperationException: Login timeout is not supported.
	at org.apache.commons.dbcp.PoolingDataSource.setLoginTimeout(PoolingDataSource.java:144)
	at org.apache.commons.dbcp.BasicDataSource.setLoginTimeout(BasicDataSource.java:945)
	at com.webreach.mirth.connectors.jdbc.JdbcConnector.setupDataSource(JdbcConnector.java:408)
	at com.webreach.mirth.connectors.jdbc.JdbcConnector.doConnect(JdbcConnector.java:423)
	at org.mule.providers.AbstractConnector.connect(AbstractConnector.java:780)

Imported Comment. Original Details:
Author: brendanh
Created: 2008-09-19T11:04:31.000-0700

**Comment by rbeckman-nextgen** [comment]
BasicDataSource does not support the login timeout parameter.

Imported Comment. Original Details:
Author: geraldb
Created: 2008-09-19T11:42:11.000-0700
