### ISSUE TITLE
SFTP Reader Not Writing to assigned directory

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#922]
The sftp reader Channel successfully processes the file in the sftp folder, but when the reader attempts to write to the processed or error folder (read from the Move-to directory), it generates the message below:

[2008-09-19 08:29:42,812]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: dabeb40b-b15f-4966-80bb-ed848128652e: 2: No such file
2: No such file
	at com.jcraft.jsch.ChannelSftp.throwStatusError(ChannelSftp.java:2078)
	at com.jcraft.jsch.ChannelSftp.cd(ChannelSftp.java:281)
	at com.webreach.mirth.connectors.sftp.SftpMessageReceiver.processFile(SftpMessageReceiver.java:262)
	at com.webreach.mirth.connectors.sftp.SftpMessageReceiver.poll(SftpMessageReceiver.java:83)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:118)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)

It appears to occur with any type of file. The destination type appears to be irrelevant. Could reproduce with default settings.

Imported Issue. Original Details:
Jira Issue Key: MIRTH-917
Reporter: peisima
Created: 2008-09-19T05:34:34.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed and tested in 1.8.0.

Imported Comment. Original Details:
Author: geraldb
Created: 2008-10-10T12:02:33.000-0700
