### ISSUE TITLE
Cannot upload extensions to install them when running Mirth as a Service in Vista

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#963]
Cannot upload extensions to install them when running Mirth as a Service in Vista

WARN  2008-10-23 16:53:33,568 [SslListener0-1] org.mortbay.jetty.context./: /extensions: 
org.apache.commons.fileupload.FileUploadBase$IOFileUploadException: Processing of multipart/form-data request failed. C:\Windows\system32\config\systemprofile\AppData\Local\Temp\upload_1ae3732e_11d2c1e3ad9__7fcf_00000001.tmp (The system cannot find the path specified)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:359)
	at org.apache.commons.fileupload.servlet.ServletFileUpload.parseRequest(ServletFileUpload.java:126)
	at com.webreach.mirth.server.servlets.ExtensionServlet.doPost(ExtensionServlet.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:616)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
	at org.mortbay.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:666)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1530)
	at org.mortbay.http.HttpContext.handle(HttpContext.java:1482)
	at org.mortbay.http.HttpServer.service(HttpServer.java:909)
	at org.mortbay.http.HttpConnection.service(HttpConnection.java:816)
	at org.mortbay.http.HttpConnection.handleNext(HttpConnection.java:982)
	at org.mortbay.http.HttpConnection.handle(HttpConnection.java:833)
	at org.mortbay.http.SocketListener.handleConnection(SocketListener.java:244)
	at org.mortbay.util.ThreadedServer.handle(ThreadedServer.java:357)
	at org.mortbay.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by: java.io.FileNotFoundException: C:\Windows\system32\config\systemprofile\AppData\Local\Temp\upload_1ae3732e_11d2c1e3ad9__7fcf_00000001.tmp (The system cannot find the path specified)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at org.apache.commons.io.output.DeferredFileOutputStream.thresholdReached(DeferredFileOutputStream.java:165)
	at org.apache.commons.io.output.ThresholdingOutputStream.checkThreshold(ThresholdingOutputStream.java:221)
	at org.apache.commons.io.output.ThresholdingOutputStream.write(ThresholdingOutputStream.java:127)
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:101)
	at org.apache.commons.fileupload.util.Streams.copy(Streams.java:64)
	at org.apache.commons.fileupload.FileUploadBase.parseRequest(FileUploadBase.java:354)
	... 16 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-959
Reporter: jacobb
Created: 2008-10-23T17:21:24.000-0700

**Comment by rbeckman-nextgen** [comment]
Configured temp storage directory for file uploads to be install_temp. Also modified the installer to only copy over directories.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-10-23T18:27:53.000-0700
