### ISSUE TITLE
Message Pruner setting in the Channel Summary allows 'null' number of days value.

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#976]
and when the message pruner kicks in, it results in following error and fails:

[2008-11-05 01:31:26,709]  WARN  (com.webreach.mirth.plugins.messagepruner.MessagePrunerService:226): could not prune message database
java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
    at java.lang.Integer.parseInt(Integer.java:468)
    at java.lang.Integer.parseInt(Integer.java:497)
    at com.webreach.mirth.plugins.messagepruner.MessagePrunerService.execute(MessagePrunerService.java:198)
    at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
    at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:529) 

Imported Issue. Original Details:
Jira Issue Key: MIRTH-972
Reporter: chrisr
Created: 2008-11-05T12:52:48.000-0800

**Comment by rbeckman-nextgen** [comment]
Duplicate of MIRTH-971

Imported Comment. Original Details:
Author: jacobb
Created: 2008-11-05T14:04:31.000-0800
