### ISSUE TITLE
Joins not working as expected in transformer select statements

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#98]
Select statement that works in SQL natively, does not work inside of Mirth.

Here is a zip file with some stuff:

db schema (2 tables)
error log excerpt
screenshot of channel
channel itself

http://www.clubpacswestmi.net/mircissue.zip

The statement throws the below exception...

<pre>
ERROR [6_source._jdbcEndpoint#-1420882832.receiver.3] org.mule.impl.DefaultExceptionStrategy: Caught exception in Exception Strategy: Can not retrieve argument orders.id
java.lang.IllegalArgumentException: Can not retrieve argument orders.id
        at org.mule.providers.jdbc.JdbcUtils.getParams(JdbcUtils.java:154)
        at org.mule.providers.jdbc.JdbcMessageReceiver.processMessage(JdbcMessageReceiver.java:90)
        at org.mule.providers.TransactedPollingMessageReceiver$MessageProcessorWorker.doInTransaction(TransactedPollingMessageReceiver.java:159)
        at org.mule.transaction.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.mule.providers.TransactedPollingMessageReceiver$MessageProcessorWorker.run(TransactedPollingMessageReceiver.java:149)
        at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
        at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
        at java.lang.Thread.run(Thread.java:613)
</pre>

<pre>
mysql> SELECT patients.id, patients.patient_name, patients.patient_middle, patients.patient_last, patients.sex, orders.id, orders.procedure FROM patients JOIN orders WHERE patients.id=orders.patient_id AND orders.sent_flag = '0';
+----+--------------+----------------+--------------+------+----+---------------------+
| id | patient_name | patient_middle | patient_last | sex  | id | procedure           |
+----+--------------+----------------+--------------+------+----+---------------------+
|  1 | Ron          | J              | Sweeney      | M    |  1 | CT with contrast    | 
|  1 | Ron          | J              | Sweeney      | M    |  2 | MRI                 | 
|  1 | Ron          | J              | Sweeney      | M    |  3 | CT with contrast    | 
|  2 | PATIENT MF   | NULL           | TEST         | M    |  4 | DR                  | 
|  2 | PATIENT MF   | NULL           | TEST         | M    |  5 | CT without contrast | 
|  2 | PATIENT MF   | NULL           | TEST         | M    |  6 | MRI                 | 
|  2 | PATIENT MF   | NULL           | TEST         | M    |  7 | US                  | 
+----+--------------+----------------+--------------+------+----+---------------------+
7 rows in set (0.00 sec)
</pre>

Imported Issue. Original Details:
Jira Issue Key: MIRTH-75
Reporter: sween
Created: 2006-09-26T18:32:24.000-0700

**Comment by rbeckman-nextgen** [comment]
this seems to blow up even with a simple join of one of the selected JOINS. 

Do you have any sample channels utilizing a join?

Imported Comment. Original Details:
Author: sween
Created: 2006-09-27T16:07:05.000-0700

**Comment by rbeckman-nextgen** [comment]
I rolled back to version 1.0.3 with the same results as well...



Imported Comment. Original Details:
Author: sween
Created: 2006-09-30T19:08:56.000-0700

**Comment by rbeckman-nextgen** [comment]
I tested this with postgres (Mac OSX) and (Windows) too suspecting a driver/operating system/java issue with the same results... versions 1.1.0 and 1.0.3...



Imported Comment. Original Details:
Author: sween
Created: 2006-10-01T15:41:42.000-0700

**Comment by rbeckman-nextgen** [comment]
Fixed in 1.3.3

Imported Comment. Original Details:
Author: chrisl
Created: 2007-01-25T19:28:44.000-0800
