### ISSUE TITLE
Mirth 1.8 RC3 - could not prune message database

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#989]
Since I update from mirth 1.7.1 to mirth 1.8 RC3, mirth can't prune messages from database and I get this error in log.

[2008-11-24 06:00:00,031]  WARN  (com.webreach.mirth.plugins.messagepruner.MessagePrunerService:260): could not prune message database
com.webreach.mirth.server.controllers.ControllerException: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred while applying a parameter map.  
--- Check the Message.pruneMessages-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: java.sql.SQLException: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
Caused by: java.sql.SQLException: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.pruneMessages(DefaultMessageObjectController.java:372)
	at com.webreach.mirth.plugins.messagepruner.MessagePrunerService.execute(MessagePrunerService.java:245)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:529)Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred while applying a parameter map.  
--- Check the Message.pruneMessages-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: java.sql.SQLException: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
Caused by: java.sql.SQLException: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:91)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.update(SqlMapExecutorDelegate.java:505)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.delete(SqlMapExecutorDelegate.java:528)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.delete(SqlMapSessionImpl.java:98)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.delete(SqlMapClientImpl.java:75)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.pruneMessages(DefaultMessageObjectController.java:364)
	... 3 moreCaused by: java.sql.SQLException: This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2928)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1571)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1666)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:2994)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:936)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:773)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:81)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
	... 8 more

Imported Issue. Original Details:
Jira Issue Key: MIRTH-985
Reporter: omrubio
Created: 2008-11-24T04:06:20.000-0800

**Comment by rbeckman-nextgen** [comment]
Removed message pruning limit from mysql.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-11-26T18:07:11.000-0800

**Comment by rbeckman-nextgen** [comment]
Still get following error:

WARN  2008-12-01 13:20:02,406 [DefaultQuartzScheduler_Worker-1] com.webreach.mirth.plugins.messagepruner.MessagePrunerService: could not prune message database
com.webreach.mirth.server.controllers.ControllerException: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred while applying a parameter map.  
--- Check the Message.pruneMessages-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: java.sql.SQLException: You can't specify target table 'MESSAGE' for update in FROM clause
Caused by: java.sql.SQLException: You can't specify target table 'MESSAGE' for update in FROM clause
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.pruneMessages(DefaultMessageObjectController.java:387)
	at com.webreach.mirth.plugins.messagepruner.MessagePrunerService.execute(MessagePrunerService.java:245)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:529)
Caused by: com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred while applying a parameter map.  
--- Check the Message.pruneMessages-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: java.sql.SQLException: You can't specify target table 'MESSAGE' for update in FROM clause
Caused by: java.sql.SQLException: You can't specify target table 'MESSAGE' for update in FROM clause
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:91)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.update(SqlMapExecutorDelegate.java:505)
	at com.ibatis.sqlmap.engine.impl.SqlMapExecutorDelegate.delete(SqlMapExecutorDelegate.java:528)
	at com.ibatis.sqlmap.engine.impl.SqlMapSessionImpl.delete(SqlMapSessionImpl.java:98)
	at com.ibatis.sqlmap.engine.impl.SqlMapClientImpl.delete(SqlMapClientImpl.java:75)
	at com.webreach.mirth.server.controllers.DefaultMessageObjectController.pruneMessages(DefaultMessageObjectController.java:370)
	... 3 more
Caused by: java.sql.SQLException: You can't specify target table 'MESSAGE' for update in FROM clause
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2928)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1571)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1666)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:2994)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:936)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:773)
	at com.ibatis.sqlmap.engine.execution.SqlExecutor.executeUpdate(SqlExecutor.java:81)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.sqlExecuteUpdate(GeneralStatement.java:200)
	at com.ibatis.sqlmap.engine.mapping.statement.GeneralStatement.executeUpdate(GeneralStatement.java:78)
	... 8 more


For MySQL, you can't select from a table you're updating/deleting at the same time.  JOIN would be a workaround, but it can't be used due to the "messageFilterCriteria" in the message SqlMap.



Imported Comment. Original Details:
Author: chrisr
Created: 2008-12-01T14:32:03.000-0800

**Comment by rbeckman-nextgen** [comment]
removed the subquery.

Imported Comment. Original Details:
Author: chrisr
Created: 2008-12-01T17:37:14.000-0800

**Comment by rbeckman-nextgen** [comment]
thanks,
is this fix avaliable for download?

Imported Comment. Original Details:
Author: omrubio
Created: 2008-12-02T05:05:33.000-0800
