### ISSUE TITLE
SFTP Move To Functionality Is Now Broken

### ISSUE THREAD

**Issue by rbeckman-nextgen** [nextgenhealthcare/connect#992]
Using Move-To Directory/Move-to File Name is broken

To reproduce..

Import script and run against your favourite SFTP server.  Create one file named 1.test and then set appropriate path.

[2008-11-25 20:22:43,773]  ERROR (org.mule.impl.DefaultComponentExceptionStrategy:95): Caught exception in Exception Strategy for: 7ef9b7af-4716-4df9-b8bc-9ca3757a9626: org.mule.MuleException: Failed to move file "/home/ross/1.test" to "completed/1.test12276625637589".  The file already exists.
org.mule.MuleException: Failed to move file "/home/ross/1.test" to "completed/1.test12276625637589".  The file already exists.
	at com.webreach.mirth.connectors.file.FileMessageReceiver.processFile(FileMessageReceiver.java:263)
	at com.webreach.mirth.connectors.file.FileMessageReceiver.poll(FileMessageReceiver.java:124)
	at org.mule.providers.PollingMessageReceiver.run(PollingMessageReceiver.java:90)
	at org.mule.impl.work.WorkerContext.run(WorkerContext.java:290)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
	at edu.emory.mathcs.backport.java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
	at java.lang.Thread.run(Unknown Source)

<com.webreach.mirth.model.Channel>
  <id>7ef9b7af-4716-4df9-b8bc-9ca3757a9626</id>
  <name>test</name>
  <description></description>
  <enabled>true</enabled>
  <version>1.8.0.4014</version>
  <lastModified>
    <time>1227662517664</time>
    <timezone>America/New_York</timezone>
  </lastModified>
  <revision>10</revision>
  <sourceConnector>
    <name>sourceConnector</name>
    <properties>
      <property name="processBatchFiles">0</property>
      <property name="pollingFrequency">5000</property>
      <property name="scheme">sftp</property>
      <property name="directory"></property>
      <property name="moveToErrorDirectory">completed</property>
      <property name="password">XXXXXXXX</property>
      <property name="username">ross</property>
      <property name="moveToPattern">${ORIGINALNAME}${SYSTIME}${COUNT}</property>
      <property name="host">labs/home/ross</property>
      <property name="moveToDirectory">completed</property>
      <property name="binary">0</property>
      <property name="autoDelete">0</property>
      <property name="pollingType">interval</property>
      <property name="DataType">File Reader</property>
      <property name="FTPAnonymous">0</property>
      <property name="fileAge">0</property>
      <property name="checkFileAge">0</property>
      <property name="passive">1</property>
      <property name="charsetEncoding">DEFAULT_ENCODING</property>
      <property name="fileFilter">*.test</property>
      <property name="pollingTime">12:00 AM</property>
      <property name="validateConnections">1</property>
      <property name="sortAttribute">date</property>
    </properties>
    <transformer>
      <steps/>
      <inboundProtocol>DELIMITED</inboundProtocol>
      <outboundProtocol>XML</outboundProtocol>
    </transformer>
    <filter>
      <rules/>
    </filter>
    <transportName>File Reader</transportName>
    <mode>SOURCE</mode>
    <enabled>true</enabled>
  </sourceConnector>
  <destinationConnectors>
    <com.webreach.mirth.model.Connector>
      <name>Destination 1</name>
      <properties>
        <property name="outputAppend">1</property>
        <property name="FTPAnonymous">1</property>
        <property name="validateConnections">1</property>
        <property name="template">${message.rawData}</property>
        <property name="directory"></property>
        <property name="scheme">file</property>
        <property name="host">C:/temp</property>
        <property name="password">anonymous</property>
        <property name="outputPattern">${ORIGINALNAME}${SYSTIME}</property>
        <property name="DataType">File Writer</property>
        <property name="passive">1</property>
        <property name="charsetEncoding">DEFAULT_ENCODING</property>
        <property name="username">anonymous</property>
        <property name="binary">0</property>
      </properties>
      <transformer>
        <steps/>
        <inboundProtocol>XML</inboundProtocol>
        <outboundProtocol>XML</outboundProtocol>
      </transformer>
      <filter>
        <rules/>
      </filter>
      <transportName>File Writer</transportName>
      <mode>DESTINATION</mode>
      <enabled>true</enabled>
    </com.webreach.mirth.model.Connector>
  </destinationConnectors>
  <properties>
    <property name="synchronous">true</property>
    <property name="removeNamespace">true</property>
    <property name="encryptData">false</property>
    <property name="store_messages">true</property>
    <property name="dont_store_filtered">false</property>
    <property name="initialState">started</property>
    <property name="max_message_age">-1</property>
    <property name="transactional">false</property>
    <property name="error_messages_only">false</property>
  </properties>
  <preprocessingScript>// Modify the message variable below to pre process data
return message;</preprocessingScript>
  <postprocessingScript>// This script executes once after a message has been processed
return;</postprocessingScript>
  <deployScript>// This script executes once when the mule engine is started
// You only have access to the globalMap here to persist data
return;</deployScript>
  <shutdownScript>// This script executes once when the mule engine is stopped
// You only have access to the globalMap here to persist data
return;</shutdownScript>
</com.webreach.mirth.model.Channel>

Imported Issue. Original Details:
Jira Issue Key: MIRTH-988
Reporter: healthscreen
Created: 2008-11-25T18:27:37.000-0800

**Comment by rbeckman-nextgen** [comment]
Fixed in 1.8.0, but all paths used must be absolute paths from the root of the ftp or sftp server.  MIRTH-993 will add support of relative paths.

Imported Comment. Original Details:
Author: jacobb
Created: 2008-12-02T15:03:38.000-0800
